### ISSUE TITLE
Component/Action/Reducer command line generators

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#10]
https://medium.com/@yamalight/building-modular-javascript-applications-in-es6-with-react-webpack-and-babel-538189cd485f#.ujsh7hpzj

**Comment by mxstbr** [comment]
This seems like a good starting point: https://github.com/ironer/este-cli

**Comment by mxstbr** [comment]
This might be useful maybe https://github.com/tj/commander.js

**Comment by mxstbr** [comment]
https://github.com/FormidableLabs/generator-formidable-react-component/blob/master/app/index.js

**Comment by somus** [comment]
Can we use something like this? https://github.com/amwmedia/plop

**Comment by mxstbr** [comment]
That looks very promising, thanks for the link @somus! Have you worked with it before?

**Comment by somus** [comment]
I use this at work. If it is ok, I could do a PR.

**Comment by mxstbr** [comment]
@somus I'd love a PR for that! Could you do it against the `v3.0.0` branch? Thanks!

**Comment by somus** [comment]
Sure.

**Comment by mxstbr** [comment]
Done by the amazing @somus!
