### ISSUE TITLE
Change WebpackDevServer for Express? 

### ISSUE THREAD

**Issue by amorino** [mxstbr/react-boilerplate#100]
How about changing the development server from WebpackDevServer to Express? Similar to [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate), there's some [benefits in using this approach] (https://github.com/gaearon/react-transform-boilerplate#can-i-use-webpackdevserver-with-this).

**Comment by mxstbr** [comment]
Interesting approach, could I then take [the same server](https://github.com/gaearon/react-transform-boilerplate/blob/master/devServer.js) without the middleware and have a production ready server ready for deployment?

**Comment by amorino** [comment]
You mean use the boilerplate to create an universal app? Yes it will be possible. In fact, that is part of the benefits of using the express server but I believe that extend this boilerplate to make it universal is a lot of code to maintain. I'm not too familiar with universal apps, but you need different configurations for this to work as a deployable app.

That been said, I think that if people want to use this example for a universal app, the Express server will help.

**Comment by mxstbr** [comment]
I'm not currently interested in making this a universal app, as I have no experience with it. I'll look into switching the server to an express.js based one though, thanks for the hint!
