### ISSUE TITLE
Can't stop on breakpoints

### ISSUE THREAD

**Issue by edoloughlin** [mxstbr/react-boilerplate#1003]
Not much to add in addition to the title. Sourcemaps work and you can click to set a breakpoint but they're never hit. Chrome and FF.

**Comment by edoloughlin** [comment]
Using 'eval-source-map' improves things slightly, but it's still not perfect. I guess this isn't a react-boilerplate bug.

**Comment by mxstbr** [comment]
This is sadly a limitation of using source maps, I'm afraid 😢 I know the relevant people are aware of this and are working on it, but right now you have to choose between source maps or breakpoints.
