### ISSUE TITLE
User auth, Firebase, deployment

### ISSUE THREAD

**Issue by sedubois** [mxstbr/react-boilerplate#1009]
When assessing which boilerplate to start from, this project looks really great, except that it doesn't seem to provide any out-of-the-box user authentication, realtime database, and app deployment. https://github.com/este/este boilerplate provides all of them through Firebase. 

Is there a plan to add Firebase or something as good to react-boilerplate?

**Comment by mxstbr** [comment]
Integrating firebase with this boilerplate is trivial – their SDK is really easy to use.

We could put Firebase in the example app to showcase it, but other than that I don't see any possible point to make using Firebase with react-boilerplate easier. (ref: [Firebase docs](https://firebase.google.com/))

----

`este` has a totally different focus. We give you the best place to start your _webapp_ from, where `este` tries to have a good setup for apps that will be shared across Android, iOS, Extensions and web apps.

**Comment by sedubois** [comment]
Regardless of whether Este has a different focus, all webapps need to be deployed and they basically all involve users. So IMHO, showcasing Firebase and enabling people to deploy their user-aware app in a single command would be a huge plus 😊 I know that this project is for advanced users, but it shouldn't prevent providing the basic things. 

Handling users is far from trivial, even using Firebase. Authentication with proper redirections, forms for password reset, handle error cases, state management, reducers and routes to view the users, keep track of which user is online, store data with proper security rules, etc.

Even integrating Firebase itself is not trivial, involves proper handling of environment variables etc e.g with nconf, and there's quite some piping required to bind Firebase data to React/Redux.

(see [Este](https://github.com/belongapp/belong/tree/master/src/common/lib/redux-firebase))

NB: I don't know what you mean by Extensions.

**Comment by mxstbr** [comment]
> IMHO, showcasing Firebase and enabling people to deploy their user-aware app in a single command would be a huge plus 

Agreed, our current example isn't complex enough. Back when I originally envisioned it, we didn't have the `npm run clean` command, so each extra file of the example had to be manually deleted.

This isn't the case anymore, so I've been thinking about building a more complex app to showcase our stack better. I can't yet say if that involves Firebase, and I'm quite busy for the coming month, but a better example will arrive soon-ish! 

Thanks for kicking off this discussion!

**Comment by sedubois** [comment]
From my limited understanding, I guess the data alternative is Facebook's Relay/GraphQL (which would make sense for use with React), https://github.com/kriasoft/react-starter-kit.
