### ISSUE TITLE
appended !default selector invalidating css font-family rule

### ISSUE THREAD

**Issue by Kielan** [mxstbr/react-boilerplate#1012]
I have recently cloned a clean copy of a project based on this boilerplate but found that the font-family class css is invalidated due to !default being added to the font-family. In my css (utilizing postcss) there is no !default so I think this must be some issue with webpack compiling like this.

I'm comparing the new copy and checking the exact versions of webpack, webpack-dev-middleware, webpack-sources,  which are all the same. Is there any known reason why !default is being added like this?

<img width="268" alt="screen shot 2559-09-20 at 9 02 10 am" src="https://cloud.githubusercontent.com/assets/4452059/18720344/a3e9e98e-8055-11e6-957d-9b340550c06d.png">

Node v5.7.0
NPM v3.10.7
webpack v2.1.0-beta.20

Browsers: all.

possibly related issue #443

**Comment by mxstbr** [comment]
Must be something in our PostCSS pipeline – @ben-eb would know which part of it!

**Comment by ben-eb** [comment]
Try https://github.com/andywer/postcss-debug.

**Comment by Kielan** [comment]
I'm not sure how to use that tool @ben-eb and not seeing documentation for the C/LI.

I installed with `npm install -g postcss-debug `

is there a   .postcss.js file i should look for or point it at my .css files?

**Comment by ben-eb** [comment]
The documentation points to a simple configuration file. 😄

https://github.com/andywer/postcss-debug#cli

**Comment by Kielan** [comment]
my webpack options.postcssPlugins

`// Process the CSS with PostCSS
  postcssPlugins: [
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true,
    }),
],`

so I added

`module.exports = function (postcss) {
  return postcss([ calc, nested, cssnext, postcssReporter ]);
};`

However the output of the web debugger does not include this !default addition which I find in the element styles.

When looking at the source files I see at the top 

`exports = module.exports = require("./../../../node_modules/css-loader/lib/css-base.js")();
// imports
exports.i(require("-!./../../../node_modules/css-loader/index.js?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1!./../../../node_modules/postcss-loader/index.js!../shared/styles/colors.css"), undefined);

could this -! at the beginning of the file path be a problem with css-modules? Sort of a wild guess not sure about this -! in the search path.
