### ISSUE TITLE
route with param not work with production mode

### ISSUE THREAD

**Issue by hieubq-working** [mxstbr/react-boilerplate#1016]
Hi.
I have some probs while deploying in production mode with route contain param

I try setup route like this

`{
      path: '/home/:param',
      name: 'login',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/LoginPage'),
        ]);
        const renderRoute = loadModule(cb);
        importModules.then(([component]) => {
          renderRoute(component);
        });
        importModules.catch(errorLoading);
      },
    }`

- run with npm run start  or npm run start:production: OK
I open on url : "http://localhost:3000/home/param_value"

- deploy on surge.sh or (GO) caddy http server, nginx
I open on url : 
"http://localhost/home/param_value"
"http://domain.surge.sh/home/param_value"
I got 404 error, page not found

**Comment by gihrig** [comment]
Have seen [Server Config](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/server-configs.md) docs and sample [`/app/.nginx.conf`](https://github.com/mxstbr/react-boilerplate/blob/master/app/.nginx.conf) file?

**Comment by hieubq-working** [comment]
@gihrig Thank you!
