### ISSUE TITLE
Minified development version of React in production

### ISSUE THREAD

**Issue by tzusman** [mxstbr/react-boilerplate#1017]
> Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

How can I include the production react library during the `npm run build` process, but of course keep the dev build during development?

**Comment by andykenward** [comment]
`NODE_ENV=production` in the `npm run build` command should do this for you

see the "Note:" in
[https://facebook.github.io/react/downloads.html#npm](https://facebook.github.io/react/downloads.html#npm)

**Comment by mxstbr** [comment]
This should happen automatically! 😱 are you sure this doesn't happen?

**Comment by tzusman** [comment]
I changed a whole bunch of stuff around my repo, one of which was removing `NODE_ENV=production` from the package.json build line because I saw the `-p` flag on webpack.   Changed so many things today that I didn't associate that console warning to that removal.  Sorry guys!
