### ISSUE TITLE
Background image at styles

### ISSUE THREAD

**Issue by VadimuZz** [mxstbr/react-boilerplate#1018]
Hello! I'm very thankful for that great project. You are doing a amazing thing...

I can't figure out why the images attached to  `./styles.css` as backround is not appearing?

`background-image: url('./user-pic.png');`

![screenshot 2016-09-22 15 48 45](https://cloud.githubusercontent.com/assets/8515290/18748760/7097a4d6-80dc-11e6-9251-aaf77d09cbb2.png)

The image in root is exist...

![screenshot 2016-09-22 15 53 32](https://cloud.githubusercontent.com/assets/8515290/18748827/c7d51832-80dc-11e6-9c8c-5c9b06b8da32.png)

Could you explain me, how can I attach background image with right way (path)?

Thank you!

**Comment by gihrig** [comment]
This has been discussed in #370 and #144. I have not worked through that discussion, but if you find a solution a PR would be welcome.
