### ISSUE TITLE
Firebase not compatible

### ISSUE THREAD

**Issue by noquepoaqui** [mxstbr/react-boilerplate#1019]
I'm trying the 3.2.0 boilerplate version. Just cloned it and added firebase package. Whenever i try to npm run start, i get a browser error: ```Uncaught Error: Cannot find module "fs"```. It seems firebase is using dom-storage package and there seems to be some sort of incompatibility with webpack...

**Comment by gihrig** [comment]
You're right, Firebase has compatibility problems. More [here](https://groups.google.com/forum/#!topic/firebase-talk/gFtK1YoRUoE).

**Comment by siriwatknp** [comment]
I found the same issue, does anyone know how to fix this 
Uncaught Error: Cannot find module "fs"

**Comment by noquepoaqui** [comment]
I had to go back to older versions of react-boilerplate after messing up with 100 different dependencies problems because of this. I haven't tried any further since then...
