### ISSUE TITLE
Webpack crashing

### ISSUE THREAD

**Issue by VadimuZz** [mxstbr/react-boilerplate#1020]
Hi there.
I have the latest node and npm versions. And I can't build the project `npm run build`. 
Webpack is crashing. My log file is empty.
Maybe you have some thoughts on this.

![screenshot-2016-09-23-01 15 45](https://cloud.githubusercontent.com/assets/8515290/18768102/05fb282a-8134-11e6-8f55-7f2f56f9e19c.png)

Thank you!

**Comment by gihrig** [comment]
> node v4.5.0

I guess you mean "latest LTS"? I just ran a Travis build with Node 4.5.0, it's proven to work.

I'm not able to find the reference just now, but IIRC, `npm Exit status 2` is some internal error that has no meaningful description.

Some ideas:

1. Does the project work in dev mode e.g. `npm start` ?
2. Try remove `node_modules` folder, `npm cache clean`, `npm install`.

**Comment by amilajack** [comment]
We should add a list of installation debugging steps to help out. Should I make a PR for this?

**Comment by gihrig** [comment]
Yes, a troubleshooting docs page sounds like a great idea. Consider the distinction between the existing [FAQ](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md) and troubleshooting.
