### ISSUE TITLE
Do we have some product to show support on this project?

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#1021]
I just realize that this repo are now becoming so popular.
And i would love to show my support for this project.
Not sure if we have some souvenir and store for buying some stuff ?

I think i can contribute big lot of stickers if we have store.But i do need a logo to do so.

What do you guy think ? :)

**Comment by amilajack** [comment]
People already have the option to [back this project](https://opencollective.com/react-boilerplate?utm_campaign=react-boilerplate&utm_medium=github&utm_source=opencollective#support) but I dont disagree with having stickers.

**Comment by gihrig** [comment]
@chaintan17 before you get too busy creating stickers, check with @mxstbr. He has had some printed up, but I don't know of any for sale (cool idea though) 😄

**Comment by mxstbr** [comment]
I have ~400 stickers, if you DM me your address on twitter or via email to contact at my handle dot com I'll happily send you some asap!

Backing this project is also a great help, as is answering questions, submitting PRs and discussing. All of those are very much appreciated!
