### ISSUE TITLE
offline-plugin warning

### ISSUE THREAD

**Issue by sedubois** [mxstbr/react-boilerplate#1025]
## Steps to reproduce

- `npm start`
- open `localhost:3000` with developer console
- shows message `offline-plugin: runtime.install() was executed without OfflinePlugin being added to webpack.config.js. The installation of offline-plugin has not been performed. You can ignore this message if you are skipping the OfflinePlugin during development. Otherwise, you may have a configuration issue.`

# Versions

- Node/NPM: 6.2.2/3.9.5
- Browser: chrome 53.0.2785.116 (64-bit)

**Comment by andykenward** [comment]
This is not an issue. It is suppose to show that warning in development mode.

If you want the offline-plugin to work locally you have to run in production mode.

`npm run start:production`

As only the webpack production config `webpack.prod.babel.js` has the `offline-plugin` setup

see
https://github.com/mxstbr/react-boilerplate/blob/ae1a1584f564335b31332e755877a2df2329a2c5/internals/webpack/webpack.prod.babel.js#L72-L87

**Comment by sedubois** [comment]
OK. If there's an easy way to remove offline code completely in development mode and thus remove this warking, it would avoid confusing rewcomers.

**Comment by andykenward** [comment]
Could put a check for the `process.env.NODE_ENV === 'production'` around https://github.com/mxstbr/react-boilerplate/blob/0f88f55ed905f8432c3dd7b452d713df5fb76d8e/app/app.js#L126-L127


```
if (process.env.NODE_ENV === 'production') {
  require('offline-plugin/runtime').install();
}
```

But I find the warning log is pretty clear to me.

**Comment by NekR** [comment]
Well, it could be an `console.info` instead of `console.warn` though.

**Comment by mxstbr** [comment]
Why don't we have that check? It's a bit unnecessary to log that for every user, right?

**Comment by NekR** [comment]
Yeah. I think there is no sense for that warning in `react-boilerplate`. It's for users who just grabbed `offline-plugin` for their app and forgot to add to config. If it's preinstalled to a boilerplate -- warning doesn't make sense.

**Comment by mxstbr** [comment]
Would you mind to submit a PR adding that check from above so we don't have that warning everytime?

**Comment by tulanowski** [comment]
The warning is still present after `npm run clean`. I think that file inside internal/templates should be updated as well.

**Comment by gihrig** [comment]
@tulanowski Is this in current `dev` branch?

`internals/templates/app.js` contains this on line 114-116
```javascript
if (process.env.NODE_ENV === 'production') {
  require('offline-plugin/runtime').install(); // eslint-disable-line global-require
}
```

If yes (`dev` branch) could you dig deeper please?

**Comment by tulanowski** [comment]
No, I'm using master branch. `dev` branch looks good.

**Comment by gihrig** [comment]
Hopefully 3.4 will be released to `master` soon. #1322
