### ISSUE TITLE
Update webpack.base.babel.js in preparation for Webpack 2.1 release

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#1027]
Updating the webpack dependency beyond "2.1.0-beta.22" causes a build error:

> Invalid configuration object

This is due an evolutionary change in Webpack. It is not a bug.

More info is at  [webpack #3018](https://github.com/webpack/webpack/issues/3018).

There is mention of [PostCss problems](https://github.com/webpack/webpack/issues/3018#issuecomment-248378677) as well.

I don't have time to dig into this issue ATM, it would wonderful if someone could investigate and move this forward.

OS X 10.11.6
latest react-boilerplate `dev` branch.

To reproduce:
1. Update `package.json` `"webpack": "2.1.0-beta.22"` to `"webpack": "2.1.0-beta.25"`
2. Run any of the following in a new clone:
`npm run setup`
`npm install`
`npm run build:dll`

``` bash
Building the Webpack DLL...
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'progress'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           progress: ...
         }
       })
     }
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by veegee** [comment]
I pinned my webpack version to 2.1.0-beta.20 and it works. _Sigh..._

**Comment by oliverturner** [comment]
@gihrig Given the scale of the changes between beta.22 and beta.24 my recommendation would be to pin the dependency and wait for more stability - e.g. an `rc` release.

**Comment by peter-mouland** [comment]
the is a PR waiting to be merged for beta.25 https://github.com/mxstbr/react-boilerplate/pull/1032

**Comment by gihrig** [comment]
@mxstbr So, given that we both have reacted 👍 to @oliverturner's sentiment to 'leave well enough alone', shall we merge @peter-mouland's PR?

**Comment by mxstbr** [comment]
Done by the amazing @peter-mouland in #1032!
