### ISSUE TITLE
Update README with quickstart prereqs

### ISSUE THREAD

**Issue by toddsby** [mxstbr/react-boilerplate#1034]
quick start will fail if the minimum pre requirements are not met. (node v4+ and npm v3+)
These are currently missing from quick start steps.

**Comment by amilajack** [comment]
Does [the npmcheckversion script](https://github.com/mxstbr/react-boilerplate/blob/master/internals/scripts/npmcheckversion.js) not run?

**Comment by toddsby** [comment]
Doesn't even get that far! I believe npm 3 handles dependancies in a much more through manner. I got multiple dependency errors when using npm 2.5.0.  😵

**Comment by mxstbr** [comment]
Did you run `npm install` manually?

If you take a look at the setup instructions, it's `git clone` and then `npm run setup` – which should check that you have the correct version installed…

**Comment by toddsby** [comment]
@mxstbr I followed the quick start exactly. My system had node v0.10.26 and npm 2.50 when I ran `npm run setup`. This resulted in npm errors. I then used NVM to install node v4.50 and npm v3.10.8 after looking through the FAQ's in the docs mentioning > node v4 support.

**Comment by amilajack** [comment]
> This resulted in npm errors. I then used NVM to install node v4.50 and npm v3.10.8 after looking through the FAQ's in the docs mentioning > node v4 support.

Did you get the same error after doing this? I would recommend installing against latest npm and node versions (node 6.7.0)

After you `nvm install 6.7.0`, make sure to `npm i -g npm` to update to the latest node version (sometimes nvm doesn't install with it). After that, try this:

```
npm cache clean
rm -rf node_modules
npm i
npm rb
```
