### ISSUE TITLE
Change default branch to dev

### ISSUE THREAD

**Issue by sedubois** [mxstbr/react-boilerplate#1038]
As pull requests must be made against `dev` branch, maybe you could switch the default branch to `dev` so that this branch is pre-selected when creating pull requests.

https://help.github.com/articles/setting-the-default-branch/

**Comment by amilajack** [comment]
This is a good idea for contributors. Not sure if its good for ppl wanting to use the boilerplate

**Comment by sedubois** [comment]
Yes, I'm not sure if that also changes the branch used by `git clone`.

**Comment by gihrig** [comment]
My understanding is that changing default to dev means a git clone will default to dev branch, which kind of defeats the purpose of having a dev branch.

Anyone know if it's possible to have separate "default" branches for clone and PR? That _would_ be cool.

In the meantime, devs must pay attention to detail, but it's also easy to "Edit" a PR and change the base branch.

**Comment by mxstbr** [comment]
> My understanding is that changing default to dev means a git clone will default to dev branch, which kind of defeats the purpose of having a dev branch.

Same, this is why I haven't done it. For now we'll just need to edit the PR base branches manually, hopefully Github adds what we need someday!
