### ISSUE TITLE
Build failure & unable to import auth0-lock

### ISSUE THREAD

**Issue by georgelovegrove** [mxstbr/react-boilerplate#1042]
node and npm versions found in the first image, using an up to date Chrome version (though that should be irrelevant here).

cloned and npm run setup on the repo. After that I've been having trouble with adding auth0 to the boilerplate. I've whittled it down to the auth0-lock package and have the following issues after I have run 'npm install --save auth0-lock auth0-js' and added 'import Auth0Lock from 'auth0-lock'; // eslint-disable-line no-unused-vars' to any part in the application.

The npm run build error is as follows:

<img width="1132" alt="screen shot 2016-09-26 at 21 19 24" src="https://cloud.githubusercontent.com/assets/6073296/18850322/f0336284-842e-11e6-92aa-614b70aa9716.png">

The web console error when running npm start is as follows:

<img width="443" alt="screen shot 2016-09-26 at 21 14 23" src="https://cloud.githubusercontent.com/assets/6073296/18850332/fa46485e-842e-11e6-8255-f76acea929c1.png">

If anyone can install and import the auth0-lock npm package and it import correctly then would love to see a working repo and what I'm missing here?!

**Comment by sedubois** [comment]
In that last picture, did you expand the red arrow `Uncaught SyntaxError` to see the stack trace?

**Comment by georgelovegrove** [comment]
@sedubois thanks for the reply!! I've rewritten the question as I think the build if failing without auth0 in the first place for 'npm run build' without updating both react and eslint. The problem with using auth0 is still the same with that fixed though with the error messages shown above. May be easier to just try and add auth0 to your own clone of the repo to see?

**Comment by meilers** [comment]
Can you show what you have in npm-debug.log? I'm having a [very similar issue](https://github.com/mxstbr/react-boilerplate/issues/1045).

**Comment by georgelovegrove** [comment]
[npm-debug.txt](https://github.com/mxstbr/react-boilerplate/files/495950/npm-debug.txt)

Hey @meilers, Attached a txt file with the npm-debug log, feel it may be the case but can't pin point how to solve it.

**Comment by meilers** [comment]
[npm-debug.txt](https://github.com/mxstbr/react-boilerplate/files/496013/npm-debug.txt)

Here it is.

**Comment by marcelorl** [comment]
Same issue.
I'm getting this error:
`Uncaught SyntaxError: Unexpected token :`

I think it is related to babel compilation.


In Auth0 website, they provide a full example with es6 + react + auth0Lock, and it works fine. 
I have another project with same environment, and it works.

I'm moving that code to react-boilerplate and when I import Auth0Lock the console brings up this warning.

Any clue?

**Comment by sedubois** [comment]
Does this help https://github.com/mxstbr/react-boilerplate/pull/1108?

**Comment by marcelorl** [comment]
My point is, when I `import Auth0Lock from 'auth0-lock';` react-boilerplate brings me the error I mentioned before.

@sedubois Have you done anything special to import auth0-lock or you just did it?

Thanks.

**Comment by sedubois** [comment]
@marcelorl I just imported it and it all works well. You can clone the code shown in the other PR to check it out.

**Comment by jashmenn** [comment]
Okay @marcdel I fixed the bug we're seeing. What fixed it was adding `'browser'` to `'mainFields'` in `webpack.base.babel.js - This issue is actually fixed in https://github.com/mxstbr/react-boilerplate/pull/1054

Huge thanks to @sedubois for the example of how to use `auth0` and this boilerplate.

**Comment by marcdel** [comment]
@marcelorl ^^ 🙂

**Comment by Lknechtli** [comment]
I added `'browser'` to `webpack.base.babel.js`, and it doesn't appear to have solved the issue. Getting the same error as @marcelorl

**Comment by bnol** [comment]
@Lknechtli try to add `browser` to the **1st position** of `mainFields` and it will work :D
![image](https://cloud.githubusercontent.com/assets/1011106/20007923/03e28ce0-a2d1-11e6-9aac-1eac2417354f.png)
