### ISSUE TITLE
Question: What is the "proper" way to import 3rd-party javascript SW into the project?

### ISSUE THREAD

**Issue by Aeyos** [mxstbr/react-boilerplate#1043]
Hello! I've been wondering and tinkering with the webpack.*.js inside internals/webpack/ but was unable to figure out what's the "proper" way to include a 3rd-party software into the application. More specifically, I'd like to be able to use socket.io to handle my REST API requests since my app will require a websocket connection. Can someone help me figure this out?

As a bonus, I'd like to have the un-minified version in dev mode and pack it into a bundle for production.

Thanks in advance to anyone willing to help!

**Comment by Schubbcasten** [comment]
If you absolutely need to run scripts you can take a look at [script-loader](https://www.npmjs.com/package/script-loader)
But for your case there actually is a npm repository for the client side of socket.io: 
https://www.npmjs.com/package/socket.io-client

**Comment by Aeyos** [comment]
I think I figured it out and it works but I sincerely don't know why and an explanation would be great... What I did was import the module with

`import io from 'socket.io-client';`

and the io global became available. Does webpack automatically search for the imports when building the app and packs it nicely into a js?

**Comment by mxstbr** [comment]
> Does webpack automatically search for the imports when building the app and packs it nicely into a js?

Yes, that's the whole point of using a module bundler 😉

If you're not familiar with this type of technology yet, I highly encourage you to go through https://github.com/petehunt/webpack-howto before diving in – otherwise you're going to end up having a lot of pain down the line!

**Comment by Aeyos** [comment]
I'll surely look into informing myself more about webpack.

But, just for the record, using import like above (after build, in production server) gives me a "require error" on the console. The ~~newbie~~ solution was making an alias to the import on the **webpack.base.babel.js**
```javascript
resolve: {
  alias: {
    'socket.io-client': path.join('.', 'socket.io-client', 'socket.io.js'),
  },
}
```

I appreciate very much the all the help you guys gave me. Thanks!

**Comment by maurocolella** [comment]
Since `react-boilerplate` already has a loder for .js file (babel), I figured I'd include client-only script by testing, like **underscore**, for the availability of CommonJS.

What I did is:
 ~~~~
const clientScript = () => {
  if (typeof module !== 'undefined' && module.exports) {
    // client script goes here
  }
};

export default clientScript;
~~~~

I import this in my `App` container, and run it with the appropriate React lifecycle method.
