### ISSUE TITLE
Build failure & cannot import Firebase

### ISSUE THREAD

**Issue by meilers** [mxstbr/react-boilerplate#1045]
# React Boilerplate

## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

I've just started a project from scratch and added a dependency to [firebase](https://firebase.google.com/docs/web/setup). When I generate the build, it finishes with an error. Here's what I find in the npm-debug.log:

17 info lifecycle react-boilerplate@3.2.0~build: Failed to exec build script
18 verbose stack Error: react-boilerplate@3.2.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p`
18 verbose stack Exit status 2
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at EventEmitter.emit (events.js:185:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at ChildProcess.emit (events.js:185:7)
18 verbose stack     at maybeClose (internal/child_process.js:850:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

If I run `npn run start` and go to the Chrome browser, I see this in my console:

![screen shot 2016-09-27 at 10 09 50 am](https://cloud.githubusercontent.com/assets/2792041/18879600/e89c57a0-84a2-11e6-8faf-57cd6ff58735.png)

## Steps to reproduce

1. Clone the repo, setup and start a new project
2. Add a firebase dependency with: `npm install firebase --save`
3. Add initialization code in app.js:

const firebase = require('firebase');
const config = {
  apiKey: '<API_KEY>",
  authDomain: '<PROJECT_ID>.firebaseapp.com',
  databaseURL: 'https://<DATABASE_NAME>.firebaseio.com',
  storageBucket: '<BUCKET>.appspot.com',
};
firebase.initializeApp(config);

4. run `npm run build`

# Versions

- Node/NPM: v5.10.1/3.8.3
- Browser: Chrome Version 54.0.2824.0 dev (64-bit) on Mac OS 10.11.6

**Comment by georgelovegrove** [comment]
I've read about a similar thing, give this a try and tell me what happens:

Move the following code from webpack.test.babel.js to webpack.base.babel.js in a suitable place and then retry building it:

node: {
    fs: 'empty',
    child_process: 'empty',
    net: 'empty',
    tls: 'empty',
},

**Comment by meilers** [comment]
Found the culprit:
http://stackoverflow.com/questions/37311500/firebase-reference-is-empty-after-requiring-new-version

**Comment by srinivasdamam** [comment]
@georgelovegrove I tried, getting error
```js
assert.js?9281:160Uncaught TypeError: util.inherits is not a function

node: {
    console: true,
    fs: 'empty',
    child_process: 'empty',
    net: 'empty',
    tls: 'empty',
    dgram: 'empty',
    dns: 'empty',
  }

**Comment by siriwatknp** [comment]
@srinivasdamam I have the same error, still don't know how to fix it

**Comment by srinivasdamam** [comment]
try using require, it worked for me.
```js
const firebase = require('firebase/app'); //uhh, you have to import from firebase/app since webpack has some issues
//require modules you need
require('firebase/auth')
```
I hope this works, let me know.

**Comment by siriwatknp** [comment]
@srinivasdamam do you still add this in webpack
node: {
    console: true,
    fs: 'empty',
    child_process: 'empty',
    net: 'empty',
    tls: 'empty',
    dgram: 'empty',
    dns: 'empty',
  }

**Comment by srinivasdamam** [comment]
No when I import  using `require`

**Comment by siriwatknp** [comment]
@srinivasdamam Thanks for your advice, now it works !!!

**Comment by BearandYoon** [comment]
@siriwatknp 
I am trying to import firebase in my react project and followed your solution but when I call firebase.unauth() function, I got invalidkey error.
the key is correct.
This is my code.
```
/**
 * Combine all reducers in this file and export the combined reducers.
 * If we were to do this in store.js, reducers wouldn't be hot reloadable.
 */

import { fromJS } from 'immutable';
import { combineReducers } from 'redux-immutable';
import { LOCATION_CHANGE } from 'react-router-redux';

import Rebase from 're-base';
const firebase = require('firebase/app');
require('firebase/auth');
require('firebase/database');

import { firebaseConfig } from 'shared/constants';

import globalReducer from 'containers/App/reducer';
import languageProviderReducer from 'containers/LanguageProvider/reducer';

/*
 * routeReducer
 *
 * The reducer merges route location changes into our immutable state.
 * The change is necessitated by moving to react-router-redux@4
 *
 */

// Initial routing state
const routeInitialState = fromJS({
  locationBeforeTransitions: null,
});

/**
 * Merge route into the global application state
 */
function routeReducer(state = routeInitialState, action) {
  switch (action.type) {
    /* istanbul ignore next */
    case LOCATION_CHANGE:
      return state.merge({
        locationBeforeTransitions: action.payload,
      });
    default:
      return state;
  }
}

// Initial fireBase state
const fireBaseInitialState = fromJS({
  firebase: {},
});

let fireBaseBase = null;

function fireBaseReducer(state = fireBaseInitialState, action) {
  if (!fireBaseBase) {
    let app = firebase.initializeApp(firebaseConfig);
    fireBaseBase = Rebase.createClass(app);
  }
  return state
    .set('firebase', fireBaseBase);
}

/**
 * Creates the main reducer with the asynchronously loaded ones
 */
export default function createReducer(asyncReducers) {
  return combineReducers({
    route: routeReducer,
    global: globalReducer,
    language: languageProviderReducer,
    firebase: fireBaseReducer,
    ...asyncReducers,
  });
}
```

**Comment by SeunghunSunmoonLee** [comment]
I'm still having the issue even though I used 
```
const firebase = require('firebase/app');
require('firebase/auth');
require('firebase/database');
 
```
