### ISSUE TITLE
Unable to add rest.js dependency

### ISSUE THREAD

**Issue by lsanders** [mxstbr/react-boilerplate#1046]
# React Boilerplate

## Issue Type

- [x ] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

Unable to add [rest.js](https://github.com/cujojs/rest), perhaps due to webpack error?

## Steps to reproduce

You can easily reproduce by using the stock demo provided by the boilerplate

`npm install --save rest`

Then in `app/containers/HomePage/index.js` just add an import:
```
import rest from 'rest'; // eslint-disable-line 
```

Then, `npm run start`

Console log:

```
?d41d:9 Dynamic page loading failed TypeError: inherits is not a function(…)
index.js?2eeb:formatted:24Uncaught (in promise) TypeError: inherits is not a function(…)
```
(more trace below, but not sure how to proceded to debug?)

# Versions
- Node/NPM: v6.4.0
- Browser: Chrome 54.x

# More Details 

Clicking the top of the stack highlights the inherits line. (Mousing over the index.js?2eeb:formated tab suggests this is due to `webpack:///./~/stream-browserify/index.js` but I have no idea how to proceed from here:

![image](https://cloud.githubusercontent.com/assets/127957/18888306/598c2b1a-84bd-11e6-8217-39fe930a4cc5.png)

```

(anonymous function)	@	index.js?2eeb:formatted:24
319	@	1.chunk.js:formatted:57
__webpack_require__	@	main.js:620
fn	@	main.js:103
(anonymous function)	@	request.js?a434:1
361	@	1.chunk.js:formatted:286
__webpack_require__	@	main.js:620
fn	@	main.js:103
(anonymous function)	@	index.js?b982:3
341	@	1.chunk.js:formatted:179
__webpack_require__	@	main.js:620
fn	@	main.js:103
(anonymous function)	@	node.js?4483:17
(anonymous function)	@	node.js?4483:141
(anonymous function)	@	node.js?4483:143
(anonymous function)	@	node.js?4483:149
376	@	1.chunk.js:formatted:374
__webpack_require__	@	main.js:620
fn	@	main.js:103
(anonymous function)	@	node.js?f9e5:14
(anonymous function)	@	node.js?f9e5:20
(anonymous function)	@	node.js?f9e5:22
377	@	1.chunk.js:formatted:380
__webpack_require__	@	main.js:620
fn	@	main.js:103
(anonymous function)	@	VM108105:22
(anonymous function)	@	?d41d:165
304	@	1.chunk.js:formatted:6
__webpack_require__	@	main.js:620
fn	@	main.js:103
```

**Comment by mxstbr** [comment]
Oooh this is because we look for the `main` field in the `package.json` as the entry point for the dependency with webpack but need to use the `browser` field, if one exists!

Would appreciate a PR fixing this, the `resolve.packageMains` configuration is the one that needs adjustment!

**Comment by chaintng** [comment]
i think this can be closed
