### ISSUE TITLE
How to keep the boilerplate up-to-date?

### ISSUE THREAD

**Issue by tzusman** [mxstbr/react-boilerplate#1047]
I started my project a couple months ago with the react-boilerplate, but now I'm many many commits behind.  I've made several updates to the core of the project however, the biggest of which was probably less support, but there are several other smaller updates that were needed for my use case.

So my question is how do I keep up with the latest and greatest?  Since react-boilerplate's purpose is to be the latest and greatest, having an old snapshot of the boilerplate makes me a sad 🐼 

Would love to know how folks are solving this!

**Comment by gihrig** [comment]
Generally speaking, this is not a 'feature' of react boilerplate. It was discussed in #889, you may find some helpful ideas there.

**Comment by amilajack** [comment]
Maybe it would be a good idea to turn that information into documentation.

**Comment by tzusman** [comment]
@gihrig yep, definitely a question, not a feature request, although I suppose it could be.

I can imagine this project being "incrementally upgradable," but it would take a significant refactor.  I believe that it might be worth an investment of time in this endeavor since I'm going to be working on this project for at least 2 years, and I don't want to be constantly behind on the times, especially considering how fast the frontend environment is moving.

Could you guys/gals review this proposal?  Here are the major parts of the boilerplate that would need to be upgraded throughout the process:

- package.json: upgrading packages, removing packages, adding required packages
- server: personally I only use this in development, so I'm not going to focus on this
- internals: critical to being upgraded consistently
- generators: *maybe* these can be upgraded, but unlikely if the structure changes considerably

With regards to internals and package.json, I believe this could be accomplished by making the webpack configuration very modular.  Each module could have npm dependencies, and changes to them would accompany a migration.  Migrations could be accepted or rejected by the developer, and would do checks on the files to ensure that nothing is being disastrously overwritten.  Maybe in that case, it would show the diff and give the developer the option to apply the patch.

**Comment by mxstbr** [comment]
I think taking the `create-react-app` approach and having the build tools as a separate thing and dependency might be the solution to all of this. (see [this discussion](https://github.com/facebookincubator/create-react-app/issues/580) for some of the great points @gaearon made)

I'm convinced this is worth exploring, but I don't have the time at the moment to do so. (seems like quite a massive change too, would probably warrant bumping up to v4)
I'd love for somebody to research this a bit more and post their findings – let's open a separate issue for this and kick off the exploration!
