### ISSUE TITLE
What is sw.js ?

### ISSUE THREAD

**Issue by rangerch** [mxstbr/react-boilerplate#1048]
When I performed 'npm run build', A new file named sw.js appeared in build folder, but how to use this file?

**Comment by oliverturner** [comment]
You don't use it directly: it's the **S**ervice**W**orker generated by the Webpack Offline plugin. It handles caching, offline-first features, etc.

**Comment by avdeev** [comment]
@rangerch, you can remove it

https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/remove.md#removing-offline-access

**Comment by rangerch** [comment]
Thanks! @oliverturner  @avdeev
