### ISSUE TITLE
de.json not deleted after npm run clean

### ISSUE THREAD

**Issue by rubenmoya** [mxstbr/react-boilerplate#1050]
I just used `npm run clean` and  the file `/app/translations/de.json` is not being deleted, the `en.json` file is empty but the other one is still there, with the example app translations.

Probably adding `rm('/app/translations/de.json');` to `/internals/scripts/clean.js` would fix it. I could open a pull request if necessary.

Cheers.

**Comment by mxstbr** [comment]
Sounds reasonable, a PR would be appreciated!

**Comment by chaintng** [comment]
Closed. The fix have already merged.
