### ISSUE TITLE
npm run test -- --browsers Safari, test failed.

### ISSUE THREAD

**Issue by chaintng** [mxstbr/react-boilerplate#1053]
## Issue Type
- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
## Description

`npm run test -- --browsers Safari`
test failed.
## Steps to reproduce
1. Pull commit tag `v3.2.1`
2. `npm install`
3. `npm run test -- --browsers Safari`
4. Test failed. For example

```
    ✖ should render the IssueIcon
      Safari 9.1.2 (Mac OS X 10.11.6)
    [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
    See: http://formatjs.io/guides/runtime-environments/
```

**Comment by chaintng** [comment]
does any body else having this issue ?

**Comment by amilajack** [comment]
They seem to be working fine on travis

**Comment by gihrig** [comment]
@amilajack The Safari tests don't run on Travis (unless you are referring to a custom setup) see [travis.yml](https://github.com/mxstbr/react-boilerplate/blob/master/.travis.yml)

@chaintng I have no error running that command on latest `dev`. 68eef925e9c1a6593c6aead84e128f1cc8182fe6

**Comment by amilajack** [comment]
@gihrig I see. Was there a reason for only running the tests on linux?

**Comment by gihrig** [comment]
@amilajack I'm not the best one to answer that, but as you know ;-) , Tests have until recently only been run on a single version of node.

I believe the tests run in Chrome because it's the default/most common. If you can figure out how to run CI tests in all three officially supported browsers, I think that would be a worthy PR subject.

**Comment by chaintng** [comment]
May be because i'm still on Safari 9... El Capitan ?

**Comment by gihrig** [comment]
> May be because i'm still on Safari 9... El Capitan ?
Possibly, I had success (above) on 
Safari 10.0 (11602.1.50.0.10) 
OS X 10.11.6

In any case Safari 9 is only one rev back, I would expect it to work. Do you have access to another machine w/ Safari 10?

> [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
   
Isn't this the problem that was fixed in #790?

**Comment by mxstbr** [comment]
> Isn't this the problem that was fixed in #790?

This very much sounds like it. Are you on an old version of the boilerplate @chaintng?

**Comment by chaintng** [comment]
Yes, i'm on commit 3515b78
Safari version 9.1.2 😕

**Comment by mxstbr** [comment]
This will be irrelevant when we merge #980, so I'll close this issue. Feel free to discuss on though!

**Comment by mxstbr** [comment]
Just to note this, `npm run test:safari` isn't something fancy, it just runs Karma in Safari. If that doesn't work, that means the Karma Safari Adapter hasn't been updated to work with Safari 9 maybe, but that's not an issue with this boilerplate I'm pretty sure!
