### ISSUE TITLE
Sagas root template

### ISSUE THREAD

**Issue by avdeev** [mxstbr/react-boilerplate#1057]
Why you use this template in sagas

``` js
export function* getReposWatcher() {
  while (yield take(LOAD_REPOS)) {
    yield call(getRepos);
  }
}
```

instead takeEvery or takeLatest helpers?

**Comment by mxstbr** [comment]
Good point, we should definitely be using `fork(takeLatest, LOAD_REPOS, yourSaga)`! (back when those were written that wasn't around, and `while()` was still the default pattern)

Would appreciate a PR changing this!

**Comment by wedranb** [comment]
I currently have a large project using while(true) pattern, why would I change from while to fork(takeLatest, ..., ...) ? What are advantages?

**Comment by avdeev** [comment]
@wedranb, 
It's shorter, it's easier, it's a redux-saga style, easy to dispatch payload from action

**Comment by pgdejardin** [comment]
I've switched some sagas functions with `fork(takeLatest, LOAD_REPOS, yourSaga)` and I've noticed that sometimes for one action dispatched (only one logged in redux-dev-tools), there's multiple call of `yourSaga` function.

Does anyone got this ? I think i've missed something somewhere but can't see where.

**Comment by avdeev** [comment]
@pgdejardin You may cancel saga at root

```
export function* authWatcher() {
  yield fork(takeLatest, AUTH, auth);
}

export function* authRoot() {
  const watcher = yield fork(authWatcher);

  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}
```

**Comment by pgdejardin** [comment]
@avdeev @gkaran Oh yeah ! Tanks a lot !

I knew it was something like that but I don't know why I didn't thought to cancel the preview watcher...

Thank you =)

**Comment by mxstbr** [comment]
Fixed!
