### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by midcore-nam** [mxstbr/react-boilerplate#1059]
windows 10

![image](https://cloud.githubusercontent.com/assets/16084009/18955939/7b4ab22e-8627-11e6-8401-09211ab2cf86.png)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-boilerplate@3.2.1
6 info start react-boilerplate@3.2.1
7 verbose unsafe-perm in lifecycle true
8 info react-boilerplate@3.2.1 Failed to exec start script
9 verbose stack Error: react-boilerplate@3.2.1 start: `cross-env NODE_ENV=development node server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-boilerplate@3.2.1
11 verbose cwd C:\xampp\htdocs\react-boilerplate
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error react-boilerplate@3.2.1 start: `cross-env NODE_ENV=development node server`
17 error Exit status 1
18 error Failed at the react-boilerplate@3.2.1 start script 'cross-env NODE_ENV=development node server'.
18 error This is most likely a problem with the react-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env NODE_ENV=development node server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-boilerplate
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by mxstbr** [comment]
Can you try doing `npm install cross-env` and seeing if that fixes it?

**Comment by midcore-nam** [comment]
I did that and it shows different error:

$ npm start

> react-boilerplate@3.2.1 start C:\xampp\htdocs\react-boilerplate
> cross-env NODE_ENV=development node server

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\xampp\htdocs\react-boilerplate\server\index.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.1 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.2.1 start script 'cross-env NODE_ENV=development node server'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\react-boilerplate\npm-debug.log

**Comment by sedubois** [comment]
You need to first do `npm install`.

**Comment by midcore-nam** [comment]
already did from beginning.

**Comment by sedubois** [comment]
What was the result? Can you run it again? Then show `npm ls express`?

**Comment by midcore-nam** [comment]
I've tried to run npm run setup again and face this error:
![image](https://cloud.githubusercontent.com/assets/16084009/18956971/5a5527e4-862b-11e6-9ef1-46fdcd9e8b03.png)

**Comment by sedubois** [comment]
`npm run setup` is a destructive command, can only be run once. What matters is to run `npm install` properly.

**Comment by midcore-nam** [comment]
![image](https://cloud.githubusercontent.com/assets/16084009/18957060/a93f13d8-862b-11e6-9ee8-dbe0f18d2d41.png)

**Comment by midcore-nam** [comment]
$ npm install

> react-boilerplate@3.2.1 preinstall C:\xampp\htdocs\react-boilerplate
> npm run npmcheckversion


> react-boilerplate@3.2.1 npmcheckversion C:\xampp\htdocs\react-boilerplate
> node ./internals/scripts/npmcheckversion.js

C:\xampp\htdocs\react-boilerplate\internals\scripts\npmcheckversion.js:6
    throw new Error('[ERROR: React Boilerplate] You need npm version @>=3');
    ^

Error: [ERROR: React Boilerplate] You need npm version @>=3
    at C:\xampp\htdocs\react-boilerplate\internals\scripts\npmcheckversion.js:6:11
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "npmcheckversion"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.1 npmcheckversion: `node ./internals/scripts/npmcheckversion.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.2.1 npmcheckversion script 'node ./internals/scripts/npmcheckversion.js'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/npmcheckversion.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\react-boilerplate\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.1 preinstall: `npm run npmcheckversion`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.2.1 preinstall script 'npm run npmcheckversion'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run npmcheckversion
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\react-boilerplate\npm-debug.log

**Comment by sedubois** [comment]
Yes, you need an npm version >=3 😊

**Comment by midcore-nam** [comment]
lol...just saw that too

**Comment by midcore-nam** [comment]
awesome. Love it 💃
