### ISSUE TITLE
[Question] How to pass route parameters through to a saga ?

### ISSUE THREAD

**Issue by arthurCormack** [mxstbr/react-boilerplate#1063]
Imagine a scenario where you go to a page at the following route: 
`/posts/:postID` 
where postID is the id of a post that you want to get out of some json rest api, and then display in a container called `<SinglePost>`.
In the sagas.js for the SinglePost, we'll have something like:
```javascript
export function* getSinglePost(postID) {
  const someRestAPIURL = 'http://example.com';
  const requestURL = `${someRestAPIURL}/v1/getpost/${postID}`;
  const somePost = yield call(request, requestURL);
  if (!somePost.err) {
    console.log("!somePost.err");
    console.log(somePost);
    yield put(postDataLoaded(somePost.data, catSlug, postSlug));
  } else {
    console.log("somePost.err");
    yield put(postDataLoadingError(somePost.err));
  }
}
```
My question is this: what is the best way pass along the postID into to the saga.

I know this is basic, but I've been banging my head up agains various walls trying to figure it out to no avail. The clue fairy has not been kind to me today.

**Comment by mxstbr** [comment]
Thanks to `react-router-redux`, the current location is in the redux state!

Something like this should solve it:

```JS
import { select } from 'redux-saga/effects';
import { selectLocationState } from 'containers/App/selectors';

export function* getSinglePost(postID) {
  const state = yield select(selectLocationState());
  const postID = state.location…
  /* and so on */
}
```

**Comment by fazalrasel** [comment]
How about page reload/refresh? `locationBeforeTransitions` is `null` if I reload.

**Comment by Augustin82** [comment]
Yeah, we're having the exact same issue as @fazalrasel. Everything works fine when navigating from within the app, but when accessing the route directly (or after reloading), the info is gone.

@mxstbr any chance of reopening this issue, please? Thanks.

**Comment by flo-pereira** [comment]
may help : https://github.com/reactjs/reselect#accessing-react-props-in-selectors

**Comment by Augustin82** [comment]
@flo-pereira how so?

**Comment by flo-pereira** [comment]
sorry, misunderstand, but why don't you pass your needed routes parameters to your action ...
for exemple:

```
/* actionsCreator */
export const myAction = (routeParam) => ({ type: 'MY_ACTION', routeParam });
```

```
/* saga */
export function* mySaga({ routeParam }) {
  console.log(routeParam);
}

export function* myWatcher() {
  yield fork(takeLatest, 'MY_ACTION', mySaga);
}
```

```
dispatch(myAction(props.routeParams))
```

**Comment by Augustin82** [comment]
@flo-pereira 
Well, then you do what is done everywhere else: you do that dispatch in the cWM or cDM.

The point of redux-saga, or at least the point of the original poster of this thread, would be to just describe that, upon starting the saga (probably by injecting it at runtime when hitting the route), you would just go in the Redux store, get the params of the route, and do the dispatch from there.

**Comment by Darmikon** [comment]
I created root container for react router which dispatches router params to redux store. 
[router-redux-params](https://github.com/Darmikon/router-redux-params)
I can listen to `@@routerParams/URL_UPDATE` action in sagas. And also I can take router params from `store.routerParams.params` with saga API [select()](https://github.com/redux-saga/redux-saga/tree/master/docs/api#selectselector-args) in any moment

**Comment by rclai** [comment]
Has anyone addressed [the above comment](https://github.com/react-boilerplate/react-boilerplate/issues/1063#issuecomment-268664526)?

**Comment by developer239** [comment]
```
I can listen to @@routerParams/URL_UPDATE action in sagas. And also I can take router params from store.routerParams.params with saga API select() in any moment
```

Is this for real? What about testing? What about dependency injection? Why would you take the route from state? That seems extremely wrong to me. I hope that @flo-pereira 's solution work.

**Comment by Darmikon** [comment]
@flo-pereira 's solutions relies on the action which is dispatched from react component and therefore has direct access to react router params. This action can deliver this params to saga in payload. But in my case I tried to solve the problem when my sagas should react on actions which don't contain information in payload about router params. Such as async callbacks, cron operations etc.

**Comment by developer239** [comment]
I still don't believe that you should get state directly from sagas. How do you test generators with such a side effect?

**Comment by Darmikon** [comment]
I don't share your concerns regarding touching store within sagas.  Sagas have proper effect for this activity: [redux saga: select](https://redux-saga.js.org/docs/api/index.html#selectselector-args) . You can use it together with [reselect library](https://github.com/reactjs/reselect) to simplify your code. Here is [an example](https://stackoverflow.com/a/38408397)

**Comment by marutha** [comment]
Any ideas where I could take the url param value from,
So I have two routes
"/user/new" -> component form that creates new user
"/user/:id" -> component that shows the user information

the router.locationBeforeTransitions.pathname does contain the path, but again I have to parse it for id value and do my logic.

how should be my approach to above problem.

**Comment by Justin-Maxwell** [comment]
Re null location at startup:

see: https://github.com/react-boilerplate/react-boilerplate/issues/1380#issuecomment-297224781

**Comment by ReneCode** [comment]
I don't recomment to use the router. 
Focus on the question you have: 
Dispatch an action + parameter and get that parameter in the saga.
It's really simple, because you trigger your saga with:
' takeLatest(actionTypes.LOAD_PAGE_LIST, loadPageListSaga)'
and on the saga you get the hole action-object as a parameter:
'export function* loadPageListSaga(actionObject)'
