### ISSUE TITLE
pre-commit hook doesn't check all changes are staged

### ISSUE THREAD

**Issue by sedubois** [mxstbr/react-boilerplate#1064]
`pre-commit` will usefully run tests before committing, but doesn't check that it will commit *all* the changes in working copy. Some changes might not be in the index, and therefore will not be part of the commit.

**Comment by mxstbr** [comment]
How'd you mean It doesn't check all changes?

**Comment by sedubois** [comment]
@mxstbr I updated the description for more clarity.

**Comment by mxstbr** [comment]
cc @okonet, known issue?

**Comment by okonet** [comment]
@sedubois I still don't get it. `pre-commit` uses `lint-staged` that is in turn only lints staged files.

**Comment by sedubois** [comment]
@okonet apologies, I mixed up between linting and tests. Tests aren't run by `pre-commit` (although once they're fast enough, maybe they could).

**Comment by sedubois** [comment]
@okonet I think there's actually an issue:

- add a linting error in a CSS file, e.g remove newline at end of `app/containers/App/styles.css`
- `git add app/containers/App/styles.css`
- `npm run lint:staged`: gives an `Unexpected missing end-of-source newline` as expected
- undo the change, but don't stage it
- `npm run lint:staged`: doesn't give an error any more although index hasn't changed

**Comment by okonet** [comment]
1. Don't think this discussion should happen in this repository. Has nothing to do with the boilerplate.
1. Why do you run `npm run lint:staged` manually? It should be done in a pre-commit hook.
1. Lint-staged just runs linters for you on staged files by passing paths to them to the linters. You can find the source code here: https://github.com/okonet/lint-staged/tree/master/src

**Comment by sedubois** [comment]
1. I opened https://github.com/okonet/lint-staged/issues/62
2. that was to isolate the problem, but same issue occurs when committing (that's how I discovered it)
