### ISSUE TITLE
Discussion: Stripping/Detecting Unused Dependencies

### ISSUE THREAD

**Issue by amilajack** [mxstbr/react-boilerplate#1069]
JS world, we have literally hundreds (sometimes thousands) of dependencies. It would be help to know which ones are included in production or in our `package.json` but are not actually used.

[webpack-unused](https://github.com/latentflip/webpack-unused) can help with analyzing unused dependencies in bundles and [npm-check](https://github.com/dylang/npm-check) can help with removing unused dependencies from our `package.json`.

Thoughts?

**Comment by gihrig** [comment]
1. webpack-unused is in very early days
2. How much does it actually reduce the overall size of an RBP production build?

**Comment by amilajack** [comment]
Good points. I'll close this for now.
