### ISSUE TITLE
Automatically cache all files in the ServiceWorker

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#107]
With the chunking happening right now in `v3.0.0`, not all the files that are emitted by webpack get cached in the ServiceWorker.

We should use https://github.com/sporto/assets-webpack-plugin to emit a .json file that has a list of all files, which we can then cache using the ServiceWorker.

**Comment by mxstbr** [comment]
This looks incredible and like exactly what we need: https://github.com/NekR/offline-plugin

**Comment by NekR** [comment]
@mxstbr Yes, `offline-plugin` automatically adds everything emitted by webpack to ServiceWorker. Of course, you can configure it to add other files (not from webpack), like `index.html` for example.

**Comment by mxstbr** [comment]
@NekR thanks for the insights, I'll switch to `offline-plugin` soon! (Or maybe you want to submit a PR..?)

**Comment by NekR** [comment]
@mxstbr sure, will try find for that this week.

**Comment by mxstbr** [comment]
@NekR perfect, thank you!

<sup>*(I'm sure you know, please submit your PR against the `v3.0.0` branch)*</sup>

**Comment by NekR** [comment]
Hi @mxstbr, why this is needed https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/app/app.js#L11-L13? Is it some kind of hack for SW/AppCache? Not sure they those files need to be bundled into output JS file.

**Comment by mxstbr** [comment]
This does not bundle them. file-loader transfers them to the `build` folder, if we didn't `import` them like this they would stay in the `app` folder.

<sup>*See the [file-loader documentation](https://github.com/webpack/file-loader) for more info.*</sup>

**Comment by NekR** [comment]
@mxstbr yep, I missed that they are prefixed with file, my bad, sorry.

**Comment by mxstbr** [comment]
@NekR don't worry. :sparkles:

**Comment by mxstbr** [comment]
Done by #111 thanks to @NekR!

**Comment by dbhandel** [comment]
How do I regain access to port 3000 on my mac? It's like having a ghost in my machine, seeing mxstbr/react-boilerplate appear on localhost:3000 even though the repo is no longer on my machine. Am I supposed to download this repo again? Will that stop the older removed version from running?

**Comment by mxstbr** [comment]
In [`chrome://appcache-internals`](chrome://appcache-internals) & [`chrome://serviceworker-internals/`](chrome://serviceworker-internals/), delete `localhost:3000`.

**Comment by dbhandel** [comment]
Sorry to be so dense but could you explain the steps more fully? These are not bash commands, correct? I've tried to enter in the chrome browser bar "chrome://appcache-internals & chrome://serviceworker-internals/" ?? Also, will this solve the problem for FF and Safari?

**Comment by mxstbr** [comment]
1. You enter `chrome://appcache-internals` into your Chrome URL bar.

2. You find the entry saying `localhost:3000` and delete it. If it doesn't exist, you're good to go here.

3. You enter `chrome://serviceworker-internals/` into your Chrome URL bar.

4. You find the entry saying `localhost:3000` and delete it. If it doesn't exist, you're good to go here.

And then the problem is solved! I have no idea how to do this for Safari and FF to be honest. This entire problem is fixed in v3 and shouldn't happen anymore as soon as it's released!

**Comment by dbhandel** [comment]
Thanks Max. It worked. At least I'm free up in Chrome.

**Comment by mxstbr** [comment]
Perfect, glad it helped!
