### ISSUE TITLE
Why is `react/prefer-stateless-function` disabled?

### ISSUE THREAD

**Issue by amilajack** [mxstbr/react-boilerplate#1070]
In many places, it seems like the eslint rule `react/prefer-stateless-function` is disabled. What was the reasoning for this decision? Personally, I think stateless components is one of the best parts of react because it emphasizes how the UI is a pure function of the state.

**Comment by gihrig** [comment]
There is an issue with HMR working only with class based components. e.g. #590,  #684 and #821.

**Comment by amilajack** [comment]
I see.

**Comment by sedubois** [comment]
Shouldn't `react/prefer-stateless-function` be disabled in `package.json`?

**Comment by gihrig** [comment]
There's an update coming (don't recall which package) that's expected to fix this issue. Disabling in package.json might lead to forgetting about it, but an open issue is probably a better reminder.

ref: [react-ho-boilerplate (comment)](https://github.com/gaearon/react-hot-boilerplate/issues/97#issuecomment-249862775)
