### ISSUE TITLE
Child route renders the container of its parent

### ISSUE THREAD

**Issue by RvanderLaan** [mxstbr/react-boilerplate#1071]
## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

After adding a child route as described [here](https://github.com/mxstbr/react-boilerplate/blob/master/docs/js/routing.md#child-routes), the container specified in the parent of the child route route is rendered instead of the one specified in the child route. 

## Steps to reproduce

In the `routes.js` file, for example add a child route to the `/features` route:
```
...
    {
      path: '/features',
      name: 'features',
      getComponent(nextState, cb) {
        System.import('containers/FeaturePage')
          .then(loadModule(cb))
          .catch(errorLoading);
      },
      childRoutes: [
        {
          path: '/features/test',
          name: 'home2',
          getComponent(nextState, cb) {
            System.import('containers/HomePage')
              .then(loadModule(cb))
              .catch(errorLoading);
          },
        }
      ],
    }
...
```
Now, after running `npm start` the `/features/test` route should display the HomePage container, but instead its parent, the FeaturePage container, is rendered. The same thing happens when using the code from the [example from the documentation](https://github.com/mxstbr/react-boilerplate/blob/master/docs/js/routing.md#child-routes). 

I was able to reproduce this in both the master and dev branch, however I've seen other people using it so maybe I'm making a mistake somewhere.

**Comment by justingreenberg** [comment]
in the case of your example, you have to
 1. provide reducer/sagas for `HomePage`
 2. render `children` somewhere in `FeaturePage` container so RR has target for nested routes

```js
//...
    {
      path: '/features',
      name: 'features',
      getComponent(nextState, cb) {
        System.import('containers/FeaturePage')
          .then(loadModule(cb))
          .catch(errorLoading);
      },
      childRoutes: [
        {
          path: '/features/test',
          name: 'home2',
          getComponent(nextState, cb) {
            const importModules = Promise.all([
              System.import('containers/HomePage/reducer'),
              System.import('containers/HomePage/sagas'),
              System.import('containers/HomePage'),
            ]);

            const renderRoute = loadModule(cb);

            importModules.then(([reducer, sagas, component]) => {
              injectReducer('home', reducer.default);
              injectSagas(sagas.default);

              renderRoute(component);
            });

            importModules.catch(errorLoading);
          },
        }
      ],
    }
//...
```

somewhere in `FeaturePage` container...

```js
export class FeaturePage extends React.Component {
  //...
  render() {
    return (
      <div>
        {React.children.only(this.props.children)}
         //...
```

**Comment by RvanderLaan** [comment]
Ah, thanks! Number one was my bad. Should have known about number two, I see that the same happens in the index of the App container now that I know what it does. My mistake after all...
