### ISSUE TITLE
Nothing shown (white page) if JS is disabled

### ISSUE THREAD

**Issue by Vadorequest** [mxstbr/react-boilerplate#1073]
# Nothing shown (white page) if JS is disabled

## Issue Type

- [ ] Feature: Display a simple message in the demo telling that `If you're seeing this message, that means JavaScript has been disabled on your browser, please enable JS to make this app work.`

## Description

I ran into this issue because I use the options "disable javascript" when the console is opened. So, everything went fine at the start, because my console wasn't opened, but later then I got a white page and couldn't figure out why; that's because I had opened the console since.

I don't really know where is the best place to add such a message, but no doubt it may come handy for other developers. And maybe for users as well.

**Comment by gihrig** [comment]
As react-boilerplate is a Javascript heavy app (it even has _React_ in the name) it should be obvious that JS must be enabled. What may not be obvious, especially to the end user, is that JS is disabled in a particular browser, as in your case above.

I have not tried this, but I expect that adding a `<noscript>` tag to [index.html](https://github.com/mxstbr/react-boilerplate/blob/master/app/index.html) and its [template](https://github.com/mxstbr/react-boilerplate/blob/dev/internals/templates/index.html) would be the place to notify end users that JS is disabled and must be enabled to run the app.

If you are able to make this work with a clean and simple `<noscript>` tag, please consider opening a PR for that. It's a nice touch that could save a support call or two in production.

**Comment by Vadorequest** [comment]
@gihrig It works indeed using <noscript>.  I pushed a commit on my repo and I am about to make a PR. I should make it to the `dev` branch, right?

https://github.com/Vadorequest/react-boilerplate/commit/3fef0d5240f52636ff708e0be79c00c591c6de5b

I also fixed some indentation on the template, I don't know if that's something that should be part of the PR but it makes sense to me.

**Comment by gihrig** [comment]
>  I should make it to the dev branch, right? 

You got that right.

> I also fixed some indentation on the template

Yes, that's fine.

More at #1075

**Comment by gihrig** [comment]
Closing, handled in #1075
