### ISSUE TITLE
Sagas in app/containers/App folder

### ISSUE THREAD

**Issue by meilers** [mxstbr/react-boilerplate#1077]
I noticed that sagas get injected when you visit a specific route (and defined in the corresponding container). What should i do if I want a shared sagas file? For example, I want to integrate Firebase with authentication, but since authentication can happen anywhere, do I need to add the same logic to every sagas file of every container?

I was thinking of placing a sagas file in the "app/containers/App", but I'm not sure how to makethat work.

**Comment by jshumakerpruitt** [comment]
You can import and run your appSaga directly in `store.js`

```
  import appSaga from 'containers/App/sagas';

  ...

  const store = createStore(
    createReducer(),
    undefined,
    compose(...enhancers)
  );

  // Extensions

  //run saga from 'containers/App/sagas' here
  sagaMiddleware.run(appSaga);

  store.runSaga = sagaMiddleware.run;
  ...

```

**Comment by chaintng** [comment]
@meilers i think @jshumakerpruitt approach is a good call.
can i close this issue now ? do you still experience any issue ?
