### ISSUE TITLE
Components are getting unmounted when route change.

### ISSUE THREAD

**Issue by chaintng** [mxstbr/react-boilerplate#1078]
## Issue Type

[x] Question

## Description

When route change using `<Link>` or `browserHistory.push()` every component get unmounted. I'm not sure if it is default behaviour.
~~But the problem is when i want to route to the same page, but bind param (e.g.from `/user/` => ` /user?showModal=true`). All component should not get unmount/remount...~~ It won't unmount if it's under the same route.

## Steps to reproduce
1. clone repository
2. add below code in `HomePage/index.js`
```
  componentWillUnmount() {
    alert(1);
  }
```
3. run server, and click `Feature` button.
4. You can see the alert box, imply that it's being unmounted.

**Comment by sedubois** [comment]
> every component get unmounted

I guess this is due to the code splitting. See mxstbr's [post](http://blog.mxstbr.com/2016/01/react-apps-with-pages/) linked at top of [routes](https://github.com/mxstbr/react-boilerplate/blob/master/app/routes.js) file.

**Comment by chaintng** [comment]
should be. Thank you :) @sedubois

**Comment by avdeev** [comment]
I have the same behavior

On open first route i have

```
constructor
componentWillMount
componentDidMount
componentWillUnmount

constructor
componentWillMount
componentDidMount

componentWillReceiveProps
```

It's weird

**Comment by Dattaya** [comment]
Most likely it's a standard behavior (see https://github.com/ReactTraining/react-router/blob/master/docs/guides/ComponentLifecycle.md) unless you see WillUnmount while navigating and staying on the same route.
