### ISSUE TITLE
Closed issue #94 still affects me: port 3000 live with this repo after repo removed from my Mac

### ISSUE THREAD

**Issue by dbhandel** [mxstbr/react-boilerplate#108]
I tried updating to v3.0.0 to no avail. I have since removed all copies of the repo from my machine, emptied the trash, rebooted, do not have it running in my terminal, can't identify any processes for it but, it is still running on port 3000 and blocks any other use of that port. There is an endless stream of error messages in the console.
<img width="786" alt="screen shot 2016-01-20 at 6 48 17 am" src="https://cloud.githubusercontent.com/assets/1734740/12448411/cd188474-bf43-11e5-8e90-325ef1c15ed1.png">

<img width="464" alt="screen shot 2016-01-20 at 6 59 39 am" src="https://cloud.githubusercontent.com/assets/1734740/12448453/0ca1cb78-bf44-11e5-9f04-1a449f1e5a6b.png">

**Comment by mxstbr** [comment]
Confirmed, this is a bug and is being fixed by @NekR.

See #107 for more information. Closing this issue for now as a duplicate, thank you very much for submitting this!

**Comment by NekR** [comment]
Just a small quick note, `offlne-plugin` doesn't support `webpack-dev-server` at the moment and honestly, I do not see there much profit for it. I meant, it won't work with hot-reloading unless heavily coupled to React. It probably can work with iframe reloading, but I am sure there will be many edge cases. 

Anyway, I will try to dig into it today, maybe everything is simpler than I think. @mxstbr, what do you think here?

**Comment by mxstbr** [comment]
@NekR it shouldn't. It should only be enabled for production, if that answers the question.

**Comment by NekR** [comment]
@mxstbr Yep, this is what I always thought. Just had couple of issues opened where people complained about dev server.
