### ISSUE TITLE
Connection refused for HMR

### ISSUE THREAD

**Issue by maurocolella** [mxstbr/react-boilerplate#1082]
Hello, and thank you for the nice boilerplate.

I have a problem with HRM. On Ubuntu 16.04, probably Node 5.7 (installed with NVM). Actually:
- While I can run setup as a simple user, I have to sudo to actually run the application.

Sudo run start works fine, the boilerplate tells me that my code is running on 

> Localhost: http://localhost:3000

But when I update the code, with Atom, latest version, ES6 and Babel and React and  .. all linters and plugins, I get:

**GET http://localhost:3000/__webpack_hmr net::ERR_CONNECTION_REFUSED**

In my Chrome development tools.

**Comment by amilajack** [comment]
When you get:
```
GET http://localhost:3000/__webpack_hmr net::ERR_CONNECTION_REFUSED
```
do you see any errors in the `npm start` process?

**Comment by gihrig** [comment]
> While I can run setup as a simple user, I have to sudo to actually run the application.
Are you saying

`npm run setup` worked OK, but
`npm start` failed but then `sudo npm start` worked ?

If that's the case, my guess is you have a permissions problem. Are you installing under your `home/user` directory?

What do you see for owner and permissions for `build`, `app` and the project root?

**Comment by maurocolella** [comment]
I have installed node with `nvm`, but filesystem permissions shouldn't be affecting a `GET` request. I have no error on the console output on launch, and no further output during runtime - I'll copy my console output a little later, as well as more detailed logs.

I work on another project with that node configuration. One loosely based `react-starter-kit` and hot reloading works.

**Comment by maurocolella** [comment]
It's working.

What I did:
`sudo chown -R myuser:myuser ./*`

To make sure I had ownership of all files and dependencies in project.

Then `npm start` instead of `npm run start`

**Comment by gihrig** [comment]
Glad you got it working!
