### ISSUE TITLE
How can I add elmental ui css to the boilerplate ?

### ISSUE THREAD

**Issue by adai183** [mxstbr/react-boilerplate#1086]
My main problem seems to be that I can't add the elemental styles as global css.

**Comment by gihrig** [comment]
Did you see this in the [docs](https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/css-modules.md#integrating-global-css)?

**Comment by adai183** [comment]
yes. I excluded elemental from the dll build.
I also compiled the elemental less to css and added it after sanitize.css in app/app.js.

**Comment by adai183** [comment]
I solved my problem adding the css to `app/containers/App/index.js` like this:
`import '!style!css!../../styles/style.css';`
I am open to better solutions
