### ISSUE TITLE
How can I properly debug in react-boilerplate?

### ISSUE THREAD

**Issue by kossel** [mxstbr/react-boilerplate#1087]
I created some really simple functions, and I usually debug with chrome dev tool by either looking for the source (which with source map) or just add `debugger;` at the code and it will stop there.

but I think because of the lazy loading routes feature of the starter kit, I can't located the source in chrome dev tool, and with `debugger;` I just get an empty file. with
```
undefined


// WEBPACK FOOTER //
// 
```  

like the screenshot

![image](https://cloud.githubusercontent.com/assets/1760498/19243160/0e97e2a6-8edc-11e6-829b-ad4e06332087.png)

How to do debug?

**Comment by gihrig** [comment]
Does the build produce any errors in the terminal?

If not, you will have to undo your changes one at a time until things work, then compare the first change that breaks.

Frequent small git commits are highly recommended.

**Comment by kossel** [comment]
There's no error in the terminal, I just clean clone the project and happens the same :S,

![image](https://cloud.githubusercontent.com/assets/1760498/19248269/a2e7f8f2-8ef4-11e6-9026-40ce7d14313f.png)

to reproduce:
add  `debugger;` line to any valid js code, eg.  `util/request.js`  before line 11  
```
function parseJSON(response) {
  debugger;
  return response.json();
}
```

**Comment by gihrig** [comment]
You're right, I get exactly the same results with the `debugger` statement as you suggested.

I haven't used `debugger` statements with react-boilerplate, or any webpack based project, so I don't know what else to recommend.

Maybe [this](http://stackoverflow.com/questions/27626764/configure-webpack-to-allow-browser-debugging) SO entry will help.

**Comment by kossel** [comment]
Hmm I have always used either `debugger;` or breakpoints at `webpack://` and both they work great, I can see there is `devtool: 'cheap-module-eval-source-map',` in `webpack.dev.babel.js`.

perhaps looks like the source-map is not working or something else needs to be configure for lazy router because it just get a chunk of the app? how you guys debug  react-boilerplate?

**Comment by gihrig** [comment]
Try changing to `devtool: 'inline-source-map'`. Not sure that will work, but it's worth a try. See #881.

**Comment by GGAlanSmithee** [comment]
@gihrig, yeah `inline-source-map` should work. This is a long-standing issue with chrome sourcemap debugging, see https://github.com/webpack/webpack/issues/2145

**Comment by kossel** [comment]
Oh yeah, changed to `devtool: 'inline-source-map'` in  `webpack.dev.babel.js` and now it maps correctly to the source!

huge thanks to both.

**Comment by GGAlanSmithee** [comment]
@kossel one downside of `inline-source-map` is that it is slower than the `eval` ones. I do not know how much slower it is, it might be acceptable. Also important to keep in mind that it is a chrome bug causing the other maps to not work, so should eventually be fixed (I guess). Might be a good idea to document this though.

**Comment by kossel** [comment]
yeah I just read that it works, at cost of built time. :( I don't think it's a chrome bug, just tested at firefox same problem :s

**Comment by GGAlanSmithee** [comment]
> I don't think it's a chrome bug, just tested at firefox same problem :s

Interesting, I wonder what is causing it then? I thought it was a browser bug, judging by the conversation in the linked issue, but It's unlikely for the same bug to be in both browsers, so I guess the source-map is really broken.

**Comment by happy2share** [comment]
Changing to `devtool: 'source-map'` in `webpack.dev.babel.js` worked for me
