### ISSUE TITLE
NPM Install Issue 

### ISSUE THREAD

**Issue by joer14** [mxstbr/react-boilerplate#1089]
## Description

When cloning down my app, and attempting to `npm install` it on another machine I encounter errors.
Specifically, I currently I've been doing my development on a mac (Node 6.2.0/NPM 3.8.9). Now I'd like to deploy the app using the built in node server (behind Nginx) on a ubuntu 16. Any help would be greatly appreciated. 

## Steps to reproduce

1. Clone Down my repo (which is private unfortunately) but here is the [Package.json](https://gist.github.com/joer14/25f98d644a20c23247d2d1149d57db10)

2. I run `npm install` in the project folder.

I get the following error: 

```
Building the Webpack DLL...
Hash: d3c11d7538e2e5f835de
Version: webpack 2.1.0-beta.15
Time: 4096ms
                      Asset     Size  Chunks             Chunk Names
reactBoilerplateDeps.dll.js  3.51 MB       0  [emitted]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 3.17 MB [rendered]
  [775] dll reactBoilerplateDeps 12 bytes {0} [built]
     + 781 hidden modules

ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: /Users/joe/projects/tcpi/newFrontend/new2/tcpifrontend/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
| {"uChars":[128,165,169,178,184,216,226,235,238,244,248,251,253,258,276,284,300,325,329,334,364,463,465,467,469,471,473,475,477,506,594,610,712,716,730,930,938,962,970,1026,1104,1106,8209,8 (shortened for brevity) ]}
 @ ./~/iconv-lite/encodings/dbcs-data.js 99:37-76

```
3. Running `npm run build` fails on a different error which I think is related to the npm install not completing.

# Versions

- Node/NPM: v6.7.0/3.10.3 
- Browser: NA

**Comment by amilajack** [comment]
Did you make any changes to the boilerplate?

**Comment by joer14** [comment]
I didn't make any big changes to my knowledge. Only installed a few packages, added a proxy to the server script for API calls, and disabled linting.

**Comment by vimniky** [comment]
@joer14 `I didn't make any big changes to my knowledge. Only installed a few packages`.

I guess you have installed some packages that can't  be bundled by webpack. check out your package.json's dependencies field . All the package list the your package.json dependencies would be bundled into the dll bundle if you don't exclude them in the dllPlugin.exclude
```json

 "dllPlugin": {  
    "path": "node_modules/react-boilerplate-dlls",
    "exclude": [  // you can exclude packages here
      "chalk",
      "compression",
      "cross-env",
      "express",
      "ip",
      "minimist",
      "sanitize.css"
    ],
    "include": [
      "core-js",
      "lodash",
      "eventsource-polyfill"
    ]
  },
  "dependencies": {
    "babel-polyfill": "6.13.0",
    "chalk": "1.1.3",
    "cross-env": "2.0.1",
    "compression": "1.6.2",
    //...........
  },
```

**Comment by mxstbr** [comment]
As you can see webpack says

```
Module parse failed: /bla/node_modules/bla.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
```

This is telling you that webpack, for some reason, does not know how to handle `json` files. You will probably need to add some configuration to tell webpack to load `.json` files **in the `node_modules/` folder** with the `json-loader`.

**Comment by joer14** [comment]
@mxstbr thanks for boilerplate. As it turns out that error went away after excluding a package from the dllPlugin as was suggested by @vimniky. 

Thanks all for your help.
