### ISSUE TITLE
Fix public path

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#109]
When using nested `<Route>`s in your application using this boilerplate, as soon as you are two levels deep the browser won't find the necessary JS files anymore. The links in the `index.html` link to `bundle.js`, but when the URL is `yourdomain.com/sub/route` all those files 404 because the browser tries to get `yourdomain.com/sub/bundle.js` which doesn't exist.

----

This should be fixed by adding `publicPath: '/'` to the webpack config `output` variable.

*Tip: The webpack config is right [here](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/webpack/webpack.base.babel.js).*

----

Steps to do this:

- [ ] Claim this issue by commenting below
- [ ] Setup a local copy of react-boilerplate
    - [ ] Clone the repo with `git clone git@github.com:mxstbr/react-boilerplate`
    - [ ] Enter the newly created folder with `cd react-boilerplate`
    - [ ] **Go to the `v3.0.0` branch of this repo with `git checkout v3.0.0`**
    - [ ] Install the dependencies with `npm install`
- [ ] Fix the bug mentioned above
- [ ] Start a pull request
- [ ] Review
- [ ] Merge

**Feel free to ping me on [twitter](https://twitter.com/mxstbr) if you need any help/tips/pointers/are stuck!**

> Note: This feature is scheduled for v3 of this boilerplate, please don't forget to make your changes on the `v3.0.0` branch of this repo.

**Comment by AndrewIngram** [comment]
Will this help? https://developer.mozilla.org/en/docs/Web/HTML/Element/base

**Comment by mxstbr** [comment]
That might work, I like it! Do you want to give it a try?

**Comment by marr** [comment]
I am seeing this too. I tried using the latest `html-webpack-plugin` because there was a recent fix around module id's, https://github.com/ampedandwired/html-webpack-plugin/commit/b42074844ce22cfc711838317cc1907f92bd6e07 however the issue still exists.
