### ISSUE TITLE
How to add support for decorators?

### ISSUE THREAD

**Issue by meilers** [mxstbr/react-boilerplate#1096]
I'm trying to use [Facebook's library](https://www.npmjs.com/package/fb) and it uses [core-decorators](https://www.npmjs.com/package/core-decorators), which unfortunately requires Babel5.  According to [this thread](http://stackoverflow.com/questions/33801311/webpack-babel-6-es6-decorators), they suggest installing the [babel-plugin-transform-decorators-legacy plugin](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) and adding the plugin to Babel. Which I did (for dev & production):

"babel": {
    "presets": [
      [
        "es2015",
        {
          "modules": false
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-decorators-legacy",
          "transform-class-properties",
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      },
      "test": {
        "plugins": [
          "istanbul"
        ]
      },
      "development": {
        "plugins": [
          "transform-class-properties",
          "transform-decorators-legacy"
        ]
      }
    }
  }

However, I'm still getting the same error when I require the Facebook module:

`import { FB, FacebookApiException } from 'fb';`

![screen shot 2016-10-12 at 10 21 39 am](https://cloud.githubusercontent.com/assets/2792041/19313846/e8089582-9065-11e6-8a18-99ce09918906.png)

Am I missing something? Should I be adding the plugins to the webpack.dev.babel.js and webpack.prod.babel.js files too?

**Comment by sedubois** [comment]
You fixed this? What was your solution?

**Comment by meilers** [comment]
The problem wasn't actually the decorators, but with the library itself.

**Comment by jackywhlee** [comment]
@meilers  May I ask how you added `transform-decorators-legacy` for production?

I added it inside webpack.ev.babel.js and it works fine on dev, like this: 

```// Tell babel that we want to hot-reload
  babelQuery: {
    // require.resolve solves the issue of relative presets when dealing with
    // locally linked packages. This is an issue with babel and webpack.
    // See https://github.com/babel/babel-loader/issues/149 and
    // https://github.com/webpack/webpack/issues/1866
    plugins: ["transform-react-display-name", "transform-decorators-legacy"],
    presets: ['babel-preset-react-hmre'].map(require.resolve),
  },
```

But when I deploy my app onto production using npm run build, it breaks, with the following error:

```Module build failed: SyntaxError: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
```

I've tried installing the package without -dev, no luck.

**Comment by monkeydri** [comment]
Hello, I ran into the same problem when trying to use th epackage `fontkit` which uses decorators.

I installed `babel-plugin-transform-class-properties and babel-plugin-transform-decorators-legacy` as dev dependancies and added the plugins as you did in `package.json`, but I still get the same error (Module parse failed... Unexpected character '@') when running `npm run build:dll`.

Could anyone point me to the right direction for correctly adding those babel plugins ?
