### ISSUE TITLE
Use styled-components

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#1100]
Sooo, the reason I've been kinda quiet for the past weeks in this repo (sorry, back now!) is because I've been working on a new way to style react apps with @geelen that solves all the issues with other approaches!

It's called `styled-components`, and we just released it: https://github.com/styled-components/styled-components

It allows you to write 100% colocated (same file) CSS code in your Javascript, and it removes the mapping between styles and components. It's also fully ReactNative compatible.

We both use `styled-components` in some small-to-medium apps and it's been working perfectly for us.

I want to implement `styled-components` in react-boilerplate, but I might not have time for a few weeks (gotta catch up on all the issues here!), so if anybody wants to go ahead and submit a PR doing that I'd much appreciate it!

**Comment by samit4me** [comment]
They are both your projects, so this is a little daunting, but I'd <3 to have an attempt.

**Comment by samit4me** [comment]
@mxstbr Currently the `<A>` and `<ListItem>` components accept a `className` prop and when passed, they will use it instead of the default styling *(e.g. `className={props.className || styles.defaultStyle}`*. Did you want to retain this functionality? Or are you happy to convert over to the StyledComponents way of [overriding styles](https://github.com/styled-components/styled-components#overriding-component-styles)? 

Passing a `className` to a StyledComponent does work, but if a specific CSS property (e.g. `background-color`) is both, passed in via `className` and also defined in the StyledComponent, the StyledComponent will win.

In the example below `<div>` will have a green background. This should be fine, but I'm a little concerned that if people have used these example components in a real app they might have some problems if they are relying on this `className` prop to override the default styles?

Or is this a bug in StyledComponents, should the CSS properties sent via the `className` prop override any matching CSS properties in the StyledComponent?


```javascript
// StyledUpYo.js
const StyledUpYo = styled.div`background-color: green;`;
```
```javascript
// styles.css
.styledUpYo {
  background-color: red;
}
```
```javascript
import StyledUpYo from './StyledUpYo';
import styles from './styles.css';

const Contrived = (props) => (
  <StyledUpYo className={styles.styledUpYo}>
    {props.children}
  </StyledUpYo>
);
```

**Comment by mxstbr** [comment]
@geelen wrote that code, so I'm unsure if this is intended but it kinda sounds like a bug to me.

That being said, go ahead and implement it anyway and we'll either fix that and release a new version or it's fine – so don't let that hold you back!

**Comment by sedubois** [comment]
Does styled-components integrate well with server-side rendering?

**Comment by mxstbr** [comment]
Currently it works – it's not the best yet, though that will change very soon with the [babel transform we're working on](https://github.com/styled-components/styled-components/issues/59)! That shouldn't be the blocker for integrating it 😊

**Comment by samit4me** [comment]
@mxstbr Is there any chance you could apply the label "Hacktoberfest", I'm keen to get a [free Tshirt](https://hacktoberfest.digitalocean.com/) :)

Also, it seems that Appveyor CI failed due to a timeout. Is there a way to re-run this?

**Comment by AOHUA** [comment]
Just want to know why styled-components is a better approach compare to CSS Modules.

**Comment by sedubois** [comment]
@mxstbr how does styled-components compare with Khan Academy's new [Aphrodite](https://github.com/Khan/aphrodite)? (I saw [it](https://twitter.com/jlfwong/status/789566897213747200) retweeted by [reactjs](https://twitter.com/reactjs) today) For example, it apparently supports server rendering.
A comparison table could be great 😊

**Comment by mxstbr** [comment]
Aphrodite has been around for a long time, and there are only 3 commits between 0.6 (the release I know) and 1.0 (which was retweeted by @reactjs) – so not a lot of changes.

To see a direct comparison between those two go to https://github.com/styled-components/comparison, this is the summary of my experiences from that repo:

![](https://pbs.twimg.com/media/Cvg-GKRXEAAsSS4.jpg:large)

*We in fact started the exploration towards styled-components because we were unhappy with how aphrodite makes making third party component libraries almost impossible, doesn't support nesting and a bunch of other stuff*

**Comment by sedubois** [comment]
@mxstbr Perfect, thanks 😊

**Comment by mydearxym** [comment]
@mxstbr  what's your opinion about [glamor](https://github.com/threepointone/glamor) which is used by [next.js](https://github.com/zeit/next.js) ?

**Comment by sedubois** [comment]
@mydearxym glamor is in styled-components' dependencies

**Comment by mxstbr** [comment]
Glamor is great, Sunil is amazing!

He's been helping us a lot building styled-components, and in fact we're blatantly using his injection mechanism. At this point, I believe styled-components has the better API that enforces best practices in component systems (more about this in a talk soon), but I'm excited to see where Sunil takes glamor!

**Comment by crazymunky** [comment]
I started using styled-components in a existing project based on this repo and its amazing. Really easy to build dynamic styles.
Would love to help implementing it, what would be the objective? Replace the current tooling setup?

**Comment by mxstbr** [comment]
Done by the amazing @samit4me in #1110!

**Comment by KarandikarMihir** [comment]
Does it mean that we can't use normal css files in this boilerplate? We have a project which uses earlier version of this boilerplate. Is it going to be painful to upgrade to the latest version?

**Comment by crazymunky** [comment]
If you have both dependencies you can use it on a per component basis. You can even use both to extend functionality.

**Comment by mxstbr** [comment]
You are totally fine just sticking with CSS Modules @KarandikarMihir! It's not like they don't work anymore 😉

**Comment by acjay** [comment]
Question -- what is meant by "No wrappers"? I looked at the example code for Aphrodite and styled-components, but couldn't figure it out. Is this to do with the generated output or with the process of using the library?

**Comment by mxstbr** [comment]
@acjay no wrappers means that some libraries don't generate wrapper components that you see in the React DevTools, like e.g. aphrodite. Compare that to the DevTools when using Radium, and you'll know what I mean :blush:
