### ISSUE TITLE
Is there a reason why in the sample project you use button for creating A Tag ?

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1101]
# React Boilerplate

## Description

I am trying to implement Pages routing. I have followed the example in your sample app, but it appear that you use button only. 

I was surprise to see that you can also render a A tag with Button if you don't use `props.handleRoute` , this is pretty confusing because the components name is Button.

Also, the A components doesn't seems to handle route, so I wanted to know if it's a common practice in react world or if it's just a personal proposition for the sample case ?

**Comment by mxstbr** [comment]
> if it's just a personal proposition for the sample case ?

Just happened that way, it doesn't reflect any common practice at all. We'll be building a new, more complex example app with updated best practices built in as soon as I find a few free days to actually do it!
