### ISSUE TITLE
Integrating with redux-auth-wrapper and saga-login-flow

### ISSUE THREAD

**Issue by williamgranli** [mxstbr/react-boilerplate#1105]
I'm trying to integrate this boilerplate with https://github.com/mjrussell/redux-auth-wrapper and https://github.com/sotojuan/saga-login-flow. 

Everything related to redux-auth-wrapper is working, and the basic logic and components from saga-login-flow are integrated BUT for some reason the sagas won't listen to events. 

Here's a repo with my modifications to the boilerplate. All the auth stuff is in the User component. 
https://github.com/williamgranli/react_auth 

I'm quite new to react/redux and very new to sagas, so I have no idea how to check if the sagas are getting injected/connected the right way. I've tried printing the sagas object in asyncInjectors but I can't read out any useful info from there to help me determine if the saga from the User component is active or not. 

Right now the code is a bit messy and contains a lot of linting errors since saga-login-flow isn't linted... If I can get everything to work I'm planning to share the code so people can get an idea of how to integrate these three libs. 

Any pointers or help would be MUCH appreciated.

**Comment by aldaty** [comment]
I cloned your repo to check it out, but you seem to have npm installed some things without adding them to package.json, so it won't run.

I quickly looked in your routes.js, and you don't load the User component's sagas in any route - that is probably why it doesn't work - this boilerplate loads sagas and components asynchronously, and it needs to know which ones to load specifically for any route.

As for testing whether a saga has been injected, you could just add a saga that logs something to the console, no need to meddle with asyncInjectors. If it's injected, it will run. To check that the redux-saga middleware is working, you could just put() any action in a saga and use the redux browser extension to see if it was dispatched. 

I hope this helps at least a little bit.

**Comment by williamgranli** [comment]
@aldaty I've pushed a fix for the missing package... sorry about that. 

So you're saying only components which are connected to a route will have sagas injected? The way I have it set up now is I have containers for each page related to auth, e.g. LoginPage and these import actions from the User component which handles everything related to auth. Do you suggest I move the sagas/actions/reducer to the LoginPage components since it's connected to a route?

**Comment by aldaty** [comment]
If you want the sagas and store from a component, what you need to load in a given route is not the entire component itself, but the sagas and reducers from it. You can do this without using the actual component anywhere in the route itself. Examples of how to do this are already in your routes.js file - basically you System.import the saga and reducer files, and then inject them using the asyncInjector functions. Since you don't need to connect the User component to a route in order to use its sagas and store, moving the sagas and store would be unnecessary work.

**Comment by williamgranli** [comment]
@aldaty Ahh I see. Just got it working with changing the injects for saga+reducer for my LoginPage. Thanks a LOT!!!

How should I structure it around the fact that many containers/components (e.g. login/register/logout components) will need to use my User/Auth component? Do I just need to inject the reducer/saga once and import the action creators from wherever I need them? Or does every component/route which uses the saga/reducer from User need to import them?

**Comment by aldaty** [comment]
The issue of structuring an app around parts of the store which multiple pages depend on is something I struggle with myself and I think an open problem in general, so I really wouldn't feel comfortable giving advice on it. I only started using react and this boilerplate about 3 weeks ago myself. I am happy to have been of some help at least.

**Comment by samit4me** [comment]
@williamgranli It appears that @aldaty has resolved the issue you raised, so I hope you don't mind me closing this!

**Comment by tblazina** [comment]
@williamgranli Could you please share how you've implemented these two together? I'm trying to do this at the moment and any example would be great to see!

**Comment by williamgranli** [comment]
@tblazina I've gotten it to work, but because of a rushed deadline all the code is in quite bad shape. I'll post what I have sometime tomorrow morning EU time.

**Comment by williamgranli** [comment]
**In app/routes.js:** 
Components are loaded like this. First example is non-protected (login) route and second (dashboard is protected. 
```
	{
      path: '/login',
      name: 'loginPage',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/LoginPage/reducer'),
          System.import('containers/LoginPage/sagas'),
          System.import('containers/LoginPage'),
        ]);

        const renderRoute = loadModule(cb, null);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('loginPage', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
         path: '/dashboard',
      name: 'dashboardPage',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/DashboardPage/reducer'),
          System.import('containers/DashboardPage/sagas'),
          System.import('containers/DashboardPage'),
        ]);

        const renderRoute = loadModule(cb, Auth);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('dashboardPage', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
```

loadModule modified like so:
```
const loadModule = (cb, hoc = null) => (componentModule) => {
  if (hoc) cb(null, hoc(componentModule.default));
  else cb(null, componentModule.default);
};
```

UserAuthWrapper config like so: 
```
import { UserAuthWrapper } from 'redux-auth-wrapper';
// Redirects to /login by default
const Auth = UserAuthWrapper({ // eslint-disable-line new-cap
  // how to get the user state
  authSelector: state => state.get('loginPage'), // eslint-disable-line no-unused-vars
  predicate: user => user.loggedIn, // eslint-disable-line no-unused-vars
  redirectAction: routerActions.replace, // the redux action to dispatch for redirect
  wrapperDisplayName: 'UserIsAuthenticated', // a nice name for this auth check
});
```

**LoginPage container:** 

```
  componentWillMount() {
    const { changeRoute, redirect } = this.props;
    let { isAuthenticated } = this.props;
    isAuthenticated = isAuthenticated.loggedIn;
    if (Object.keys(isAuthenticated).length === 0 && isAuthenticated.constructor === Object) {
      isAuthenticated = null;
    }
    if (isAuthenticated) changeRoute(redirect);
  }

  componentWillReceiveProps(nextProps) {
    const { isAuthenticated, changeRoute, redirect } = nextProps;
    let { isAuthenticated: wasAuthenticated } = this.props;
    const one = wasAuthenticated.loggedIn;
    const two = isAuthenticated.loggedIn;
    if (Object.keys(wasAuthenticated).length === 0 && wasAuthenticated.constructor === Object) {
      wasAuthenticated = null;
    }
    if (!one && two) changeRoute(redirect);
  }
```


```
function mapDispatchToProps(dispatch) {
  return {
    changeRoute: (url) => dispatch(push(url)),
  };
}
```

The sagas which are triggered onClick on the login button are implemented with a lot of copy/paste from https://github.com/sotojuan/saga-login-flow/tree/master/app.

As I said, a lot of the code is in bade shape and most of the variable names don't make sense, but it should work at least. Let me know if you run in to any problems @tblazina .

**Comment by tblazina** [comment]
@williamgranli  

Cheers thanks for great input, it turns out in the end that I can do all the authentication without problems using the saga-login flow as a template. Like you I am under pressure with a deadline at work so kind of used what works but I'll eventually try to implement the wrapper as well, so thanks a lot!

**Comment by andrewvmail** [comment]
@williamgranli Just wondering if you have the mashup with everything, the old repo you got at the top of this page doesn't work anymore. It was a good reference for me . Cheers!

**Comment by xmanjack** [comment]
@williamgranli I am wondering if you still have https://github.com/williamgranli/react_auth on github?
