### ISSUE TITLE
How to enable source map in dev with chrome

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1112]
## Issue Type

- [ x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Using v3, 

I don't have any sourcemaps generated, I have tried to swap in the dev webpack configuration:

      //devtool: 'cheap-module-eval-source-map',
      devtool: 'inline-source-map',

there are also opened issues, all are related to different stack of technology:

- https://github.com/mxstbr/react-boilerplate/issues/132
- https://github.com/webpack/style-loader/pull/96
- https://github.com/webpack/webpack/issues/2145

So just to make it clear:

**Comment by simobasso** [comment]
@mxstbr says in #132:
> Done in 1e87379!
 
and with google-chrome:latest works.

@mxstbr any plan to release?

**Comment by kopax** [comment]
@simobasso are you telling us that 1e873789 hasn't been published yet on master branch ? Or do you mean it's already supposed to work? Because It's not working for me.

I have pulled from master mxstbr/react-boilerplate/internals/webpack/webpack.dev.babel.js:

     + devtool: "cheap-module-eval-source-map"

instead of this settings

    -  devtool: 'inline-source-map'

Has I have said before, I have tried to use both `inline-source-map` and `cheap-module-eval-source-map` (current value on master) as well, both doesn't enable debugging in chrome.

I am using google chrome on Debian 8 : Version 53.0.2785.143 (64-bit)

**Comment by simobasso** [comment]
@kopax using `devtool: 'inline-source-map'` with chrome on OSX it's work as expected:
![schermata 2016-10-19 alle 14 19 17](https://cloud.githubusercontent.com/assets/4202614/19518362/24c4f49c-9607-11e6-9591-7c42f87ac5b5.png)

> @simobasso are you telling us that 1e87379 hasn't been published yet on master branch ?

actually it's not in master:
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L49

> I am using Google chrome on Debian 8 : Version 53.0.2785.143 (64-bit)

the latest version of chrome is: `54.0.2840.59 (64-bit)`

I'll try later on Debian.

**Comment by kopax** [comment]
I have downloaded chrome from their website and reinstalled it.

     $ wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
     $ sudo dpkg -i google-chrome-stable_current_amd64.deb

Current version is : Version 53.0.2785.143 (64-bit)

Please note that for debian : 

    Google Chrome
    Copyright 2016 Google Inc. All rights reserved.
    Google Chrome is made possible by the Chromium open source project and other open source software.
    Google Chrome Terms of Service

Which means the original linux project is Chromium. I am not using chromium but chrome downloaded from their website. I'll try later with chromium

**Comment by redwind** [comment]
i face same problem, many thanks to you
