### ISSUE TITLE
immutable.js update all the states

### ISSUE THREAD

**Issue by tinybug** [mxstbr/react-boilerplate#1116]
When I change the name, all the state in redux will be updated, it will cause all the components which connect to redux render again. Just like the following picture, you will see it when you check the `Trace React Updates` in react devtool, all the components were rendered again. Is that reasonable?

<img width="828" alt="657faf8b-fad8-4d18-8cf1-27a4baed905b" src="https://cloud.githubusercontent.com/assets/3439875/19436542/5222703c-94a3-11e6-8f9d-b6b5f57d90ab.png">

**Comment by mxstbr** [comment]
That's just how redux and react work. If you want to opt-out of updates for a specific component, you'll have to add a `shouldComponentUpdate` method!

**Comment by tinybug** [comment]
@mxstbr I don't think it's a good practice to use react and redux in this way. It will contribute to  react virtual DOM deep compare inside. If there are tons of states in redux, react will compare all of the element to decide wether the DOM element should rerender. Is that will not cause app slow? Why not just return a new object relate the component and combine shouldComponentUpdate to reduce react compare inside?

**Comment by tinybug** [comment]
@mxstbr Maybe I have some misunderstanding in immutable.js, I should pass the map object instead of the toJS() object to react, and then shallow compare the map object in shouldComponentUpdate. Thanks!😀

**Comment by mxstbr** [comment]
That's exactly it @tinybug, sorry for not being more explicit!

**Comment by janjachacz** [comment]
Have a look at [react-immutable-render-mixin](https://github.com/jurassix/react-immutable-render-mixin) as FB's shallowEqual doesn't compare well immutables from immutablejs and Immutable.is() won't work with plain obj.

```javascript
import shallowEqual from 'fbjs/lib/shallowEqual';
import Immutable, { fromJS } from 'immutable';
import { shallowEqualImmutable } from 'react-immutable-render-mixin';

const objA = { a: 1 };
const objB = { a: 1 };
const immA = fromJS(objA);
const immB = fromJS(objB);

console.log('shallowEqual', shallowEqual(objA, objB), shallowEqual(immA, immB));
// ==> shallowEqual true false
console.log('Immutable', Immutable.is(objA, objB), Immutable.is(immA, immB));
// ==> Immutable false true
console.log('shallowEqualImmutable', shallowEqualImmutable(objA, objB), shallowEqualImmutable(immA, immB));
// ==> shallowEqualImmutable true true

```
