### ISSUE TITLE
WebpackDevServer breaks on complex nested routes

### ISSUE THREAD

**Issue by jongold** [mxstbr/react-boilerplate#113]
Was running into this for a few days (on master & since upgrading to 3.0.0)

I had some routes like
`/releases`
`/releases/:version`

My `:version` param takes a semver number, like `1.2.3`.

They work perfectly when navigating around the app using `<Link />` etc, and `/releases` works when hard-refreshing the page, but hard refreshing on a url like `localhost:3000/releases/1.2.3` returns an error like this:
<img width="527" alt="messages image 3763230329" src="https://cloud.githubusercontent.com/assets/591643/12516743/f39566f0-c126-11e5-8157-888fae9e2ff5.png">

I confirmed that it's specifically having periods in paths that are broken (by adding a route handler on `/releases/foo`; finally managed to track it down to this issues. The fix proposed by stefanfisk works perfectly when I edited `webpack/server.dev.js`.

https://github.com/rackt/react-router/issues/676#issuecomment-73963306

I think this is a general enough problem to fix; it certainly shouldn't be happening - do you want me to clean up the code and submit a PR to 3.0.0?

**Comment by mxstbr** [comment]
Wow thanks for the in-depth bug report, much appreciated!

This ties into #100 – do you reckon it's worth switching to express.js as the development server? I haven't worked with that at all, so I'd love a PR!

**Comment by mxstbr** [comment]
I think we're fine sticking with `WebpackDevServer` for now, I don't really see any benefit switching to `express.js`. I'd love a PR implementing the fix by Stefan above!

**Comment by mxstbr** [comment]
@jongold any update on this?

**Comment by jongold** [comment]
@mxstbr it's still intermittently breaking for me; I want to find time to figure out why & make it bulletproof before I put code in other people's repos 😁

**Comment by mxstbr** [comment]
Nice, sounds good! :+1:

**Comment by mxstbr** [comment]
If you can't get it to work, a simple `express.js` server implementation like [this one](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#configuring-your-server) might solve the problem.

**Comment by jshultz** [comment]
I'm running into the same problem. Once I get to a url like http://localhost/something/somethingelse a hard refresh breaks it. I see this in the console log:

`GET http://localhost:3000/classrooms/js/bundle.js 404 (Not Found)`

**Comment by mxstbr** [comment]
Add the `publicPath` to your `output` option in your `webpack.prod.config.js`:

```JS
output: {
  path: path.resolve(__dirname, '..', 'build'),
  filename: '[name].js',
  chunkFilename: '[name].chunk.js',
  publicPath: '/'
}
```

**Comment by jshultz** [comment]
That didn't work? 

My routes look like this:

`<Router history={browserHistory}>
      <Route component={App}>
        <Route path="/" component={Classrooms} />
        <Route path="/assignments" component={Assignments} />
        <Route path="/classrooms" component={Classrooms} />
        <Route path="/classrooms/archived" component={Classrooms}/>
        <Route path="/login" component={LoginPage} onEnter={checkAuth} />
        <Route path="/register" component={RegisterPage} onEnter={checkAuth} />
        <Route path="/dashboard" component={Dashboard} onEnter={checkAuth} />
        <Route path="*" component={NotFound} />
      </Route>
    </Router>
  </Provider>,`


and my output in makewebpackconfig looks like this:

`output: { // Compile into js/build.js
      path: path.resolve(__dirname, 'build'),
      filename: "js/bundle.js",
        publicPath: '/'
    },
`

**Comment by mxstbr** [comment]
Can you try this? (Notice the prefixed slash in front of `filename` and `chunkFilename`)

```JS
output: {
  path: path.resolve(__dirname, '..', 'build'),
  filename: '/[name].js',
  chunkFilename: '/[name].chunk.js',
  publicPath: '/'
}
```

**Comment by jshultz** [comment]
So I tried it both like this:

`output: {
      path: path.resolve(__dirname, '..', 'build'),
      filename: '/bundle.js',
      chunkFilename: '/[name].chunk.js',
      publicPath: '/'
    },`
and like you wrote it:
`output: {
  path: path.resolve(__dirname, '..', 'build'),
  filename: '/[name].js',
  chunkFilename: '/[name].chunk.js',
  publicPath: '/'
}`

and either way i got the same error: `GET http://localhost:3000/js/bundle.js 404 (Not Found)`

**Comment by mxstbr** [comment]
I totally forgot you're on master, the above solution would only work on `v3.0.0`! For master, please try this:

```JS
    output: { // Compile into js/build.js
      path: path.resolve(__dirname, 'build'),
      filename: "/js/bundle.js",
      publicPath: "/"
    },
```

Sorry for the unnecessary troubles!

**Comment by jshultz** [comment]
Unfortunately it doesn't. :(

`Application Cache Error event: Resource fetch failed (6) http://js/bundle.js
classrooms:18 GET http://localhost:3000/js/bundle.js 404 (Not Found)`

**Comment by jshultz** [comment]
Here's the whole file: https://gist.github.com/jshultz/50ca04ab37d05598271d

**Comment by mxstbr** [comment]
Alright, maybe that was one slash too much, can you try this:

```JS
    output: { // Compile into js/build.js
      path: path.resolve(__dirname, 'build'),
      filename: "js/bundle.js",
      publicPath: "/"
    },
```

**Comment by jshultz** [comment]
still no luck. :(

`Application Cache Error event: Manifest fetch failed (404) http://localhost:3000/classrooms/archived
archived:18 GET http://localhost:3000/classrooms/js/bundle.js 404 (Not Found)`

**Comment by jshultz** [comment]
it pulled http://localhost:3000/classrooms/ just fine, and when I initially went to archived it worked. but a hard refresh and it died.

**Comment by mxstbr** [comment]
Damn, I have no idea then, sorry :(

**Comment by jshultz** [comment]
ok, no problem. I guess I don't have a choice but to migrate to 3.0

**Comment by mxstbr** [comment]
@jshultz is your issue the same as #160 ?

@jongold any updates on this PR? Is it still coming, or are you running into massive issues?

**Comment by jshultz** [comment]
@mxstbr it looks to be the same. It was happening in the master branch. I've since migrated to 3.0 but removed the saga code and brought in the original redux/thunk code. Basically, I'm working on a hybrid of 2.0 and 3.0 :)

**Comment by jongold** [comment]
Sorry, I've been super busy with work. Written and rewritten about 1000 webpack configs over the past month; just ran into that bug again and fixed it by…

- building into `/public/build/{commons,main}.js` etc
- serving from public `app.use(express.static(staticPath))`
- proxying from webpack dev server's build folder to `public/build`
- sending every other request to public/index.html

It's a little bit different from the current setup and I don't feel confident enough with my webpack or express skills to propose a change to such a popular project (sorry) - but this is working for me.
https://gist.github.com/d69778adb88ec1acf11b

**Comment by mxstbr** [comment]
Mate what should I say, I gotta change this popular project every single day. :worried: 

Thanks for the update, I'll open a new issue and see if I find somebody with more Express.js skills than me to fix this!

**Comment by Adriang71** [comment]
@thehashrocket I have this same issue with routing and I add HtmlWebpackPlugin, try this solution maybe help you. `plugins: [new HtmlWebpackPlugin({template: 'index.html'})],`

**Comment by Syndesi** [comment]
@mxstbr thank you for the help with the _publicPath_-setting, you saved my day :D

**Comment by marcobiedermann** [comment]
Another solution would be to add the `base` tag to your index page.

index.html

```html
<head>
  <base href="/">
</head>
```

webpack.config.js

```js
module.exports = {
  devServer: {
    historyApiFallback: true,
  },
};
```
