### ISSUE TITLE
Disabling the content of /app/containers/App/index.js on selected routes

### ISSUE THREAD

**Issue by williamgranli** [mxstbr/react-boilerplate#1130]
I know this component is meant to show content that should be seen on all pages. Right now mine contains only a navigation bar... BUT, I don't want to show this navbar on some routes, such as the login page. 

Is it possible to tell a route to not show whatever is rendered in the app component? Or can I specify in the App/index.js which routes should be excluded?

Thanks!

**Comment by sourcesoft** [comment]
If you've wrapped App container inside `withRouter` then you can use `this.props.location.pathname` to as condition to not show it inside render:
````
render() {
  const withNav === this.props.location.pathname !== '/login';
  return(
    <div>
    {withNav && <Nav />}
    </div>
  );
}
````
However you have more control creating custom nested containers inside `routes.js` and don't use default `App` container.

**Comment by williamgranli** [comment]
You da man @sourcesoft 

Just fyi your code contains a typo '===' instead of assign (=) on line 2 between render and return. 

Fixing that it worked perfectly!

**Comment by sourcesoft** [comment]
Happy to hear that, fixed the typo.
