### ISSUE TITLE
Hashbang routing

### ISSUE THREAD

**Issue by kenny1har** [mxstbr/react-boilerplate#1135]
how to use hashbang URL#! in building static HTML ?
any changes in react-router config ?
in case the files are hosted in S3.

thanks

**Comment by diegys** [comment]
In `app.js` import `hashHistory` instead of `browserHistory` from react-router and modify the store constant to use hashHistory: `const store = configureStore(initialState, hashHistory);`

**Comment by kenny1har** [comment]
thanks. the hashBang URL#! works.
i also made changes to the container to use hashHistory.push('/') , instead of browserHistory.push('/') .
