### ISSUE TITLE
How to remove event listener (unbind components)

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1138]
I have a DashboardPage that has a button : 

```
<button onClick={::this._getEmployee}>GET /employees (TEST)</button>
```

The DashboardPage is loaded as follow in the `routes.js` :

```
{
  path: pages.pageDashboard.path,
  name: pages.pageDashboard.name,
  getComponent(nextState, cb) {
    const importModules = Promise.all([
      System.import("containers/DashboardPage/reducer"),
      System.import("containers/DashboardPage/sagas"),
      System.import("containers/DashboardPage")
    ]);

    const renderRoute = loadModule(cb);
    importModules.then(([reducer, sagas, component]) => {
      injectReducer("dashboard", reducer.default);
      injectSagas(sagas.default);

      renderRoute(component);
    });

    importModules.catch(errorLoading);
  }
}
```

When I hit the button, my request is done properly.

But if I left and come back, everytime I will press the button I will have request \* number of time DashboardPage has been loaded.

I have checked how to unbind event when unmounting components.

Seems that I should use the default addEventListener function like : 

```
componentDidMount() {
  window.addEventListener('resize', this.onClick.bind(this)); 
}

 componentWillUnmount() {
  window.removeEventListener('resize', this.onClick.bind(this));
}
```

This bring me to theses questions : 
- Should react unbind components itself ?
- Is there a more convenient way in boilerplate v3 to unbind components ?

**Comment by sedubois** [comment]
I think that's because you use `bind` (implictly through `::` operator), which is bad according to [this eslint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)? Can check their protips for alternatives.

Normally you also get the warning when using `::`, maybe you deactivated that rule?

**Comment by kopax** [comment]
Oh my bad, I found this in an example and found it pretty conveniant.

I have restore the default eslint rules now, thanks for warning me.

However, I have followed the advices provided in your link the bring the context into my _getEmployeeFunction

I have tried with : 

- autobind ES7 decorator : but it wasn't supported by es6
- the purposed syntax : 

     constructor() {
       super();
       this._getEmployee = this._getEmployee.bind(this);
     }
     
      render() { 
          return (
              <button onClick={this._getEmployee}>GET /employees (TEST)</button>
          )
      }

I keep having my events binded, is this the error you were pointing me at ? Because it didn't change much.

Should I take care of the unbinding my self ? Do you have an example I could start with ?

**Comment by kopax** [comment]
React should take care of unbinding components, so I guess it's completely unrelated.

There something in the way react switch routes, because I got my action called multiple times.

Do you mind reopening this ?

**Comment by sedubois** [comment]
Do you need to access `this` at all? Can you avoid using the `.bind()` method altogether? I'm not familiar with decorators so can't comment on that.

**Comment by kopax** [comment]
For some reason, using `.bind()` does the same bug result as `::`, components doesn't unbind when it get unmounted.

**Comment by sourcesoft** [comment]
> But if I left and come back, everytime I will press the button I will have request * number of time DashboardPage has been loaded.

Can I see the `_getEmployee`? Are you calling an action that a saga is listening to it? this happens not because the binding doesn't get unmounted but since your saga instance is being called everytime you switch to the related route and it's listening to the action being dispatched more and more. You can make sure of that by logging inside `_getEmployee` and another console.log inside the saga.
If that's the case you should control the saga threads using `cancel` inside a watcher.

**Comment by kopax** [comment]
__app/containers/DashboardPage/index.js:__

    /*
     * DashboardPage
     *
     * The Dashboard is only visible to logged in users
     * Route: /dashboard
     *
     */
    
    import React from "react";
    import { connect } from "react-redux";
    import { getEmployeeRequest }  from "./actions";
    
    class Dashboard extends React.Component {
    
      static propTypes = {
        data: React.PropTypes.object.isRequired,
        dispatch: React.PropTypes.func.isRequired,
        history: React.PropTypes.object.isRequired
      };
    
      constructor(props) {
        super(props);
        console.log("switch to DashboardPage")
        this._getEmployee = this._getEmployee.bind(this);
      }
    
      render() {
        return (
          <button onClick={this._getEmployee}>GET /employees (TEST)</button>
        );
      }
    
      _getEmployee() {
        this.props.dispatch(getEmployeeRequest());
      }
    }
    
    // Which props do we want to inject, given the global state?
    function select(state) {
      return {
        data: state
      };
    }
    
    // Wrap the component to inject dispatch and state into it
    export default connect(select)(Dashboard);

__app/containers/DashboardPage/sagas.js:__

    // This file contains the sagas used for async actions in our app. It"s divided into
    // "effects" that the sagas call (`authorize` and `logout`) and the actual sagas themselves,
    // which listen for actions.
    
    // Sagas help us gather all our side effects (network requests in this case) in one place
    
    import { take, call, put, fork } from "redux-saga/effects";
    import employeeService from "services/employees";
    import { sendingRequest, requestError } from "./actions";
    
    import {
      GET_EMPLOYEE_REQUEST
    } from "./constants";
    
    /**
     * Effect to handle getEmployee
     */
    export function* getEmployee() {
      // We send an action that tells Redux we"re sending a request
      yield put(sendingRequest(true));
    
      // We then try to register or log in the user, depending on the request
      try {  // eslint-disable-line padded-blocks
        console.log("getEmployee called from DashboardPage/sagas");    
        // make a first request to generate the cookie seession and include it in the login request
        const fetchEmployeeList = yield call(employeeService.getAll);
        const employeeList = yield fetchEmployeeList.response;
    
        console.log(employeeList);
    
        return fetchEmployeeList;
      } catch (error) {
        // If we get an error we send Redux the appropiate action and return
        yield put(requestError(error.message));
    
        return false;
      } finally {
        // When done, we tell Redux we"re not in the middle of a request any more
        yield put(sendingRequest(false));
      }
    }
    
    /**
     * Get employee saga in saga
     */
    export function* getEmployeeFlow() {
      // Because sagas are generators, doing `while (true)` doesn"t block our program
      // Basically here we say "this saga is always listening for actions"
      while (true) { // eslint-disable-line no-constant-condition
        console.log("getEmployeeFlow called from DashboardPage/sagas");
        yield take(GET_EMPLOYEE_REQUEST);
        yield call(getEmployee);
      }
    }
    
    
    // The root saga is what we actually send to Redux's middleware. In here we fork
    // each saga so that they are all "active" and listening.
    // Sagas are fired once at the start of an app and can be thought of as processes running
    // in the background, watching actions dispatched to the store.
    export function* root() {
      yield fork(getEmployeeFlow);
    }
    
    export default [
      root
    ];


I have tried to apply cancel that way : 

    export function* getEmployeeFlow() {
      // Because sagas are generators, doing `while (true)` doesn"t block our program
      // Basically here we say "this saga is always listening for actions"
      while (true) { // eslint-disable-line no-constant-condition
        // And we"re listening for `LOGIN_REQUEST` actions and destructuring its payload
        console
        yield take(GET_EMPLOYEE_REQUEST);
        const bgGetEmployeeTask = yield fork(getEmployee);
        yield cancel(bgGetEmployeeTask);
      }
    }

But this still bind multiples times.

I have added the console.log as you suggested and this is the result  :

These are the step of the test : 

1. Go to login page "/" (Home)
1. Login
1. Click the getEmployeeButton,
1. Changepage to login
1. Changepage to dashboard
1. Changepage to login
1. Changepage to dashboard
1. Changepage to login
1. Changepage to dashboard
1. Click the getEmployeeButton,

![image](https://cloud.githubusercontent.com/assets/1866564/19634928/c0be3982-99e8-11e6-88df-83c9b02df291.png)


This lead me to the following assumption : 

- `getEmployeeFlow` from `DashboardPage/sagas.js` is called before the constructor in `DashboardPage/index.js` (see screen at 12:39:59.228)
- when I click on the button, `_getEmployee` from `DashboardPage/sagas.js` is executed once, and again `getEmployeeFlow` from `DashboardPage/sagas.js` is called
- if I hop to this page 3 times, a click on the button will run once `_getEmployee` and 3 times `getEmployeeFlow`

I assume you are right, but I haven't find the correction to this. Can you see any strange behavior in the way sagas get loaded ?

**Comment by sourcesoft** [comment]
Problem is changing routes and how this boilerplate injects them. Try this in watcher:
````
export function* getEmployeeFlow() {
  while (true) { // eslint-disable-line no-constant-condition
    console.log("getEmployeeFlow called from DashboardPage/sagas");
    const  employeeTask = yield fork(GET_EMPLOYEE_REQUEST);
    yield take(LOCATION_CHANGE);
    yield cancel(employeeTask);
  }
}
````

This should be your imports:
````
import { LOCATION_CHANGE } from 'react-router-redux';
import { take, call, put, fork, cancel } from "redux-saga/effects";

````

Your listening to route changes action to cancel the running task.

**Comment by andykenward** [comment]
@kopax try this using arrow function to bind instead.
```
import React from "react";
import { connect } from "react-redux";
import { getEmployeeRequest }  from "./actions";

class Dashboard extends React.Component {

  static propTypes = {
    data: React.PropTypes.object.isRequired,
    dispatch: React.PropTypes.func.isRequired,
    history: React.PropTypes.object.isRequired
  };

  constructor(props) {
    super(props);
    console.log("switch to DashboardPage");
  }

  _getEmployee = () => {
    this.props.dispatch(getEmployeeRequest());
  }

  render() {
    return (
      <button onClick={this._getEmployee}>GET /employees (TEST)</button>
    );
  }

}

function select(state) {
  return {
    data: state
  };
}

export default connect(select)(Dashboard);
```

Otherwise you can always `unbind` or `removeEventListener` in `componentWillUnmount()` if you are manually binding etc.

[See react component lifecycle](https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle)

But you should [never bind in the render](https://ryanfunduk.com/articles/never-bind-in-render/) function as every time that component renders it would do a bind again.

**Comment by SyntaxChris** [comment]
Hey guys, why was this closed?  What was the solution?  I've tried everything, fat arrows, bind(this) in the constructor, decorators.  Nothing seems to unbind the event listener on the componentWillUnmount function.

**Comment by toroc** [comment]
I'm also having this issue. Any solution for resolving this.

**Comment by SyntaxChris** [comment]
@toroc use this and be happy https://github.com/davezuko/react-redux-starter-kit

**Comment by gretzky** [comment]
This was closed because it has to do with React, not this boilerplate. I recommend StackOverflow for issues like this.
