### ISSUE TITLE
"Dependencies" includes the "express"

### ISSUE THREAD

**Issue by bicycleChen** [mxstbr/react-boilerplate#1140]
## Description
My point of view is that express should in devDependencies, it is only used in dev-env

**Comment by bicycleChen** [comment]
I probably know, is aim to SEO?

**Comment by sedubois** [comment]
AFAIK the project can be deployed in basically ways:
- deploy the whole monorepo to e.g Docker, Heroku. In this case the express server is needed.
- push all static files (generated by `npm run build`) to a CDN, in this case the express server won't be used but the package.json won't be used either, so we don't care

Please correct if I'm mistaken.
