### ISSUE TITLE
How to add third-party css files via CDN

### ISSUE THREAD

**Issue by AshCoolman** [mxstbr/react-boilerplate#1145]
What is the "react-boilerplate blessed" way to add a standard 
`<link rel="stylesheet" href="//bootstrapcdn.com/bootstrap.css">` to the project?

**More info**

I'd like to add a css file (bootstrap) from a CDN. The `index.html` warns about adding assets because of the magic, and mentions `webpackconfig.js`, which led me to https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/css-modules.md#integrating-global-css

In my project I'm happy to have the global css file (bootstrap). 

thanks

**Comment by whathejoe** [comment]
You could add this as a prop in your helmet component,
```
link={[
  { rel: 'stylesheet', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css' }
]}
```

**Comment by Altiano** [comment]
what if it's a JS library?

**Comment by whathejoe** [comment]
Assuming still via cdn, you can use:  
```
script={[
  {  src: '...', type: 'text/javascript' }
]}
```
See [docs](https://github.com/nfl/react-helmet#examples) for more info.

**Comment by danielo515** [comment]
Where is the helmet supposed to be used? On the main App container? On any place? Thanks

**Comment by felipefunes** [comment]
I have the same problem, I can't find the way to add this into Helmet
