### ISSUE TITLE
Who is using react-boilerplate?

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#115]
I would like to gather a list of projects/companies using this boilerplate for the README and out of personal interest.

**Please post here if your project/company uses react-boilerplate and wouldn't mind being mentioned in the README.**

*A logo with a link to the project and a short description of how react-boilerplate has helped would be awesome, but isn't necessary. If the code is open source, please link to it too! If you're not allowed to say it in public, DM me on [twitter](https://twitter.com/mxstbr) – I won't tell anybody anything, promise.*

**Comment by gkio** [comment]
Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "start:tunnel"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-boilerplate@3.0.0 start:tunnel: `cross-env NODE_ENV=development node server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 start:tunnel script 'cross-env NODE_ENV=development node server'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gkio/Desktop/react-boilerplate/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "start"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start: `npm run start:tunnel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'npm run start:tunnel'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:tunnel
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gkio/Desktop/react-boilerplate/npm-debug.log








# this error

**Comment by oliverturner** [comment]
@gkio I've deleted your comment as off-topic. In any case, please don't aggressively shout for attention as you did. 

To address your error, I'd suggest updating your npm version to 3.x.x and using a stable version of Node.

**Comment by martinduo** [comment]
I have cloned your repo some weeks before and have run your app at port 3000 just fine. Today I wanted to work with another copy so I again cloned your repo into another folder and did the npm run setup successfully. But I got an error when I next did the npm run start. Did I do something wrong?

I tried to attach the npm-debug.log, but was told that the file type was not supported, even though I zipped it up in a npm-debug.zip file. So I have inserted the error below.

`> react-boilerplate@3.3.3 start C:\Users\Bruce\Dropbox\Projects BlueDuck\react-boilerplate
> cross-env NODE_ENV=development node server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (C:\Users\Bruce\Dropbox\Projects BlueDuck\react-boilerplate\node_modules\express\lib\application.js:617:24)
    at Object.<anonymous> (C:\Users\Bruce\Dropbox\Projects BlueDuck\react-boilerplate\server\index.js:26:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bruce\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.3.1
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.3.3 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.3.3 start script 'cross-env NODE_ENV=development node server'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Bruce\Dropbox\Projects BlueDuck\react-boilerplate\npm-debug.log
`

**Comment by kopax** [comment]
This error `Error: listen EADDRINUSE :::3000` is a common error when your port is unavailable (mostly because another service is listening to it).
This means you cannot listen on port 3000.
Check what service access this port and disable it.
Alternativaly, you can change react-boilerplate port in 3 differents way : 

1. change the default port in `server.js`
1. specify an overriding port using argument when starting `server.js`
1. specify an overriding port using system environment variable `server.js`

For the 3 of theme, avec a look at `server.js`

**Comment by martinduo** [comment]
Thank you for the quick reply. Yes that was the problem. Easily fixed when
you know the cause.

**Comment by nickwild-999** [comment]
Hi, I have an error when the setup runs...

const shell = require('shelljs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

Anybody have any thoughts please?

**Comment by gihrig** [comment]
@nickwild-999 I have deleted your comment as off-topic. 

Please read the entire error message more closely (old versions?) and try again. If you're still having problems, please search open and closed issues, if still no luck feel free to open a new issue.
