### ISSUE TITLE
React-dates incompatibility or any lib using momentjs

### ISSUE THREAD

**Issue by akiokio** [mxstbr/react-boilerplate#1152]
## Issue Type

- [X] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Hello, I'm trying to implement the react-dates package in one of my projects but I always get the error "Uncaught (in promise) TypeError: (0 , _moment2.default) is not a function" even in the simplest setup. 

My guess is something related to the way we load the dependencies (momentjs in this case) but I was unable to go further in my investigations because I still learning how the webpack loads the modules specially using DLL.

## Steps to reproduce
This happens even with a clean setup, you can see the error happening here: https://github.com/akiokio/react-boilerlate-error-react-dates

I made this repo using the react-boilerplate and just running the install commands here: https://github.com/airbnb/react-dates

or

1. Clone this repo
2. Run npm run setup, npm run clean as aways
3. Run the react dates setup script: `(
    export PKG=react-dates;
    npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
  )`
4. Open the homepage container (app/containers/HomePage/index.js) and import the react dates component: `import SingleDatePicker from 'react-dates';`
5. Done, now open the homepage and look the error in the console.

# Versions

- Node/NPM: node: v6.2.2 npm: 3.9.5
- Browser: Any

**Comment by akiokio** [comment]
Closing this issue, the problem was related to the momentjs version 2.1.0 update. More info here: https://github.com/moment/moment/#port-to-ecmascript-6-version-2100

To fix in the react-boilerplate project: Add an alias from 'moment' to 'moment/moment.js'. 
Reason: With the update (es5 -> es6) the guys over moment changed the library path.

Actual code on `webpack.base.babel.js`:

`resolve: {
    modules: ['app', 'node_modules'],
    alias: { moment: 'moment/moment.js' },
    extensions: [
      '',
      '.js',
      '.jsx',
      '.react.js',
    ],
    mainFields: [
      'jsnext:main',
      'main',
    ],
  },`

** I pasted the whole dict entry to be easier to  newcomers like me :)

** PS. I posted the fix on the github project too if you guys want to see the whole code but keep in mind I just showing the component so the css is missing 👍

**Comment by ej23lee** [comment]
@akiokio Thanks for this. I was having this issue and couldn't seem to find the fix.

**Comment by talbenbasat** [comment]
Any workaround?

**Comment by akiokio** [comment]
I posted the steps here: https://github.com/mxstbr/react-boilerplate/issues/1152#issuecomment-256547900

**Comment by cristobal-io** [comment]
With the latest versions is not working, keeps appearing the same error. 

`webpack.base.babel.js` have changed from the version that @akiokio implemented the solution, not sure if this would affect.

Thanks.
