### ISSUE TITLE
selector css with bootstrap support

### ISSUE THREAD

**Issue by redwind** [mxstbr/react-boilerplate#1158]
Hi  all !

i'm using bootstrap by this [doc](https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/css-modules.md)
my layout as bellow:
`<div className={"row"}>`
`<div className={"col col-md-6 col-md-pull-6"}>`
                                    `<div className={styles.title}>title here</div>`
                                   `<div className={styles.summary}>sumary here.</div>`
                                   `<a className={styles.viewmore} href="#"><i className="fa fa-plus-square-o" aria-hidden="true"></i> view more</a>`
                                `</div>`
`</div>`

so how could i style like this:
`.row .col .title{
    font-size:2em;
    font-weight:400;
}`

cause when css is compile, it look like this:
`.row__app-containers-HomePage-styles__3CsVt .col__app-containers-HomePage-styles__17lAf .title__app-containers-HomePage-styles__14bTN{
    font-size:2em;
    font-weight:400;
}
.row__app-containers-HomePage-styles__3CsVt .col__app-containers-HomePage-styles__17lAf .summary__app-containers-HomePage-styles__2jVL-{
    font-weight:100;
    margin: 20px 0;
}`

then style is not effected. So how i resolve this problem ?

thanks all !

**Comment by avdeev** [comment]
may be `<div className="row"></div>` ?

**Comment by redwind** [comment]
@avdeev  yes, in this case class="row" and className={"row"} is the same, i think so

**Comment by mxstbr** [comment]
This is done by using css modules' `:global` helper:

```
:global(.row) :global(.col) .title
```
