### ISSUE TITLE
Algolia importing node modules is crashing webpack

### ISSUE THREAD

**Issue by redgenie** [mxstbr/react-boilerplate#1159]
I am trying to use `react-algoliasearch-helper` which requires `algoliasearch`. Algolia claim that their  isomorphic library works perfectly with webpack. Now when I tried to include it in the boilerplate, webpack is crashing with this error:

```
ERROR in ./~/debug-ms-fix-yui-compressor/node.js
Module not found: Error: Can't resolve 'fs' in '/path/node_modules/debug-ms-fix-yui-compressor'
 @ ./~/debug-ms-fix-yui-compressor/node.js 163:15-28
 @ ./~/algoliasearch/src/browser/createAlgoliasearch.js
 @ ./~/algoliasearch/src/browser/builds/algoliasearch.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi main

ERROR in ./~/debug-ms-fix-yui-compressor/node.js
Module not found: Error: Can't resolve 'net' in '/path/node_modules/debug-ms-fix-yui-compressor'
 @ ./~/debug-ms-fix-yui-compressor/node.js 170:16-30
 @ ./~/algoliasearch/src/browser/createAlgoliasearch.js
 @ ./~/algoliasearch/src/browser/builds/algoliasearch.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi main
```

I tried following the code and I saw that it's trying to include some debugging features which requires `fs`. The problem is that it's picking the wrong module, instead of picking `browser`, it's picking `node` in the package `debug-ms-fix-yui-compressor`. This should not be a problem in webpack alone because it works out of the box, but with this boilerplate, it's thinking that it's running in a node environment rather than browser.
## Steps to reproduce
1. `npm install --save algoliasearch algoliasearch-helper react-algoliasearch-helper`
2. Add these lines to containers/App/index.js:

```
// ...other  imports above
import algoliasearch from 'algoliasearch';
import algoliasearchHelper from 'algoliasearch-helper';
import {Provider} from 'react-algoliasearch-helper';
const client = algoliasearch('id', 'somekey');
const helper = algoliasearchHelper(client, 'index');

function App(props) {
  return (
    <Provider helper={helper}>
     // Reste of the app
    </Provider>
  );
}
```
1. run `npm start` and you'll get the webpack errors
# Versions
- Node/NPM: 7.0.0/3.10.8

**Comment by Luis-Teixeira** [comment]
Some here trying to use twilio

**Comment by mxstbr** [comment]
Those libraries are meant to run in node, not in the browser. What you're seeing means that node-internal modules don't exist in the browser, which, well, they don't. This is expected behaviour, you're trying to make something work that isn't meant to work.

**Comment by redgenie** [comment]
@mxstbr that's why I said that it's an "isomorphic" package. It's supposed to work with node and browser. They come with both versions in the same package. If you use the package `algoliasearch` with webpack, it will work regardless of node. Please check:
https://www.npmjs.com/package/algoliasearch#nodejs--react-native--browserify--webpack
They are webpack and browsersify friendly, they're not exclusively node modules.
