### ISSUE TITLE
Markdown is broken in recently added remove.md docs 

### ISSUE THREAD

**Issue by KarandikarMihir** [mxstbr/react-boilerplate#1164]
I saw that recently updated docs for `remove.md` has [broken numeric lists](https://github.com/mxstbr/react-boilerplate/blob/dev/docs/js/remove.md). By broken, I mean ill-formatted list.

![screenshot from 2016-10-31 15-11-27](https://cloud.githubusercontent.com/assets/17466938/19850050/62f693d2-9f7c-11e6-8a51-8ea16d0d02b8.png)

It was looking just fine a few days ago. Maybe github has upgraded their markdown plugin? :suspect:
I don't know. I can send a new PR for docs.

**Comment by mxstbr** [comment]
Done by the amazing @GGAlanSmithee in #1165!
