### ISSUE TITLE
Add info about stable branch to the readme

### ISSUE THREAD

**Issue by web2style** [mxstbr/react-boilerplate#1169]
I spent a lot of time considering what version of the boilerplate is stable and ready to use in production. Then fount the following in v3.1.0 changelog:

> Now using an unstable dev branch for development stuff so master is 100% stable. Please test dev and tell us where some problems are!

Consider adding a section about it in the readme.

**Comment by gihrig** [comment]
Great idea! Would you consider creating a PR for this?

**Comment by web2style** [comment]
Done: https://github.com/mxstbr/react-boilerplate/pull/1172
