### ISSUE TITLE
Server API Middleware ES6 SyntaxError?

### ISSUE THREAD

**Issue by bryan** [mxstbr/react-boilerplate#1170]
I can't seem to get my server to work with ES6 syntaxes such as import and export. I've noticed someone else had a similar problem https://github.com/mxstbr/react-boilerplate/issues/430#issuecomment-232573482 except the given solution by the original owner doesn't necessary solve anything and it's been quite a while since the thread has been closed. I was wondering what I had to do in order to get ES6 syntax working on the server.

Trying to change all the `const = requires('')` into `import from` seems to be problematic and was wondering if there was a solution to allow it.

```
import api from './api';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by Dattaya** [comment]
You can do that with babel (of course not directly in the file where `babel-register` is imported):

```js
require("babel-register");
```

But according to [the official docs](https://babeljs.io/docs/setup/#babel_register), it is not recommended for production
![image](https://cloud.githubusercontent.com/assets/387256/19920213/fe68560c-a0df-11e6-94e3-daf5de12d2a1.png)
so unless you decide to ignore their advice you'll need to require `babel-register` only in development mode and compile for production:

```js
if (process.env.NODE_ENV !== 'production') {
  require('babel-register');
}
``` 
`package.json`:

```js
"build:server": "rimraf ./build && babel server -d build --copy-files",
```

**Comment by mxstbr** [comment]
See #546
