### ISSUE TITLE
Unhandled promise rejection ReferenceError: Can't find variable: IntlPolyfill

### ISSUE THREAD

**Issue by andylhansen** [mxstbr/react-boilerplate#1179]
This error started showing up on Safari.

Unhandled promise rejection ReferenceError: Can't find variable: IntlPolyfill

Any ideas what could be causing this?

**Comment by mxstbr** [comment]
Which version of the boilerplate are you on? I think we fixed that bug a while back, see #805!

**Comment by mxstbr** [comment]
I'll close this for now since I cannot replicate it, please copy the changes done in #805 into your project and it should all work perfectly. If it doesn't, feel free to comment again and we'll investigate this further.
