### ISSUE TITLE
Document how to keep project up-to-date with react-boilerplate

### ISSUE THREAD

**Issue by samit4me** [mxstbr/react-boilerplate#1180]
I've seen at least two people asking how to keep their project up-to-date with react-boilerplate.

Would you be happy for me to create a new section under [Documentation](https://github.com/mxstbr/react-boilerplate#documentation)?

My rough outline would be something like what is already documented in the [CONTRIBUTION](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#pull-requests) guidelines!

**Comment by gihrig** [comment]
Previously discussed in #600, #889, #1047.

As those issues attest, this is not an easy task. The ideal would be to split the boilerplate and the application into separate modules as Create React App does. I seem to recall @mxstbr discussing this somewhere, but I'm not finding it now. :-/ In any case, this is a large task, that when accomplished will move this boilerplate lightyears ahead.

**Comment by mxstbr** [comment]
I want `react-boilerplate` to be a fork of `create-react-app`. This will a) give us some goodies in configuration that we don't currently have, but b) it will allow updating more easily.

The problem is that doing so requires a huge rewrite of the whole thing, and I don't have time to do that at the moment.

That being said, let's caution people in the FAQ that while it's possible to update, it's very hard for now. I don't want to set the expectation that it's simple or easy to do, which it isn't right now.

**Comment by ansumanshah** [comment]
I am trying to create a universal boilerplate using `create-react-app` and `react-native` with `styled-components` taking some bits on project structure from this awesome project and `este` would be happy to submit a PR/Fork if needed

**Comment by samit4me** [comment]
@gihrig @mxstbr Thanks for the info, that makes a lot of sense, I too really like the idea of separating the boilerplate from the application 👍 Your totally right, it is not easy to update. Will try and write up something in FAQs.

**Comment by GGAlanSmithee** [comment]
This is an interesting topic. For the sake of discussion, this is how I am doing it:

I have my own template proejct which has this (along with a few other projects) as git submodules, that I keep around as references. This template project contains mostly configuration and build related code, and almost no application code. When there is an interesting development in any of the reference projects, such as this, I patch it to my template project.

I then have a couple of actual projects which contains application code, that are based on the template project. I try to avoid making changes to anything _but_ application code in these, and when the template project updates, i rebase these projects on it.

This workflow adds a bit of manual labor and overhead, but it's a nice intermediate step which allows me to keep my projects up to date with evolving tech.

**Comment by nonotest** [comment]
I can confirm it is very hard to update. It should be clear that it is a *do it as your own risk* operation.

**Comment by afitiskin** [comment]
It is possible to simplify update process by splitting boilerplate core and example app into `react-boilerplate` and `react-boilerplate-example` repos (I think it is not so hard to do). `react-boilerplate-example` should be built on top of `react-boilerplate` (it will be a real example of how to keep project update-to-date with `react-boilerplate`).

So when example app will be moved from this repo to separated one, we could change setup script a bit: do not totally remove `.git` directory, but create a new branch named `boilerplate`. The `boilerplate` branch will track `react-boilerplate`'s `master` branch, so it will be possible from time to time merge `boilerplate` branch into your project's `master` to be up-to-date.

And few notes about last update (featuring `styled-components`): I like the idea of `styled-components`, but these kind of updates should not be so cardinal (If you really thinking of possibility to keep projects based on `react-boilerplate` up-to-date with `react-boilerplate`). We should have a transitional state between `css-modules` and `styled-components`: we have not to remove `package.json`/`webpack`/`eslint` and other settings/configuration/deps of previous approaches at once but provide a special script to remove unused parts after refactoring. So during refactoring both approaches (`css-modules` and `styled-components` for example) will work, and after refactoring developer are able to run migration script to cleanup his settings (by the way, moving `eslint` and other configurations from `package.json` to separated files make it easy to make migration script).

**Comment by mxstbr** [comment]
> but provide a special script to remove unused parts after refactoring.

I would love to have somebody contribute such a script next time we do a big change!

I sadly don't have the time to look into that at all, and while I agree it'd be useful, I don't think it's feasible for us to spend that much more time on a script to update existing boilerplates with new apps in them. Imagine all the edge cases with people building their apps! 😱 

If you're on an "old" version that still uses css modules, you're totally fine! Go on with building your app, ignore all the updates this boilerplate does. Thousands of other projects are on the same boilerplate as you, so it's not like you're now fucked just because you're still using css modules.

**Comment by afitiskin** [comment]
@mxstbr it's not so hard to make such scripts cause it should just make a cleanup like `npm uninstall --save-dev stylelint` and of course not to convert whole project from CSS modules to styled components :) 
Other way (in case if building migration script is really hard) provide a migration guides what you have to do manually (just short and simple summary of last N commits) not to force users to check and understand all commits diffs manually 

I'd like to know your opinion about splitting project into boilerplate and example app as well, thank you!
