### ISSUE TITLE
i18n.js - Can't resolve 'containers/App/constants' after 'npm run clean'

### ISSUE THREAD

**Issue by adjnor** [mxstbr/react-boilerplate#1185]
-Node: 7.0.0 (also tried with 6.9.1)
-NPM: 3.10.8

Steps to reproduce:
1. git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
2. cd react-boilerplate
3. npm run setup
4. npm run clean
5. npm start (or npm run start)

Results in:

```
ERROR in ./app/i18n.js
Module not found: Error: Can't resolve 'containers/App/constants' in '/Users/MyUsername/Work/react-boilerplate/app'
 @ ./app/i18n.js 8:0-58
 @ ./app/app.js
 @ multi main
```

Fix is adding back a 'constants.js' file in 'containers/App/' with the line:
`export const DEFAULT_LOCALE = 'en';`

**Comment by connorbode** [comment]
Was just going to report this; I can confirm that after running `npm run clean`, the resulting project is missing `app/containers/App/constants.js`.  This was a bit confusing when just starting out.

**Comment by mxstbr** [comment]
Ugh, would appreciate a PR fixing this!

**Comment by adjnor** [comment]
I'm on it!

**Comment by mxstbr** [comment]
Released as v3.3.1, thanks for the quick fix @adjnor, amazing!

**Comment by sebscholl** [comment]
Hey, this issue is popping back up for me.

Inside the /containers/App/ directory there is a constants.js file with 

`export` const DEFAULT_LOCALE = 'en';

However the same error is popping up

`ERROR in ./app/i18n.js
Module not found: Error: Can't resolve './translations/en.json' in 'c:\Users\sebsc\Development\rampex\rampex-frontend\app'
 @ ./app/i18n.js 13:0-59
 @ ./app/app.js
 @ multi main`

**Comment by gihrig** [comment]
@sebscholl I just did a clone, yarn install, npm run clean on current `master` and `translation/en.json` is present.

![image](https://cloud.githubusercontent.com/assets/1481063/22311317/d568f922-e307-11e6-9c3d-65a13c9a9240.png)

It contains an empty array.

What version of the boilerplate are you using?

**Comment by sebscholl** [comment]
@gihrig I didn't use yarn install but npm... maybe there's something in there?

**Comment by gihrig** [comment]
I have been using `yarn install`exclusively for a couple of months. The resulting dependency tree has been very solid, `npm install` not so much...

This may not have anything to do with the error you are seeing, but it's a simple experiment. worth a try next time you have a weird problem that seems to have no explanation.

To be fair to `npm`, this sequence also solves a lot of problems:

`rm -rf node_modules`
`npm cache clean`
`npm install`
