### ISSUE TITLE
All my Redux actions are building up at the speed of n+1!?!?!

### ISSUE THREAD

**Issue by williamgranli** [mxstbr/react-boilerplate#1188]
I have a really strange bug, which seems to be related to the way I use react-router-redux {push} for changing route, or it might be that I've set up my reducers incorrectly. 

To help you better understand the issue I'm having, see below scenario using the starter template project as example: 

1. Go to http://localhost:3000/
2. Type in a repository name and hit enter
3. Redux actions triggered: 
- LOAD_REPOS
- LOAD_REPOS_SUCCESS
4. Click the features button
5. Click the home button
6. Type in a repository name and hit enter
7. Redux actions triggered:
- LOAD_REPOS
- LOAD_REPOS
- LOAD_REPOS_SUCCESS
- LOAD_REPOS_SUCCESS
8. If I were to go back and forth to features and home and load the repos again, each action would be triggered three times. AND SO ON.

Note, this isn't actually happening with the starter project but with my project. I'm just using the starter project as an example. 

I'm quite new to React and Redux so I'm not sure where to begin the troubleshooting, since I'm changing routes the way it's done in the starter project and I can't spot any differences in the reducer structure.

Does anyone have any idea on what could be causing this? Please let me know if there's any part of my code that you'd like to see that might be relevant and I'll post it ASAP. 

Thanks!

**Comment by afitiskin** [comment]
@williamgranli you have to cancel your sagas on `LOCATION_CHANGE`. See #1183 there are few refs with more information there.

**Comment by williamgranli** [comment]
@afitiskin You da man! Thanks! I've been looking at saga tutorials and example code which are unrelated to this project. I'm guessing none of them use the same setup with injections, hence I missed that part.

**Comment by justingreenberg** [comment]
this should be resolved by #1746 — feedback is welcome!
