### ISSUE TITLE
Feature page: Error message when change language from English to German

### ISSUE THREAD

**Issue by nhducit** [mxstbr/react-boilerplate#1196]
## Description
There are some error messages in console when change language from English to German
<img width="960" alt="screen shot 2016-11-05 at 11 40 30 am" src="https://cloud.githubusercontent.com/assets/4246176/20027691/4915bb6c-a34d-11e6-8c39-41fcba41bb7a.png">

## Steps to reproduce
git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
npm run setup
open http://localhost:3000/features
change language from English to German
# Versions
v3.3.1
- Node/NPM: v6.9.1
- Browser: Version 54.0.2840.71 (64-bit)

Error message:
```
index.es.js:976 [React Intl] Missing message: "boilerplate.components.Header.features" for locale: "de", using default message as fallback.
index.es.js:976 [React Intl] Missing message: "app.components.LocaleToggle.en" for locale: "de", using default message as fallback.
index.es.js:976 [React Intl] Missing message: "app.components.LocaleToggle.de" for locale: "de", using default message as fallback.
```

**Comment by adjnor** [comment]
These errors are from the react-intl library, a simple way to fix them is to edit the de.json file (in the translations folder) and add translations (or any text) to the empty strings. AFAIK it's the intended behavior when translations are missing.
