### ISSUE TITLE
Rename npm run initProject to npm run setup

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#120]
`$ npm run setup` is much nicer than `$ npm run initProject`, we should rename it.

----

<sub>*Note: This is defined in the [`package.json`](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/package.json) in the `"scripts"` field. Try to find the `"initProject"` script! If you want to learn more about those scripts in general, check out [this blogpost](http://blog.mxstbr.com/2016/01/npm-scripts). Als, don't forget to update the [documentation](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/docs/general/commands.md) and the [readme](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/README.md) after fixing the bug.*</sub>

----

Steps to do this:

- [ ] Claim this issue by commenting below ~~(claimed by @Francososa)~~
- [ ] Setup a local copy of react-boilerplate
    - [ ] Clone the repo with `git clone git@github.com:mxstbr/react-boilerplate`
    - [ ] Enter the newly created folder with `cd react-boilerplate`
    - [ ] **Go to the `v3.0.0` branch of this repo with `git checkout v3.0.0`**
    - [ ] Install the dependencies with `npm install`
- [ ] Fix the bug mentioned above
- [ ] Update the documentation
- [ ] Start a pull request
- [ ] Review
- [ ] Merge

**Feel free to ping me on [twitter](https://twitter.com/mxstbr) if you need any help/tips/pointers/are stuck!**

**Comment by Francososa** [comment]
I claim this! Going to start working on it.

**Comment by brotzky** [comment]
I will give it a shot.
