### ISSUE TITLE
Use `babel-plugin-filenamespace` for message files

### ISSUE THREAD

**Issue by samit4me** [mxstbr/react-boilerplate#1201]
Writing message files for a component involves a little boilerplate, which is completely necessary and it's great that `npm run generate` does this for us. What I've noticed in projects based on this boilerplate is that it is quite easy to make mistakes when moving, renaming or adding additional messages to components. 

The message "id" naming convention appears to closely follow the directory structure in which the component lives, so I think this is a possible use case for [`babel-plugin-filenamespace`](https://github.com/samit4me/babel-plugin-filenamespace). Instead of manually copy-pasting or typing the message "id", you can use the global variable `__filenamespace` which Babel will convert into to a string representing the directory structure. This is especially helpful when renaming or moving a component, example:

Before:
```
export default defineMessages({
  home: {
    id: 'boilerplate.components.Header.home',
    defaultMessage: 'Home',
  },
  features: {
    id: 'boilerplate.components.Header.features',
    defaultMessage: 'Features',
  },
});
```

After:
```
export default defineMessages({
  home: {
    id: `${__filenamespace}.home`, // id: 'components.Header.home'
    defaultMessage: 'Home',
  },
  features: {
    id: `${__filenamespace}.features`, // id: 'components.Header.features'
    defaultMessage: 'Features',
  },
});
```

This plugin was originally created to help reduce boilerplate and name conflicts with Redux Action Types in a [Domain-style code structure](http://redux.js.org/docs/faq/CodeStructure.html#code-structure). As I am the author of the plugin, my opinion ***may*** be slightly biased 😃, so it would be great to hear the thoughts of others, do you think this would add value? I believe it simply reduces the chance of human error.

**Comment by mxstbr** [comment]
Why don't we do this automatically? Not a fan of the magic variable, we could just have magic?

**Comment by samit4me** [comment]
You could "just have magic" but that would require a very specialised plugin that targets only the "id" of defineMessage.  `babel-plugin-filenamespace` is a little more generic in that it can be used whereever you like, but in doing that, you must specify where you want it.

If you think that it might add value? I could certainly look into adding a flag to `babel-plugin-filenamespace` to do this.

There is also the problem of duplicating the "id"s into the `translations` directory.

On second thoughts, maybe it's NOT worth adding magic unless it improves the entire i18n workflow rather than just some of it. I cannot think of a better "complete" solution atm, so maybe we just close this discussion for now and re-open if a better solution comes to mind, what's your thoughts?

**Comment by mxstbr** [comment]
Yeah, that sounds good to me. Let's wait a bit with the magic!
