### ISSUE TITLE
`npm run start:prod` results in error

### ISSUE THREAD

**Issue by outdooricon** [mxstbr/react-boilerplate#1203]
After cleaning a new checkout of master, when running `npm run start:prod` I see `Error: ENOENT: no such file or directory, stat '\Projects\my-project\build\index.html'`. Then when loading the page, the browser just shows "Not Found"

# Versions

- Node/NPM: 7.0.0 / 3.10.8

**Comment by samit4me** [comment]
Thanks for reporting the issue. Looking at `package.json` it would seem that `npm run start:prod` starts the production server, serving files from the `build` directory. Assuming you have not run the command `npm run build` the `build` directory would not exist and therefore result in the error you mentioned.

So for the `npm run start:prod` command to work it must be preceded by `npm run build`. If you would like to build and start the production server with a single command you could try `npm run start:production`.

The [documentation](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/commands.md#production) might need updating as it kinda leads you to believe that `npm run start:prod` builds the assets too. I would suggest replacing `npm run start:prod` with `npm run start:production`. Would you be interested in submitting a PR for this @outdooricon, it would be greatly appreciated? If so, please take a look at the [CONTRIBUTING guide](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md).

**Comment by outdooricon** [comment]
@samit4me Thank you for the response! I should've thought to look in package.json and see what it was doing, my bad. As requested, I've created a pr to reference the other cmd: https://github.com/mxstbr/react-boilerplate/pull/1204

**Comment by samit4me** [comment]
Thank you for that, nice work 👌

**Comment by samit4me** [comment]
PR has been merged
