### ISSUE TITLE
Update testing documentation

### ISSUE THREAD

**Issue by samit4me** [mxstbr/react-boilerplate#1206]
Just recently [Mocha](https://mochajs.org/), *the JavaScript testing framework* was swapped out for [Jest](https://facebook.github.io/jest/) as it brings features like snapshot testing, built in coverage reporting, mocking capabilities, and huge performance gains (see #980).

Currently, this is only in the `dev` branch and the docs have not yet been updated. Moving forward the [Testing documentation](https://github.com/mxstbr/react-boilerplate/tree/master/docs/testing) will need updating, so if you have a passion for testing and / or writing docs, we would 😍 for you to submit a PR. It will need to cover all current topics at minimal and it would be great if it could at least mention some of the extra capabilities of Jest like a snapshot testing.

If you have some suggestions on what you would like to see in the Testing docs, please leave a comment if you think it will add value and help improve the docs.

**Comment by DJTB** [comment]
Could be helpful to add a link in the Jest section's resources to these videos by Kent C. Dodds (covers watch and snapshot).

[Free egghead videos: Test Javascript with Jest](https://egghead.io/lessons/javascript-test-javascript-with-jest?pl=testing-javascript-with-jest-a36c4074)

**Comment by outdooricon** [comment]
fwiw, I'm trying to tackle this right now! I'm not sure how amazing it will be, but I'm hoping that we can count on the rest of the great docs out there to fill in the gaps.

**Comment by outdooricon** [comment]
PR is up!
