### ISSUE TITLE
RFC: Collaboration Guidelines

### ISSUE THREAD

**Issue by Dattaya** [mxstbr/react-boilerplate#1209]
What do you guys (@mxstbr, @oliverturner, @justingreenberg, @gihrig, @sedubois, @chaintng, @samit4me, @amilajack (whoa, so many collaborators, is it a full list :smiley: ?) ) think about adding some "Collaboration Guidelines." Usually everyone waits for Max to merge a PR, we can create a rule that it can't be merged without two or three sign offs (comments with 'LGTM' or the like), unless it's a non-trivial contribution like using a GraphQL client, switching testing framework to Jest, etc. In addition if one of the collaborators against a change, then @mxstbr decides whether to merge it or not.

@mxstbr, if you haven't done already, you can restrict push access to master branch. ["Restrict who can push to this branch"](https://help.github.com/articles/about-branch-restrictions/) option has to be somewhere in repository settings. I can see that when you check "Protect this branch" it by default protects it from force pushes according to description: "Disables force-pushes to this branch and prevents it from being deleted."

**Comment by mxstbr** [comment]
> Usually everyone waits for Max to merge a PR, we can create a rule that it can't be merged without two or three sign offs (comments with 'LGTM' or the like), unless it's a non-trivial contribution like using a GraphQL client, switching testing framework to Jest, etc.

This sounds very very good to me. Let's wait for two approved reviews and then merge to `dev`, no matter if I'm around or not!

In reality, you folks have been doing most of the work (and doing a much better job at it than I have!) and have been blocked by me not having as much time as I'd like, so this would speed up the process a lot.

*I'd also like to look into automating releases so I don't have to be around for those either, but let's make that a second step.*

**Comment by Dattaya** [comment]
@mxstbr, what do you think about a rule that a PR must be open for at least two (?) days before merging, so everyone has time to take a look/make a case against it?

**Comment by mxstbr** [comment]
That also sounds good to me! We should use https://github.com/danger/danger-js to enforce these rules maybe? /cc @orta

**Comment by gihrig** [comment]
@Dattaya Great idea! _really_ needed.

I'm concerned about approval in the form of a simple LGTM though. I would like to see approvers run a basic acceptance test script, and confirm that those tests pass in their environment. This is what I do for dependency updates e.g. #1162. It's time consuming and error prone to do this work manually, so it would be great if these tests could be automated.

I have found a couple of tools that look promising in this area: [CodeceptJS](http://codecept.io/) and [NightmareJS](http://www.nightmarejs.org/).

**Comment by Dattaya** [comment]
Thanks for the links @gihrig. Ideally we would add those tests to the CI workflow instead of doing it manually. I don't know if it's possible, but quick search led me to this: https://github.com/travis-ci/travis-ci/issues/5002 so I assume it is.

**Comment by orta** [comment]
FWIW, Danger might feel a bit weird with that, as it would require an extra CI build to un-mark it as read ( the last approval would need to re-trigger CI for example )

Once I get hosted Danger's up and running, that may become feasible

**Comment by Dattaya** [comment]
I've found this: https://github.com/integrations/lgtm 

From their overview:
> Pull requests are locked and cannot be merged until the minimum number of approvals are received (two, by default.) Project maintainers can indicate their approval by commenting on the pull request and including LGTM, looks good to me, in their approval text.

My understanding is that it will work for every protected branch of a repository. It seems to have a bug—https://github.com/lgtmco/lgtm/issues/40; 'disapprovals' are being currently discussed—https://github.com/lgtmco/lgtm/issues/49. Last commit is from 2 month ago.

**Comment by mxstbr** [comment]
I've used LGTM.co before somewhere, and it worked perfectly fine, 👍  from me!
