### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#121]
This boilerplate needs a logo to show "window shoppers" we're committed and are going to maintain it for the foreseeable future.

Ideally it'd be an icon that works on it's own, and then *maybe* the text "react boilerplate" typeset nicely. Important requirements are that it's recognizable and can scale down well so we can use it as a favicon!

**Comment by mxstbr** [comment]
@okonet do you want to take a stab at this?

**Comment by okonet** [comment]
I could give it a try. Do you have any particular ideas in mind?

**Comment by mxstbr** [comment]
Not really, would love something simple like you did with React Vienna :+1:

**Comment by mxstbr** [comment]
A first proposal by @ev1stensberg via [twitter](https://twitter.com/ev1stensberg/status/703675527366905856):

<img src="https://pbs.twimg.com/media/CcP1KZrW8AAvsd6.jpg" height="350" />

Not sure about the direction here, what do the diamonds have to do with a boilerplate/foundation? Also doesn't scale very well to small sizes, nevermind to being a favicon:

<img src="https://pbs.twimg.com/media/CcP1KZrW8AAvsd6.jpg" height="50" />

**Comment by okonet** [comment]
Agree, this not gonna work.

**Comment by Connorelsea** [comment]
Saw this on Twitter and wanted to give it a try. Here are some quick ideas. Let me know what you guys think and we can iterate if needed or discard if you're not a fan.

<img width="576" alt="reactboilerplatelong copy" src="https://cloud.githubusercontent.com/assets/1844458/13686283/bc0792f6-e6da-11e5-861d-b058ae0a619e.png">

<img width="500" alt="reactboilerplatesimple" src="https://cloud.githubusercontent.com/assets/1844458/13685894/8b86b1fe-e6d8-11e5-98bb-75dd8ab7f1d4.png">

**Comment by mxstbr** [comment]
Thanks for taking the time Connor! What does the planet ring signify? (I'm not sure I dig the capitalization, I think the name of the project is "react boilerplate")

**Comment by elioqoshi** [comment]
@mxstbr here is my proposal, based on boilerplate style in the literal meaning.
![draft-01](https://cloud.githubusercontent.com/assets/5436686/13699053/3d48b1cc-e778-11e5-8ee0-3437aea1b01d.jpg)

**Comment by mxstbr** [comment]
Ohh I like where this is going @elioqoshi! What do you think, would maybe a stylized version of the react logo inside the boilerplate instead of the grill work?

**Comment by elioqoshi** [comment]
Good idea @mxstbr ! Here are 2 variations :)

![react boilerplate](https://cloud.githubusercontent.com/assets/5436686/13699431/93df7906-e77a-11e5-8ebb-8b54f22b05f5.jpg)
![react boilerplate2](https://cloud.githubusercontent.com/assets/5436686/13699432/9404b14e-e77a-11e5-999f-eeaca0d355f1.jpg)

**Comment by elioqoshi** [comment]
P.S: The font is Lato Bold, so it's open source of course

**Comment by timseverien** [comment]
Really like the first flavour of @elioqoshi’s logo with the react logo (https://cloud.githubusercontent.com/assets/5436686/13699431/93df7906-e77a-11e5-8ebb-8b54f22b05f5.jpg)

**Comment by mxstbr** [comment]
Really liking that first version!

**Comment by elioqoshi** [comment]
Thanks! Let me know what you will decide so I can export the final files :)

**Comment by mxstbr** [comment]
Definitely going with that first version! Which files would you export? I reckon we need the icon as a `.svg` and a `.ico` for usage as a favicon, and then something for the readme on github as a banner sort of thing. What do you think?

**Comment by elioqoshi** [comment]
Sure! Let me get back to this

**Comment by elioqoshi** [comment]
@mxstbr here we go:
http://elioqoshi.me/owncloud/index.php/s/Qhf5JXCFpnwvgSx

What do you have in mind for a banner?

**Comment by elioqoshi** [comment]
Here are 2 banner proposals:

![banner plain-01](https://cloud.githubusercontent.com/assets/5436686/13701006/017b0494-e785-11e5-85e8-20a25e818daa.jpg)
![banner-01](https://cloud.githubusercontent.com/assets/5436686/13701007/0192aa9a-e785-11e5-962d-e239172cc763.jpg)

**Comment by mxstbr** [comment]
The background on the second one is *awesome*, digging that a lot!

**Comment by mxstbr** [comment]
What do you think? I love it! https://github.com/mxstbr/react-boilerplate/blob/issue/branding-v3/README.md 

![screen shot 2016-03-11 at 12 49 53](https://cloud.githubusercontent.com/assets/7525670/13701384/d5fa1ac8-e787-11e5-9a0f-19a95fc2c504.png)

**Comment by mxstbr** [comment]
@elioqoshi I've added you as a collaborator at https://github.com/mxstbr/react-boilerplate-brand, would you mind pushing all the assets up there? Amazing work, thanks so much!

**Comment by elioqoshi** [comment]
@mxstbr Awesome! I'm really bad at git, so never learned how to push things (no pun intended). I can upload them though, but the repo is empty and doesn't allow manual upload I guess.

**Comment by mxstbr** [comment]
@elioqoshi Fair enough, I've added a README so you should be able to drag'n'drop!

**Comment by elioqoshi** [comment]
@mxstbr here we go!
https://github.com/mxstbr/react-boilerplate-brand/tree/master/Assets

Enjoy the new identity :) Maybe we will meet in Vienna at some point

**Comment by mxstbr** [comment]
Awesome, thanks so much! Definitely ping me if you're around and we'll grab a coffee or a beer.

**Comment by mxstbr** [comment]
@elioqoshi Could you maybe also upload the source files you used to make the banner/logo/icon? That'd help a lot if we decide to tweak it further down the line!

**Comment by oliverturner** [comment]
_Loving_ the logo. Stellar work @elioqoshi :smile: 

Just a question: do you think that a tweak to the contrast helps make the text pop a little more? something like...

https://dl.dropboxusercontent.com/u/2439670/react-boilerplate.png

**Comment by brotzky** [comment]
Nice work. I'll update the website this weekend with the logo and possibly look into setting up the documentation section.
