### ISSUE TITLE
can't access subdomain from browser

### ISSUE THREAD

**Issue by mydearxym** [mxstbr/react-boilerplate#1215]
thanks for the work.

i am little confused with [Server Configurations](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/server-configs.md), it's seems *Always serve index.html for any request* ?

[here is a example](http://deploy-preview-1008.react-boilerplate.netlify.com/)。

i can't goto http://deploy-preview-1008.react-boilerplate.netlify.com/features  directly from browser , instead i have to goto http://deploy-preview-1008.react-boilerplate.netlify.com first , then click the features button to the features page。

can't i just goto feature page from browser?

**Comment by peter-mouland** [comment]
This boilerplate doesn't _yet_ have server-side rendering, which means you have to setup your server to accept any url and push them all to the homepage.  depending on the client-side router setup, it should then load the correct page based on the url in the browser

**Comment by mydearxym** [comment]
@peter-mouland thanks!
you mean the current solution is set up a server parse the coming url ,  then redirect the url like

``` bash
http://www.example.com/index?path=features
```

and let client-side load the correct page based on the *path* params ?

**Comment by mxstbr** [comment]
We delegate the routing to client side with `react-router`, please read their documentation: https://github.com/reacttraining/react-router

**Comment by mydearxym** [comment]
found answer [here](http://stackoverflow.com/questions/36304302/how-can-i-configure-react-router-to-with-nginx-cherrypy-and-my-current-reactjs-a)
