### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#122]
I'm thinking of setting up a simple website to have a centralized place with all the documentation we'll add. (see #14)

The main focus should be that developers can quickly find the information they're looking for, and when they've found it the information is easily scannable.

I'm not a great designer, so I'd love if somebody could jump in and design a basic mockup with some typography rules, a layout and a color scheme which I can take and turn into code!

**Comment by brotzky** [comment]
I can probably work on this. I might skip the .psd mockup and go straight in browser. 

I'm thinking a static site gen that builds to a couple simple pages? A ember-cli / redux type website may be overkill documentation for a boilerplate.

**Comment by mxstbr** [comment]
Sounds good!

**Comment by brotzky** [comment]
Sweet, I'll get started on something simple. :+1:

**Comment by brotzky** [comment]
repo is setup here for future readers: https://github.com/brotzky/react-boilerplate-site

**Comment by luandro** [comment]
Looking good!

**Comment by mxstbr** [comment]
Work is going on over at https://github.com/brotzky/react-boilerplate-site, closing this issue! Thanks @brotzky for the initial efforts!
