### ISSUE TITLE
HMR Sync does not reload UI in browser when making change in any .js file

### ISSUE THREAD

**Issue by rmaroun** [mxstbr/react-boilerplate#1220]
## Description

Hi, I am using version 3.3.3 but I still have the issue with HMR sync:
The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.logUpdates @ process-update.js?e13e:81applyCallback @ process-update.js?e13e:49(anonymous function) @ process-update.js?e13e:57
process-update.js?e13e:89 [HMR] - ./app/containers/HomePage/index.js

Thanks for your help

## Steps to reproduce

I reset the project with npm run clean and added some translations in en.json when updating the file then the HMR reloads the page but when I update the index.js then nothing happens and I get the message.

# Versions

- Node/NPM: v3.10.8
- Browser: Chrome 54.0.2840.87 m (64-bit)

**Comment by DJTB** [comment]
You can change HomePage to inherit from `Component` instead of `PureComponent` and the hot reloading will work in the meantime.

**Comment by rmaroun** [comment]
Thanks @DJTB. It is now working. It this a bug? What is the impact of using React.Component instead of the PureComponent? Thanks.

**Comment by GGAlanSmithee** [comment]
@rmaroun 

> It is now working. It this a bug?
it's a known limitation of react hmr prior to react-hot-loader@3

>What is the impact of using React.Component instead of the PureComponent? Thanks.
`PureComponent` will only re-render as props or state changes: [ref](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)

**Comment by rmaroun** [comment]
@GGAlanSmithee thanks for the clarification :)! I will then close the issue.
