### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by basimhennawi** [mxstbr/react-boilerplate#1222]
I got this error while loading a **css** file, is there anything to do with loaders in **weback.base.babel.js** file? Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/10829464/20235326/8a06e2dc-a897-11e6-91a3-dde40f91b308.png)

**Comment by samit4me** [comment]
This boilerplate uses [`styled-components`](https://styled-components.com/) allowing you to write your CSS in your JavaScript, for more info check out the [CSS docs](https://github.com/mxstbr/react-boilerplate/tree/master/docs/css).

If you would still like to import CSS files, you can do so by adding the `css-loader` and `style-loader` to `webpace.base.babel.js` like you suspected. See the [official webpack docs](https://webpack.github.io/docs/stylesheets.html) for more info.
