### ISSUE TITLE
Trouble configuring webpack to add flexbox

### ISSUE THREAD

**Issue by meilers** [mxstbr/react-boilerplate#1227]
I'm having a hard time adding a new css loader to support [flexbox](https://github.com/roylee0704/react-flexbox-grid). Here's what I have in my base webpack configuration file:

{
test: /.css$/,
loader: 'style!css?modules',
include: /flexboxgrid/,
}, {
// Transform our own .css files with PostCSS and CSS-modules
test: /.css$/,
exclude: [/node_modules/,/flexboxgrid/],
loader: ''style-loader!css-loader?localIdentName=[local][path][name][hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader',
}, {
// Do not transform vendor's CSS with CSS-modules
// The point is that they remain in global scope.
// Since we require these CSS files in our JS or CSS files,
// they will be a part of our compilation either way.
// So, no need for ExtractTextPlugin here.
test: /.css$/,
include: /node_modules/,
exclude: /flexboxgrid/,
loaders: ['style-loader', 'css-loader'],
},

And here's the error I get in the console:
"Dynamic page loading failed Error: Module build failed: Unknown word (5:1)"

![screen shot 2016-11-11 at 4 43 38 pm](https://cloud.githubusercontent.com/assets/2792041/20269750/88eb31ac-aa52-11e6-9749-9af53280b111.png)

Any ideas?

**Comment by samit4me** [comment]
@meilers Do you have a repository you could share demonstrating the problem? This would be rather difficult to debug without seeing the code!

**Comment by meilers** [comment]
@samit4me Never mind. I followed the instructions on their page and it turns out I didn't need to exclude flexbox from my css loaders after all. Now everything works :) Thanks!
