### ISSUE TITLE
Deployed website/app doesn't come up

### ISSUE THREAD

**Issue by GaryThomas** [mxstbr/react-boilerplate#1228]
## Description

I cloned the repo and ran 'npm run setup;npm run build' and then pushed './build/' to my webserver.
When I try and run that, it just hangs :-(

## Steps to reproduce

  http://www.mlbassoc.com/testrb

# Versions

- Node/NPM:
- Browser:

**Comment by GaryThomas** [comment]
I see now what the problem is: all deployed files assume they are at the root of the web server.

Is there a way to configure this to allow deployment to a subfolder, as in the example URL?

**Comment by samit4me** [comment]
Have you tried adding your subfolder to the webpack option `output.publicPath`? Try adding it to `webpack.prod.babel.js`? For more info check out the  [webpack docs](http://webpack.github.io/docs/configuration.html#output-publicpath) and let us know how that goes?
