### ISSUE TITLE
ESlint errors in Atom editor

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#1233]
While working on dependency update #1225 I observed many linting errors in the Atom editor.

These errors do not appear when linting from the terminal, only in Atom.
The errors first appear in `98f2d0d` feat(core): Move to Jest for testing (#980)

Atom: 1.11.2
linter-eslint 8.0.0
OS X 10.11.6

To reproduce:
Open `/app/app.js`  (or other .js files) in editor

![image](https://cloud.githubusercontent.com/assets/1481063/20282317/1a5d4c40-aa69-11e6-89d1-2756a0a6b058.png)

**Comment by gihrig** [comment]
A solution that is working for me is make package.json conform to this [#980 comment](https://github.com/mxstbr/react-boilerplate/pull/980#issuecomment-247111015)

The original works (provided `webpack.test.babel.js` is restored):
`package.json`
````json
"import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.test.babel.js"
        }
      }
````

The recommended change works:
`package.json`
````json
"import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.prod.babel.js"
        }
      }
````

The way it ended up in #980 _does not_ work. It produces the errors listed in the OP:
`package.json`
````json
"import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.dev.babel.js"
        }
      }
````

This make no sense to me, I'm not a webpack wizard. `webpack.test.babel.js` (removed in #980) is the only file with a `resolve` key which I (obviously wrongly) assume is the reason for the `import/resolver` key in the blocks above.

I have tried:

 - Copying keys from `webpack.test.babel.js` one at a time, to `webpack.dev.babel.js`.
 - Entering the `resolve` key from `webpack.test.babel.js` directly into `package.json`
 - Entirely removing the `settings` key from `package.json`

None of these actions had any effect on the errors listed in the OP.

I have opened PR #1261 with this change.

**Comment by Dattaya** [comment]
I'm also not a webpack wizard 😄 and don't have Atom installed, but have one idea, what if you replace:
```js
const pkg = require(path.resolve(process.cwd(), 'package.json'));
```
with 
```js
const pkg = require(path.resolve(__dirname, '../..', 'package.json'));
```
And if that doesn't help, replace `process.cwd()` everywhere in `webpack.dev.babel.js`. IMO `process.cwd`'s are nasty, I always avoid them and prefer `__dirname` instead.
