### ISSUE TITLE
Firefox dll.js warning: mutating the [[Prototype]] of an object will cause your code to run very slowly...

### ISSUE THREAD

**Issue by jforaker** [mxstbr/react-boilerplate#1240]
FYI - I get this error in Firefox v46 / Mac OSX

` mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

from 

`reactBoilerplateDeps.dll.js line 6966 > eval`

Also throws this doozie, and my app is near unusable.

![image](https://cloud.githubusercontent.com/assets/2042031/20353550/3b1854e4-abe9-11e6-9d25-40f3d241e278.png)

Any thoughts? I can't post code examples because its a large and private app. But it is bulletproof and snappy in Chrome/Safari. Could I be doing something wrong?  

using RB `version: '3.0.0'` 
![image](https://cloud.githubusercontent.com/assets/2042031/20354272/9958a246-abeb-11e6-9294-07a1d6433aaf.png)

**Comment by samit4me** [comment]
Well, that certainly isn't good, thank you for submitting an issue. Is it specifically with v46 of Firefox ONLY?

Before I look into the issue, could you please try the following and report back:

1. Get a fresh clone of the `master` branch of this repo and test in the same environment.
1. If `master` fails, please try the `dev` branch.
1. If `master` works, please install all the same `dependencies` and `devDependencies` you have in your private repo.
1. If that fails, please share your `package.json` file.
1. If that works, well it's going to be near impossible to debug without seeing any code that can reproduce the error.

**Comment by jforaker** [comment]
Yes it was v46 only. However, I updated my build config to more closely match the current version and the problem seems to have gone away. If it happens again, I will try the above steps. Thanks.
