### ISSUE TITLE
Redux-Forms integration into redux and middleware

### ISSUE THREAD

**Issue by JustinJKlein** [mxstbr/react-boilerplate#1244]
## My Issue
Integrating redux-forms

## Description
I am having difficulty tying my redux-form installation into the redux and middleware setup we have in the boilerplate. I have added it to the combineReducers and imported the node modeul by following the docs but I can not even get it to enter input into the field. It just stays blank when typing with the cursor in the field. 

If any of you guys have suggestions that would be a big help.

Thanks in advance

## Steps to reproduce
npm  install --save redux-form

**Comment by nhducit** [comment]
Did you follow to this setup? http://redux-form.com/6.2.0/examples/immutable/

**Comment by JustinJKlein** [comment]
Thanks a ton! I am going to try that now. I can absolutely see now why that would likely be the problem.

**Comment by samit4me** [comment]
@JustinJKlein it sounds like @nhducit help you resolve the problem, are you happy for this issue to be closed?

**Comment by carlos-peru** [comment]
In case somebody is struggling with this I have a sample integration: https://github.com/carlos-peru/react-boilerplate-redux-form

**Comment by theRealFakeRock** [comment]
Hello, I recently encountered this problem. Encase anyone else finds this thread the solution is to import redux-form as "redux-form/immutable", everywhere. 
ex:
`import { Field, reduxForm } from 'redux-form';`
becomes
`import { Field, reduxForm } from 'redux-form/immutable';`

and 

`import { reducer as formReducer } from 'redux-form';`
becomes
`import { reducer as formReducer } from 'redux-form/immutable';`
