### ISSUE TITLE
can't use request.js with spring

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1245]
I am trying to modify this file 

https://github.com/mxstbr/react-boilerplate/blob/master/app/utils/request.js The problem is it handle the errorMessage in statusText, which is not something I can set from my Spring backoffice.

I have my error message in the body of the response.

This is how I solve it so far : http://pastebin.com/LfiXbcHt

I have tried many different way of makint it work it, but I always break the logic implemented in this commit : https://github.com/mxstbr/react-boilerplate/pull/1122/commits/48eecac3b53fb3267a4beddc7a0644926f3483c3

Any help would be appreciated

**Comment by samit4me** [comment]
I'm not sure I understand the question! Is it possible for you to share a sample API response you are trying to process?

According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText), the `statusText` is simply the status message that goes with the status code (e.g. 200 OK), so if the server responded with "Successful 2xx" the `statusText` won't actually be used. Again, it's difficult without an example.

**Comment by kopax** [comment]
@samit4me The problem I have is : 

In the current `request.js`

    function checkStatus(response) {
      if (response.status >= 200 && response.status < 300) {
        return response;
      }

      const error = new Error(response.statusText); <== this works because statusText is a string, Error expect a string so all good. 
      error.response = response;
       // throwing the error here will work perfect because the message exist 
      throw error;
    }

On this [commit](https://github.com/mxstbr/react-boilerplate/pull/1122/commits/48eecac3b53fb3267a4beddc7a0644926f3483c3#diff-b51f2d70361e7739047f6e675cb046c2R37) : 

    - * @return {object}           An object containing either "data" or "err"
    + * @return {object}           The response data

So the error will be catched correctly and this make the unit test work because we can catch the error normally.

Now Imagin the error message is in the body. How can I have it available here ?

          const error = new Error(response.body)

This doesn't work, because body is a stream and cannot be read. You need to call response.json() in order to have the body content, as I did in the [pastbin](http://pastebin.com/LfiXbcHt)

But this break the unit test.

**Comment by samit4me** [comment]
I am still confused and not sure what you are asking, I'm really sorry 🤔

What is it that you are trying to achieve? It sounds like you've modified the request.js file to suit your needs but it's not working and your looking for help? Is that correct?

I can only assume so I'm probably wrong, but it kind of sounds like you want request.js to throw an error if the status is NOT 2XX and also if it is 2xx but has an error in the actual response???

**Comment by kopax** [comment]
@samit4me yes that's correct. The way it was made I couldn't send an error message string from the rest api.

I want in request.js the function checkStatus to throw an error if the status is not 2XX. I need to use the error message from the response body.
