### ISSUE TITLE
Add information about naming convensions to the README

### ISSUE THREAD

**Issue by web2style** [mxstbr/react-boilerplate#1247]
For example, why in `app/components/Button` directory `StyledButton.js` file begins with capital letter and `buttonStyles.js` starts from lowercase letter. And `app/global-styles.js` is even with hyphen.

**Comment by jesnil01** [comment]
I think the logic is to use capital letter for components.

StyledButton.js -  renders a button and therefore should be in capital.
buttonStyles.js - just holds styles to be used in other components.

Not sure about the logic behind global-styles.js though.

**Comment by samit4me** [comment]
You right it's not exactly clear. This repo uses Airbnb style guides, so yes @jesnil01 is 💯 correct.

Currently there is an open issue #1213 to add some docs about this. Feel free to open a PR against that ticket if you have some good ideas, there is more info in that issue. Cheers

**Comment by gihrig** [comment]
I agree with @samit4me  on moving discussion to #1213, so I'll close this issue. but please feel free to contribute there.
