### ISSUE TITLE
Add an ability to change port

### ISSUE THREAD

**Issue by okonet** [mxstbr/react-boilerplate#125]
ATM the port number is hardcoded in several places which makes it hard to change. I think it would be much better to be able to provide optional port number trough env variables like:

```
PORT=4000 npm start
```

**Comment by mxstbr** [comment]
:+1: Good idea!

**Comment by fireantik** [comment]
It might also be worth considering moving default port to something less used, like 3001, because App Cache and ServiceWorker then messes every other app that will be tested on localhost:3000.

**Comment by mxstbr** [comment]
They don't anymore in v3 because they are both disabled in development there. :+1:

**Comment by okonet** [comment]
Btw how to remove those caches? It's very annoying :)

**Comment by mxstbr** [comment]
`chrome://serviceworker-internals` and `chrome://appcache-internals`

**Comment by mxstbr** [comment]
Done with 42b3f78!
