### ISSUE TITLE
Dynamic page loading failed Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

### ISSUE THREAD

**Issue by angelosembrano** [mxstbr/react-boilerplate#1254]
I tried to remove all references to `react-intl` because there's not much use of it in my web app.

Your docs simply said to remove `<IntlProvider>` from app.js but there's none already there. Figures that you seemed to move it all with `<LanguageProvider>` and thus from there remove all references to it, along with `i18n.js`.

But then I still get this error whenever I try to navigate to another route.

```
Dynamic page loading failed Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
```

Why is that?

**Comment by samit4me** [comment]
Closing this in favour of #1257
