### ISSUE TITLE
How to test i18n components

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1256]
By using `injectIntl`, it is possible to get locale message in JS:

    import { injectIntl, intlShape } from 'react-intl';
    ... props
      intl   : intlShape.isRequired,
    ... render 
    const { formatMessage } = this.props.intl;
    let closeLabel = formatMessage(messages.closeAlert);
    ....
    export default injectIntl(Alert);

The problem is now the unit test of my Alert is complaining because of the absence of `<IntlProvider>`

If I wrap my test with a `<IntlProvider messages={{}}>`, it complain of the absence of the connect store : 

        Invariant Violation: Could not find "store" in either the context or props of "Connect(LanguageProvider)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(LanguageProvider)".

Does anyone know how to solve this without importing the whole context into the test ?

**Comment by justingreenberg** [comment]
https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl
