### ISSUE TITLE
How to fully remove react-intl in boilerplate?

### ISSUE THREAD

**Issue by angelosembrano** [mxstbr/react-boilerplate#1257]
The docs seems to be outdated, it says [here](https://github.com/mxstbr/react-boilerplate/blob/0f88f55ed905f8432c3dd7b452d713df5fb76d8e/docs/js/i18n.md#removing-i18n-and-react-intl) that `You can remove react-intl modules by first removing the IntlProvider object from the app/app.js`, but there's no IntlProvider in `app.js` already. Instead I found it at the LanguageProvider.
(PS. Please do update your docs with respect to this).

So I did that, but I don't the real gist of what this means: `and by either removing or not selecting the i18n text option during component scaffolding.`

I assumed that I remove any references to `translationMessages` and `il8n` in this code snippet, am I correct in my understanding?

### app.js
```
// Hot reloadable translation json files
if (module.hot) {
  // modules.hot.accept does not accept dynamic dependencies,
  // have to be constants at compile-time
  module.hot.accept('./i18n', () => { //'./i18n',
    render(translationMessages);
  });
}

//Chunked polyfill for browsers without Intl support
if (!window.Intl) {
  (new Promise((resolve) => {
    resolve(System.import('intl'));
  }))
    .then(() => Promise.all([
      System.import('intl/locale-data/jsonp/de.js'),
    ]))
    .then(() => render(translationMessages))
    .catch((err) => {
      throw err;
    });
} else {
  render(translationMessages);
}
```

I have did as above, **I removed any LanguageProvider and il8n** references, but to no avail, when I navigate to a new route I declared in `router.js`, it states this [issue](https://github.com/mxstbr/react-boilerplate/issues/1254).

I have traced carefully the origin of the error by switching through different devtools, and the error points at this specific line in `routes.js`.

### routes.js
```
const errorLoading = (err) => {
  console.error('Dynamic page loading failed', err); // eslint-disable-line no-console
};
```

Why is that?

**Comment by DJTB** [comment]
If you've removed LanguageProvider and il8n, in `app.js` you can also remove all the above regarding module.hot and the polyfill, replacing it simply with:
```
// Initial render
render();
``` 
HMR should work for normal Components still (excepting PureComponent currently, but new HMR and new React Router in future updates should address this).

**Comment by angelosembrano** [comment]
I see, thanks @DJTB. One last thing though. 

I did all that as above, but this still shows whenever I navigate to a new route:

`Dynamic page loading failed Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.`

Note that I have done as what you have stated above.

**Comment by DJTB** [comment]
Have you already run `npm run clean` or is this the example project?
After cleaning you still need to remove any references that try to use react-intl like:```
import { FormattedMessage } from 'react-intl';
<FormattedMessage {...messages.header} />
```
Those two lines still remain in `App/containers/HomePage/index.js` after cleaning the example project.
