### ISSUE TITLE
Livereload from a remote machine?

### ISSUE THREAD

**Issue by ezuk** [mxstbr/react-boilerplate#1259]
Hi there,

My development workflow is:

1. A VM sitting on a box somewhere in my LAN runs `react-boilerplate`.
2. From a Chromebook, I connect to that VM via SSH and edit files in Vim.
3. When I need to see the site, I go to `192.168.0.1:3000` -- the IP of the host machine, which forwards the port over to the VM.

It's weird, but it does work. The only thing that doesn't quite work is livereload. I recognize this isn't strictly exclusive to React-boilerplate but I was wondering if anyone might have any tips or ideas as to how to get Livereload to work in this convoluted scenario.

**Comment by samit4me** [comment]
Not sure I fully understand the setup, but I've previously worked in a VM and from memory live reload worked, but the VM had its own static IP which I could access or add a DNS entry to make it nicer.
