### ISSUE TITLE
Fix CSS processing

### ISSUE THREAD

**Issue by okonet** [mxstbr/react-boilerplate#126]
ATM requiring any CSS from 3rd party authors (i.e. located in node_modules) will be piped through the same pipeline as project's CSS. This means, CSS will be procssed as CSS-modules which, in turn, hides all global CSS making it impossible to consume 3rd party CSS.

**Comment by mxstbr** [comment]
On :fire: today, great catch!

**Comment by okonet** [comment]
Just trying to use it on a real project... Will submit PRs.

**Comment by mxstbr** [comment]
See #115 :wink:

**Comment by okonet** [comment]
Just found out that cssnano was also striping relative URLs to images, making build and serve fail. This should also be fixed (by removing cssnano?). css-loader does CSS minification so I think we don't need cssnano.

**Comment by mxstbr** [comment]
Sounds good to me!

**Comment by ewnd9** [comment]
@okonet did you solve the problem of external css? I ended up with splitting css loader into two parts with different regexps: default for externals (e.g. bootstrap) and css-modules for components.

**Comment by okonet** [comment]
Yeah, same here. I've also split them to 2 loaders. I'll try to find some time and do a PR for this.

**Comment by mxstbr** [comment]
Done in #198!
