### ISSUE TITLE
Implement global selectors in root App

### ISSUE THREAD

**Issue by basimhennawi** [mxstbr/react-boilerplate#1263]
I want to implement global selector, in root App for example, that can be reached within any container.

**Use case:**
This global shared selector will be holding the session user object after login.

What is the best practice for implementing this selector?
Also, want to know where to implement the reducer too that will set the user object after login via `Login` container?

Thanks in advance.

**Comment by samit4me** [comment]
The user object is something that will be "App" wide, so I personally would place your reducers etc in the `containers/App/` directory. You can then import the selectors you want into any container you want. I hope this helps, but seeing as you opened the issue 2 days ago, maybe not. What did you end up doing?

**Comment by carlos-peru** [comment]
Yea, I agree with sami4me. I'm working on the same thing. Both the reducer and selector should be in containers/App/ because that's the parent container and we want all the children to have access to it. The trick is to add the reducer in combineReducer in reducers.js like:

# app/reducers.js
import appReducer from 'containers/App/reducer';
...
export default function createReducer(asyncReducers) {
  return combineReducers({
    route: routeReducer,
    language: languageProviderReducer,
    global: appReducer,
    ...asyncReducers,
  });
}

Then the children containers can just check the state of global through the selector.

**Comment by CHRISTOPHERDIEHL** [comment]
How would one go about getting the selectors in the children containers?

**Comment by samit4me** [comment]
I would have thought something like `import { theSelector } from 'containers/App/selectors';` should work! Does that answer your question @CHRISTOPHERDIEHL ???

**Comment by CHRISTOPHERDIEHL** [comment]
Haha thanks @samit4me! I was having a blonde moment!

**Comment by CHRISTOPHERDIEHL** [comment]
@samit4me  I implemented almost a carbon copy of what is in the example, but when I navigate to a child container of App the redux store is lost. I am confused as to why the store is being held inside the child containers and not the parent container, app. Any thoughts or suggestions?

**Comment by samit4me** [comment]
@CHRISTOPHERDIEHL Thank you for providing a code sample, it would be impossible without it. I cloned your repo and got something working, but there were quite a few errors being thrown and I don't have time to debug them all, but this is what I did:
 
#### Step 1: 
In `package.json` change `"react": "^15.3.2",` 👉 `"react": "15.3.2",`.

#### Step 2:
In `components/DashComponent` change `<BootstrapTable ref='table' data={  }>` 👉 `<BootstrapTable ref='table'>`.

#### Step 3:
In `containers/DashBoard` replaced the class component with the following:
```
export class DashBoard extends React.Component { // eslint-disable-line react/prefer-stateless-function
  render() {
    return (
      <div>
        {`User email is ${this.props.user}`}
      </div>
    );
  }
}
```

#### Step 4:
In `containers/Login` removed both `componentWillMount()` and `handleSubmit()` and replaced them with the following:
```
  componentWillUpdate(nextProps) {
    const { user, router } = nextProps;
    if (user) {
      router.replace('/dashboard');
    }
  }

  handleSubmit(event) {
    event.preventDefault();
    // Mock login
    // NOTE: using refs in this way is deprecated
    const { email, pw } = this.refs;
    if (email.value && pw.value) {
      this.props.loginUser(email.value);
    }
  }
```

#### Step 5:
I then did `npm start` opened the homepage, entered in a fake email and password, clicked **Login** and then I was taken to the `/dashboard` which showed me the email address I entered as it now lives in the store.

This proves to me that the state is persisted between routes. I hope this helps and good luck!

**Comment by CHRISTOPHERDIEHL** [comment]
Aaa sorry, I forgot to take all those extra data components out @samit4me . I had to strip part of an existing application and repost it to make it public. In the process, I probably grabbed the wrong branch with incomplete code..

Thank you kindly, and hope you have a nice night! @samit4me

**Comment by samit4me** [comment]
Does any of the above answered your question @basimhennawi???

**Comment by basimhennawi** [comment]
@samit4me Yes. Actually, I moved to this approach back then (3 days ago).
**_For reducer_**: Add a new `reducer` file under `containers/App` and already implement and then import and add it in `app/reducers.js` as @carlos-peru mentioned.
**_For selector_**: I already use the one with the boilerplate under `containers/App` too, exporting extra selectors.

Thanks guys!
