### ISSUE TITLE
Unit test timeout behavior uncontrollable lead to "Chrome was not killed in 2000 ms, sending SIGKILL"

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1266]
I have some strange behavior when running test.
I have tried to diagnosis this issue but it remain unexplained.

I have this error that come up sometimes : 

```bash
=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================

Finished in 10.745 secs / 0.628 secs

25 11 2016 00:45:06.335:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
```

instead of 

```bash
=============================== Coverage summary ===============================
Statements   : 79.87% ( 1246/1560 )
Branches     : 45.35% ( 200/441 )
Functions    : 68.58% ( 203/296 )
Lines        : 80.62% ( 1227/1522 )
================================================================================

Finished in 1.168 secs / 0.807 secs

SUMMARY:
✔ 382 tests completed
```

The only difference between the working state and the not working state is almost nothing.

I have replaced in a file :  

```javascript
  return `
    position: relative;
    // Prevent columns from collapsing when empty
    min-height: 1px;
  `
```

by this :  

```javascript
  return `
    position: relative;
    /* Prevent columns from collapsing when empty */
    min-height: 1px;
  `
```

Am I the only one to face that kind of bugs with the unit tests tools ?

**Comment by samit4me** [comment]
Unfortunately, I was unable to replicate this issue on Windows in either `master` or `dev`. Do you have any further details about your environment or the component causing the issue? I would assume that the comment should be /* Prevent columns from collapsing when empty */ as that is what's valid in CSS, but I'm not sure if that actually matters.

**Comment by KarandikarMihir** [comment]
That has happened to me quite a few times while running `npm run test:watch`.

**Comment by samit4me** [comment]
Do you have any further details @KarandikarMihir like your OS, Node version, boilerplate version, example code?

**Comment by KarandikarMihir** [comment]
@samit4me It's been days since I saw this error. So it was definitely earlier version of this boilerplate. I'll confirm the boilerplate version tomorrow. 

OS- Ubuntu 14.04
Node/npm- 5.5.0 / 3.3.12

**Comment by mxstbr** [comment]
The comment is definitely not what breaks this, as we allow both comment sytax' from `styled-components` core.

I think this just generally happens with browser testing – sometimes it's faster and sometimes slower, so sometimes timeouts happen which don't happen always. I don't think there's anything we can do to prevent this I'm afraid, it's just a tiny bit flaky ¯\_(ツ)_/¯ if anybody has ideas how to fix this please let me know though!
