### ISSUE TITLE
After "yarn add foo" DLLs have to rebuild

### ISSUE THREAD

**Issue by tpinne** [mxstbr/react-boilerplate#1267]
## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

After I add a package via `yarn add` the DLLs have to be rebiuld. I don't know if this is a bug or intended behaviour. But I think with `npm install` the behaviour has been different.

**Comment by mxstbr** [comment]
No, this hasn't changed with the yarn integration. Whenever you add a new dependency you have to rebuild the DLL!
