### ISSUE TITLE
Issue with production build

### ISSUE THREAD

**Issue by kempfe** [mxstbr/react-boilerplate#1268]
I created a production build of my app and get the following error when trying to open the production page.

main.6ad4fcd….js:1 Uncaught TypeError: Cannot read property 'call' of undefined(…)

the building process works fine - no errors from webpack.

im calling cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress

any infos where the problem could be ?
i only installed a handful of other dependencies like chartjs, react-bootstrap and fetch

**Comment by kempfe** [comment]
Ok i can be more specific now

to reacreate the issue do the following
install a clean installation of react-boilerplate
install react-boostrap with npm install --save react-bootstrap
import react-bootstrap in any index.js for testing purpose
build it for production
test production and see it fails with the above stated error

i got prove from react-boostrap team that it works fine on webpack - so i guess it is an issue of the react boilerplate settings

can you pls look into this ?

**Comment by zamrq** [comment]
yah... :(
same with me

**Comment by zamrq** [comment]
solver by remove webpack DedupePlugin from webpack.prod.babel.js

https://webpack.github.io/docs/list-of-plugins.html#dedupeplugin

any ideas ?

**Comment by samit4me** [comment]
The DedupePlugin appears to cause many issues indeed.

There is an open PR to resolve this #1218, feel free to give it a thumbs up 😄

**Comment by zamrq** [comment]
[https://s22.postimg.org/lcviqaqht/error.png](img)

**Comment by zamrq** [comment]
![error](https://cloud.githubusercontent.com/assets/20111802/20639405/1598f7a0-b3f5-11e6-9375-f9a62a0c102d.png)

found error in react-bootstrap

**Comment by kempfe** [comment]
i didn't got any errors while building to production
did you import a special element ?

**Comment by samit4me** [comment]
@kempfe it looks like @zamrq has the `CircularDependencyPlugin` installed which is not included with this boilerplate. Webpack has actually removed the DedupePlugin, so it will be resolved once that PR is merged. Feel free to close the issue, if you are convinced your issue is resolved by removing the DedupePlugin.

**Comment by kempfe** [comment]
thx guys
