### ISSUE TITLE
Missing menu item Using sass at document

### ISSUE THREAD

**Issue by nndung179** [mxstbr/react-boilerplate#1269]
Missing "Using Sass" at main document

**Comment by samit4me** [comment]
Not sure what you mean exactly, can you please elaborate on what the issue is?

**Comment by nndung179** [comment]
Hi @samit4me. At main document
1. go to folder docs
2. go to "Table of Contents" > section CSS. You will see 2 items: **syled-components, sanitize.css**
3. Go to section CSS. Now it turns into 3 items: **syled-components, sanitize.css, Using Sass**.

**Comment by samit4me** [comment]
I see, it's missing from the Table of contents, thanks for reporting the issue, nice find 👌. Are you keen to open a PR? If so, please take a look at the [CONTRIBUTING](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md) guidelines. If not, that's cool too, either way, please let us know so it can get fixed quickly.

**Comment by nndung179** [comment]
I already looked at it. And I have made a PR followed this guildline

**Comment by nndung179** [comment]
Here is PR: [](https://github.com/mxstbr/react-boilerplate/pull/1270)

**Comment by samit4me** [comment]
Thank you for that, linking the issue in the PR is useful to prevent this confusion.

**Comment by nndung179** [comment]
Hi @samit4me. Here is another PR I have made to branch dev

[https://github.com/mxstbr/react-boilerplate/pull/1271](https://github.com/mxstbr/react-boilerplate/pull/1271)
