### ISSUE TITLE
Utilize long-term caching in production build

### ISSUE THREAD

**Issue by okonet** [mxstbr/react-boilerplate#127]
See https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95 for more details

**Comment by mxstbr** [comment]
Great idea. PR maybe? :+1:

**Comment by okonet** [comment]
Sure!

**Comment by mxstbr** [comment]
@okonet any updates on this and #126?

**Comment by mxstbr** [comment]
Done in #198! Thanks @okonet!

**Comment by ryan-roemer** [comment]
Nice boilerplate!

We were just chatting this at work, and I posted a comment on @okonet 's blog post, but I'm curious if there was a consideration of the DLL (https://github.com/webpack/webpack/tree/master/examples/dll) and DLLUser (https://github.com/webpack/webpack/tree/master/examples/dll-user) plugins which are part of core and have a similar manifest scheme?

**Comment by mxstbr** [comment]
I have no experience with them actually, @okonet any insights? They look pretty awesome!

**Comment by ryan-roemer** [comment]
@mxstbr -- I posted https://github.com/mxstbr/react-boilerplate/issues/319 to make the discussion perhaps easier there as an actual issue for you to track 😉
