### ISSUE TITLE
Our first impression: We like it!

### ISSUE THREAD

**Issue by theLordz** [mxstbr/react-boilerplate#1272]
**_Hello!_**

We've tested many of the kits made by devs focused on improving the React project. From simple to complex. Every project tested had something apart with their own pros and cons. In terms of performance, it's hard to tell unless we port one of our medium project in the React ecosystem and test it in real world servers.

The features within this foundation are a solid way on how to combine the business logic inside applications. SSR is a great adition too. It should be a SSR branch to let other play and change things to improve the process.

Glad you have a sponsorship program, we shall take in consideration investing in the future of this dev project.

So I would say we want to start porting our project using this foundation. It's time consuming because it's angular based. We also intent using the SSR feature made here by tomazy. We know there will be a need for improvements, because of the complexity that we should implement. 

**BUT** it's a solid foundation with an extra atention for not losing the best approach criteria. **AND** that's not an easy-to-find these days!

**_To conclude,_**
A lot of Effort, Research and Love we've found between the coding lines :-)
Congrats!

**Comment by mxstbr** [comment]
Thanks, we much appreciate comments like this, we don't get them very often! This certainly just made my day! 😊 

All due to the amazing team and collaborators we have! 

👏 @oliverturner 👏 
👏 @datapimp 👏 
👏 @gihrig 👏 
👏 @amilajack 👏 
👏 @chaintng 👏 
👏 @sedubois 👏 
👏 @samit4me 👏 
👏 @Dattaya 👏 
👏 @justingreenberg 👏
