### ISSUE TITLE
More newbie friendly explanation about the relationship between sagas, reducers and routes

### ISSUE THREAD

**Issue by danielo515** [mxstbr/react-boilerplate#1274]
## Issue Type

Documentation

## Description

First of all, please let me thank you for the awesome work done with this boilerplate. It has a lot done out of the box, and has a lot of potential. But, at the few hours of start using it I got really confused. Before even trying to do anything I understood what sagas are and how do they work.

I missed a lot a bit explanation about how to "start your own application". There is a lot of good documentation about generators, the frameworks used, and all that stuff, but when you find yourself alone in front of the keyboard... you feel overwhelmed. I got no idea where to start: 
- how or where can I link selectors with reducers? I mean  root of the flow
- how to properly fire actions, from where?
- how or where can I name a part of the store? How can I nest containers inside other containers and map them to a new part of the store?

Those are actions that I'm able to do in a regular react+redux workflow, but as I said, here I feel a bit lost.

Everything is so automatic that it took me an hour to figure that: 
1.  When you create a new container, the default reducers and sagas are named with that container
1. When you create a new route, the store section that corresponds is named with the name of the container that will live on that route
1. You have to match the name of the selectors with the name of the container plus the `select` prefix
1. CamelCase words are converted to lower case when the prefix is removed, for example `selectUsers` becomes `users`

If you can clarify those doubts and write a small "getting started" guide you will be my heroes.

## Steps to reproduce

Just being an inexperienced developer on this boilerplate and start using it 😄 

Regards

**Comment by samit4me** [comment]
@danielo515 I can totally understand where you are coming from, I've been there many times and I'm sure I'll be there many times in the future. I'm not sure if there is any way I can say this without sounding like a dick, but in the [README](https://github.com/mxstbr/react-boilerplate#quick-start) it specifically states that this boilerplate is not for beginners.

> Please note that this boilerplate is **production-ready and not meant for beginners**! If you're just starting out with react or redux, please refer to https://github.com/petehunt/react-howto instead. If you want a solid, battle-tested base to build your next product upon and have some experience with react, this is the perfect start for you.

If you are just starting out with React or Redux, it's much easier to learn them first, before using boilerplates like these. With so many new libraries, tools and concepts, it totally normal to feel lost and overwhelmed and that is okay.

Boilerplates like this one cannot be fully understood or appreciated until you've put in the time to learn the tools and discover how challenging it can be and also to understand why / if you actually need them, often you do not. Anyways, I'm sorry if I have offended you in anyway, I certainly wasn't trying too. I hope this helps clear things up?

**Comment by danielo515** [comment]
Dear @samit4me 

>  I'm not sure if there is any way I can say this without sounding like a dick, but in the README it specifically states that this boilerplate is not for beginners.

You tried... and failed 😄 Seriously, no offense here.
That section of the readme it's shocking, but I took it very serious. I make myself sure that I understand how selector works and basically I fill all the gaps between my knowledge and the concepts of the template.

There are however some important parts that could be confusing for any developer that starts using this boilerplate, even for those with more react-redux experience. As examples I can list the automatic naming  , how routes are linked to reducers , how and where are the sagas launched... those details can make you waste a lot of time figuring out how do they work.

For example, one of my sagas it's being triggered every time I navigate certain route ( where the container that owns the saga lives). I don't think this is 100% related to my lack of experience with sagas.

I think that a small diagram of how things wires, first steps and that stuff will be useful even for the most experienced programmers. Today you have experience with this particular template, leave it for a month and you will become a newbie again.

Regards

**Comment by mxstbr** [comment]
I think it'd be useful to add a better outline doc that explains the general concept of how this boilerplate works too! We'd appreciate a PR adding this from somebody

**Comment by KarandikarMihir** [comment]
@mxstbr Can I try this one? Since I've worked my way up from building sample redux + redux-thunk projects to be able to use this boilerplate in one of our projects, I know the pain-points of beginners.

**Comment by KarandikarMihir** [comment]
@mxstbr Can I take a shot at this? Since I've worked my way up from building sample redux + redux-thunk projects to be able to use this boilerplate in one of our projects, I know the pain-points of beginners.

**Comment by samit4me** [comment]
@danielo515 Mate, judging from your response, you are far from a beginner! There is a similar discussion going on over on [issue 1277](https://github.com/mxstbr/react-boilerplate/issues/1277#issuecomment-263474768), feel free to have a read and see if any of the helps. Understanding how something works and explaining it to others are two different things, some people are naturally good at teaching and others are not, unfortunately, I am not, but I am trying to improve :)

**Comment by mxstbr** [comment]
@KarandikarMihir please please do!

**Comment by KarandikarMihir** [comment]
I'll have the first draft ready by Sunday!

**Comment by danielo515** [comment]
Dear @samit4me, that explanation was very clarifying,thank you very much. 
I have some diagrams in mind, I will try to post them here to see what do you think about them

**Comment by KarandikarMihir** [comment]
I have the first preview ready. It's not complete, but it's a start. Please have a look and let me know if I'm going in the right direction. Let me know if it is too verbose, too curt or too whatever :) Since English is not my native language, you could find some sentences to be ill-formed. Help me to reconstruct such sentences. I've been able to squeeze some time out to write this. More to come. In the next iteration, I'll include some of the points raised in this issue.

**[Link to doc](https://github.com/KarandikarMihir/react-boilerplate/blob/feature/add-beginner-friendly-docs/docs/general/introduction.md)**

@danielo515 If you have those diagrams ready, you can post them here. Might come handy for me. It's totally cool if you don't have time. I'm going to draw something anyway.

**Comment by gihrig** [comment]
@KarandikarMihir Looks like a great start 😃 

Yes, grammar and sentence structure could use a few tweaks, but nothing worse than what's already in the docs. Don't worry about that, I find it's best to proofread a completed doc. Otherwise I get too comfortable with the style and miss little things...

Suggestions so far:
_Tech stack: core_
Add reselect
Add links to each library's project pages and docs

_tech stack:unit testing_
Remove karma and mocha, not used after 3.4

I'm convinced: This will be huge benefit to all who are new to the boilerplate and help advance its adoption.

**Comment by KarandikarMihir** [comment]
@gihrig :smile: Thank you!

> Otherwise I get too comfortable with the style and miss little things...
Oh I'm sure you'll find something in every sentence! :sweat_smile:

> Add links to each library's project pages and docs
Will do. Very thoughtful! :thumbsup:

I'll finish this first and then you guys can jump in for the final touch!

**Comment by danielo515** [comment]
It looks like a good start, thank you.
But I expected a bit of more in-deep explanations in the following section :

Example App: Behind the scenes

That is the part that I really miss from the docs. 
Thanks again, as I said, I'll try to extract some time this weekend to "virtualize" mi diagrams (the exist on paper)

**Comment by KarandikarMihir** [comment]
@danielo515 I stopped writing "Example App: Behind the scenes". Don't worry I'll cover the [points you have raised](https://github.com/mxstbr/react-boilerplate/issues/1274#issuecomment-263116530) in the next iteration..

**Comment by mxstbr** [comment]
This is an amazing start @KarandikarMihir! Can't wait to see where this goes, super exciting!

**Comment by sammy6464** [comment]
Thanks @KarandikarMihir  so much this is going to really help me out. I also find this boilerplate quite overwhelming not so much from a point of view of not understanding it but just trying to see how everything is linked together, working backwards from the bottom up is hard. A more top down approach will be amazing! Thanks again everyone for the great boilerplate and @KarandikarMihir  for helping make it easier to get my head around :)

**Comment by KarandikarMihir** [comment]
Hi all, I've opened a PR!

@sammy6464 You're welcome :) I'm just [paying it forward](http://www.imdb.com/title/tt0223897/). Hopefully you'll adopt RBP for your next project!

**Comment by gihrig** [comment]
@KarandikarMihir I have not had time to review or proof, so this is just FYI, but there is some in depth data just added to #1315 that you may find insightful. Note that #1315, as of now is not going to be merged, but there may be important data here in relation to the frequently misunderstood issue of multiple saga instances created on location change.

**Comment by KarandikarMihir** [comment]
@gihrig Thanks for the heads up. I have one more section to add, something like FAQs. I'll make sure to address multiple saga instances issue.

**Comment by danielo515** [comment]
This is getting better and better. Keep up the good work

**Comment by oliverturner** [comment]
@KarandikarMihir you've done an absolutely brilliant job: really clear, easy-to-~~reason about~~follow explanation that nails the tone perfectly.

Super impressed: great work.

**Comment by KarandikarMihir** [comment]
@oliverturner Thank you very much, Sir! 😊  Any suggestions or ideas are most welcome.

**Comment by oliverturner** [comment]
@KarandikarMihir if see anything I'll be sure to raise it, but right now your PR warms the cockles of my heart 🤘

**Comment by KarandikarMihir** [comment]
Hahaha! :smile: Cool!

**Comment by justingreenberg** [comment]
this should be resolved by #1746 — feedback is welcome!

**Comment by danielo515** [comment]
Just with a brief overview of the new readme seems that things have improved a lot. Thank you all!!!
