### ISSUE TITLE
Lint CSS

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#128]
Using [Stylelint](https://github.com/stylelint/stylelint) as a PostCSS Plugin, we should lint the stylesheets for consistency.

The rules should fit the current style of the existing CSS.

----

> Note: If you submit a PR, do it against the **v3.0.0** branch please!

**Comment by brotzky** [comment]
Giving this one a shot

**Comment by mxstbr** [comment]
:+1:

**Comment by mxstbr** [comment]
Done by @brotzky, thanks for the amazing work!

**Comment by brotzky** [comment]
:+1:
