### ISSUE TITLE
route redirects?

### ISSUE THREAD

**Issue by Evanion** [mxstbr/react-boilerplate#1280]
I'm trying to figure out how to add a redirect route (301).

For instance ... I want to add an alias for /sign-in so that users that try to go to /login will be forwarded to the correct page.

Usually I would just add a `<Redirect />` to the router.. but I'm not sure how to handle it in this code structure, as I can't seem to find any documentation about it.

**Comment by zamrq** [comment]
```javascript
onEnter: (_nextState, replace, next) {
  replace('/something');
 next();
}
```
