### ISSUE TITLE
Update OffflinePlugin to latest version (4.0)

### ISSUE THREAD

**Issue by nhducit** [mxstbr/react-boilerplate#1284]
## Issue Type
[Enhancement] Update OfflinePlugin to latest 4.0 version

**Comment by gihrig** [comment]
@nhducit This will be included in the next dependency update. Hoping for this coming weekend, unless it breaks something...

Is there a special reason for requesting this update, some feature or fix you need?

**Comment by nhducit** [comment]
@gihrig I don't need any special reason just found that this plugin was outdate

**Comment by gihrig** [comment]
OK, Dependencies update every day, with many breaking changes it's a considerable chore to keep current.

Thanks for pointing it out.
