### ISSUE TITLE
Update templates be in sync with current app functionality

### ISSUE THREAD

**Issue by jeremyadavis** [mxstbr/react-boilerplate#1286]
## Issue Type

- Bug

## Description

The templates need updating to remove items from 3.2 that no longer exist and add new things from 3.3.

Here are a few of things I found after setting up a new app off of 3.3.3.
**Stuff Missing to be added**
Offline Plugin Dev Message #1095 
[global-styles reference](https://github.com/mxstbr/react-boilerplate/blob/master/app/app.js#L33)

**Stuff to be removed**
CSS Modules. Should be fixed with #1260 

**Other suggestions**
I modify my templates to include following:
- import styled-components 
- include propTypes
- import createStructuredSelector and update mapStateToProps to use it instead

It might be a good idea to include those by default.

These are just the items I've personally run into, there might be a few more things lingering.

## Steps to reproduce

`npm run clean`

**Comment by mxstbr** [comment]
Good catches, please submit PRs, we'd very much appreciate it!

**Comment by jeremyadavis** [comment]
k, I'll try to go back over the generator templates and clean up anything that seems amiss.
The only other item I've hit so far is that the saga tests need to have
``` /*eslint-disable redux-saga/yield-effects */ ```
added.

What's the most productive way to go about creating the PR? There are some template fixes staged for 3.4 release so I don't really want to work off master knowing merge conflicts are coming down the pike.

**Comment by gihrig** [comment]
Definitely work off of and submit to `dev` and have a look at open PRs to see what others might be working on.

**Comment by jeremyadavis** [comment]
Implemented with PR #1331
