### ISSUE TITLE
Fresh Install Build Issue - ReactTestUtils

### ISSUE THREAD

**Issue by rileybwesley** [mxstbr/react-boilerplate#1294]
I am experiencing an issue with the latest version. Upon doing a fresh install the builds are failing with dependency issues. Here are the steps to reproduce on Windows:

1. Clone most recent version.
2. run "npm run setup"
3. run "npm run build"

I have reproduced this on several computers.

The following error is received:

> START:

ERROR in ./~/react-addons-test-utils/index.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactTestUtils' in 'C:\pro
jects\react-boilerplate\node_modules\react-addons-test-utils'
 @ ./~/react-addons-test-utils/index.js 1:17-56
 @ ./~/react-element-to-jsx-string/index-dist.js
 @ ./~/chai-enzyme/build/assertions/contain.js
 @ ./~/chai-enzyme/build/index.js
 @ ./internals/testing/test-bundler.js
30 11 2016 20:56:21.470:INFO [karma]: Karma v1.3.0 server started at http://loca
lhost:9876/
30 11 2016 20:56:21.473:INFO [launcher]: Launching browser Chrome with unlimited
 concurrency
30 11 2016 20:56:21.590:INFO [launcher]: Starting browser Chrome
30 11 2016 20:56:22.866:INFO [Chrome 54.0.2840 (Windows 8.1 0.0.0)]: Connected o
n socket /#GXhPm9TBOJyuB-5iAAAA with id 64305036
Chrome 54.0.2840 (Windows 8.1 0.0.0) ERROR
  Uncaught Error: Cannot find module "react-dom/lib/ReactTestUtils"
  at webpack:///~/react-addons-test-utils/index.js:1:0 <- test-bundler.js:72222

**Comment by rationalthug** [comment]
Seeing issues using OSX (10.12.1) as well. Upon running 'npm run setup':

Error: Cannot find module './request'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:145:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

**Comment by gihrig** [comment]
@rileybwesley There is a know issue with the current version of RBP 3.3.3 where an untracked dependency has been updated. This will be corrected in the next RBP update.

Try:
`npm install react-addons-test-utils@15.3.2`
`npm start`

@rationalthug I suspect you have a corrupt npm cache.
Try:
`rm -rf node_modules`
`npm cache clean`
`npm install`
`npm start`

Better yet for both of you, (re)install with yarn.

`npm install -g yarn` (if you don't already have yarn)
`yarn`

**Comment by rhengeveld** [comment]
Encountered the same issue. Reinstalling and using `yarn` as described solved the issue. Thanks!

**Comment by mxstbr** [comment]
Sorry about that, will be releasing a new version today or tomorrow!
