### ISSUE TITLE
is there any large project build with this boilerpate?

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1298]
is there any large project build with this boilerpate?

**Comment by KarandikarMihir** [comment]
Is that an issue?

**Comment by KarandikarMihir** [comment]
@zamrq Is that an issue?

**Comment by mxstbr** [comment]
Yes. I legally cannot say which ones, but there's a lot of big companies using this boilerplate (including the biggest of them all) for huge projects.
