### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by gondar00** [mxstbr/react-boilerplate#1300]
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L80

This markdown file link is broken

**Comment by mxstbr** [comment]
Please submit a PR! Thanks!

**Comment by IvanJov** [comment]
@mxstbr Seems like that file is missing. I've checked documentation and wasn't able to find file about webpack. Maybe we should remove this link? I can send PR
