### ISSUE TITLE
Preload chunks while app is in idle state (feature req)

### ISSUE THREAD

**Issue by jsvg** [mxstbr/react-boilerplate#1302]
Currently with code splitting on routes, chunks are delivered on route transitions. I know that with #1008, there's an effort to add a progress bar to let users know when large chunks are being being requested. I'm wondering if it fits within the scope of this project to create a means for downloading the application's other chunks while it sits in an idle state.

**Comment by mxstbr** [comment]
I don't think so, for the simple reason that any such behaviour would be very very specific to the app that is built with it. Providing a solution that works for everybody for this doesn't sound possible to me, but I'm open to being proven otherwise!
