### ISSUE TITLE
Error after added font awesome

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1306]
```javascript
zamr@node8 ~/react-frontend $ yarn build:dll
yarn build:dll v0.17.9
$ node ./internals/scripts/dependencies.js 
Building the Webpack DLL
Hash: 570143d58282a9849986
Version: webpack 2.1.0-beta.25
Time: 8859ms
                      Asset     Size  Chunks             Chunk Names
reactBoilerplateDeps.dll.js  4.38 MB       0  [emitted]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 3.6 MB [entry] [rendered]
    [4] dll reactBoilerplateDeps 12 bytes {0} [built]
     + 1310 hidden modules

ERROR in dll reactBoilerplateDeps
**Module not found: Error: Can't resolve 'font-awesome' in '/home/zamr/react-frontend'**
 @ dll reactBoilerplateDeps
Done in 10.75s.

```

**Comment by Virsaviya** [comment]
@zamrq I see that you closed this - did you ever figure out why you were getting this error?

**Comment by ayasin** [comment]
@Virsaviya I didn't report this issue but I did find a solution.  The issue results from the fact that `font-awesome` isn't a JS package, it's just CSS.  You can get rid of this error by excluding it from the `dllPlugin`.  This can be done in the `app/config.js` file.

**Comment by designbyadrian** [comment]
@ayasin Do the fonts still work after exclusion? I suddenly got either this issue, or an OTS parsing error if I follow your example. I'm trying to figure out if there's a path error, but I don't know how to find the fonts when the server is running, and I can't remember what I did to create this error...

**Comment by yummyelin** [comment]
To exclude it from 

> dllPlugin

, you can find 

> dllPlugin

 in 

> package.json

, and add 

> font-awesome

.
