### ISSUE TITLE
Disable mangling

### ISSUE THREAD

**Issue by skeep** [mxstbr/react-boilerplate#1308]
How do I disable mangling in production. Adding `mangle: false` in uglify plugin have no effect.

I also noticed latest master [do not even have Uglify](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L29).

**Comment by mxstbr** [comment]
Running webpack in production (`webpack -p`) automatically adds UglifyJS, that's why we removed it. I sadly don't know how to add flags to that automatically added plugin though, sorry!
