### ISSUE TITLE
Karma Bug?

### ISSUE THREAD

**Issue by santaclauze** [mxstbr/react-boilerplate#1314]
Karma seems to skip directories that names are too long.

While testing on the boilerplate, I have had no issues until I tried with he following `CardDeckWrapper`.
After swapping the name the `CDW` Karma picked up on the tests. 

I then modified other directories names to longer ones whose testing had been successful in the past and the same bug originated (example: `Nav` to `NavDeckWrapperNext`)

Has any one observed the same issue or understand why this may be happening?
I have opened an Issue on Karma, https://github.com/karma-runner/karma/issues/2488

UPDATE: It seems to be the size of the path rather then the size of the directory.

**Comment by kopax** [comment]
Thanks for informing us, I have the same issue.

When my tree under `/components` become too long, the test got excluded.

I have now created a `FIX` directory in every parents of ignored tests to reimport and reexport the ignored tests and it's working again.

Is there any over workaround ? this is a pretty annoying bug.

I am using react boilerplate 3.3.3

**Comment by mxstbr** [comment]
That's really annoying, but sadly I don't think there's anything we can do to fix this 😢 We'll have to wait for Karma to fix it!

**Comment by kopax** [comment]
@mxstbr do you think you could keep this open until it got fixed ? It has an incidence on the boilerplate file structure.

**Comment by mxstbr** [comment]
It's not really related to the boilerplate, is it? Nothing we can do to change it, and if people are having this bug they'll search the issues anyway, not triage the full existing list :blush:

**Comment by santaclauze** [comment]
No Worries!:)
