### ISSUE TITLE
Add moment.js to boilerplate or a similar framework

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1316]
What are you users using as date library ?

I am using `moment.js` but the installation step instruction for webpack isn't clear enough.

I did like recommended [here](https://github.com/moment/moment/issues/2979#issuecomment-189899510)

I was hesitating between adding this either to webpack.base or webpack.dev.

    new webpack.ContextReplacementPlugin(/\.\/locale$/, 'empty-module', false, /js$/)

I assume the build prod doesn't need to import anything anymore and this should be added only to dev configuration am I right ? Or is it required to be in the build prod ?

Also, I am trying to figure out how to configure locale in order to work with the <LocaleToggle />

**Comment by DJTB** [comment]
I modified webpack.base with:
```
 resolve: {
      modules: ['app', 'node_modules'],
 +    alias: { moment: 'moment/moment.js' }, // reference proper moment js
```
However, I later removed moment and decided to use https://date-fns.org/ since it's immutable and can be tree-shaken.

**Comment by mxstbr** [comment]
Yeah I use `date-fns`, seems to be much more modern and made for this purpose!
