### ISSUE TITLE
[question] property destructuring pattern expected

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1326]
![qwqww](https://cloud.githubusercontent.com/assets/20111802/21063208/fb9f5708-be86-11e6-8c52-fd5f5912ff97.png)

how to enable  destructuring pattern in eslint config ?

i think its es6 features stage 3 and the boilerpate support all es6 syntax

thanks

**Comment by zamrq** [comment]
argg still proposal stage 3.
solved by experimentalObjectRestSpread

how to safely use this feature?

**Comment by mxstbr** [comment]
Is that a bug on our side?

**Comment by zamrq** [comment]
sorry @mxstbr  to buzz you,
the problem is not from this great boilerpate. problem solved

anyone use vscode under 1.6
 set "javascript.validate.enable": false
