### ISSUE TITLE
[Questions] about jsx-control-statements

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1330]
anyone used 
https://github.com/AlexGilleran/jsx-control-statements for control statement ?

ist work with enzime chai ?

**Comment by oliverturner** [comment]
This isn't a project-specific question: probably better to ask [here](http://stackoverflow.com/questions/tagged/jsx) for wider reach.

For what it's worth, I'd suggest avoiding control-flow logic in your JSX as far as possible. When you _do_ need to, it's generally preferable to use standard JS syntax (ternaries, functions, etc) to return the appropriate child.

That said, if you like really exploring the possibilities of JSX's declarative syntax, [this guy is a great source of inspiration](https://github.com/hnordt) (check out the [smalldots](https://github.com/smalldots/smalldots) library).
