### ISSUE TITLE
Build speed improvements

### ISSUE THREAD

**Issue by 6pm** [mxstbr/react-boilerplate#1332]
I use pc with intel i3 4gen, SSD with 500 read/write Mb/s. After I change some code into clean boilerplate, project rebuilds 1.5s. I think it's very long time. 
How to accelerate this process?

**Comment by samit4me** [comment]
Hi @6pm thanks for the details, did you know of any setups that run faster, maybe we could take a look to find out how. I personally thought 1ish seconds is quite fast.

**Comment by gihrig** [comment]
Closing due to lack of interest, but faster test/build cycles are always appreciated 😁
