### ISSUE TITLE
[Discussion] getstorybook.io

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1337]
I am aware of the contributors have tried to change the karma becomes jest aka super jasmine.
thank you very much for this. Unit testing is becoming more efficient, with a jest, and enzime mount.

What do you think if one day we are adding interactive testing  features like **getstorybook.io.**
I think it would be fun and not boring when creating a testing scenario

if there is a user here who are experienced in using **getstorybook**, asked to share what you have done and how the results so far

**Comment by mxstbr** [comment]
I don't think we'll add storybook by default as the integration is very quick and not everybody needs it. Thusly, the value of us adding it by default isn't very high and will annoy more people than it'll please.

Thanks for contributing!

**Comment by marc-rutkowski** [comment]
Just wrote a blog post about this topic.
https://medium.com/@mrutkowski/react-storybook-with-react-boilerplate-b95f541f5f7c#.3oodfi3vj
