### ISSUE TITLE
SyntaxError: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by julianorafael** [mxstbr/react-boilerplate#1339]
When using the recommended syntax to write the actions functions, I get an error when importing the functions on the index file of the container.

Here is how I wrote the functions on actions.js
```
export function action1 () {
  return {
    type: ACTION1
  }
}

export function action2 () {
  return {
    type: ACTION2
  }
}
```

Here is the import on the index.js file
```
import {
  action1,
  action2
} from './actions'
```

When I run `npm start` I get the following error `SyntaxError: 'import' and 'export' may only appear at the top level`.

Am I doing something wrong? Is it a bug? From all I know, babel should be parsing those es6 modules properly and I should be able to import them. Can anybody help me?

**Comment by julianorafael** [comment]
Well, it's embarassing but in the end it was a missing curly braces that was causing the problem.

**Comment by gihrig** [comment]
Happens to the best of us 😃  Too bad the error message was not more helpful..
