### ISSUE TITLE
How to load local font files (otf, ttf, woff, etc)

### ISSUE THREAD

**Issue by jeanmichelcote** [mxstbr/react-boilerplate#1340]
## Description

Using latest version of React-Boilerplate,  can't load local fonts:
`You may need an appropriate loader to handle this file type.`

Its a `ttf` type loaded in `container/App/styles.css` like so:
```
@font-face {
  font-family: 'PTC55F';
  src: url('assets/fonts/PTC55F.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'PTC75F';
  src: url('assets/fonts/PTC75F.ttf') format('truetype');
  font-weight: bold;
  font-style: bold;
}
```

Loader is :
```
{
      test: /\.(eot|svg|ttf|woff|woff2)$/,
      loader: 'file-loader',
    }
```

Anybody has any solution for this?

**Comment by DJTB** [comment]
I think the file loader is only looking for imports in js files (not within css files). I could be wrong about this though! 

One solution using styled components would end up as:

In `global-styles.js`
```
import myfont from 'path/to/font.ttf'
injectGlobal`
  @font-face {
    font-family: 'PTC55F';
    src: url(${myFont}) format('truetype');
    font-weight: normal;
    font-style: normal;
  }
`;
```

**Comment by samit4me** [comment]
Hi @jacobhamblin, as far as I am aware the latest version uses `styled-component` and no longer imports css files.

I have not tried what you are explaining, but I did notice that it looks like you can include fonts in the  [index.html](https://github.com/mxstbr/react-boilerplate/blob/master/app/index.html) file.

After a quick google there seems to be many issues surrounding @font-face + css-modules + webpack, did you have any example code?

**Comment by samit4me** [comment]
Great solution @DJTB, I just tested that in the latest `dev` branch with `Bodoni Ornaments.tff` which I found on my mac and it worked great! The only thing I did was copy the font into the app directory and modify `/app/global-styles.js` to look like the following:

```
import { injectGlobal } from 'styled-components';

/* eslint no-unused-expressions: 0 */
injectGlobal`
  @font-face {
    font-family: 'Bodoni Ornaments';
    src: url('./Bodoni Ornaments.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }
  html,
  body {
    height: 100%;
    width: 100%;
  }

  body {
    font-family: 'Bodoni Ornaments', Helvetica, Arial, sans-serif;
  }

  body.fontLoaded {
    font-family: 'Bodoni Ornaments', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  }

  #app {
    background-color: #fafafa;
    min-height: 100%;
    min-width: 100%;
  }

  p,
  label {
    font-family: Georgia, Times, 'Times New Roman', serif;
    line-height: 1.5em;
  }
`;
```
And this is what I got:
<img width="718" alt="screen shot 2016-12-13 at 6 39 16 pm" src="https://cloud.githubusercontent.com/assets/3248531/21133413/680aa21e-c164-11e6-8045-93af3a6833ea.png">

**Comment by DJTB** [comment]
Just to confirm - you didn't need to import the font before injectGlobal?
Or simply used `src: url('./Bodoni Ornaments.ttf') format('truetype');` in injectGlobal and file loader replaced the path anyway?

**Comment by jeanmichelcote** [comment]
Thanks for helping out, guys.

Just tried both suggestions. First:
```
  @font-face {
    font-family: 'PTC55F';
    src: src: url('./assets/fonts/pt_sans/PTC55F.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'PTC75F';
    src: src: url('./assets/fonts/pt_sans/PTC75F.ttf') format('truetype');
    font-weight: bold;
    font-style: bold;
  }
```
That throws:
`Uncaught TypeError: Cannot read property '0' of undefined |  parser.js:215 `

Second, with the import statement:
```
import PTC55F from './assets/fonts/pt_sans/PTC55F.ttf';
import PTC75F from './assets/fonts/pt_sans/PTC75F.ttf';

/* eslint no-unused-expressions: 0 */
injectGlobal`
  @font-face {
    font-family: 'PTC55F';
    src: src: url(${PTC55F}) format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'PTC75F';
    src: src: url(${PTC75F}) format('truetype');
    font-weight: bold;
    font-style: bold;
  }
```

...which throws the exact same error.

**Comment by jeanmichelcote** [comment]
Another related question, though:
If I don't wish to have those local fonts globally available, let's say I only want to load them in a specific component and using `styled-component` module to load them, how would I do that?

**Comment by Virsaviya** [comment]
@samit4me and @DJTB  thanks so much for the solution. I also used the import at the top and it works now!

However, now my tests are all broken.  I keep getting a loader error when I try to run my tests, and after some troubleshooting, I'm still nowhere.  The font itself loads, both locally and once the app is deployed.  But the tests aren't even running because this error is thrown.  Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/14098014/21255975/407ae0da-c324-11e6-8dd8-f73a8d5a8b12.png)

Any ideas?

**Comment by samit4me** [comment]
It's difficult to say, but I've just run `npm t` on the example I shared earlier and the tests appears to run without error. Important to note, that in that example there was no import statement for the font, only:

```
@font-face {
    font-family: 'Bodoni Ornaments';
    src: url('./Bodoni Ornaments.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }
```

Do you know what version of the boilerplate you are using? Or even better do you have some code you can share demonstrating the issue?

**Comment by Virsaviya** [comment]
I tried it without the import statement, and the font doesn't load.  I get an [OTS error](http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts) which, as far as I understand, is because webpack doesn't like relative paths (an issue I've had in the past, which is why I went with the import).

The font loads perfectly both locally and in production, it's just the test that breaks.  I tried loading a different font in - I thought maybe the font itself was causing the issue.  But it's not. :-(  

I believe I'm using v3.3.  I haven't changed any of the test configs so the issue shouldn't be coming from thee.  I'm not sure how I can demonstrate the issue, as I'm not sure where's it's coming from.  What code would be useful?  Here's my global-style.js:

```js
import { injectGlobal } from 'styled-components';
import mainFont from 'media/fonts/PontanoSans-Regular.ttf';
/* eslint no-unused-expressions: 0 */
injectGlobal`
  @font-face {
    font-family: 'Pontano Sans';
    src: url(${mainFont}) format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  html,
  body {
    height: 100%;
    width: 100%;
  }

  body {
    font-family: 'Pontano Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  }

  body.fontLoaded {
    font-family: 'Pontano Sans', 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  }

  #app {
    background-color: #fafafa;
    min-height: 100%;
    min-width: 100%;
  }

  p,
  label {
    font-family: 'Pontano Sans', 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    line-height: 1.5em;
  }
`;
```

**Comment by samit4me** [comment]
It's difficult to say, can you share the repo so I can check it out?

**Comment by joelfsreis** [comment]
I have faced the exact same issue. To remove the error in the test suit you need to add to your test-bundler.js (inside of internals/testing) the directory where you have your fonts.

Here is my example:
`const context = require.context('../../app', true, /^^((?!(app|reducers|routes|assets)).)*\.js$/);`

My fonts are inside the assets directory.

**Comment by amrbz** [comment]
@Virsaviya same issue with me. I was going to use google fonts in my project, but because of an error had to import fonts in `global-styles.js`

```
import { injectGlobal } from 'styled-components';
import { red400 } from 'material-ui/styles/colors';


/* eslint no-unused-expressions: 0 */
injectGlobal`

  @import url('https://fonts.googleapis.com/css?family=Open+Sans|Press+Start+2P&subset=cyrillic');

  html,
  body {
    height: 100%;
    width: 100%;
  }

  body {
    font-family: 'Open Sans', sans-serif;
  }

  body.fontLoaded {
    font-family: 'Open Sans', sans-serif;
  }

  #app {
    background-color: ${red400};
    min-height: 100%;
    min-width: 100%;
  }

  p,
  label {
    font-family: 'Open Sans', sans-serif;
    line-height: 1.5em;
  }
`;
```

It is also possible to use imported fonts in container styling. For example

```
import styled from 'styled-components';
import { grey50 } from 'material-ui/styles/colors';


const Body = styled.div`
  color: ${grey50};
  font-size: 24px;

  h1 {
    margin: 0 0 1em 0;
    font-family: 'Press Start 2P', cursive;
  }
`;

export default Body;
```

**Comment by rizal76** [comment]
I have same issue when `npm t` or `npm run test`.
Solved with add
```
{ test: /\.ttf$/i,
        loader: 'null-loader',
},
```
in webpack.test.babel.js
