### ISSUE TITLE
Remove duplicated code for dllconfig

### ISSUE THREAD

**Issue by juanda99** [mxstbr/react-boilerplate#1341]
It seems to me that code for webpack dllPlugin is duplicated in package.json and internals/webpack/config.js. It takes info from package.json and if not exists, it goes to the second one.

Couldn't we remove it from package.json, as this file is quite large? Do I miss something?

**Comment by gihrig** [comment]
I don't know, why don't you try deleting one (probably config.js) and see what happens. If everything checks out, open a PR.

Thanks for reporting this, we're always looking to remove duplicated code 😄

**Comment by juanda99** [comment]
I tested removing from package.json. 
Why do you prefer the info inside package.json (it's so loooong!).
I can make a PR

**Comment by gihrig** [comment]
> Why do you prefer the info inside package.json (it's so loooong!).

One concept of the boilerplate is to keep the root dir clean by avoiding a lot of config files that have to be searched to understand how things work. `package.json` becomes sort up a 'one stop shop' for configuration. Agreed, it's long 😄 

A PR would be appreciated.
