### ISSUE TITLE
[v3.4] Remove babel-jest since it automatically loaded by Jest

### ISSUE THREAD

**Issue by nktssh** [mxstbr/react-boilerplate#1344]
From https://github.com/babel/babel-jest:
> The contents of this repository were moved into the Jest repository. The source code can be found in packages/babel-jest. babel-jest is now automatically loaded by Jest and fully integrated.

Just checked - all tests are passed without `babel-jest` explicitly specified in package.json. However, `babel-jest` is present in `node_modules` folder (`jest-cli#jest-runtime` depends on it)

**Comment by gihrig** [comment]
@nktssh Thanks for the heads up! If you have tested thoroughly and found no issues, would you open a PR?

Either way, I've made a note to keep this issue in mind for the next dependency update.

Thanks for contributing 🎉

**Comment by nktssh** [comment]
@gihrig with pleasure!

**Comment by mxstbr** [comment]
Awesome, thanks for digging in!
