### ISSUE TITLE
Replace `System.import()` with `import()`

### ISSUE THREAD

**Issue by Dattaya** [mxstbr/react-boilerplate#1346]
once we update webpack to 2.1.0-beta.28, from their [release notes](https://github.com/webpack/webpack/releases):

> add import() as Code Splitting construct. It should be used instead of System.import when possible. System.import will be deprecated in webpack 2 release (removed in webpack 3) as it's behavior is incorrect according to the spec.

Here's all the places where it's used: https://github.com/mxstbr/react-boilerplate/search?utf8=%E2%9C%93&q=System.import

in addition, `json-loader`'s functionality is now in webpack's core:

> *.json files are now supported without the json-loader. You may still use it. It's not a breaking change.

Also, good news from sokra: `We are approaching the first Release Candidate...` 🎉

**Comment by gihrig** [comment]
> It should be used instead of System.import when possible.

Without researching this, as far as I know `System.import` (or require) are needed for dynamic imports. ES6 `import` does not do dynamic imports.

In the past, webpack betas have brought several breaking changes, so I've been holding out for RC release before updating.

But still, an important issue to consider going forward. Thanks for the heads up! ✨

**Comment by Dattaya** [comment]
Seems like it's an `import` function, not a statement, this is what they plan to add to the readme:

```js
async function getTemplate(templateName) {
 	try {
 		let template = await import(`./templates/${templateName}`);
 		console.log(template);
 	} catch(err) {
 		console.error("template error");
 		return new Error(err);
 	}
}
```
Code's taken from https://github.com/webpack/webpack/pull/3454/files

**Comment by mxstbr** [comment]
Exactly, we should definitely do this. Webpack plans to deprecate `System.import` before the final webpack v2 release, instead using and recommending `import` everywhere.

**Comment by mxstbr** [comment]
A [webpack v2 RC](https://medium.com/webpack/webpack-2-2-the-release-candidate-2e614d05d75f) is out with `import()` support so we should a) update to the RC and b) do this asap.

**Comment by Dattaya** [comment]
I can do that unless some else is on it.

**Comment by mxstbr** [comment]
Doesn't look like it @Dattaya, go for it!
