### ISSUE TITLE
Feature: Replacing `npm scripts` with `Yeoman Generator`

### ISSUE THREAD

**Issue by akshayKrSingh** [mxstbr/react-boilerplate#1348]
# Suggestion
Just a thought, If the npm script generators are moved to Yeoman generators, would that not provide more room for scaffolding the boilerplate?

## Issue Type
- [ ] Feature

**Comment by mxstbr** [comment]
We decided against that, as yeoman is quite a bit of overhead for the quite simple string manipulation we did back then. By now that might be a different story, but it'd be quite hard to switch to Yeoman and everything works perfectly fine, so I don't see the benefit in investing a bunch of time switching to it.
