### ISSUE TITLE
Add editorconfig

### ISSUE THREAD

**Issue by fireantik** [mxstbr/react-boilerplate#135]
To keep tabs and spaces consistent. Besides Github and JetBrains products which have support by default, [there is a plugin for every major editor](http://editorconfig.org/#download). [http://editorconfig.org/](http://editorconfig.org/)

**Comment by mxstbr** [comment]
Sounds like a good idea, would you mind submitting a PR against the `v3.0.0` branch? Thanks!

**Comment by mxstbr** [comment]
Thanks @fireantik, great idea!
