### ISSUE TITLE
Unexpected token: operator (>) on npm run build react-boilerplate v3.3.3

### ISSUE THREAD

**Issue by IpaliboWhyte** [mxstbr/react-boilerplate#1356]
I have been trying to build my project for quite a while now with `npm run build`

package.json snippet
```
"prebuild": "npm run build:clean && npm run test",
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress",
```

When I try building the tests completes successfully however I get an error at the end:

> ERROR in 0.48ab22465dd601878235.chunk.js from UglifyJs
> SyntaxError: Unexpected token: operator (>) [0.48ab22465dd601878235.chunk.js:25875,38]
> 
> ERROR in 1.87da2a5099491e2a5c15.chunk.js from UglifyJs
> SyntaxError: Unexpected token: operator (>) [1.87da2a5099491e2a5c15.chunk.js:25522,38]
> 
> ERROR in 2.cb9f761fa70767cc99df.chunk.js from UglifyJs
> SyntaxError: Unexpected token: operator (>) [2.cb9f761fa70767cc99df.chunk.js:9065,38]

I suspect this is coming from a node module i'm using and this is the exact line it's throwing the error from the chunk js file:

`exports.location = (config, callback)=> {...code-block}`

my webpack.(base/prod).babel.js files remains unchanged.

Any ideas?

Thanks a lot!!!

**Comment by mxstbr** [comment]
I think this is because we don't babelify `node_modules`, and whatever module that is doesn't transpile their source to ES5. That's their mistake, would you mind opening an issue on their repo?
