### ISSUE TITLE
[Questions] React.Component vs React.PureComponent

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1360]
React.Component vs React.PureComponent ??
whether the fundamental difference between them

Can you include a valid argument ...
I look at react 1.5 , even though we use the Component directly [extends Component], they will automatically   do checked  / deep equal check in state change before decide to rerender the components

**Comment by gihrig** [comment]
> Can you include a valid argument ...

Have you seen the [docs](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)?

> If your React component's render() function renders the same result given the same props and state, you can use React.PureComponent for a performance boost in _some cases_.

See #811 for more.

**Comment by zamrq** [comment]
ahh.... thx @gihrig . clearly information
since our state base on redux state...  PureComponet is better for performa
PureComponet  = Shallow check when props arrived

https://github.com/facebook/react/pull/7195/files#diff-6363300a479c9057729248ca9dd3e7b6R874
