### ISSUE TITLE
Generator failed with SyntaxError

### ISSUE THREAD

**Issue by tention** [mxstbr/react-boilerplate#1365]
Hi, I am getting problem running the generator. Anyone facing this as well? This was tried on a newly setup environment after running npm install.
[npm-debug.txt](https://github.com/mxstbr/react-boilerplate/files/659324/npm-debug.txt)

$ npm run generate

> react-boilerplate@3.3.3 generate /Users/yensheng/react-boilerplate
> plop --plopfile internals/generators/index.js

/Users/yensheng/react-boilerplate/internals/generators/component/index.js:35
    let componentTemplate;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/yensheng/react-boilerplate/internals/generators/index.js:8:28)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/yensheng/.nvm/versions/node/v5.2.0/bin/node" "/Users/yensheng/.nvm/versions/node/v5.2.0/bin/npm" "run" "generate"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.3.3 generate: `plop --plopfile internals/generators/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.3.3 generate script 'plop --plopfile internals/generators/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     plop --plopfile internals/generators/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yensheng/react-boilerplate/npm-debug.log

**Comment by tention** [comment]
Adding "use strict"; to react-boilerplate/internals/generators/component/index.js fix the issue.

**Comment by jeremyadavis** [comment]
Probably an issue with your node env. see #1189

**Comment by tention** [comment]
@jeremyadavis guess you're right. it happened only on Node v5 as per the #1189 

it was fixed automatically without "use strict"; on Node v6.
