### ISSUE TITLE
Discussion: Consider using @connect

### ISSUE THREAD

**Issue by nndung179** [mxstbr/react-boilerplate#1367]
Would you guys consider using 

`@connect(mapStateToProps, mapDispatchToProps)` instead of using 

`export default connect(mapStateToProps, mapDispatchToProps)(...);` ?

It looks more clearly and more easy to understand

**Comment by gihrig** [comment]
I like the `@` decorator approach though I've never worked with it in JS (I come from a Java background where this is common).

@nndung179 I think the big issues here will be lack of familiarity in the community and complexity of implementation. Can you speak to these issues from personal experience?

**Comment by nndung179** [comment]
hi @gihrig !

To set up the decorator is not hard at all. Things to do:
+ install babel plugin
+ then change syntax of `connect`

props:
+ the code looks less messy & easy to understand. 
+ we can get familiar with decorator in js

cons:
+ with developers who not familiar with decorator. It must be looked strange at the first time but it is not so hard to understand. 

I tried in my project. It all works fine. If PR welcome, I will make one.

**Comment by kopax** [comment]
I would love to see annotations in general to this project.

**Comment by oliverturner** [comment]
Personally I prefer the simplicity and explicitness of 
```export default connect(mapStateToProps, mapDispatchToProps)(...)```

Agree with @gihrig that familiarity within the community should be considered when looking at changes that are a matter of individual aesthetic preference.

**Comment by redgenie** [comment]
I'm with oliverturner. Magic is nice, but too much and it becomes confusing. Some stuff still needs to be explicitly defined.

**Comment by kopax** [comment]
@oliverturner @redgenie 

If you look at others js "framework", they all stick to the standard of writing.

The main advantage would be to be the first to implement annotation widely on an application.
Today I can't find any JS framework helpful like Spring or Zen.

I can see everyday numbers of discussion and PR here but It has to take it's own way at some point, some other framework are coming out everyday with lot's of cool features.

This project earn today a lot from it's community and could take one more step to affirm it's "opinionated way" to build JS App in 2017 by adding usage of annotations.

This is not a question to keep the code understandable to everyone, but to have a good way to write clean and maintainable code. If I need to reed a complex documentation to do that I vote for.

**Comment by oliverturner** [comment]
@kopax 

> The main advantage would be to be the first to implement annotation widely on an application.

I'm not sure I agree that this would be an advantage to the project. I get that you may benefit from an example of best practice, but that's the kind of trade-off that needs more than early-adopter status for to it to be persuasive.

> This project [...] could take one more step to affirm it's "opinionated way" to craft JS App in 2017 by adding usage of annotations.

I think most people would say it's already plenty opinionated!

It's great that you're comfortable reading documentation to help writing clean and maintainable code... but you have your own apps to do that in, no? Whether RBP has additional syntactic sugar doesn't affect that.

**Comment by kopax** [comment]
> Whether RBP has additional syntactic sugar doesn't affect that.

I wonder why they decided to implemente that then https://en.wikipedia.org/wiki/Java_annotation curious ?

I would be glad to see a gist of your implementation @nndung179 to see what that sugar look like.

**Comment by Dattaya** [comment]
I'm completely in support of decorators, but only when they are more stable (reach level 3) and released officially by Babel (more details on this: https://github.com/babel/babel/issues/2645#issuecomment-265482493). My two concerns are:

1. Don't want to add another not that necessary dependency in package.json: `babel-plugin-transform-decorators-legacy`
2. I don't know how well `babel-plugin-transform-decorators-legacy`'s supported, this issue: [Decorator incorrectly applies to nested class if used before export default](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/51) was left unanswered, we definitely don't want any new bugs introduced because of some nice syntactic sugar.

**Comment by nndung179** [comment]
Hi @Dattaya !

I completely agree with you. Hope it is stable soon. Thank you for the feedbacks :)

**Comment by scf4** [comment]
I'm not sure "familiarity" is a good argument against. This boilerplate introduced me to a lot of new (and good) concepts.

@connect looks a lot better and the concept is very simple. 

But wait to see how the proposal pans out first.

**Comment by nndung179** [comment]
@kopax the reason I changed to use `@connect` that the syntax is simple and clear for my team & everything starts at the beginning not the bottom.

**Comment by oliverturner** [comment]
Closing for now since the evidence (thanks @Dattaya) points clearly in the direction of deferring further discussion until the Decorators proposal hits stage 3. 

Thank you all for your input: I had no idea before that this pattern had so many passionate fans! 

Let's revisit when the spec reaches maturity.

**Comment by mxstbr** [comment]
We definitely don't want to use legacy decorators – that'll just confuse people once the spec is officially out and then they work differently.
