### ISSUE TITLE
[Question]: regarding build speed, considered HappyPack ?

### ISSUE THREAD

**Issue by bytewiz** [mxstbr/react-boilerplate#1368]
You might already have stumbled upon this [HappyPack](https://github.com/amireh/happypack) which supposedly speeds up webpack by allocating the ressources differently. 
If you weren't aware could this be considered and if you already reviewed it, why didn't it make it to the boilerplate? 

Thanks in advance!

**Comment by 6pm** [comment]
I think no. Very small loader support in happypack  https://github.com/amireh/happypack/wiki/Loader-Compatibility-List

**Comment by bicycleChen** [comment]
But it fully supported babel-loader, I think that's enough, cuz the js compiler will take long time

**Comment by oliverturner** [comment]
@bytewiz thanks for the suggestion. Happy to consider if it offers meaningful benefits.

A PR implementing it on the demo app would be the best evidence here. 

Closing for now, will happily reopen discussion on receipt.
