### ISSUE TITLE
Container/Component file structure proposal

### ISSUE THREAD

**Issue by JakobReiter** [mxstbr/react-boilerplate#137]
Currently the containers/components are organized in <type>/<name>/index.js
Problem is if I search for the App Container in Subline/IntelliJ I get a lot of index.js files but no App.js
That makes is really hard to find, and slow to switch between files.

Proposal: change the folder structure to use index as a "dummy" wrapper.
```
- containers
| - App
  |- index.js
  |- App.js
  |- ...
|- OtherContainer
```
with index.js only importing and exporting as a wrapper
```
import App from './App';
export default App;
```

Pro: Unique File names, faster switching
Cons: 1 additional file

Happy to create Pull request if people agree.

**Comment by mxstbr** [comment]
Hahaha mate you're a good 3 months behind. See the last few posts in #27.

**Comment by mxstbr** [comment]
@nikgraf *ping* you're going to love this
