### ISSUE TITLE
How to create npm package with component created with react-boilerplate

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1372]
I have worked on a bootstrap 4 library all made in styled components.

I used the react-boilerplate 3.3.3 for that.

I want to create a npm package to share this work and I  am now wondering because I am not yet familiar with all the webpack thing.

What is the build step to create a npm package in order to share components made with react-boilerplate ?

I know I will have some JS components files to import, does theses files needs to be compiled in ES5 right?

**Comment by redgenie** [comment]
Some vendors don't compile and leave it for the implementor to do it, just like in #1370. This may allow some packagers to do tree shaking (in your case, it's bootstrap and it definitely needs this). But you can compile it too for the convenience of some developers.

Thanks for your work btw.

**Comment by kopax** [comment]
So I just reuse the webpack config from the boilerplate ? Does anyone as a sample for starting ?

**Comment by KarandikarMihir** [comment]
Feel free to reopen. Closing for now due to inactivity.
