### ISSUE TITLE
Production Fails when run npm run start-production

### ISSUE THREAD

**Issue by fullyfaltu** [mxstbr/react-boilerplate#1377]
I'm trying to run production server but it gives me following errors. 

<img width="1121" alt="screen shot 2016-12-23 at 3 42 21 am" src="https://cloud.githubusercontent.com/assets/24522717/21442778/ed4f4c2c-c8c1-11e6-83e3-c74a5a4389d3.png">

<img width="1086" alt="screen shot 2016-12-23 at 3 42 41 am" src="https://cloud.githubusercontent.com/assets/24522717/21442779/ee49477c-c8c1-11e6-81bb-274e5112f53d.png">

need help to find and fix the issue. Thanks in advance.

**Comment by gihrig** [comment]
The real error is likely above all the "npm ERR!" clutter. please provide that info.
