### ISSUE TITLE
Error deploying to Heroku (followed instructions in docs).

### ISSUE THREAD

**Issue by CHRISTOPHERDIEHL** [mxstbr/react-boilerplate#1379]
Error:

2016-12-23T19:23:38.961975+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-12-23T19:23:39.081676+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-23T19:23:39.068092+00:00 heroku[web.1]: Process exited with status 1
2016-12-23T19:23:39.471149+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ads.herokuapp.com request_id=0f79c307-1b19-40f1-9577-5642a0a3be1b fwd="81.231.123.124" dyno= connect= service= status=503 bytes=
2016-12-23T19:23:39.729246+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=ads.herokuapp.com request_id=78991fb8-5b2d-4a50-a4f7-8d1a17e2d12f fwd="81.231.123.124" dyno= connect= service= status=503 bytes=

#Deployment steps followed:

### Easy 5-Step Deployment Process

*Step 1:* Create a _Procfile_ with the following line: `web: npm run start:prod`. We do this because Heroku runs `npm run start` by default, so we need this setting to override the default run command.

*Step 2:* Install the Node.js buildpack for your Heroku app by running the following command: `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v91 -a [your app name]`. Make sure to replace `#v91` with whatever the latest buildpack is, which you can [find here](https://github.com/heroku/heroku-buildpack-nodejs/releases).

*Step 3:* Add this line to your `package.json` file in the scripts area: `"heroku-postbuild": "npm run build",`. This is so Heroku can build your production assets when deploying (more of which you can [read about here](https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps)). Then, adjust the _prebuild_ script in your `package.json` file so it looks like this: `"prebuild": "npm run build:clean",` to avoid having Heroku attempt to run Karma tests (which are unsupported with this buildpack).

*Step 4:* Run `heroku config:set NPM_CONFIG_PRODUCTION=false` so that Heroku can compile the NPM modules included in your _devDependencies_ (since many of these packages are required for the build process).

*Step 5:* Follow the standard Heroku deploy process: 

1. `git add .`
2. `git commit -m 'Made some epic changes as per usual'`
3. `git push heroku master`

**Comment by rizvified** [comment]
Were you able to find the solution to this? I'm encountering this problem right now

**Comment by shirbr510** [comment]
@christopherdiehl could you please post your solution?
I'm facing it now as well

**Comment by christopherdiehl** [comment]
My solution was to bundle using `npm run build` then host in using S3

**Comment by shirbr510** [comment]
oh, that's unfortunate
I've actually was "evolving" my project from S3 deployment to Heroku due to server-side rendering requirement.
I actually managed to solve this after a few tries once I've configured my server code to be compiled by babel first (used `"transpile": "babel server -s -D -d dist"` in conjuction with `.babelrc`)

apparently, this error is thrown when your error has crashed for some reason
