### ISSUE TITLE
Debug karma tests in WebStorm

### ISSUE THREAD

**Issue by wer32** [mxstbr/react-boilerplate#1382]
Hi

Is anybody was successful to debug karma tests in WebStorm?

I successfully run karma tests in WebStorm but breakpoints do not work in usual way. I mean debug which is described in docs/general/faq.md

**Comment by gihrig** [comment]
As the project has moved on beyond Karma/Mocha, and due to lack of interest. I'm closing this, but fee free to contribute if you have anything to offer.
