### ISSUE TITLE
ESLIT error.

### ISSUE THREAD

**Issue by ItsMrAkhil** [mxstbr/react-boilerplate#1383]
I don't know whether issue with boilerplate or with eslint. 

I have changed (only a line) eslint config in package.json to below

`"lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts --ignore-path app/assets",`

```
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at addIgnoreFile (/home/akhil/Desktop/react-boilerplate/node_modules/eslint/lib/ignored-paths.js:102:26)
    at new IgnoredPaths (/home/akhil/Desktop/react-boilerplate/node_modules/eslint/lib/ignored-paths.js:158:13)
    at /home/akhil/Desktop/react-boilerplate/node_modules/eslint/lib/util/glob-util.js:165:34
    at Array.forEach (native)
    at Object.listFilesToProcess (/home/akhil/Desktop/react-boilerplate/node_modules/eslint/lib/util/glob-util.js:153:18)
    at CLIEngine.executeOnFiles (/home/akhil/Desktop/react-boilerplate/node_modules/eslint/lib/cli-engine.js:709:35)

```

It is breaking when I am trying to build by using `npm run build`

I think this is an issue with eslint. But I hope I can find an answer here.

**Comment by gihrig** [comment]
Did everything work before you made the change? Does it work again if you change it back?

Check the docs, but I'm wondering if having two `--ignore-path` parameters is legal.
What happens if you remove `--ignore-path .gitignore`?
What if you run lint only (`npm run lint`)?
Does the `app/assets` exist?

**Comment by ItsMrAkhil** [comment]
@gihrig Thanks for the comment. Your suggestion works. I've changed `--ignore-path app/assets` to` --ignore-pattern /app/assets/*`. Then it is started working.

But after the successfull build it is giving me an error inside browswer when I do` npm run start:prod`.
`Uncaught TypeError: r is not a function.`

I've removed all rest folders. And skipped testing. ( Hope it's not creating this issue )

**Comment by gihrig** [comment]
@ItsMrAkhil 

> but I do `npm run start:prod`

You may already know, but that command only starts the production server. It requires that you have run `npm run build` first. 

By design you are expected to run `npm run start:production`. This runs the entire lint, test, build, serve process in a single command. If some part of that sequence is failing, that should be addressed, but the first step is to get everything working in dev mode `npm start`.

I hope that helps.

**Comment by ItsMrAkhil** [comment]
@gihrig earlier I did `npm run build `first before starting server in prod mode (`npm run server:prod`). Giving me the same error. And As your suggestion, I've tried `npm run start:productio`n as well. But I ended up with the same error in browser. 
`Uncaught TypeError: r is not a function`. 

No errors, no warnings when I'm running in dev mode `npm start`. No errors, no warnings while building as well by `npm run start:production`

**Comment by ItsMrAkhil** [comment]
@gihrig I am still facing this issue. I want to deploy it in Heroku. But I cannot do this, because of this. Issue. Please, someone help me with this.

`Uncaught TypeError: Cannot read property 'call' of undefined`

**Comment by gihrig** [comment]
@ItsMrAkhil Well, starting with the idea that something is going wrong in the webpack build, my approach would be:

1. Restore your app to the "finished" condition. e.g. produces the error

`Uncaught TypeError: r is not a function`

There's no point in chasing an error that may be a consequence of removing 'withProgressBar'.

2. Reproduce the error in Chrome's console, click the line number to see the source, locate the point of the error (should be highlighted).

3. Examine the surrounding code. See if you can relate '_r_' to the function webpack renamed to 'r'.

4. If the above leads you to an understanding of this variable, trace it back to its assignment and work out what is going wrong.

It's entirely possible that 'r' is nested deep in some library and this procedure will lead nowhere, but it's a good place to start.

Failing that, you might look into generating a sourcemap that will better lead you back into the source code. See [here](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L46) and example of how it's done in `dev` mode. Also see webpack [docs](https://webpack.github.io/docs/configuration.html#devtool) on sourcemap. Also [this](http://survivejs.com/webpack/building-with-webpack/enabling-sourcemaps/) may help.

Good luck!

**Comment by ItsMrAkhil** [comment]
@gihrig

I finally figured out what is the issue. I think three is no issue with boilerplate. But with webpack. As I see there is a some webpack plugin DedupePlugin.
After commenting the line in webpack.prod file. It's started working.

https://github.com/webpack/webpack/issues/959#issuecomment-155552808

**Comment by gihrig** [comment]
WebpackDedupe plugin has been a source of trouble. It has been removed from the 3.4 branch.

Glad you got it working and Sorry for the pain 😢
