### ISSUE TITLE
A problem when deploying source code to Heroku.

### ISSUE THREAD

**Issue by thinhhung610** [mxstbr/react-boilerplate#1385]
## Issue Type

- [ ] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

When I deployed code to Heroku and got an issue below:

> remote:        > react-boilerplate@3.3.3 build /tmp/build_600744b67092a6dd97f29470d0f1d24d
> remote:        > cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress
> remote:        
> remote: module.js:471
> remote:     throw err;
> remote:     ^
> remote: 
> remote: Error: Cannot find module 'yargs'
> remote:     at Function.Module._resolveFilename (module.js:469:15)
> remote:     at Function.Module._load (module.js:417:25)
> remote:     at Module.require (module.js:497:17)
> remote:     at require (internal/module.js:20:19)
> remote:     at Object.<anonymous> (/app/.cache/yarn/npm-webpack-2.1.0-beta.25-c35ff4da4ee70344a2f14c35258d95412709e9ed/bin/webpack.js:16:3)
> remote:     at Module._compile (module.js:570:32)
> remote:     at Object.Module._extensions..js (module.js:579:10)
> remote:     at Module.load (module.js:487:32)
> remote:     at tryModuleLoad (module.js:446:12)
> remote:     at Function.Module._load (module.js:438:3)
> remote: 
> remote: npm ERR! Linux 3.13.0-105-generic
> remote: npm ERR! argv "/tmp/build_600744b67092a6dd97f29470d0f1d24d/.heroku/node/bin/node" "/tmp/build_600744b67092a6dd97f29470d0f1d24d/.heroku/node/bin/npm" "run" "build"
> remote: npm ERR! node v6.9.1
> remote: npm ERR! npm  v4.0.5
> remote: npm ERR! code ELIFECYCLE
> remote: npm ERR! react-boilerplate@3.3.3 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress`

Anyone can help me?

## Steps to reproduce

- Follow all step in this link [Deployment](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/deployment.md)
- And issue appeared when push this command `git push heroku [mybrand]:master`

# Versions

- ReactBoilerplate: v3.3.3
- Node/NPM: node v6.9.1 / npm v3.10.8
- OS: MacOS

**Comment by zsherman** [comment]
@thinhhung610 can we get some context? Is this on a fresh install of the boilerplate?

**Comment by thinhhung610** [comment]
Hi @zsherman , it's not fresh.
I'm installed some node modules to dependency like react-icons, react-progressbar.js, react-typist and slick-carousel.
The error appeared when ran `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress` but it's okay when ran in my computer.

**Comment by thinhhung610** [comment]
A new context about this bug:
1. Clone new source from `git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git` and running `npm run setup`.
2. In the repository, run `heroku create`.
3. Follow all step in this link `https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/deployment.md`
4. Run `git push origin master` and getting an error : http://prntscr.com/doca89

**Comment by easingthemes** [comment]
I had similar issue. It was due to `NPM_CONFIG_PRODUCTION` not set correctly via console.

Try adding `NPM_CONFIG_PRODUCTION` in settings panel.

![npm-prod](https://cloud.githubusercontent.com/assets/2750284/21511242/71b7687a-cc9e-11e6-90d8-09c0e0ffb3f1.png)

**Comment by thinhhung610** [comment]
@easingthemes , thanks but it's not resolved my problem.

**Comment by zsherman** [comment]
@easingthemes that worked for me when I tested again

**Comment by thinhhung610** [comment]
I found the root cause of my problem is the source code that deployed to Heroku git not configured with [Deployment](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/deployment.md), I've configured in the second commit and pushing to Heroku, it's failed.
After that, I tried to config all local source code before pushing to new Heroku git and it's working fine.
I close this issue.
Thanks all.

**Comment by thinhhung610** [comment]
Okay, that is all steps that fixed my problem:
1. On the repository, do the step 1 and step 3 on [Deployment Process](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/deployment.md).
2. On Heroku dashboard, create a new app.
3. On the repository, run the command: `heroku login`, after that run `heroku git:remote -a [heroku-app-name]`
4. Do the step 2,4 on [Deployment Process](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/deployment.md) and go to Heroku dashboard to check it's configured or not.
5. Only do step 5 when all above steps done.

Hope it will help for you.

**Comment by null-reference** [comment]
Thanks for the quick response @thinhhung610!

My issue ended up being to do with the buildpack I used. I followed the directions in the deployment process but used [v93](https://github.com/heroku/heroku-buildpack-nodejs#v93) of the buildpack. Switching to [v91](https://github.com/heroku/heroku-buildpack-nodejs#v91) fixed my issue...or so it seems :)

**Comment by giautm** [comment]
@null-reference : Thank you very much, u just save my day!. 💯
