### ISSUE TITLE
use bootstrap or other css components

### ISSUE THREAD

**Issue by VinzentE** [mxstbr/react-boilerplate#1386]
I love the boilerplate and just got started with it trying to understand the bits and peaces.
Also I do enjoy the styled components logic: great work!

The issue I am facing though:
When I add  e.g. npm packages for bootstrap or muicss (which I would love to use "out of the box") and add the boilerplate ALL the default styling is gone looking quite awful. I tried e.g.
```import React from 'react';
import ReactDOM from 'react-dom';
import Form from 'muicss/lib/react/form';
import Input from 'muicss/lib/react/input';
import Textarea from 'muicss/lib/react/textarea';
import Button from 'muicss/lib/react/button';

class Example extends React.Component {
  render() {
    return (
      <Form>
        <legend>Title</legend>
        <Input hint="Input 1" />
        <Input hint="Input 2" />
        <Textarea hint="Textarea" />
        <Button variant="raised">Submit</Button>
      </Form>
    );
  }
}
```
Any idea?

**Comment by RobEasthope** [comment]
The `styled-components` [documentation ](https://github.com/styled-components/styled-components) has a whole section on integrating third party components such as Bootstrap.

Hope it helps.

**Comment by nhducit** [comment]
@VinzentE just add your css files you want to use to index.html file

```
    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.css" rel="stylesheet">
```

**Comment by slaveofcode** [comment]
I just import an external css components by doing these, and i don't know if it is still a best practice or not, if you have any better suggestion please let me know. 

For an example here i want to add bootstrap style into my project

1. Install boootstrap by npm `npm i -S bootstrap@3`
2. Open up the `app.js` which located on `<your-root-project>/app/app.js`
3. Add bootstrap import after sanitize import like this
    
```
    import 'sanitize.css/sanitize.css';    // --> insert after this part
    import Bootstrap from 'bootstrap/dist/css/bootstrap.css';
```
and you're ready to go now

**Comment by xih** [comment]
@slaveofcode 

Your steps worked for me, but how would I get started with react-bootstrap ? 
I tried npm install -S react-bootstrap and then just going to Homepage/index.js and import carousel, ex import { Carousel } from 'react-bootstrap', but to no avail.
