### ISSUE TITLE
Webpack HMR with domain not working

### ISSUE THREAD

**Issue by andylhansen** [mxstbr/react-boilerplate#1391]
I am wanting to run the development server with a domain name. https://myapp.dev.mydomain.com
It all works, except for hot module reloading. It works if I navigate directly to the ip address of my server, but it doesn't if I use my domain name. The __webpack_hmr endpoint simply says "pending" in Chrome's network tab.

Any ideas on how to fix this?

I'm using v3.3.3 of the boilerplate

**Comment by andylhansen** [comment]
It seems to be partially working now, but not completely.
In the browser console I get: "[HMR] connected" and "[HMR] bundle rebuilding" but it never seems to finish rebuilding the bundle. If I visit /__webpack_hmr I can see the data getting sent back. It just doesn't seem to reload anything.
Any ideas?

**Comment by mxstbr** [comment]
You will probably have better luck getting an answer on [StackOverflow]. (you can use the `react-boilerplate` tag there) 

[StackOverflow]: https://stackoverflow.com

**Comment by diego-betto** [comment]
In my case was BitDefender: disable protection, reload page, re-enable protection shield. Everything should be ok.
