### ISSUE TITLE
(default)-secure nginx.conf

### ISSUE THREAD

**Issue by supergicko** [mxstbr/react-boilerplate#1392]
# React Boilerplate

First of all thank you for this amazing boilerplate :)

## Issue Type
- [X ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
The provided [nginx.conf](https://github.com/mxstbr/react-boilerplate/blob/master/app/.nginx.conf) provides basic security with TLS, but misses important security options that are considered modern but a must have. So currently the nginx config

- does provide basic security (tls 1.0, 1.1, 1.2)
- does **NOT** eliminate weak ciphers like RC4 or EXPORT per default (vulnerable to [FREAK](https://censys.io/blog/freak) f.e)
- does **NOT** set  [HSTS Header](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet)
- does **NOT** insist on his own ciphersuites (attacker could trick the server with downgrading)
- does **NOT** set recommended options for modern nginx ssl conf by Mozilla.

Since it is realistic that users may use this configuration in production, it would be nice to provide solid security configuration for nginx by default in this boilerplate. 
This is especially needed when people use the config for the api which (maybe) serves sensitive data.

**Comment by gihrig** [comment]
@supergicko Excellent points! Thank you for pointing that out 😄 

Would mind opening a PR with appropriate changes?

How about Apache's `.htaccess`?

**Comment by supergicko** [comment]
@gihrig:

> How about Apache's .htaccess?

As far as I know, .htaccess only can redirect from HTTP to HTTPS ( regarding SSL/TLS configurations).

To achieve the same config as in .nginx.conf , a VirtualHost or Server Config for apache httpd would be needed.

**Comment by gihrig** [comment]
OK, well now it's documented.

Thanks.

**Comment by supergicko** [comment]
Let me know if you need the same config for apache httpd. I would then open a new PR for this purpose only.

**Comment by gihrig** [comment]
> Since it is realistic that users may use this configuration in production, it would be nice to provide solid security configuration ... 

> Let me know if you need the same config for apache httpd.

While I don't think it would be appropriate for this boilerplate to provide a complete `httpd.conf`, I would welcome an addition to the [Apache](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/server-configs.md#apache) section of `docs/general/server-configs.md` outlining an appropriate security configuration.

**Comment by supergicko** [comment]
> While I don't think it would be appropriate for this boilerplate to provide a complete httpd.conf, I would welcome an addition to the Apache section of docs/general/server-configs.md outlining an appropriate security configuration.

Ok. Will do it soon and update the PR ok?

**Comment by gihrig** [comment]
> Will do it soon and update the PR ok?

Updating this PR is fine 😄

**Comment by supergicko** [comment]
@gihrig done

**Comment by mxstbr** [comment]
Thanks so much for the PR, this is fixed and released in 3.4! @supergicko
