### ISSUE TITLE
Webpack Problem with Production Build

### ISSUE THREAD

**Issue by robbieyng** [mxstbr/react-boilerplate#1394]
`import styles from './styles.css';` get included and work fine for the dev build, but the production build is not picking them up. Has anyone run into this or have a fix?

webpack.prod.babel.js

`// Important modules this config uses
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const OfflinePlugin = require('offline-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
module.exports = require('./webpack.base.babel')({
  // In production, we skip all hot-reloading stuff
  entry: [
    path.join(process.cwd(), 'app/app.js'),
  ],

  // Utilize long-term caching by adding content hashes (not compilation hashes) to compiled assets
  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: '[name].[chunkhash].chunk.js',
  },
  // Load the CSS in a style tag in development
  cssLoaders: ExtractTextPlugin.extract({
                fallbackLoader: "style-loader",
                loader: "css-loader"
            }),

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      children: true,
      minChunks: 2,
      async: true,
    }),

    // Minify and optimize the index.html
    new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
    }),

    new ExtractTextPlugin("styles.css"),

    // Put it in the end to capture all the HtmlWebpackPlugin's
    // assets manipulations and do leak its manipulations to HtmlWebpackPlugin
    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',

      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],

      caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },

      // Removes warning for about `additional` section usage
      safeToUseOptionalCaches: true,

      AppCache: false,
    }),
  ],
});
`

Node: 7.0.0
NPM: 3.10.8

**Comment by MehdiRaash** [comment]
firstly update your npm!

**Comment by veebuv** [comment]
can you paste your webpack.base file to see if the loaders have been accommodated for ? Its not done in the live project but it is in one of his sub projects where he has done CSS modules and uses  the cssLoaders approach.

**Comment by mxstbr** [comment]
Closing since there wasn't any new response and nobody's replicated this. Likely a local environment issue.

**Comment by designbyadrian** [comment]
@robbieyng How did you resolve this issue?

**Comment by robbieyng** [comment]
@designbyadrian Couldn't ever figure it out, switched everything over to https://github.com/styled-components/styled-components
