### ISSUE TITLE
Sagas reinjection for child routes

### ISSUE THREAD

**Issue by adelsz** [mxstbr/react-boilerplate#1397]
Lets suppose I have the following routing scheme:
```
/tree/:branchId/
/tree/:branchId/:leafId
```
And I need `branchId` level sagas to keep running while the user is on any `/tree/:branchId/*` path.
The current approach of the boilerplate is to `asyncInject` sagas in the `getComponent` method of the `/tree/:branchId/` path and to let the sagas manage their life-cycle themselves (fork a watcher then cancel on location change).

This approach is flawed because:
1. The `LOCATION_CHANGE` event fires even on `leafId` changes. Thus, `branchId` level sagas are recreated (canceled then forked) on each `leafId` change.
2. `branchId` level sagas cant manage `leafId` redirects, because they get canceled as soon as `leafId` changes.

Is this an open issue, or I have missed something?

**Comment by gihrig** [comment]
@adelsz You might want to check out #1384
