### ISSUE TITLE
(release 3.4) ngrok LAN connection failing to connect

### ISSUE THREAD

**Issue by outdooricon** [mxstbr/react-boilerplate#1398]
I'm seeing a regression in how ngrok is serving up the content on the LAN url for 3.4 .

When I perform `yarn start` on master, the output looks normal and when I navigate to the LAN url, the boilerplate page loads fine. When I then immediately switch to 3.4 branch, run `yarn` and then `yarn start`, the terminal output looks the same (normal) but when I navigate to the new LAN url, I cannot reach the site. Navigating to localhost:3000 works as expected.

I have tried bumping the ngrok version down to 2.2.3, but that doesn't seem to help.

I'm not really sure where to begin for debugging...

**Comment by outdooricon** [comment]
I've found that removing the additional host param at https://github.com/mxstbr/react-boilerplate/blob/3.4/server/index.js#L27 brings back the expected functionality

**Comment by gihrig** [comment]
Fixed in #1399 - closing.
