### ISSUE TITLE
Changes to the locale force components to mount again

### ISSUE THREAD

**Issue by juanda99** [mxstbr/react-boilerplate#1403]
If I enter this code in HomePageindex.js:

```
  constructor(props) {
    super(props);
    console.log('enter constructor');
  }

  componentWillMount() {
    console.log ('enter willmount')
  }
```

I can see the HomePage component is mounted again everytime I change the locale. 
It's a problem as my component is in a state and then, after changing locale all the state setting got initialized again. I can move my state to redux state, but is there a better way?

**Comment by Dattaya** [comment]
I believe here is described a workaround: https://github.com/yahoo/react-intl/issues/695#issuecomment-254612200, please try it and tell us about the result.
