### ISSUE TITLE
npm clean script removes global-styles import

### ISSUE THREAD

**Issue by alexlukin-softgrad** [mxstbr/react-boilerplate#1404]
I'm not sure, is this a bug, but it looks a bit confusing.
When I run `npm run clean` it removes this import from `app.js`

`import './global-styles';`

But this script doesn't remove `global-styles.js` file. So, changing global styles takes no effect.

**Comment by gihrig** [comment]
@alexlukin-softgrad Yeah, I'd say that's a bug 😦

**Comment by alexlukin-softgrad** [comment]
Now I'm totally busy, unfortunately. Maybe after a few weeks.

**Comment by jimmyheaddon** [comment]
I thought it was just me, but I too had this issue

**Comment by jeremyadavis** [comment]
This was fixed in #1331  
I'm not sure if it's in the 3.4 release though.

**Comment by kelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/12773166/21830695/bb72e332-d75b-11e6-8c46-72b389d449af.png)

The script did not remove `import './global-styles';` on the latest version of both `dev` and `master`.

**Comment by gihrig** [comment]
@kelsonic How recent is your boilerplate?

It works as expected for me in the latest 3.4 (note that `dev` was merged into 3.4 Jan 9).

**Comment by jeremyadavis** [comment]
@kelsonic It isn't supposed to remove the import. 

Prior to #1331 it did, but it also left the global-styles.js file so it was confusing if you added styles to it thinking it would globally affect the app and it wouldn't because the import was missing.

**Comment by kelsonic** [comment]
@gihrig I was working off the latest versions of `dev` and `master` [when](https://github.com/mxstbr/react-boilerplate/issues/1404#issuecomment-271743519) I posted.

@jeremyadavis it doesn't look like `import './global-styles';` is being removed anymore, right? That means that global styles should still function properly. So this issue is solved?

**Comment by jeremyadavis** [comment]
@kelsonic I believe so

**Comment by Dattaya** [comment]
Closing then, if the problem reappears, I'll reopen it.
