### ISSUE TITLE
package.json run lint:css missing

### ISSUE THREAD

**Issue by jimmyheaddon** [mxstbr/react-boilerplate#1406]
Hello, the npm script 'lint:css' was removed on Nov 2nd 2016 in [this pull request](https://github.com/mxstbr/react-boilerplate/commit/33b473912addd03f4436d8915e1df3c5a80b90c5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

However, the [commands documentation](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/commands.md) still refers to this command.  Should it still exist, or is the documentation out-of-date?  I can't see any way of linting the CSS anymore, as the 'lint' command simply redirects to 'lint:js' now?

**Comment by gihrig** [comment]
@jimmyheaddon You are correct. Please consider a openning PR to update the docs.

There is experimental support for linting styled-components [here](https://github.com/styled-components/stylelint-processor-styled-components). It would be great to hear about your experience with that project.

**Comment by jimmyheaddon** [comment]
@gihrig Sure, I can raise a PR to remove all references to lint:css from the documentation.  I'm guessing we'd want a separate PR in future for the styled-components support?

**Comment by gihrig** [comment]
Yeah, since styled-components support for linting is experimental, I'd recommend a separate PR.
