### ISSUE TITLE
Component rendering behavior changes in production

### ISSUE THREAD

**Issue by Schubbcasten** [mxstbr/react-boilerplate#1408]
I am having quite a vague problem at the moment, but maybe someone here experienced something similar.

On a page I have container that's rendered inside a parent container.
In development, on page load, the constructor of both containers is called and when the props change the parent container re-renders as well as the child container. But in production when the parent re-renders, the child container not only re-renders, but now its constructor is called again too. Thus the child containers internal state is reset, every time the parent container updates, which makes that container unusable. 
As far as I understand the expected behavior in react is that the constructor is only called the first time a component mounts (thus as it is happening in development).

It might not even be an issue in the boilerplate itself but more in one of the dependencies used for building.

**Comment by mxstbr** [comment]
You might have more luck getting answers on [StackOverflow]! (you can use the `react-boilerplate` tag there) 

[StackOverflow]: https://stackoverflow.com
