### ISSUE TITLE
Include tests (and high coverage) for all components remaining after clean

### ISSUE THREAD

**Issue by neverfox** [mxstbr/react-boilerplate#1410]
## Issue Type

- [ ] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

This pertains the 3.4 branch (since that's all I've messed with) and running `npm run clean`. The cleaning process removes the tests from the components that it does leave behind, so it's impossible to get a production build of the clean app without changing the coverage settings or adding the tests back in (with modifications). It would be better if a clean app came with minimal tests to meet coverage requirements, guided by the assumption that a clean app really shouldn't fail any of the npm scripts as written. I understand that this might not be easy to achieve given that some of the components referred to in the tests no longer exist, but that could mean that either the sample should be refactored so that that can't happen, or a different test file should be dropped in during clean (probably harder to do). For some of the components left behind, such as `App`, `NotFoundPage` and `LanguageProvider`, the boilerplate was considered common enough not to clean out so there should be tests on all of that boilerplate. Keeping these tests around would at least stop the coverage from plummeting right off the bat.

## Steps to reproduce

1. `npm run clean`
2. See that tests are gone from `app`.
3. `npm run build`
4. See that build fails because of low coverage

# Versions

- Node/NPM: 7.3.0
- Browser: Chrome 56

**Comment by gihrig** [comment]
@neverfox Thanks for reporting this 😄 

It has been addressed in #1414, which is waiting to be merged and expected to be included in the 3.4 release.
