### ISSUE TITLE
How to add a babel plugin?

### ISSUE THREAD

**Issue by LRPalacios** [mxstbr/react-boilerplate#1411]
Hello and thank you for this awesome boilerplate.

I am bit a new to react and this entire ecosystem, I've cloned the boilerplate using the branch 3.4, and everything worked great, I've finished setup and clean.

Now I want to use the [react-mdl](https://github.com/react-mdl/react-mdl) components in my project so following their instructions, I've done the following:

`npm install react-mdl --save`

In the main app.js file I've added:

```
import 'react-mdl/extra/material.css';
import 'react-mdl/extra/material.js';
```

Then in one of my components that I've created trough scaffolding(npm run generate component) I added:

`import { Button, Card, CardText } from 'react-mdl';` 

But when I run the server (npm run start) I get many errors on the command line about Module Parse Failed: unexpected token in the react-mdl files from the node_modules directory.

After some reading I though that I needed to install the babel-plugin-transform-object-rest-spread because it was pointing to lines of code that contained  "...someProp" and I notice on the babel configuration of react-mdl that they use that plugin and is not installed by default on the react-boilerplate so I went ahead and add it to my plugins doing the following:

`npm install babel-plugin-transform-object-rest-spread --save-dev`

Then I modified in the package json the babel configuration to:

```
"babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements",
          "transform-object-rest-spread" <-- Added this
        ]
      },
      "development": { <-- Added this
        "plugins": [ <-- Added this
          "transform-object-rest-spread" <-- Added this
        ] <-- Added this
      }, <-- Added this
      "test": {
        "plugins": [
          "transform-es2015-modules-commonjs"
        ]
      }
    }
  },
```
But i am still getting the same error, any ideas what i am doing wrong? Am I on the right path here?

Thank you for your time

# Versions

- Node/NPM: 6.9.2/ 3.10.9

**Comment by Dattaya** [comment]
> I needed to install the babel-plugin-transform-object-rest-spread

`babel-plugin-transform-object-rest-spread` is already installed, it's a part of `stage-0` preset, but I don't know what exactly is causing that error.

**Comment by mxstbr** [comment]
This question is better suited for [StackOverflow]. (you can use the `react-boilerplate` tag there) 

[StackOverflow]: https://stackoverflow.com

**Comment by timbrand** [comment]
I'm having the exact same issue. Can't find a discussion/solution on StackOverflow.
Sorry to handle this here again, but I'm not sure how to solve this.

**Comment by LRPalacios** [comment]
In my case I was not able to fix it, I'm not sure if it was the library that was not compatible for some reason with the webpack react-boilerplate configuration or the library that i was trying had errors. I had to switch to use another library for material implementation. So far I have not any more problems with libraries I've installed

**Comment by brianyang** [comment]
this question is not answered in SO. I'm having the exact same issue.  @timbrand @LRPalacios what was your resolution?

**Comment by LRPalacios** [comment]
@brianyang I was not able to fix it, I had to use another library that didn't had any problem with react-boilerplate

**Comment by drFabio** [comment]
@LRPalacios  bumped on here with the exact same problem. I would assume this is due to the node_modules NOT Being parsed by Babel (And it shouldn't be). I would say that this is a react-mdl fault to distribute it's package on a non ES5 way.

**Comment by gihrig** [comment]
Also note that react-mdl is [deprecated](/root/filesystem-backup.sh) in preference to [material-components-web](https://github.com/material-components/material-components-web).
