### ISSUE TITLE
Trouble with images being saved to filesystem when ran via docker-compose

### ISSUE THREAD

**Issue by xtrinch** [mxstbr/react-boilerplate#1423]
The following piece of code (I checked, if this piece of code is not in the project, those 4 images are not saved):

    import LogoImage from './images/logo.png';

Saves 4 logo images to the root of my filesystem (filenames as random guid, no file extension), only when the client is ran via docker-compose:

    client:
        image: node
        command: bash -c "cd src && npm start"
        volumes:
            - ../frontend:/src
        ports:
            - "3000:3000"

When I run it locally via npm start, nothing is saved.

Is there any possibility this is connected to the way this boilerplate is written or should I be going elsewhere with this issue?

Update:

Traced it all the way down to webpack config:

```
      test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}',
      ],
```

Namely, the image-webpack part.

**Comment by xtrinch** [comment]
Traced it all the way down to webpack config:

```
      test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}',
      ],
```

Namely, the image-webpack part.

**Comment by mxstbr** [comment]
Glad you figured it out!
