### ISSUE TITLE
How to enable SCSS syntax with precss?

### ISSUE THREAD

**Issue by fredrik-sogaard** [mxstbr/react-boilerplate#143]
I'm a little noob, but how do I add [precss](https://github.com/jonathantneal/precss) to the boilerplate? I've tried to add it in the PostCSS plugins part of `webpack.dev.babel.js` but I can't get it to work.

**Comment by mxstbr** [comment]
That should work, but it doesn't support all features.  (e.g. Inline comments will make it fail) to use full Sass, you'd need to parse your CSS with the Sass parser: https://github.com/postcss/postcss-scss

**Comment by learntoswim** [comment]
@fredrik-sogaard Did you get this to work with Postcss-scss?

**Comment by fredrik-sogaard** [comment]
@learntoswim Not really. I kinda gave up on the whole thing.

**Comment by mxstbr** [comment]
@fredrik-sogaard that's a shame to hear! Was it just the Sass thing or were there other things that kept you from enjoying this as much as possible?

**Comment by fredrik-sogaard** [comment]
@mxstbr It was a couple of things, I think. Both the sass thing and that I needed a simpler boilerplate without Sagas, selectors, service workers and the whole deal. And I prefer having const, actions and reducers in one file from the start. But that's just personal preference! But keep up the good work!

**Comment by nareshbhatia** [comment]
I am also stuck on this. I am new to webpack so simple things seem hard right now.

I am trying to follow the instructions for precss [here](https://github.com/jonathantneal/precss#postcss). I have added `precss` as a plugin for `postcss` in webpack.dev.babel.js:

```
  postcssPlugins: [
    precss(),
    postcssFocus(), // Add a :focus to every :hover
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true,
    }),
  ],
```

However, as per instructions, I am supposed to use `postcss-scss` as the parser for `precss` at runtime:

```
postcss([
    require('precss')({ /* options */ })
]).process(YOUR_CSS, { parser: require('postcss-scss') }).then(function (result) {
    // do something with result.css
});
```

That's the part I have no idea where to do.

**Comment by nareshbhatia** [comment]
Anyone listening to this? Curious if I should open a new issue.

**Comment by mxstbr** [comment]
Add `?parser=scss` to your postcss loader query in the webpack config `cssLoaders` option:

```
postcss-loader?parser=postcss-scss
```

**Comment by nareshbhatia** [comment]
Thanks, @mxstbr. It's working now - yay!

**Comment by mxstbr** [comment]
Glad to hear! :tada:

**Comment by shredding** [comment]
Sorry for reopening that, but I'm not really sure what to do where.

I have ` npm install --save precss postcss-scss` and tried to do the changes as done by @nareshbhatia and @mxstbr but still get parse errors on scss.

@nareshbhatia: Mind sharing your final webpack.dev.babel.js?

**Comment by nareshbhatia** [comment]
@shredding, sorry I accidentally deleted that project, but I have something similar working in another project. You can find it here: https://github.com/sapientglobalmarkets/staffer/tree/master/staffer-react-redux. Hope you can replicate the approach from here.
