### ISSUE TITLE
Problem with deployed project after build

### ISSUE THREAD

**Issue by silentlight** [mxstbr/react-boilerplate#1430]
When I build project using `npm run build` and when I put resulting files on the server, the app does not want to load. I see white screen and in the console I see this: 
`TypeError: o(...).concat is not a function` with below stack:
`["./"] http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:17032
	e[t]</< http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:1915
	t http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:96
	["./node_modules/core-js/shim.js"] http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:11:14640
	t http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:96
	["./node_modules/babel-polyfill/lib/index.js"]/< http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:2:12750
	["./node_modules/babel-polyfill/lib/index.js"] http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:2:12658
	t http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:96
	["./app/app.js"] http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:17176
	t http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:96
	[3] http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:54:20532
	t http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:96
	<anonymous> http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:1712
	<anonymous> http://scheduling-app.synergeelabs.com/main.e39e1fa23ad91246e55d.js:1:2
        `

Does anyone have an idea what can possibly be wrong? Thanks

**Comment by Dattaya** [comment]
Could it be a problem with `DedupePlugin` again? Try to merge this PR into your project: #1218

**Comment by silentlight** [comment]
@Dattaya Thank you. This worked. Apparently `DedupePlugin` does not like Material UI :)

**Comment by Dattaya** [comment]
Yeah, many people had issues with this it, I'm glad to know your problem was resolved.
