### ISSUE TITLE
expect documentation link 

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1433]
I don't understand but this can't be the documentation : http://chaijs.com/api/

It appear in node_modules folder that 3.4 use chai 3.5.0.

I really don't know for which version is this documentation, I need to convert this : 

    expect(css).toNotContain('undefined').toNotContain('null');

Not that I am looking for a string not a type (this for styled-components that allow props to be rendered has undefined or null)

.toNotContains is undefined since 3.4 update, using the documentation wasn't helpful.

I have tried to log the expect object but it is even more confusing : http://pastebin.com/f6dDsa2N

This would work: 

    expect(css).not.toContain('undefined');
    expect(css).not.toContain('null');

I just wan't to know what documentation should I look at.

**Comment by Dattaya** [comment]
I think you should look into the Jest documentation: https://facebook.github.io/jest/docs/api.html#writing-assertions-with-expect, unless you're importing something from `chai` directly (`import { assert } from 'chai';`), so now I have a dumb question: do we even need `chai` and `chai-enzyme`? [`Using Jest with Enzyme` guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/jest.md) states that `enzyme` work fine without any additional library and we don't use `chai` assertions.

**Comment by gihrig** [comment]
Well, I just removed chai and chai-enzyme, commented out related imports in internals/testing/test-bundler.js, deleted node_modules, ran yarn and npm test.

All tests pass 😁 
![image](https://cloud.githubusercontent.com/assets/1481063/21825529/f6ea36a4-d738-11e6-93fb-331df3b3b588.png)

Chai is also mentioned in the new docs/general/introduction.md

**Comment by Dattaya** [comment]
@kopax, I'll assume that your question was answered.

> Chai is also mentioned in the new docs/general/introduction.md

Not anymore in #1441
