### ISSUE TITLE
Sagas are injected twice!?

### ISSUE THREAD

**Issue by williamgranli** [mxstbr/react-boilerplate#1434]
For some reason, the sagas are injected twice in a new project I started. I did not have this problem in my previous project, even though the code is the same from what I can tell. 

routes.js

```
import { getAsyncInjectors } from 'utils/asyncInjectors';

const errorLoading = (err) => {
  console.error('Dynamic page loading failed', err); // eslint-disable-line no-console
};

const loadModule = (cb) => (componentModule) => {
  cb(null, componentModule.default);
};

export default function createRoutes(store) {
  // Create reusable async injectors using getAsyncInjectors factory
  const { injectReducer, injectSagas } = getAsyncInjectors(store); // eslint-disable-line no-unused-vars
  console.log("in route");
  return [
    {
      path: '/',
      name: 'consolePage',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/ConsolePage/reducer'),
          System.import('containers/ConsolePage/sagas'),
          System.import('containers/ConsolePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('consolePage', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
      path: '*',
      name: 'notfound',
      getComponent(nextState, cb) {
        System.import('containers/NotFoundPage')
          .then(loadModule(cb))
          .catch(errorLoading);
      },
    },
  ];
}
```

ConsolePage/sagas.js

```
export function* root() {
  console.log("starting saga")
  const watcher1 = yield fork(a);
  const watcher2 = yield fork(b);
  const watcher3 = yield fork(c);
  const watcher4 = yield fork(d);
  const watcher5 = yield fork(e);

  yield take(LOCATION_CHANGE);
  yield cancel(watcher1);
  yield cancel(watcher2);
  yield cancel(watcher3);
  yield cancel(watcher4);
  yield cancel(watcher5);
}

export default [
  root,
];
```
Where a, b, c, d and e are generator function as below:
```
export function* a() {
  while (true) { // eslint-disable-line no-constant-condition
    const action = yield take(X);
    const id = action.payload.id;
    const url = path + ':10020/' + id + '/logs';
    const response = yield call(y, url);
    if (response) {
      const logs = response.data;
      yield put({ type: z, payload: { asd } });
    }
  }
}
```

When printing the root function in the saga, the print happens twice. And when printing in the main function in routes.js, it happens once. The reducer receives two actions, one is INIT and the other is LOCATION_CHANGE from react-redux-router (from null to index since it's the first loading of the page). 

At first I thought the problem was related to not canceling sagas, but I am doing that as you can see in sagas.js. I'm running an older version of the boilerplate on my other project, so it might be that canceling sagas like this doesn't work anymore, any info on that?

Any help is appreciated, thanks!

**Comment by web2style** [comment]
I can confirm the problem exists. I just thought this is a problem in my code as it already differs a bit from the original boilerplate.

I didn't find where the problem exactly is. For now I have the following hack to prevent it:

```javascript
// asyncInjectors.js
export function injectAsyncSagas (store: Store) {
  let isExecuted = false

  return function injectSagas (sagas: [Function]) {
    if (isExecuted) return // temporary dirty hack
    isExecuted = true      // to prevent double saga execution

    sagas.map(store.runSaga)
  }
}
```

**Comment by williamgranli** [comment]
That fix worked fine! Thanks. Will use that for now.

**Comment by web2style** [comment]
The sad thing here: this is not a fix, but a workaround. And the problem itself is not fixed. This reminds me modern medicine that cures symptoms and not the disease itself.

So any help here from core contributors is highly appreciated!

**Comment by williamgranli** [comment]
Sorry! Just wanted some help with my code. :(

**Comment by andreipopovici** [comment]
It looks like when a problem hits, it's simultaneous! I hit the exact same issue today.

In my case, it seems the problem is `injectSagas` doing its job (injecting sagas) *each time* the route is reached, especially when using react-router's `push` or `replace`. So it `runSaga`s once on route load, then again if, somewhere, I happen to call `replace('/sameroute')`.

The dirty hack works just fine, but I'm not sure if it won't break something elsewhere. On some routes, maybe I do want the saga to re-run... Huh.

**Comment by gihrig** [comment]
I'm sorry I don't have an immediate solution, but the issue of loading and canceling sagas is being addressed in #1420 you may find insight in that work.

It would be great if you could try it out and let us know if that work solves this problem for your use case.

**Comment by andreipopovici** [comment]
@gihrig This was the most straightforward and easy to understand and implement suggestion, out of all the others. It gets my vote for official integration into the boilerplate!

The current example's suggestion to manage state inside the saga itself on `LOCATION_CHANGE` is affected by a bug in `react-router-redux`, where the action is triggered too fast and the saga doesn't receive it when it runs.

**Comment by williamgranli** [comment]
@gihrig I have changed to your solution since @yantakus fix didn't work well with some modifications I made to routes when implementing login/user/auth functionality. Thank you both for your help! I have upvoted your PR @gihrig.

**Comment by williamgranli** [comment]
@andreipopovici @gihrig @yantakus @adelsz @petemill I'm still actually experiencing a problem with the solution mentioned in #1420 by @yantakus, even though I don't have my onEnter and onLeave declared within shorthand functions. 

this.loadedSagas is always undefined, even though it shows up as a property on the object (console.log(this)) when I open it up in the dev console. 

This is what my sagas.js looks like: 

```
function getAllContainersRequest(url) {
  return http(url, 'GET', null)
    .then(response => (Promise.resolve(response)))
    .catch(error => {
      throw (error)
    });
}
function* getAllContainers(action) {
  const url = path + ':10020/status/';
  try {
    const response = yield call(getAllContainersRequest, url);
    let data = response.data;
    let containers = {}; 
    for (var i = 0; i < data.length; i++) {
      containers[data[i].Id] = data[i];
    }
    const id = Object.keys(containers)[0];
    yield put({ type: SET_CONTAINERS, payload: { containers } });
  } catch (error) {
    return false;
  } finally {
  
  }
}
export function* getAllContainersFlow() {
  yield* takeLatest(GET_ALL_CONTAINERS, getAllContainers);
}
```

This is what my routes.js looks like:

```
export default function createRoutes(store) {
  // Create reusable async injectors using getAsyncInjectors factory
  const { injectReducer, injectSagas } = getAsyncInjectors(store); // eslint-disable-line no-unused-vars
  injectSagas([loginFlow, logoutFlow]);
  return [
    {
      path: '/',
      name: 'consolePage',
      onEnter(nextState, replace, callback) {
        // onEnter gets called when we visit a route
        // childRoute changes do not trigger onEnter, which is a desired behavior
        console.log("loadedSagas", this.loadedSagas); // UNDEFINED!!!!!!!!
        console.log("this", this); // When opening up this in the dev console, shows a property on the object named loadedSagas even though above print shows undefined
        // Prevent saga reinjection if they are running
        if (this.loadedSagas) {
          callback();
          return;
        }
        // Inject sagas as usual
        const importModules = System.import('containers/ConsolePage/sagas');
        importModules.then((sagas) => {
          this.loadedSagas = injectSagas(sagas.default);
          callback();
        });
        importModules.catch(errorLoading);
      },
      onLeave() {
        // onLeave gets called when we leave the route
        // Cancel the sagas if they are running
        if (this.loadedSagas) {
          this.loadedSagas.forEach((saga) => saga.cancel());
          delete this.loadedSagas;
        }
      },
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/ConsolePage'),
          System.import('containers/ConsolePage/reducer'),
        ]);
        const renderRoute = loadModule(cb, Auth);
        importModules.then(([component, reducer]) => {
          injectReducer('consolePage', reducer.default);
          renderRoute(component);
        });
        importModules.catch(errorLoading);
      },
    },
  ];
}
```


This is what my asyncInjectors.js looks like:

```
export function injectAsyncSagas(store, isValid) {
  return function injectSagas(sagas) {
    if (!isValid) checkStore(store);
    invariant(
      Array.isArray(sagas),`
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    );
    warning(
      !isEmpty(sagas),
      '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
    );
    return sagas.map(store.runSaga);
  };
}
```

Please see the console.log and comments in the routes.js code snippet. 

Does anyone know what the problem might be?

Thanks!

**Comment by adelsz** [comment]
@williamgranli, you are importing `sagas.default`, but you do not export them in `sagas.js`.
You should add an `export default` in your `sagas.js`, to use sagas as in  #1420.
Example:
```
export function* rootSaga() {
  yield fork(actionListener1);
  yield fork(actionListener2);
}
export default [
  rootSaga,
];
```

**Comment by williamgranli** [comment]
@adelsz Sorry, I mistakenly left that out of the code snippet in my previous reply. This is what my root saga and default export look like. (In reality there are more saga flows, but I removed the others to simplify the case). I've also edited my previous comment if you want to see the saga in its entirety. 

```
export function* root() {
  console.log("con sagas init");
  yield fork(getAllContainersFlow);
}
export default [
  root,
];
```

**Comment by petemill** [comment]
I'm pretty sure you are logging this.loadedSagas at the beginning of
onEnter when it's supposed to be undefined. It gets set later, once he
sagas are loaded. That's probably why it shows up when inspecting it as by
the time you look at it, they've loaded.

**Comment by williamgranli** [comment]
@petemill That seems like a logical explanation. When printing the return from the saga function in asyncInjectors.js it shows up after the undefined of this.loadedSagas in routes.js. I just can't see what I'm doing differently than the solution in #1420. To me it seems that the code there doesn't take into account the fact that sagas are loaded async and therefore the check on this.loadedSagas will always happen before the callback has been made. Am I misunderstanding something here?

**Comment by petemill** [comment]
The check in `onEnter` as to whether `this.loadedSagas` is not neccessary. It's just a safety check to ensure that any previous navigation to the route had `onLeave` fire, thus calling `delete this.loadedSagas`. You should not ever get in to that if statement, if you do you might want to log an error. Your code seems fine though. Put a console.log in the line after `this.loadedSagas = ...` to check.

**Comment by williamgranli** [comment]
@petemill Ah, I see. A log after the line you referred to shows that the sagas have been loaded. The problem is that it happens twice for every route. This seems to be the case:
If I load index, the index saga gets ran twice.
If I load /login, the login saga gets ran twice.
If I load /login and get redirected to index, login saga is ran twice but index only once. 

So basically I'm still struggling with the initial issue of sagas loading twice.

**Comment by yantakus** [comment]
I can confirm the problem is still there.
I implemented the solution from #1420 and it worked for one of my routes. Here is my version:

```javascript
  const createRoute = (path, name, component, sagas) => {
    const route = {
      path,
      name,
      getComponent (nextState, cb) {
        const importModules = Promise.all([component, sagas])
        const renderRoute = loadModule(cb)
        importModules.then(([component, sagas]) => {
          if (sagas) {
            injectReducer(name, sagas.reducer)
          }
          renderRoute(component)
        })
        importModules.catch(errorLoading)
      }
    }

    if (sagas) {
      route.onEnter = function (nextState, replace, callback) {
        if (this.loadedSagas) {
          callback()
          return
        }
        const importModules = sagas
        if (importModules != null) {
          importModules.then((importedSagas) => {
            this.loadedSagas = injectSagas(importedSagas.default)
            callback()
          })
          importModules.catch(errorLoading)
        }
      }.bind(route)

      route.onLeave = function () {
        if (this.loadedSagas) {
          this.loadedSagas.forEach((saga) => saga.cancel())
          delete this.loadedSagas
        }
      }.bind(route)
    }
    return route
  }

  return [
    createRoute(
      '/sign-up',
      'signUp',
      System.import('components/Auth/SignUp'),
      System.import('components/Auth/SignUp/sagas')
    ),
]
```

So I thought this is success.

But I've just added another route and it's sagas are injected twice. The code of both sagas is very similar, so I really have no idea why it works in one case and doesn't work in another.

And my dirty hack works well in both cases.


Why do we at all think the problem is in sagas? I tried to paste console.logs in different places of the app and what I see is every route is rendered twice, not just sagas. `getComponent` is fired twice for every route, every component is rendered twice, etc. Isn't it the root problem, not just in sagas?

**Comment by 0777101** [comment]
@yantakus can it be the old issue? reactjs/react-router-redux#481 & https://github.com/mxstbr/react-boilerplate/commit/33485f41053caa6e90b9cbede8b51c168b38bda4#commitcomment-20063005

**Comment by Dattaya** [comment]
If someone's using `hashHistory`, there is another bug in `react-router`: [Double call to Route.getComponent()](https://github.com/ReactTraining/react-router/issues/4266). And I'd like to know whether this bug is present in 3.4 or affects 3.3 only.

**Comment by yantakus** [comment]
@0777101 Yes, this is definitely the case. Downgrading to `"react-router-redux": "4.0.6"` resolves the problem for me. Thank you for pointing this out!

@Dattaya Both 3.3 and 3.4 use `"react-router-redux": "4.0.6"`, so I suppose only those who updated `react-router-redux` to v4.0.7 experience this issue.

**Comment by Dattaya** [comment]
> Downgrading to "react-router-redux": "4.0.6" resolves the problem for me. 

so cool, what about you, @williamgranli?

**Comment by williamgranli** [comment]
@Dattaya I fixed the problem by downgrading as well. Did it before I spotted the comments here. I started by doing some testing with the latest version of react-boilerplate and couldn't reproduce the bug, so I basically started over with a fresh project and manually moved my components and changes to the boilerplate. Now it works without any onEnter shenanigans in routes.js, even. 

Thanks for the help everyone, closing the issue.

**Comment by tadas-subonis** [comment]
For those that are interested what's the problem with 4.0.7 ->
https://github.com/reactjs/react-router-redux/commit/60f34adf49e27c9372df204650de3e973dede6bf from https://github.com/reactjs/react-router-redux/pull/476

This commit broke the flow by adding an eager pre-double-dispatch of currently loaded location.

**Comment by nndung179** [comment]
@yantakus the solution worked for me.

**Comment by nndung179** [comment]
@williamgranli see my comment at here: [https://github.com/react-boilerplate/react-boilerplate/pull/1420#issuecomment-281424743](https://github.com/react-boilerplate/react-boilerplate/pull/1420#issuecomment-281424743)

**Comment by Jinnified** [comment]
i dont think either upgrade react-router-redux to 4.0.8 would fix this issue as it was claimed by react-router-redux ppl at their github, nor downgrade to 4.0.6 would either, as i have tried both on my project, and also on a clean boilerplate. IMHO, the only fix for now is to use a 'global' saga and not to inject sagas to routes asynchronously.

**Comment by Gyvastis** [comment]
This is my current approach of making sure sagas are injected only once. Also thinking of passing in a name as in `injectReducer` to prevent skipping sagas of same name but from a different container.

`export function injectAsyncSagas(store, isValid) {
  if(!store.asyncSagas) {
    store.loadedSagas = [];
  }

  return function injectSagas(sagas) {
    if (sagas.length <= 0) return;

    if (!isValid) checkStore(store);

    invariant(
      Array.isArray(sagas),
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    );

    sagas.filter((saga, i) => {
      if(!store.loadedSagas.includes(saga.name)) {
        store.loadedSagas.push(saga.name);
        sagas.splice(i, 1);

        return true;
      }

      return false;
    }).map(store.runSaga);

    console.log(store.loadedSagas);

    store.dispatch(injectAsyncSagasAction());
  };
}`

**Comment by developer239** [comment]
```
export function injectAsyncSagas(store, isValid) {
  // this is required because otherwise child route sagas get injected twice, thanks react boilerplate!
  const injectedSagasNames = [];

  return function injectSagas(sagas) {
    if (!isValid) checkStore(store);

    invariant(
      Array.isArray(sagas),
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    );

    warning(
      !isEmpty(sagas),
      '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
    );

    sagas.map((saga) => {
      if (!injectedSagasNames.includes(saga.name)) {
        store.runSaga(saga);
        injectedSagasNames.push(saga.name);
      }
      return null;
    });
  };
}
```

**Comment by sabarnix** [comment]
@Gyvastis 's solution works like a charm. I can't think of a possible scenario where we would want the saga to be reinjected. Can't we just merge these changes and save new devs from hours of debugging.

**Comment by Tushant** [comment]
@Gyvastis I get an error as Expected `sagas` to be an array of generator functions'. But if i remove name from injectSagas(name, sagas), the error is gone but still the sagas are injected twice.

**Comment by sabarnix** [comment]
@Tushant you have to replace the `injectAsyncSagas` function in `utils/asyncInjectors.js` with @Gyvastis 's second solution.

**Comment by Tushant** [comment]
@sabarnix this is the code which does not throw me an error 

```javascript
export function injectAsyncSagas(store, isValid) {
  const asyncSagas = [];

  return function injectSagas(sagas) {
    if (!isValid) checkStore(store);

    invariant(
      Array.isArray(sagas),
      "(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions"
    );

    if (sagas.length <= 0) return;

    sagas
      .filter(saga => {
        if (asyncSagas.includes(saga.name)) {
          return false;
        }

        asyncSagas.push(saga.name);

        return true;
      })
      .map(store.runSaga);
  };
}

export function getAsyncInjectors(store) {
  checkStore(store);

  return {
    injectReducer: injectAsyncReducer(store, true),
    injectSagas: injectAsyncSagas(store, true)
  };
}

```
if i pass name arguments, i get an error  injectAsyncSagas: Expected `sagas` to be an array of generator functions. Do i have to pass something else from somewhere else?

**Comment by sabarnix** [comment]
@Tushant you have to use this functions. @Gyvastis 's second solution. The function you are using clearly don't take two parameters. See your `injectSagas` function.

```javascript
export function injectAsyncSagas(store, isValid) {
  const asyncSagas = {};

  return function injectSagas(name, sagas) {
    if (!isValid) checkStore(store);

    invariant(
      Array.isArray(sagas),
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    );

    if (sagas.length <= 0) return;

    if(!asyncSagas[name]){
      asyncSagas[name] = [];
    }

    sagas.filter((saga) => {
      if(asyncSagas[name].includes(saga.name)) {
        return false;
      }

      asyncSagas[name].push(saga.name);

      return true;
    }).map(store.runSaga);
  };
}
```

**Comment by Tushant** [comment]
When i put name argument i get error beacause i am passing sagas this way
 ```javascript 
importModules.then(([reducer, sagas, component]) => {
    injectReducer("commission", reducer.default);
    injectSagas(sagas.default); // here you see 

    cb(component);
  });

  importModules.catch(errorLoading);
};
```

How are your passing your component sagas? Can i see it, please?

**Comment by sabarnix** [comment]
You gave to replace the `injectAsyncSagas` function in `utils/asyncInjectors.js` and in `route.js` replace `injectSagas` like this.
```javascript
importModules.then(([reducer, sagas, component]) => {
   injectReducer('commission', reducer.default);
   injectSagas('commissionSaga', sagas.default); 

   cb(component);
 });

 importModules.catch(errorLoading);
};
```
Add an unique name to each sagas.

**Comment by Tushant** [comment]
@sabarnix I am not getting an error but still my saga in injecting multiple times. Can i share my project with you? Can you look at it, please?

**Comment by Gyvastis** [comment]
@Tushant if you're still having the issue it might be you're doing something odd with sagas itself. Could you give a link to the repo? And which sagas, actions you have the problem with?

**Comment by developer239** [comment]
@Tushant Look at my answer above. You literally have to copy and paste the source code. You don't have to do anything else.

```
export function injectAsyncSagas(store, isValid) {
  // this is required because otherwise child route sagas get injected twice, thanks react boilerplate!
  const injectedSagasNames = [];

  return function injectSagas(sagas) {
    if (!isValid) checkStore(store);

    invariant(
      Array.isArray(sagas),
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    );

    warning(
      !isEmpty(sagas),
      '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
    );

    sagas.map((saga) => {
      if (!injectedSagasNames.includes(saga.name)) {
        store.runSaga(saga);
        injectedSagasNames.push(saga.name);
      }
      return null;
    });
  };
}
```

**Comment by JK0N** [comment]
I used this boilerplate to start learning react. After 30 minutes of playing around with the project, I run into this bug.. :P Easy steps to reproduce it:

1. Type something in "Try me! - Show Github repositories by" input box.
2. Change switch the language on bottom section "en" --> "de" and back a couple of times and check your network inspector window. It start sending a lot of requests to GitHub.

**Comment by designbyadrian** [comment]
@Gyvastis Your solution doesn't work with minified code, as saga.name could be a string of one letter and same as another saga...

**Comment by developer239** [comment]
Yes exactly I ran into this problem too. None of these solutions work.

**Comment by Dattaya** [comment]
@developer239, @designbyadrian, @JK0N, try:
```diff
diff --git a/app/store.js b/app/store.js
index c41a940..efe9b06 100644
--- a/app/store.js
+++ b/app/store.js
@@ -41,6 +41,7 @@ export default function configureStore(initialState = {}, history) {
   // Extensions
   store.runSaga = sagaMiddleware.run;
   store.asyncReducers = {}; // Async reducer registry
+  store.asyncSagas = new Map(); // Async saga registry to avoid multiple executions of the same saga

   // Make reducers hot reloadable, see http://mxs.is/googmo
   /* istanbul ignore next */
diff --git a/app/utils/asyncInjectors.js b/app/utils/asyncInjectors.js
index fc1afcd..eae8e1f 100644
--- a/app/utils/asyncInjectors.js
+++ b/app/utils/asyncInjectors.js
@@ -62,7 +62,10 @@ export function injectAsyncSagas(store, isValid) {
       '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
     );

-    sagas.map(store.runSaga);
+    const asyncSagas = store.asyncSagas;
+    const filteredSagas = sagas.filter((saga) => !(asyncSagas.has(saga) && asyncSagas.get(saga).isRunning()));
+
+    filteredSagas.forEach((saga) => asyncSagas.set(saga, store.runSaga(saga)));
   };
 }
```

**Comment by bjackson** [comment]
@Dattaya is that in addition to Gyvastis's changes?

**Comment by bjackson** [comment]
@Dattaya, ah if I understand that's an alternative to @Gyvastis's changes. I tried both and both work on a static route, but fail on dynamic routes.

**Comment by bjackson** [comment]
@Dattaya Your fix along with upgrading react-router-redux to 4.0.8 fixed the issue and sagas are no longer executed more than once on both static and dynamic routes!

**Comment by Jamakase** [comment]
Solutions that are similar to @Gyvastis are working wrong. If the code is minimised then some sagas can be omitted. That's what happened to me. For development, it works like a charm, for prod it fails sometimes.

**Comment by yummyelin** [comment]
@Gyvastis @sabarnix 's solution is working!! why not create a pull request?

BTW, we are using hashhistory, not browsehistory, now saga is only injected once, but route / reducer are still injected twice.

**Comment by developer239** [comment]
What are we even talking about? This repo has more than 15 000 stars...

**Comment by alexmason528** [comment]
New version of react-boilerplate fixed this issue.

Anyway, my solution to this issue is

`export function injectAsyncSagas(store, isValid) {
  const asyncSagas = {}

  return function injectSagas(name, sagas) {
    if (!isValid) checkStore(store)

    invariant(
      Array.isArray(sagas),
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    )

    warning(
      !isEmpty(sagas),
      '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
    )

    if (Reflect.has(asyncSagas, name)) return

    asyncSagas[name] = sagas
    sagas.map(store.runSaga)
  }
}`
