### ISSUE TITLE
Remove unknown reference in index.html

### ISSUE THREAD

**Issue by kelsonic** [mxstbr/react-boilerplate#1435]
In `./app/index.html` there is this comment:

```html
<!-- A lot of magic happens in this file. HtmlWebpackPlugin automatically includes all assets 
(e.g. bundle.js, main.css) with the correct HTML tags, which is why they are missing in this HTML
 file. Don't add any assets here! (Check out webpackconfig.js if you want to know more) -->
```

Since there doesn't seem to be a `webpackconfig.js` file, do we want to replace it with a reference to 
[this file](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L17) 
or should we remove `(Check out webpackconfig.js if you want to know more)`?

**Comment by gihrig** [comment]
Good observation!

I would suggest replacing 

> (Check out webpackconfig.js if you want to know more)

 with

> (Check out the webpack config files in `internals/webpack` for details)

**Comment by kelsonic** [comment]
@gihrig Should I make the PR off `master` or `dev`? 😄

**Comment by gihrig** [comment]
@kelsonic Always make general PRs against `dev`.

**Comment by kelsonic** [comment]
Got it, thanks!
