### ISSUE TITLE
Childroutes renders parent route

### ISSUE THREAD

**Issue by bytewiz** [mxstbr/react-boilerplate#1438]
I am not sure if I am completely of the grid, but I tried to follow the routes.md for `childRoutes`.

Example I have a route `/test` and I add `childRoutes` to access a slug of `/test/:id`

when I visit `/test` as expected it renders the `TestRoute` container but when I visit `/test/:id` it renders the same container and not `TestRouteID`

code snippet below, might just be might, going blind...

appreciate the feedback
 
![image](https://cloud.githubusercontent.com/assets/16811871/21831050/4edccf8a-d7a1-11e6-8c21-e0bf12083732.png)

**Comment by jeremyadavis** [comment]
Although I haven't built an app with child routes off of this boilerplate yet, I think you might be having issues because you're not using the async getChildRoutes for declaring child routes.
https://github.com/ReactTraining/react-router/blob/master/docs/API.md#plainroute

**Comment by Dattaya** [comment]
@bytewiz, first of all, your path for the sub-route looks weird, you probably meant: `path: '/:id'`, second, be sure to return `{children}` somewhere in the `render` of the parent `TestRoute` container.

**Comment by bytewiz** [comment]
@Dattaya I don't know how I did not see that myself... thanks appreciate it! complete brainfart.

**Comment by warmansuganda** [comment]
my issue same like this, T_T
