### ISSUE TITLE
Docs to deploy to AWS?

### ISSUE THREAD

**Issue by kelsonic** [mxstbr/react-boilerplate#1439]
Many users will be fine with the docs that already exist to deploy the app to Heroku. However, it may be a good idea to have docs that describe how to host the app on AWS as well. Thoughts?

**Comment by gihrig** [comment]
@kelsonic Have you deployed to AWS? A PR would be welcome!

**Comment by kelsonic** [comment]
I have not but I'm happy to try it out when I get some free time! 😄

**Comment by kelsonic** [comment]
Perhaps it would also be a good idea to add docs on how to deploy to Google Cloud, too: [https://cloud.google.com/storage/](https://cloud.google.com/storage/)

**Comment by gihrig** [comment]
> Perhaps it would also be a good idea to add docs on how to deploy to Google Cloud

Sure - Have at it! 

Would also be good to have deployment instructions for a generic web host such as Digital Ocean (if you're so inclined).

**Comment by michaelcuneo** [comment]
I need to deploy a massive project to AWS, as soon as I get my head around React and can actually finish it.

**Comment by octodroidrus** [comment]
isn't there already a section in the docs on deploying to S3?

**Comment by gihrig** [comment]
@octodroidrus Yes, that was added by @kelsonic (the OP) in #1442 and merged into 3.4 (current release).

This issue was left open in hopes others would add docs for deploying to other platforms. Since that hasn't happened, I'll close now.

**Comment by kelsonic** [comment]
@gihrig Came across this line earlier today in `docs/general/README.md`. I think I missed it when writing the docs for how to deploy to AWS:

`- [Deployment](deployment.md) *(currently Heroku specific)*`

Should be changed to:

`- [Deployment](deployment.md) *(currently Heroku and AWS specific)*`
