### ISSUE TITLE
Referencing images from css

### ISSUE THREAD

**Issue by fredrik-sogaard** [mxstbr/react-boilerplate#144]
Noob question again: How do I reference images in my css?
I'm doing this (the image is next to the css file in the folder):
```
.poster {
    background: url(./hero-banner.jpg) no-repeat;
    background-size: cover
}
```
The outputted css is:
```
._33hlffvz0sgxpxLxtaBGAu {
    background: url(/b1e8ba2d0f312bdf6d0011f87d91bed1.jpg) no-repeat;
    background-size: cover;
}
```
The image dosen't show up (and I can't open it in a new tab, for instance).

If I do this:
```
.poster {
    background: url(/hero-banner.jpg) no-repeat;
    background-size: cover
}
```
The outputted css is:
```
._33hlffvz0sgxpxLxtaBGAu {
    background: url(/hero-banner.jpg) no-repeat;
    background-size: cover;
}
```
But the image still dosen't show, and if I try to open the image in a new tab, this is the url I get: `chrome-devtools://devtools/hero-banner.jpg`

Sorry for my stupid questions, but any help is much appreciated!

**Comment by mxstbr** [comment]
Are you on the `master` branch or on the `v3.0.0` branch?

**Comment by fredrik-sogaard** [comment]
`v3.0.0.` branch

Might be related to my system. I can't build the app either. I get errors on the linting. Node and npm are ```
node v5.2.0
npm  v3.6.0
```

**Comment by mxstbr** [comment]
This is probably copy of https://github.com/mxstbr/react-boilerplate/issues/126#issuecomment-178720831

Thanks for reporting this, I'll publish a fix soon!

**Comment by abeaclark** [comment]
@fredrik-sogaard did you end up resolving this issue? I'm having the same issue still and haven't been able to find a workaround.

**Comment by gihrig** [comment]
@fredrik-sogaard did you see #370?

**Comment by abeaclark** [comment]
@gihrig Thanks! I hadn't seen that thread. [`webpack/style-loader#96 (comment)`](https://github.com/webpack/style-loader/pull/96#issuecomment-228370602) saved me.

**Comment by kachkaev** [comment]
I just faced the same issue, which only happened in dev mode - the images did show up after build.

Here are the steps that should help getting over it (inspired by https://github.com/webpack/style-loader/pull/96#issuecomment-228370602):

1. Create `internals/dev-preamble.js`:

  ```js
  __webpack_public_path__ = window.location.protocol + "//" + window.location.host + "/";
  ```

2. Open `internals/webpack/webpack.dev.babel.js` and add one line:

  ```js
  // Add hot reloading in development
  entry: [
    'eventsource-polyfill', // Necessary for hot reloading with IE
    'webpack-hot-middleware/client',
    path.join(process.cwd(), 'internals/dev-preamble.js'), // <--------------- this one
    path.join(process.cwd(), 'app/app.js'), // Start with js/app.js
  ],
  ```

Here is what changes when you look at your CSS in Chrome's inspector:
```txt
background: url(/8fe95655bf016c50f6c443abf0186652.png) no-repeat 0 0;
↓
background: url(http://localhost:3000/8fe95655bf016c50f6c443abf0186652.png) no-repeat 0 0;
  ```

Might be worth doing this right in the boilerplate, but I'm not sure if my solution is elegant enough for a PR. Hope others spend less time making this work!

**Comment by sourcesoft** [comment]
@kachkaev this fixed the issue for me.
used to happen only in dev mod, not adding http://localhost:3000 before image hash name.

**Comment by luandro** [comment]
Since #972 it seems this fix isn't working anymore. Can anyone confirm? Any work around?

**Comment by asinghal** [comment]
@mxstbr I would highly recommend including @kachkaev 's patch into the boilerplate. We had the same issue for prod builds and this patch seems to be the only way to get the images in CSS to work!

**Comment by kachkaev** [comment]
@mxstbr what do you think of including my patch above into 3.3? ATM I have to repeat the same magic spell in every new project to see static assets like fonts and images in dev. I once even forgot what was wrong and started searching, ended up learning from my own comment xD

I can create a PR in the exact way things are described above. I'm just not sure that creating an extra file with one line of code is elegant enough. The same line in `app.js` wrapped into an if statement did not work fro me unfortunately.

**Comment by mxstbr** [comment]
There's gotta be a better way to do this. /cc @sokra @TheLarkinn, maybe they know what's wrong here?

**Comment by TheLarkInn** [comment]
This looks related to an issue we have reported in our repo but Im struggling to find it.

**Comment by rizedr** [comment]
@mxstbr Has any solution been adopted for this issue? Except @kachkaev's solution posted above? I am working on a project which has v3.0.0 as dependency.

**Comment by williamgranli** [comment]
@kachkaev 's solution did not work for me. 

The browser console show the following, both with and without the fix: 
background-image: url(img/header-bg.jpg);

Is there any way I can track what's not working? Kind of lost on how to proceed to solve the bug. 

Thanks!

**Comment by karna41317** [comment]
Same here

**Comment by williamgranli** [comment]
@karna41317 importing the image (javascript require) and then passing the imported image to the css in styled components works.
