### ISSUE TITLE
initial clone

### ISSUE THREAD

**Issue by Ankiewicz** [mxstbr/react-boilerplate#1448]
on `NPM Run`

I received
 `
Cleaning old repository ✓
Installing dependencies. ✓ (This might take a while)Installing dependencies
Initialising new repository ✓
Done!
> react-boilerplate@3.3.3 postsetup /Users/jankiewicz/projects/ankiewicz
> npm run build:dll

> react-boilerplate@3.3.3 build:dll /Users/jankiewicz/projects/ankiewicz
> node ./internals/scripts/dependencies.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jankiewicz/projects/ankiewicz/internals/scripts/dependencies.js:13:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "build:dll"
npm ERR! node v6.3.0
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.3.3 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.3.3 build:dll script 'node ./internals/scripts/dependencies.js'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/dependencies.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jankiewicz/projects/ankiewicz/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v6.3.0
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.3.3 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.3.3 postsetup script 'npm run build:dll'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dll
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jankiewicz/projects/ankiewicz/npm-debug.log
➜  ankiewicz git:(master) ✗ npm run start

> react-boilerplate@3.3.3 start /Users/jankiewicz/projects/ankiewicz
> cross-env NODE_ENV=development node server

sh: cross-env: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.3.0
npm ERR! npm  v2.15.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-boilerplate@3.3.3 start: `cross-env NODE_ENV=development node server`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.3.3 start script 'cross-env NODE_ENV=development node server'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.`

**Comment by gihrig** [comment]
I believe this is the same issue as #1446. Continue this thread there.

Closing this in favor of that.
