### ISSUE TITLE
[Question] How to load initial App data

### ISSUE THREAD

**Issue by Edwin-Luijten** [mxstbr/react-boilerplate#1450]
Situation:
I am creating an application which needs to fetch some initial data from an API.

As I understood you use saga's to fetch data from a given source, so I created on with corresponding reducer/actions, so far so good.

I created a reducer, actions and a saga, based on the homepage one's.

The thing I'm failing to get working is let it fetch the data and bind it to the app, so all it's child components have access to it and or listen for the event when the data is fetched.

My guess is I need to do something in App\index.js.

Any pointers are appreciated.

**Comment by denisflorkin** [comment]
I think you might find what you looking for in this  [comment](https://github.com/mxstbr/react-boilerplate/issues/1277#issuecomment-263267639)

The idea is to use injectSagas() in the createRoute function, not in a specific route, this should give you what you want

**Comment by jeremyadavis** [comment]
You'll need to inject the saga to the App like @denisflorkin mentioned then in App/index.js you'll need to have componentWillMount lifecycle method dispatch your init type actions for the sagas to watch for.

**Comment by Edwin-Luijten** [comment]
Thanks for the pointers guys, I have it working by combining your tips.

**Comment by RobertSheaO** [comment]
@Edwin-Luijten would you mind sharing the relevant parts of how you configured your createRoutes function to inject an app level saga?
