### ISSUE TITLE
Add route after start

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1451]
I need to load a list of application path allowed by the client, is it possible to add new path using a saga ?

**Comment by jeremyadavis** [comment]
Maybe you can use the [onEnter](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#onenternextstate-replace-callback) method like a lot of authentication flow setups use?

**Comment by kopax** [comment]
@jeremyadavis I am using onEnter the problem is I don't know where should I inject this extra routes.

Any Idea ? I am still stuck on that part.

**Comment by jeremyadavis** [comment]
I don't know of any way currently to inject routes. 

My thought about onEnter would be to just have all your routes statically created like normal routes and just do an authentication-like challenge onEnter and redirect if that client is not authorized to view the route.

You might be looking at some modifications to createRoutes to fetch your dynamic routes and append the results to the array of plain routes currently being returned.

**Comment by mxstbr** [comment]
This is a better question to ask on StackOverflow tagged with `react-router`.
