### ISSUE TITLE
Dynamic routing - connecting everything the right way (help wanted)

### ISSUE THREAD

**Issue by denisflorkin** [mxstbr/react-boilerplate#1452]
Hello,

I'm working on integrating some dynamic routes, following the [doc](https://github.com/mxstbr/react-boilerplate/issues/1277#issuecomment-263267639)
I manage to have the route trigger the saga (it would seems I'm also having this [issue](https://github.com/mxstbr/react-boilerplate/issues/1277#issuecomment-263267639) but this is not the problem I'm having right now).

My issue is that instead of actually getting the value from `:slug` in my saga, I get `0` (Number)

The router has the right data and 'knows' the value :`slug`
I'm new to redux and sagas, I have no idea where this is coming from or how to go about diagnosing.

#### routes.js :
```
(...)
    }, {
      path: '/profile/:slug',
      name: 'userProfile',
      getComponent(nextState, cb) {
        console.log('loadign dynamic route profile/: ; nextState', nextState)
        const importModules = Promise.all([
          System.import('containers/ProfilePage/reducer'),
          System.import('containers/ProfilePage/sagas'),
          System.import('containers/ProfilePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('profilePage', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
(...)
```

#### sagas.js
```
export function* getUserData(slug) {
  /** this is my problem : */
  console.log(' *getUserData slug', slug) // outputs:  0 

  const requestURL =
    `https://localhost/projects/neoapi/${slug}/GET.json`

  const userprofile = yield call(request, requestURL);
  console.log('userprofile', userprofile)
  if (!userprofile.err) {
    yield put(getUserProfileDataSuccess(userprofile));
  } else {
    yield put(getUserProfileDataFail(userprofile.err));
  }
}

/**
 * Watches for LOAD_PROFILE actions and calls getUserProfileData when one comes in.
 */
export function* getUserDataWatcher() {
  const { slug } = yield take(LOAD_PROFILE);
  console.log('getUserDataWatcher(slug)\'s slug', slug)
  yield call(getUserProfileData, slug);
}

/**
 * Root saga manages watcher lifecycle
 */
export function* userData() {
  // Fork watcher so we can continue execution
  const watcher = yield fork(getUserDataWatcher);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

// Bootstrap sagas
export default [
  getUserData,
];
```
Here is a screenshot of the browser console output:
![screen shot 2017-01-13 at 1 01 39 pm](https://cloud.githubusercontent.com/assets/10850995/21929394/942959aa-d990-11e6-8a8a-f0102f67775e.png)

Any help would be greatly appreciated

**Comment by kylesavant** [comment]
This is how I do it with a slug called roomId:

**actions.js**
Make sure the action has an argument (roomId) and that it's passed on in the action
```
export function fetchRoom(roomId) {
  return {
    type: FETCH_ROOM,
    roomId,
  };
}
```

**routes.js**
Dispatch the action and inject the slug. Actions imported in importModules
`store.dispatch(actions.fetchRoom(nextState.params.roomId));`

**sagas.js**
```
export function* getRoom(action) {
  const roomId = action.roomId;
  let room = yield select(selectRoom(roomId));
  if (room) {
    yield put(roomLoaded(room)); // Update global room
  }
}

export function* showRoom(action) {
  console.log('show ', action.room)
}


export function* getRoomWatcher() {
  yield fork(takeLatest, FETCH_ROOM, getRoom);
}

export function* roomData() {
  const watcher = yield fork(getRoomWatcher);
}

// Bootstrap sagas
export default [
  roomData,
];

```

**Comment by jeremyadavis** [comment]
I setup most of my sagas like @kylesavant did. Note that the [takeLatest](https://github.com/redux-saga/redux-saga/tree/master/docs/api#takelatestpattern-saga-args) effect will pass on the arguments so it might seem like magic how the 'action' param makes it the getRoom method.

One thing to correct in your example would be to replace your default export in the saga to userData, not getUserData. Currently it is bypassing the watcher generators so it's correct that the slug is 0.

Also be sure that your LOAD_PROFILE action creator is dispatching the slug value so the getUserDataWatcher can grab it and pass it on to call what I think should be the getUserData generator, not getUserProfileData.

**Comment by denisflorkin** [comment]
Hello @kylesavant, thanks for the example, it made things more clear for me. My action was ok, the problem was that I did not dispatch anything - this boilerplate is so awesome that I might have excepted to do it automagically... :)
An as @jeremyadavis noticed I was trying to call unexisting function 'getUserProfileData' and also not exporting the correct generator as default export.
This is working now.
Thanks for your help

I'm still a bit un clear on the saga conceling, shouldn't the saga for my 'profilepage' container/route be canceled on 'LOCATION_CHANGE' when it's not needed anymore ? Or is 'something' actually automagically taking care of this ?

I'll leave my updated code here for the next one it might help :

**sagas.js** :
```
/**
 * Gets the profile data of a user
 */
import { takeLatest } from 'redux-saga';
import {
  take,
  call,
  put,
  fork,
  cancel } from 'redux-saga/effects';

// import { LOCATION_CHANGE } from 'react-router-redux';

import {
  LOAD_PROFILE,
} from './constants';

import {
  getUserProfileData,
  getUserProfileDataSuccess,
  getUserProfileDataFail,
} from './actions';

import request from 'utils/request';


export function* getUserData(action) {
  const requestURL =
    `https://localhost/projects/neoapi/user/${action.slug}/GET.json`

  const userprofile = yield call(request, requestURL);
  if (!userprofile.err) {
    yield put(getUserProfileDataSuccess(userprofile));
  } else {
    yield put(getUserProfileDataFail(userprofile.err));
  }
}

/**
 * Watches for LOAD_PROFILE actions and calls getUserData when one comes in.
 * By using `takeLatest` only the result of the latest API call is applied.
 */
export function* getUserDataWatcher() {
  yield fork(takeLatest, LOAD_PROFILE, getUserData);
}

/**
 * Root saga manages watcher lifecycle
 */
export function* userData() {
  // Fork watcher so we can continue execution
  const watcher = yield fork(getUserDataWatcher);
}

// Bootstrap sagas
export default [
  userData,
];

```

**actions.js** :
```
(...)
export function getUserProfileData(slug) {
  return {
    type: LOAD_PROFILE,
    slug,
  };
}
(...)
```

**routes.js**
```
(...)
}, {
      path: '/profile/:slug',
      name: 'userProfile',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/ProfilePage/actions'),
          System.import('containers/ProfilePage/reducer'),
          System.import('containers/ProfilePage/sagas'),
          System.import('containers/ProfilePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([actions, reducer, sagas, component]) => {
          injectReducer('profilePage', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
          store.dispatch(actions.getUserProfileData(nextState.params.slug))
        });

        importModules.catch(errorLoading);
      },
    }, {
(...)
```

**Comment by kopax** [comment]
@denisflorkin how do you wait until the async operation is finish to trigger the route change ?

I've tried to play with https://github.com/jfairbank/redux-saga-router but I can't get integrated on top of react-boilerplate.

**Comment by denisflorkin** [comment]
Hello @kopax, if I understand correctly, I'm not waiting. I change route immediately and the 'page' component that is the target of the route change (here: ProfilePage) handle displaying a loader if the data aren't there yet

**Comment by rentrop** [comment]
@denisflorkin Thanks for sharing your code in depth. Reading this was much clearer than the doku on the topic: https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/routing.md#dynamic-routes

**Comment by denisflorkin** [comment]
@rentrop glad this could be of help :)

**Comment by filipveschool** [comment]
@denisflorkin @kylesavant  Would it be possible to share your project or explain what you did? Because for some reason it still doesnt work for me. I will share my code in a bit.

**Comment by soundstripe** [comment]
This thread was very helpful to me...I suggest using it to amend the outdated (with broken links) routing.md README.

**Comment by kunal-arora** [comment]
Hello guys,
I was facing the same issue, this post really helped me solve it. 
There is another issue which is regarding the initial render.
When I use dynamic routing and change the routes, The initial render still shows the old state data. Can anyone help me with this, here is the link to my [routes.js](https://github.com/gitserverhu/ustraa_v2_react/blob/feature/mobileCategoryPage/v1.6/app/routes.js)
