### ISSUE TITLE
Conflict with react-infinite-scroller

### ISSUE THREAD

**Issue by vanhtuan0409** [mxstbr/react-boilerplate#1457]
I tried to use this boilerplate with [react-infinite-scroller](https://github.com/CassetteRocks/react-infinite-scroller) but this error popup

<img width="595" alt="screenshot 2017-01-14 14 12 52" src="https://cloud.githubusercontent.com/assets/8175932/21952554/95b26c84-da63-11e6-8081-a8de790e6f7c.png">

I think it has some problem with ES6 config but cannot trace where it is
If someone has found a way to resolve this problem. Can you post it here

**Comment by gihrig** [comment]
See [here](https://github.com/mxstbr/react-boilerplate/issues/1370#issuecomment-268438354) to have babel transform individual packages in `node_modules`.

**Comment by vanhtuan0409** [comment]
It works 👍  thank you a lots
