### ISSUE TITLE
[Question] redux-saga-router with react-router in boilerplate

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1458]
I have two case I am trying to resolve when doing route transition

1. create dynamique routes : (Part of my application tree is returned by our server send the route to the component.)
1. Load async data using sync code (redux-saga)

For the dynamique routing case, I have before tried to edit `router.js` like this, to see how import will behave in a loop : 

```jsx
class Route {
 constructor(path, name, componentPath) {
   this.path = path;
   this.name = name;
   this.component = componentPath;
 }
}

class Pages {
 constructor(routeList) {
   routeList.forEach((route) => {
     this[route.name] = route;
   });
 }
 createRoutes() {
   const routes = [];
   Object.keys(this).forEach((name) => {
     const route = Object.assign({}, this[name]);
     routes.push({
       path: route.path,
       name: route.name,
       getComponent(location, cb) {
         import(route.component)
           .then(loadModule(cb))
           .catch(errorLoading);
       },
     })
   });
   return routes;
 }
}

export const pages = new Pages([
 new Route('/', 'home', '/containers/HomePage'),
 new Route('/getting-started/introduction', 'introduction', 'containers/gettingStartedPages/Introduction'),
]);


export default function createRoutes() {
 return pages.createRoutes();
}
```

This of course crash, but I don't know why...

Why don't we just use the `require` like in : https://github.com/ReactTraining/react-router/blob/master/docs/guides/DynamicRouting.md ? 

Do you know how this could be integrated properly in react-boilerplate ?

I will have to then have a method like `injectRoute` and `replaceRoute` I guess.

Regarding the async and saga question, I have enough case in my application to think adding this plugin that pretend to do the job :

 [redux-saga-router#react-router](https://github.com/jfairbank/redux-saga-router#react-router) purpose an integration with the router, but I can't really understand how I should translate these `import('containers/...')` in webpack.

Does anyone has a small gist or a small integration to demonstrate how this could be done ?

I would love to see this included in the boilerplate, it's like if we using 50% of our async loading that can't be done in route change using redux-saga.

**Comment by michaelcuneo** [comment]
Not sure I understand exactly where all this is going wrong. You're using the latest boilerplate yes?

(Part of my application tree is returned by our server send the route to the component.) This part here... is where it's gets weird. Part of the application's routes, i.e. pages that the server is meant to go back and forward between is returned by the server? The application is sitting on the server, how does it not know it's own routes? If it needs to be top level, i.e. (a variable found out after the server has been started and is running), on top of those routes that are hard coded into the base of the boilerplate, push it in as normal top-level code, without routes. Forward people around with buttons, and such. I'm fairly sure the low level routing was never intended to be dynamic.

Not sure if I got this right. Someone correct me if I'm wrong.

**Comment by kopax** [comment]
> You're using the latest boilerplate yes?

3.4.0

>  This part here... is where it's gets weird. Part of the application's routes, i.e. pages that the server is meant to go back and forward between is returned by the server? The application is sitting on the server, how does it not know it's own routes? 

The application use an `express` server to serve it's index.html. I have in addition another server (API).
The login success action fetch the menus and add them to the store, this sounds a bit weird, but I don't wan't to keep any route on my client, the client should scale to the servers routes returned for my users.

> I'm fairly sure the low level routing was never intended to be dynamic.

This is also my feeling and my point. We use `redux-saga` in the boiler plate but only part of it's potential.

1. Should redux-saga-router be added in the boilerplate instead of the original router.
2. How to solve this import failing on execution in order to build my routing ?

**Comment by michaelcuneo** [comment]
What I mean, is I don't fully understand your use case to figure out how to work out what you should do... but if I get what you're saying correctly... you should, leave the routes which you know about, routes that will never change and be part of the framework, in the routes.js file... but in this route.js file... pull in a new Reducer into the combineReducers function for the additional Dynamic Routing, which is yet to be known... append that Dynamic Routing reducer to the list before the asyncReducers, then run a higher level location.state on top of the existing aSync routes. ... 

/**
 * Creates the main reducer with the asynchronously loaded ones
 */
export default function createReducer(asyncReducers) {
  return combineReducers({
    route: routeReducer,
    global: globalReducer,
    language: languageProviderReducer,
    viewer: viewerReducer,
    ...asyncReducers,
  });
}

Route, Global, Language and Viewer will all work independently of one another, they do their own jobs, so just make one new one called DynamicLocations and write .js to handle bringing in new routes and appending them as locations as necessary.

I hope this helps. I'm a 20+ years developer, but this is only my 2nd month of JavaScript.

**Comment by kopax** [comment]
@michaelcuneo, it's the new viersion of javascript so it's much faster to learn how to write proper code.

I see that you would solved the dynamic routing issue by injecting a new reducer. What will be the job of this reducer and how would you get the new route into the router daemon ?
