### ISSUE TITLE
Eslint config in a separate file

### ISSUE THREAD

**Issue by alexidsa** [mxstbr/react-boilerplate#1459]
I'm trying to setup Eslint support for WebStorm and it requires a separate .eslint config file. But currently Eslint configuration is stored as part of package.json. Could we change it? If yes, I would be glad to make a PR.

**Comment by mxstbr** [comment]
See #185 and the subsequent PR #187

**Comment by gihrig** [comment]
@alexidsa For Webstorm support see the [docs](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md#using-this-boilerplate-with-webstorm). It covers debugging and Eslint.
