### ISSUE TITLE
Link to redux-saga docs is broken

### ISSUE THREAD

**Issue by gregoralbrecht** [mxstbr/react-boilerplate#1463]
The [`introduction.md`](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/introduction.md#core) links to the wrong page for `redux-saga`.

This one is linked: http://yelouafi.github.io/redux-saga/
I think this is the right one: https://redux-saga.github.io/redux-saga/

**Comment by KarandikarMihir** [comment]
Thanks. Could you send a PR?

**Comment by mxstbr** [comment]
Thanks for the PR @gregoralbrecht, this is fixed! :tada:
