### ISSUE TITLE
async loaded

### ISSUE THREAD

**Issue by kopax** [mxstbr/react-boilerplate#1464]
## Issue Type

- [x] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I have the following router 

```jsx

export default function (store) {
  // Create reusable async injectors using getAsyncInjectors factory
  const { injectReducer, injectSagas } = getAsyncInjectors(store);

  injectSagas(appSagas);
  injectSagas([routeSagas]);

  return [
    {
      path: pages.pageLogin.path,
      name: pages.pageLogin.name,
      onEnter: checkAuth(store),
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          import('containers/LoginPage/reducer'),
          import('containers/LoginPage/sagas'),
          import('containers/LoginPage'),
        ]);

        const renderRoute = loadModule(cb);
        importModules.then(([reducer, saga, component]) => {
          // here we load asynchronously one saga and one reducer
          injectReducer('login', reducer.default);
          injectSagas(saga.default);
          renderRoute(component);
        });
      },
    },
  ];
}

```

I need to dispatch an async saga before the transition, is this possible ?

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM: 7.4.0
- Browser: chrome

**Comment by mxstbr** [comment]
This question is better suited for [StackOverflow]. (you can use the `react-boilerplate` tag there) FWIW, you probably want the `routerWillLeave` hook, see the `react-router` docs: https://github.com/ReactTraining/react-router/blob/master/docs/guides/ConfirmingNavigation.md

[StackOverflow]: https://stackoverflow.com
