### ISSUE TITLE
CI/appveyor/branch stalling PRs

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#1466]
@mxstbr 
![image](https://cloud.githubusercontent.com/assets/1481063/21964689/c873f596-db05-11e6-8dd1-e5b218eb772c.png)
![image](https://cloud.githubusercontent.com/assets/1481063/21964740/e84d01f4-db06-11e6-8459-bdbd253a7edc.png)

From [AppVeyor Updates](https://www.appveyor.com/updates/2015/11/06/) Nov-6-2015
![image](https://cloud.githubusercontent.com/assets/1481063/21964730/b219b79e-db06-11e6-8e8f-d26319f3c374.png)

Based on the above, .../branch is for regular push builds. This is currently holding up several PRs. Do we actually need it on a protected branch?

**Comment by gihrig** [comment]
@mxstbr 

Problems with GitHub hooks are blocking PR merge. Please remove:
**appveyor/branch**
**deploy/netlify**

These checks are unreliable and don't offer much (if any?) value. Can we just turn them off please?

**Comment by mxstbr** [comment]
Done, sorry for the delay.

(we should really move to an organisation so you can do this too...)
