### ISSUE TITLE
Remove ".react" from docs and code

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#1467]
In the docs and in code there are a few instances of `.react` being used in file names. 

To may way of thinking this just adds clutter and confusion, similar to use of the `.jsx` extension, I would like to see it removed.

Thoughts?

Ref:
![image](https://cloud.githubusercontent.com/assets/1481063/21972601/70ac6a54-db6f-11e6-8871-53f87ee44f82.png)

**Comment by KarandikarMihir** [comment]
@gihrig I agree. Are you sending a PR?

**Comment by gihrig** [comment]
I would be happy for you to do that, if you would like 😁

**Comment by gihrig** [comment]
Done in #1469 Thanks @KarandikarMihir! ✨
