### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by 18601673727** [mxstbr/react-boilerplate#1472]
Boilerplate version: 3.3.3
Webpack version: 2.2.0-rc.7
offline-plugin version: 4.5.5
```
    ERROR in ./~/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/offline-plugin/empty-entry.js
    Module not found: Error: Can't resolve 'exports' in '/Users/xxx/project/node_modules/offline-plugin'
    BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                     You need to specify 'exports-loader' instead of 'exports'.
     @ ./~/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/offline-plugin/empty-entry.js 1:0-42
```

**Comment by KarandikarMihir** [comment]
I could not reproduce this on my machine.

`npm run setup`
`npm run build`
:white_check_mark: Successful

`npm run clean`
`npm run build`
:white_check_mark: Successful

OS: Ubuntu 14.04
RBP: 3.3.3

Can you specify repro steps?
![screenshot from 2017-01-17 102928](https://cloud.githubusercontent.com/assets/17466938/22008319/1c5e1326-dca0-11e6-95c0-9dcce415e036.jpg)

**Comment by gihrig** [comment]
@18601673727 I ran into something similar. My solution was to `rm -rf node_modules` the 'yarn'.

If you don't have [Yarn](https://yarnpkg.com/) package manager installed you should, but `npm install` should work too.

**Comment by 18601673727** [comment]
Thanks @gihrig but doesn't work for me, I regenerated the project in `3.4.0` and everything goes well.

**Comment by designbyadrian** [comment]
@18601673727 What was the change in 3.4.0 that solved your issue? I'm not in a position to replace the entire project.

**Comment by IvanoffDan** [comment]
Add this to your webpack.base.babel to fix on earlier versions:
```
new webpack.ProvidePlugin({
      fetch: 'exports-loader?self.fetch!whatwg-fetch',
    });
```

**Comment by 18601673727** [comment]
@designbyadrian sorry for the delay but the change list is huge and I've already switched for a long time.
