### ISSUE TITLE
Styled components inside component/container test folder are ignored

### ISSUE THREAD

**Issue by BrandoIsNotASword** [mxstbr/react-boilerplate#1474]
It doesn't matter if it is a clean or used instalation of the boilerplate, apparently the test archives inside the component/container test folder are ignored.

For example, the Wrapper.test.js inside Footer.js

![image](https://cloud.githubusercontent.com/assets/3867650/22036323/12a90d92-dcc1-11e6-808a-189460f151ee.png)

The test doesn't break, but the Footer's <Wrapper /> tests are not found, neither other child components tests that are inside the test folder of the parent component.

**Comment by kopax** [comment]
Is this happening with `v3.3.3` of react-boilerplate ? 
This might be related to this [#1314](https://github.com/mxstbr/react-boilerplate/issues/1314).

Changing to `v3.4.0` solved the issue of ignored karma tests for me.

`3.4.0` bring up Jest testing and also an individual run test possibility which help improve our productivity.

**Comment by BrandoIsNotASword** [comment]
It was `v3.3.3`; thanks @kopax, changing to `v3.4.0` fixed the issue.
