### ISSUE TITLE
[Feature] Implement Redux-Actions 

### ISSUE THREAD

**Issue by jeremyadavis** [mxstbr/react-boilerplate#1476]
## Issue Type
- [x] Feature

## Description
In a few weeks I'm about to start another project off of this boilerplate and the first thing I usually do after cleaning it is implement [redux-actions](https://github.com/acdlite/redux-actions).

I haven't seen any discussion around the topic and was curious if you'd be interested in a PR for it.

Pros
- Removes action type constants file.
- Cleans up reducer file syntax.
- Standardizes actions to [Flux Standard Actions](https://github.com/acdlite/flux-standard-action).

Cons
- Adds new dependency
- Adds new reducer syntax style that differs from how most tutorials explain reducers.

I've been very happy with it in my apps. I have less boilerplate syntax to maintain and I can confidently get my params from actions without needing to look back at the action creator definitions.

**Comment by gihrig** [comment]
@jeremyadavis Always in favor of reduced boilerplate, I would like to see examples of implementation (I didn't get a clear idea from the r-a project README). Need not be a full PR, unless that's easiest for you. Just a couple of snippets showing how action and reducer code is handled would be a great start. 😀

**Comment by jeremyadavis** [comment]
K, I did a basic 1:1 conversion for the [App files](https://github.com/jeremyadavis/react-boilerplate/commit/556c461064ddd20f49fd256958aca6a47964ef41)

Redux-actions has a few different flavors of syntax that can be implemented. While this might not be the most terse style, I feel that the code is still readable and maintainable whereas some of the others ways were more confusing and/or depend too much on knowing how the redux-actions methods work.

If I did a full conversion I'd probably tweak a few other things like have the saga catch blocks send Error objects so that the [FSA](https://github.com/acdlite/flux-standard-action) can set the error flag.

**Comment by jsvg** [comment]
With [redux-saga 1.4.3](https://github.com/redux-saga/redux-saga/releases/tag/v0.14.3), you can drop the `.toString()` method in your saga watcher to: `yield takeLatest(loadRepos.toString(), getRepos)`. That aside, I really like the reduction in boilerplate this would bring.

**Comment by jeremyadavis** [comment]
@jsvg  Thanks, good to know.

**Comment by mxstbr** [comment]
I'd much rather get rid of things than add even more abstractions at this point. `redux-actions` is great, but I know a lot of apps that are fine without it so I don't see a good reason to include it by default. Adding it is quite easy anyway!

Closing for now, thanks for kicking off this discussion.

**Comment by gihrig** [comment]
@jeremyadavis I've been experimenting with redux-actions in my work project. So far I really like the simplification of action creators, I'm finding declarative reducers to be hard to debug though.

I can easily add `console.log()`statements to a function based reducer, but not a declarative style `handleAction` reducer.

Do you find this to be a downside to `handleAction`? Do you have an alternative?

**Comment by jeremyadavis** [comment]
I use either the [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) plugin for Chrome to inspect the actions or just ```console.log``` the payload in the reducer.

With redux-actions following the [FSA](https://github.com/acdlite/flux-standard-action) standard there really isn't much to debug with the actions themselves. If I'm only expecting a single item with the action, then I just use payload. If I'm expecting more than one item then I know payload is an object with the properties on them.

I do use a very simple implementation of redux-actions and I know there are several ways to accomplish the same things, so you might have more luck digging deeper into the other syntaxes.
