### ISSUE TITLE
Including Twilio CDNs to the project

### ISSUE THREAD

**Issue by nielswh** [mxstbr/react-boilerplate#1478]
I've been assigned to use Twilio with our current project that uses the react-boilerplate.

However one of the conditions of using Twilio chat is including two script files at the end file. (normally after the webpack bundle)

However, there is a comment in the index.html file
-- HtmlWebpackPlugin automatically includes all assets (e.g. bundle.js, main.css) with the correct HTML tags, which is why they are missing in this HTML file. Don't add any assets here! (Check out webpackconfig.js if you want to know more) -->

I could not for the life of me find the webpackconfig.js file.

Where would I include the following CDN so that they included?

https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js
https://media.twiliocdn.com/sdk/js/chat/v0.11/twilio-chat.min.js

Any help on where I need to include these CDN files would be very helpful.

**Comment by jeremyadavis** [comment]
The text got updated in #1435 to reference the correct directory. ***Spoiler Alert*** It's in internals/webpack/

The proper way to do what you're wanting would be to find the equivalent twilio npm packages, npm install them and then import/require the package in the app/containers/App/index file. From there webpack will make sure to bundle all the appropriate files/assets.

Or you could just add the <script> tag reference to the CDN files in the index.html file

**Comment by jeremyadavis** [comment]
I've never worked with Twilio so I'm not sure why npm installing the [common](https://www.npmjs.com/package/twilio-common) and [chat](https://www.npmjs.com/package/twilio-chat) packages can't be imported like normal packages.

Try putting your CDN script references in the index.html head tag. The webpack plugin does a lot of magic in the body tag, so maybe it's getting wiped if it's in there.

**Comment by nielswh** [comment]
Thanks Jeremy.  I moved it to the head and that did the trick!!
