### ISSUE TITLE
Code coverage reports using isparta

### ISSUE THREAD

**Issue by jbinto** [mxstbr/react-boilerplate#148]

**Comment by mxstbr** [comment]
Code coverage would indeed be great, I tried getting it to work with Istanbul before but got stuck helplessly. Would love a PR for this!

**Comment by jbinto** [comment]
I have this mostly working, but of course, another wrench.

The `redux-saga` code depends on generators, and the output from `isparta` for the saga files is totally broken.

I had to include `babel-polyfill` to get generator support in Chrome. From what I can tell, `facebook/regenerator` does not (fully?) support source maps. So, anything around sagas would be broken.

I'll post what I have, and maybe open an issue on redux-saga to see if anyone else has figured it out.

**Comment by jbinto** [comment]
#155

**Comment by jbinto** [comment]
Closing this now.
