### ISSUE TITLE
Very simple nginx  configuration for routes in a production build

### ISSUE THREAD

**Issue by TimMeade** [mxstbr/react-boilerplate#1480]
This is not an issue, but I'm new to this forum. 

So I packed up my first production build yesterday.   After 5 hours of eslint fixes and writing tests, I was pretty pleased with the webpack nice clean build.  I moved it over to a new nginx install and had a running production version.

I then noticed that the refresh was not working on the url routes.  So back to the docs and 2 hours of playing with the configs per the documentation here and still no luck.   

Then I stumbled on this:

        location / {
           try_files $uri $uri/ /index.html;
        }

Simply adding that to the location in the main nginx.conf file fixed everything.   

I just wanted to post here for someone to verify and maybe post for others.

Thanks everyone, we are love, love, loving this boilerplate.  

Tim

**Comment by gihrig** [comment]
@TimMeade Did you see [app/.nginx.conf](https://github.com/mxstbr/react-boilerplate/blob/master/app/.nginx.conf) ?

Discussed further [here](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/server-configs.md).

**Comment by TimMeade** [comment]
Yes i tried to get that to work for several hours.   I could not.  ngnix kept throwing errors.   The simple change above did everything we need with refresh and react-router.  I'll go ahead and close. This is not an issue.

**Comment by heshamelmasry77** [comment]
so how you solved this at the end

**Comment by mndvn** [comment]
Hi Guys, 

I have changed my vim /etc/nginx/sites-avaliable/default file as on the following file  
https://gkedge.gitbooks.io/react-router-in-the-real/content/nginx.html 
But There is no change now. I mean I have not dealt with the problem. After refreshing the page, I got 404 Error.

**Comment by MinasA1** [comment]
```
location / {
       try_files $uri /index.html;
    }
```
Answer [here](https://stackoverflow.com/questions/43951720/react-router-and-nginx)

**Comment by omermindivanli** [comment]
Thanks MinasA1, Have a nice day...
