### ISSUE TITLE
Active Anchor Tag

### ISSUE THREAD

**Issue by L3ARNING2B** [mxstbr/react-boilerplate#1482]
# React Boilerplate

## Description
I want to know if it is possible to use the anchor tag and make them active with automatic scrolling ?
Does it better with A tag or Link ?

## Exemple A tag
```sh
export default class TextContent extends React.Component {
  render() {
    return (
      <div>
        <H1 className="bd-title" id="content">
          <A className="anchorjs-link " to="#content" >
            Text Content
          </A>
        </H1>
      </div>
     )
  }
```

## Original effect (using js)
See [ Basic-Left anchorjs exemple](https://www.bryanbraun.com/anchorjs/#basic-link-left)

# Versions
- React-Boilerplate: 3.4.0
- npm: 3
- node: 5

**Comment by KarandikarMihir** [comment]
@L3ARNING2B I don't see how this is an issue with `react-boilerplate`. Please use StackOverflow.
