### ISSUE TITLE
Documentation - Sass.md - New Webpack loader suffix problem

### ISSUE THREAD

**Issue by vedatmahir** [mxstbr/react-boilerplate#1485]
New webpack version no longer allowed to omit the '-loader' suffix when using loaders.
In https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/sass.md we need to specify 'sass-loader' instead of 'sass'.

**Comment by KarandikarMihir** [comment]
@vedatmahir Thanks for submitting this!

**Comment by mxstbr** [comment]
Thanks @vedatmahir!
