### ISSUE TITLE
Authentication implementation in routes

### ISSUE THREAD

**Issue by wer32** [mxstbr/react-boilerplate#1489]
Hi can you please help to found a way to implement authentication check in routes.
I've found https://github.com/mjrussell/redux-auth-wrapper propect which implement this great,\
But there is a problem in this project. It is required to define single component to Route
But current project in some cases reqired to initialize several components

```
const importModules = Promise.all([
          import('containers/HomePage/reducer'),
          import('containers/HomePage/sagas'),
          import('containers/HomePage'),
        ]);
```

For example for HomePage above.

Is there any common way to check role of user or some other condition?
As an option how can I use redux-auth-wrapper ?

**Comment by mxstbr** [comment]
This question is better suited for StackOverflow. (you can use the `react-boilerplate` tag there) Also see [previous discussions](https://github.com/mxstbr/react-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue%20redux-auth-wrapper).
