### ISSUE TITLE
Location of test files

### ISSUE THREAD

**Issue by jbinto** [mxstbr/react-boilerplate#149]
There seems to be a lack of consistency in React land as to where to put your tests. Options include:

* Having multiple, nested `__test__` directories (like the official React repo, and react-router)
* A `.test.js` file beside the code being tested (what we're doing today)
* A top level `./test` or `./spec` directory

Personally, I like the top-level `test` directory the most. (Maybe it's my Rails/Ember background). When I start work on a new code base I want to see all of the tests first, and in one place. 

Right now, we only have component tests, but there's no reason we couldn't have reducer, saga, etc. tests as well. I really like the idea of `app` and `test` mirroring each other in terms of directory structure (e.g. `app/reducers` => `test/reducers`).

I'm open to have my opinion changed though, especially if it'd be going against an established trend.

**Comment by mxstbr** [comment]
I'm not a big fan of copying the folder structure of the app folder in a separate folder – especially in large apps, this gets really tiring and error-prone. Having the tests right next to the parts being tested also makes it easier to find the relevant tests.

That was my reasoning behind going with the tests-next-to-tested thing, but I'm happy to reevaluate if you think that's not the optimal solution!

**Comment by mxstbr** [comment]
I'll close this issue for now, if you have more concerns feel free to comment again/reopen it!
