### ISSUE TITLE
Calling .toJS() in generators' selectors

### ISSUE THREAD

**Issue by kelsonic** [mxstbr/react-boilerplate#1490]
In the generators, the selectors have these lines:
```
const select{{ properCase name }} = () => createSelector(
  select{{ properCase name }}Domain(),
  (substate) => substate.toJS()
);
```
Shouldn't we refrain from calling `.toJS()` in selectors since [it is very expensive](https://github.com/jaredpalmer/react-production-starter/issues/136#issue-175815188), especially if the selector is called multiple times?

**Comment by gihrig** [comment]
From the reselect [README](https://github.com/reactjs/reselect#reselect):

> Selectors are efficient. A selector is not recomputed unless one of its arguments change.

That's the whole point of using selectors. The expensive operation is only executed when needed.

**Comment by Augustin82** [comment]
Sure, but the question is, why use .toJS() at all?

**Comment by kelsonic** [comment]
Selectors are optimized, I fully agree. However, I believe `.toJS ()` should never be called (if possible) since it is an expensive operation. This means using immutable data structures even in the views, which should optimize performance.

**Comment by adjnor** [comment]
Or we could use something like [updeep]( https://github.com/substantial/updeep) instead, it has a declarative API and uses native javascript objects, so no need for .fromJS() and .toJS(). I'd be up for trying to migrate the boilerplate to updeep if interested

**Comment by jeremyadavis** [comment]
@gihrig Clarify something for me then, if you would. If the selectors don't recompute unless one of their input selectors do, does that mean that shouldComponentUpdate will work as expected when comparing object props?

For me personally, I've always returned immutable types from my selectors and rarely do the .toJS(). Granted though, I'm not a fan of having to remember the .get() method of selecting object properties as it often leads to me forgetting and hitting runtime errors.

**Comment by gihrig** [comment]
@jeremyadavis To be honest, I have not tested it. But the point of "memoization" (caching) is that selectors return a copy of the previous result rather than computing a new result. If the returned result is identical to the previous result, I would expect shouldComponentUpdate to return false.

The Reselect [FAQ](https://github.com/reactjs/reselect#faq) indirectly sheds light on this issue.

**Comment by mxstbr** [comment]
Would appreciate somebody benchmarking the actual performance implications. I haven't noticed any problems related to this, so closing for now.
