### ISSUE TITLE
Question - Getting the state

### ISSUE THREAD

**Issue by ThibaultLesuisse** [mxstbr/react-boilerplate#1492]
If been working with your boilerplate and it's awesome but something bothered me. I made a goals overview. A list of goals for the week and i did it with redux. However when calling the state ( used combined reducers ) I could only call it with `state.get('counterPage').goals` and not with `state.counterPage.goals`
Why?

**Comment by KarandikarMihir** [comment]
That is because we're using immutable js. As the name suggests, it prevents you from mutating state directly. You'll have to use `get` to retrieve the data.
