### ISSUE TITLE
Hot module reloading doesn't preserve state in PureComponents

### ISSUE THREAD

**Issue by colophonemes** [mxstbr/react-boilerplate#1495]
Hot module reloading is one of the best DX features of the boilerplate, but if you're creating components by extending `React.PureComponent` (as opposed to `React.PureComponent`) then you lose application state on a HMR update.

Is there a way to use `PureComponent` with HMR, or do I need to just develop using `Component`?

**Comment by gihrig** [comment]
For the time being, HMR only works with `Component`. In version 3.4 the boilerplate automatically reloads the page when HMR fails, so state is lost.

More on this at #1220 and #1357 (react-boilerplate 3.4 only).
