### ISSUE TITLE
Build can not find rimraf and eslint

### ISSUE THREAD

**Issue by alexidsa** [mxstbr/react-boilerplate#1497]
I'm trying to run tests on 3.4. First I got an error that rimraf could not be found (though it was installed in node_modules). I "fixed" that by installing it globally. Then the same error happened with eslint. I tried to implement the same "fix" and it kinda worked but now eslint wants me to install all its plugins globally.

Either I'm doing something wrong or there's a problem with these references for test build (seems like they are referenced globally, not from node_modules).

**Comment by alexidsa** [comment]
Removed node_modules and reinstalled packages. Somehow it helped.

**Comment by KarandikarMihir** [comment]
@alexidsa Thanks for the solution! :)
