### ISSUE TITLE
Eslint errors are not shown when you start an application

### ISSUE THREAD

**Issue by alexidsa** [mxstbr/react-boilerplate#1498]
I used to use react-hot-boilerplate and eslint errors were immediately shown in a browser. With react-boilerplate I didn't see them and even thought I have no erros for a while but then I ran "npm run test" and all the erros are there.

Is there a way to show eslint errors immediately during development? If yes, why is it not a default option?

**Comment by gihrig** [comment]
It is expected that you will have ESLint configured in your editor. This way you see lint errors instantly as you type. There are instructions for setting up ESLint with WebStorm in the docs, but most popular editors support an ESLint plugin that provides this feature.

**Comment by alexidsa** [comment]
I should've been more specific. I do have errors shown to me in Web Storm. But sometimes you can miss it (especially when copy-pasting from other projects) and I expect to see these errors in a browser but I don't.

**Comment by mxstbr** [comment]
I don't think this is necessary functionality for now, it just distracts from actual errors.

**Comment by alexidsa** [comment]
Hm... I have mixed feelings about treating eslint errors as not actual errors. If we don't consider them as such then may be we should reconfigure them as warnings.

All I'm saying it's quite inconvenient to suddenly get all those errors in console during build and have no autoreload during fixing them (have to rebuild to check whether I'm done with them).

I would really like to know what others think about this potential feature.
