### ISSUE TITLE
Server Rendering

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1499]
if anyone has successfully created a rendering server using this boilerpate ? 

I observe what is done in [this commit](https://github.com/mxstbr/react-boilerplate/pull/1236)
but not yet updated

**Comment by mxstbr** [comment]
See #92, #625, #1236 and the myriad of other discussions. I also think [`isomorphic-webpack`](https://github.com/gajus/isomorphic-webpack) by @gajus might work with react-boilerplate!

**Comment by gajus** [comment]
> See #92, #625, #1236 and the myriad of other discussions. I also think isomorphic-webpack by @gajus might work with react-boilerplate!

There is blocker related to Immutable.js that prevents from raising a PR at the moment. :-(

https://github.com/gajus/isomorphic-webpack/issues/12

I will prioritise it to see if I can find a workaround.

**Comment by mxstbr** [comment]
We might remove ImmutableJS (see #1384, #441), so if you're willing to give #1384 a go that might be quicker?
