### ISSUE TITLE
npm run setup  ; fails Error: Cannot find module 'lodash/defaultsDeep'

### ISSUE THREAD

**Issue by auswalk** [mxstbr/react-boilerplate#1500]
ubuntu:~/apps$ git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
Cloning into 'react-boilerplate'...
remote: Counting objects: 365, done.
remote: Compressing objects: 100% (316/316), done.
remote: Total 365 (delta 67), reused 200 (delta 27), pack-reused 0
Receiving objects: 100% (365/365), 1.87 MiB | 811.00 KiB/s, done.
Resolving deltas: 100% (67/67), done.
Checking connectivity... done.
allen@ubuntu:~/apps$ cd react-boilerplate/
✔ ~/apps/react-boilerplate [master|✔] 
12:14 $ npm run setup

> react-boilerplate@3.4.0 presetup /home/allen/apps/react-boilerplate
> npm i chalk shelljs

react-boilerplate@3.4.0 /home/allen/apps/react-boilerplate
├─┬ chalk@1.1.3 
│ ├── ansi-styles@2.2.1 
│ ├── escape-string-regexp@1.0.5 
│ ├─┬ has-ansi@2.0.0 
│ │ └── ansi-regex@2.1.1 
│ ├── strip-ansi@3.0.1 
│ └── supports-color@2.0.0 
└─┬ shelljs@0.7.5 
  ├─┬ glob@7.1.1 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├─┬ minimatch@3.0.3 
  │ │ └─┬ brace-expansion@1.1.6 
  │ │   ├── balanced-match@0.4.2 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├── interpret@1.0.1 
  └─┬ rechoir@0.6.2 
    └── resolve@1.2.0 

> react-boilerplate@3.4.0 setup /home/allen/apps/react-boilerplate
> node ./internals/scripts/setup.js

Cleaning old repository ✓
Installing dependencies... (This might take a while) ✓

Initialising new repository ✓
Done!
> react-boilerplate@3.4.0 postsetup /home/allen/apps/react-boilerplate
> npm run build:dll

> react-boilerplate@3.4.0 build:dll /home/allen/apps/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/allen/apps/react-boilerplate/internals/scripts/dependencies.js:13:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by gihrig** [comment]
Try:
`rm -rf node_modules`
`yarn install`

See [Yarn](https://yarnpkg.com/) project if you don't have it already.

**Comment by auswalk** [comment]
Yep yarn must be installed correctly for "npm run setup" to execute correctly. Thank you.
