### ISSUE TITLE
Is there an official way to update the boilerplate?

### ISSUE THREAD

**Issue by dharmawankenny** [mxstbr/react-boilerplate#1508]
Hi, i am currently using version 3.1.0 of this boilerplate, the one which still uses css loader instead of styled components, i am wondering if there is an official way to update my current boilerplate-based app to the latest boilerplate setup?

Thank you in advance, this stuff is amazing!

**Comment by KarandikarMihir** [comment]
No, currently there's no way to update the boilerplate automatically. Although it'll be fairly easy to replace old setup with the new one if you haven't touched the boilerplate stuff. If you have any ideas of automating this, we'll be thrilled to know!

**Comment by DJTB** [comment]
Realistically, as soon as you start working on an app using the boilerplate you'll end up changing some things. The only way I've found to "update" is to pull down the latest, `npm run setup && npm run clean` then do a git diff between your local copy and the cloned repo. There isn't really any way for a computer to determine what's essential to retain for your particular project.

Using linux I'm fond of [meld](http://meldmerge.org/), no idea what's popular on osx or win.

**Comment by gihrig** [comment]
I've had good (but tedious) results doing basically what @DJTB said. The only thing I would add is [GitUp](http://gitup.co) has nice simple gui that makes cherry picking much easier IMO. See #1180 for discussion.

**Comment by kurtmilam** [comment]
[create-react-app](https://github.com/facebookincubator/create-react-app) is easy to update because it's installed via npm. It would be nice to see a similar solution for react-boilerplate.
