### ISSUE TITLE
Use a real DOM for enzyme tests

### ISSUE THREAD

**Issue by jbinto** [mxstbr/react-boilerplate#151]
Even though we're running our tests through Karma/Chrome, `enzyme`'s shallow rendering has a hard dependency on `jsdom`.

This will be fixed in (currently unreleased) enzyme 2.0.

See https://github.com/airbnb/enzyme/pull/159

**Comment by mxstbr** [comment]
Do you think this will be ready for the v3 release of the boilerplate? Or do you think it's worth postponing the release if enzyme 2.0 takes longer for this?

**Comment by lelandrichardson** [comment]
@jbinto @mxstbr Just an FYI, I plan on cutting the 2.0 release some time this week.  End of week at the latest.

**Comment by mxstbr** [comment]
Nice, that's very good to know – thanks for the information @lelandrichardson!

**Comment by mxstbr** [comment]
enzyme 2.0 is out, thanks @lelandrichardson! @jbinto are you on this?

**Comment by mxstbr** [comment]
Jesse, do you want to take a look at this?

**Comment by jbinto** [comment]
Sure, I'll take a look shortly.

**Comment by mxstbr** [comment]
I went ahead and wrote the tests anyway – we now have [96% coverage](https://coveralls.io/github/mxstbr/react-boilerplate) of the example app. 👌🏼
