### ISSUE TITLE
Command to clean the example

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#159]
When starting a new project, it can be quite tedious to delete all the example code and files but keep the important boilerplate code and structure. It'd be great to have a `npm run clean` command that does that so users don't have to take care of marching through that.

----

> Note: If you want to submit a PR for this issue, work on the **v3.0.0 branch** please!

**Comment by mxstbr** [comment]
Scoping out what the command should specifically do:

- Completely emptying all the folders in `app/`, but leaving intact (resp. replacing with a minimal implementation) `app/sagas/index.js` and `containers/App`.
- Setting the `app.js`, `index.html`, `rootReducer.js` and `mainfest.json` to the state they are in at the beginning of the boilerplate (except maybe deleting all the Open Sans + Observer stuff in the `index.html` and the `app.js`)
- Emptying `routes.js`. (Maybe leaving the error route intact so people don't forget about it?)

I haven't done a lot of CLI work with Node.js, especially making sure it works across most major OSes, so I'd love if somebody else could take a crack at this!

**Comment by svenanders** [comment]
I suggest using shjs and make a script, like this: https://github.com/svenanders/ezreact-starter/blob/bootstrap/scripts/copy.js only more complex of course. 
I think the easiest way of accomplishing it is create a copy of the state you want the files to be in, and then simply remove all files you want gone and replace the ones you want to keep with the pristine ones.

**Comment by somus** [comment]
As @svenanders suggested, [shelljs](https://github.com/shelljs/shelljs) looks like the right tool for the job.

Also, replacing the files with the corresponding templates seems to be the right solution instead of modifying them. Later, even if the examples get modified, we don't have to worry about modifying the clean script.

I'll try to implement it with shelljs later today.

**Comment by mxstbr** [comment]
Awesome, sounds good!

**Comment by mxstbr** [comment]
This is done thanks to @somus! See #205
