### ISSUE TITLE
Route params

### ISSUE THREAD

**Issue by tmoc** [mxstbr/react-boilerplate#160]
There is a problem with using react-router route params (as in /route/:param).

What happens is that when a route with a param gets loaded, index.html is retrieved, and then all files are loaded relative to the param.

For example, if a route is configured as /messages/:id,  refreshing the page with /messages/1 will mean that instead of fetching /js/bundle.js, you will get /messages/js/bundle.js, which 404s (obviously).

I'm not sure what the solution is yet. I immediately thought to tweak the webpack config to use absolute URLs for the files, but html-webpack-plugin does not offer this option. It looks like the script tag's src can only match the file path exactly.

**Comment by mxstbr** [comment]
Are you on the `master` or the `v3.0.0` branch?

**Comment by tmoc** [comment]
master

**Comment by mxstbr** [comment]
I see, I'll close this issue and keep this in mind but it *should* be fixed on the `v3.0.0` branch. If you want to check that out, awesome! Otherwise see the discussion in #113 and have a look if one of the suggestions fixes your issue on `master`.

**Comment by tmoc** [comment]
Adding `publicPath: '/'` fixed the issue for me, both for the Webpack server and an Express server.

**Comment by mxstbr** [comment]
:heart: That's great to hear!

*If you're using it either personally or at work I'd love to hear from you: #115*
