### ISSUE TITLE
Tagline

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#161]
The tagline of this boilerplate up to v2 was

> "Quick setup for performance orientated, offline-first React.js applications featuring Redux, hot-reloading, PostCSS, react-router, ServiceWorker, AppCache, FontFaceObserver and Mocha"

That's a nice, short description, which is reinforced in the README and other documentation. With v3 though, we've made some big changes and the above tagline doesn't really describe the focus of this boilerplate anymore. We need a new one.

----

The main ideological change is that the boilerplate now focusses on being **the best foundation to start your big applications with**. We've adopted a new structure and made a few other improvements that help massive applications manage their scale:

- We've added tools such as reselect, ImmutableJS and react-pure-render to help manage frontend performance for large-scale applications.

- We've added improvements to the usability of the boilerplate itself, which includes remote testing with `npm run serve`, generating containers, components, routes etc. with `npm run generate`, etc.

- We made the boilerplate bulletproof, fixing dozens of issues that can only be found with real world usage.

- We've made the webpack configuration even better with chunking (code splitting) and more fixes.

(see #123 for the full list of changes) 

I'm really not sure what the focus of our "branding" of v3 should be. What do you think?

**Comment by mxstbr** [comment]
We should probably also highlight our focus on giving the users the best development experience possible with hot-reloading, generators etc. This boilerplate makes it easy and fast to build great applications, maybe that should be the main focus of the tagline?

First possible idea:

> Kickstart your new project with the best development experience, a highly scalable and solid foundation and a focus on performance and offline access.

That's not very catchy though...

**Comment by willklein** [comment]
I love where this is going! Your bold description really caught my attention:

> ...the best foundation to start your big applications with...

I personally prefer something more succinct, the tagline doesn't need to over-sell. Maybe something like:
- A foundation for big applications
- A foundation for developers writing big applications
- A performance-oriented, developer-friendly foundation for serious apps
- Next-level developer experience for great applications

:smile:

**Comment by mxstbr** [comment]
We need to show people through the tagline why they should choose react-boilerplate over any of the other starter projects. It's the first (and maybe only) thing they see of it, before they see anything else.

Saying "A foundation for big applications" is fair and probably the most honest tagline one could have, but does it really intrigue you enough to click on the link to it? I don't think so...

**Comment by mxstbr** [comment]
What about this:

<div align="center"><strong>Start your next react project in seconds</strong></div>
<div align="center">A scalable foundation with the best DX and a focus on performance and best practices</div>

**Comment by mxstbr** [comment]
Adding offline-first back in, slight wording change...

<div align="center"><strong>Start your next react project in seconds</strong></div>
<div align="center">A highly scalable, offline-first foundation with the best DX and a focus on performance and best practices</div>

**Comment by oliverturner** [comment]
Liking it: punchy, succinct, appealing.

**Comment by mxstbr** [comment]
I can't think of a way to make this better, if nobody has any suggestions I'll close this issue and add the tagline everywhere tomorrow!

**Comment by oliverturner** [comment]
My only reservation is around the "scalable" statement: what makes it so? How is it highly so? Can the value be more explicitly/clearly expressed?

**Comment by mxstbr** [comment]
Hmm, good point. It is *highly* scalable because it *should* be able to scale to a massively sized frontend. (i.e. 1000's of components and pages)

The scalability mostly refers to the architecture we chose, so maybe adding that in makes it better? It seems very long now though:

> An offline-first foundation with a highly scalable architecture, the best DX and a focus on performance and best practices

**Comment by oliverturner** [comment]
I guess my issue with "scalable" is that it's a term more often used in the context of infrastructure than architecture...

What about 
"An offline-first foundation for apps of any size, with a focus on DX, performance and best practice"

**Comment by mxstbr** [comment]
I kind of like the "A highly scalable, offline first foundation..." though, it has a really nice ring and sounds very appealing – though it might just be my non-native ears.

**Comment by mxstbr** [comment]
Added to the README!
