### ISSUE TITLE
Update to eslint 2.0

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#162]
Eslint 2.0 was just released, and we should update to it. I've done most of the work in the `eslint-v2` branch, but the airbnb javascript config is throwing lots of errors because of deprecated rules.

This will be fixed in the next release, but we'll have to wait until then to include it in the `v3.0.0` branch. See https://github.com/airbnb/javascript/issues/728

**Comment by ljharb** [comment]
I'll attempt to update eslint-config-airbnb (which requires 1.x right now) to require 2.x over the weekend.

**Comment by mxstbr** [comment]
Awesome @ljharb, great to hear!

**Comment by mxstbr** [comment]
eslint-config-airbnb is now at 6.0.0 and uses eslint 2.0, so this can be done!

**Comment by mxstbr** [comment]
Done!
