### ISSUE TITLE
Coveralls.io

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#168]

**Comment by jbinto** [comment]
It's pretty straightforward, but it requires you (project owner) to do some travis stuff. I can PR the rest.

- [ ] sign up for coveralls.io account, acquire token
- [ ] add coveralls token to your Travis environment variables

--

- [ ] install `coveralls` npm package 
- [ ] add an npm script to submit coverage data to coveralls 
- [ ] add a post-deploy hook to travis.yml to run that npm script
- [ ] add a badge in README

**Comment by mxstbr** [comment]
I've added the `COVERALLS_REPO_TOKEN` to our travis env, can you try enabling it from the repo?

**Comment by jbinto** [comment]
Not sure what you mean by "try enabling it from the repo"...

I will do the 4 items above and PR, shouldn't take long, I have it set up in another project already.

**Comment by mxstbr** [comment]
Exactly that, sorry for the weird wording. :100:

**Comment by jbinto** [comment]
Wow, looking at README, I never knew you could set variable-like things in Markdown, e.g. :

```
# React.js Boilerplate [![Dependency Status][dep-status-img]][dep-status-link] [![devDependency Status][dev-dep-status-img]][dev-dep-status-link] [![Build Status][ci-img]][ci]


[dep-status-img]: https://david-dm.org/mxstbr/react-boilerplate/v3.0.0.svg
[dep-status-link]: https://david-dm.org/mxstbr/react-boilerplate/v3.0.0
[dev-dep-status-img]: https://david-dm.org/mxstbr/react-boilerplate/v3.0.0/dev-status.svg
[dev-dep-status-link]: https://david-dm.org/mxstbr/react-boilerplate/v3.0.0#info=devDependencies
[ci-img]: https://travis-ci.org/mxstbr/react-boilerplate.svg?branch=v3.0.0
[ci]: https://travis-ci.org/mxstbr/react-boilerplate?branch=v3.0.0
```

I can't find anywhere that documents this. Cool find.

**Comment by jbinto** [comment]
PR in #169

**Comment by mxstbr** [comment]
Yeah that's pretty neat, makes for much nicer reading. Got it from the PostCSS Readme I think...

Will merge asap, thanks Jesse!
