### ISSUE TITLE
WebpackDevServer should not be used in production. 

### ISSUE THREAD

**Issue by aickin** [mxstbr/react-boilerplate#172]
Hey there, great project!

I was poking around in the server code, and I noticed that both the dev and prod configurations use WebpackDevServer to serve up the application. I think that is not optimal, as the WDS documentation is pretty clear that [it should never be used in production](https://github.com/webpack/webpack-dev-server#webpack-dev-server).

Luckily, this is a pretty easy thing to change; you can use the same webpack config to compile the code to a local directory and fire up an express server to serve up those static assets.

Cheers, and thanks for the work you do!

**Comment by mxstbr** [comment]
He @aickin, glad to hear you like the boilerplate!

`server.prod.js` gets started with `npm run serve`, it runs the website locally and tunnels it through `ngrok` so it's available and can be tested on the entire internet. I'm pretty sure nobody uses that in production. Thanks for your concern!
