### ISSUE TITLE
Switch to express.js

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#175]
Instead of using Webpack Dev Server, we should switch to express.js for the development and "production" server. (devserver breaks on complex nested routes, see #113)

I have never worked with express, so I'd rather somebody with a bit more experience fixes this, a PR would be very welcome. (on the `v3.0.0` branch)

**Comment by amorino** [comment]
Hey, I just read your twitter message. I will try to work on this this week. :D

**Comment by mxstbr** [comment]
In progress at #194!

**Comment by grabbou** [comment]
@amorino do you need any help with that? I was thinking about setting up express.js as well.

@mxstbr not sure if that's been considered yet, but what about server-side rendering? Not a big deal nowadays, but still once we integrate `express`, it should be possible to write it as a middleware that is completely optional (and maybe even developed in a separate repo)

**Comment by mxstbr** [comment]
@grabbou see #174, this is planned down the road, but I figured it'd require a complete architecture overhaul which is something that's definitely not happening for v3 – are you telling me that's not true? It'd be amazing to be able to switch in-n-out of server-side rendering very easily!

**Comment by grabbou** [comment]
Well, I **might** be wrong, but back in the day when I was working on Este, we were having it as a middleware (to do all heavy processing) with just few tricks required. It probably still requires some changes, but maybe we can somehow workaround them :D

**Comment by mxstbr** [comment]
I'd love if you could take a stab at that and provide a WIP PR!

**Comment by oliverturner** [comment]
Coupling this project so completely to Express is worrisome to me. Completely get the motivation, but would make a plea to consider a more modular approach.

**Comment by grabbou** [comment]
Could `express.(dev|prod).js` file be potentially a solution for that?

**Comment by mxstbr** [comment]
The project isn't really coupled with express, I don't think any express-specific features need to be used here. Switching it out for a different node.js server framework shouldn't be too hard, but I'm not the expert – what do you think @grabbou?

**Comment by grabbou** [comment]
Yeah, that's true. It might be just that some people would prefer sticking with plain webpack and maybe shipping HTML on its own? If that's the case, we can provide express as a submodule with its own dependencies that you can either plug-in or delete?

**Comment by mxstbr** [comment]
We're going to switch to express anyway because of a problem with `WebpackDevServer`, see #194, so feel free to go ahead and implement SSR in express!

**Comment by oliverturner** [comment]
FWIW my recommendation would be what @grabbou is proposing with an Express submodule approach: I have several apps that only need static HTML and my preference is firmly Hapi over Express. 
This is just my use case, and whatever's best for the project should win out, but thought I'd throw it out there...

**Comment by mxstbr** [comment]
I absolutely agree @oliverturner, as I tried to imply I don't think it's going to be hard to switch to hapi. At least, that's the impression I got from @grabbou! :+1:

**Comment by mxstbr** [comment]
Done by @grabbou in #211, thanks so much!
