### ISSUE TITLE
Add JSCS

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#179]
Airbnb uses eslint in combination with JSCS because there are a few rules that eslint doesn't support, see [here](https://github.com/pure-ui/styleguide/blob/master/.jscsrc) for an example implementation. We should add JSCS for v3!

**Comment by gonzochic** [comment]
Hi,
added it (see #240) ;).

**Comment by gonzochic** [comment]
Again ;) #241

**Comment by mxstbr** [comment]
Done by the amazing @gonzochic in #241, thanks so much!
