### ISSUE TITLE
Generators UX

### ISSUE THREAD

**Issue by nikgraf** [mxstbr/react-boilerplate#181]
I suggest to make a suggestion when asking for the name as otherwise you end up like me `requestJs.saga.js`.

Another question: Can we remove `.saga`? The file is anyway located in the saga folder. 

```
➜  react-boilerplate git:(v3.0.0) npm run generate

> reactjs-boilerplate@2.4.0 generate /myPath/react-boilerplate
> node ./node_modules/plop/plop.js

? [PLOP] Please choose a generator. saga - Generate a saga
? [SAGA] What should it be called? request.js
[SUCCESS] add /myPath/react-boilerplate/app/sagas/requestJs.saga.js
[SUCCESS] modify /myPath/react-boilerplate/app/sagas/index.js
[SUCCESS] modify /myPath/react-boilerplate/app/sagas/index.js
```

I also tried the `container` generator. 

```
➜  react-boilerplate git:(v3.0.0) ✗ npm run generate

> reactjs-boilerplate@2.4.0 generate myPath/react-boilerplate
> node ./node_modules/plop/plop.js

? [PLOP] Please choose a generator. container - Generate a Container Component
? [CONTAINER] What should it be called? RockOn
? [CONTAINER] Describe what the container component does? what?
? [CONTAINER] Do you want to create corresponding CSS file? No
? [CONTAINER] Do you want to generate corresponding actions/reducer files for the container? Yes
? [CONTAINER] Do you want to add selectors to the connect method? Yes
? [CONTAINER] Select one option Generate new one
? [CONTAINER] What the selector should it be called? RockOn
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/index.js
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/RockOn.test.js
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/actions.js
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/tests/actions.test.js
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/constants.js
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/reducer.js
[SUCCESS] modify myPath/react-boilerplate/app/rootReducer.js
[SUCCESS] modify myPath/react-boilerplate/app/rootReducer.js
[SUCCESS] add myPath/react-boilerplate/app/containers/RockOn/tests/reducer.test.js
[SUCCESS] add myPath/react-boilerplate/app/selectors/rockOnSelector.js
```

Feedback:
1. I had no idea what I should have provided here. Is there any effect? `[CONTAINER] Describe what the container component does?`
2. The generator asks to generate a CSS file for a container. I would consider it best practice after reading this: https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.udzbn0shp

**Comment by mxstbr** [comment]
> I suggest to make a suggestion when asking for the name

Good idea, I'll look into that!

> 1. I had no idea what I should have provided here. Is there any effect? [CONTAINER] Describe what the container component does?

Good point, going to remove that!

> 2. The generator asks to generate a CSS file for a container. I would consider it best practice

From the article you linked: `"My container components [...] never have any styles"`
I don't think adhering strictly to that is the way to go, quite often my container components do have some styles, so I think asking is the way to go here.

Thanks for the feedback!
