### ISSUE TITLE
npm run build does not write to the build folder.

### ISSUE THREAD

**Issue by debopamsengupta** [mxstbr/react-boilerplate#184]
Steps I followed:
- ```git clone``` the project
- ```npm install```
- ```npm run build```
- tried to open ```build/index.html``` in the browser.

However, it works if I ```npm start``` and open ```localhost:3000``` in the browser. 
@mxstbr

**Comment by mxstbr** [comment]
Hey, thanks for taking the time to submit a bug report! Are you on the `master` branch? Also, what do you mean with "tried to open build/index.html in the browser.", what exactly did you do?

**Comment by debopamsengupta** [comment]
Yeah, on the ```master``` branch. In the README it says
![image](https://cloud.githubusercontent.com/assets/9649659/13208045/033e3e42-d950-11e5-83c1-e5c8a88f3802.png)

so, I assumed that once I run ```npm run build``` I should be able to open the ```build/index.html``` file on Chrome and expect the static site locally without running ```npm run serve```. Am I correct ?

**Comment by mxstbr** [comment]
Not quite.

When you run `npm run build`, your app will be compiled to the `build` folder in the root of the project. To see your production application in the browser, you have to run `npm run serve` or upload the contents of the `build` folder to a web server.
