### ISSUE TITLE
Consider moving config files to `package.json`

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/react-boilerplate#185]
This is just a suggestion from my own preferences.

A lot of tools like Babel allow you to move a `.rc` or config file to `package.json`. Personally I dislike having a lot of dotfiles in the root directory that could mostly be in one place. This is especially true of "opinionated" projects like these. Also, our `.babelrc` is very short for now, so it won't look weird.

Aside from Babel, it looks like ESLint and Stylelint support this too.

Like I said, this is up to debate, but I like to hide as much config as possible.

**Comment by mxstbr** [comment]
I actually agree, the whole reason for the webpack folder is to hide as much config as possible! 

Would you mind submitting a PR with this implemented?

**Comment by sotojuan** [comment]
Would love to! Will do it by the end of the day.

**Comment by mxstbr** [comment]
Done by @sotojuan, thanks!
