### ISSUE TITLE
ApplicationCache on localhost

### ISSUE THREAD

**Issue by peter-gordon** [mxstbr/react-boilerplate#190]
There's some fierce ApplicationCache happening on localhost:3000 for me.

I'm now seeing the "Hello World" screen at http://localhost:3000, even with no node apps running, or running other projects from localhost:3000.

Clearing the Chrome ApplicationCache hasn't helped, along with a few other things I've tried. 
The result is I'm unable to use localhost:3000 until I can figure out how to resolve this.

**Comment by mxstbr** [comment]
Fixed on the `v3.0.0` branch, also see here: https://github.com/mxstbr/react-boilerplate/issues/71

**Comment by peter-gordon** [comment]
Thanks mx. A bit more info as it wasn't mentioned on #71 or #70 
I ended up resolving this by accessing the ServiceWorker internals control panel and unregistering from there: chrome://serviceworker-internals

**Comment by tconroy** [comment]
I had this issue too -- thanks for the solution @peter-gordon that did it for me ( didn't want to wipe my whole app cache ). Cheers.
