### ISSUE TITLE
webpack folder name

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#191]
Currently, we have a folder called `webpack` in the root directory. It now contains much more than just webpack configuration, so we should change the name to something else – though I can't find another word to convey the three things I want it to:

- This is configuration
- These configuration files help us make your life more awesome
- DON'T TOUCH ANY OF THIS IF YOU DON'T HAVE TO OR DON'T KNOW WHAT YOU'RE DOING

Any ideas?

**Comment by lewiscowper** [comment]
`configs` or `config`, with a doc note to say something like:

> "Everything inside the `{config/configs}` folder should be considered read only, unless you know what you're doing, and accept that stuff might break."

**Comment by mxstbr** [comment]
That could work, but users might think that they can configure meta information about their app in there, don't you think? (stuff like name, url,...)

We'd have to make the note really prominent to avoid that, which I'd rather avoid...

**Comment by lewiscowper** [comment]
`boilerplateConfig`? `internalConfig`?

**Comment by mxstbr** [comment]
I like `boilerplateConfig`, but I'd rather have it be one word since it's a folder name.

@oliverturner suggested `sys` on [twitter](https://twitter.com/oliverturner/status/702807517441761280), which is my favorite so far. It's a bit of a stretch to call this boilerplate a "system", but from a semantic perspective it's nice. (`win32` anybody? :joy:)

**Comment by oliverturner** [comment]
You could prefix it with an underscore too - `_sys` - to indicate that it's semi-private (and has the advantage of pinning it at the top of the directory listing), while another option is `internals`, which sounds pretty foreboding.

Thing is though, personally I'd want to _encourage_ people to make whatever changes that work for them / their project... to learn by doing, breaking, fixing etc. for themselves. For me `conf[ig]` is a winner.

**Comment by mxstbr** [comment]
Ooh I like `internals`, that's a great one! :+1: It implies that you can go in and change things yourself if you know what you're doing, but you normally shouldn't have to.

We could also make it hidden by calling it `.internals`, then you'd have to go look for it and know what you're doing if want to change things!

**Comment by oliverturner** [comment]
Hmm... I get the logic behind the dot prefix, but again I really feel that for a lot of folks this will be a project that's a learning platform for them, and I'd counsel against anything that makes it harder to understand at first glance _how_ all this stuff works.

Again, I'd recommend the `_internals` because it ties in with the standard naming convention for "private" properties and emphasises its specialised nature... 

What do you think?

**Comment by mxstbr** [comment]
Fair enough, I understand where you're coming from – lets just go with `internals` then! 👍
