### ISSUE TITLE
Try to implement AVA for concurrent tests

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#192]
[AVA](github.com/sindresorhus/ava) is a really cool testing framework that runs tests concurrently, thus speeding them up by quite a big margin.

I think it'd be worth investigating if there is a possibility of switching to it, though I don't have a fine-grained enough view of the testing system to say. @jbinto, can you share some insights on what you think?

**Comment by sotojuan** [comment]
I'm a contributor to AVA, so I'd love this. That said, AVA was made with Node in mind, not frontend. Reducer and action testing would be easy and I can do that, but not sure about stuff like JSX/rendering testing (I haven't used AVA to test React either, maybe you can do it now). 


// @sindresorhus @vdemedes Can you guys offer better insight?

**Comment by mxstbr** [comment]
The rendering can still be done by enzyme, AVA would basically replace Mocha. I think it's possible, I'm just not sure if Karma plays well enough with AVA for this to work out!

**Comment by sindresorhus** [comment]
Don't really have any special insight. No one on the team really needs browser support, so it haven't been a priority, and no one have contributed it. Some people were looking into using Karma, but don't remember how it turned out. Follow thread and post your findings if you decide to try https://github.com/sindresorhus/ava/issues/24.

**Comment by vdemedes** [comment]
With the right tools & helpers, I think you can test every bit of React app with AVA. Reducers/actions are just plain functions, so there's no problem there. If you need `document` or `window`, you can use `jsdom`. For React components, there is an official helper, that allows to render & test React components on the server, which should cover your needs too. React apps can easily be tested in Node.js, not necessarily in browser. So, to sum up, if you're not planning to test browser-specific APIs, AVA will be a good friend to you :)

**Comment by mxstbr** [comment]
Agreed, I don't think it will be a problem but I'm not entirely sure. @sotojuan do you want to try?

**Comment by sotojuan** [comment]
Will do after my exams next week!

**Comment by sotojuan** [comment]
Sorry, been super busy with school, but still have this on my todo-list and can start soon! Definitely want to.

For reference, @kentcdodds has done [something related](https://github.com/kentcdodds/react-ava-workshop), should be even easier with `enzyme`.

**Comment by MoOx** [comment]
There is now some recipes for AVA and react https://github.com/avajs/ava/blob/master/docs/recipes/react.md

**Comment by sotojuan** [comment]
We can update this to using Jest as IMO it fits right in with React.

**Comment by mxstbr** [comment]
Definitely agree @sotojuan, let's get Jest in! See #970 for updates on that.
