### ISSUE TITLE
Use Redux Devtools

### ISSUE THREAD

**Issue by carloscuatin** [mxstbr/react-boilerplate#197]
I see that the repository uses so I think redux redux-devtools help a lot when watching as stocks soar among other oopciones that these have

**Comment by mxstbr** [comment]
We've thought about implementing it before, and @standino actually went ahead and submitted a great PR, which I sadly had to discard – see #173 for my reasoning behind not implementing redux-devtools.

If you know of a way to solve the issues associated with it, feel free to reopen this issue!

**Comment by carloscuatin** [comment]
yes, solution is with include in new.webpack.DefinePlugin a var _DEVTOOL_ true or false for not render in production

**Comment by mxstbr** [comment]
The problem is not rendering it, but including the code for it in production. I don't want to simply not render it in production, I don't want the code for the DevTools in my bundle in production! Any ideas how to do that?

**Comment by carloscuatin** [comment]
If I use just redux-devtools in development, and not be included in the production code

**Comment by mxstbr** [comment]
How do you exclude it from the production bundle?

**Comment by carloscuatin** [comment]
the CLIENT variable is defined in webpack.dev.js and also using it to create history without having to make a Root.dev.js and Root.prod.js as exponene in sagas or in the same repository redux![redux-devtool](http://i.imgur.com/VqmXLTG.png)
