### ISSUE TITLE
Codesplitting reducers

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#199]
Right now we codesplit routes (see [`app/routes.js`](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/app/routes.js)) but all reducers are loaded with the main bundle – that doesn't make a lot of sense in large applications. They should be loaded when the corresponding route is visited.

*See [this StackOverflow answer](https://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application) for an example implementation.*

----

> Note: If you want to submit a PR for this, work on the **v3.0.0 branch** please!

**Comment by somus** [comment]
I tried it and got it working. But, there is only one reducer which is a global reducer. Should we add another one reducer to demonstrate how it works?

I'm thinking of creating a separate reducer for the homepage widget. What do you say?

**Comment by mxstbr** [comment]
Yeah that could work @somus, maybe split out the username form and make that have its own reducer, and move the `changeUsername` action and state there!

**Comment by mxstbr** [comment]
This was done by @somus, thanks!
