### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#200]
With the (currently in beta) webpack 2, we get tree shaking and a few other improvements.

Tree shaking is the practice of eliminating dead/unused code. This only works with ES6 modules, so it requires some changes to our Babel configuration. *See [this article](https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233#.vm6wn9q98) for information how to implement this.*

**Comment by 7rulnik** [comment]
I tried do it yesterday.
Faced problem with karma (or mocha?). It's crashed on import es2015 modules.
I cannot understand where and when test task executes during build task, and how fix it.
Also I think that if we switch tests to AVA problem will be eliminated.

**Comment by mxstbr** [comment]
This is likely a problem with the `webpack.test.babel.js` file, or the `karma.conf.js` file, which are in the `internals/webpack` and `internals/testing` folder respectively.

If you want to, you can also take a look at implementing AVA at the same time! I'd love that!

**Comment by 7rulnik** [comment]
Will try it tomorrow again

**Comment by mxstbr** [comment]
Done by the awesome @7rulnik in #254!
