### ISSUE TITLE
Add npm run visualize command

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#203]
Using the [webpack visualizer plugin](https://github.com/chrisbateman/webpack-visualizer) we can create a visualization where the bundle size comes from, which can be really handy! This should come as a simple npm command, maybe `npm run visualize`?

----

> Note: If you do want to submit a PR work on the **v3.0.0 branch** please!

**Comment by oliverturner** [comment]
Nice idea! Can have a crack later if you like

**Comment by mxstbr** [comment]
Sure thing, would love that!

**Comment by oliverturner** [comment]
👍

**Comment by mxstbr** [comment]
How is this coming along @oliverturner, any problems so far?

**Comment by oliverturner** [comment]
Only the absence of opportunity...

**Comment by oliverturner** [comment]
Out of interest, is there a reason to use an alternative to the version at http://webpack.github.io/analyse ?

**Comment by mxstbr** [comment]
Absolutely none, I didn't know an official visualizer exists. (maybe the command should be `npm run analyse`?)

Take a look at both of them, implement whichever one you prefer and tell my why!

**Comment by oliverturner** [comment]
That's what I called it before :)

**Comment by oliverturner** [comment]
I'm inclined to use tools directly associated with the project and supported by the author (particularly in light of the upcoming 2.0 release).

**Comment by mxstbr** [comment]
Sure thing, sounds like a good reason!

**Comment by oliverturner** [comment]
I'll get that (and the documentation PR) done tomorrow. Apologies for the delay.

**Comment by mxstbr** [comment]
No worries, thanks for the help!

**Comment by mxstbr** [comment]
This is pretty much done in #261, thanks to the always amazing @oliverturner!
