### ISSUE TITLE
[upgrade] postcss-import glob is now removed

### ISSUE THREAD

**Issue by grabbou** [mxstbr/react-boilerplate#204]
As of 8.0 - no longer part of the core.

As a workaround, it's advised to:
```js
postcssImport({
  resolve: function(id, base) {
    return glob.sync(path.join(base, id))
  }
})
```

**Comment by mxstbr** [comment]
`postcss-import` is no longer necessary with the switch to CSS modules, see the `v3.0.0` branch of this repo.

Thanks for submitting this bug though, I appreciate that!

**Comment by grabbou** [comment]
Ah, sorry, been pretty sure I'm on it already :dash:

**Comment by mxstbr** [comment]
Don't worry!

**Comment by grabbou** [comment]
BTW, amazing work on v3, took me 5 times less to strip out stuff I don't want (mainly Redux, doing static app).

Anyway, just trying it out and looks like we might stay here for a bit longer, so be ready for PRs :fire:

I'll drop you the link when I am done!

**Comment by mxstbr** [comment]
Thanks @grabbou, that's great to hear. I'd love me some issues/PRs and a link when you're done! (see #115)

**Comment by grabbou** [comment]
Sure! cc: @knowbody

**Comment by knowbody** [comment]
@grabbou nah, I'm old school :sunglasses: - using the best react boilerplate out there - https://github.com/knowbody/react-boilerplate

ok let me be **serious** now. I've played around with it in the very beginning and really liked it. Haven't used it for any projects though. Going to check out the new v3 soon.

Great work @mxstbr! Keep it up :shipit:

**Comment by mxstbr** [comment]
Hah, you'd like the [initial version](https://github.com/mxstbr/react-boilerplate/tree/bd8c4f40f6213164f646571a90d81c43ee55da82) of this one. :stuck_out_tongue_winking_eye:

Thanks, let me know what you think about it!

**Comment by grabbou** [comment]
Haha, I know you are.

But - I was so happy to jump to v3 since it fixed few annoying things I was like "hm... why?" (general syndrome of using webpack config not made by you haha)

Good work, but most importantly - very helpful atmosphere, I like that! Will go crazy and adapt it to RN at some point

**Comment by grabbou** [comment]
And... I can blow everything up and redirect to @knowbody super bare to-go awesome hot setup <3

Sure, if you like - I am happy to help on meta & docs to start with :8ball: 

PS. Looking forward to your talk in Paris!

**Comment by mxstbr** [comment]
Done, and I've added Mateusz as well while I was at it!

**Comment by knowbody** [comment]
:bow:

**Comment by grabbou** [comment]
Poland is taking over this repo, sorry :police_car:
