### ISSUE TITLE
[Docs] [Idea] Heroku

### ISSUE THREAD

**Issue by grabbou** [mxstbr/react-boilerplate#210]
Hey,

Just deployed to Heroku - leaving my feedback while it's :fire:

> In general real-life production, you'd probably want to build resources & test them on CI and then, ship build folder manually to Heroku, but most people tend to build on Heroku instead. Since it's just a static website, I did the same

and

> You will have to set NPM_CONFIG_PRODUCTION=false on Heroku to have your devDependencies installed as well. My convention when coupling backend & front-end is to make dependencies - server only and devDependencies - everything needed for building front-end.

1) Edit `package.json` scripts section:
```json
"scripts": {
    "start": "if [ \"$NODE_ENV\" = \"production\" ]; then npm run serve-prod; else npm run serve-dev; fi",
    "postinstall": "if [ \"$NODE_ENV\" = \"production\" ]; then npm run build; fi",
    "build": "NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --colors -p",
    "serve-dev": "NODE_ENV=development node internals/webpack/server.dev.js",
    "serve-prod": "NODE_ENV=production node internals/webpack/server.prod.js",
    "pagespeed": "./internals/scripts/pagespeed",
    "setup": "NODE_ENV=initialisation ./internals/scripts/init",
    "lint": "npm run lint:js && npm run lint:css",
    "lint:js": "eslint . --ignore-path .gitignore",
    "lint:js:staged": "eslint-staged",
    "lint:css": "stylelint ./app/**/*.css",
    "lint:css:staged": "stylelint-staged",
    "lint:staged": "npm run lint:js:staged && npm run lint:css:staged"
  },
```
Most importantly, move current `start` to be `serve-dev` and change `start` to choose the right command based on NODE_ENV. The serve commands still have NODE_ENV set manually in case you run them directly.

Add optional `postinstall` hook to automatically build your app when NODE_ENV = production (that's the case for Heroku).

2) Change port from `3000` to `process.env.PORT || 3000` in server.prod.js
3) Profit!

Any better ideas?

**Comment by mxstbr** [comment]
Awesome, I'd love a PR adding that documentation! (If I understand this correctly you're running the `server.prod.js` on Heroku? Is that what this does?)

Do you think there is something we can do to make deploying to Heroku easier without messing up everybody else?

*(Also, if you have a link to the application, I'd love to see it! Ref #115)*

**Comment by grabbou** [comment]
I think all the above steps are quite easy and non-breaking to make it working on Heroku.

Yeah, I am running server.prod.js, with Webpack at the moment, but going to move towards Express.js as PRed somewhere here with few optimisations :)

**Comment by mxstbr** [comment]
I just answered that here: https://github.com/mxstbr/react-boilerplate/pull/194#issuecomment-192675025, but the TL;DR is – please don't use `server.prod.js` in production. despite the (admittedly bad) naming, it is not meant to be used there!

I posted steps above to fix that misconception, because if you're running into this I don't want to know how many people out there are relying on webpack dev server for their production applications! :astonished: 

----

Thanks, I look forward to seeing it!

**Comment by grabbou** [comment]
Haha, yeah. I've knew that `devServer` inside prod is definitely not something you should run! Anyway, don't be worried, it's just there to demo the website to others w/o need of my laptop running #ngrok.

I'll update this issue when we merge the express stuff.

**Comment by webdesserts** [comment]
Yeah my first thought when I saw that `npm run start` ran `start:tunnel` was that services like Heroku expect `npm start` to be the production script. I've always had an `npm run dev` or similar because of this. Might be worth changing even if we save the Heroku docs until later?

**Comment by grabbou** [comment]
The way I am using it is NPM start proxies to run dev only when NODE_ENV != production. Otherwise it runs prod :)

**Comment by webdesserts** [comment]
@grabbou  Yes :+1: I think this is a good idea and shouldn't be tied to the Heroku docs update (as I don't even think it's Heroku specific).

**Comment by webdesserts** [comment]
Quick google and these PaaS services do too:

- Google Cloud (required) https://cloud.google.com/nodejs/resources/runtime#application_startup
- AppFog (allows alternate script) https://www.ctl.io/knowledge-base/appfog/deploy-nodejs-application/
- EvenNode (can also use app.js) http://www.evennode.com/docs/node

**Comment by rbeers** [comment]
I would also like to see a recipe for deploying to heroku with travis-ci or directly.

**Comment by kunal-mandalia** [comment]
Thanks @grabbou for suggesting a way to deploy. I'm using express as the server, here's how I deployed to Heroku:

1.  Tell Heroku to install dev dependencies as well as production dependencies, as per @grabbou 's suggestion
`In CLI: heroku config:set NPM_CONFIG_PRODUCTION=false`
2. Change the start script so that Heroku first builds your project and then runs your app via the server
`In package.json: "start": "webpack --config internals/webpack/webpack.prod.babel.js && node server"`

Deploying takes a little while. If anyone knows of a better way, please share 👍

**Comment by mxstbr** [comment]
Done by the great @raksonibs in #485! :+1: :fire:

**Comment by kunal-mandalia** [comment]
I tried changing the heroku build scripts as per #485 but I get these errors in heroku's application logs:

2016-06-09T21:54:35.515596+00:00 heroku[slug-compiler]: Slug compilation started
2016-06-09T21:54:35.515601+00:00 heroku[slug-compiler]: Slug compilation finished
2016-06-09T21:54:40.104157+00:00 heroku[web.1]: Starting process with command `npm run build && npm run start:prod`
2016-06-09T21:54:42.949460+00:00 app[web.1]: 
2016-06-09T21:54:42.949471+00:00 app[web.1]: > react-boilerplate@3.0.0 prebuild /app
2016-06-09T21:54:43.758286+00:00 app[web.1]: 
2016-06-09T21:54:43.758297+00:00 app[web.1]: > react-boilerplate@3.0.0 pretest /app
2016-06-09T21:54:44.415737+00:00 app[web.1]: 
2016-06-09T21:54:44.415747+00:00 app[web.1]: > react-boilerplate@3.0.0 lint /app
2016-06-09T21:54:45.127629+00:00 app[web.1]: 
2016-06-09T21:54:45.127640+00:00 app[web.1]: > react-boilerplate@3.0.0 lint:js /app
2016-06-09T21:54:52.904132+00:00 app[web.1]: 
2016-06-09T21:54:52.904174+00:00 app[web.1]: /app/app/app.js
2016-06-09T21:54:52.904184+00:00 app[web.1]: ✖ 6 problems (6 errors, 0 warnings)
2016-06-09T21:54:52.939725+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-06-09T21:54:52.941254+00:00 app[web.1]: npm ERR!     eslint . --ignore-path .gitignore --ignore-pattern internals/scripts
2016-06-09T21:54:52.941417+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-06-09T21:54:52.964635+00:00 app[web.1]: npm ERR!     npm run lint:js && npm run lint:css
2016-06-09T21:54:52.969298+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-06-09T21:54:52.987316+00:00 app[web.1]: npm ERR!     npm run lint
2016-06-09T21:54:53.011334+00:00 app[web.1]: npm ERR!     npm owner ls react-boilerplate

Steps: took a clean copy of react-boilerplate today, `npm run setup`, `npm run clean`, add `styles.css` to components (to stop lint shouting), `npm run build` works locally. Added file `Procfile` with script `web: npm run build && npm run start:prod`, `heroku create`, `heroku config:set NPM_CONFIG_PRODUCTION=false` (to install devdep in heroku), `git add .` `git commit -m "initial commit"`, `git push heroku master`. Above, heroku quits after a lint error but even not linting crops up errors later. Has anyone deployed to heroku using the method in #485 ? In the end I reverted back to the start script in my previous post which works.

Cheers

**Comment by hadifarnoud** [comment]
I also want to know the proper way to deploy to Heroku? don't want to change package.json myself
