### ISSUE TITLE
Default example styling

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#214]
Right now, the default example looks okay-ish, but it's not cross-browser tested at all and could be made nicer looking and working.

**Comment by webdesserts** [comment]
@mxstbr I could look into working on this this weekend if you don't mind me taking time from working on the website.

**Comment by mxstbr** [comment]
I think this is fine, I'd rather get the website and v3 finally out of the door. :+1: 

Closing for now, but we'll definitely revisit this after the initial release!

**Comment by webdesserts** [comment]
Sounds good 🐐
