### ISSUE TITLE
Remove React Transform

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#220]
See [here](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.so70l3qv0) for a very elaborate explanation why React Transform is going away soon.

We should move to a "cold reloading" setup, something like this: https://github.com/reactjs/redux/pull/1455

**Comment by grabbou** [comment]
I am going to apply that to my projects based on this boilerplate internally since normal hot-reloading is not working well at this stage. Once I get that working, will get back with a PR (if nobody's faster :8ball: )

**Comment by mxstbr** [comment]
:+1: Awesome, looking forward!

**Comment by MoOx** [comment]
Maybe check [react-hot-loader v3](https://github.com/gaearon/react-hot-loader)

**Comment by bsr203** [comment]
Hi. I found this boilerplate got it working, including hot reloading of functional components. it uses react-hot-loader v3 as suggested by @MoOx 

https://github.com/mgcrea/react-webpack-factory

hope it can be incorporated here as well.

**Comment by mxstbr** [comment]
Closing in favor of #1068
