### ISSUE TITLE
Error when npm installing.

### ISSUE THREAD

**Issue by thm-design** [mxstbr/react-boilerplate#221]
Today pulled a fresh copy of the repo and npm install won't complete successfully.

`npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0

npm ERR! Invalid Version: 0.0.1alpha1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0

npm ERR! Invalid Version: 1.0.2beta
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request::`

**Comment by thm-design** [comment]
I have a forked copy that I have been using for a project, I can still clone/install it on different machines. It doesn't have the latest commits from March 7th.

**Comment by thm-design** [comment]
Ah just read the commit, it says to use the 3.0.0 branch.. :D

**Comment by thm-design** [comment]
Ah should use the 3.0.0 branch yeah?

**Comment by mxstbr** [comment]
Yes, the `v3.0.0` branch is the one to use – did that work out?

**Comment by thm-design** [comment]
Yes sir it did! Apologies for the non-issue. Please close :D

**Comment by mxstbr** [comment]
Thanks, glad that worked out – enjoy v3!
