### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#226]
The two main things the config need to do:

* Redirect HTTP to HTTPS so the ServiceWorker works
* Rewrite all requests to subpages (e.g. `yourdomain.com/about`) to the root `index.html` so `react-router` can take care of routing

I've added a [`.htaccess`](https://github.com/mxstbr/react-boilerplate/blob/master/.htaccess) for Apache servers (that's what I use), but I don't have any experience with nginx.

----

> Note: Please add it to the `docs/general/server-configs.md` file on the `v3.0.0` branch and submit a PR!

**Comment by sergeycooper** [comment]
#234 Done.

**Comment by sergeycooper** [comment]
And docs #235

**Comment by mxstbr** [comment]
Done by the amazing @sergeycooper, thanks so much for the help!
