### ISSUE TITLE
Page load blank on stock Galaxy S3 samsung Android browser 

### ISSUE THREAD

**Issue by andrewvmail** [mxstbr/react-boilerplate#228]
Hi there, 

I'm not sure why but I get a blank page on the stock browser of the S3.
Can reproduce by downloading Genymotion motion and use the S3 image and open up the browser and access the site. Demo is working on Chrome browser downloaded through the app store.

Thanks
Andrew

**Comment by mxstbr** [comment]
Interesting, thanks for notifying me. Is that on `master` or on `v3.0.0`?

**Comment by andrewvmail** [comment]
It's on master, figured it out it looks like Promise is not supported on that browser. Added promise polyfill and it is working now. Created a pull request.

**Comment by mxstbr** [comment]
Not merging anything into master anymore, as stated in the README, but I'd appreciate if you could check the `v3.0.0` branch and, if relevant, send a PR against that! Thanks so much for digging into this!

**Comment by andrewvmail** [comment]
Oh missed that readme this seems to be fine in the v3 branch. Closing.

**Comment by mxstbr** [comment]
:+1: awesome, thanks for checking!
