### ISSUE TITLE
testing: code coverage and sourcemaps

### ISSUE THREAD

**Issue by bsr203** [mxstbr/react-boilerplate#231]
Hi,

excited to use this project. I am on v.3.0.0 branch and couple of questions.

1. how to generate coverage report. as per https://github.com/mxstbr/react-boilerplate/pull/155 , run `npm run test`, but I don't see any `coverage` directory.

2. Is sourcemap enabled for testing. As far as I see, when I initiate a karma debug session, I only see transpiled code.

thanks again for your work on this.
Cheers,
bsr.

**Comment by mxstbr** [comment]
The coverage report does work for me and is generated, can you double check that's not a problem on your end?

That is a good question, to be honest I have no idea. If they aren't, would you mind submitting a PR enabling them? The main conf files are in `internals/testing/` and `internals/webpack/webpack.test.babel.js`. Thanks!

**Comment by bsr203** [comment]
this is what I did, just now. 
```
git clone https://github.com/mxstbr/react-boilerplate
cd react-boilerplate
git checkout origin/v3.0.0  
npm run setup  
> reactjs-boilerplate@2.4.0 setup /Users/bsr/tmp/react-boilerplate
> NODE_ENV=initialisation ./internals/scripts/init

Cleaning old repository ✓
Installing dependencies.. ✓
Initialising new repository ✓

~/t/react-boilerplate ❯❯❯ npm run test                                                                                     master

> reactjs-boilerplate@2.4.0 pretest /Users/bsr/tmp/react-boilerplate
> npm run lint

....
....
  reposSelector
    ✔ should select the repos
  routeSelector
    ✔ should select the route
  selectLocationSelector
    ✔ should select the route as a plain JS object
  usernameSelector
    ✔ should select the username

Finished in 0.452 secs / 0.199 secs

SUMMARY:
✔ 64 tests completed
~/t/react-boilerplate ❯❯❯ ls                                                                                               master
CODE_OF_CONDUCT.md README.md          docs               node_modules
LICENSE.md         app                internals          package.json
```

there is no coverage folder.

let me know what I am doing wrong ? 

tried adding coverage in `preprocessor`, still the result is same

```
preprocessors: {
      ['./test-bundler.js']: ['webpack', 'sourcemap', 'coverage'],
    },

```

**Comment by mxstbr** [comment]
You are in fact correct, I just tried myself and the coverage was not generated. Give me one second, I'll try to figure it out

**Comment by mxstbr** [comment]
Fixed in 38330c5, very very sorry about that, my change to `process.cwd()` from `__dirpath`  in d855c7661abd821e7f67ed7e320e6d766d7e511a broke the `coverageReporter` config in `karma.conf.js`.

My bad, thanks so much for sticking with this, my bad for not trying first! Thanks!!

**Comment by bsr203** [comment]
thanks a ton.  I was bit overwhelmed with all the changes. struggled to get tape working with enzyme, and that's how I came to your package. Also like the act that you have excellent support for offline and caching. I am more confident using this package as you are so responsive and supportive. thanks again for your effort on this.

**Comment by bsr203** [comment]
About sourcemaps, it is working me on my tests, but wasn't when I tried with the tests of this package. will check later. thanks.

**Comment by mxstbr** [comment]
Glad to hear that, again I'm very sorry for how I handled this bug report, that shouldn't have happened – I was too confident in this project apparently!

Hope you enjoy this boilerplate, let me know any feedback you have and of any projects you build with it!
