### ISSUE TITLE
Question: reasoning behind changing some containers to pure functions

### ISSUE THREAD

**Issue by Kielan** [mxstbr/react-boilerplate#237]
I have been tracking changes in v3 of this repo and in the past week or two there was a rather large change making most non pagecontainers pure functions and passing in the props as a parameter. 

I don't see any explanation anywhere about the advantages or reasoning behind this change and would like to know why one would use a class component extending from react vs a function in different areas of an app.

**Comment by mxstbr** [comment]
There is a new eslint rule I tried to adhere by, but while the idea is good the rule is quite annoying. I'll reevaluate soon, and then move the ones that shouldn't be in the containers folder anyway, I just haven't come around to updating that! Thanks for the reminder!

**Comment by oliverturner** [comment]
@Kielan it's best practice to try and eliminate local state as far as possible: preferring functions simply encourages this (the so-called "pit of success").

**Comment by mxstbr** [comment]
Oh sorry I totally misunderstood the question in my morning sleepiness. Read [my SO answer](https://stackoverflow.com/questions/35724997/two-ways-of-defining-es6-react-components/35725702#35725702) for the reasoning behind using stateless functional components!

**Comment by Kielan** [comment]
Thanks for the answers @mxstbr and @oliverturner the explanations make a lot of sense to me.
