### ISSUE TITLE
How to add bootstrap and custom themes?

### ISSUE THREAD

**Issue by TangRufus** [mxstbr/react-boilerplate#238]
Where should we place the bootstrap and custom themes files?
 - add as vendor files?
 - use webpack to compile a separate `.css` file?  
 - or ??

Thanks!

P.S.: I am using the v3.0.0 branch

**Comment by mxstbr** [comment]
That is a good question, there is a few ways to do this.

The easiest one and what I'd go for is:

1. Add a separate `themes` or `styles` folder.
2. Import your `.css` files with the file loader like so

  ```JS
  import 'file?name=[name].[ext]!customstyles.css' from '../styles/customstyles.css';`
  ```
3. Reference that CSS file in your HTML:

  ```HTML
  <link href='mypath/customstyles.css' />
  ```

Hope that helps & works!

**Comment by bryandbor** [comment]
I receive the following error when I try to use bootstrap (or fontawesome):

Module parse failed: (_project directory_)/fonts/glyphicons-halflings-regular.eot Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.

It seems as though the compiler is complaining about trying to compile the .eot file. I receive the same issue for .woff, .woff2, .ttf, and .svg files used by bootstraps glyphicons. The same is true when I try incorporate fontawesome. Please advise. :)

**Comment by robbyfine** [comment]
Hi there. Very useful guide! By the way, guys, where do you get yout bootstrap templates from? I'm considering downloading one from [Templatemonster](http://www.templatemonster.com/bootstrap-website-templates/)  website. My friend recommends me to use this template provider.

**Comment by holoiii** [comment]
The solution that worked for me is creating a folder structure like this in the root of the project:

```
vendor/
  css/
    bootstrap.min.css
  fonts/
    (all the font files)
```

And inside the entry point of webpack (currently /app/app.js), add the following:
```javascript
import '!!style-loader!css-loader!../vendor/css/bootstrap.min.css';
```

What this does is strip out the configured loaders for this specific css file, and then use only the style-loader and css-loader. This is necessary because the configured css-loader had modules turned on, which caused bootstrap's styles to be namespaced and thus not show up properly.

Hope this helps - took me a while to figure out!

**Comment by tarun2502** [comment]
Still cant figure it out, trying to add vendor css but confused where to put it.

**Comment by mxstbr** [comment]
`app.js`!

**Comment by tarun2502** [comment]
Thanks for your answer but when i am trying to put into app.js i am getting the following error.
`import 'file?name=[name].[ext]!material.min.css' from './vendor/mdl/material.min.css';`

I am getting the following error for using from
react-boilerplate/app/app.js: Unexpected token (16:49)
> 16 | import 'file?name=[name].[ext]!material.min.css' **f**rom './vendor/mdl/material.min.css';

**Comment by mxstbr** [comment]
Leave the `from` part away, this does the trick:

```JS
import 'file?name=[name].[ext]!./vendor/mdl/material.min.css';
```

**Comment by tarun2502** [comment]
worked, Thanks

**Comment by mxstbr** [comment]
No worries, glad to be of help!

**Comment by kopax** [comment]
@holoiii nice trick.
In the past I was using stylus and stylus-bootstrap, this allowed devs to customize bootstrap very quickly  by defining bootstrap parameters to overriden default ones.

By any chance, did you find a way to do that or are you using bootstrap as it is ?

**Comment by viiiprock** [comment]
@kopax  I don't know how to resolve "Resource interpreted as Stylesheet but transferred with MIME type text/html" ?
