### ISSUE TITLE
Not quite sure if the boilerplate behaves as supposed to

### ISSUE THREAD

**Issue by nicolabortignon** [mxstbr/react-boilerplate#244]
First of all, thanks for this boilerplate.

I just downloaded the boilerplate, run npm install and npm run.

Now, if I edit something on the reducer, ie.: the title in the homepage reducer, i don't see any change.
Shouldn't be that triggering the hot reload ?

**Comment by mxstbr** [comment]
Is that on `master` or on the `v3.0.0` branch?

**Comment by nicolabortignon** [comment]
master

**Comment by mxstbr** [comment]
I encourage you to check out the `v3.0.0` branch. It's a complete overhaul, and I'm no longer working/maintaining `master` until v3 is released!
