### ISSUE TITLE
Include original class name and location in component classes in development

### ISSUE THREAD

**Issue by webdesserts** [mxstbr/react-boilerplate#247]
Although it seems the sourcemaps are handled pretty well for the css, it would be nice if you could tell what css was affecting an element at a glance during development. For example the output for the `H1` component currently looks like this:

<img width="377" alt="screen shot 2016-03-27 at 11 29 21 pm" src="https://cloud.githubusercontent.com/assets/916253/14070991/c9218ea0-f473-11e5-8e67-dfc79a416d20.png">

If we updated the css loader `localIdentName` like so:

```diff
   // Load the CSS in a style tag in development
-  cssLoaders: 'style-loader!css-loader?modules&importLoaders=1&sourceMap!postcss-loader',
+  cssLoaders: 'style-loader!css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader',
```

We could get classes that look like this:

<img width="375" alt="screen shot 2016-03-27 at 11 17 35 pm" src="https://cloud.githubusercontent.com/assets/916253/14070891/7971dfa0-f472-11e5-85c6-e6fd81b1dc36.png">

We could then just use a pure hash in prod if we wanted to obfuscate the apps internals.

**Comment by mxstbr** [comment]
That sounds useful, would you mind submitting a PR implementing this?

**Comment by mxstbr** [comment]
Done in #248!
