### ISSUE TITLE
3.0.0: npm run test fails with linting errors

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#249]
I'm getting an error message when running `npm run test` on Windows 10. 
Everything apart from the tests works fine (start, build, serve etc.)...

**Comment by maxmantz** [comment]
Since attaching the log file didn't work here it is in copy & paste:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Maxe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.8.1
3 info using node@v4.4.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle reactjs-boilerplate@2.4.0~pretest: reactjs-boilerplate@2.4.0
6 verbose lifecycle reactjs-boilerplate@2.4.0~pretest: unsafe-perm in lifecycle true
7 verbose lifecycle reactjs-boilerplate@2.4.0~pretest: PATH: C:\Users\Maxe\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Maxe\Projekte\react-boilerplate\node_modules\.bin;C:\Program Files (x86)\nodejs;C:\cmder\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\share\vim\vim74;C:\cmder\vendor\conemu-maximus5;C:\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Maxe\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Maxe\AppData\Local\atom\bin;C:\Users\Maxe\AppData\Roaming\npm;C:\cmder
8 verbose lifecycle reactjs-boilerplate@2.4.0~pretest: CWD: C:\Users\Maxe\Projekte\react-boilerplate
9 silly lifecycle reactjs-boilerplate@2.4.0~pretest: Args: [ '/d /s /c', 'npm run lint' ]
10 silly lifecycle reactjs-boilerplate@2.4.0~pretest: Returned: code: 1  signal: null
11 info lifecycle reactjs-boilerplate@2.4.0~pretest: Failed to exec pretest script
12 verbose stack Error: reactjs-boilerplate@2.4.0 pretest: `npm run lint`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\Maxe\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\Maxe\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:827:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid reactjs-boilerplate@2.4.0
14 verbose cwd C:\Users\Maxe\Projekte\react-boilerplate
15 error Windows_NT 10.0.10586
16 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Maxe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
17 error node v4.4.0
18 error npm  v3.8.1
19 error code ELIFECYCLE
20 error reactjs-boilerplate@2.4.0 pretest: `npm run lint`
20 error Exit status 1
21 error Failed at the reactjs-boilerplate@2.4.0 pretest script 'npm run lint'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the reactjs-boilerplate package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run lint
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs reactjs-boilerplate
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls reactjs-boilerplate
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by maxmantz** [comment]
Update: It seems like this is caused by linting errors in the *.js files which cause the tests to fail (as they probably should). However the linting errors refer to the `internals/*` part of the app which shouldn't be touched. I've tried defining an `.eslintrc` file but ran into more errors with linting. Is it possible to provide an `.eslintrc` file which specifies the rules in the project in order to prevent this from happening?

**Comment by mxstbr** [comment]
Thanks @maxmantz for reporting this error! I'll check it out ASAP and see what I can do.

**Comment by mxstbr** [comment]
This does not seem to be a general problem, linting works fine for me on OS X. I think this is a problem with your local setup, can you double check that it doesn't work?

**Comment by maxmantz** [comment]
I've just retried it with a newly pulled version of branch v3.0.0. Using a command prompt (run as administrator), I get errors when running `npm run test` after successfully completing `npm run setup`. 
The complete output from the command line is in this text file:
[error.txt](https://github.com/mxstbr/react-boilerplate/files/194412/error.txt)

**Comment by mxstbr** [comment]
Ah, that's much more helpful! That seems to be [this issue](https://github.com/ramda/ramda/issues/468) which was fixed by disabling `validateLineBreaks` in the jscsConfig.

Can you try doing that and seeing if that fixes your issue, and if it does submitting a PR adding that? Thanks so much, sorry for assuming this was a problem with your setup!

**Comment by maxmantz** [comment]
@mxstbr the solution you've suggested worked for me. I've created a PR containing the change to the `.gitattributes` file. I also had to run `git config --global core.autocrlf false` to prevent git from using the default crlf line ending in Windows.
