### ISSUE TITLE
3.0.0: CLI generator for adding routes does not update the file.

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#251]
I'm loving the CLI tools in the 3.0.0 version and they work, except for the `routes` option. I've created a TestPage component with the CLI and was trying to hook it up with the routes by using the CLI like this:

? [PLOP] Please choose a generator. route - Add a route
? [ROUTE] Which component should the route show? TestPage
? [ROUTE] Enter the path of the route. /test
[SUCCESS] modify C:\my\path\react-boilerplate\app\routes.js

but the file did not get updated. Using Windows 10 and npm 3.8.1

**Comment by mxstbr** [comment]
Will check it out asap, thanks for reporting this!

**Comment by mxstbr** [comment]
This also works fine for me on OS X. I'm pretty sure both of those issues are due to some local env problems!

**Comment by maxmantz** [comment]
@mxstbr Just as with the linting error, I've retried this using a freshly pulled version of v3.0.0. The routes.js file does not get updated (using Windows 10, NVM 3.8.1, Node 4.4.0)
