### ISSUE TITLE
3.0.0: Questions about the structure of the app

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#253]
After getting to know more about the boilerplate I was wondering about a few things:

##### Where should reducers & actions go which are not connected to any container?
I know this calls for an opinionated answer but it would be interesting to know how you would solve this. Is there maybe a reason why separate actions and reducers are not implemented in the example (except for the global state)?

##### Where would separate reducers be registered?
Independent from where I keep the code for them, the most reasonable location I found to register any separate reducers with the store is the function `createReducer` in `app/reducers.js`. Is that correct?

##### How about generators for these?
The generators are a great. Would you support generators for reducers and actions as well? I would happily try out creating these as PRs.

**Comment by mxstbr** [comment]
There shouldn't be any reducers/actions that aren't associated with any container, if they're global add them to the uppermost `App`! ([more info](http://marmelab.com/blog/2015/12/17/react-directory-structure.html)) 

I'd be interested to hear what sort of actions and reducers that you cannot put anywhere.

**Comment by maxmantz** [comment]
I was wondering about that while I was trying to implement an i18n reducer (together with actions) and it didn't seem to fit the directory structure.
I'm sure all reducers and actions fit in somewhere. Thanks for sharing the blog post. This makes things very clear and understandable. I guess it is fine that anything global goes into `App`. Just as the blogpost said, my opinion was influenced by other boilerplates/configurations which use global reducers and actions.

**Comment by mxstbr** [comment]
I totally understand, glad you found the blog post helpful – that reminds me to write something about the philosophy somewhere in the documentation! :+1:

**Comment by grabbou** [comment]
I am also using appReducer and appSelector to be kind of kitchen sink for small things, like storing user preferences or information about app being online / offline. Works really well!

**Comment by MrOutis** [comment]
What about using [ducks](https://github.com/erikras/ducks-modular-redux)?

**Comment by gihrig** [comment]
I have worked with  [React Redux Universal Hot Example](https://github.com/erikras/react-redux-universal-hot-example) which uses ducks. See [/src/redux/modules](https://github.com/erikras/react-redux-universal-hot-example/tree/master/src/redux/modules).

I found that starter kit/boilerplate to be very difficult to understand (could be just me). In contrast, I find the layout of this boilerplate example to be intuitive and easy to grasp.

I would advocate for maintaining the present layout.

**Comment by MrOutis** [comment]
I've read https://github.com/mxstbr/react-boilerplate/issues/27, and saw why this decision was took.
