### ISSUE TITLE
3.0.0: multiple instances of the same selector

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#262]
I have a `Sidenav` container in my `App` container. Also in my `App` container is a `Layout` container with a `Header` container, which in turn has a `ToggleMenuButton` component which toggles the `isMenuToggled` property of `global` state. I also have a `isMenuToggledSelector` to select this property.

The issue I ran into is that the selector fails when it is used by more than one component at once. In my case both the `Sidenav` component and the `ToggleMenuButton` component need the `isMenuToggledSelector`, which fails if it is referenced more than once. [reselect](https://github.com/reactjs/reselect) suggests using a wrapper method called `makeSelector` which returns the call to `createSelector()`. I was able to fix the issue by wrapping every selector in a make function and calling it in the `createSelector()` function for `mapStateToProps` in each container.

Since this is a subtle error that can quickly happen in an unforseen fashion (the error message really doesn't explain much as to the nature of the problem, the selector simply receives `undefined` as state and throws an error), would it be acceptable to wrap every single selector in a make function like I have done? Could there be any unwanted side effects to my approach? If not, would it be OK to change the generators for selectors and containers to implement the creation and usage of those `make` functions?

**Comment by maxmantz** [comment]
To clarify what i mean I use the `loadingSelector` from the example app. The changes would look like this:
selectors/loadingSelector.js:

    import { createSelector } from 'reselect';
    import globalSelector from 'globalSelector';
    
    // make it a function
    const loadingSelector = () => createSelector(
      globalSelector(), // globalSelector also exports a function
      (globalState) => globalState.get('loading')
    );

    export default loadingSelector;

selectors/test/loadingSelector.test.js:

    import loadingSelector from '../loadingSelector';
    import { fromJS } from 'immutable';
    import expect from 'expect';
   
    // call the make function here
    const selector = loadingSelector();   

    describe('loadingSelector', () => {
      it('should select the loading', () => {
        const loading = false;
        const mockedState = fromJS({
          global: {
            loading,
          },
        });
        expect(selector(mockedState)).toEqual(loading);
      });
    });


and in the `export` of every container:

    export default connect(createSelector(
      loadingSelector(), // call the make function here
      (loading) => ({ loading })
    ), mapDispatchToProps)(Container);

**Comment by mxstbr** [comment]
This is, in fact, the recommended approach by `reselect`! https://github.com/reactjs/reselect#sharing-selectors-across-multiple-components

Very good call on changing the generators and the example app, I'd love a PR for this! :+1:

**Comment by maxmantz** [comment]
I'm almost done with it but the new version of v3.0.0 gives me the following error under Windows when I run `npm start`:
[errorlog.txt](https://github.com/mxstbr/react-boilerplate/files/207346/errorlog.txt)

Do you know what could be causing this?

**Comment by jwinn** [comment]
@maxmantz This is caused because windows cannot set env variables in this manner (windows uses `set ENV_VAR`). I will be fixing this omission, but want to figure out a line-endings issue with jscs on windows. In the interim, feel free to add `cross-env ` in front of the script task, e.g.
```
    "start:tunnel": "cross-env NODE_ENV=development node server",
    "start:prod": "cross-env NODE_ENV=production node server",
```
Please note `npm run build` will, currently fail as well, on the line endings issues with jscs.

**Comment by maxmantz** [comment]
@jwinn thanks for the info. The server works now. All tests are passing. I'm creating a PR.
About the line breaks issue: In my project I've disabled the `validateLineBreaks` check in the jscs config. I could add this to the PR if you wish.

**Comment by jwinn** [comment]
Well my fix for the line endings was to clone from scratch, although I'm sure there is a way to update based upon `.gitattributes` being changed.

I see the same issue when refreshing the page or directly navigating to "/features" route on windows. (It works fine on OSX) (The links work as well) I will investigate further what's going on with react-router (-redux) on windows...

**Comment by jwinn** [comment]
@maxmantz refreshing my cache in chrome and restarting chrome (or opening in incognito) caused the issue to be resolved (it's related to `offline-plugin` use). I guess a good practice, is to develop in incognito mode. ;-)

**Comment by maxmantz** [comment]
@jwinn thanks for the info :) it now orks for me too.
