### ISSUE TITLE
Add ReactCSSTransitionGroup to a component

### ISSUE THREAD

**Issue by DonKanallie** [mxstbr/react-boilerplate#266]
Hi,
I'm just facing some problems for a React CSS Transition. I want to animate an Component on a state change, but i think, because of the Unique generated class names, the -active or -enter classes can't be found. Is there a workaround for that?

**Comment by oliverturner** [comment]
Does the discussion here help at all?

https://github.com/css-modules/css-modules/issues/84

**Comment by DonKanallie** [comment]
Yes! Thank you!
