### ISSUE TITLE
Clean command removes globalSelector

### ISSUE THREAD

**Issue by JCB-K** [mxstbr/react-boilerplate#272]
V3.0.0: The ```npm run clean``` command removes all Selectors, but the globalSelector is referenced in the selector generator. So if you generate a new selector after cleaning, it tries to import the globalSelectors, which does not exist anymore.

Should be an easy fix (just don't delete it in internals/script/clean.js). I can fix it myself later, just opening an issue to keep track of it.

**Comment by mxstbr** [comment]
:+1: good catch, thanks so much! Looking forward to the fix!

**Comment by mxstbr** [comment]
Did we end up fixing this?

**Comment by mxstbr** [comment]
Actually, now that I take a look at this, this fix won't be as easy as originally anticipated because we don't generate a global state when cleaning the example app. Will have to take a look myself, thanks for pointing that out – very good find!

**Comment by mxstbr** [comment]
Fixed in 5cc3ba6, this was simply a not-up-to-date template issue!

(We need to find a better way to keep templates in sync)

**Comment by mxstbr** [comment]
Thanks again for pointing that out!

**Comment by JCB-K** [comment]
Yeah, it got slowed-down a bit because it was more complicated than I thought :). Glad you found an easy fix!

Tangentially related: when removing reselect, the router breaks, because of this:

```
// Sync history and store, as the react-router-redux reducer
// is under the non-default key ("routing"), selectLocationState
// must be provided for resolving how to retrieve the "route" in the state
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: selectLocationSelector,
});
```

Any tips on how to fix this? I know how to hook up normal components directly to the state, but here I'm not entirely sure...

**Comment by mxstbr** [comment]
```
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: (state) => state.get('route'),
});
```

Would you mind submitting a PR adding that to the removing reselect documentation? :+1: Good catch!
