### ISSUE TITLE
[v3.0.0] Cannot navigate between pages

### ISSUE THREAD

**Issue by webdesserts** [mxstbr/react-boilerplate#273]
When pulling the latest of the v3.0.0 navigating between pages does not work unless I manually type out the url. If I click on the "Features" button on the HomePage it won't do anything. If you go to the features page directly and try to click the "Home" button, you can see the the url is temporarily cleared, but restored to `/features` soon after.

**Comment by redduck3** [comment]
I found the same problem. The router didn't take effect.

**Comment by mxstbr** [comment]
Thanks, I'll take a look later!

**Comment by mxstbr** [comment]
Fixed in 7ddab60, this was a regression from #265 where we forgot to call the createLocationSelector function properly in app.js. Should've tested that PR more thoroughly, my bad, sorry about that!
