### ISSUE TITLE
Switch to Babel for code coverage

### ISSUE THREAD

**Issue by bsr203** [mxstbr/react-boilerplate#274]
http://dev.topheman.com/es6-code-coverage-with-babel-plugin/

Looks like isparta not maintained anymore. Above article suggest an alternative.

**Comment by mxstbr** [comment]
isparta isn't maintained, but works perfectly fine.
I'm inclined to leave the current setup as-is, but if you are willing to submit a PR with a better, maintained alternative we'd be happy to merge it!

**Comment by bsr203** [comment]
Hi. I should have more clear. I too think `isparta` is best option as of now, and raised this issue for tracking any progress on this. Cheers.

**Comment by MoOx** [comment]
[nyc](https://github.com/bcoe/nyc) is pretty nice.

**Comment by mxstbr** [comment]
Done

**Comment by MoOx** [comment]
FYI, I you decide to switch to #980, coverage will be handled, no need for an additional tool ;)

**Comment by mxstbr** [comment]
Yes, I know. We switched to Babel a while ago though, just forgot to close the issue!
