### ISSUE TITLE
[v3.0.0] Page does not maintain scroll postion after css changes

### ISSUE THREAD

**Issue by webdesserts** [mxstbr/react-boilerplate#275]
One thing that I noticed while working with the boilerplate's hot reloading is that when editing anything in the css the page always scrolls back to the top. This may seem like a minor annoyance, but when working on the footer of a long website (think mobile site where everything is vertical) this will severely prolong the feedback loop.

**Comment by oliverturner** [comment]
Sounds like a job for https://github.com/taion/scroll-behavior

**Comment by mxstbr** [comment]
Can you try removing the `useScroll` call here and see if that fixes the issue? https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/app/app.js#L66

**Comment by webdesserts** [comment]
@mxstbr I used that on the react-boilerplate-site and it fixed the issue 👍

**Comment by mxstbr** [comment]
Awesome!

**Comment by webdesserts** [comment]
@mxstbr Do you want me to make a PR for this or does that function still serve some use?
