### ISSUE TITLE
Boilerplate Stuck In Chrome Cache

### ISSUE THREAD

**Issue by vinniejames** [mxstbr/react-boilerplate#276]
This boilerplate has been stuck in the browser cache for a month now, I've deleted everything, cleared browser, AppCache, and deleted chrome and nothing works. The boilerplate completely hijacked localhost:3000

How do I delete this?

**Comment by mxstbr** [comment]
```
chrome://appcache-internals
chrome://serviceworker-internals
```

Delete the localhost:3000 entry on both sites. Also see #71, #94, #190. Fixed on v3.0.0 branch.

**Comment by oliverturner** [comment]
@vinniejames This is just how ServiceWorker functions (rather than an issue with this boilerplate). 

For future reference, a simple remedy lies in the Dev Tools: 
![Dev Tools](https://pbs.twimg.com/media/CftI-n3UYAAS3BR.jpg)

**Comment by vinniejames** [comment]
:+1: thank you!

**Comment by enderahmetyurt** [comment]
Great solution thanks!

**Comment by gihrig** [comment]
For reference, the workaround presented above by @oliverturner  is just that, a development workaround. This is not a solution that can be expected to work in production for a public audience.

The actual solution lies in the configuration of [offline-plugin](https://github.com/NekR/offline-plugin/blob/master/docs/updates.md)

**Comment by oliverturner** [comment]
@gihrig That's a great point :)
