### ISSUE TITLE
Fix route generator

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#278]
Since we're code splitting reducers now, if a route is generated for a container component *with a reducer*, we need to add that reducer to the route!

**This can only be done after #254 is merged!**

**Comment by jurekbarth** [comment]
@mxstbr how do you want to solve this bug? Asking by 'do you have a reducer for this component?' or by asking 'is it a component or container' or something else?

**Comment by mxstbr** [comment]
What we need to do is check in the [route generator](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/internals/generators/route/index.js#L12-L18) if the selected component for the route is a container that has a `reducer.js` file, and if it does add the code splitting code added in #254 to the route!

**Comment by mxstbr** [comment]
Done by the great @jurekbarth in #294! :tada:
