### ISSUE TITLE
3.0.0: Tests for selectors failing

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#280]
I have the following state structure:

    const state = fromJS({
        global: fromJS({
             snackbar: fromJS({
               open: false,
               message: 'some message'
             })
        })
    });

I have the following selectors set up:

`globalSelector`:
`export default const () => (state) => state.get('global');`

`snackbarSelector`:

    const snackbarSelector = () => createSelector(
      globalSelector(),
      (globalState) => {
        console.log('globalSelector', globalSelector());
        const state = globalState.get('snackbar');
        console.log('snackbarState', state);
        return state;
      }
    );

    export default snackbarSelector;

and the following test for the snackbar selector:

    import snackbarSelector from '../snackbarSelector';
    import { fromJS } from 'immutable';
    import expect from 'expect';

    const selector = snackbarSelector();

    describe('snackbarSelector', () => {
      it('selects the snackbar state', () => {
        const snackbar = {
          open: false,
          message: 'some message',
        };

        const mockedState = fromJS({
          global: {
            snackbar,
          },
       });

       expect(selector(mockedState)).toEqual(snackbar);
       });
    });

The selectors work as intended when i run the app, however during tests, the following error message appears:

> Chrome 49.0.2623 (Windows 10 0.0.0) LOG: 'globalSelector', function (state) { ... }
> Chrome 49.0.2623 (Windows 10 0.0.0) ERROR
>   Uncaught TypeError: Cannot read property 'get' of undefined
>   at C:/Projekte/react-boilerplate/internals/testing/test-bundler.js:138606 <- 
> webpack:///app/selectors/snackbarSelector.js:9:933

the `console.log()` inside snackbarSelector still works (the first output). However when it tires to access the state parameter via `globalState.get('snackbar')`, the code fails. Do you know what could be causing this? I know that all of your tests for the sample app work fine. Is there maybe something in the test environment setup I'm missing?

**Comment by maxmantz** [comment]
On that note: I've pulled the latest 3.0.0 build and the setup fails with this error (Win10):
[error.txt](https://github.com/mxstbr/react-boilerplate/files/218238/error.txt)

**Comment by mxstbr** [comment]
There's two issues with your tests.

The first one is that I think there is a problem with your state structure.
**`fromJS` deeply converts JavaScript data structures to immutable ones** ([docs](https://facebook.github.io/immutable-js/docs/#/fromJS)), meaning nesting them is likely the problem here.
Change your state structure to just have one at the outermost level and it *should* work

```
const state = fromJS({
    global: {
         snackbar: {
           open: false,
           message: 'some message'
         }
    }
});
```

The second one is that *I think* you return an immutable state from the selector, meaning in your tests you have to do:
`expect(selector(mockedState).toJS()).toEqual(snackbar);`
That should solve the problem!

---- 

As far as the second error goes, as the message says itself this is likely a problem with npm, not with the boilerplate. I think it might be resolved by running `npm uninstall -g nodecoverage` and then `npm install -g nodecoverage`, but that's just a guess. Try it and let me now!

**Comment by maxmantz** [comment]
Sadly both or your suggestions didn't work. It seems like (on Windows) `npm install coverage` causes npm to crash - at least that's the case with me. As for the tests, I've tried every combination of assigning fromJS() / toJS() to any state object within the test, the result is the same. I want to try out my tests on the new version of the boilerplate but the errors with coverage prevent me from doing that. Is there a way to remove the dependency on `coverage`?

**Comment by mxstbr** [comment]
There is no dependency on coverage, that module doesn't exist. You've got a globally installed module called "nodecoverage" that's crashing your npm.

**Comment by maxmantz** [comment]
Sorry, I've missed this tiny detail that the test command is targeting my global eslint installation instead of the local one. Thanks for pointing that out. Is it intentional that the commands target the global dependencies? Or is it a Windows bug?

**Comment by maxmantz** [comment]
I've got the tests to work after installing the following packages using `npm install -g`:
-karma,
-mocha,
-webpack,
-karma-webpack,
-babel-core,
-all babel-* deps,
-all karma-* deps

I've removed the jscs command and stylelint command from the `pretest` script in order to minimize the amount of packages I have to install globally.

This is a workaround for now.

**Comment by maxmantz** [comment]
Final update: after cloning the repo again, this time under c:\ instead of my documents folder, and running in a NodeJS command prompt with admin rights, everything mysteriously started working. I don't know why, but npm on Windows sometimes makes me want to pull my hair out. Thanks for your help :+1:

**Comment by mxstbr** [comment]
Awesome, glad to hear it worked out – sorry for all the struggles!
