### ISSUE TITLE
3.0.0 How to add bootstrap scss

### ISSUE THREAD

**Issue by mariusleu** [mxstbr/react-boilerplate#283]
Hello,

I would like to add into my application bootstrap v4 which is written in scss.

I want for example to include the global things like reboot, grids, fonts but also I want to use it for particular components for example I want to create a component Button and extend the style from bootstrap .btn

Which is the best approach to achieve this ?

How should I include the sass files ?

**Comment by mxstbr** [comment]
Are you on `master` or on the `v3.0.0` branch?

**Comment by mariusleu** [comment]
Sorry I forgot to mention. I am on v3.0.0 branch.

**Comment by oliverturner** [comment]
Hi Marius... This is more of a support request than an issue. Please come on over to the [discussion channel](https://gitter.im/mxstbr/react-boilerplate) where it's easier to chat.
