### ISSUE TITLE
Add scripts-info to package.json

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#288]
Similar to this, let's add a `scripts-info` field to the `package.json` that explains what each script does: https://github.com/ReactiveX/rxjs/blob/a3ec89605a24a6f54e577d21773dad11f22fdb14/package.json#L14-L96

(also needs this package: https://www.npmjs.com/package/npm-scripts-info)

**Comment by rogr** [comment]
Another dependency? 😢

**Comment by mxstbr** [comment]
Hmm, you're right, we have quite extensive documentation of the commands in `docs/general/commands.md`...

**Comment by mxstbr** [comment]
Thought about this, it's probably not worth to have another dependency for this. Thanks @rogr for keeping me real, closing!
