### ISSUE TITLE
Add react/addons to webpack testing externals

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#291]
Otherwise enzyme complains when using any React addon.

[Ref](https://github.com/fubhy/drupal-decoupled-app/blob/master/internals/webpack/webpack.test.js#L59)

**Comment by sotojuan** [comment]
Isn't this already [done](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.test.babel.js#L78)?

**Comment by mxstbr** [comment]
Oh yeah, this is already done. Thanks @sotojuan, not sure how I missed this!
