### ISSUE TITLE
After running `npm start` once, it permanently has port 3000

### ISSUE THREAD

**Issue by elzii** [mxstbr/react-boilerplate#293]
Sorry, probably a noob question. But how can I get port 3000 back? I can't run any other projects since running this.

The npm start command looks to be:

`cross-env NODE_ENV=development node server.dev.js`

`ps aux | grep 3000` and

`lsof -P | grep ':3000' | awk '{print $2}'`

dont return any process ID, so I have no idea how to kill it.

**Comment by mxstbr** [comment]
#276: 

> `chrome://appcache-internals`
> `chrome://serviceworker-internals`
> Delete the localhost:3000 entry on both sites. Also see #71, #94, #190. Fixed on v3.0.0 branch.

**Comment by elzii** [comment]
impeccably fast response, thanks a ton.

**Comment by mxstbr** [comment]
No worries! Definitely check out the `v3.0.0` branch, it's basically done and a lot improved over what's currently on `master`.
