### ISSUE TITLE
NODE_ENV seems to be overriden by webpack in dev mode

### ISSUE THREAD

**Issue by ralomucho** [mxstbr/react-boilerplate#301]
using npm start (so NODE_ENV is set to development), NODE_ENV is always empty when I log it in brower console.

fixed it in webpack.dev.babel.js with 
  
```
new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('development'),
      },
    }),
```

but don't know if it is a good solution.

**Comment by mxstbr** [comment]
Is that on `master` or on `v3.0.0`?

**Comment by ralomucho** [comment]
sorry, v3.0.0

**Comment by mxstbr** [comment]
That's definitely a bug, would you mind submitting a PR implementing your fix?

**Comment by ralomucho** [comment]
Ok, I'll do it. This will be my first PR ever ! If I make something wrong, tell me.
By the way, thanks for you work, it helped me a lot entering into this new world for me (js/React/Redux.....)

**Comment by mxstbr** [comment]
So glad to hear that, both that it's your first PR ever and that this project has helped you! :tada:
