### ISSUE TITLE
What's DX?

### ISSUE THREAD

**Issue by victorkane** [mxstbr/react-boilerplate#316]
Most of the README explains things already familiar to anyone who has spent a few weeks with React. So what's DX??? Why do you speak about "DX" like everyone knows what it is?

**Comment by mxstbr** [comment]
Developer eXperience, should've probably elaborated a bit more. :blush: Added to the documentation in #314!

**Comment by victorkane** [comment]
I've spent several months getting to know the React ecosystem, even cobbling together my own exploration (by no means a boilerplate) https://github.com/awebfactory/react-pathways and you know we're all _dying_ for a no-nonesense, honest to gosh boilerplate (without even expecting the scaffolding you are providing)... so, thanks for the quick response, will keep tabs on progress here!

**Comment by mxstbr** [comment]
Awesome, great to hear you like it!!

**Comment by steinitz** [comment]
I edited the [Wikipedia DX page](en.wikipedia.org/wiki/DX) to include 'Developer Experience'.

**Comment by KarandikarMihir** [comment]
@steinitz Umm, it 404'd..
