### ISSUE TITLE
Container test file location in example app

### ISSUE THREAD

**Issue by bsr203** [mxstbr/react-boilerplate#317]
`index.test.js` files of `Homepage`, `FeaturePage` are not in test directory, but `App` is. Need to consistent?

**Comment by mxstbr** [comment]
Yeah, that's an oversight—they should be in the `test/` directories too! Would you mind submitting a PR that fixes it? :+1:

**Comment by bsr203** [comment]
:-) ok take a little bit time, as I am just setting up and looking through code.

**Comment by ralomucho** [comment]
Fixed with merge #321
