### ISSUE TITLE
Switch the setup script to readline for Windows compatability

### ISSUE THREAD

**Issue by ericyang89** [mxstbr/react-boilerplate#328]
my system is win 7 X64; node version 6.2.0;
when running "npm run setup"  meet this error:

```
TypeError: process.stdout.clearLine is not a function
```

**Comment by mxstbr** [comment]
I think we might need to use `var readline = require('readline')` to do this in a cross-OS compatible way. Would love a PR fixing this!

**Comment by ericyang89** [comment]
it works well on my win 7 now
