### ISSUE TITLE
Make components stateless

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#33]
Remove all `class`es and make all components pure functions. E.g. turn

```JS
class Example extends Component {
    render() {
        return (
            <h1>Hello {this.props.name}!</h1>
        );
    }
}
```

into

```JS
function Example(props) {
    return (
        <h1>Hello {props.name}</h1>
    );
}
```

Positives
----

+ Performance improvement ([src](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions))
+ Not possible to use `setState()`, which is an anti-pattern anyway so we help to keep devs from using it. Since we're using Redux, everything should flow through a reducer.
+ Might be better unit testable, have to look into it.

Negatives
----

- No component lifecycle methods, which might confuse newcomers, so that's another thing we'd have to explain in the docs.

----

Is the more explanation in the documentation worth it? I think so.

**Comment by hampusohlsson** [comment]
It is hard to completely get rid of the lifecycle methods, as you probably will need them for some components. A better approach might be to make the distinction between [smart and dumb components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0).

**Comment by mxstbr** [comment]
@hampusohlsson that's a great link, thanks! How would you reflect that split in the application structure?

**Comment by yjcxy12** [comment]
Not really sure if this is good idea. As discussed above, getting rid of all the state and lifecycle methods is not easy and sometimes not necessary. (e.g. a Countdown component might need secondsLeft state, but parent components don't need to be aware this state)

Separating "smart" and "dumb" component can be done putting them into different folders - "containers" for "smart" components and "components" for "dumb" components.

**Comment by mxstbr** [comment]
:+1: I really like that approach.

What about pages - they are stateful components, but I feel like they should be in their own folder?

I'm closing this issue in favor of #27, please comment there!
