### ISSUE TITLE
Get rid of static reducers

### ISSUE THREAD

**Issue by ralomucho** [mxstbr/react-boilerplate#331]
In container generator, some plop actions update reducers.js when you add a reducer to the container.
In the same time, if you assign a route to this container, the reducer will be dynamically imported so the former reference in reducers.js  is no more relevant.

I think there must be situations when containers  are used without being linked to a route, and so "static" (don't know if it's the appriopriate word) reducer are still usefull. So we might make the distinction between the two kinds of reducer in container generator (by asking user if the container must be linked to a page). I can do this if you agree.

What do you think?

**Comment by mxstbr** [comment]
Ah, that sounds like a good call actually! Would you mind submitting a PR with that so I can take a closer look?

**Comment by ralomucho** [comment]
ok, I'll do it.

**Comment by ralomucho** [comment]
I don't have time to do it for the moment. I'll do it next week.

**Comment by mxstbr** [comment]
I think there's a case to be made that we do need static reducers, (e.g. for routing, i18n,…) but we should not be adding the newly generated, code-split reducers to the static reducers list!

That's a pretty bad bug we should fix asap, I'd appreciate a PR changing the container generator to no longer do that!

**Comment by mxstbr** [comment]
Done by the great @ralomucho in #509! Thanks!! :tada:
