### ISSUE TITLE
Make CSS Modules optional

### ISSUE THREAD

**Issue by VinSpee** [mxstbr/react-boilerplate#334]
Awesome work on this stable boilerplate.

I think it'd be wise to make CSS modules optional.

This is a bit of a personal quibble, so I totally understand if it isn't in your vision for this project, but CSS modules (IMO) can cause more complexity and problems than help, and they don't solve anything that a good CSS architecture can't.

I'd be happy to PR this if you're interested. If so, how would you envision it working? an option passed to setup?

**Comment by mxstbr** [comment]
We're going to get into customization at the setup step soon, but I don't think it's in the scope at the moment. I'd love to add this, but it'll need a lot more thinking about to make most features optional, please chime in at #140!

*(Removing CSS modules is explained in the docs, see `docs/css/remove.md`)*

**Comment by VinSpee** [comment]
👍 sounds good - thanks! I know how to remove, it'd just be nice to not have to. Looking forward to the discussion!

**Comment by VinSpee** [comment]
#140 seems unrelated, was there another issue or PR that you meant to reference?

**Comment by mxstbr** [comment]
Ah my bad, it's #180! Stylelint isn't quite related :wink:
