### ISSUE TITLE
Enable push notifications

### ISSUE THREAD

**Issue by ashsidhu** [mxstbr/react-boilerplate#338]
We can enable push notifications and provide boilerplate and instructions to get started by integrating this repo [Nickersoft/push.js](https://github.com/Nickersoft/push.js). Would it be a cool thing to do?

**Comment by mxstbr** [comment]
I don't think that's necessarily related to this boilerplate directly, so I'm not sure we really want to include that by default. I'd love adding a documentation page about how to use it with React though!
