### ISSUE TITLE
Setup script gets deleted after execution

### ISSUE THREAD

**Issue by GQAdonis** [mxstbr/react-boilerplate#339]
I am not sure if this is intended, but the setup.js script in "internals" gets deleted after being run.  When I update my local repository the script disappears from my repo, after which "npm run setup" fails on subsequent machines I clone the repository to.

**Comment by mxstbr** [comment]
Yeah, this is intended—you shouldn't setup more than once. It deletes your entire git history, so running it again will delete all your stuff!
