### ISSUE TITLE
can't clone repo?

### ISSUE THREAD

**Issue by bradparks** [mxstbr/react-boilerplate#341]
Hey... I tried cloning the repo as suggested in the README's quickstart:

`git clone git@github.com:mxstbr/react-boilerplate`

and it fails - I think maybe the default way of cloning it should be suggested as:

`git clone https://github.com/mxstbr/react-boilerplate.git`

as that doesnt require a public key?

**Comment by mxstbr** [comment]
Sounds good to me! Would you mind submitting a PR fixing this? (Also to [`react-boilerplate-site`](https://github.com/mxstbr/react-boilerplate-site))
