### ISSUE TITLE
Where's autoprefixer?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#347]
v3 should have autoprefixer but I can't find it... What's wrong?

**Comment by mxstbr** [comment]
`cssnext` includes `autoprefixer`! :+1: (See [here](http://cssnext.io/features/#automatic-vendor-prefixes))

**Comment by FezVrasta** [comment]
Then probably something with cssnext is wrong, because I don't get any prefix... But if I add autoprefixer and use the same settings:

```
    autoprefixer({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    })
```

everything works

**Comment by mxstbr** [comment]
Hmm, that might be a problem with your specific configuration because it works perfectly fine for me…

**Comment by FezVrasta** [comment]
Probably I'm missing something... nevermind, I'll use autoprefixer alone for it.
