### ISSUE TITLE
Migrate from ESLint + JSCS to just ESLint

### ISSUE THREAD

**Issue by sscotth** [mxstbr/react-boilerplate#348]
http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint

**Comment by MisterFantastic** [comment]
Please let us know why you are removing JSCS as it is good linter.

**Comment by mxstbr** [comment]
The JSCS team released 3.0 and announced they were merging the teams with ESLint, see the blogpost posted in the OP.

Agree @sscotth, we should do this sometime. It's imo not super high priority since it works, but I'd merge a PR making this happen!

**Comment by sscotth** [comment]
Agreed on not being high priority, but with JSCS not being maintained any more a path forward is necessary.

> We will continue to support JSCS for three months fixing bugs but will not be implementing any new features.

https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2

**Comment by mxstbr** [comment]
Done by @glennreyes in #417! :fire:
