### ISSUE TITLE
Future Improvements (Discussion)

### ISSUE THREAD

**Issue by azampagl** [mxstbr/react-boilerplate#350]
After evaluating different react boilerplates, I wanted to discuss some items that I've seen in other repositories that might be advantageous to this boilerplate (and to see if they are potentially on the roadmap):

- Fractal Design
 - See: https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure
 - Code Splitting might not be ideal since this project is offline focused
 - Related issues: #319 

- React Optimize
 - See: https://github.com/thejameskyle/babel-react-optimize
 - Optimize the code during production builds

- Babel ES6/ES7 Support by Default
 - Support for async/await will help with cleaner code

- Koa (?)
 - Express is certainly more mature at the moment, but one could argue that a large part of the community is shifting towards Koa
 - Help "future proof" the boilerplate
 - Related issues: #211 

- BrowserSync (?)
 - See: https://github.com/Browsersync/recipes/tree/master/recipes/webpack.react-transform-hmr
 - Potentially overkill if you're looking to keep the boilerplate lean

I'm going to avoid the Universal/Isomorphic discussion since it's already been asked and involves a lot of complexity...

Overall, great boilerplate and thanks for all the work!

**Comment by mxstbr** [comment]
Interesting, thanks for taking the time to submit this issue! I'll address each of these on their own:

- **Fractal Design**: We actually already code split most things!

- **React Optimize**: Sounds great, would love a PR for that!

- **ES6/ES7 support by default**: Already in there, for `redux-saga` (i.e. ES7 generator) support

- **Koa**: I'm very much not in that space of the JS world, so I have no idea what's going on there. We have a working express implementation now, so I'm kind of hoping we could go along with that.
I think the best thing to do here would be make express.js and the frontend side of things as decoupled as possible, to allow for a Koa implementation to easily be done without much pain. Not sure how feasible that is yet, though.

- **BrowserSync**: Sounds useful, but should probably be optional/a guide in the doc.

I'll close this massive issue and open a new one for react optimize. Thanks again for taking the time to submit this!!

**Comment by malixsys** [comment]
@mxstbr Could `/app/containers/HomePage/sagas.js` use the newer `async`/`await` instead?
