### ISSUE TITLE
Proposal: Use classnames?

### ISSUE THREAD

**Issue by davidwparker** [mxstbr/react-boilerplate#353]
As class name manipulation is removed from React (https://facebook.github.io/react/docs/class-name-manipulation.html)
I propose that this project uses the "official" replacement Jed Watson's "classnames": https://github.com/JedWatson/classnames as a default.

Thoughts?

**Comment by OxyzebaCristelle** [comment]
Je ne parle pas anglais

**Comment by mxstbr** [comment]
@davidwparker I've tried `classnames` a bunch of times, but personally didn't really see the value in it. (sorry @JedWatson)

What does it give you (in combination with CSS modules) that makes your life easier? How does it help?

**Comment by davidwparker** [comment]
I like to compose `className` similar to how the examples show:
```
const menuClassName = classNames(
  styles.menu
  , 'pure-menu'
);
```
Etc.

I mainly just agree with how it's designed (https://github.com/JedWatson/classnames#usage-with-reactjs)... just seems super clean to me.

Does `react-boilerplate` have a plugin system that I could provide generators for including such a thing? Or is that overkill?
(I just added it as a dependency in my package.json and then ran `npm install`, so maybe it's unneeded?)

**Comment by mxstbr** [comment]
The thing with CSS modules is that it gives you the `composes` property:

```CSS
.button {
  padding: 0.5em 1.5em;
  background-color: white;
  color: blue;
}

.buttonPrimary {
  composes: button;
  background-color: blue;
  color: white;
}
```

Then, when you want a primary button you only have to include the `.button--primary` class, which will automatically also apply the `.button` class and override those styles. This means there is no need for any string concatenation whatsoever, only a need to switch out classes based on a prop of the component:

```JS
render() {
  return (
    <button className={(this.props.primary) ? styles.buttonPrimary : styles.button}></button>
  );
}
```

Does `classnames` make this use case cleaner too?

**Comment by JulienMelissas** [comment]
`classnames` def adds value to your above example if you have more than one class on an element. If you had 2-3+ on an element that's when it becomes really helpful, cleaner to look at (separation of concerns because class logic is seperate from your `render()`), and more readable, IMO.

That said, with CSS Modules, you probably don't have that many classes on any given element ¯\_(ツ)_/¯

**Comment by davidwparker** [comment]
There's been a few times when I haven't been able to separate framework components (bootstrap, purecss, etc) with my own, so I've needed to have some of their classes on an element as well as my own at the same time. This is really the only time this comes up for usage for me.

Otherwise, composition is nice when it's just my stuff.

**Comment by mxstbr** [comment]
IMO we should try to keep all non-critical dependencies to a minimum.

While I now see that there is good use cases for `classnames`, I don't think including it by default is necessary. It's always only one `npm install classnames --save` away anyway!

*I'll leave this open for a few more hours, if you really think we have to include it by default then please comment, but otherwise I'll close this soon.*

**Comment by JulienMelissas** [comment]
^ I agree with this now that I've spend like 5+ minutes with the repo. Adding classnames is so easy if you need it.

**Comment by davidwparker** [comment]
I'm good with keeping it out @mxstbr. I'm sure others may find it useful as well, but it _is_ super easy to add it manually.

**Comment by mxstbr** [comment]
Awesome, thanks for kicking off the discussion!

**Comment by ralomucho** [comment]
Maybe you could add this in docs?

**Comment by mxstbr** [comment]
Yeah sure, I'd merge a PR adding a section about installing/using classnames!

**Comment by aeman1** [comment]
ok ive got. it. cool as. care to let me have some fucking.would be awsome.
yeah
