### ISSUE TITLE
npm run generate route small bug

### ISSUE THREAD

**Issue by Bigbrd** [mxstbr/react-boilerplate#362]
in route.hbs it should be:
        System.import('components/{{ properCase component }}')

not: 
        System.import('{{ properCase component }}')

as first time users will have their build fail if they just create a route and point it to a component that is in their components folder.

**Comment by mxstbr** [comment]
Very good catch! Would you mind submitting a PR that fixes this bug?

**Comment by Bigbrd** [comment]
would be glad to

**Comment by Bigbrd** [comment]
#363
