### ISSUE TITLE
Styleguide configuration

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#367]
I have tried to integrate this boilerplate with several styleguides generators without success (react-styleguide-generator, react-styleguide-generator-alt, react-styleguidist)

Any chance to get one of them working with this boilerplate?

Thanks!

**Comment by mxstbr** [comment]
Coming very soon.

_hint: watch ReactEurope_

**Comment by FezVrasta** [comment]
Since I'm starting a big project with this boilerplate, can you give us any hint on how to structure the code to make sure everything will work fine with it?

(need to include the `styleguide` static property, or jsdoc like comments, etc)

Thanks

**Comment by mxstbr** [comment]
I think the main thing is that you name all components `index.jsx` (notice the `.jsx`), which makes you able to reference _just_ the components by doing:

```JS
components: './app/**/*.jsx',
```

That should fix most issues, then it's just a matter of copy-and-pasting the webpack config. (this example was using the `react-styleguidist` configuration option)

Let me know how you get along though!

----

_I honestly haven't looked at that too much, I'll reopen the issue and see if anybody has done this sort of thing before!_

**Comment by harijoe** [comment]
This thread has not been active for 3 weeks now but I think the discussion should go on. Code style is very important for consistency within a developer team. 

Why not integrate something as [the proposition for a standard js style](https://github.com/feross/standard) into the project ? It would certainly require some fixing but could be worth it.

**Comment by mxstbr** [comment]
This has nothing to do with code style, it's about styleguides like http://ux.mulesoft.com, https://marvelapp.com/styleguide/,…

While it's not quite a styleguide, we're hard at work making [Carte Blanche](https://github.com/carteb/carte-blanche) compatible with this boilerplate (almost there!), so I'll close this for now.

**Comment by aurbano** [comment]
Also trying to setup a styleguide, any updates on this?

**Comment by avdeev** [comment]
From Carte Blanche README.md

> IMPORTANT: Since Max & Nik are quite busy with other projects this project is not maintained at the moment, but we hope to get back to it early 2017.

Any news?

**Comment by nesbert** [comment]
Attempting to integrate `react-styleguidist` with the latest `dev` branch but getting the following error...

```js
Uncaught TypeError: Cannot read property 'tokTypes' of undefined
    at module.exports (buble.es.js?:sourcemap:716)
    at eval (buble.es.js?:sourcemap:7646)
    at Array.reduce (<anonymous>)
    at Object.eval (buble.es.js?:sourcemap:7646)
    at eval (buble.es.js?:sourcemap:7721)
    at Object../node_modules/buble/dist/buble.es.js (reactBoilerplateDeps.dll.js:96)
    at __webpack_require__ (reactBoilerplateDeps.dll.js:21)
    at eval (buble.es.js from dll-reference reactBoilerplateDeps?0688:1)
    at Object../node_modules/buble/dist/buble.es.js (main.bundle.js:868)
    at __webpack_require__ (main.bundle.js:707)
```
Seems like a webpack/babel error from what I can tell (something with `acron.tokTypes`).

Anyone with luck getting these two projects working together?

**Comment by nesbert** [comment]
Figured out my issue... thought I would share in case someone else has a similar problem. My issue stemmed from how webpack was being configured (the sequence to be exact). The example below shows what I did to force the proper sequence when configuring with react-styleguidist.

```js
// sample styleguide.config.js
module.exports = {
  dangerouslyUpdateWebpackConfig(webpackConfig, env) {
    const reactBoilerplateWebConfigFile =  'webpack.' + (env === 'development' ? 'dev' : 'prod' ) + '.babel';
    const reactBoilerplateWebConfig = './internals/webpack/' + reactBoilerplateWebConfigFile;
    return Object.assign(
      {},
      require(reactBoilerplateWebConfig),
      webpackConfig
    );
  },
  components: './app/@(components|Components)/**/*.{js,jsx}',
};
```

HTH :)
