### ISSUE TITLE
ES6 code not compiling in development environment.

### ISSUE THREAD

**Issue by arpan-jain** [mxstbr/react-boilerplate#369]
Whenever i start the app with npm start. i get below mentioned error which is probably because in the development environment server/index.js is not being loaded through babel. 
React Projects/react-boilerplate/server/index.js:25

app.listen(port, (err) => {
                        ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

Thanks in advance

**Comment by mxstbr** [comment]
See #349, this is because you're on Node below v4.

Please upgrade to at least Node v4, if not v5 or v6!

**Comment by mxstbr** [comment]
Also, you're absolutely right with

> server/index.js is not being loaded through babel.

The server indeed isn't loaded through Babel! :+1:

**Comment by arpan-jain** [comment]
Thanks. Missed that point completely. Now its working fine.
