### ISSUE TITLE
Background image not displayed in CSS Modules

### ISSUE THREAD

**Issue by harijoe** [mxstbr/react-boilerplate#370]
I was experimenting with the CSS modules provided by this boilerplate (great work by the way), but I could not make background image work properly:
- When the whole app is reloaded, styles  such as `background: url('my-background.jpg');` will be ignored
- If you edit it though, without reloading the whole page, HMR will inject the new style and it will be interpreted correctly

I haven't found what could cause this strange behavior. I wonder if other CSS directives are affected by this. I'm posting this here because it seems to be linked to this repo config, I have found an example using CSS modules which [was properly working](https://github.com/css-modules/webpack-demo/blob/08a74f1b778913aea6da899680c77eb16a5090b9/src/components/0-Logo/Logo.css).

**Comment by harijoe** [comment]
I found out that the problem was caused by the use of `sourceMap` for the `css-loader` in the dev webpack config. As it is described on the webpack/css-loader doc, source maps make relative paths buggy and thus force the use of absolute paths. I don't know if there is an easy way to seamlessly transform every relative path to absolute path in development, but if not, I suggest the removal of source maps as it can be very annoying :)

**Comment by mxstbr** [comment]
Interesting problem! Could you try adding adding an `import 'file?[path].[ext]!my-background.jpg'` to your component and seeing if that fixes it too?

I'd really like to avoid removing source maps, as development without them is horrible!

**Comment by harijoe** [comment]
Unfortunately, it does not seem to do the trick. I guess the background image is imported correctly because when inspected with chrome dev tools, the my-background.jpg url has correctly been replaced by an hash. I will carry on the investigation :)

**Comment by infernalmaster** [comment]
I think this is related to https://github.com/webpack/css-loader/issues/29 and https://github.com/webpack/style-loader/issues/55. As mentioned there "Setting output.publicPath to an absolute URL should fix the issue". So you should add something like this in dev webpack config (url isn't correct, I added it just for example)
```
output = {
  ....
  publicPath: 'http://localhost:3000/dist'
}
```

**Comment by maslianok** [comment]
You can add this to your `webpack.dev.babel.js`:
```javascript
const ip = require('ip');
.....
output: {
  publicPath: `http://${ip.address()}:3000/build`, // <-- overwrite public path
  ...
},
```

**Comment by nkrambo** [comment]
So this is an issue with the style-loader module.

There is an open PR for this that hasn't been merged for 5 months, which fixes this issue.

I think the owner is holding out for a better implementation but people have been using this as a fix, myself included. Worked like a charm.

https://github.com/webpack/style-loader/pull/96

**Comment by mxstbr** [comment]
I'll close this for now since the question seems answered thoroughly and this is nothing we can fix from our side, thanks everybody!

**Comment by SimonSelg** [comment]
@mxstbr: 

It's fixable from our side! See here: https://github.com/webpack/style-loader/pull/96#issuecomment-228370602

I can create a PR that'd help.

**Comment by mxstbr** [comment]
> This solution requires you to have no output.publicPath specified in config or command line.

Not sure I'm a fan of that, since we do (and should) use it and that is necessary from time to time. Though I would really appreciate you submitting a PR adding that to the FAQ! :pray:

**Comment by SimonSelg** [comment]
Will do that later. Have to try it first in one of my projects if it scales well.

Personally, I'm using [this fork](https://github.com/bendytree/style-loader) of style-loader in my projects, which replaces the urls clientside at runtime to fix this issue ([explanation].(https://github.com/webpack/style-loader/pull/96#issuecomment-220695189)]. But the maintainer of style-loader doesn't want to merge it, because it doesn't work on AST basis (valid point). Maybe we should add a note about it to. Ofc it'd be better to fix the issue in style-loader itself, I'm working on that.

**Comment by mxstbr** [comment]
> Have to try it first in one of my projects if it scales well.

:+1: :+1: :+1: :+1: :+1: 

> Actually, this is not a problem. See the 2nd part of his comment.

Ah yeah, my bad, that actually sounds reasonable! Let's do it, and also add documentation about the fact that we do that!

**Comment by SimonSelg** [comment]
K, will work on that later this night.

**Comment by paothegit** [comment]
I have same issue on loading background images, they are accessible via url, but not via css.
So what was the final decision on this?
I see it fixes when I remove `sourceMap` for `css-loader`.
Thanks.

**Comment by SimonSelg** [comment]
I haven't really gotten to implement the proposed fix (see above) yet because I'm stuck in the middle of exams and a lot of work, unfortunately. 

For now to fix the problem you could use [this fork](https://github.com/bendytree/style-loader) of style-loader instead (see [here](https://github.com/webpack/style-loader/pull/96) for an explanation.

**Comment by paothegit** [comment]
@SimonSelg 
Thanks for your tip, will try it for sure. Good luck for your exams.

**Comment by outdooricon** [comment]
@mxstbr Would you mind reopening this so that it doesn't get forgotten and since @SimonSelg has a proposed solution?

**Comment by SimonSelg** [comment]
Well it looks like this issue is going to solve itself (the fix is getting merged into style-loader soon™): https://github.com/webpack/style-loader/pull/124#issuecomment-249382607

**Comment by kopax** [comment]
with the current version of react-boilerplate I am not able to use source map, I guess this is the related issue. any update on this ?

**Comment by mrdulin** [comment]
Same issue. If you enabled `css module`, you can not enabled the source map, otherwise, the `background: url(path/xxx.jpg)` will not work. But `base:64 DataUrl` works correctly.

**Comment by alianrock** [comment]
+1, enabled css module and got the "can't resolve 'img/icon.png' ", it's a old old problem/(ㄒoㄒ)/~~
