### ISSUE TITLE
server is permanently running on port :3000 - not able to kill the process

### ISSUE THREAD

**Issue by snyoz** [mxstbr/react-boilerplate#373]
After a successful setup - the boilerplate server is permanently running on localhost:3000 and still after a fresh reboot. How can this happen? How I cancel this?

**Comment by rogr** [comment]
Are you on OSX?

You can try netstat:
`netstat -anp tcp | grep 3000`
For OSX "El Capitan" or if your netstat doesn't support -p, use lsof
`lsof -i tcp:3000`

The kill the process. Are you sure sure is still running? or maybe is the ServiceWorker.

**Comment by snyoz** [comment]
Negative... still running on localhost:3000.
Any Ideas if it is the ServiceWorker? How can I find it out?

**Comment by rogr** [comment]
The server is still running after you killed the process with `kill -9 PID`? (where PID is the ID you get from `netstat -anp tcp | grep 3000`)

You can see the serviceworker here:
chrome://inspect/#service-workers

**Comment by mxstbr** [comment]
Go to `chrome://serviceworker-internals` and `chrome://appcache-internals`, search for `localhost:3000` and kill both of them.

That should fix the issue, see see #71, #94, #190 and #293! Fixed in version three!

**Comment by snyoz** [comment]
Thank you very much! Buzzword: ServiceWorker

**Comment by itamark** [comment]
Finally@ Thanks @mxstbr .
Thanks for fixing it in the new version, btw.

**Comment by peter-mouland** [comment]
I just ran into this problem today and it took me a couple of hours of debugging to work out what was going on...  I was creating an app from scratch on port 3000 and i kept getting a html page returned that was not my own

So i think the bug has cropped up again...

**Comment by mxstbr** [comment]
That should definitely not be happening. Have you visited the app in production mode at that URL previously?

Aside, we should change the port when running the app in production so you don't get a cache problem when switching back to development. (if we're not doing that already)

**Comment by peter-mouland** [comment]
I wasn't creating an app using RBP, it was just a simple new app of my own (for which i also happen to use port 3000).  For some reason I was struggling to get the server going when i realised what all the sw.js files popping up in the console must have been.  

I can't remember which run commands I've used for RBP in the past - I assume prod and dev at some point with the other PR's

**Comment by pooja-malvi259** [comment]
Cannot find localhost:3000 in serviceworker-internals and apache-internals. Any help?

**Comment by KarandikarMihir** [comment]
@pooja-malvi259 Perhaps #645?

**Comment by reaganscofield** [comment]
I have the same problem i can't find localhost in both chrome://serviceworker-internals and chrome://appcache-internals.   I'm running windows 10, can anyone help me please

**Comment by taylorsabell** [comment]
@reaganscofield I had this issue with create-react-app on Windows 10. Try killing the NodeJS processes from Task Manager.

**Comment by dqbui** [comment]
what worked for me was ending the Node.js processes in Task Manager

**Comment by bespired** [comment]
When using Chrome: Clear your browsing data. 
Chrome is rather aggressive in caching non existing servers.

**Comment by laiba421** [comment]
I ran into the same problem today but isn't there a permanent fix?

**Comment by taylorsabell** [comment]
I continue to have this problem using Git Bash on Windows. I'll run `npm run start`, terminate it with Ctrl+C shortly after, try `npm run start` again and get this error message. When I do this with the regular Windows Command Prompt, however, it works fine.

I'm thinking something is wrong with the bash emulator.

**Comment by gretzky** [comment]
I'm in agreement that this is an emulator issue, not an rbp issue. Please ask on StackOverflow if there are further questions on this.

**Comment by paoramati** [comment]
Yep, this problem persists using Git Bash on Windows, but normal command prompt allows you to terminate a session and restart one at will.

**Comment by avijitelu** [comment]
For windows user go to task maneger (ctrl+alt+del) then click on more details then on process tab you see many things are running, scroll down for a while until you can find "node.js server side javascript..." select and click on end task.

**Comment by sznowicki** [comment]
Since this issue is high in google results page, I'd post it here.

If you happen to have this issue on macos High Sierra, the solution is adding below to your /etc/hosts. Something changed in the networking setup of macos and some apps (including ping) cannot resolve localhost.

Same happens to the 'detect-port-alt'. Editing /etc/hosts seems like a fix:

`/etc/hosts/`
`127.0.0.1 localhost`
