### ISSUE TITLE
Add possibility to provide meta information for a page, like title, description etc.

### ISSUE THREAD

**Issue by smashercosmo** [mxstbr/react-boilerplate#376]
This feature is very important for the SEO. Currently the most popular way to do that is using react-helmet component. Would you be interested in PR?

**Comment by mxstbr** [comment]
Yes absolutely, that sounds very reasonable!

**Comment by smashercosmo** [comment]
Don't you think, that we gonna need separate generators for containers and pages? Because only page containers need that kind of meta data.

**Comment by mxstbr** [comment]
No, I think if you want meta information you're going to add it yourself, probably…

**Comment by smashercosmo** [comment]
I don't quite understand, will we at least offer an option like "Does it have meta data" during component's scaffolding? If not, then where do you want me to add this?

**Comment by testerdvest** [comment]
He

**Comment by smashercosmo** [comment]
@mxstbr ping

**Comment by mxstbr** [comment]
> "Does it have meta data" during component's scaffolding?

That actually sounds very reasonable, now that I've thought about it a bit more! What about something like "Is this component _(or container)_ a separate page?"?

**Comment by smashercosmo** [comment]
Ok, let's go with this. I'll submit a PR.

**Comment by glennreyes** [comment]
What about linking/scaffolding react-helmet to a route generator?

**Comment by smashercosmo** [comment]
Well, that's a good idea for further improvement. Because naturally if you create a new page, you want to create a related route along with a container.

**Comment by mxstbr** [comment]
Yeah :+1: @glennreyes, that sounds reasonable!

**Comment by sascha1337** [comment]
hot-reloader-example boilerplate uses helmet and works fine, maybe take a look how they implemented it and add this feature, SEO is very important

**Comment by datapimp** [comment]
I've almost finished implementing server rendering using react-helmet, in a project which was based on this boilerplate.  I'm happy with how it turned out and it was an easy addition with the structure of routes / containers 

@smashercosmo let me know how you're coming along if you would like some gists or something.

**Comment by suhaotian** [comment]
**react-helmet** just for Serve-Side-Render, but currently **react-boilterplate** don't support ssr

**Comment by smashercosmo** [comment]
@datapimp I'm going to work on this in the next two days

**Comment by datapimp** [comment]
@suhaotian correct -- and implementing ssr involved refactoring in a number of places throughout the boilerplate, and unfortunately most of these were part of the documentation, examples, and generators so it is would be a bigger effort than just putting in react-helmet

Helmet does a number of use cases outside of a server environment, and could be used along side the html webpack plugin with some small changes. This library would provide an easy way for the container components to control elements of the head tag and such, which is worth introducing without thinking about SSR.  The helmet library would be something the container components can opt into if they want to change a class on the body tag, update document title, change meta, etc.

**Comment by suhaotian** [comment]
@datapimp Maybe like https://github.com/gaearon/[react-document-title](https://github.com/gaearon/react-document-title) 😄 ?

**Comment by maticrivo** [comment]
there also [react-helmet](https://github.com/nfl/react-helmet)

**Comment by jmcclell** [comment]
@datapimp Do you happen to have the code required to add SSR available, even if it's too big for a PR? I'm heading down that rabbit hole now and seeing a lot needs to be changed, but I'm not an expert on these tools yet so seeing a more experienced implementation would be really great.

**Comment by joshhornby** [comment]
@datapimp I'd also like to see the SSR code as well :)

**Comment by datapimp** [comment]
I'm working on a PR for it and should be done by Friday - if not I'll send a gist

**Comment by tzarger** [comment]
@datapimp was the PR for this Friday supposed to be 6/17/2016 or 6/24/2016, sorry I was not sure based on the comment/date.

**Comment by datapimp** [comment]
@tzarger @joshhornby @jmcclell apologies for the delays! I wasn't able to get to this before I went on vacation.  See https://github.com/mxstbr/react-boilerplate/pull/625 for the basic approach.  I can answer any questions you have.  I still have some work to do to improve upon that but hopefully it helps in the meantime

JS

**Comment by jmcclell** [comment]
@datapimp No worries! Thanks so much for taking the time.

**Comment by ankitduseja** [comment]
@datapimp It seems like #625 (SSR) is going to take a while to get merged in this repo, but as you said: 

> Helmet does have a number of use cases outside of a server environment, and could be used along side the html webpack plugin with some small changes.

Can we just merge helmet first if that doesn't require big changes or if you could just share some info on that process?

**Comment by gihrig** [comment]
I have worked with Helmet and found it to very helpful for page specific metadata like title and description. [Examples](https://github.com/erikras/react-redux-universal-hot-example/search?utf8=%E2%9C%93&q=helmet)

**Comment by ankitduseja** [comment]
I just added a PR #691 for react-helmet. This should bring partial SEO support for search engines that index javascript content and will allow to update title, meta tags.

@mxstbr @datapimp @gihrig

**Comment by mxstbr** [comment]
Done by the amazing @ankitduseja in #691!
