### ISSUE TITLE
i18n support: react-intl

### ISSUE THREAD

**Issue by SilentCicero** [mxstbr/react-boilerplate#377]
Internationalization is a huge part of Apps that scale. Without efficient i18n support an app has to hard code all language into separate builds by hand. What is everyone's thoughts on integrating i18n support?

Perhaps:
https://github.com/yahoo/react-intl
https://github.com/ratson/react-intl-redux

This package looks to be the most reasonable with a provider design. This module also provides pluralization support which is necessary for most apps.

I can provide a PR if we feel we should move forward with this.

Language files could be implemented with the same approach we take to constants:

For example, FeaturePage Scaffolding Text:

`boilerplate.containers.FeaturePage.scaffolding.header` = "Quick scaffolding"
`boilerplate.containers.FeaturePage.scaffolding.message` = "Automate the creation of components, containers, routes, selectors and sagas - and their tests - right from the CLI!"

That looks like this:
```
          <li className={styles.listItem}>
            <p className={styles.listItemTitle}>
              <FormattedMessage
                id="boilerplate.containers.FeaturePage.scaffolding.header"
                defaultMessage={`
                  Quick scaffolding
                `}
              />
            </p>
            <p>
              <FormattedMessage
                id="boilerplate.containers.FeaturePage.scaffolding.message"
                defaultMessage={`
                  Automate the creation of components, containers, routes, selectors
                  and sagas - and their tests - right from the CLI!
                `}
              />
            </p>
          </li>
```

The Intl Provider looks something like this in the app/app.js:

```
ReactDOM.render(
  <Provider store={store}>
    <IntlProvider locale="en">
      <Router
        history={history}
        routes={rootRoute}
        render={
          // Scroll to top when going to a new page, imitating default browser
          // behaviour
          applyRouterMiddleware(
            useScroll(
              (prevProps, props) => {
                if (!prevProps || !props) {
                  return true;
                }

               .....
```

**Comment by benjaminlgt-littlelives** [comment]
I support the inclusion of react-intl and can help in any PR efforts.

To add on, I feel we should automatically generate the language files using
https://github.com/yahoo/babel-plugin-react-intl

**Comment by mxstbr** [comment]
Both of those tools look really good, and I'd very much be up for further evaluating them!

Would you mind collaborating on a RFC PR? (Maybe converting the [`react-boilerplate-site`](https://github.com/mxstbr/react-boilerplate-site) to have i18n as a practical example? I can add a german translation if wanted.)

**Comment by SilentCicero** [comment]
@benjaminlgt-littlelives do you want to handle the language files?

@mxstbr I think we should discuss the approach to the intl provider. Do we want to be able to change languages via the redux state or just manually set it at application start?

I think my first PR will be just setting up the provider, then converting the existing language to FormattedMessages. We can then think about intl redux integration after in a seperate PR perhaps.

@benjaminlgt-littlelives would love your thoughts on integration, I'll see how quick I can do the PR.

**Comment by mxstbr** [comment]
> Do we want to be able to change languages via the redux state or just manually set it at application start?

Not sure, I haven't thought about that topic too much. What are the up– and downsides of each approach?

> I think my first PR will be just setting up the provider, then converting the existing language to FormattedMessages. We can then think about intl redux integration after in a seperate PR perhaps.

:+1:

**Comment by SilentCicero** [comment]
@mxstbr the redux-intl package is not nearly as widely used as `react-intl` which I believe to be far more standardized. 

The downside of integrating the redux-intl is it is less used, less vetted and less battle tested. Upside: a nice module to change languages within the app (so imagine a drop down with multiple langs you can switch on the fly).

I think the right approach is to stage the intl first, then we can think about redux.

I'll use the same naming approach to constants, as I mentioned above.

**Comment by mxstbr** [comment]
> I think the right approach is to stage the intl first, then we can think about redux.

Sounds good to me, thanks for the summary, let's start with `react-intl`!

**Comment by benjaminlgt-littlelives** [comment]
@SilentCicero Sounds good, I'll handle the extracting from your <FormattedMessage /> components into suitable language files. 

It'll be good to use pollyfill.io for Intl since Safari still doesn't have it.

**Comment by benjaminlgt-littlelives** [comment]
@SilentCicero Finished with the extractor. Pumps the files into app/translations/${locale}.json. 
https://gist.github.com/benjaminlgt-littlelives/1c6fdd44dc4608de9268d33394e45447

@mxstbr May I ask where should user defined config go? In the case the list of locales to be supported. i.e: `const locales = ['en', 'zh'];`

**Comment by mxstbr** [comment]
Hmm, good question, I don't really know.

I think it should probably not be in `app.js`, since we try to keep that as don't-touch-this-file as possible. How much config is associated with that, i.e. should it be its own file?

**Comment by benjaminlgt-littlelives** [comment]
Agreed that app.js should be kept as pristine as possible.

I feel we should have a unified JSON  configuration file for purposes such as this. The configuration associated with internationalisation is likely minimal.

I also feel we should have a user-editable bootstrap.js which app.js can call not just for this but other instances where necessary. There are some functions that are needed to be called to initialise react-intl.

**Comment by SilentCicero** [comment]
First pass here: @mxstbr @benjaminlgt-littlelives -- https://github.com/mxstbr/react-boilerplate/pull/391

**Comment by benjaminlgt-littlelives** [comment]
@mxstbr @SilentCicero My contribution -- https://github.com/SilentCicero/react-boilerplate/pull/1

**Comment by chaintan17** [comment]
I need this feature also, let me help!

**Comment by mxstbr** [comment]
Right this way! 👉 https://github.com/mxstbr/react-boilerplate/pull/391#issuecomment-232287102

**Comment by pavel06081991** [comment]
@mxstbr , am I right that now boilerplate loads translations for all languages when page is opened? Are you going to use [async feature](https://github.com/yahoo/react-intl/tree/master/examples/async) to asynchronously load translations for that language which is used on the page?

**Comment by mxstbr** [comment]
> am I right that now boilerplate loads translations for all languages when page is opened

Translations for all languages _of that specific page_, yes.

I guess that might be a downside now that you mention it, any ideas how we could fix that @SilentCicero?

**Comment by chaintan17** [comment]
I afraid that it's not for specific page 😕 ...
it preloaded every js files under `/translations` folder.

**Comment by mxstbr** [comment]
Hmm, that shouldn't happen! Would you mind fixing it?

**Comment by chaintan17** [comment]
@mxstbr but in `i18n.js` files, it's now importing every files under `'./translations/*`
Doesn't it means that webpack will pack all these files without do chunking?
