### ISSUE TITLE
Rewrite of reducer template

### ISSUE THREAD

**Issue by harijoe** [mxstbr/react-boilerplate#381]
This project is truly awesome, but I find the approach of [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/modules/counter.js) about the reducers file quite good, and maybe clearer and more extendable than the one currently used here. It also offers more single responsibility functions (action creators, reducer) that can be each unitary tested. What do you think ? 

If it seems reasonable, I can make a PR for that.

**Comment by mxstbr** [comment]
See [this comment](https://github.com/mxstbr/react-boilerplate/issues/27#issuecomment-168247634) and [this comment](https://github.com/mxstbr/react-boilerplate/issues/27#issuecomment-168932177) for my problems with the ducks pattern.

I'm not a big fan of it, basically, but I'd love to add documentation about it to the JS docs! Would you mind submitting a PR with a doc explaining how to use that pattern? :+1:
