### ISSUE TITLE
gaps intergrating with other modules

### ISSUE THREAD

**Issue by katcu** [mxstbr/react-boilerplate#383]
Hi guys, thanks for the awesome job! I just start using it in my project with other modules. unfortunately, they were not smoothly integrated during my job. Would you please help looking into it? greatly appreciated!

issues:
[mjrussell/redux-auth-wrapper](https://github.com/mjrussell/redux-auth-wrapper/issues/40)

[erikras/redux-form](https://github.com/erikras/redux-form/issues/1034)

**Comment by mxstbr** [comment]
I've never used either of these modules, I'm afraid, so I can't really help you. 😞 Sorry!

**Comment by mjrussell** [comment]
If anyone is also having trouble using redux-auth-wrappers with this boilerplate, see this [comment](https://github.com/mjrussell/redux-auth-wrapper/issues/40#issuecomment-221643579)
