### ISSUE TITLE
github request for each time you navigate to the home page

### ISSUE THREAD

**Issue by phoenecke** [mxstbr/react-boilerplate#384]
Each time you navigate back to the home page, there is another fetch done for each github search.

1. Run sample app.
2. Open Redux dev tools.
3. Navigate to Features page.
4. Click Back or Home.
5. Search for github user.
6. See two `LOAD_REPOS_SUCCESS` actions, and 2 requests in the network tab.

I assume it is because `runSaga` is called each time you navigate, but I'm pretty new to redux-saga.

**Comment by mxstbr** [comment]
That sounds like a bug! Would appreciate a PR fixing it :+1:

**Comment by kraffslol** [comment]
I'm noticing the same thing in my current project. Every time I return to the route it adds an additional instance of the saga. I've yet to figure out how to fix it but my guess is that injectSaga is the culprit.

**Comment by kraffslol** [comment]
I think I have gotten it to work, although i'm not sure its the best way. Heres how I did it:
```javascript
export function injectAsyncSagas(store) {
  let prevSagas = [];
  return (sagas) => sagas.map((saga) => {
    if (!prevSagas.includes(saga)) {
      store.runSaga(saga);
      prevSagas.push(saga);
    }
  });
}
```

If this is an acceptable solution I will create a PR.

**Comment by hansoksendahl** [comment]
My coworker and I also ran into the issue of sagas being injected multiple times for second level URLs from the react router configuration.  This does not appear to be fixed.  Implementing the injectAsyncSagas refactor mentioned by @kraffslol fixed the bugs we were experiencing.  I suggest that @kraffslol's refactor be merged into the boilerplate.

**Comment by gihrig** [comment]
@kraffslol @hansoksendahl How about submitting a PR?
