### ISSUE TITLE
Cannot setup package

### ISSUE THREAD

**Issue by Kinnza** [mxstbr/react-boilerplate#385]
npm install fails because of webpack version

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
npm ERR! peerinvalid Peer karma-webpack@1.7.0 wants webpack@^1.4.0
npm ERR! peerinvalid Peer offline-plugin@3.2.1 wants webpack@>=1.0.0
npm ERR! peerinvalid Peer webpack-dev-middleware@1.6.1 wants webpack@1 || ^2.1.0-beta
```

**Comment by rogr** [comment]
you need at least [node > 5](https://github.com/mxstbr/react-boilerplate/blob/master/.travis.yml#L5)

**Comment by mxstbr** [comment]
Yeah, this is fixed by an upgrade to `npm@>=3`.

Sadly, this is out of our hands and in the hands of package authors, there's nothing we can do here! Sorry!

**Comment by Kinnza** [comment]
Ok thanks. So upgrading npm to 3 should fix it? i'll try :)

**Comment by mxstbr** [comment]
Yeah, that's hopefully going to fix that! Let us know how it goes!

**Comment by Kinnza** [comment]
Ok now the setup passed. Do i have to have node 5?

**Comment by mxstbr** [comment]
Well, you have to have `npm@>=3`. If you can figure out how to use that with `node@<5`, that's absolutely fine!

**Comment by Kinnza** [comment]
👍
