### ISSUE TITLE
A guide for hybrid page

### ISSUE THREAD

**Issue by 108adams** [mxstbr/react-boilerplate#386]
Your boilerplate is a fantastic piece of software when one wants to build SPA from scratch. Unfortunately I'm in a migration phase, where an existing live jQuery-based page using a lot of jQuey-based specialized libraries (e.g. for charts) is supposed to move to React slowly, component by component, while still in production.

React is not a problem here, but I must admit Webpack magic is overwhelming for a npm/Grunt/Gulp only newcomer. Especially CSS inclusion is hard, I spent over 2 hours (and failed) just trying to get all the bootstrap+libraries+custom css used globally when served from css/ folder (I just tried to adapt your example project expanding it with a jQuery component - 'the other way up' so to say - just to learn the proper way to connect those two worlds).

Proposition: Please provide an example html page in such a hybrid state, with jQuery-dependent component (jQuery UI dialog or something similar) and document the way you would include React in harmony with an existing code. 

Your great boilerplate would then serve not only the starting-fresh projects, but an army of projects already live, who would like to go The React Way in a gradual way.

Adam

**Comment by mxstbr** [comment]
This is not something I've done so far, so I can't really help you with that, I'm afraid. I'd love a guide about that if anybody's ever done it!

Since this issue is now 10 days old I'll close it, but feel free to post below if you have ideas how to explain this in the docs.

**Comment by geco** [comment]
Perhaps this solution can help?
http://reactkungfu.com/2015/10/integrating-jquery-chosen-with-webpack-using-imports-loader/
