### ISSUE TITLE
Update docs for removing reselect

### ISSUE THREAD

**Issue by robbue** [mxstbr/react-boilerplate#387]
Thanks for a great boilerplate! :)

I followed the instructions for removing reselect form the boilerplate, but the store did not keep in sync with the history so it when I tried pushing to an new url it automatically reverted back to the previous page.

From the docs: 
```javascript
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: (state) => state.get('route'),
});
```

But if I convert it back to raw JavaScript object it works:
```javascript
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: (state) => state.get('route').toJS(),
});
```

**Comment by mxstbr** [comment]
Very good catch, would you mind submitting a PR fixing that? Thanks!!

**Comment by robbue** [comment]
[https://github.com/mxstbr/react-boilerplate/pull/388](url)

First time doing a PR so hopefully I got it right :)

**Comment by mxstbr** [comment]
Done in #388, thanks so much @robbue!
