### ISSUE TITLE
How can we do paginations with redux in this boilerplate?

### ISSUE THREAD

**Issue by kidjp85** [mxstbr/react-boilerplate#393]
I tried to implement paginations for user's repositories. Did anyone here try this or have any idea how to do it ?

**Comment by sascha1337** [comment]
+1 this redux thing is hell new for me so any good example would help thinking in redux. old jquery routines X_X

**Comment by tsm91** [comment]
@kidjp85 @sascha1337 https://github.com/reactjs/redux/tree/master/examples/real-world

the real-world example contains pagination

**Comment by mxstbr** [comment]
I've never needed to implement pagination, but following the example @tsm91 posted is a good start!

I'll close this issue since it isn't directly related to the boilerplate, but feel free to continue commenting.
