### ISSUE TITLE
How do I seemlessly use a third party css framework?

### ISSUE THREAD

**Issue by mihir-harbinger** [mxstbr/react-boilerplate#394]
I want to use semantic-ui framework for my project. Is there any way to install semantic-ui painlessly? If not, can you guide me in the right direction? Thanks in advance.

[Semantic UI](http://semantic-ui.com/)

**Comment by mxstbr** [comment]
I've never done this, but this seems to be the best solution: https://github.com/Semantic-Org/Semantic-UI/issues/3533#issuecomment-169156670

**Comment by mihir-harbinger** [comment]
@mxstbr Thanks it worked!

**Comment by nkrambo** [comment]
This is also another great option for integrating semantic UI with react, although it's a work in progress.
https://github.com/hallister/semantic-react

**Comment by levithomason** [comment]
@KarandikarMihir @nkrambo there is now an official [Semantic-UI-React](https://github.com/TechnologyAdvice/stardust) project you might be interested in.  It will be ported to Semantic-Org/Semantic-UI-React soon.  Cheers!

**Comment by KarandikarMihir** [comment]
@levithomason Yes. Great work indeed! Thanks for the update.

**Comment by nkrambo** [comment]
@levithomason Awesome! Thanks for the update.
