### ISSUE TITLE
Error with redux-persist

### ISSUE THREAD

**Issue by suhaotian** [mxstbr/react-boilerplate#396]
add redux-persist to store.js, then it look like:
```js
/**
 * Create the store with asynchronously loaded reducers
 */

import { createStore, applyMiddleware, compose } from 'redux';
import { fromJS } from 'immutable';
import { routerMiddleware } from 'react-router-redux';
import createSagaMiddleware from 'redux-saga';
import createReducer from './reducers';

// persist
import { persistStore, autoRehydrate } from 'redux-persist';
import { localForage } from 'localforage'


const sagaMiddleware = createSagaMiddleware();
const devtools = window.devToolsExtension || (() => noop => noop);

export default function configureStore(initialState = {}, history) {
  // Create the store with two middlewares
  // 1. sagaMiddleware: Makes redux-sagas work
  // 2. routerMiddleware: Syncs the location/URL path to the state
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
  ];

  const enhancers = [
    applyMiddleware(...middlewares),
    devtools(),
  ];


  const store = autoRehydrate()(createStore)(createReducer(), fromJS(initialState), compose(...enhancers));
  persistStore(store, {storage: localForage});

  // Extensions
  store.runSaga = sagaMiddleware.run;
  store.asyncReducers = {}; // Async reducer registry

  // Make reducers hot reloadable, see http://mxs.is/googmo
  /* istanbul ignore next */
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      const nextRootReducer = require('./reducers').default; // eslint-disable-line global-require
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
}

```
run npm start, get error: 
selectors.js:34 Uncaught TypeError: state.get is not a function

**Comment by mxstbr** [comment]
Sorry, I've never worked with `redux-persist` before, so I'm not sure what the problem is! I think you need the `redux-persist-immutable` bindings: npm.im/redux-persist-immutable

**Comment by chaintan17** [comment]
If someone want how to do local storage, i have a work around on it. I will describe below.
I initially think that i will do a new lib, but there is already `redux-persist` out there, just that it still have some bug with their immutable (https://github.com/rt2zz/redux-persist-transform-immutable/issues/13)

My work around is to subscribe the store and keep the it in `localStorage` and load it once the app hit refresh.

for example

```
import transit from 'transit-immutable-js';

export const loadState = () => {
  try {
    const serializedState = localStorage.getItem('state');
    if (serializedState === null) {
      return undefined;
    }
    return transit.fromJSON(serializedState);
  } catch (err) {
    return undefined;
  }
};

export const saveState = (state) => {
  try {
    const globalState = state.get('global');
    const serializedState = transit.toJSON({global: globalState});
    localStorage.setItem('state', serializedState);
  } catch (err) {
    console.log(err);
  }
};
```

I got this technique from https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage

Please feel free to contact me if somebody has a problem with this workaround.

**Comment by ansumanshah** [comment]
@chaintan17 Can you provide a commit for this please?

**Comment by juanda99** [comment]
@chaintng Isn't it ok just using https://github.com/rt2zz/redux-persist-immutable ?

**Comment by rachit1994** [comment]
Hi,
Still unable to work around the issue. Having same problem. is there any code example to see what I am doing wrong?

**Comment by juanda99** [comment]
@rachit1994 https://github.com/juanda99/arasaac-frontend/blob/master/app/store.js (I'm using redux-persist 4)
