### ISSUE TITLE
Error when committing deleted file

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#397]
If I delete a file, and then I try to commit the deletion. The linter throws an error in the pre-commit hook, because it tries to lint the deleted file that doesn't exists anymore.

```Shell
Running eslint on git staged files: **/*.@(js|jsx)
Running jscs on git staged files: **/*.@(js|jsx)
Error: Path internals/scripts/clean.js was not found.
    at .<anonymous> (node_modules/jscs/lib/checker.js:188:19)
    at Array.<anonymous> (node_modules/vow/lib/vow.js:712:39)
    at Immediate.callFns [as _onImmediate] (node_modules/vow/lib/vow.js:23:35)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

**Comment by mxstbr** [comment]
Oooh, that's a very good catch! A quick fix for you would be to remove the "precommit" script from the package.json!

Moved to the lint-staged repo, lets hope @okonet can fix it quickly! https://github.com/okonet/lint-staged/issues/12

**Comment by JustinJKlein** [comment]
I ran  into this issue as well. Very glad FezVrasta  posted this or I would have been looking for quite some time. Is there a more permanent solution for this other than removing the the precommit script? I like the idea of linting before I commit to make sure that I am checking in proper code.

**Comment by FezVrasta** [comment]
The new version of the pre-commit script should have fixed this problem I think

**Comment by okonet** [comment]
It was fixed 4 months ago.
