### ISSUE TITLE
how the favicon get loaded?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#403]
There's not the meta tag in the header, so...

In my local project, it just can't find the favicon.icon and complains about it.

**Comment by mxstbr** [comment]
The `HTMLWebpackPlugin` takes care of that! See the documentation: https://github.com/ampedandwired/html-webpack-plugin#configuration

**Comment by FezVrasta** [comment]
oh right, thanks

**Comment by FezVrasta** [comment]
@mxstbr any way to share the same config between dev and prod? Title and favicon, for instance, will not change between the two.

**Comment by mxstbr** [comment]
You could change the `webpack.base.babel.js` to always include the HTMLWebpackPlugin, and pass in environment specific changes via new variables defined in `webpack.dev.babel.js` and `webpack.prod.babel.js`!

**Comment by FezVrasta** [comment]
Thanks, works perfectly!

I just wonder why in the boilerplate you don't already configure it in this way.

**Comment by mxstbr** [comment]
I thought it was configured like that to be honest, feel free to submit a PR implementing this!

**Comment by ItsMrAkhil** [comment]
@mxstbr I've tried adding the favicon but whenever I started viewing it in browser it is giving a strange error

@mxstbr @FezVrasta Can anyone help me with this.

```
plugins: options.plugins.concat([
    // Change favicon
    new HtmlWebpackPlugin({
      favicon: 'app/assets/favicon.png',
    }),

    new webpack.ProvidePlugin({
      // make fetch available
      fetch: 'exports?self.fetch!whatwg-fetch',
    }),
    new webpack.ContextReplacementPlugin(/\.\/locale$/, 'empty-module', false, /js$/),

    // Always expose NODE_ENV to webpack, in order to use `process.env.NODE_ENV`
    // inside your code for any environment checks; UglifyJS will automatically
    // drop any unreachable code.
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
      },
    }),
    new webpack.NamedModulesPlugin(),
  ]),
```

**`Uncaught ReferenceError: reactBoilerplateDeps is not defined`**

**Comment by khoaanh2212** [comment]
use react-favicon can handle your problem,no need webpack

**Comment by csantiago132** [comment]
@ItsMrAkhil  im loading it using 
```js
// Load the favicon
import '!file-loader?name=[name].[ext]!./assets/favicon/favicon.ico';
```
and works like a charm
