### ISSUE TITLE
Where is webpack.config.js?

### ISSUE THREAD

**Issue by Natanael1234** [mxstbr/react-boilerplate#407]
I need to use react-boilerplater together react-toobox. React-toolbox uses sass and react-boilerplate don't supports sass officially. So I need to change the webpack.config.js file to make it support sass. But I don't found this file in react-boilerplate.

**Comment by mrvicadai** [comment]
check out `react-boilerplate/internals/webpack`

**Comment by Natanael1234** [comment]
In this folder there is 4 files. What file should I use?

**Comment by mrvicadai** [comment]
since your objective is to add sass support, I would recommend modifying the `base` configuration file, since the other three configuration files are all branched on top of it.

**Comment by mxstbr** [comment]
The CSS loaders are adapted per environment, so you'll need to tinker with the `cssLoaders` variable in `webpack.prod.babel.js` and `webpack.dev.babel.js`!
