### ISSUE TITLE
Usage with fullcalendar css

### ISSUE THREAD

**Issue by mrisoli** [mxstbr/react-boilerplate#408]
Hi, I tried using this boilerplate with a standard fullCalendar view, it renders the calendar and fetches events normally but it does not load fullcalendar.min.css that comes within the calendar node module.

How can I import the fullcalendar.min.css to within a calendar component or the global css scope?

**Comment by mxstbr** [comment]
See #394!

**Comment by xxryan1234** [comment]
hi @mrisoli can you possibly share a snippet on how you added fullcalendar to react-boilerplate? I have been having a hard time integrating it to the boilerplate.
