### ISSUE TITLE
Fail when re-install dependencies

### ISSUE THREAD

**Issue by tylerle** [mxstbr/react-boilerplate#412]
Hi guys,

I have a problem when reinstalling dependencies as follows:

npm run setup -- worked
npm run start -- worked
rm -rf node_modules -- worked
npm install -- not work

When I run npm install, I get the following error:

npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
npm ERR! peerinvalid Peer karma-webpack@1.7.0 wants webpack@^1.4.0
npm ERR! peerinvalid Peer offline-plugin@3.2.1 wants webpack@>=1.0.0
npm ERR! peerinvalid Peer webpack-dev-middleware@1.6.1 wants webpack@1 || ^2.1.0-beta

**Comment by rogr** [comment]
You need to upgrade to `npm@>=3`.

**Comment by mxstbr** [comment]
What @rogr said!
