### ISSUE TITLE
npm run build : Missing semicolon after statement

### ISSUE THREAD

**Issue by vimniky** [mxstbr/react-boilerplate#419]
I made some changes on eslint's rules and here's my .eslintrc.json rules:
<img width="329" alt="screen shot 2016-05-30 at 4 31 57 pm" src="https://cloud.githubusercontent.com/assets/11426875/15644209/25949fb4-2684-11e6-83ce-9328c5cf8f43.png">

With this configuration I can run `npm start` without any problems
but when I run `npm run build ` I got the following errors:
<img width="795" alt="screen shot 2016-05-30 at 4 26 19 pm" src="https://cloud.githubusercontent.com/assets/11426875/15644247/6a16cb58-2684-11e6-8792-5d803424186a.png">

**Comment by rogr** [comment]
I think you need to add `"disallowTrailingComma": true` on `jscsConfig` in your `package.json`.

**Comment by mxstbr** [comment]
Since this isn't directly related to `react-boilerplate` but a problem with your local env, I'll close this issue. Feel free to continue the discussion!

**Comment by vimniky** [comment]
I have add the following lines to my jscsConfig : 
```
    "disallowSemicolons": true,
    "requireSemicolons": null ,
```
and it works ! 
Thanks ! @rogr  @mxstbr
