### ISSUE TITLE
"$ npm run build" in windows stays freeze

### ISSUE THREAD

**Issue by ududsha** [mxstbr/react-boilerplate#420]
Hi I successfully installed the dependencies and was able to run the app. But when I run the "$ npm run build" to build the app for deployment cursor blinks and nothing happened. Is that process take lot of time? or any issue with windows environment.

**Comment by mxstbr** [comment]
It does take a bit of time, but there should be output. Do you see absolutely no output in the terminal, and what's your Windows version?

**Comment by ududsha** [comment]
windows 7 professional. Yes no output in the terminal.

**Comment by ududsha** [comment]
Seems the issue is related with the directory creation. I manually created the "build" folder and now it's fixed.

**Comment by maxmantz** [comment]
I've experienced similar issues before on Windows. In order to avoid these problems make sure that

- the command line you use is run as administrator,
- your project files are on C:\ (or the partition windows is installed on).

See if this works :-)

**Comment by joevbruno** [comment]
Good suggestions form @maxmantz. Something else to keep in mind is that on windows, npm can die silently if you run into max-path issues. Thus, you should use npm 3+ to avoid this issue as well.

**Comment by mxstbr** [comment]
Since this seems like an environment-specific problem to @ududsha's machine I'll close this issue for now.

The excellent pointers by @joevbruno and @maxmantz should point you in the right direction to fix this issue, thanks to you two!
