### ISSUE TITLE
HMR unavailable in localhost after normal page reload

### ISSUE THREAD

**Issue by kunal-mandalia** [mxstbr/react-boilerplate#422]
Hi guys,

I installed react-boilerplate, ran `npm run setup && npm start` and went to http://localhost:3000. In chrome devtools I can see HMR is connected. If I normal reload the page (chrome has three options; normal, hard, and empty cache and reload) HMR is no longer available. The error in console is:

GET http://localhost:3000/sw.js net::ERR_INSECURE_RESPONSE

If I hard reload the page, HMR is available. Is this expected behaviour?

Cheers

**Comment by kunal-mandalia** [comment]
I should also add that HMR continues to work following a page reload if accessing the app via the LAN address http://192.168.1.199:3000

**Comment by NekR** [comment]
offline-plugin doesn't support HMR. There is no point to use it with HMR.

I thought `prod` is only for production, so ejy you run it with HMR at all?

**Comment by NekR** [comment]
If you don't use prod version though, then you probably just have registered ServiceWorker for locahost, which has to be cleared manually if you don't serve SW on it now.

**Comment by mxstbr** [comment]
Yeah, what @NekR said makes sense. (thanks for jumping in!)

To clear the ServiceWorker, go to `chrome://serviceworker-internals` and delete the entry for `localhost:3000`, that should solve your issue!
