### ISSUE TITLE
Including Websocket

### ISSUE THREAD

**Issue by nikolas6** [mxstbr/react-boilerplate#426]
First of all thanks for the great boilerplate!

I'm having problem including Websocket. To replicate, include the following line
```
let ws = new window.Websocket('ws://localhost:3003');
```
inside render() of HomePage index.js.

This throws an error `"Websocket is not defined"`. Does anyone know how to include Websocket correctly?

Thank you.

.:Nikolas

**Comment by rogr** [comment]
did you install `ws`?

in the [webpack conf](https://webpack.github.io/docs/webpack-dev-server.html#proxy). you need to set:

```js
proxy: {
  '/data': {
    target: 'http://localhost:port',
    ws: true
  }
}
```

I have this in one project, hope it helps:
```js
  initWebsocket() {
    this.ws = new WebSocket(`ws://${SERVER}/data`)
    this.ws.onopen = () => {
      backend.setWebsocket(this.ws)
    }

    this.ws.onclose = () => {
      this.ws = null

      this.props.dispatch(backend.disconnect())

      if (!this.closing) {
        window.setTimeout(() => {
          this.initWebsocket()
        }, 5000) // reconnect every 5s
      }
    }

    this.ws.onmessage = (event) => {
      const message = JSON.parse(event.data)
      this.props.dispatch(backend.message(message))
    }
  }
```

**Comment by mxstbr** [comment]
I've never worked with Websockets, so I won't really be of any help here—what @rogr said should be enough to get you going though! :+1: 

We're closing all questions and support requests to keep the issue tracker unpolluted and easy to manage for us maintainers. We'd kindly ask you to move this question to [Gitter](https://gitter.im/mxstbr/react-boilerplate) instead!

Thanks! :pray:

**Comment by nikolas6** [comment]
Thanks @rogr. That helps.
Noted on the [Gitter](https://gitter.im/mxstbr/react-boilerplate). Didn't know this exists, cool!

**Comment by rogr** [comment]
@mxstbr We should add the Gitter chat on the Readme

**Comment by mxstbr** [comment]
@rogr :+1: yeah definitely!
