### ISSUE TITLE
Installation fails when using npm v2.14.3 but doesn't report

### ISSUE THREAD

**Issue by idophir** [mxstbr/react-boilerplate#429]
I tried running `npm run setup` which finished very quickly with all green checkmarks but without installing any dependencies. Running `npm run start` failed. When I tried to run `npm install` I saw an error that I need npm v3.

You may want to add a proper message.

**Comment by rogr** [comment]
What do you mean with a proper message?

**Comment by idophir** [comment]
The installation process seems to work fine. It didn't give any error. When I tried to run the boilerplate I got an error that a dependency is missing.
I tried installing a few times before I started digging in. Would have been nice to get an error straight away saying I must upgrade to npm 3.
Nothing major. Just a nice to have for us noobs.


On Tue, May 31, 2016 at 23:02, Rogelio <notifications@github.com> wrote:
What do you mean with a proper message?

**Comment by mxstbr** [comment]
I _think_ @idophir cloned the repo before the warning was added, because we now throw a helpful error if you're using npm < 3 thanks to @rogr, so I believe this is fixed.

Feel free to comment below if I misunderstood something!
