### ISSUE TITLE
Writing the backend middleware api

### ISSUE THREAD

**Issue by kunal-mandalia** [mxstbr/react-boilerplate#430]
Thanks for commenting your codebase throughout :)

I'm writing an api and I saw this comment:

```
// If you need a backend, e.g. an API, add your custom backend-specific middleware here
// app.use('/api', myApi);
```

I'm used to writing my api in the form of api.get('/api/hello', function(req, res))... but writing it as a middleware as you suggest seems cleaner.

My question is about the best (or a good) way of doing this and if the approach I outline below is problematic . I've used a switch statement to first find the method of the request and then a nested switch to find the url of the call like so:

```
var myApi = function (req, res, next) {
  switch (req.method){
		case 'GET':
			switch (req.url) {
				case '/hello':
					res.send('hello get');
					break;
				default:
					res.send('invalid get');
					break;
			}
			break;
		case 'POST':
		  switch (req.url) {
				case '/hello':
					res.send('hello post');
					break;
				default:
					res.send('invalid post');
					break;
			}
			break;
		default:
			res.send('invalid method');
			break;
	}
};
```

I appreciate this is outside the scope of this project itself but some guidance would go a long way.

**Comment by azampagl** [comment]
@kunal-mandalia You might want to check out https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4#route-middleware (starting at the route middleware section).

you could have something like...

**api/index.js**
```
...

var router = express.Router();

// middleware to use for all requests
router.use(function(req, res, next) {
    console.log('Something is happening.');
    next();
});

// GET http://localhost:8080/api
router.get('/', function(req, res) {
    res.json({ message: 'hooray! welcome to our api!' });   
});

//
// import other routes here?
//

...

export default router;
```

**server/index.js**
```
...

import { default as api } from '../api';

...

// more routes for our API will happen here

// REGISTER OUR ROUTES -------------------------------
// all of our routes will be prefixed with /api
app.use('/api', api);

...
```

**Comment by kunal-mandalia** [comment]
Thanks @azampagl. I see the benefit of doing it the way you suggest; it's easier to e.g. version the api '/api/v1/' and clearly see the params expected e.g. '/bears/:bear_id'.

**Comment by chaintan17** [comment]
@kunal-mandalia may i ask some newbie question here?
I tried to add backend in this boilerplate, after follow your instruction. I cannot start the server.
It said that...

```
export default router;
^^^^^^

SyntaxError: Unexpected token export
```

in `/api/index.js` file

Is it because i should add this folder for babel to transpile?
But how can i do that?

**Comment by kunal-mandalia** [comment]
@chaintan17 hey who didn't start off as a newbie? :)

So your api should sit within your `server` folder. Here's how I have it:

`server > middlewares > api.js` you'd write the api here as azampagi suggested
`server > index.js` in this file you 'use' the api by `app.use('/api', api)`

The project's been setup for this to  work without any other configuration; give my suggestion a go and let me know how you get on 👍

**Comment by StanleyFestus** [comment]
@kunal-mandalia  this didn't really help. I still got this 
import api from './middlewares/api';
^^^^^^
my code:
server > middlewares > api.js
const express = require('express');
const router = express.Router();

router.use((req, res, next) => {
  console.log('Yayy');
  next();
});

router.get('/', (req, res) => {
  res.json({ message: 'It works' });
});

export default router;

server > index.js

import api from './middlewares/api';

app.use('/api', api);

**Comment by StanleyFestus** [comment]
@kunal-mandalia 
I got it working..  
const api = require('./middlewares/api'); instead of import
module.exports = router; instead of export default

**Comment by SeunghunSunmoonLee** [comment]
For people still searching, 
all you need is to create something like this in server/index.js

```
app.get('/api/user', (req, res, next) => {
  let parsedBody = JSON.parse(req.body)
  
  res.send({ express: 'Hello From Express.' });
});
```
on client side request to  /api/user
```
    axios.get(`/api/user`)
      .then(function (response) {
        console.log("/api/user response", response);
      })
      .catch(function (error) {
        console.log(error);
      });
```
