### ISSUE TITLE
Add decorators to test task?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#432]
I have installed and made it work the `babel-plugin-transform-decorators-legacy`.

To do so, I added:

```
  babelQuery: {
    plugins: [
      'transform-decorators-legacy',
    ],
  },
```

to my `webpack.base.babel.js` file.
I've also added the same plugin in the `babel.env.production.plugins` section of `package.json`.
Also, I have added the plugin in the `webpack.test.babel.js`

They work fine in dev and production builds, but seems to not get loaded when i run `npm run test`.

Should I include the plugin somewhere else?

More generically, may you provide an example to make it clear how to add an additional babel plugin to the tests configuration?

**Comment by FezVrasta** [comment]
I think I'm near the solution... https://github.com/deepsweet/isparta-loader/issues/18

any help is welcome

**Comment by FezVrasta** [comment]
I ended up using https://github.com/jas-chen/karma-sourcemap-writer to generate coverage reports with istanbul.

It seems to work better and doesn't give me all these problems.

Maybe you could consider using it instead of the current (not supported) isparta

**Comment by mxstbr** [comment]
Yeah that looks solid! See #274, would definitely appreciate a PR!

I'll close this since it seems resolved :grin:

**Comment by kwent** [comment]
@FezVrasta I cannot make it work in `dev` or in `production` even with you instructions...

I'm still having a `Unexpected character '@' `. Any other clues ?
