### ISSUE TITLE
Proplem when running 'npm run clean'

### ISSUE THREAD

**Issue by ankerbachryhl** [mxstbr/react-boilerplate#433]
After I runned npm run setup and everything went fine, I get this error when trying to run npm run clean:

`Cleanup started... ✓Running eslint on git staged files: **/*.@(js|jsx)
Running jscs on git staged files: **/*.@(js|jsx)
Error: Path app/components/A/index.js was not found.
    at null.<anonymous> (/Users/ankerbachryhl/react-boilerplate/node_modules/jscs/lib/checker.js:188:19)
    at Array.<anonymous> (/Users/ankerbachryhl/react-boilerplate/node_modules/vow/lib/vow.js:712:39)
    at Immediate.callFns [as _onImmediate] (/Users/ankerbachryhl/react-boilerplate/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:516:17)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the lint:staged
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 

Error: Git commit failed

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/ankerbachryhl/.nvm/versions/node/v5.9.0/bin/node" "/Users/ankerbachryhl/.nvm/versions/node/v5.9.0/bin/npm" "run" "clean"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 clean: `shjs ./internals/scripts/clean.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 clean script 'shjs ./internals/scripts/clean.js.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     shjs ./internals/scripts/clean.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ankerbachryhl/react-boilerplate/npm-debug.log`

Do you guys have any idea why?

Thank you in advance :)

**Comment by kunal-mandalia** [comment]
I had similar problems. `cloned repo, cd, npm run setup, npm run clean` --> error similar to above. Running build also gave the same problems relating to pre-commit. As a workaround I reinitialised git (removed the .git directory and git init) to create a clean git repo. Running build gave one linting error of files no css files matching condiiton /app/**/*.css, so I created an empty file and build works. Definitely funky.

**Comment by jogoodma** [comment]
It looks like this error was introduced in [80da0c5](https://github.com/mxstbr/react-boilerplate/commit/80da0c517e94b9c78614773b94be10427f4083fc
).  Performing the steps above in the commit prior to this does not produce any errors.

**Comment by kunal-mandalia** [comment]
@jogoodma you're right. To confirm, I used the previous internals/scripts/setup.js (the one prior to #371) script and was able to `npm run setup` and `npm run clean` ok. @FezVrasta 's point still remains; pre-commit must be installed manually afterwards which is an issue. Finally, the user must have at least one css file within the path ./app/**/*.css to satisfy stylelint, else `npm run build` will fail.

@mxstbr could you revert commit 80da0c5 until an alternative is suggested. I'd be happy to submit a PR to the FAQ/gotchas docs to highlight the above steps in the meanwhile but alas I'm a noob here and don't know how. In any case, this one's urgent since newcomers to this project will be put off if they fall at the first hurdle of setting up the project.

Cheers

**Comment by kunal-mandalia** [comment]
P.S. The pre-commit will still spew when commiting to git:

```
Running eslint on git staged files: **/*.@(js|jsx)
/Users/kunalmandalia/Documents/Private Repos/samples/react-bp/react-boilerplate/node_modules/.bin/eslint-staged: line 10: /Users/kunalmandalia/Documents/Private: No such file or directory
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

**Comment by mxstbr** [comment]
I'd love a PR reverting that change for now, and we can discuss how to fix it properly! :fire:

**Comment by kunal-mandalia** [comment]
Cool, @mxstbr I'll go ahead and create the PR. It'll be my first PR so please run your eyes over it :) there's two branches which a PR can currently be sent to: master and v3, which one should I use?

**Comment by mxstbr** [comment]
Thanks @kunal-mandalia, that was perfect!

**Comment by kunal-mandalia** [comment]
Awesome! Note to future contributors: I sent the PR to the master branch, not v3

**Comment by FezVrasta** [comment]
Weird.. I had tested my commit and it was working fine 😔

**Comment by kunal-mandalia** [comment]
Hi @FezVrasta I'd be happy to run local use cases/scripts if you've a PR you want tested locally on another machine, reach out whenever. I see you're pretty prolific when it comes to open source so you've probably got many good PRs to come in the future 😃
