### ISSUE TITLE
Why the webpack loader for tests doesn't load css?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#434]
I was wondering why the webpack.test.babel.js doesn't load the same stuff loaded by the `.dev` version.

I expect to run the tests on the same app my users will use, or at least on the same I use during development.

Why, instead, you don't load all that stuff?

**Comment by mxstbr** [comment]
> webpack.test.babel.js doesn't load the same stuff loaded by the .dev version

What's different? We only add some test specific stuff as far as I can tell.

**Comment by FezVrasta** [comment]
You use `null-loader` for css and images

**Comment by mxstbr** [comment]
> You use null-loader for css and images

Yes, because we don't do any visual regression tests so loading those has an unnecessary performance impact since they don't actually change anything. Now, this is an assumption that wasn't validated afaik (cc @jbinto), so we might need to double check that!

**Comment by xiplias** [comment]
I might also have run into this problem. My case is testing if a component adds the correct CSS class based on a prop like 'selected' is set. 

Is this a problem for you? or is there another way of testing/structuring this?

**Comment by qmmr** [comment]
Hi, I have similar problem as @xiplias. I'd like to use enzyme to find nodes by css className, not the node-name while using css-modules. Is it possible to use the same webpack settings for css-modules as for `dev`?

**Comment by FezVrasta** [comment]
Additionally, I may be wrong, but it breaks everything if you use [react css modules](https://github.com/gajus/react-css-modules).

**Comment by mxstbr** [comment]
This will be irrelevant when we merge #980!
