### ISSUE TITLE
npm start problems

### ISSUE THREAD

**Issue by iboch** [mxstbr/react-boilerplate#435]
When i try npm start, get some issue. I updated node.js, but nothing

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start: `npm run start:tunnel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'npm run start:tunnel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:tunnel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /work/TRASH/react-boilerplate/npm-debug.log

**Comment by azampagl** [comment]
Try cleaning your cache (`npm cache clean`), removing local node modules (`rm -rf ./node_modules`), run the setup (`npm setup`), then `npm start`.

**Comment by mxstbr** [comment]
From the snippet above, one can't really tell what the problem is. I'd also suggest reinstalling, feel free to comment again if you're still having issues!
