### ISSUE TITLE
How to call POST method from within a generator (sagas.js)?

### ISSUE THREAD

**Issue by kunal-mandalia** [mxstbr/react-boilerplate#436]
Hello folks - hopefully an easy one,

I'm following along the default demo app but now trying to make a POST request from within sagas.js (app/containers/HomePage)

How can I pass options e.g. {method: 'POST'} to the following call?:
 `   const repos = yield call(request, requestURL);
`

The comments in utils/request.js suggest initialising request with a url and options but I'm not sure how to do this within a generator function:

```
/**
 * Requests a URL, returning a promise
 *
 * @param  {string} url       The URL we want to request
 * @param  {object} [options] The options we want to pass to "fetch"
 *
 * @return {object}           An object containing either "data" or "err"
 */
export default function request(url, options) {
  return fetch(url, options)
    .then(checkStatus)
    .then(parseJSON)
    .then((data) => ({ data }))
    .catch((err) => ({ err }));
}
```

**Comment by mxstbr** [comment]
You can simply pass in more options arguments and they'll be passed through!

```JS
const postRequest = yield call(request, requestURL, {
  method: 'POST',
});
```

See the redux-saga documentation about the declarative effects: https://github.com/yelouafi/redux-saga/blob/master/docs/basics/DeclarativeEffects.md

**Comment by kunal-mandalia** [comment]
Thanks @mxstbr . To anyone else reading this and still having issues ensure the api is sending the data out in the right format e.g. using res.json as opposed to for example res.send

**Comment by kunal-mandalia** [comment]
P.S. If you can't see the body of the request on the server req.body then ensure:
1. body-parser is installed and used before your api in your server.js file
2. explicitly set header info and stringify body in sagas.js as per the fetch api docs: https://github.com/github/fetch#post-json

**Comment by guangningyu** [comment]
Thanks @kunal-mandalia !
"stringify body in sagas.js" -- this solved my problem. I've been working on this the whole night.

**Comment by bharadwajag** [comment]
Hello Guys,
I'm trying to call an API by sending headers in the request, but as I noticed in the chrome network section ( headers -> Request Headers), AuthenticationToken is missing. 
Here is my code How I'm passing headers
```
export` function* getProducts() {
  // Select username from store
  const requestURL = API_URL + `GetAllProducts?PageNo=1&PageSize=2`;
  const headers = {
    method: 'GET',
    mode: 'no-cors',
    headers: {
      'AuthenticationToken': '19d01592-ec4e-433a-9456-443373675952', // Need to get from store once login done
      'Content-Type': 'application/json'
    },
  };

  try {
    // Call our request helper (see 'utils/request')
    const products = yield call(request, requestURL, headers);
    yield put(productsLoaded(products));
  } catch (err) {
    yield put(productsLoadingError(err));
  }
}

```
![headers](https://cloud.githubusercontent.com/assets/7804894/25117083/fb2730cc-242d-11e7-8d7b-c4ab95fb5972.png)

Could you please tell me what I'm missing, suggest me if there any public repo which is using react boilerplate.

**Comment by kunal-mandalia** [comment]
@bharadwajag try including `credentials: 'include'` in your header i.e:

`const headers = {
    method: 'GET',
    credentials: 'include',
    mode: 'no-cors',
    headers: {
      'AuthenticationToken': '19d01592-ec4e-433a-9456-443373675952', // Need to get from store once login done
      'Content-Type': 'application/json'
    },
  };`

**Comment by bharadwajag** [comment]
@kunal-mandalia 
Thanks for the response, your answer works for me, but we enabled cors at server end too.
