### ISSUE TITLE
something feel weird

### ISSUE THREAD

**Issue by tinybug** [mxstbr/react-boilerplate#442]
Why not put App/reducer.js, App/action.js, App/selector.js into HomePage container? That redux stuff in App  have no directly relationship with the App container. If there are tons of api request in HomePage, shall I add the redux stuff in App container? If so, I feel it will really mess up in App container.

**Comment by SilentCicero** [comment]
I have a point on this as well. I think it should be in the main app container. That seems to be the right global place to keep global app like actions/reducers etc. Here is my thoughts on scaling this properly:

https://github.com/mxstbr/react-boilerplate/issues/444

**Comment by tinybug** [comment]
@SilentCicero I agree with you in #444 ,but I can't figure out why the LOAD_REPOS stuff define in App container, while the real request in saga is defined in HomePage container. Can you tell me why? 😲

**Comment by Kielan** [comment]
@tinybug I agree that in the example for the boilerplate it is strange to have the actions/sagas/constants in the app container but it is a minimal example. In a larger application when storing user data across multiple views you will want the app container scope level.

**Comment by mxstbr** [comment]
> while the real request in saga is defined in HomePage container.

Because you could load repos from different pages. You could dispatch the `LOAD_REPOS` action from a third, profile page, specific to a Github user.

The implementation of the example app is a showcase what the technologies used in the boilerplate look like. Write your application the way you feel it makes sense!
