### ISSUE TITLE
Local webfonts not working for development

### ISSUE THREAD

**Issue by benjaminlgt-littlelives** [mxstbr/react-boilerplate#443]
Defining font-faces in App/styles.css imports fonts into webpack but somehow the fonts cannot load properly in development, they work fine however when you build it.

I suspect it may be a webpackDevMiddleware issue though.

**Comment by benjaminlgt-littlelives** [comment]
http://stackoverflow.com/questions/34133808/webpack-ots-parsing-errosdr-loading-fonts

Seems like it's chrome and not webpackDevMiddleware. Solution is to add an absolute output.publicPath in webpack.dev.babel.js, with protocol. i.e 'http://127.0.0.1:3000/'

**Comment by mxstbr** [comment]
That'd be a great addition to the FAQ, would you mind submitting a PR? Thanks!

**Comment by benjaminlgt-littlelives** [comment]
Will do this weekend!

**Comment by somghosh** [comment]
+1

**Comment by tblazina** [comment]
@benjaminlgt-littlelives sorry but I'm still unable to get static webfonts to load..

i've added a  publicPath: 'http://127.0.0.1:3000/' to the webpack.dev.babel.js, 

and in App/styles.css I've defined the font face using

@font-face {
 font-family: "NovecentoWideRegular";
 src: url("styles/fonts/novecentowide/Novecentowide-Normal-webfont.eot");
 src: local("Novecento Regular"), local("Novecento"), url("styles/fonts/novecentowide/Novecentowide-Normal-webfont.ttf") format("truetype") format("svg");
},

When I do this.. the font does not seem to load, however when I look in networking in chrome dev tools, the style sheet generated shows:


@font-face {
 font-family: "NovecentoWideRegular";
 src: url(http://10.0.1.91:3000/52a23c35fe7bc3f937e54157e2627209.eot);
 src: local("Novecento Regular"), local("Novecento"), url(http://10.0.1.91:3000/967656a39dafee3bdca40b073777a86a.ttf) format("truetype") format("svg");
}


and if I just go to http://10.0.1.91:3000/52a23c35fe7bc3f937e54157e2627209.eot the font file downloads. I'm not sure what i'm doing wrong? any ideas??

**Comment by tblazina** [comment]
Ok, so if I direct it to load the .ttf file it loads ok and everything renders correctly but not with the .eot. Why might this be?

**Comment by fredcarle** [comment]
Has there been an actual solution for this issue. I've been trying to include icomoon font icons for the past 4 hours and I tried every solution I could find on the internet and still can't get the fonts to load. Help would be greatly appreciated. Thanks!

**Comment by elmeister** [comment]
@fredcarle, import './styles.css'; worked for me.
