### ISSUE TITLE
Why "npm run build" can yield so many actions?

### ISSUE THREAD

**Issue by skywalkerlucas** [mxstbr/react-boilerplate#445]
I have a silly question, as I am trying to understand the workflow :

When I type "npm run build" in the terminal and hit enter, it seems a lot of actions happen, including:

1, react-boilerplate@3.0.0 prebuild ..... npm run test && npm run build:clean
2, react-boilerplate@3.0.0 pretest ..... npm run lint

and so on.

But examining "package.json" file, I only find:

```
"scripts": {
...
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p",
...
}
```

How does that happen?

**Comment by ThomasMarnet** [comment]
Hi,

There is a `prebuild` script which is called right before the `build` one.
```
"scripts": {
...
    "prebuild": "npm run test && npm run build:clean",
...
}
```

The `test` script also has a `pretest` script which runs the `lint` one.
```
"scripts": {
...
    "pretest": "npm run lint",
...
}
```

As you might have guessed, these `pre` scripts are launched right before the scripts they are attached to.

Hope it answered your question :)

**Comment by mxstbr** [comment]
Exactly what @ThomasMarnet said, thanks for answering this question Thomas!

**Comment by skywalkerlucas** [comment]
Thanks a lot! : ) @ThomasMarnet  @mxstbr

**Comment by jeremyadavis** [comment]
Had to dig into this myself today. The detailed answer is found in the [npm docs](https://docs.npmjs.com/misc/scripts#description):

> Additionally, arbitrary scripts can be executed by running npm run-script <pkg> <stage>. Pre and post commands with matching names will be run for those as well (e.g. premyscript, myscript, postmyscript).
