### ISSUE TITLE
How to get action payload in a saga?

### ISSUE THREAD

**Issue by jadidian** [mxstbr/react-boilerplate#447]
Hi folks, I was wondering how I can get the action's payload inside the saga body?
```js
import { take, call, put, select } from 'redux-saga/effects';

// all sagas to be loaded
export default [
  defaultSaga
];

// individual exports for testing
export function* defaultSaga() {
  while (true) {
    yield take('SOME_ACTION');
    // how to get action's payload here?
  }
}
```
When I put `console.log(arguments)` in there, I'd get:
```js
[0, Array[1]]
 0: 0
 1: Array[1]
   0: defaultSaga()
   length: 1
.
.
.
```
Thanks

**Comment by jwinn** [comment]
Just assign the returned object from `take`
```
const action = yield take('SOME_ACTION');
```

**Comment by CharlieIGG** [comment]
Hi @jwinn and @jadidian can you please elaborate on this?
I cannot find the action type or payload by calling `const action = yield take('SOME_ACTION');`, rather I seem to get the constructor. Also: does this work with `takeLatest`?

**Comment by eduard-tkv** [comment]
@CharlieIGG Thanks a lot! Have been struggling with it for a couple of hours. You made my day.

**Comment by 92hackers** [comment]
@CharlieIGG  Thanks a lot.

**Comment by SoundBlaster** [comment]
@CharlieIGG great, but you need to fix 'SOME_ACTION' to 'FOO' in your example.

**Comment by cal0610** [comment]
Actually you don't even need to do this:

`const action = yield takeLatest('SOME_ACTION', doSomething);`

Remove `const action = ` completely.

And just do this:

```
function* doSomething(action){
  console.log(action.payload)
}
```

The action parameter takes the argument from 'yield takeLatest...'
