### ISSUE TITLE
heroku causes infinite loop with appcache file

### ISSUE THREAD

**Issue by mlennie** [mxstbr/react-boilerplate#450]
A `appcache/appcach` path is being added in an infinite loop in heroku server logs
Please see issue here: http://stackoverflow.com/questions/37581134/heroku-react-appcache-file-causes-infinite-loop

**Comment by mlennie** [comment]
Ok I found out it only cause the infinite loop with `http` and not with `https`. Weird?

**Comment by mlennie** [comment]
Ok it happens on safari if it's http or https

**Comment by ThomasMarnet** [comment]
Having the same issue on Safari (http or https), everything is fine on others browsers.

**Comment by mxstbr** [comment]
Hmm, I've never had that issue before and I'm running on a 5$ DO Droplet. Any ideas what could be causing this?

**Comment by ThomasMarnet** [comment]
After some digging, I found out that it only occurs when the location's path has at least 2 levels (such as `/post/:id` or `/post/new` for example).

The (weird ?) thing is that it doesn't occurs when I navigate to such a route, but only when I reload the page being already on this route.

I hope you understand what i'm trying to say, if not I'll try to explain it with more specifics.

**Comment by mxstbr** [comment]
Hm, weird. What does you route configuration look like?

**Comment by ThomasMarnet** [comment]
Something like that mostly:

```javascript
{
      path: '/',
      
      getComponent(nextState, cb) {...},

      indexRoute: {
        getComponent(nextState, cb) {...},
      },
      
      childRoutes: [
        {
          path: 'work',
          getComponent(nextState, cb) {...},
        }, {
          path: 'work/:slug',
          getComponent(nextState, cb) {...},
        },
      ],
    }
```

**Comment by ThomasMarnet** [comment]
Something like that mostly:

```javascript
{
	path: '/',
     
	getComponent(nextState, cb) {...},

	indexRoute: {
		getComponent(nextState, cb) {...},
	},
  
	childRoutes: [{
		path: 'work',
		getComponent(nextState, cb) {...},
    }, {
		path: 'work/:slug',
		getComponent(nextState, cb) {...},
	}]
}
```

**Comment by mxstbr** [comment]
I honestly have no idea how to fix this, and I also don't much experience with Heroku, so I won't really be of help here. Has anybody fixed this issue yet?

**Comment by jupitercow** [comment]
I have this same issue on my local when I try to get the boilerplate working in a subdirectory. I changed the `publicPath` in webpack base and that got most stuff working. Except for webfonts and appcache.

In my case, I have the app installed at: `http://example.com/wp-content/themes/build/` as a WordPress theme pulling in content using a Rest API. This works fairly well so far.

My publicPath is: '/wp-content/themes/build/'

When I visit the page: `http://example.com`, it immediately goes haywire with the appcache looping:
```
GET http://example.dev/donate/appcache/manifest.html 404 (Not Found)
GET http://example.dev/donate/appcache/appcache/manifest.html 404 (Not Found)
GET http://example.dev/donate/appcache/appcache/appcache/manifest.html 404 (Not Found)
GET http://example.dev/donate/appcache/appcache/appcache/appcache/manifest.html 404 (Not Found)
GET http://example.dev/donate/appcache/appcache/appcache/appcache/appcache/manifest.html 404 (Not Found)
. . .
```

I moved the appcache folder to the root, and that seemed to fix it, but then just like OP, if I start fresh from a rewritten subdirectory, it goes haywire again. So `http://example.com` is fine, but then `http://example.com/donate` gets batty.

**Comment by jupitercow** [comment]
I haven't gotten to the bottom of this yet, but, in case it helps point someone else in a useful direction. 

We are using this offline plugin library.
https://github.com/NekR/offline-plugin

It is configured in prod webpack config. You can add a publicPath variable in the settings. I know it has to be relative and _cannot_ be absolute, but I am not sure about much else.

**Comment by mlennie** [comment]
I seemed to have fixed it by turning off appcache.

I looked up appcache and MDN say's it shouldn't be used anymore https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

So in offline-plugin config in `internals/webpack/webpack.prod.babel.js ` I added `appcache: false`

``` javascript
    new OfflinePlugin({
      relativePaths: true, // Use generated relative paths by default
      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],
      AppCache: false,

      caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },
    }),
```

**Comment by mxstbr** [comment]
What @mlennie recommends seems to be very sensible, I think we should turn it off by default. AppCache really won't be supported for much longer and should only be used if legacy support is 100% needed, so turning it off by default should be fine.

Would somebody care to submit a PR? Thanks!

**Comment by learntoswim** [comment]
@ThomasMarnet Curious if you've had success using childRoute with the importModules setup in this boilerplate?

**Comment by mxstbr** [comment]
Done by the amazing @sethmcleod in #791! 🎉
