### ISSUE TITLE
`expect` it not the one from Chai

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#451]
I have a simple test:

```javascript
  import { expect as expect2 } from 'chai';
  it('should render an uncontrolled text input', () => {
    const renderedComponent = shallow(
      <Input value='test' />
    );
    console.log(expect, expect2);
    expect(renderedComponent.find('input')).to.have.value('test');
    expect2(renderedComponent.find('input')).to.have.value('test');
  });
```

The first one complains about `to` being `undefined`, the second one works as expected.

The console log says:

```Shell
LOG: function expect(actual){ ... }, function (val,message){ ... }
```

Seems like the global `expect` is not the one of Chai...

in `test-bundler.js` we have:

```javascript
chai.use(chaiEnzyme());

global.chai = chai;
global.sinon = sinon;
global.expect = chai.expect;
global.should = chai.should();
```

So I wonder why it's not the one from chai when the tests are ran...

**Comment by FezVrasta** [comment]
Correction, sorry.

Actually, in the tests, we include `expect from 'expect`... so this overrides the `global.expect`...

So now I wonder why you set those globals in `test-bundler.js` if you then override them?

**Comment by mxstbr** [comment]
Because I like `expect` by mjackson, it's a nice library!

Feel free to simply not import it, and your chai assertions are going to work perfectly fine!

**Comment by FezVrasta** [comment]
May I know then why do you set the `expect` of Chai as global?

**Comment by mxstbr** [comment]
That's just an oversight :grin: happens from time to time, we can remove it!

**Comment by FezVrasta** [comment]
Ah! thanks

**Comment by FezVrasta** [comment]
I wanted to make a PR for this, I just need an information.

Do we use Sinon or Chai at all?
What's the scope of Acorn in this boilerplate?

Thanks!

**Comment by mxstbr** [comment]
> I wanted to make a PR for this

Awesome! :tada:

> Do we use Sinon or Chai at all?

We do use sinon when testing React components, no idea why we have chai in there to be honest… Try removing it and see if everything still works as expected I guess?

> What's the scope of Acorn in this boilerplate?

What is Acorn?

**Comment by FezVrasta** [comment]
We have this rule in webpack:
https://github.com/mxstbr/react-boilerplate/blob/b96b83a20836cf6822e1d73a2983b63e8cfc95fb/internals/webpack/webpack.test.babel.js#L24

**Comment by mxstbr** [comment]
To be honest, I cannot remember. If that's the only thing, I guess we should keep it in there because something's requiring it!
