### ISSUE TITLE
Protecting routes with auth middleware

### ISSUE THREAD

**Issue by kunal-mandalia** [mxstbr/react-boilerplate#453]
Whattup folks,

Suppose I have a route `'/membersOnly'` which I want only members to be able to access. And a second route for non members `'/nonMember'`

For example sake, I also have an auth function:
```
const auth = function() {
 // if user exists in store return true, else return false
}
```
How can I have the auth function run and guide the user to a route based on its value? Other libraries implement this as middleware clientside. Thanks.

**Comment by tsm91** [comment]
Hi,

check out the official react-router [example](https://github.com/reactjs/react-router/tree/master/examples/auth-with-shared-root)

what i did is basically extend the hooks.js like this:

```js
// ...

function redirectToLogin(store) {
  return (nextState, replace) => {
    if (!store.getState().app.currentUser) {
      replace({
        pathname: '/auth',
        state: { nextPathname: nextState.location.pathname }
      });
    }
  };
}

function redirectToDashboard(store) {
  return (nextState, replace) => {
    if (store.getState().app.currentUser) {
      replace('/profile');
    }
  };
}

/**
 * Helper for creating injectors
 */
export default function getHooks(store) {
  return {
    injectReducer: injectAsyncReducer(store),
    injectSagas: injectAsyncSagas(store),
    redirectToLogin: redirectToLogin(store),
    redirectToDashboard: redirectToDashboard(store)
  };
}
```

and in the routes.js:

```js
// ...

export default function createRoutes(store) {
  const { injectReducer, injectSagas, redirectToLogin, redirectToDashboard } = getHooks(store);

// ...

   {
      onEnter: redirectToDashboard,
      path: '/auth',
      name: 'authPage',
      getComponent(nextState, cb) { ... }
    },
    {
      onEnter: redirectToLogin,
      path: '/profile',
      name: 'profilePage',
      getComponent(nextState, cb) { ... }
    },
```

If you wonder what nextPathname good for... well something like this, after login it will redirect to the page you wanted to visit unauthorized
```js
    // ...

    // redirect to nextPathName or to the profile page
    const nextPathName = yield select(selectNextPathname);
    if (nextPathName) {
      yield put(push(nextPathName));
    } else {
      yield put(push('/profile'));
    }
```

**Comment by mxstbr** [comment]
Well, I was starting to write an answer but @tsm91's very throughout explanation covered everything I was going to say! Thanks @tsm91!

**Comment by kunal-mandalia** [comment]
Cheers @tsm91 that's what I was looking for!

One more thing (probably showing my lack of knowledge on redux) I'm getting a console error computing `store.getState().app.currentUser : Uncaught TypeError: Cannot read property 'currentUser' of undefined` - in redux devtools I can see there exists a bool state.global.currentUser - how can I get this value from within hooks.js?

**Comment by tsm91** [comment]
@kunal-mandalia i have no idea

maybe you skip something very trivial, it happends to me a lot, for example `store.app.currentUser`  or `state.global.currentUser`?

but it should be there, if you see the store got populated. (The `@@INIT` action get fired on startup and so redux creates the store with all the default values of reducers.)

**Comment by kunal-mandalia** [comment]
Thanks @tsm91 it's similar, ... I ended up getting the values via

`store.getState().get('global').get('currentUser')`

(basically I had a look at how the selectors were getting the info to begin with) do you think this is okay practice? I don't see any side effects.

**Comment by timothyallan** [comment]
Hey @kunal-mandalia, I'm working on the same thing, and the `store.getState()` calls in `hooks.js` work, but they feel a bit dirty. 

I'd rather use the `selectCurrentUser()` selector from `App/selectors.js` to keep everything in the one spot, but I can't the App selectors imported and working in `hooks.js` page. They just spit out a function and don't evaluate. I'm trying to work backwards now and see how it's all wired up, any suggestions from those in the know would be great.

**Comment by kunal-mandalia** [comment]
Hi @timothyallan, I bet you tried to get the darned function to execute a bunch of ways like I did! No doubt your answer will be somewhere in https://github.com/reactjs/reselect. With an unfamiliar stack, I gotta' pick my battles and this isn't one I want to fight right now! 👊 😄 ...I wonder if the javascript gods will heed your call...

**Comment by kunal-mandalia** [comment]
Also, for those who tried using store.getState().get('global').get('currentUser') but found the value doesn't change with state, wrap it in a function call:

> hooks.js

```
function getUser(){
   return store.getState().get('global').get('currentUser');
}

```
then in redirectToDashboard:
...
```
if (getUser()) {
      replace('/profile');
    }
```
Paul Dirac would instantly reject this for not being beautiful but alas it does work

**Comment by timothyallan** [comment]
@kunal-mandalia Hahah indeed I did! Couldn't get the damned thing to run :) I'll post back if/when I figure it out.

**Comment by timothyallan** [comment]
@kunal-mandalia Got the answer from @mxstbr regarding the Selectors not working. You need to add a double parenthesis at the end, before you pass in the state! 

Then you don't need to query the State directly and can use the Selector in Utils.js

```
 const user = selectCurrentUser()(store.getState());
````

**Comment by kunal-mandalia** [comment]
@tsm91 well done for getting to the bottom of that! 

One question for you, declaring user as you've done requires store to be accessible; did you define user within each function where it was required (or did you manage to only declare user once?), a copy of your code would be great:)

**Comment by tsm91** [comment]
@kunal-mandalia so this is how i done it:

1, you need a signup and a login form, use [redux-form](https://github.com/erikras/redux-form) for that
2, when the form is submitted you dispatch an action with the payload. its a bit tricky to connect redux-form async validation with sagas, [here is a useful comment how to do it](https://github.com/yelouafi/redux-saga/issues/161#issuecomment-191312502)
3, if the saga response is good, you set the user in the store's global part `store.app.currentUser`, and redirect the user as i showed above
4, if the sage returned with error you reject the redux-form validation

now, i think your question what if the user closes the tab or refresh the browser, because the store contents will be empty. As you will see in the below chunk of code the jwt token i being saved to local storage. What you can do is to create a global background process (saga) that will start at `window.onLoad` and check if there is a jwt token in local storage. If yes then it will automatically send a request to the backend api to populate currentUser on the store. In the meanwhile you can of course set `store.app.loading` to true if needed.

So the code isn't finished. But [here are the containers folder](https://github.com/tsm91/react-seed/tree/master/app/containers).

Check out AuthPage, LoginForm, SignupForm i guess.

**Comment by mrboomer** [comment]
For anyone that implemented what @tsm91 did above in your saga (within a try/catch), and need to listen for the selector that gets `nextPathName`, go about it this way within your selector:

> selectors.js

    // ...
    
    const selectRoute = (state) => state.get('route');
    
    // ...
    
    const selectNextPathname = () => createSelector(
      selectRoute,
      (routeState) => {
        try {
          return routeState.get('locationBeforeTransitions').get('state').get('nextPathname');
        } catch (error) {
          return null;
        }
      }
    );

Otherwise it will fail the try in your saga at this point:

`const nextPathName = yield select(selectNextPathname);`

because there will be an error in the selector:

    TypeError: Cannot read property 'get' of undefined

This error only happens when the user doesn't explicitly enter a restricted route.

**Comment by kartik2014** [comment]
Guys, I am kinda late to the party but here's a related example to the issue discussed on this page : 

https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by rahulbasu710** [comment]
Hey guys,
 This is actually a problem that I was coming across while using JWT based authentication with auth0 non-interactive client. 
I have a React Express based universal environment but the jwt authentication is from server to server only (non-interactive clients)
So what I am doing is I am calling a standalone API which returns data only if authenticated. Now I am unable to use the conditional rendering in case of server-side for the states of auth and non-auth

This is my setup with react-router for universal environment

```
app.get('*', (req, res) => {
  if (__DEV__) webpackIsomorphicTools.refresh();
  const history = createHistory();
  const store = configureStore(history);
  const renderHtml = (store, htmlContent) => { // eslint-disable-line no-shadow
    const html = renderToStaticMarkup(<Html store={store} htmlContent={htmlContent} />);
    return `<!doctype html>${html}`;
  };
  // Load data on server-side
  const loadBranchData = () => {
    const promises = [];
    routes.some((route) => {
      const match = matchPath(req.url, route);
      if (match && route.loadData) promises.push(route.loadData(store.dispatch, match.params));
      return match;
    });
    return Promise.all(promises);
  };
  loadBranchData()
    .then(() => {
      // Setup React-Router server-side rendering
      const routerContext = {};
      const htmlContent = renderToString(
        <Provider store={store}>
          <StaticRouter location={req.url} context={routerContext}>
            <App />
          </StaticRouter>
        </Provider>,
      );
      // Check if the render result contains a redirect, if so we need to set the specific status and redirect header and end the response
      if (routerContext.url) {
        res.status(301).setHeader('Location', routerContext.url); res.end(); return;
      }
      // Checking is page is 404
      const status = routerContext.status === '404' ? 404 : 200;
      // Pass the route and initial state into html template
      res.status(status).send(renderHtml(store, htmlContent));
    })
    .catch((err) => {
      res.status(404).send('Not Found :(');
      console.error(`==> 😭  Rendering routes error: ${err}`);
    });
});
```


And this is what standard express does where the api works on routing properly

```
app.get('/', function(req, res){
  res.render('index');
})
app.get('/movies', getAccessToken, function(req, res){
  request
    .get('http://localhost:8080/movies')
    .set('Authorization', 'Bearer ' + req.access_token)
    .end(function(err, data) {
      if(data.status == 403){
        res.send(403, '403 Forbidden');
      } else {
        var movies = data.body;
        res.render('movies', { movies: movies} );
      }
    })
})
```

Any help shall be appreciated greatly!
Thank you so much for your attention
