### ISSUE TITLE
State variables.

### ISSUE THREAD

**Issue by Stalso** [mxstbr/react-boilerplate#454]
Hello. As far as I understand, state is structured in some kind of substates. For example, in sample application there is async  `HomePage` reducer, which adds `home ` variable to state (in addition to `global` and `route`). In this  `home ` object only username is stored. When you are loading repositories,  you should load data and show spinner while loading (setting `state.global.loading` variable to `true`). 

I understand, that `loading` variable should be global for whole application. Because of it, you need to get access in one reducer to both `loading `and `userData.repositories` variables . That is why you handle ` LOAD_REPOS` action on application level (in `App/reducer` not in `HomePage/reducer`). And that is why you have to keep HomePage specific info ( `userData.repositories` variable ) in `state.global`, not in `state.home`. Am I right?

If I am right, let us imagine, that I have some `BlogPage` container (generated by your generator), which adds ` blogPage` section in state. I need to retrieve list of blogs from API and show spinner while I am loading it. For that purpose I need something like this:

    function blogPageReducer(state = initialState, action) {
      switch (action.type) {
        case LOAD_BLOGS:
              return  state.set('loading', true).
                setIn(['blogData'],['blogs'],false);
        case BLOGS_LOADED:
              return state.setIn(['blogData', 'blogs'], action.blogs)
                          .set('loading', false);
        default:
          return state;
      }
    }

 But as I understand, I can not do this, because I do not know, how to get access to `state.global.loading` variable from '`BlogPage/reducer`'. Only  `blogPage` object is passed in reducer function. That is why I also need to handle `LOAD_BLOGS` in `App/reducer` and add my `blogData` object (with list of blogs) in `state.global` object. Is it normal? How can I get access to `state.global.loading` from '`BlogPage/reducer`'?

**Comment by kunal-mandalia** [comment]
I've been fiddling around with this too...was able to get access to state values via the store e.g.

`store.getState().get('global').get('currentUser') // returns false by default, as per app's initial state`

Not sure if this is best practice (I'm sure someone out there can tell us). So in your case if store isn't available, just import it.

**Comment by tylerle** [comment]
@kunal-mandalia we don't have store from BlogPage/reducer? How can I get store object from BlogPage/reducer?

**Comment by mxstbr** [comment]
The missing piece here is that with Redux, you can **react to an action with multiple reducers**.

That means in your `blogPageReducer` you handle the `LOAD_BLOGS` action with `setIn(['blogData'],['blogs'],false);`, and in the `appReducer` you handle the `LOAD_BLOGS` action with `state.set('loading', true)`! The same goes for the `BLOGS_LOADED` action.

Hope that answers the question, let me know if you have any more!

**Comment by Stalso** [comment]
Thank you.  It answers the question.  But you hold your `repositories` array in `global` variable of state?  For simplicity?

**Comment by mxstbr** [comment]
Yes, mostly for simplicity since this is a tiny example app!

**Comment by Stalso** [comment]
Thank you Max.  Your template is cool.  I am. Net and Asp. Net developer,  who decided to learn something new,  and your template is awesome starting point

**Comment by mxstbr** [comment]
Thanks, great to hear! Let me know how you get along!

**Comment by Stalso** [comment]
It is is rather unusual for me.  All this node and especially react stuff is some kind of chaos for me,  after structured and rather static .Net world.  Also I am confused with the leak of normal debug (like we do it in  Visual Studio).  But this is funny.  Maybe someday (I believe in it)  Asp.Net Core will become the best backend and with React will become a future of Web
