### ISSUE TITLE
variables defined outside function

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#455]
Hi, I was wondering if there is a specific reason for declaring these two variables outside of the function right below.

https://github.com/mxstbr/react-boilerplate/blob/master/app/containers/App/selectors.js#L30-L31

Thanks.

**Comment by mxstbr** [comment]
Yeah, they cache the results for the next time we come around and call the locationState selector! That way, we know what the location was last time and can react accordingly!

**Comment by FezVrasta** [comment]
Thanks!
