### ISSUE TITLE
Hot reloading of  reducers

### ISSUE THREAD

**Issue by Stalso** [mxstbr/react-boilerplate#456]
Hi. For some reason reducers hot reloading does not working. Try to change something in home reducer. 

I found similar issue ( [#379](https://github.com/mxstbr/react-boilerplate/issues/379) ) and checked code in `store` . The code is 

    if (module.hot) {
      module.hot.accept('./reducers', () => {
        System.import('./reducers').then((reducerModule) => {
          const createReducers = reducerModule.default;
          const nextReducers = createReducers(store.asyncReducers);
  
          store.replaceReducer(nextReducers);
        });
      });
    }

**Comment by tsm91** [comment]
Yeah its a known issue.

Try to implement [react-hot-loader](https://github.com/gaearon/react-hot-loader) v3, maybe it will fix the problem.

**Comment by mxstbr** [comment]
Closing for now!
