### ISSUE TITLE
Error: Expected Map {} to equal {} on boilerplate test

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#457]
I have generated a container using `npm run generate`, when I run the `reducer.test.js` I get:

```
Error: Expected Map {} to equal {}
```

The test is:

```js
import expect from 'expect';
import settingsReducer from '../reducer';

describe('settingsReducer', () => {
  it('returns the initial state', () => {
    expect(settingsReducer(undefined, {})).toEqual({});
  });
});
```

Seems like we can't just compare maps and objects in this way.
Am I the only one with this problem?

```
~$ node -v
v6.2.0
```

**Comment by mxstbr** [comment]
Ah yeah, it should be `expect(settingsReducer(undefined, {})).toEqual(fromJS({}));`!

**Comment by chaintan17** [comment]
@mxstbr i checked the code and it's already using `fromJS({})`
https://github.com/mxstbr/react-boilerplate/blob/50fe5c66d49bfe80696d94a17e8c704e928f034e/internals/generators/container/reducer.test.js.hbs#L7
