### ISSUE TITLE
Automatically add import PropTypes when 'npm run generate' makes new components

### ISSUE THREAD

**Issue by DenisNeustroev** [mxstbr/react-boilerplate#459]
Smth like this:
`import React, { PropTypes } from 'react';`
Insted of:
`import React from 'react';`

What do you think?

**Comment by mxstbr** [comment]
If we do that, the linter is going to complain about an unused variable We have gotten tons of questions about stateless components not hot-reloading because we only had stateless ones after cleaning, so I'd rather avoid that scenario for now!

Thanks for the suggestion though!
