### ISSUE TITLE
Why do you suggest to put presentational stuff in the App container?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#460]
I'd like to know what's behind this decision.

Shouldn't we have an App component which get rendered by the App container?

**Comment by mxstbr** [comment]
Yes, but it was easier at the time to simply keep it in the App container for our small example!

**Comment by FezVrasta** [comment]
I see, thanks as usual 🙂

**Comment by mxstbr** [comment]
No worries, keep em coming!
