### ISSUE TITLE
npm run setup and then npm run start gives cross-env error

### ISSUE THREAD

**Issue by AustinMCrane** [mxstbr/react-boilerplate#461]
Hello,

i downloaded the source from the current master efb3f40 and ran the suggested setup

`npm run setup` 
installing the dependencies took like 4 seconds so im assuming the issue is that it is not installing all of the node modules
`npm run start`
running this gives the following error:

 react-boilerplate@3.0.0 start /Users/t332j375/Desktop/Museum/react-boilerplate-master
 npm run start:tunnel

 react-boilerplate@3.0.0 start:tunnel /Users/t332j375/Desktop/Museum/react-boilerplate-master
 cross-env NODE_ENV=development node server

sh: cross-env: command not found

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:tunnel"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-boilerplate@3.0.0 start:tunnel: `cross-env NODE_ENV=development node server`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 start:tunnel script 'cross-env NODE_ENV=development node server'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/t332j375/Desktop/Museum/react-boilerplate-master/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start: `npm run start:tunnel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'npm run start:tunnel'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:tunnel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

**Comment by mxstbr** [comment]
Yes, as the error says `"sh: cross-env: command not found"`, you'll need to `npm install --save cross-env`!
