### ISSUE TITLE
Init values in sub state from variable in global state

### ISSUE THREAD

**Issue by tylerle** [mxstbr/react-boilerplate#463]
Let's assume, we have a state.global.authUser.email under global state and I want to show email in UserProfilePage which is generated by generators.

In UserProfilePage/reducer.js, 
```
const initialState = fromJS({
  email: '' **// How can I init it from state.global.authUser.email** 
});
```

UserProfilePage/index.js

```
  render() {
    return (
      <div className="container">
        <input type="text" className="form-control" onChange={this.props.onChangeEmail} value={this.props.email}/>
     </div>
 
```

**Comment by mxstbr** [comment]
You wouldn't do that from the reducer, you'd do that by using the selector you have configured to get that state in the `mapStateToProps` function. Data in the state should only ever live in one reducer. 

I.e. in your `UserProfilePage` component do:

```
export default connect((state) => {
  return {
    userEmail: selectUserEmail(state), 
  };
})(UserProfilePage);
```

(excuse any typos, I'm on mobile)
