### ISSUE TITLE
Blank screen, app not hooking into html

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#468]
Following the [Quick start instructions ](https://github.com/mxstbr/react-boilerplate#quick-start) at 1:49 pm PDT:

1.Clone this repo using $ git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
2. Run $ npm run setup to install dependencies and clean the git repo.
3. At this point you can run $ npm start to see the example app at http://localhost:3000.

Server starts as expected
localhost:3000 opens with a blank page
No errors in terminal or browser console
web page html shows empty app div

`<div id="app"></div>`

`common.js.js` and `main.js` both have substantial content, hundreds and thousands of lines respectively.

Have cleared browser cache, tried Chrome (51.0.2704.79) and firefox (43.0.4) and another machine on the private LAN. Same results on all.

All 65 tests pass.

OS X 10.11.5
Node 5.8.0
npm 3.8.2

Thanks for your attention.

**Comment by blissdev** [comment]
I'm seeing this same issue.

**Comment by stunaz** [comment]
+1 same issue

**Comment by ajunge** [comment]
Same issue here. Tested on Chrome and Firefox on latest Ubuntu

**Comment by mxstbr** [comment]
Working on reproducing and fixing this asap, sorry for the troubles! Thanks for the detailed bug report @gihrig!

**Comment by gihrig** [comment]
The problem is webpack@2.1.0-beta.9 which is installed recently. 

`$ npm install --save-dev webpack@2.1.0-beta.8` gets things working again.

**Comment by mxstbr** [comment]
Nice on @gihrig, fix is pushed up to master, I pinned the dependency! Thanks for the help! :tada:

**Comment by gop-aroy** [comment]
Hey… I know i'm showing a little late, but i have the same issue here. Webpack is compiling but i have a "grey" screen… Yes my CSS styles are applied but no HTML is injected into my `<div id="app"></div>`.
Any idea ? I have no error in browser's console… Here is my webpack config :
```
const path = require('path');
const webpack = require('webpack');
let env = process.env.NODE_ENV ? process.env.NODE_ENV : 'dev';

module.exports = {
    context: path.join(__dirname, 'public', 'index.html'),
    entry: path.join(__dirname, 'src', 'App.jsx'),
    output: {
        publicPath: "/public/",
        path: __dirname + "/public/",
        filename: "bundle.js"
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx|es6)$/,
                loader: "babel-loader",
                exclude: "/node_modules",
                query: {
                    presets: ["es2015", "react", "stage-2"]
                }
            },
            {
                test: /\.scss$/,
                loaders: ["style-loader", "css-loader", "sass-loader"],
                exclude: "/node_modules"
            },
            {
                test: /\.css$/,
                loaders: ["style-loader", "css-loader"],
            },
            {
                test: /\.html$/,
                loader: 'file-loader?name=[name].[ext]'
            },
            {test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff"},
            {test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff2"},
            {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url-loader?limit=10000&mimetype=application/octet-stream"},
            {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file-loader"},
            {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url-loader?limit=10000&mimetype=image/svg+xml"},
        ]
    },
    resolve: {
        extensions: ['.js', '.jsx'],
    },
};
```

**Comment by gihrig** [comment]
@gop-aroy You likely have a JS error that is crashing the render of one of your components.

The best I can recommend is to retrace your steps since it was working. Hopefully you have made frequent git commits, so you can step back to a working configuration and compare to see what is breaking your app.

**Comment by gop-aroy** [comment]
I didn't even think about this possibility considering i didn't change anything in my components (as far as i remember) and when i'm run `react-scripts start` i have no error :(
<img width="413" alt="With react-scripts start (Affectations)" src="https://cloud.githubusercontent.com/assets/22291966/23156428/265aa500-f817-11e6-89fc-99ecd4d6ffc8.png">
<img width="413" alt="With Webpack (Affectations)" src="https://cloud.githubusercontent.com/assets/22291966/23156393/0fcd2e34-f817-11e6-8b9e-d3d9e0e9c0ea.png">
<img width="413" alt="With Webpack (home)" src="https://cloud.githubusercontent.com/assets/22291966/23156394/0fcde5fe-f817-11e6-921e-d3a34bfa1788.png">

I know i look like a noob, and i surely am, but do you have anything you can think of for me to investigate on ?

**Comment by gop-aroy** [comment]
Ok, it was because of my webpack configuration, but i won't be able to tell you where and why (maybe my vendors ?)… I used this awesome configuration sample : https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2
and by updating some data (folders etc.) i have a result \o/
Thank you for your time.

**Comment by gihrig** [comment]
Congrats on finding the bug 🎉

**Comment by dragGH102** [comment]
Same issue here. I tried to update webpack and other dependencies to the latest version

**Comment by gop-aroy** [comment]
Did you try the sample I linked ?

**Comment by dragGH102** [comment]
@gop-aroy actually I solved. something to do with the redux data apparently

**Comment by webandcraft** [comment]
what to do with redux ?

**Comment by ffcactus** [comment]
I have the same problem when I upgrade Webpack from 1.x to 3.10.0.
No error messages, it's really hard to find out the problem, It's not a helloworld project...

**Comment by HarryAdney** [comment]
Same here. The annoying thing is, I had it working fine, but now, nada, just the empty <div id="root"></div> plus css and script links.

Seriously, I spend more time chasing bugs and updating packages and modules than actually producing work some days!

**Comment by anitahkimanzi** [comment]
I have the issue; my reactjs application is displaying empty container
![appjs](https://user-images.githubusercontent.com/25051454/37462473-18b1723a-2863-11e8-9eec-24c21961223e.PNG)
![d](https://user-images.githubusercontent.com/25051454/37462474-18e5bf40-2863-11e8-96fb-b73d3c793522.PNG)
![html](https://user-images.githubusercontent.com/25051454/37462476-191507be-2863-11e8-8c11-9ea73bcdace4.PNG)
![index](https://user-images.githubusercontent.com/25051454/37462477-1943e6d8-2863-11e8-84a8-9a9f51269880.PNG)
That how it is.
please help.
