### ISSUE TITLE
Integrating react-toolbox

### ISSUE THREAD

**Issue by Stalso** [mxstbr/react-boilerplate#474]
Hello. I am struggling for few ours trying to use [react-toolbox](https://github.com/react-toolbox/react-toolbox)  in this template. All styles in components of the template are made using SASS. How can I load third party modules with SASS. As far as I understand, [this ](https://github.com/mxstbr/react-boilerplate/blob/eafbee2cfe6efeac729630d6dbca31a21137bc5b/docs/css/sass.md) instructions are fit to situations, when I need SASS for my own components. To enable SASS for react-toolbox, which is installed in npm_modules I have tried (last attempt) to add such code in `webpack.base.babel.js`  

    {
      // Do not transform vendor's CSS with CSS-modules
      // The point is that they remain in global scope.
      // Since we require these CSS files in our JS or CSS files,
      // they will be a part of our compilation either way.
      // So, no need for ExtractTextPlugin here.
      test: /(\.s?css)$/,
      include: /node_modules/,
      loaders: ['style-loader', 'css-loader','sass-loader'],
    }

And I am not sure , for another parts. How can I make this work? Also the author of react-toolbox says, that it supports css-modules

**Comment by mxstbr** [comment]
I've never used react-toolbox before, so I'm not really sure how to work with it. Maybe @javivelasco can help out?

**Comment by Stalso** [comment]
I think that integration of working library in template is the problem of template,  not library 😊.  If you will  be so kind to not close the issue,  I will provide my solution tomorrow.  Maybe you will see it and advise something.  Also I will try to contact with react-toolbox author. If he will help me,  I will provide code.  I think that integration with react - toolbox is important,  because it is rather popular ui library

**Comment by joehua87** [comment]
@Stalso 
I've try integrate with react-toolbox@1.0.0 with this commit: https://github.com/joehua87/react-boilerplate/commit/44cf758871e9b8ebc65ae5f5d803d29d3e682eb3
Screenshot: 
![](http://image.prntscr.com/image/32ac4b3bb50a4dc2aa6e82121b55b42f.png)

**Comment by datapimp** [comment]
@stalso 

In your specific case the configuration looks wrong off so I would double check.  It seems like that `/(\.s?css)$/` would also match files with the `.css` extension. Are you trying to match either `.scss` or `.sass`? 

The loader configuration has two key settings: `include` and `exclude`.  either can include an array of values, either regular expressions, functions, or strings.  A file's absolute path must match everything in include, and must not match any of the values listed in exclude.  

The `test` value can always be more specific, as well.   

Getting different css processors to play well together is going to be a process of finding the right combination of configuration entries for webpacks loaders, one for each of the different types of behaviors we want.

There's no reason the react-toolbox library wouldn't work, but unfortunately if you want to use a different preprocessor i see no way around getting your hands dirty with loader configurations but once it is done you can generally forget about it.

**Comment by javivelasco** [comment]
Hey guys! I think I didn't congrat @mxstbr and contributors for the project yet so **congrats**! It's pretty neat. I wanted to create an example today but the configuration looks pretty much like @joehua87 detailed. @datapimp I think I would set a single match for both too.

BTW, I wanted to ask why are you advising against sass?

**Comment by Stalso** [comment]
Hello I also managed to include it. It is similar to @joehua87 implementation. But I do not understand, why he need to create  `App/styles.scss` file and import it in `App/index.js` . Can you explain? Personally I have done several modifications.

I have installed sass-loader. Then I modified `\internals\webpack\webpack.base.babel.js` file with such code:

    {
      test: /\.scss$/,
      include: /node_modules/,
      loaders: options.sassLoaders,
    },

Also I added `'.scss'` value in the same file (in `resolve.extensions`).

Then I added `options.sassLoaders` variable in `\internals\webpack\webpack.dev.babel.js` like this:

    sassLoaders: 'style-loader!css-loader?localIdentName=[local]__[path]    [name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader!sass-loader',

Also I have included Roboto font in `index.html` and everything worked.

**Comment by gihrig** [comment]
Why advise against sass? IMHO, PostCSS and CSSModules is the future of styling. There's even a [SCSS parser for PostCSS](https://github.com/postcss/postcss-scss).

> PostCSS can do the same work as preprocessors like Sass, Less, and Stylus. But PostCSS is modular, 3-30 times faster, and much more powerful.

[From Sass to PostCSS](https://pawelgrzybek.com/from-sass-to-postcss/)

**Comment by joehua87** [comment]
@Stalso Sorry for confusing it. It's no need to create App.scss, I just try to override some default style :)

**Comment by mxstbr** [comment]
It seems like this question has been answered quite thoroughly, so I'll close it for now—thanks everybody for chiming in! :+1:

**Comment by inyigo** [comment]
@joehua87 @Stalso 
 just wondering if anyone has encountered this while integrating react-toolbox?

![saifon 2016-09-26 00-39-11](https://cloud.githubusercontent.com/assets/405883/18816731/c1a506dc-8381-11e6-8dfa-1f66a6170792.png)

I followed this https://github.com/joehua87/react-boilerplate/commit/44cf758871e9b8ebc65ae5f5d803d29d3e682eb3

**Comment by apinnecke** [comment]
Yes @inyigo ! Facing this bug since weeks and still didn't find a solution for that. @schubidu and me tried to have a closer look into what's happening, but no success. Would be great to find out what's really going on there.

**Comment by joehua87** [comment]
@inyigo you should include theme.scss in webpack.dev.config.js, try remove this line `include: /node_modules/,`

**Comment by apinnecke** [comment]
@joehua87 I tried that some time ago, that didn't solve the problem. Will try for myself again anyway.

**Comment by inyigo** [comment]
thanks @apinnecke I haven't really got back into this one as I was only trying out react-toolbox for some practice project. I will update if I dig deeper about this one

@joehua87, i wil try it too. thanks!

**Comment by Vadorequest** [comment]
I'm getting stuck here too.

`Dynamic page loading failed Error: Module parse failed: C:\wamp\www\kiosks-manager\node_modules\react-toolbox\lib\ripple\theme.scss Unexpected character '@'`

_It's such a hassle to deal with config like webpack nowadays, I feel like it has become so complicated to just test new stuff, I can't even display a dumb button without getting stuck._
