### ISSUE TITLE
In the Browser: "System.import is not a function"

### ISSUE THREAD

**Issue by skywalkerlucas** [mxstbr/react-boilerplate#481]
Hi,

I tried to write a redux project based on this project,
but after I implement the Dynmaic Router like in this project, run it, and visit the app in the browser,
the console reports error "System.import is not a function", and the component does not render correctly, I do not know why. 

Anyone could help me out? 

Thanks in advance.

**Comment by Aweary** [comment]
Hey @skywalkerlucas! react-boilerplate uses [webpack 2](https://github.com/mxstbr/react-boilerplate/blob/master/package.json#L187) which [introduces `System.import`](https://gist.github.com/sokra/27b24881210b56bbaff7#code-splitting-with-es6) into the webpack build system.

You're probably still using webpack 1, like most folks.

**Comment by skywalkerlucas** [comment]
Hi @Aweary ,

Got it, and clear. I am using webpack stable.

Thank you so much!
