### ISSUE TITLE
Generator route config

### ISSUE THREAD

**Issue by nkrambo** [mxstbr/react-boilerplate#484]
When generating a route using "npm run generate", user is prompted "Which component should the route show?".

If I want this route to point to a container component, I have to then update the routes.js after the generator has run as it will point to the components folder by default.

`{
      path: 'exampleroute',
      getComponent(location, cb) {
        System.import('components/ExampleContainer')
          .then(loadModule(cb))
          .catch(errorLoading);
      },
    },`

Would be handy to have an additional configuration prompt here perhaps? Or additional documentation if it's already achievable from the command line.

**Comment by mxstbr** [comment]
Oh my, what a horrible bug! Would you mind submitting a PR to fix this? The code is in internals/generators/route!

**Comment by nkrambo** [comment]
Sure can! I'll hopefully get around to this in the next day or so.
Cheers.

**Comment by mxstbr** [comment]
Fixed by the amazing @nkrambo in #504! :fire:
