### ISSUE TITLE
Express display

### ISSUE THREAD

**Issue by Stalso** [mxstbr/react-boilerplate#486]
Hello. It is stupid problem, but I can not resolve t. I have tried to log something in express midlleware, but there is no output in console with such code ( `server\middlewares\frontendMiddleware.js` ):

    app.get('*', (req, res) => {
      console.log('echo route');
      const file = fs.readFileSync(path.join(compiler.outputPath, 'index.html'));
      res.send(file.toString());
    });

**Comment by mxstbr** [comment]
The above code works for me…

Have you restarted the express server?

**Comment by Stalso** [comment]
Yes. I am using windows and Node v6

**Comment by mxstbr** [comment]
Are you looking into the browser console or the terminal console?

**Comment by Stalso** [comment]
I am looking in browser console

**Comment by mxstbr** [comment]
Ah yeah, express.js runs on the command line, so those logs are only visible in the terminal!

**Comment by Stalso** [comment]
Oh, sorry. I am looking in TERMINAL console.

**Comment by mxstbr** [comment]
> I am looking in TERMINAL console.

Are you visiting the page in the browser? Those logs will only be visible if you actually open the page in the browser.

**Comment by Stalso** [comment]
Of course I do.

**Comment by mxstbr** [comment]
I'm sorry, I have no idea then, this is definitely working for me 😢

**Comment by Stalso** [comment]
Ok. It is not a big trouble.

**Comment by mxstbr** [comment]
No issue is ever stupid. Does it still work?
