### ISSUE TITLE
Packaging with Electron: Resources issue

### ISSUE THREAD

**Issue by Unforgiven-wanda** [mxstbr/react-boilerplate#488]
Hello,
after building my project and checking that it runs flawlessly on my server, I've wanted to package it with Electron (mainly as an experiment). However when I load the URL and the desktop app starts I encounter the following errors (in Electron's DevTools):

`file:///main.7b77c3177cbc4b4b77cac63e87f9d891.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///common.js.59147b1f2eb4275afbd1.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///main.69a8ce0e0b57952af202.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

I've tried removing the "/" in my index file, only to stumble on this next:

`Failed to load resource: net::ERR_FILE_NOT_FOUND
main.69a8ce0….js:21 Dynamic page loading failed Error: Loading chunk 2 failed.(…)`

I'm a bit at a loss here, why is it behaving this way? And how to fix this? 
Thank you

**Comment by datapimp** [comment]
You can try setting the `publicPath` property to an empty value instead of `/`

```js
{
  target: 'electron-renderer',
  output: {
    publicPath: ''
  }
}
```

and this will make all links relative to the `build/index.html` that you open with electron.

Another approach I've tried ( in the interests of being able to easily share code between the electron and web platforms ) is adding a `<base href="file://whatever/" />` tag to the head tag -- this works well.

**Comment by datapimp** [comment]
In case it wasn't clear I was referring to making changes in the webpack configuration, both solutions only really address production builds and not development with hot module reloading 

To make development electron scenarios work, you either open the browser window to a localhost:3000 url just as you do for the browser...

or you dynamically add the webpack entries from a local file by appending a script tag to the DOM.  

I am currently working on on an electron app and will share code asap - let me know if you have any questions

**Comment by Unforgiven-wanda** [comment]
Hi,
I've tried your answer, and now the issue just "morphed" somewhat.
Now I can see something (the "not found" view) when the app starts -as opposed to nothing earlier-. However, not only do I end up in the 404 page on startup, when clicking home I have the following error still. A screenshot to illustrate:
![screenshot from 2016-06-08 11-14-30](https://cloud.githubusercontent.com/assets/4499783/15891012/7524427c-2d6a-11e6-9802-3d730640d594.png)

What I'm trying to build is a fully-offline desktop app, could I somehow modify the Webpack configuration so that I have a single javascript file, and not all those "chunks"?

**Comment by tinybug** [comment]
@Unforgiven-wanda you should change browserHistory to hashHistory in app.js, and add `target: electron-renderer in webpack configuration`, and then it will work fine.

**Comment by Telemakhos** [comment]
@datapimp we're facing a similar scenario where we need to share electron and web codebases. What approach did you end up using? Where should we place our electron (the usual `main.js`) code?

Any pointer/advise highly appreciated =)
