### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by Ndpnt** [mxstbr/react-boilerplate#489]
Image optimization can be a really performance improvement for big Apps. 
Unless I miss something, there is no such thing for now. What is your thoughts on integrating image optimization in webpack process, like this one [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader)?

Would you be interested by a pull request?

**Comment by mxstbr** [comment]
I tend to agree, there won't be many big apps that don't want this! Would love a PR!
