### ISSUE TITLE
Server in production needs packages from devDependencies

### ISSUE THREAD

**Issue by Ndpnt** [mxstbr/react-boilerplate#491]
After installing dependencies in our production server with `npm install --production`, when we run `npm run start:prod`, the command fails because some packages can't be found:
- `cross-env`,
- `ip`,
- `ngrok`,
- …

Do we miss something or there are some packages which should be moved from `devDependencies` to `dependencies`?

**Comment by Ndpnt** [comment]
I think I got it… Files should be served by Nginx, that's it?

**Comment by datapimp** [comment]
There isn't any reason to use those in production I don't think;

I was able to reproduce this, I will try to fix it;  In the meantime, can you install the dev dependencies?

**Comment by Ndpnt** [comment]
Thanks for your quick response. Yes, for now we use dev dependencies.

**Comment by mxstbr** [comment]
Ah yeah, I forgot to put server dependencies into `dependencies`, my bad!

Thanks for fixing this @datapimp!

**Comment by mxstbr** [comment]
Resolved in #495, thanks for notifying us @Ndpnt!
