### ISSUE TITLE
Offline feature – Add support for fallback app shell

### ISSUE THREAD

**Issue by werbitzky** [mxstbr/react-boilerplate#492]
As I understand, the Service Worker only works with the initial root path ```"/"``` For example: if you try to access ```"/features"``` directly offline, the Service Worker cache won't match and your offline page won't load (ERR_CONNECTION_REFUSED).

The Service Worker should serve the app shell, i.e. index.html as a fallback.

**Comment by sotojuan** [comment]
As an aside, I'd love for this boilerplate to support progressive rendering. Currently the app (before doing the offline caching) takes more than ten seconds to load with "Good 4G" throttling and for those ten seconds, all you get is a white screen. It'd be nice to include some sort of basic layout rendering with `renderToString` and the HTML Webpack plugin. Not only would this be good UX, but having it in the boilerplate by default would be attractive to potential users.

I can look into this, but IIRC it can be hard to get working right.

**Comment by werbitzky** [comment]
The step from progressive rendering to complete server-side rendering (with data fetching) might not be that big. You only need to provide a structure by which route handlers can specify what data they need – so I am not sure if it would be worth doing as two separate steps?
I assume that server-side/universal rendering would make progressive rendering obsolete, since it would essentially be `renderToString` with data, or am I missing something?

I've never implemented a service worker, but it seems to me, for a functional version of a fallback, we would need a "wildcard route" and possibly a whitelist/blacklist to not catch everything, for example to exclude asset routes?

We can find that in the wild, for example here: https://github.com/GoogleChrome/sw-precache#navigatefallback-string

Also the offline plugin has an open issue for a feature that could help to achieve that:
https://github.com/NekR/offline-plugin/issues/59

**Comment by mxstbr** [comment]
Yeah, serverside rendering is basically going to fix all of these issues hopefully :grin: just need to get it in…

See #174 for the discussion about this feature, feel free to chime in there!
