### ISSUE TITLE
eslint failing with generated component.

### ISSUE THREAD

**Issue by nkrambo** [mxstbr/react-boilerplate#494]
Generating a component from the command line introduces 2 react/jsx-curly-spacing lint issues.

This is because of the spacing on the className attribute.

`<div className={ styles.generatedComponent }>`

**Comment by mxstbr** [comment]
Awesome, thanks for the bug report! Would love a PR fixing this!

**Comment by jurekbarth** [comment]
@nkrambo should be fixed now in #529

**Comment by mxstbr** [comment]
Awesome, closing! THanks @jurekbarth!
