### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by agungsb** [mxstbr/react-boilerplate#496]
Hi, I just would like to let you know that I found error when I tried to build the application with `npm run build`. Here is one of the message:

```
36:7   error  Extra space after key 'loader'  key-spacing
36:29  error  Missing trailing comma          comma-dangle

✖ 2 problems (2 errors, 0 warnings)
```

So I changed the 'pointed' line with `loader: 'file-loader',` and then it works.

I hope this will help someone out there who faced the same problem as I had.

**Comment by datapimp** [comment]
thank you. the project runs the test suite prior to building, and the test suite runs the linter;  personally I'm not a fan of this behavior, but I'm also pretty sloppy so I try to force myself to accept using a linter.

you can always modify the eslint rules to not force you to use the trailing comma if this keeps tripping you up.
