### ISSUE TITLE
"npm ERR!" when "npm run lint" reports errors

### ISSUE THREAD

**Issue by Augustin82** [mxstbr/react-boilerplate#498]
Hi, and thanks for the very helpful boilerplate.

I have the following problem, which may or may not be the intended behaviour: when I run `npm run lint`, I expect to have a nice list of errors I need to go through and fix, for both my JS and CSS. Instead, I have a list of errors to fix in my JS, and then npm spits out a nasty error log, and then my CSS never gets linted. See the edited version:

> $ npm run lint
> 
> \> react-boilerplate@3.0.0 lint ************
> \> npm run lint:js && npm run lint:css
> 
> 
> \> react-boilerplate@3.0.0 lint:js ************
> \> eslint . --ignore-path .gitignore --ignore-pattern internals/scripts
> 
> *lots of JS errors here*
> 
> ✖ 46 problems (46 errors, 0 warnings)
> 
> 
> npm ERR! Linux 4.5.0-040500-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:js"
> npm ERR! node v6.2.1
> npm ERR! npm  v3.9.5
> npm ERR! code ELIFECYCLE
> npm ERR! react-boilerplate@3.0.0 lint:js: `eslint . --ignore-path .gitignore --ignore-pattern internals/scripts`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the react-boilerplate@3.0.0 lint:js script 'eslint . --ignore-path .gitignore --ignore-pattern internals/scripts'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     eslint . --ignore-path .gitignore --ignore-pattern internals/scripts
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs react-boilerplate
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls react-boilerplate
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     ************/npm-debug.log
> 
> npm ERR! Linux 4.5.0-040500-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
> npm ERR! node v6.2.1
> npm ERR! npm  v3.9.5
> npm ERR! code ELIFECYCLE
> npm ERR! react-boilerplate@3.0.0 lint: `npm run lint:js && npm run lint:css`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the react-boilerplate@3.0.0 lint script 'npm run lint:js && npm run lint:css'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run lint:js && npm run lint:css
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs react-boilerplate
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls react-boilerplate
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     ************/npm-debug.log

So the problem, to me, is two-fold: not only the big npm error message is ugly and useless and forces me to scroll my terminal to access the real info, it stops the CSS linting from happening (if I'm not mistaken).

Thanks for your help!

PS: I'm using the latest versions of node (v6.2.1) and npm (3.9.5) that I could install on Ubuntu 16.04 using npm's `n` and `npm` packages.

**Comment by mxstbr** [comment]
Yeah that's the way `npm` works…

AFAIK there's no way to change this, even though I would greatly prefer it to work the way you suggest. I'll close this issue for now, but feel free to ping me if you know how to fix it!

Cheers!

**Comment by WesHildebrandt** [comment]
I was able to fix this issue by changing the lint:eslint script to "eslint --ignore-path .gitignore --ignore-pattern internals/scripts || true".  If the eslint command results in an error, the "|| true" part will run, returning true (e.g., non-error) to npm.

**Comment by sahiljain112** [comment]
Thanks @WesHildebrandt. That solved the problem.

**Comment by gihrig** [comment]
@WesHildebrandt Seems like a nice improvement 😄  How about opening a PR?

**Comment by mxstbr** [comment]
That's not an improvement, that's an ugly workaround. :blush: doing so would mean the CI doesn't stop when listing fails, for example.

**Comment by gihrig** [comment]
So many masters, devs, local build, servers, browsers, CI... how to keep everyone happy... sigh.

**Comment by WesHildebrandt** [comment]
Well, I guess I won't bother with a PR, then.  Hopefully others with this issue can just google and find the solution.  :-)

**Comment by Augustin82** [comment]
Unfortunately, it is not "a solution", as was said.

I would love for NPM to just stop and show me the error log WITHOUT spewing 40 lines or so of meaningless error messages, telling me to check my node version while the problem is the test or even the CSS linting.

However, just suppressing error messages is definitely NOT the way to go with this, for reasons mentioned. If that's what YOU need, then by all means go for it: it's important that we tailor tools to our needs =)

**Comment by felipenmoura** [comment]
I just used

` || exit 0`

This way, when it fails linting, it exits the commands, preventing the CI from running other tasks.
What do you think about it?

**Comment by nitindev111** [comment]
Any solid solution for the above issue?

**Comment by gihrig** [comment]
The "solution" is as @felipenmoura suggested. But this is something you will have to evaluate and apply to your project if it works for you and your build process.

The real "problem" is npm's behavior, that's not something this project can change.
