### ISSUE TITLE
How do I generate nested routes using this starter kit?

### ISSUE THREAD

**Issue by yookore** [mxstbr/react-boilerplate#499]
First off, thanks for this fantastic starter kit that's being actively developed. I'd like to know how to generate nested routes to components that share the same parent layout and functionality, something akin to a ProfileHome component that handles /profile and a ProfilePhotos component that handles /profile/photos but wrapped in a ProfileContainer that provides shared layout features like  a header.

**Comment by harijoe** [comment]
It is not currently possible to generate nested route using the provided generator. You can still add children routes manually. Even though the generator does not allow the automated generation of nested routes, I think there should be at least an example of how to implement it.

**Comment by yookore** [comment]
Exactly! I've been battling with this for the whole day and trying to compare notes with the react-redux-starter kit and I'm still quite confused how to go about it. An example is sorely needed. :)

**Comment by mxstbr** [comment]
> I think there should be at least an example of how to implement it.

We'd appreciate a PR adding that to the docs!

**Comment by JulienMelissas** [comment]
> You can still add children routes manually.

Hate to resurrect an old issue but does anyone have an example of this I can go off of? If so, I'll be happy to contribute back and add a good example to the docs. Thanks!

**Comment by mxstbr** [comment]
```JS
{
  path: '/something',
  name: 'features',
  getComponent(nextState, cb) {
    System.import('somepath/Layout1')
      .then(loadModule(cb))
      .catch(errorLoading);
  },
  childRoutes: [
    {
      /* more routes here, these will be /something/** */
    }
  ]
}, {
  path: '/else',
  name: 'features',
  getComponent(nextState, cb) {
    System.import('somepath/Layout2')
      .then(loadModule(cb))
      .catch(errorLoading);
  },
  childRoutes: [
    {
      /* more routes here, these will be under /else/** */
    }
  ]
}
```

**Comment by JulienMelissas** [comment]
Thanks @mxstbr. I actually figured it out myself, but your example helped me know I was going about it the right way. PR for documentation here: https://github.com/mxstbr/react-boilerplate/pull/648

**Comment by mxstbr** [comment]
Thanks @JulienMelissas, that's awesome!
