### ISSUE TITLE
Change .react.js extension

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#50]
See https://github.com/mxstbr/react-boilerplate/issues/27#issuecomment-167496962, maybe consider switching to `.jsx` for react files? 

Going to look around at different boilerplate to see what the current consensus is.

**Comment by zavelevsky** [comment]
Although not everyone might want to use JSX - it makes a good distinction. And as it is - you have a webpack-based project - so no harm in letting people know JSX is a supported option.
In any case - I don't see any need to add `.react` to the file name - it's under the /react/components folder as it is (or as it should be IMO). So the way I see it it should wither be `.jsx` or simple `.js`.

I'm in favor of `.jsx` in my projects - because I use JSX and:
 - it clearly states the usage of jsx
 - it allows for easier definition of templates in IDEs
 - it allows for specific rules in webpack (less strong argument)
 - easier to filter search results in larger projects.

**Comment by mxstbr** [comment]
While I tend to agree, @steida made some good points in https://github.com/este/este/issues/125 about using `.react.js`. I'll quote him here:

> Non elegant .react extension is pretty elegant once you have naming clash between user.react.js and user.js (Record or class). It's also idiomatic Facebook style - https://github.com/facebook/flux/blob/master/examples/flux-chat/js/components/MessageListItem.react.js User should know what is part of view without seeing file source, and custom dirs will not help. .react.is is the most pragmatic.

And on why no `.jsx`:

> No, because then you have to set up two file extensions. Also, xyz.react.js is very convenient for fuzy file search. Typing "home.r" is faster then typing "home.jsx".

I'll have to think about this a bit more, I'm not convinced switching to `.jsx` is the right thing to do.

**Comment by zavelevsky** [comment]
Actually I didn't find his arguments very convincing - but I tend to agree because it seems that it's a common practice - so no real reason to go against it here.
Windows users might be pissed because of long path names :smiley:

**Comment by philihp** [comment]
I'm a fan of `SomeComponent.jsx`. I've found that importing them is easier, as mentioned in https://github.com/mxstbr/react-boilerplate/issues/27#issuecomment-167564804

**Comment by mateodelnorte** [comment]
Not using the .jsx extension breaks most IDE's syntax highlighting - you won't get jsx highlighting in Sublime or vim unless you manually change the syntax highlighter - which is a PITA. That alone makes me not want to use this boilerplate.

**Comment by mxstbr** [comment]
- **Sublime Text**: Install [`babel-sublime`](https://packagecontrol.io/packages/Babel) and set it as your default syntax highlighter for all `.js` files. Not only do you get correct JSX syntax highlighting, you also get all ES6,7,… features correctly syntax highlighted for free!

- **Atom**: Install [`language-babel`](https://atom.io/packages/language-babel) and set it as your default syntax highlighter for all `.js` files.

 I'm not a Vim user, so I can't help you there, but I'm sure such a package exists for Vim too! :+1:

**Comment by jwinn** [comment]
Just wanted to add how to get syntax in vim for JSX:
[vim-jsx](https://github.com/mxw/vim-jsx)
For JSX support in all .js files, add the following to your `vimrc` file:
`let g:jsx_ext_required = 0`
