### ISSUE TITLE
What about adding carte-blanche? 

### ISSUE THREAD

**Issue by Ndpnt** [mxstbr/react-boilerplate#500]
I saw your talk https://www.youtube.com/watch?v=0IkWuXeKPV0 and I think this is a really great idea. Do you plan to add this in the boilerplate? 
I think having a component's catalog could be really useful for integration testing with lib like Nightwatch.js.

**Comment by mxstbr** [comment]
Yes absolutely, I just haven't come around to doing it yet. There's an open issue over at the Carte Blanche repo about supporting some techniques we use here: https://github.com/carteb/carte-blanche/issues/285

**Comment by ansumanshah** [comment]
Want to add this but getting some webpack error any snippet that I can follow?

**Comment by agriffis** [comment]
There doesn't seem to be an issue for tracking the addition of carte-blance to the boilerplate. Any chance we'll see it soon? Would it be worth adding something to the v3.3 project for tracking?
