### ISSUE TITLE
"npm WARN" regarding webpack versions

### ISSUE THREAD

**Issue by Augustin82** [mxstbr/react-boilerplate#508]
Hi!

From the project's master, running `npm run setup` gives the following output:

> $ npm run setup
> 
> \> react-boilerplate@3.0.0 presetup /path/to/project
> \> npm i chalk
> 
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
> npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
> npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
> npm WARN offline-plugin@3.3.0 requires a peer of webpack@>=1.0.0 but none was installed.

Shouldn't these dependencies be declared in package.json?

**Comment by mxstbr** [comment]
That's because we use webpack 2, but not all of the plugins have adjusted their peerDependencies yet. This is absolutely fine, it'll work exactly as expected!

**Comment by Augustin82** [comment]
Cheers!
