### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by Ndpnt** [mxstbr/react-boilerplate#510]
Images often represent the majority of bytes downloaded on a web page, so image
optimization can often be a notable performance improvement for large scale web app.

I'm going to open a PR where I added [`image-loader`](https://github.com/tcoopman/image-webpack-loader) to compress images in the Webpack process: https://github.com/mxstbr/react-boilerplate/compare/master...soundsgood-co:image-optimization?expand=1

In my implementation, images optimization is done both in development and production mode.

So my question is, do you think it is a good idea as it allows us to see how images are compressed during our development process and potentially adjust settings or do you think it could slowdown things too much and it's better to compress images only for production?

**Comment by azampagl** [comment]
I'd think it is best to have the compression on both production and development in case there is an degradation of the images.

Can you define "slowdown things too much" - does the compression take a while?

**Comment by Ndpnt** [comment]
I have only tested it on a very small app and there is no impacts. 
I also think it is better to have compression in development but I was wondering if it could be a drawback for a larger app.

**Comment by mxstbr** [comment]
Done by the great @Ndpnt in #518!
