### ISSUE TITLE
older browser css issue

### ISSUE THREAD

**Issue by kkneip** [mxstbr/react-boilerplate#512]
I'm having an issue with a QTWebKit4 browser. PostCSS seems to remove or modify e.g. "-webkit-transform". Unfortunately this browser is not able to handle "transform" and needs to have "-webkit-transform" instead. (Windows 7 x64, react-boilerplate v3)
I just started react and react boilerplate and I'm not sure where to handle this by taking react-boilerplate's concepts into account.
Any help is very appreciated! ;o)

**Comment by kkneip** [comment]
Maybe I just need to set **remove** option for **PostCSS autoprefixer** to **false**.
But I don't know where to set it. Who has an idea or is able to help?

Best regards, Karsten

**Comment by kkneip** [comment]
Sorry, I hit the wrong button.
I maybe just need to set **remove** option for **PostCSS autoprefixer** to **false**.
But I don't know where. Who is able to help?

Many thanks in advance and best regards, Karsten

**Comment by mxstbr** [comment]
I don't think this is related to `react-boilerplate`, and I've never heard of this issue before. I'd suggest you open an issue at the `autoprefixer` repo, you'll probably get help there faster!

**Comment by kkneip** [comment]
I think it's just related to PostCSS autofixer plugin. 
My main problem is that I don't know where to set configuration for autoprefixer.
The issue seems to be caused by the feature described [here](https://github.com/postcss/autoprefixer#only-actual-prefixes) at PostCSS documentation.

**Comment by mxstbr** [comment]
Ah, the `autoprefixer` configuration is included with the `cssnext` plugin! See `internals/webpack/webpack.dev.babel.js` and `webpack.prod.babel.js`:

```JS
cssnext({
  browsers: ['last 2 versions', 'IE > 10'], // <- AUTOPREFIXER OPTION
}),
```

**Comment by kkneip** [comment]
I changed it to 
```
cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
      remove: false,
    }),
```
But without success. Then I disabled cssnet at all by just commenting it out.
Maybe it's not the best way, but from then it is not removing -webkit- styles at all.

Thanks for pointing me to the right direction. I'll try to open a ticket at cssnext as well to try to just disable removement of "unneccessay" styles.

**Comment by mxstbr** [comment]
Awesome!
