### ISSUE TITLE
 cross-env NODE_ENV=development node server Fails

### ISSUE THREAD

**Issue by chcarter** [mxstbr/react-boilerplate#513]
Error says: 'cross-env' is not recognized as an internal or external command, operable program or batch file.

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-boilerplate@3.0.0
6 info start react-boilerplate@3.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-boilerplate@3.0.0 Failed to exec start script
9 verbose stack Error: react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development node server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-boilerplate@3.0.0
11 verbose cwd C:\Users\chcarter\Desktop\react-boilerplate
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development node server`
17 error Exit status 1
18 error Failed at the react-boilerplate@3.0.0 start script 'cross-env NODE_ENV=development node server'.
18 error This is most likely a problem with the react-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env NODE_ENV=development node server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-boilerplate
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by eddiewang** [comment]
did you install cross-env with npm?

**Comment by maraza** [comment]
'cross-env' is not recognized as an internal or external command,
operable program or batch file.

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kindo-web@1.0.0 dev: `cross-env NODE_ENV=development npm run webpack-dev-server -- -d --colors --hot`
npm ERR! Exit status 1
npm ERR!
```
I've done npm install, and my npm/node versions are mentioned above? Any advice?

**Comment by pgangwani** [comment]
Put && before 'node server' (2nd command)
