### ISSUE TITLE
Are layouts feasible?

### ISSUE THREAD

**Issue by MrOutis** [mxstbr/react-boilerplate#514]
Taking a look at `app.js`: what `App` container does, is wrap all the child components, so you put code that will render in every "page" of your app, let's say a footer, or something.

A layout allows you to surround something with some ~~HTML~~ code.

So I thought about `App` container to be sort of a layout, but what if I want to work with several layouts? how is this currently being solved?

For reference, [Middleman][middleman] has a layout feature.

[middleman]: https://middlemanapp.com/basics/layouts/

**Comment by zanedev** [comment]
I think this would be solved with the conditional display react views/components based on the app state and passing down props.  You could have a layout param in state or base it off the router like more of a page template approach.  Basically any react component can take props and display anything based on those props either conditionally or as part of the content you inject into the child component.

**Comment by mxstbr** [comment]
The `App` container is nothing but a route that renders more routes inside itself, so you could do the same thing another time:

```JS
{
  path: '/layout1',
  name: 'features',
  getComponent(nextState, cb) {
    System.import('somepath/Layout1')
      .then(loadModule(cb))
      .catch(errorLoading);
  },
  childRoutes: [
    {
      /* more routes here, these will have layout number 1 */
    }
  ]
}, {
  path: '/layout2',
  name: 'features',
  getComponent(nextState, cb) {
    System.import('somepath/Layout2')
      .then(loadModule(cb))
      .catch(errorLoading);
  },
  childRoutes: [
    {
      /* more routes here, these will have layout number 2 */
    }
  ]
}
```

Hope that answers the question!

**Comment by MrOutis** [comment]
Awesome, @mxstbr, thank you, dude! :beer:

**Comment by mxstbr** [comment]
No worries, glad I could help!

Also, thanks for the donation, I really appreciate it!

**Comment by mde17** [comment]
how about abstract layouts?
