### ISSUE TITLE
webpack `jsnext:main` working?

### ISSUE THREAD

**Issue by andykenward** [mxstbr/react-boilerplate#517]
It doesn't seem the webpack resolve packageMains for jsnext:main is working?

Does it only use it when you build in production?
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L77

**Comment by mxstbr** [comment]
Possibly, what kind of errors/bugs are you getting?

**Comment by andykenward** [comment]
It is not so much an error. Just doesnt seem to import the `jsnext:main` version of a npm package if it is defined in their `package.json`. I deleted the `dist` and `lib` folders in `redux` package folder to see if it was actually using the `es` folder. But it errors out looking for `lib` folder of the package.  

`Module not found: Error: Can't resolve 'redux' in`

`ERROR in ./~/react-redux/lib/utils/wrapActionCreators.js
Module not found: Error: Can't resolve 'redux' in`

If it isnt using the `jsnext:main` version of a package. Would this effect the tree shaking in webpack too?

**Comment by mxstbr** [comment]
Hmm, interesting, to be honest I have no idea, neither if it affects tree shaking nor how to fix it… As far as I can tell `packageMains` would be the way to do it?

Any ideas?

**Comment by mgmcdermott** [comment]
This will be fixed if #551 is merged. Currently packageMains is not overriding webpack's defaults.

**Comment by mxstbr** [comment]
This is fixed now
