### ISSUE TITLE
View PageSource in Feature page leads to page not found

### ISSUE THREAD

**Issue by sap9433** [mxstbr/react-boilerplate#520]
Browsers default behavior is not working view-page-source  while on feature page (`view-source:http://localhost:3000/features`)leads to error `Not Found`

**Comment by mxstbr** [comment]
Yes, that's because we use client-side routing and rendering. You'll have to `Inspect Element`!

**Comment by sap9433** [comment]
This is still a bug ...

**Comment by mxstbr** [comment]
Nothing we can fix, if you're using React that will always be the case!


Try to `view-source` on any other React app, and what you'll see is either an empty HTML file (not very useful) or nothing because you're on a client-side routed page. Sorry!

**Comment by sap9433** [comment]
1. Server side rendered App fix this problem . And that's how it solves SEO problem . Try view-source on Facebook . 

If your page actually shows some content , and crawler-sees (view-source) blank / some other content that you will have to pay hefty SEO penalty . 

I'm trying to use this boiler plate to bootstrap the MobileApp of one of the largest E-commerce player in India . If We succeed , we will become a sponsor of this repo. Main drawback is no ser-ver side rendering . So wish me luck  and kindly be in touch .I'll be needing your help

**Comment by mxstbr** [comment]
> Server side rendered App fix this problem

Very true, which is why that's the next big feature after i18n we're working towards! :+1: 

> If your page actually shows some content , and crawler-sees (view-source) blank / some other content that you will have to pay hefty SEO penalty .

Google crawls JS rendered sites just fine, I don't know about other search engines though…

> I'm trying to use this boiler plate to bootstrap the MobileApp of one of the largest E-commerce player in India . If We succeed , we will become a sponsor of this repo. Main drawback is no server side rendering . So wish me luck and kindly be in touch .I'll be needing your help

That's awesome! You know where to find me, keep the questions coming!
