### ISSUE TITLE
Directly hitting Route leads to 404

### ISSUE THREAD

**Issue by sap9433** [mxstbr/react-boilerplate#521]
If I hit Directly `http://localhost:3000/features` it leads to `Not Found` . Without this feature essentially it can't be used in consumer app.

**Comment by mxstbr** [comment]
That's a problem in your server setup most likely. The server needs to redirect every connection to `/`.

**Comment by sap9433** [comment]
Nopes . There's no such route match in your express . So this should fail for everybody

**Comment by mxstbr** [comment]
```JS
app.get('*', /* … */);
```

https://github.com/mxstbr/react-boilerplate/blob/master/server/middlewares/frontendMiddleware.js#L25-L33

That matches every connection (no matter what URL) to the express server, and returns the correct file.

So, the issue must be that the connection never reaches the express server!

**Comment by Moeface** [comment]
For what it's worth, I'm having the same issue.

I've pulled a fresh copy of this, and visiting the /features page through the button on the page works fine, but hitting the URL or refreshing once I'm on that page, it returns a 404.

**Comment by mxstbr** [comment]
Ahhh, I know why, that's my bad! Fixing asap.

**Comment by mxstbr** [comment]
Sorry, I didn't realize a recent change broke this, that was my bad! Thanks for notifying me, this is now fixed! :tada:
