### ISSUE TITLE
No server-side rendering ?

### ISSUE THREAD

**Issue by sap9433** [mxstbr/react-boilerplate#522]
We will like to have a server side rendering functionality with this starter.

**Comment by wdjungst** [comment]
Duplicate issue

**Comment by sap9433** [comment]
couldn't find the duplicate , please refer the issue number I'll close this.

**Comment by wdjungst** [comment]
Maybe not exact dup but discussed here https://github.com/mxstbr/react-boilerplate/issues/174

**Comment by mxstbr** [comment]
Yeah, duplicate of #174, please discuss there!

**Comment by mxstbr** [comment]
@sap9433 you might want to join us on Gitter for discussions: https://gitter.im/mxstbr/react-boilerplate :+1:
