### ISSUE TITLE
Mocha and arrow functions

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#523]
In your tests you use arrow functions with Mocha, but it's not advised by Mocha's doc:

https://mochajs.org/#arrow-functions

Do you know something that I don't? 😁

**Comment by mxstbr** [comment]
TIL, I didn't know `this.timeout` was a thing in Mocha and have never used it before! Lets remove all arrow functions from the tests since they're an antipatter!

**Comment by FezVrasta** [comment]
I think we'll have some problems with ESlint then...

https://github.com/eslint/eslint/issues/3611

Seems like we can't tell ESLint to disable the `prefer-arrow-function` rule just for our `*.test.js` files.

**Comment by mxstbr** [comment]
Oh no, that's a shame 😢

I'll close this issue for now, lets revisit this when glob support is in ESLint! Thanks for notifying me of this, let's keep an eye on this!

**Comment by FezVrasta** [comment]
There would be this project to allow arrow functions with Mocha:
https://github.com/skozin/arrow-mocha

I'm not sure if I like it or not tho.

**Comment by mxstbr** [comment]
Seems really dirty, to be honest. I'd keep it as-is for now, it hasn't killed anybody yet so I don't think it's that critical :grin:
