### ISSUE TITLE
Reading index.html from fileSysytem  on everyRequest , wont it hurt performance

### ISSUE THREAD

**Issue by sap9433** [mxstbr/react-boilerplate#524]
In `middleware/frontendMiddleware` , 
`app.get('*', (req, res) => res.sendFile(path.join(options.output.path, 'index.html')));`

On every request we are reading index.html from fileSystem.

Even if  express `sendFile` will check it's internal cache (which I'm not sure) , it will still need to do a cacheCheck from some hashfile.

shouldn't we preload entire html in some variable `const indexHtml =  "<html>.....</html>`"`and send that variable instead..

**Comment by mxstbr** [comment]
Yeah, that sounds reasonable!

**Comment by FezVrasta** [comment]
What if you edit `index.html` while the server is running?

**Comment by sap9433** [comment]
we will change only in `addProdMiddlewares` .

**Comment by watson** [comment]
I'm pretty sure `res.sendFile` does not employ any caching. It's using the "send" module internally [which specifically states](https://github.com/pillarjs/send#caching) that it doesn't perform caching. The `res.sendFile` function it self [doesn't seem to have any caching either](https://github.com/expressjs/express/blob/f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a/lib/response.js#L385-L420).

It is using a stream though, which is the correct way to handle file I/O in Node. So it's non-blocking and will therefore not have any significant impact on the rest of the application as long as the event loop isn't saturated. But it does increase the time it takes for the client to receive the file of course.

I'm not aware of any function in Express similar to `res.sendFile` that have caching. So this is something you'd have to build your self. I would personally employ lacy loading using the [thunky](https://github.com/mafintosh/thunky) module if I needed to do this, but there are several possible solutions of course.

**Comment by mxstbr** [comment]
Thanks for chiming in @watson, glad to hear it's not a big performance impact!

**Comment by mxstbr** [comment]
Closing due to little interest and tiny perf impact.
