### ISSUE TITLE
Error when generating a new ES6 class component

### ISSUE THREAD

**Issue by malexanders** [mxstbr/react-boilerplate#534]
Not sure how to trouble shoot this error. The tricky thing is, the file in which the error is contained, never actually appears in the file tree after the error is thrown. So, I don't know how to go in and fix the error.  A stateless component is generated with no problems. Please see error below

<img width="791" alt="screen shot 2016-06-11 at 2 30 13 pm" src="https://cloud.githubusercontent.com/assets/16038346/15986829/15d8bbf8-2fe1-11e6-9a1b-de5c406e5eb7.png">

**Comment by jurekbarth** [comment]
The issue occurs because of the triple curly braces i think. I changed it yesterday but you could fix it by add whitespace like this `...camelCase name }} }` here: https://github.com/mxstbr/react-boilerplate/blob/master/internals/generators/component/es6.js.hbs#L17 or use the latest version :+1:
