### ISSUE TITLE
Issue while running npm start

### ISSUE THREAD

**Issue by yogitaAP** [mxstbr/react-boilerplate#536]
vagrant@precise64:/vagrant/react-boilerplate$ sudo npm start

> react-boilerplate@3.0.0 start /vagrant/react-boilerplate
> cross-env NODE_ENV=development node server

sh: 1: cross-env: not found

Gives this error after successful installation of dependencies. Node version is 6.2.1 and npm is 3.9.5.

**Comment by mxstbr** [comment]
`$ npm install --save-dev cross-env` will fix this. Something is wrong with our dependencies, sorry about that, will look into it!

**Comment by yogitaAP** [comment]
Running the above command throws this - 

EPROTO: protocol error, symlink '../which/bin/which' -> '/vagrant/react-boilerplate/node_modules/.bin/which'

Do I need to clean up before doing this and start from scratch ?

**Comment by mxstbr** [comment]
That seems like a permissions issue from your end…

**Comment by yogitaAP** [comment]
Do I need to run npm install --save-dev cross-env  after npm run setup or instead of npm run setup. I checked the issue, it's an issue with the sym links in virtual machines and use of flag --no-bin-links solves that. I did all that, the dependency tree was formed but still cross-env:not found error is not resolved

**Comment by yogitaAP** [comment]
Attaching the screenshot here 
<img width="819" alt="screen shot 2016-06-12 at 8 15 09 pm" src="https://cloud.githubusercontent.com/assets/9781726/15991772/76a1b5ee-30da-11e6-93d0-022dfbfc341b.png">

**Comment by rog** [comment]
try `rm -rf node_modules`, then `npm install`, then `npm install --save-dev cross-env` and last: `npm run`
