### ISSUE TITLE
setup does not work

### ISSUE THREAD

**Issue by bcowgill** [mxstbr/react-boilerplate#544]
Following these instructions from the README
Quick start

Clone this repo using $ git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
Run $ npm run setup to install dependencies and clean the git repo.
At this point you can run $ npm start to see the example app at http://localhost:3000.
Run $ npm run clean to delete the example app.

I get an error:
git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
cd react-boilerplate/
npm run setup

> react-boilerplate@3.0.0 presetup /home/bcowgill/workspace/play/react-boilerplate
> npm i chalk

react-boilerplate@3.0.0 /home/bcowgill/workspace/play/react-boilerplate
└─┬ chalk@1.1.3
  ├── ansi-styles@2.2.1
  ├── escape-string-regexp@1.0.5
  ├─┬ has-ansi@2.0.0
  │ └── ansi-regex@2.0.0
  ├── strip-ansi@3.0.1
  └── supports-color@2.0.0

> react-boilerplate@3.0.0 setup /home/bcowgill/workspace/play/react-boilerplate
> node ./internals/scripts/setup.js

Cleaning old repository ✓
Installing dependencies.. ✓(This might take a while)Installing dependencies
Initialising new repository ✓

> react-boilerplate@3.0.0 postsetup /home/bcowgill/workspace/play/react-boilerplate
> npm run build:dll

> react-boilerplate@3.0.0 build:dll /home/bcowgill/workspace/play/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/bcowgill/workspace/play/react-boilerplate/internals/scripts/dependencies.js:8:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Linux 3.19.0-43-generic
npm ERR! argv "/home/bcowgill/.nvm/versions/node/v5.10.1/bin/node" "/home/bcowgill/.nvm/versions/node/v5.10.1/bin/npm" "run" "build:dll"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1 
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 build:dll script 'node ./internals/scripts/dependencies.js'.

If I try the normal thing of just running npm install, I get

npm install
npm ERR! Linux 3.19.0-43-generic
npm ERR! argv "/home/bcowgill/.nvm/versions/node/v5.10.1/bin/node" "/home/bcowgill/.nvm/versions/node/v5.10.1/bin/
npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! No compatible version found: webpack@2.1.0-beta.8
npm ERR! Valid install targets:
npm ERR! 2.1.0-beta.7, 2.1.0-beta.6, 2.1.0-beta.5,

**Comment by bcowgill** [comment]
Actually, looks like this was an issue with my local package cache.

**Comment by andrewkelley** [comment]
How did you fix this @bcowgill? Thanks!

**Comment by brycepj** [comment]
Yep, same thing here.

**Comment by gihrig** [comment]
Sounds like a possible npm cache problem. try `npm cache clean` then `npm install`.

**Comment by everythingspirals** [comment]
I have the same problem.

**Comment by gihrig** [comment]
@everythingspirals Did you run `npm cache clean` then `npm install`?

**Comment by ivnmaksimovic** [comment]
I had

`module.js:327
    throw err;`

Updatin npm version from 2.15.5 to 3.10.3 fixed the problem for me.

**Comment by skskumbharkar** [comment]
I am still facing this issue even after node-npm upgrade.

**Comment by gihrig** [comment]
@skskumbharkar Have you tried `npm cache clean`?
Setup is self-deleting (to prevent later disasters), if you have already run it once, you may need to git clone a new copy of the repo.

**Comment by skskumbharkar** [comment]
I just removed my all installed node_modules.
And then used "npm run setup".
It is working fine now.

**Comment by albertpak** [comment]
worked for me after upgrading to latest npm

**Comment by baldwindc** [comment]
Late to the party, but going off https://github.com/react-boilerplate/react-boilerplate/issues/544#issuecomment-230880439, why do people report success after updating npm / `npm clean cache`?

This happened to me after installing three.js via npm. I was able to repair by resetting package.json / package-lock.json to their default versions, `npm clean cache`, `npm install`, and `npm run start`.

I'm going to go back through the process of installing three.js and see if I can pinpoint what's causing it to break.
