### ISSUE TITLE
Running tests is too slow with karma

### ISSUE THREAD

**Issue by bcowgill** [mxstbr/react-boilerplate#545]
It takes 23 seconds to npm run test on the project as initially checked out. I have found karma to be a very slow test runner and have switched to mocha-webpack+mock-browser so that tests can be run without a browser at all. 

At the time my React karma/phantom or karma/chrome cycle was taking 60 seconds to run for a few hundred tests. After the change it took 6 seconds to run the whole thing. The best part though was the test:watch improvement as it only packs and runs the tests needed.

This is a huge improvement in red-green-refactor cycle time.  I found that karma-webpack was horribly slow on a watch change.

Do you have any plans to switch to this, or perhaps make it available as an option?

**Comment by Augustin82** [comment]
Would you mind detailing what you did? I'm very interested in that.

**Comment by mxstbr** [comment]
Feel free to submit a PR implementing this, would love to speed up the testing process! :+1:

**Comment by bcowgill** [comment]
I'd like to submit a PR but honestly won't have time soon, my home computer crashed so have a bit of restoring to do.

Having a look at my git log though:

package.json5 deltas:
"scripts": {
		"pretest": "npm run lint",
		"test": "mocha-webpack --webpack-config=config/webpack.config-test.js \
			--colors --growl \
			--require=source-map-support/register \
			--check-leaks --full-trace \
			'src/**/*.spec.js'",

		"pretest:watch": "npm run json5",
		"test:watch": "mocha-webpack --webpack-config=config/webpack.config-test.js \
			--watch --colors --growl \
			--require=source-map-support/register \
			--check-leaks --full-trace \
			'src/**/*.spec.js'",
}
dependencies: {
		"mock-browser": "^0.92.11",
}
devDependencies: {
		"mocha-webpack": "^0.3.0",
		"source-map-support": "^0.4.0",
		"webpack-node-externals": "^1.2.0"
}

config/webpack.config-test.js
var path = require('path')
    , myself = 'webpack.config-test.js'
    , DEBUG = false
    , log = console.log
    , nodeExternals = require('webpack-node-externals')
    , envSrcDir = 'npm_package_config_js_src'
    , envTestDir = 'npm_package_config_test_src'
    , srcDir = process.env[envSrcDir]
    , testDir = process.env[envTestDir]
    , relSrcDir = './' + srcDir
    , fullSrcDir = path.resolve(__dirname, '..', srcDir)
    , fullTestDir = path.resolve(__dirname, '..', testDir)

if (DEBUG) {
    log('__dirname:', __dirname)
    log('srcDir:', srcDir)
    log('relSrcDir:', relSrcDir)
    log('fullSrcDir:', fullSrcDir)
    log('fullTestDir:', fullTestDir)
}

module.exports = {
    devtool: 'cheap-module-source-map'
    , output: {
        // sourcemap support for IntelliJ/Webstorm
        devtoolModuleFilenameTemplate: '[absolute-resource-path]'
        , devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    }
    // in order to ignore built-in modules like path, fs, etc.
    , target: 'node'

    // in order to ignore all modules in node_modules folder
    , externals: [nodeExternals()]

    , module: {
        loaders: [
            {
                test: /\.js$/
                , loader: 'babel'
                , include: [fullSrcDir, fullTestDir]
            }
        ]
    }
}

Hope it helps.

**Comment by bsr203** [comment]
@bcowgill could you bale to use webpack [resolve.alias] with this setup. I have used alias to avoid relative paths and also to mock some imports during testing. Thanks in advance. (https://webpack.github.io/docs/configuration.html#resolve-alias)

**Comment by bcowgill** [comment]
my knowledge of webpack is slightly a bit above zero and I've not got time at the moment. I'm just converting an existing project to use react boilerplate and after that's done then will have a look into this.

**Comment by bsr203** [comment]
great news. I solved with the help of Markus, and adapting from his boilerplate 

see details.

https://github.com/Drathal/react-playground/issues/2

**Comment by jwyuen** [comment]
If anyone is curious as to an alternative approach with minimal changes to the boilerplate, this works for me:

```
sudo apt-get install xvfb
sudo apt-get install chromium-browser
```

Then replace test in package.json with something like:

```
export CHROME_BIN=/usr/bin/chromium-browser && xvfb-run -a cross-env NODE_ENV=test karma start internals/testing/karma.conf.js --single-run
```

**Comment by mxstbr** [comment]
No longer relevant now that we've switched to Jest in #980! Will be in the next release 👌

**Comment by jwyuen** [comment]
@mxstbr Maybe a dumb question but if we upgrade our react-boilerplate version to the latest one with jest, do we need to make any changes to our existing tests?

**Comment by mxstbr** [comment]
Only miniscule ones, see the changes in #980 – should be a simple find and replace!

**Comment by jwyuen** [comment]
Just wanted to say I recently upgraded to the newer 3.4 boilerplate which is using the Jest test setup and it's waaaaay faster than before.  Nice job!
