### ISSUE TITLE
Question: Code splitting in combination with containers that don't have their own route

### ISSUE THREAD

**Issue by SimonSelg** [mxstbr/react-boilerplate#547]
Hey,

I have a quick question on how we are meant to deal with containers that have their own reducers/sagas, but don't have their own route. 

Since reducers and sagas are loading async in routes `injectReducer` / `injectSagas` function, reducers and sagas of containers that don't have their own routes, but are used in components that do have their own routes don't get injected by default.

The boilerplate example app seems to solve this problem by just not using these kind of containers (ie all containers are routes), but that doesn't seem to scale very well, and makes redux less useful from my pov.

The only solution to this I see is to manually add the reducers from the 'subContainers' into the routes.js, like that:

```js
 {
      path: '/login',
      name: 'loginPage',
      getComponent (nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/LoginPage/reducer'),
          System.import('containers/LoginPage/sagas'),
          System.import('containers/LoginPage'),
          // load other reducers that are needed in this route
          System.import('containers/SomeContainer/reducer'),
          System.import('containers/OtherContainer/reducer')
        ])

        const renderRoute = loadModule(cb)

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('loginPage', reducer.default)
          injectReducer('someContainer', reducer.default)
          injectReducer('otherContainer', reducer.default)
          injectSagas(sagas.default)
          renderRoute(component)
        })

        importModules.catch(errorLoading)
      }
    },
``` 

Does somebody have a better way / structure do deal with this?

Cheers,
Simon

**Comment by datapimp** [comment]
Personally I think it is safe to load reducers / sagas etc synchronously from the `app/reducer.js` unless there's a strong reason not to

**Comment by Augustin82** [comment]
I'm interested in this issue, I believe it's similar to that one: https://github.com/mxstbr/react-boilerplate/issues/537

**Comment by SimonSelg** [comment]
@datapimp: But then you'd loose the benefits of code splitting, at least for the reducers and sagas.

**Comment by datapimp** [comment]
It depends on your reducer and saga code but my gut says not really, not in this case.  Unless you really don't want the reducer / saga code to make it to the client, the impact might only be very minor.  

This is because your saga and reducer implementation code is going to very small, and very likely won't import or require any modules that aren't already being depended on somewhere else in your app.  So I would say the trade off is worth it.  

You might send a little extra code to the client, but you can not worry about trying to figure out how to organize your code to handle exceptions like this.

Totally up to you though --  I would experiment with it and see.  I think as long as you're code splitting entry points for each of the different pages, you will enjoy most of the benefits of code splitting.  It really helps out when you have larger bundles of modules and code that aren't used unless somebody visits a specific page.

**Comment by justingreenberg** [comment]
there are very good reasons for using route definitions to create split points: 
 - we have access to instantiated store when building routes (for inject hooks)
 - we can hook into react-router's lazy `getComponent` to delegate async chunk loading to the router

**webpack (_compiler_)** - creates a chunk and registers module in asset manifest
**webpack (_runtime_)** - fetches registered chunks using inline jsonp client
**react-router** - route matching and async component api used to trigger webpack runtime loader
**redux store** - hooks on instantiated store used to inject reducers/sagas

i tend to agree with @datapimp that the benefits of code splitting are mostly realized in vendor deps... ie, you have a route `/charts` and you don't want to load the charting libs unless necessary. given your dependencies meet common chunking config, this should all work seamlessly with the current setup. 

if you need more functionality than this you may want to think a little bit more about your architecture... eg accessing hooks on instantiated store. you can always use parent route to inject reducer, then use componentDidMount lifecycle hook to create a split point and load deps...

```js
class Chart extends React.Component {
  componentDidMount() {
    System.import('BigChartLib').then(ChartLib =>
      //...
    )
  }
}
```

**Comment by datapimp** [comment]
@justingreenberg nice idea w/ the componentDidMount.  @SimonSelg if you need any help feel free to hit me up

**Comment by SimonSelg** [comment]
Thanks guys. The idea w/ componentDidMount is really nice!

**Comment by jcfergus** [comment]
Hi, all - I'm new to the React world, and have managed to get some basic pieces working in ReactBoilerPlate, but am running into challenges with the exact issue that's covered here, and unfortunately while @justingreenberg 's answer looks pretty much like exactly what I need, I'm too n00b (or possibly just too dense) to take the last leap from the example above to understanding what needs to replace the '//...' comment in the example.  Is there any chance someone could handhold a React/Redux n00b through the last little bit of getting a container without its own route to work in ReactBoilerPlate?

**Comment by vimniky** [comment]
Hey ! I have another problem with async reducer and sagas. Let's say we have two routers/pages: `Home` and `About` . How can I access sagas and the  portion state of `About`  router/page inside `Home` routers/gages (sagas and reducers of `About` router/page haven't loaded yet, so we don't have access to them). Actually in a real world app it quite common we want to do this.

**Comment by Augustin82** [comment]
If you need to access "stuff from About" from outside "About", I'd say it means it's not really "from About" and needs to be in the global part of your app.

**Comment by vimniky** [comment]
@Augustin82 I'm no sure it should be global part or not. Let's say I have a product page, and I want to show the counts of product.  The product related data definitely should goes into product page, and the product counts is computed from product data. In this case I don't think putting product related data info the global part of my app is a good choice.

**Comment by Marinolinderhof** [comment]
@vimniky @Augustin82 Yeah i have the same issue:

Parent saga:
/client/(:clientid) 
Then i have to do a dispatch on component did mount:
```
  componentWillMount() {
    this.props.updateRouterState({
      params: this.props.params,
    });
  }
```
I do this so i can have my params in my saga (and kick of the saga). 

and then i have a child container with path:
'/client/1/companies'

Here i need that same param in this child saga. 
but if i do something like getSelectorRoute it would fail because my component is not mount yet or worse the parent-saga is not loaded yet. 

So on container in my child  '/client/1/companies' i could componentDidMount this. But that doesn't feel right.

**Comment by arianbessonart** [comment]
> @Augustin82 I'm no sure if it should be global part or not. Let's say I have a product page, and I want to show the counts of product on Home page. The product related data definitely should goes into product page, and the product counts is computed from product data. In this case I don't think putting product related data into the global part of my app is a good choice.

@vimniky I'm having the same issue. I'm thinking about two options
- Move the product functionality (sagas, actions, reducer) to a common place, and not encapsulated on ProductPage container.
- Import saga, action, reducer form ProductPage container on routes.js

 How could you resolve this? What do you think is the best approach?

**Comment by danielo515** [comment]
Seems that this template has big problems with child routes, or at least I'm having lots of problems with child routes.
Currently, child routes don't work for me at all, I have to write absolute otherwise components are not mounted

**Comment by danielo515** [comment]
I am checking the branch 3.0 
Looks like you don't have support for nested forms (`Joi.object().keys({name:Joi.string(), age: Joi.number()})`)

**Comment by alzalabany** [comment]
```
const importModules = Promise.all([
          import('containers/HomePage'),
          import('containers/ProtectedApp/reducer'),//nested reducer that have no route
          import('containers/PublicApp/reducer'),//nested reducer that have no route
        ]);

        const renderRoute = loadModule(cb);

        importModules.then((mods) => {
          renderRoute(mods.shift()); //the first mod is a route
          mods.map(mod=>injectReducer(mod.name, mod.default)) // export const name = 'mounting_name'; on reducer
        });
```

this is how i solved nested problem

**Comment by siarheipashkevich** [comment]
@justingreenberg @datapimp [Your answers](http://joxi.ru/8AnxQlJsjQWqBm)
But how I can inject reducers and sagas in the componentDidMount method?
Could you please help me?
