### ISSUE TITLE
Routing example doesn't work

### ISSUE THREAD

**Issue by mattcreager** [mxstbr/react-boilerplate#548]
Maybe I'm doing something wrong here, but when I run your example I notice two things: Navigating to `/features` results in `not found` (the express response), and while clicking the features button takes you to the features page, navigating to `/#/features` doesn't take you anywhere.

**Comment by zanedev** [comment]
I'm seeing this behavior now after pulling in latest master changes to my project.  Not sure how to troubleshoot it.

**Comment by mattcreager** [comment]
Ya, the arguments on [L35](https://github.com/mxstbr/react-boilerplate/blob/master/server/middlewares/frontendMiddleware.js#L35) of `frontendMiddleware.js` are just backwards (`file`, `err` => `err`, `file`)

**Comment by zanedev** [comment]
Thanks @mattcreager that fixed it for me.  Strange the fs library chose the args to be in that order.  You want to submit a pull request or I can do it?

**Comment by mattcreager** [comment]
@zanedev if you don't mind 🙏.  

`fs` is a core module, and all of the core libraries are `err` firs :)

**Comment by zanedev** [comment]
ah good to know!  okay will do now np
