### ISSUE TITLE
Build does not work due to invalid paths

### ISSUE THREAD

**Issue by biznickman** [mxstbr/react-boilerplate#549]
Aside from adding `postcss-assets` and `postcss-inline-svg` I've made no changes to the default webpack files found with the react-boilerplate, however when I go to build, I can't load the files. The reason is that the paths being generated to files all start with a `/` rather than `./` or simply no slash at all resulting in path errors.

I can change the paths in the HTML but not in the javascript files themselves to attempt resolving this issue. Is there something that I'm missing here? 

The errors being spit out in the browser are: 

> Failed to load resource: net::ERR_FILE_NOT_FOUND file:///main.f0e1746a8b5bb1c19e331ecb9f56e29e.css
> Failed to load resource: net::ERR_FILE_NOT_FOUND file:///common.js.4a2082bf3b3167083075.js 
> Failed to load resource: net::ERR_FILE_NOT_FOUND file:///main.d757969f32a417a4028c.js
>

**Comment by datapimp** [comment]
are you using this in electron? why the file urls?

you can change the `output.publicPath` option in your webpack config in the mean time if you need file urls to work. 

to test builds locally I usually cd into the build dir and run `python -m SimpleHttpServer` which will open up a server on port 8000 for that folder

**Comment by biznickman** [comment]
@datapimp nope not in electron. I'm saying the URLs that show up in the index.html file. What would you change the `publicPath` option to? Running the app works but the build does not. The problem is it's appending a `/` to all the references which would be accurate if the site was in the root directory but it's not!

**Comment by datapimp** [comment]
@biznickman currently publicPath is set to '/' inside of `internals/webpack/webpack.base.babel.js`

```js
output: Object.assign({ // Compile into js/build.js
    path: path.resolve(process.cwd(), 'build'),
    publicPath: '/',
  }, options.output), // Merge with env dependent settings
}
```
Setting it to an empty string will give you the behavior you're looking for

See: http://webpack.github.io/docs/configuration.html#output-publicpath for more information

**Comment by biznickman** [comment]
@datapimp apparently changing it to './' made it work :) Good stuff! Now just to figure out how to make the links work without a server... Thanks!

**Comment by datapimp** [comment]
@biznickman check out the api docs for the history module

https://github.com/ReactJSTraining/history/tree/master/docs#readme

also you can use the hashHistory option instead of the browserHistory we use by default here

this will give you the `#/path/to/whatever` style URL which may be an option for you if you don't plan on using a server

**Comment by edmundtfy** [comment]
@datapimp just to confirm, I'm running into the same issue here. After `npm run build`, I cannot just open the index.html and expect it to work?
