### ISSUE TITLE
Adding your own custom backend-api is in the wrong place.

### ISSUE THREAD

**Issue by alikhani** [mxstbr/react-boilerplate#562]
Started with this boilerplate to try it out. 
Just a note that I noticed that could confuse someone, when trying to add an api in the project. This is not the place to add an api because app is undefined. see: https://github.com/mxstbr/react-boilerplate/blob/master/server/index.js#L13

It needs to be in the frontendMiddleware or maybe middlewares directory needs a index.js file to structure different middlewares?

My solution for playing around at the moment has been to add an api directory in middlewares and require in frontendMiddleware.js and add `app.use('/api', api);` here: https://github.com/mxstbr/react-boilerplate/blob/master/server/middlewares/frontendMiddleware.js#L64

**Comment by swordsreversed** [comment]
I've just had this exact problem, my first step in using this boilerplate was to set up and api so i could serve some data, and I ran into it as well. Would be good to hear from the author what the thoughts behind the code comment was, and where placement of the api is appropriate.

**Comment by SimonSelg** [comment]
Just had the same problem. Will submit a PR for it in a few minutes.

**Comment by eddiewang** [comment]
thanks for this - helped me setup my api.
