### ISSUE TITLE
When using the Redux DevTools extension in chrome i get an error 

### ISSUE THREAD

**Issue by Marinolinderhof** [mxstbr/react-boilerplate#564]
uncaught type error window.devtools.updatestore is not a function

![screen shot 2016-06-16 at 16 49 31](https://cloud.githubusercontent.com/assets/3657762/16121121/53230a36-33e2-11e6-8750-c34924b87e78.png)

It's a fresh git clone and then a npm start.

**Comment by suhaotian** [comment]
Did you check the devtools extension version was  2.0.1?

**Comment by suhaotian** [comment]
I think we need do this: 
```
if (window.devToolsExtension) {
  window.devToolsExtension.updateStore && window.devToolsExtension.updateStore(store);
}

```
**or**

```js

  window.devToolsExtension && window.devToolsExtension.updateStore && window.devToolsExtension.updateStore(store);

```

**Comment by Marinolinderhof** [comment]
I do have devtools extension version 2.0.1. 

i tried to debug it and your solution: ` window.devToolsExtension && window.devToolsExtension.updateStore && window.devToolsExtension.updateStore(store);` 
woulld work stop a error message. I think something went wrong in the setup phase (didn't install a module or so?). After a reinstall i worked like a charm. Thanks for helping out though.
