### ISSUE TITLE
add external js like d3.js

### ISSUE THREAD

**Issue by mde17** [mxstbr/react-boilerplate#568]
how to add external js files

**Comment by mde17** [comment]
just run npm install d3 --save

**Comment by akshayKrSingh** [comment]
what if it's a custom library not published on npm ?

**Comment by gihrig** [comment]
@akshayKrSingh Use the full path the library.

`npm install git+https://git@github.com/visionmedia/express.git --save`

Note that it must be a properly formatted npm module.

See [here](http://stackoverflow.com/a/17509764/522756) for more.
