### ISSUE TITLE
test bundler regex seems just wrong?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#569]
http://regexr.com/3dl6s

I think I'm missing something here..

**Comment by gihrig** [comment]
Is this more what you're looking for? http://regexr.com/3dl7n

Some related [discussion](http://stackoverflow.com/a/21448193/522756)

**Comment by FezVrasta** [comment]
No well the problem is that this is the regex used by https://github.com/mxstbr/react-boilerplate/blob/master/internals/testing/test-bundler.js#L12 (I've just added the optional jsx).

Btw I just got my coverage reports to work with istanbul-instrumenter-loader, I guess I'll send a PR with this change.

**Comment by mxstbr** [comment]
Hmm, this might've been changed acceidentally, does it still work?

**Comment by FezVrasta** [comment]
Yes but the coverage test includes the files that should be instead excluded

**Comment by mxstbr** [comment]
> Yes but the coverage test includes the files that should be instead excluded

Hmm, true. 

> Btw I just got my coverage reports to work with istanbul-instrumenter-loader, I guess I'll send a PR with this change.

That'd be ace :+1:

**Comment by mxstbr** [comment]
No longer relevant now that we've switched to Jest in #980! Will be in the next release 👌
