### ISSUE TITLE
Fetching initial state on the server

### ISSUE THREAD

**Issue by andrewmclagan** [mxstbr/react-boilerplate#570]
Im implementing a `storeMiddleware`  on the server. Its an express middleware, just to be clear.

This builds initial redux state by dispatching actions and so on. This is all working fine. Im stuck with how to inject the initial state data into the `index.html` file on the server. The problem is `index.html` is rendered with webpack and during production that step has already completed. I could just inject it directly into the HTML file with node, although that seems wrong for some reason?

(PS im using thunk and a different architecture)

So far my middleware looks like this:

````
import cookieParser from 'cookie-parser';
import browserHistory from 'react-router';
import createStore from 'redux/create';
import { api } from 'library/api';
import { fetchInitialState } from 'redux/modules/app';
import { addToken } from 'redux/modules/auth/auth';

/**
 * Returns token from request cookie if present
 *
 * @return Object
 */
function authTokenFromRequest(request) {
  return request.cookies._token ? request.cookies._token : '';
}

/**
 * Store middleware - fetches initial application state from API server
 *
 * @author Andrew McLagan <andrew@ethicaljobs.com.au>
 */
module.exports = (server, options) => {

  server.use(cookieParser());

  server.get('*', (request, response) => {
    
    const store = createStore(browserHistory, api);

    const token = authTokenFromRequest(request);

    store.dispatch(addToken(token)); // add token to store

    store.dispatch(fetchInitialState())
      .catch(error => console.log('>> Error fetching initialState: ', error))
      .then(() => {
        const initialState = store.getState();
        console.log(initialState);
      });
  });
};

````

Any suggestions, is anyone interested in this as a PR?

**Comment by tzarger** [comment]
@andrewmclagan Yes, interested. Will take a peek, although I am not sure I will come up with the answer as I have just started looking into this boilerplates since you mentioned it elsewhere.

**Comment by mxstbr** [comment]
Not quite sure I'm following – how does this relate to/overlap with #174?

**Comment by mxstbr** [comment]
Closing this due to little interest.
