### ISSUE TITLE
Can't get basic generated saga to run

### ISSUE THREAD

**Issue by swordsreversed** [mxstbr/react-boilerplate#575]
For the life of me I can't figure out why this basic saga won't run:

```
import { take, call, put, select } from 'redux-saga/effects';
import { TEST } from './constants';

function* workDammit() {
  while (yield take('TEST')) {
    console.log('nope');
  }
}

function* thisWorks() {
  console.log('works');
}


// All sagas to be loaded
export default [
  workDammit,
  thisWorks
];
```

constants.js
```
 export const TEST = 'boilerplate/Podcasts/TEST';

```

actions.js
```
import {
  TEST,
} from './constants';

export function doTest() {
  console.log('do test fired');
  return {
    type: TEST,
  };
}
```

The action is dispatched and the console.log fires in the action creator. The thisWorks triggers as expected. I took the quote marks off the name of the constant but that didn't do anything (i've seen examples with quotes and no quotes). The files were created using the generator so the sagas are loaded etc.

   ¯\\_(ツ)_/¯

**Comment by justingreenberg** [comment]
take has to reference imported constant... `yield take('TEST')` should be `yield take(TEST)`

**Comment by swordsreversed** [comment]
Hi Justin, thanks for the reply. 

As I said I did try without quotes originally. I added the quotes after reviewing the official docs:

```
/*
  Starts fetchUser on each dispatched `USER_FETCH_REQUESTED` action.
  Allows concurrent fetches of user.
*/
function* mySaga() {
  yield* takeEvery("USER_FETCH_REQUESTED", fetchUser);
}
```

from http://yelouafi.github.io/redux-saga/index.html

**Comment by justingreenberg** [comment]
so if you remove the quotes as i described, the code in your OP will work as expected...

try dispatching `doAction` from inside your component, eg..

```js
<Button onClick={() => this.props.dispatch(doTest())}>doTest</Button>
```

passing a `take` effect to while loop suspends execution until a matching action type flows thru store... since we're just creating a watcher, nothing will happen until the action is dispatched

hope this helps :)

**Comment by swordsreversed** [comment]
Ah ok, i had a mistake in my mapDispatchToProps. I was using the erikras boilerplate which abstracted that away with @asyncConnect, so I didn't really understand what was going on. Have now read the docs. Thanks @justingreenberg!
