### ISSUE TITLE
mapDispatchToProps creating a Uncaught TypeError: __webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by eddiewang** [mxstbr/react-boilerplate#576]
Trying to isolate the reason for this error,
trying to dispatch an action which will then be hooked by a saga, but it's failing and logging this error when I try to call the function.

**Comment by eddiewang** [comment]
fixed issue - not related to this boilerplate.

**Comment by spdaly** [comment]
@eddiewang I'm running into the same error message.  I know that it's not related to the this repo, but can you provided details on how you fixed it?

**Comment by eddiewang** [comment]
@spdaly hi, it usually has to do with the template or saga. probably a typo. the error message isn't very clear on that. if you send me the code i'll take a look for you!

**Comment by spdaly** [comment]
@eddiewang I cloned your fork to compare the code.  I think I found the problem.  I'll post if it continues to be an issue.

**Comment by spdaly** [comment]
Here's the error message:

```
utils.js:188uncaught at rootSaga 
 at setWatcher 
 TypeError: __webpack_require__.i(...) is not a function
```

And the source code:
```
import { take, takeEvery, call, fork, cancel, put } from 'redux-saga/effects';
import { LOCATION_CHANGE } from 'react-router-redux';
import { GET_DOCUMENTS } from './constants';
import { getDocumentsSuccess, getDocumentsError } from './actions';
import * as firebaseRef from 'firebase-saga';

export function* getDocuments() {
  const documents = yield call(firebaseRef.get, 'documents');

  if (!documents.err) {
    yield put(getDocumentsSuccess(documents.data.results));
  } else {
    yield put(getDocumentsError(documents.err));
  }
}

export function* setWatcher() {
  while (yield takeEvery(GET_DOCUMENTS)) {
    yield call(getDocuments);
  }
}

export function* rootSaga() {
  const watcher = yield fork(setWatcher);
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

export default [
  rootSaga,
];
```

**Comment by eddiewang** [comment]
@spdaly check for typos... that's what mine ended up being. the webpack require isn't a very clear error. if you upload your code or add me i can pull and see if i can fix it for you.

**Comment by spdaly** [comment]
Agree. I ended up using the generator to create a new container and copied code over. I'm still learning this whole stack so I'm sure that I fat fingered something somewhere.

Thanks for your time in commenting/reviewing.

I cloned your Tinder app to look at that code. #ThatTimeWhenCodeCanEffectYourMarriage. ;)

**Comment by eddiewang** [comment]
@spdaly - haha I never ended up finishing that. funny enough, my girlfriend wants me to finish that app more than I do. send me a follow, I'll make a note to update you when (and if) it ever gets complete! hope you fix all your bugs.

**Comment by villesau** [comment]
@spdaly you import your takeEvery from a wrong place. try import { takeEvery } from 'redux-saga'; instead of import { takeEvery } from 'redux-saga/effects';

takeEvery is not in effects but in the main package instead :)
