### ISSUE TITLE
Error during 'npm run build:dll'

### ISSUE THREAD

**Issue by tengis** [mxstbr/react-boilerplate#578]
Hi there,

When trying to first run project this error occurred.

- node - 6.2.2
- npm - 3.9.4
- OS - EL Captain 

Error:
`.../react-boilerplate/node_modules/babel-preset-es2015-webpack/index.js:38
    throw new Error('Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.');`

I think this line returns wrong module
https://github.com/gajus/babel-preset-es2015-webpack/blob/master/index.js#L10

so at that line throws error 
https://github.com/gajus/babel-preset-es2015-webpack/blob/master/index.js#L34

When i comment those lines everything works fine.
https://github.com/gajus/babel-preset-es2015-webpack/blob/master/index.js#L8-L13

**Comment by mxstbr** [comment]
@datapimp any ideas?

**Comment by tengis** [comment]
Hi i found the answer. 

this line loading my global module instead of local.
https://github.com/gajus/babel-preset-es2015-webpack/blob/master/index.js#L10

this helped me identify what the problem was 
`require.resolve('babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs')`
