### ISSUE TITLE
manifest.json invalid

### ISSUE THREAD

**Issue by bnhovde** [mxstbr/react-boilerplate#580]
Hi,

First of all, thanks for all the hard work that's gone into this.

After doing a build (clean install), the `manifest.json` file appears to be wrapped as a module:

```
module.exports = {
	"name": "React Boilerplate",
	"icons": [
        ...
```

This in turn causes errors with the chrome devtools, and the app doesn't get recognised as a PWA:

![Screenshot of devtools](https://bardhovde.com/share/pwa-example.png)

PS: I'm not an webpack expert, so I might be missing something.

**Comment by gaboesquivel** [comment]
yes, that needs to be plain old json https://developer.mozilla.org/en-US/docs/Web/Manifest
the `module.exports =` part can be removed.  leaving a valid json file.
to import the json file elsewhere in the app there's a webpack loader for that [json-loader](https://github.com/webpack/json-loader)

**Comment by mxstbr** [comment]
Ahh, good catch, this is a bug! Would you mind submitting a PR fixing this? Thanks!

**Comment by bnhovde** [comment]
As far as I can tell, `json-loader` is already in place and doing what it's supposed to, namely wrap a JSON file as a module. Looking at [the source code](https://github.com/webpack/json-loader/blob/master/index.js#L9), that's literally most of what it does:

```
return "module.exports = " + JSON.stringify(value, undefined, "\t") + ";";
```

Removing `json-loader` completely seems to remove the issue, importing the JSON file in it's original state with no transforms. I assume this is because `file-loader` is taking over?

I think the solution to this problem is removing json-loader completely, unless it's needed for any other reason?

**Comment by mxstbr** [comment]
Ahh, no what we should do is import the `manifest.json` file with the file loader: `import ‘file-loader?manifest.json` :+1:

**Comment by bnhovde** [comment]
Ah! I think I just realised what's happening. We're already using `file-loader` like you suggest, but the `json-loader` is still picking up the .json extension and processing the file because it's defined in the global loaders.

By adding `!` in front of the file-loader statement we can tell webpack to explicitly use the file-loader only:
```
import '!file?name=[name].[ext]!./manifest.json';
```

This fixes the problem. I'm just creating a pull request now.

**Comment by gaboesquivel** [comment]
👍

**Comment by mxstbr** [comment]
Thanks @bnhovde, good catch! :fire:

**Comment by bnhovde** [comment]
No probs, happy to help. Keep up the good work! ✌️
