### ISSUE TITLE
Creating a global styles folder (improvement)

### ISSUE THREAD

**Issue by eddiewang** [mxstbr/react-boilerplate#583]
Hi,

I recently was able to setup a global styles folder, which I think could work really well. There are alot of merits of PostCSS (specifically modules), but writing in sass is really nice as well.
1. Bourbon and other mixin libraries
   This provides important useful tools to quickly write out some functions. For example, I can use rem(40) to convert 40px into rem. 
2. Global variables
   PostCSS lacks global variables which can be solved by some solutions using a config.js file where you store variables. I'm don't believe storing styles in JS is the right approach. Rather, there should be a global folder with the variables, fonts, layout (SMACCS without the M).

Proposed Solution:
We should create a global folder called styles in the app directory with any global stylesheets. They can include variables, common styles, etc. Then we should use sass-loader to import those in. sass-loader allows us to preconfigure the path, so in stylesheets, we can selectively import files we need:
`@import 'styles/colors';`

**Comment by zanedev** [comment]
+1

**Comment by yookore** [comment]
+1 
I was about to ask a question around this when I saw the post. If I want to use something like BootStrap to provide global styling, where do I place it within the app structure so that its available in dev mode?

**Comment by mxstbr** [comment]
Have you read the discussions about this in #32 and #27?

----

Sass doesn't really offer many benefits, (if any at all) and doesn't solve the real problems with CSS _at scale_ that we're trying to address, namely naming collisions and inheritance. (See [my talk at AtTheFrontend](https://vimeo.com/168648012#t=10m20s) for an in-depth explanation of the issues we're solving, which Sass doesn't help with at all. Should the timestamped link not work, the comments about CSS start at ~10:20)

I don't think including the sass-loader by default makes much sense, what can Sass do that PostCSS can't? If you _need_ bourbon or something like that you can include the `sass-loader` anyway and make it work.

If you want variables-in-css, you can always use `postcss-simple-vars` without any problem too.

> a global folder with the variables, fonts, layout

Why do we need an extra folder for a file with variables? Not sure I understand the benefit here.

*@yookore that question is answered here #238*

**Comment by eddiewang** [comment]
@mxstbr I think the points you made are valid. How about just setting up postcss-simple-vars and create a global config file somewhere? I think it makes alot of sense to have at least global variables easily accessible. Wouldn't know any app that doesn't use common elements.

**Comment by mxstbr** [comment]
> How about just setting up postcss-simple-vars and create a global config file somewhere?

Yeah absolutely, having that in the boilerplate by default sounds reasonable!

The thing is, if we use `cssnext` and use the variables-in-js approach, we can share those constants between our JavaScript and our CSS code, which might be useful for theming etc. What's the benefit of `postcss-simple-vars`?

**Comment by eddiewang** [comment]
@mxstbr maybe we don't need the postcss-simple-vars package then. what's the approach in using cssnext? I've looked through the documentation and couldn't find anything useful in how one would make variables global.

**Comment by eddiewang** [comment]
be more than happy to document on how to setup that up - if given the right path. not having an easy way to define colors, custom media queries, default z-indexes, and fonts is a pain :-1:

**Comment by mxstbr** [comment]
@webdesserts set it up for the `react-boilerplate-site`, should've linked to that earlier!

See [`webpack.dev.babel.js:40`](https://github.com/mxstbr/react-boilerplate-site/blob/12da9df5e2aabc0d8511489b50e2097ce9341873/internals/webpack/webpack.dev.babel.js#L40-L42) and the referenced file in [`app/css-config.js`](https://github.com/mxstbr/react-boilerplate-site/blob/12da9df5e2aabc0d8511489b50e2097ce9341873/app/css-config.js) there :+1:

**Comment by feimosi** [comment]
@mxstbr That seems to be a satisfying solution for me. Although there's one issue with that, how can I make webpack autoreload on `css-config.js` change?

**Comment by kopax** [comment]
@mxstbr, I have tried to add the configuration has in [webpack.dev.babel.js](https://github.com/mxstbr/react-boilerplate-site/blob/12da9df5e2aabc0d8511489b50e2097ce9341873/internals/webpack/webpack.dev.babel.js#L40-L42), but the variable doesn't get replace in my css.
How should we use them ? I don't see any reading from these values in the project aswell.

**Comment by mxstbr** [comment]
This will be irrelevant with the inclusion of `styled-components`, since then it's all just JavaScript. Closed in favor of #1100
