### ISSUE TITLE
Page hangs when accessing a generated route / container.

### ISSUE THREAD

**Issue by bluespore** [mxstbr/react-boilerplate#584]
1. `npm run generate` -> Container (Yes to everything) **UserAuthPage**
2. `npm run generate` -> Route (`/login`) **UserAuthPage**
3. Navigate to `http://localhost:3000/login`
4. Page hangs, becomes unresponsive.

**Comment by mxstbr** [comment]
Must be something on your side, I just did those exact steps locally on an up-to-date `master` and it worked perfectly fine:

![screen shot 2016-06-21 at 08 58 31](https://cloud.githubusercontent.com/assets/7525670/16220643/58cab13c-378e-11e6-9c27-7a7d2a8aedf7.png)

Only did `$ npm start` here and went to `localhost:3000/login`:

<img width="1392" alt="screen shot 2016-06-21 at 08 57 19" src="https://cloud.githubusercontent.com/assets/7525670/16220627/42f3d3b6-378e-11e6-8a83-2a70d4ece019.png">

**Comment by bluespore** [comment]
@mxstbr I get asked more than one question when I run the container generator, which may indicate a version difference?

```? [CONTAINER] What should it be called? UserAuthPage
? [CONTAINER] Does it have styling? Yes
? [CONTAINER] Do you want an actions/constants/selectors/reducer tupel for this container? Yes
? [CONTAINER] Do you want sagas for asynchronous flows? (e.g. fetching data) Yes```

**Comment by mxstbr** [comment]
I got asked the same questions, for some reason they don't show up in the screenshot above (possibly a bug), but as you can see the files were generated!
