### ISSUE TITLE
Containers without their own routes.

### ISSUE THREAD

**Issue by jcfergus** [mxstbr/react-boilerplate#585]
I'm new to the React world, and have managed to get some basic pieces working in ReactBoilerPlate, but am running into challenges with the exact issue that was covered in #547 , but unfortunately while @justingreenberg 's answer looks pretty much like exactly what I need, I'm apparently too dense to take the last leap from the example above to understanding what needs to replace the '//...' comment in the example. 

Is there any chance someone could handhold a React/Redux n00b through the last little bit of getting a container without its own route to load and work correctly in ReactBoilerPlate?  It seems like the main issue is that the reducers aren't getting loaded if there's no route associated with the container.

**Comment by mxstbr** [comment]
See the changes in #587, I just added documentation about this! :+1:

**Comment by jcfergus** [comment]
Awesome, thanks!
