### ISSUE TITLE
Caching and HMR problems from base project

### ISSUE THREAD

**Issue by a-type** [mxstbr/react-boilerplate#590]
I've been trying to start a new project based off this boilerplate since it incorporates a lot of technologies I'm interested in learning, like CSS modules and redux-saga. However, I'm having some issues out of the gate. To clarify: I'm reproducing this locally by cloning the latest version of the repo to date, running `npm run setup`, and `npm start`.

**webpack dev middleware doesn't seem to want to load `common.js`**

I get the feeling this is an error in my local environment somewhere, but it's worth mentioning to see if anyone has a solution. When I start the server and load up `localhost:3000`, I get an `Unexpected token <` error on `common.js`. Looking at the network tab, I see that `common.js` was a `200` (not cached, presumably), but did indeed serve up HTML. It's not quite the same as the page itself; it includes another `data-dll` script, `reactBoilerplateDeps.dll.js`, which I'm not sure of the purpose of. I also notice in the network tab that the page was loaded from a `ServiceWorker`... I've never seen that behavior before.

I can resolve this issue by performing a 'Hard Reload' (I already have cache disabled in dev tools; this seems to make no difference and no requests appear to be cached).

I just checked, this happens specifically in Chrome (not FF). Could be a Chrome bug? I'm running Ubuntu 16.04 LTS, Chrome 51.0.2704.103.

**HMR does not work correctly**

This is the more disruptive issue, although it's possible it's related to the first one. HMR doesn't seem to work at all. If I change any JSX or CSS, I get the same webpack error, `[HMR] The following modules couldn't be hot updated: (Full reload needed) This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves ...`.

HMR appears to not work in either FF or Chrome, same messages.

Side note in hope that it may be of use: `sw.js` fails to load with `ERR_INSECURE_RESPONSE` consistently after a few seconds each time. I also get an `offline-plugin` warning, but I assume this is intentional since the `OfflinePlugin` isn't loaded in the dev webpack config.

Let me know if the details aren't clear enough.

**Comment by gihrig** [comment]
@a-type Hi Grant, did you try running the example app?
1. Clone the repo
2. `npm install`
3. `npm start`
4. Open `localhost:3000`

If that fails, what do you get when you run `npm test`?

In my experience, npm run setup leaves the project in a very incomplete state. There appear to be no concrete instructions yet on how to develop an app after npm run setup.

I have been more successful making copies of existing components and containers and modifying them to create new pages. The clean, highly modular architecture makes that easy. 

For example, 
1. Copy the `containers/HomePage` folder
2. Search and replace to create an new page.
3. Create route to your new page with `npm run generate route`
4. When the above works, continue modifying as needed.

In my experience, until you become more familiar with the project it's better not to `npm run generate` new components or containers. 

> HMR does not work correctly

I have found HRM to be 'quirky' in Chrome (Mac) but it's usable. Let's get you working with the example app and take it from there.

Welcome, -Glen

**Comment by a-type** [comment]
Thanks for replying @gihrig 

All the issues I listed occurred while attempting to run the example app with the steps you listed. Tests all pass. I've made no modifications at all to the repo.

**Comment by a-type** [comment]
For reference, I have already worked on a few projects with React/Redux/HMR, and they all work correctly with the same setup and environment.

**Comment by gihrig** [comment]
> HMR appears to not work in either FF or Chrome, same messages.

@a-type here's something else to try in case you haven't. My experience with 'quirky HMR' is related to the project's offline-first configuration. This gets established when you load the page in production mode `npm start:production`, and to some degree even in development mode. As far as I can tell this data is never removed. I was even able to shutdown the server and access the app, just as advertized.

To clear cached data out of Chrome (51 Mac OS):
1. Open developer tools
2. Select `Resources`
3. Select and clear all data under `Session Storage`, `Application Cache`, `Cache Storage` and `Service Workers`
4. Close the tab (don't know why but it seems to be necessary sometimes)
5. Open `localhost:3000`

I don't use Firefox much, but for me, HMR has always worked as expected in FF.

**Comment by a-type** [comment]
Interesting... the service worker was from the app which I had previously begun to build off of react-boilerplate before circling back and trying to reproduce this issue with the default example app. Deleting the service workers seems to have fixed the initial load issue. HMR still isn't working, though.

I think the next step for me might be removing all of the offline configuration from webpack. I don't think that feature is a high priority for me.

**Comment by gihrig** [comment]
Glad you're making progress.

Re:
```
HMR appears to not work in either FF or Chrome, same messages.

Side note in hope that it may be of use: sw.js fails to load with ERR_INSECURE_RESPONSE consistently after a few seconds each time.
```

I get that same message in the browser console every so often. I presume this will go away when the production mode project is loaded on a server that supports https, but I haven't gotten that far. Doesn't seem to affect HMR though.

**Comment by mxstbr** [comment]
> Deleting the service workers seems to have fixed the initial load issue. HMR still isn't working, though.

What kind of components are you changing?

Currently, **stateless function components cannot be hot reloaded**, only ES6 `class` or `React.createClass` components can. This is a downside of the current way HMR works and nothing we can fix, though there is work being done to change this!

**Comment by a-type** [comment]
Hi @mxstbr, I'm not using function components. I'm currently reproducing this with only the example application from this repo, no changes or custom components whatsoever. I have tried modifying the App container JSX and CSS, but HMR always claims that these modules do not know how to reload themselves.

**Comment by gihrig** [comment]
@a-type I see the same HMR failure with containers/App - this is a stateless function component as @mxstbr pointed out, HMR failure is expected.

Do you see the expected HMR on containers/HomePage, for example?

If so, and you want HMR for App, you could:

a) Make App an ES6 class component, as @jasoncyu linked above. Here's App specific code:
```javascript
/* eslint-disable react/prefer-stateless-function */
class App extends React.Component {
  render() {
    return (
    <div className={styles.wrapper}>
      <A className={styles.logoWrapper} href="https://twitter.com/mxstbr">
        <Img className={styles.logo} src={Banner} alt="react-boilerplate - Logo" />
      </A>
      {this.props.children}
      <Footer />
    </div>
  );
}
```
Or
b) Remove the visible components (the header) from containers/App and place those in their own components/Header. This is desirable if you have an app that doesn't need/want the same header components on every page.

**Comment by a-type** [comment]
Oh, wow, @gihrig, I feel very silly now! You're right, the HMR failure is expected. I hadn't realized that the functional-component rule would also apply to the CSS of the component, because I'm so used to working with independent SASS stylesheets which wouldn't depend on the component they're applied to. I imagine that using CSS modules makes the style reloading for App dependent on the App component itself, which cannot be reloaded.

Thanks for all your help, I'm glad I understand the source of the problem now, even though it was on my end (sorry!).

Can be closed as a non-issue.

**Comment by mxstbr** [comment]
Thanks @gihrig for helping resolve this, glad everything is clear now @a-type!
