### ISSUE TITLE
Docs state that sanitize.css is a PostCSS plugin

### ISSUE THREAD

**Issue by sotayamashita** [mxstbr/react-boilerplate#593]
In original docs is below: 

> Sanitize.css is a PostCSS plugin that makes browsers render elements more in ...

But I think sanitize.css is NOT PostCSS plugin so you should fix like that:

```diff
- Sanitize.css is a PostCSS plugin that makes browsers render elements more in ...
+ Sanitize.css makes browsers render elements more in ...
```

**Comment by mxstbr** [comment]
You're right, it isn't! Good catch! Would you mind submitting a PR that fixes this? Thanks!

**Comment by sotayamashita** [comment]
@mxstbr sure

**Comment by mxstbr** [comment]
Thanks @sotayamashita!
