### ISSUE TITLE
Using react-flexbox-grid

### ISSUE THREAD

**Issue by suren1525** [mxstbr/react-boilerplate#595]
Could someone help me using react-flexbox-grid (https://github.com/roylee0704/react-flexbox-grid) ?

In readme:

You should configure webpack to load flexboxgrid with CSS Modules, otherwise components from react-flexbox-grid will just have empty class names:
{
  test: /\.css$/,
  loader: 'style!css?modules',
  include: /flexboxgrid/,
}
If you have another loader which affects flexboxgrid, exclude it from that loader:

{
  test: /\.css$/,
  loader: 'style!css!postcss',
  include: path.join(__dirname, 'node_modules'), // this also includes flexboxgrid
  exclude: /flexboxgrid/, // so we are excluding it
}

Where I should do this changes?
build:dll gets an error:
Module parse failed: ... node_modules\flexboxgrid\dist\flexboxgrid.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by tzarger** [comment]
@suren1525 not sure if this is the best practice for this boilerplate, but this seems to work for me:

{
  test: /\.css$/,
  include: /node_modules/,
  loaders: ['style-loader', 'css-loader'],
  exclude: /flexboxgrid/,
}, {
  test: /\.css$/,
  loader: 'style!css?modules',
  include: /flexboxgrid/,
}

**Comment by suren1525** [comment]
I'm also not sure, that this is the best one.
I need responsive grid layout and I continue searching and trying. 
I made this changes in webpack.base.babel.js, but the changes don't take effect on build:dll :(
Thanks

**Comment by tzarger** [comment]
@suren1525 Sorry, I forget about the build.dll .. in webpack.dll.babel.js I also added modules, here is my exports:

module.exports = {
  context: process.cwd(),
  entry: dllConfig.dlls ? dllConfig.dlls : dllPlugin.entry(pkg),
  devtool: 'eval',
  output: {
    filename: '[name].dll.js',
    path: outputPath,
    library: '[name]',
  },
  module: {
    loaders: [{
      test: /\.css$/,
      loader: 'style!css?modules',
      include: /flexboxgrid/,
    }],
  },
  plugins: [
    new webpack.DllPlugin({ name: '[name]', path: join(outputPath, '[name].json') }), // eslint-disable-line no-new
  ],
};

Hope that helps.

**Comment by suren1525** [comment]
@tzarger  It works.
Thank you very much!!!

**Comment by arjshiv** [comment]
Thanks, this was helpful to me too

**Comment by RobertSheaO** [comment]
This helped me too, here's the part I used from tzarger's response.

webpack.dll.babel.js
```
module: {
  loaders: [{
    test: /.css$/,
    loader: 'style!css?modules',
    include: /flexboxgrid/,
  }],
}
```
