### ISSUE TITLE
Change output DIR and name

### ISSUE THREAD

**Issue by joneslloyd** [mxstbr/react-boilerplate#596]
Hi there,

Is there are way to change the output directory and filename for the app?

I'm trying to use it as part of a WordPress plugin, and want to standardise filenames

**Comment by mxstbr** [comment]
I think what you're looking for is in `internals/webpack/webpack.base.babel.js`, specifically the `output` property. :+1:

**Comment by joneslloyd** [comment]
Perfect, thanks!
