### ISSUE TITLE
Multiple issues on Windows

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#599]
I've tried to upgrade my version of the boilerplate (pre-release v3.0.0) to the latest version. I've done this by cloning this repo, running `npm run setup` and then tried to run `npm run clean`. This is where the first issue appeared:

> Cleanup started... ✓'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> child_process.js:507
>    throw err;
>

Ignoring this, I manually deleted the demo app contents and replaced them with my own modules and dependencies. I've also changed the `routes.js` and `app.js` to mirror the changes made. Now when I run `npm start` the server gets started - but the webpack build runs ad infinitum whith 20% processor usage and never finishes. I don't know what causes this, and any help would be appreciated. I have my code hosted on bitbucket, so if anyone is willing to help me I will happily provide access to the repo for analysis.

**Comment by maxmantz** [comment]
This is the full error log shown in the command line when running `npm run clean`:
[test-config.txt](https://github.com/mxstbr/react-boilerplate/files/332285/test-config.txt)

I suppose it is a pathing issue with git being under Program Files(x86) and the " " cutting off the command to call git. Still don't know why the infinite build occurs. When I load the sample app, everything works fine. I have checked the files again, trying to find issues but couldn't come up with anything...

**Comment by mxstbr** [comment]
I sadly don't have a Windows machine, so I can't replicate this… @jwinn any input here?

**Comment by jwinn** [comment]
I tried to replicate this on Windows 10 to no avail. Perhaps it's environment or permission specific.

Steps I performed:
```
mkdir C:\Projekte
cd C:\Projekte
git clone https://github.com/mxstbr/react-boilerplate test
cd test
npm run setup
npm test
npm start
npm run clean
npm start
```

My node, npm, and git are at the following:
```
C:\Users\jwinn>where node
C:\Program Files\nodejs\node.exe

C:\Users\jwinn>where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd

C:\Users\jwinn>where git
C:\Program Files\Git\cmd\git.exe

C:\Users\jwinn>systeminfo

Host Name:                 WINX
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

Note: Used Chocolatey to install node and git and ran the commands in powershell.
I hope this helps. :-)

**Comment by maxmantz** [comment]
Hi @jwinn and thank you for your time. There was a second git.exe in my PATH which caused the error. This is fixed now.

For the infinite build - I've let the last build run for 72 hours over the weekend with no change. I've made another attempt at reproducing the issue. 

I've now moved all my sagas & selectors with their components (`sagas.js` & `selectors.js` - just as in the example app). This works now by bootstrapping the sagas on my own. The only thing missing now from my previous configuration is the code-splitting of these sagas (`utils/hooks.js` & the change of `routes.js` to introduce sagas). This is something I would very much like to still implement. Do you know which PR(s) I need to look at only the code changes required for saga-splitting?

**Comment by mxstbr** [comment]
I think you're looking for #299 and #322?

**Comment by maxmantz** [comment]
I've adapted the changes from both PRs and ran into the same infinite build error. Can't find the issue with the files. I guess it's something within my existing code which causes the error. I've reverted to my version without code splitting. I'll close this now and come back to it when I find the time. Thank you for your help.

**Comment by jlkalberer** [comment]
I'm seeing this as well on a clean pull of the project. I'm wondering if this has something to do with it? --https://github.com/nodejs/node/issues/7367

**Comment by jlkalberer** [comment]
Actually, I found a good workaround.  If you are on windows you need to uninstall/reinstall node and git.  Just put the install folder in something like `C:\tools` or a path without a space.

**Comment by maxmantz** [comment]
Thank you for your suggestions. The issue I'm facing is probably related to my code. The sample app works fine and compiles well, but when I replace it with my existing code it runs into the infinite build error. I'm using nodejs & git in their standard install path, as well as using a command line with administrator rights. Nevertheless, if you find a fix to your issue I'd be happy to know about it to see if it indeed fixes my problem as well. Cheers!
