### ISSUE TITLE
Split code by top routes only?

### ISSUE THREAD

**Issue by FezVrasta** [mxstbr/react-boilerplate#601]
Right now I have these:

```
/home
/settings
/settings/a
/settings/b
/settings/c
```

Every time I change page, a different chunk is downloaded.

I'd like to reduce the number of chunks to just one for each of the top routes. So, one for `home` and one for `settings`.

Is it possible?

**Comment by mxstbr** [comment]
Yeah definitely, but it depends on how `/settings/:secondLevel` is structured/how they work, there isn't really a general answer to this.

You could use composed reducers (see the FAQ about containers without routes), or add a lower level `reducers.js` file in `settings` which combines the further up reducers and exports the sagas, etc.

Does that answer your question?

**Comment by FezVrasta** [comment]
I don't think I get it..

This is an example route with sub-route:

```js
    {
      path: '/settings',
      indexRoute: { onEnter: (nextState, replace) => replace('/settings/user') },
      getComponent(location, cb) {
        const importModules = Promise.all([
          System.import('app/containers/Settings/reducer'),
          System.import('app/containers/Settings'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([
          settings,
          component,
        ]) => {
          injectReducer('settings', settings.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },

      childRoutes: [
        {
          path: 'user',
          getComponent(location, cb) {
            System.import('app/pages/Settings/pages/User')
              .then(loadModule(cb))
              .catch(errorLoading);
          },
        },
```

As you can see, the child route does a `System.import`, that Webpacks will then try to split if possible (if I understood it correctly).

I should move that `System.import` inside its top route to avoid the code splitting I guess? But then how can I access the component and render it in the child route?

Thanks.

**Comment by mxstbr** [comment]
Ah yeah, didn't think of the components. 😅 

Good question, to be honest I have no idea how one would go about doing that. @timdorr any pointers?

**Comment by timdorr** [comment]
Only do your `getComponent`'s where you want to have split points. I haven't hopped on the `System.import` hype-train yet, but if it's like `require.ensure` you should only need to use it for when you want to create a new chunk. Otherwise, just import your components like any other module and statically reference them as the `component` for each route.

(BTW, Router 3.0 is going to make this a *lot* clearer)

**Comment by mxstbr** [comment]
The thing is that we want to code split the child routes with the higher-up routes. e.g. load `settings/a`, `settings/b` when `/settings` is accessed, and not code-split the lower routes

**Comment by justingreenberg** [comment]
i would separate the sub-route definitions—ie `settings/routes.js`—and follow tim's advice to "import your components like any other module and statically reference them as the component for each route"

then, you can `system.import` the sub-route definitions inside [`getChildRoutes`](https://github.com/reactjs/react-router/blob/master/docs/API.md#getchildroutespartialnextstate-callback) in the root `routes.js` to create the split point

**Comment by mxstbr** [comment]
That sounds reasonable!

**Comment by timdorr** [comment]
@justingreenberg Yep, that's exactly what I meant, essentially 😄  Thanks for writing out the example!

**Comment by mxstbr** [comment]
I'll close this since @justingreenberg answered the question perfectly. Let's add that to the FAQ?
