### ISSUE TITLE
Webpack 2.0 feature: treeshaking / native-module supported?

### ISSUE THREAD

**Issue by mrvicadai** [mxstbr/react-boilerplate#603]
Hi @mxstbr thanks for making such an amazing boilerplate! I noticed the webpack version in package.json is 2.0+ and seems to be able to support [treeshaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html). Is this feature already built into react-boilerplate?

**Comment by mxstbr** [comment]
Yeah, it is!
