### ISSUE TITLE
saga task duplication

### ISSUE THREAD

**Issue by salzhrani** [mxstbr/react-boilerplate#605]
a redux-saga noob here. I noticed that when I enter a route of a container, the sagas behave as expected but If I re-enter the route again, a saga will run twice after dispatched once and as I repeat the re-entry the the number gets multiplied... It seems that `injectSagas` is not idempotent. when I ensure that `injectSagas` is run once, I don't see this behaviour.

**Comment by abeaclark** [comment]
I also have this problem

**Comment by mxstbr** [comment]
See the discussion (and eventual solution) in #390 for more information how to solve this. The TL;DR is that you should use a `redux-saga` watcher and exit your sagas on `LOCATION_CHANGE`!

**Comment by emragins** [comment]
Would it make sense to add this to the generator code? (I'm too much of a noob here to have an opinion)

**Comment by Maxoos** [comment]
@mxstbr That solution works well, however, I need do something async while navigating away from the page and in that case it does not work too well:

```
      dispatch(postProperty());
      dispatch(push(url));
```
