### ISSUE TITLE
What about using react-css-modules?

### ISSUE THREAD

**Issue by Ndpnt** [mxstbr/react-boilerplate#606]
For our project we need to use [react-css-modules](https://github.com/gajus/react-css-modules#whats-the-problem) which brings us those features: 
- We do not need to refer to the styles object every time we use a CSS Module
- But above all, it allows us to mix CSS Modules and global CSS easily, (thing that I found not so easy with only css-loader package)
- We are warned when styleName refers to an undefined CSS Module

What do you think? 
If you are interested, we may provide a PR as we will use it for our needs.

**Comment by gihrig** [comment]
I'm just a user of the boilerplate, but I would love to see a PR implementing react-css-modules.

**Comment by mxstbr** [comment]
> If you are interested, we may provide a PR as we will use it for our needs.

Please do, I'd be interested to see it live in action! I haven't personally used it and so far been happy with the way CSS modules work by default, so I can't guarantee we'll merge it but it sounds very useful!

**Comment by tzarger** [comment]
@Ndpnt Are you planning to create a PR for this? I would be interested in seeing this as well. Thank you!

**Comment by Ndpnt** [comment]
@tzarger Yes, I'm planning to create a PR but I'm really busy now. I hope I can do it this week.

**Comment by afaayerhan** [comment]
please don't do this. react-css-modules wrap in high order components. adds some more computation. and makes inspecting components in dev tools very inconvinent. also requires you to have some extra changes in build step to extra css .......

**Comment by mxstbr** [comment]
Thanks for playing devil's advocate here @afaayerhan, let's see what @Ndpnt comes up with!

**Comment by Ndpnt** [comment]
Hi everyone, just to let you know that I'm working on this PR, but I encounter some issues with `enzyme`'s different rendering functions (`shallow`, `mount`) in the tests. 
So it will be longer than expected.

You can see the progression here (work in progress, history will be rewritten): https://github.com/mxstbr/react-boilerplate/compare/master...soundsgood-co:react-css-modules?expand=1

The missing parts are:
- [ ] Fix tests
- [ ] Add documentation

**Comment by ansumanshah** [comment]
are we moving ahead with react-css-modules?

**Comment by Ndpnt** [comment]
@ansumanshah Nope, I'm sorry, I'm too busy right now… I don't really know when I will come back on it.

**Comment by mxstbr** [comment]
Closing due to little interest. I'd still love to see a PR for this if you ever get around to it @Ndpnt!

**Comment by vmarinov2013** [comment]
+1 to @afaayerhan's `please don't do this.`

It seemed to be fine at the initial phase, but I had very hard time to debug this error on production build.
Fields were losing focus on first character input on `redux-form`.
Finally find out that's due to `react-css-modules` (HOC).

**Comment by gihrig** [comment]
@vmarinov2013 Thanks for the input. I have little experience with Javascript HOCs (I come from a Java background) In Java the same concept is called AOP (Aspect Oriented Programming). 

It's "cool" and easy to implement in some scenarios, but in my experience, It makes debugging _very_ difficult.
