### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by lasryaric** [mxstbr/react-boilerplate#608]
What do you recommend for clearing the cache for every new deployment? I am using the serve built in (npm run start:prod).

Thanks

**Comment by gihrig** [comment]
If you run `npm run start:production` (in place of `npm run start:prod`) the ./build directory will be cleaned out before the new build. see `package.json` `scripts` section. 

As far as I know this is all that is required between deploys.

Is there something else you had in mind?
