### ISSUE TITLE
how to import an npm js file?

### ISSUE THREAD

**Issue by mlennie** [mxstbr/react-boilerplate#610]
I can't seem to use https://www.npmjs.com/package/blueimp-load-image#usage

I'm trying to import it into my component using
`import loadImage from 'blueimp-load-image/js/load-image.all.min';`
and 
`import loadImage from 'blueimp-load-image';`
and
`import 'blueimp-load-image/js/load-image.all.min';`

Then I'm trying to use `loadImage` in the component I'm importing it into but it's appearing as undefined.

**Comment by gihrig** [comment]
The [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) package doesn't seem to support the usual npm module loading, at least I didn't see any evidence on their site. Further, as that project does not have an issue tracker, I would suggest that you ask questions of this mature on [StackOverflow](https://stackoverflow.com).

Having said that, I would guess that the right syntax might be more like:

`import { loadImage } from 'blueimp-load-image';`

See import [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) for syntax details on using import.

**Comment by mxstbr** [comment]
This is not something we can fix on our end, this is definitely a problem with the way `blueimp-load-image` is built as @gihrig said. Sorry, hope you can resolve this soon!
