### ISSUE TITLE
How to use Initializing From State of redux-form (erikras)

### ISSUE THREAD

**Issue by hieubq-working** [mxstbr/react-boilerplate#611]
Hi.
I got some problem when using redux-form of erikras
I make one page has an Image Uploader and one form,
after reducer got upload_success action, I save the link on reducer but I can't update text field of form with this link from.

Can you help me to do this like this example in http://redux-form.com/5.2.5/#/examples/initializing-from-state?_k=oa0vin
Thanks!

**Comment by mxstbr** [comment]
I have sadly never worked with `redux-form` before, so I have no idea how to use it. Will leave this open, maybe somebody else has done this before!

**Comment by gihrig** [comment]
I'm working on getting redux-forms integrated with react-boilerplate. There is a discussion on-going at #567.

I hope to have a solution, and maybe a PR early next week.

**Comment by mxstbr** [comment]
@gihrig I'd love for you to provide a reference implementation, but I think it's out of the scope of the example app to showcase redux-form!
