### ISSUE TITLE
Integrating Redux Auth Wrapper

### ISSUE THREAD

**Issue by wullaski** [mxstbr/react-boilerplate#615]
I have a basic login flow working but I've hit a wall with integrating a routing solution to check authentication and redirect based on user status. I wanted to be able to use [Redux Auth Wrapper](https://github.com/mjrussell/redux-auth-wrapper) but the way the routes are generated makes integration difficult/less clear. Is there an easy solution for this?

**Comment by mxstbr** [comment]
Have never worked with redux-auth-wrapper before, but https://github.com/sotojuan/saga-login-flow by @sotojuan is _solid_!

**Comment by sotojuan** [comment]
Yep, `onEnter` just works. Not sure if it's the cleanest solution but it gets the job done :-)

**Comment by oyeanuj** [comment]
On `onEnter` vs `HoC`, this might be relevant: http://stackoverflow.com/a/34932997

**Comment by ansumanshah** [comment]
@oyeanuj have you tried integrating redux-auth-wrapper can you provide an example/gist please?

**Comment by mjrussell** [comment]
For those looking for advice on how to integrate with redux-auth-wrapper, this is a good starting place: https://github.com/mjrussell/redux-auth-wrapper/issues/40#issuecomment-221643579

As @oyeanuj linked, there are a couple of edge cases `onEnter` didn't solve in my application which is what prompted me to write the HOC library.
