### ISSUE TITLE
Master Detail and code splitting routes

### ISSUE THREAD

**Issue by dfcarpenter** [mxstbr/react-boilerplate#618]
Hi there,

Enjoying the boilerplate so far but i'm trying to figure out how to implement a master / detail view with react-router using the code splitting setup as provided. This isn't a bug with the boilerplate but since I am following most of the structure and conventions I figure someone might be able to cast some light on this. I am basically following this 

https://github.com/reactjs/react-router/blob/master/examples/master-detail/app.js

Here is my current route config.

````
return [
    {
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/HomePage/reducer'),
          System.import('containers/HomePage/sagas'),
          System.import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('home', reducer.default);
          injectSagas(sagas.default);

          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    },
    {
        path: '/flow/:flowId',
        name: 'flow',
        getComponent(nextState, cb) {
          const importModules = Promise.all([
            System.import('containers/Flows/reducer'),
            System.import('containers/Flows/sagas'),
            System.import('containers/Flows/FlowDetail'),
          ]);

          const renderRoute = loadModule(cb);

          importModules.then(([reducer, sagas, component]) => {
            injectReducer('flow', reducer.default);
            injectSagas(sagas.default);

            renderRoute(component);
          });

          importModules.catch(errorLoading);
        },
      },
    {

```` 

I have the main app component and then the home component. In the home component I have a section to render the child (Following the same structure as the demo)

The list items have a <Link to={/flow/:flowid}> which when clicked would show the appropriate item (after a fetch from a saga)

````
render() {
    console.log(this.props)
    let mainContent = null;

    // Show a loading indicator when we're loading
    if (this.props.loading) {
      mainContent = (<List component={LoadingIndicator} />);

    // Show an error if there is one
    } else if (this.props.error !== false) {
      const ErrorComponent = () => (
        <ListItem item={'Something went wrong, please try again!'} />
      );
      mainContent = (<List component={ErrorComponent} />);

    // If we're not loading, don't have an error and there are repos, show the repos
    }  else if (this.props.flows !== false) {
      mainContent = (<List items={this.props.flows} component={FlowListItem} />);
    }

    return (
      <div>
        <div>
          <div className={styles.flowsContainer}>
            <section className={`${styles.flowList} ${styles.textSection}` }>
              <Button onClick={this.props.onSubmitForm}>Get Flows</Button>
              {mainContent}
            </section>
            <section className={styles.flowEdit}>
              {this.props.children}
            </section>
          </div>
          <Button handleRoute={this.openFeaturesPage}>Features</Button>
        </div>
      </div>
    );
  }
}
````

**Comment by datapimp** [comment]
Just from skimming the code, the thing that stands out to me is that you don't treat the `FlowDetail` as child routes.  

Something still feels off about the code below to me, but it does work in one of my projects, so I think it might help.  

(I've changed my code names to match yours -- might have missed some so don't copy paste)

```javascript
{
      path: 'flows',

      getIndexRoute(location,cb) {
        const importModules = Promise.all([
          System.import('containers/Flows/sagas'),
          System.import('containers/Flows/reducer'),
          System.import('components/FlowsDashboard')
        ])

        importModules.then(([sagas, reducer, component]) => {
          injectReducer('flows', reducer.default)
          injectSagas(sagas.default)

          cb(null, {component: (component.default ? component.default : component)})
        })
      },

      getChildRoutes(location, cb) {
        const importModules = Promise.all([
          System.import('components/FlowDetails')
        ])

        importModules
          .then(([ShowProperty]) => ({
            component: FlowDetails.default,
            path: ':flowId',
            name: 'flowDetails',
          }))
          .then((...components) => cb(null, components))

        importModules.catch(errorLoading)
      },

      getComponent(location, cb) {
        System.import('containers/Flows')
          .then(loadModule(cb))
          .catch(errorLoading);
      }
    }
}
```

If you need help hit me up.

**Comment by mxstbr** [comment]
Due to @datapimp's amazing answer I'll close this for now, feel free to continue the discussion though!

**Comment by dfcarpenter** [comment]
Thanks for the response @datapimp. What I am having trouble with is thinking through where I put my reducers and sagas (async handling, etc). I want a top level Flows page and then have sub components like the details show on the right side and another component, a list of flows show on the left. When the initial flows page is loaded I need to fetch the flows list data and render the list component with it's items. The right side of the page will be blank because no individual item has been selected. When any of the items on the list is clicked I need to make another async call to fetch the data for the individual list item and render it in the Flow Detail component. Should I keep one reducer at the top level flows component and just dispatch the required async actions in the flows list, flow details components when componentDidMount is run (or could you recommend some other solution)

**Comment by datapimp** [comment]
Hi Daniel aka @dfcarpenter 

I would load all of my reducer / saga stuff in the top level container.  I'm assuming that the flow detail stuff is tied to your route, so your redux state would have all of your flows keyed by id, and your views would be tied to the route state.   

Watching [Dan Abramov's second egghead.io series](https://egghead.io/courses/building-react-applications-with-idiomatic-redux) on writing idiomatic redux applications was a great way to crystallize the details of this pattern for me and this project's use of redux-saga makes it even cleaner IMO.  

Doing things the way he describes there ended up in a lot less manual monkeying around with `componentDidMount` and other lifecycle hooks.  

I'm working on something over the next few days which is exactly like you describe so I'll try and share -- but I think you'll figure it out before then

**Comment by verenea** [comment]
Good stuff @datapimp ... were you ever able to produce an example of the reducer/saga relationships for top level -to- child routes as you mentioned you were working on?
