### ISSUE TITLE
duplicated output of coverage

### ISSUE THREAD

**Issue by akaRem** [mxstbr/react-boilerplate#627]
Init project as suggested on main page, then execute command
`$ npm run build`
then look at `coverage/` folder — there are 2 folders with similar content:

```
$ tree coverage/html -L 1
coverage/html
├── app
├── base.css
├── index.html
├── prettify.css
├── prettify.js
├── sort-arrow-sprite.png
└── sorter.js
$ tree coverage/lcov/lcov-report -L 1
coverage/lcov/lcov-report
├── app
├── base.css
├── index.html
├── prettify.css
├── prettify.js
├── sort-arrow-sprite.png
└── sorter.js
```

and if you check diff 

```
$ diff -r coverage/html coverage/lcov/lcov-report
$ echo $?
0
```

it will show that content is exact the same

Looks like some kind of misconfiguration in `internals/testing/karma.conf.js` at L51..58:

```
    coverageReporter: {
      dir: path.join(process.cwd(), 'coverage'),
      reporters: [
        { type: 'lcov', subdir: 'lcov' },
        { type: 'html', subdir: 'html' },
        { type: 'text-summary' },
      ],
    },
```

html and lcov reporters work similar and one of  them probably should be removed

**Comment by mxstbr** [comment]
That definitely seems like a bug, but we do need to lcov output for the CI. Could you investigate what the difference is/isn't and if necessary submit a PR? Thanks!

**Comment by akaRem** [comment]
@mxstbr 
As you have seen in initial report (diff -r) these dirs are exact the same..
I'd propose to reconfigure CI and reporting to put everything into coverage (w/o additional lcov subfolder),  and remove html section.
But I've just started to look at boilerplate and not sure how this could affect integration and documentation, so .. no PR yet.

Probably someone who knows codebase could submit PR.

**Comment by mxstbr** [comment]
> Probably someone who knows codebase could submit PR.

Just try it! Doesn't have to be perfect on first try, you know what to do anyway! :+1:

**Comment by mxstbr** [comment]
No longer relevant now that we've switched to Jest in #980! Will be in the next release 👌
