### ISSUE TITLE
extract tool configs (eslint and others) from package.json

### ISSUE THREAD

**Issue by akaRem** [mxstbr/react-boilerplate#629]
Currently configs for eslint and stylelint are located in package.json.
This approach helps to reduce amount of dotfiles, but it also hides configuration from some IDEs and editors.
For example, idea family of editors (I use pyCharm) support editorconfig, linters and other stuff, but it doesn't look into package.json for configuration.

Extracting tool configs from package.json will make this starter kit more flexible and portable.

**Comment by mxstbr** [comment]
This was a conscious decision we made, we favor a clean root folder over exposing all of those configurations.

If your editor does not support it, changing it back to the old dotfile layout is a few copy-and-pastes away!

**Comment by akaRem** [comment]
@mxstbr that's exactly what I've done. :)
Then, probably analize results should be put into some separate folder instead of root of the project..
