### ISSUE TITLE
.htaccess file is not removed by npm run build:clean

### ISSUE THREAD

**Issue by bcowgill** [mxstbr/react-boilerplate#656]
rimraf ./build instead of rimraf ./build/*

stats.json isn't cleaned either

**Comment by gihrig** [comment]
Good catch!

Confirmed on OS X 10.11.5.

How about submiting a PR?

**Comment by gihrig** [comment]
Does this create a problem? 

`.htaccess` and `stats.json` are successfully overwritten on the next build or analyze, so maybe it's not an issue?

**Comment by mxstbr** [comment]
Not necessarily a problem, but could still be fixed to avoid annoyances where the build doesn't go through and one deploys with some stale files.

**Comment by gihrig** [comment]
@bcowgill Would you like to submit a PR?

**Comment by bcowgill** [comment]
Done.
https://github.com/mxstbr/react-boilerplate/pull/661
also deals with issue 628 cleaning coverage before running tests.
