### ISSUE TITLE
Document dynamic routes

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#659]
Gitter discussion recently covered dynamic routes. Seems like a common feature in some types of apps.

If someone could confirm this works and update [docs/js/routing.md](https://github.com/mxstbr/react-boilerplate/blob/master/docs/js/routing.md) with a few snippets and open a PR that would be awsome :smile:

> jcrain @jcrain 17:06
> Has anyone here used dynamic routes for example /thing/:id
> 
> jcrain @jcrain 17:15
> path: 'sample/:id', seems to work. Now any idea how I access the id in the page container?
> 
> Troy Zarger @tzarger 17:16
> @jcrain this.props.params.id
> 
> jcrain @jcrain 17:24
> @tzarger :fire:
> thanks
>

**Comment by mxstbr** [comment]
> If someone could confirm this works

This definitely works. :grin:

**Comment by mxstbr** [comment]
Done by the amazing @swordsreversed in #804!
