### ISSUE TITLE
Proxy http requests

### ISSUE THREAD

**Issue by dkostenko** [mxstbr/react-boilerplate#664]
Thank you for the boilerplate! I've started to use it. But I guess it would be suitable to add such feature: proxy http request to local server (e.g. rails), to have such process: react application on 3000 port and rails server on 3001 port

**Comment by ddltechy** [comment]
@dkostenko I was thinking on ask for that feature too!  I'm using json-server to mock up api server calls

**Comment by mxstbr** [comment]
Not entirely sure I understand the feature here, why do we need a proxy? What's the use case here?

**Comment by tzarger** [comment]
@mxstbr @dkostenko adding node-http-proxy for example is pretty easy and not sure it really needs to be added to the boilerplate. I am actually using it currently and it is just an npm install and then modifying server/index.js to proxy the api.

**Comment by gihrig** [comment]
The use case would be a react-boilerplate created front-end app that communicates with a backend server available on some `host:port` available on the network.

Suppose another team in your organization maintains a server (written in Node, Java, Rails, PHP, whatever) that exposes an api on port 8080 (or whatever). How would you connect your react-boilerplate front-end to such a server?

Considering @tzarger's comment, it sounds like this might be a candidate for an entry in (a yet to be created) `docs/general/recipes.md`?

**Comment by tzarger** [comment]
@gihrig I agree it is useful, if we added proxying to this boilerplate then we would also need to include a bare bones api server to go with it. That is the reason I mentioned it probably should not be included by default, especially since it is rather easy to add. As stated, I am using node-http-proxy in my app based on this boilerplate so I do agree it is worth the mention. Also agree, perhaps a Recipe would be a good add.

**Comment by dkostenko** [comment]
@mxstbr the other day we started 2 new projects with react-boilerplate. This is really the best boilerplate for ReactJS projects, but in my opinion the most frequent case of using ReactJS application in the pair with the server which provides data for the frontend application. And for developing such systems developers need to run 2 web servers on localhost: one for providing data (i.e. Ruby on Rails) on port :3000 and one for working with ReactJS application (something which is serving react-boilerplate) on port :3001. But as I mentioned in common cases we need proxy http request from one server to another, even on localhost (because there is CORS in browsers). And that's why I though it would be useful add proxy module (for instance node-http-proxy) in react-boilerplate.

@tzarger we use node-http-proxy too.

**Comment by mxstbr** [comment]
Ahh, right! I do like the idea behind this, but I don't think it's worth adding by default. @theWar13 went ahead and added this in #679, but I'd much rather see this as a documentation page!

**Comment by dkostenko** [comment]
@mxstbr great! Thank you

**Comment by istinspring** [comment]
yes would be nice, i'm using django to build backend stuff and need to proxy requests to api from one port to another to avoid CORS.
