### ISSUE TITLE
package.json5 to allow documenting the configuration

### ISSUE THREAD

**Issue by bcowgill** [mxstbr/react-boilerplate#674]
This might be controversial because it can be annoying for newbies.

I like to use .json5 for any configs that use json. JSON5 allows you to add comments and break across multiple lines so it's great for human readable configuration files, and temporarily commenting things out.

The difficulty lies in npm reading package.json and writing back to it when you install modules.

Personally I solve this with a npm run json5 target to convert the json5 to json.
Then I use a script to do any npm commands to install packages and visual diff the package.json back to the package.json5 so I can bring the changes back.
```
npm install json5 --save-dev
```

```
"scripts":{
        // targets for using human friendly json5 configuration
        "json5": "json5 -c package.json5
}
```

```
> cat scripts/npmi.sh 
# install npm packages then bring up diff tool to update the json5 package config
npm install $*
diffmerge package.json package.json5
```

Whenever you edit package.json5

```
npm run json5
npm run ...something else
```

**Comment by gihrig** [comment]
@bcowgill Seems like a lot of complexity. Can you discuss more on the benefits you have observed from json5? What extent of documentation/commenting would you add to the existing `package.json`?

**Comment by mxstbr** [comment]
I do see the benefits of adding comments to the `package.json`, but I don't think it's worth the added complexity by default. I think the documentation in the `docs/` folder should be enough to explain most things!

Thanks for chiming in here though, I might use this on a project soon :+1:
