### ISSUE TITLE
Caching on dev server

### ISSUE THREAD

**Issue by thgil** [mxstbr/react-boilerplate#68]
Is there any way to disable cache on the dev server because none of my changes seem to get loaded, it just loads the cache version instead. Am I just doing something wrong or is the hot loading not working correctly?

**Comment by mxstbr** [comment]
You have to do a "hard refresh", i.e. press `CMD + SHIFT + R` on Mac.

Other alternative is to only load AppCacheWebpackPlugin in dev mode in `makewebpackconfig.js`!

**Comment by thgil** [comment]
Perfect thank you!
