### ISSUE TITLE
Stateless pages

### ISSUE THREAD

**Issue by BraunreutherA** [mxstbr/react-boilerplate#681]
Hi there, I'm pretty new to react so maybe this is a wrong thought. 
Why are pages always containers? Couldn't they simply be stateless components? For example if there would be a page that only display some instruction code and a button that leads to the 'real' application.

Best regards, 
Alex

**Comment by gihrig** [comment]
> [It's a fine approach for learning but I don't think it scales well](https://github.com/reactjs/redux/issues/1176#issuecomment-167015145).

**Comment by BraunreutherA** [comment]
Okay I think thats another thing what I meant is pretty much the same as here: 
http://redux.js.org/docs/basics/UsageWithReact.html

If you have a look into the presentational components the App is just a function which assembles multiple stateful components. So in regard to this boilerplate for example I had the case of a signinpage. 
-> SigninPage = Component (stateless function)
-> SigninContainer = Container (ES6 class with all redux stuff arround)

The page has some html stuff and then just renders an signin container into this. I can think of a lot of cases (if not the most) where the "page" itself would be stateless this way and just puts together some containers like navbars or charts etc.

**Comment by gihrig** [comment]
> The page has some html stuff and then just renders an signin container into this. 
> ... puts together some containers like navbars or charts etc.

Seems like a good case for a stateless container (page). 

Beyond those issues there is the matter of consistency of project structure. When a project grows to more than a few "components" and "containers", I find it helpful in "finding may way around" the project, but that could be a matter of personal taste.

Overall, I don't know of any reason a "container" could not be stateless.

Disclaimer - I'm still pretty new at this stuff myself 😉

**Comment by BraunreutherA** [comment]
> Seems like a good case for a stateless container (page).

Maybe I misunderstood the structure but I thought containers are the stateful and components the stateless objects?
Actually from what I got out of [this article](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.4k1av27sn).

**Comment by mxstbr** [comment]
The problem with stateless components is that they cannot be hot reloaded at the moment. This will be fixed very shortly, but currently still affects us.

The idea behind the containers and components split is explained [right here](https://vimeo.com/168648012#t=6m35s), but you don't have to follow what we do in this boilerplate. If you think you want a page to be a stateless component, feel free to go ahead and do that!
