### ISSUE TITLE
ES6 class generator eslint disable

### ISSUE THREAD

**Issue by BraunreutherA** [mxstbr/react-boilerplate#684]
The generator for creating components with es6 classes could directly set the `// eslint-disable-line react/prefer-stateless-function` flag so there wouldn't be the need to do it it manually every time.

**Comment by gihrig** [comment]
Great idea :sparkles:

Would you consider submitting a PR?

**Comment by BraunreutherA** [comment]
Jap made PR #685 - had to change only for the components in the container generator it's already present.

**Comment by mxstbr** [comment]
Done in #685, thanks so much @BraunreutherA!
