### ISSUE TITLE
Unable to setup react-boilerplate

### ISSUE THREAD

**Issue by gkbiswas** [mxstbr/react-boilerplate#689]
I got the following error on running "npn run setup" ...

➜  react-boilerplate git:(master) npm run setup

> react-boilerplate@3.0.0 presetup /Users/goutamkumarbiswas/dev/react-boilerplate
> npm i chalk

chalk@1.1.3 node_modules/chalk
├── supports-color@2.0.0
├── escape-string-regexp@1.0.5
├── ansi-styles@2.2.1
├── has-ansi@2.0.0 (ansi-regex@2.0.0)
└── strip-ansi@3.0.1 (ansi-regex@2.0.0)

> react-boilerplate@3.0.0 setup /Users/goutamkumarbiswas/dev/react-boilerplate
> node ./internals/scripts/setup.js

Cleaning old repository ✓
Installing dependencies.. ✓(This might take a while)Installing dependencies
Initialising new repository ✓
Done!
> react-boilerplate@3.0.0 postsetup /Users/goutamkumarbiswas/dev/react-boilerplate
> npm run build:dll

> react-boilerplate@3.0.0 build:dll /Users/goutamkumarbiswas/dev/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/goutamkumarbiswas/dev/react-boilerplate/internals/scripts/dependencies.js:8:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dll"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 build:dll script 'node ./internals/scripts/dependencies.js'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/dependencies.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/goutamkumarbiswas/dev/react-boilerplate/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 postsetup script 'npm run build:dll'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dll
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/goutamkumarbiswas/dev/react-boilerplate/npm-debug.log

=======

➜  react-boilerplate git:(master) cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup react-boilerplate@3.0.0
6 verbose unsafe-perm in lifecycle true
7 info setup react-boilerplate@3.0.0
8 verbose unsafe-perm in lifecycle true
9 info postsetup react-boilerplate@3.0.0
10 verbose unsafe-perm in lifecycle true
11 info react-boilerplate@3.0.0 Failed to exec postsetup script
12 verbose stack Error: react-boilerplate@3.0.0 postsetup: `npm run build:dll`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:827:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid react-boilerplate@3.0.0
14 verbose cwd /Users/goutamkumarbiswas/dev/react-boilerplate
15 error Darwin 15.5.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
17 error node v4.4.7
18 error npm  v2.15.8
19 error code ELIFECYCLE
20 error react-boilerplate@3.0.0 postsetup: `npm run build:dll`
20 error Exit status 1
21 error Failed at the react-boilerplate@3.0.0 postsetup script 'npm run build:dll'.
21 error This is most likely a problem with the react-boilerplate package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build:dll
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs react-boilerplate
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls react-boilerplate
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
➜  react-boilerplate git:(master)

**Comment by gihrig** [comment]
> ERR! node v4.4.7
> npm ERR! npm v2.15.8

See #672

**Comment by gkbiswas** [comment]
thanks for the resolution!
