### ISSUE TITLE
Cannot find module font-awesome

### ISSUE THREAD

**Issue by christiansakai** [mxstbr/react-boilerplate#693]
Anyone ever got this? After `npm install` and `npm start` and visits `localhost:3000`, this is what I got in the console

![screen shot 2016-07-10 at 8 16 13 pm](https://cloud.githubusercontent.com/assets/7025139/16717035/430bfaf2-46db-11e6-9a9b-fa89ac4f06f9.png)

**Comment by suhaotian** [comment]
Please use `react-icons`, it's better!

**Comment by christiansakai** [comment]
@suhaotian 

Which package needs to be replaced to `react-icons`?

**Comment by suhaotian** [comment]
The boilerplate didn't include `font-awesome` and `react-fa`.

**Comment by christiansakai** [comment]
Ah you are right! sorry, let me close this

**Comment by gihrig** [comment]
@christiansakai 

> npm install and npm start and visits localhost:3000, this is what I got in the console

If you are getting font-awesome errors after a simple install and start, that's really odd because as @suhaotian says, it's not a part of react-boilerplate.

Maybe you have a corrupt npm cache? try `npm cache clean` Then clone a new copy of react-boilerplate.

**Comment by christiansakai** [comment]
@gihrig thanks, it was my mistake!
