### ISSUE TITLE
how to get url params in component ?

### ISSUE THREAD

**Issue by mike623** [mxstbr/react-boilerplate#695]
I am newbies of react. I am confusing how to get params from props 

here is my route setting 

```javascript
 }, {
      path: '/AskQuestion/:questionId',
      name: 'AskQuestion',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/AskQuestion/reducer'),
          System.import('containers/AskQuestion/sagas'),
          System.import('containers/AskQuestion'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('askQuestion', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    },    {
```
and my url is http://127.0.0.1:3000/AnswerQuestion/asdsad?asdas=asda#asdsad

I can set hash, query(search) set in route store, but cannot find :questionId

**Comment by mxstbr** [comment]
In the component that is rendered at the route you have access to `this.props.params.questionId`, see the `react-router` docs: https://github.com/reactjs/react-router/blob/112cce48255f930df3270382665223cd41b6f1fa/docs/Glossary.md#routecomponent
