### ISSUE TITLE
How to make hot reloading work ?

### ISSUE THREAD

**Issue by mmacedoeu** [mxstbr/react-boilerplate#70]
After git clone, npm install and npm start, I edited HomePage.react.js changing Hello World to Hello Redux and saved ! Changes don't propagated to browser even after browser refresh !

**Comment by mxstbr** [comment]
Hot reloading should work out of the box, no more setup needed.

Which browser did you use, and can you try doing a hard refresh? (`CMD` + `SHIFT` + `R` on Mac)

**Comment by mmacedoeu** [comment]
Ubuntu 15.10 with Google Chrome Version 47.0.2526.106 (64-bit)

I have other boilerplate working with hot-reloading with this browser like https://github.com/gaearon/react-hot-boilerplate

**Comment by mxstbr** [comment]
Are you getting any output in the console?

**Comment by mmacedoeu** [comment]
![image](https://cloud.githubusercontent.com/assets/4959023/12098197/b8c70b32-b307-11e5-8216-304ea422a0b6.png)

**Comment by mmacedoeu** [comment]
Looks like content is always from cache, even after stoping the server and new browser page load it displays the old content.

**Comment by mxstbr** [comment]
Hot reloading is enabled though, it works even with the AppCache in place for me.

Will think about only adding it to prod, thanks for reporting this!

**Comment by mmacedoeu** [comment]
After a full browser restart and reset to defaults it's working now :) I will close as it looks unrepeatable !

**Comment by mxstbr** [comment]
Nice, glad it's working!
