### ISSUE TITLE
Offline Access is not working

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#705]
after git clone, i tried to check offline access feature
by running `npm run start:production`

I first turn on the WiFi and refresh the page, wait for a few moments.
Then set the throttling in google chrome to "Offline"

But there is an javascript error in the console
`main.js:706Uncaught ReferenceError: reactBoilerplateDeps is not defined`

The page are shown in plain white (no happy dinosaur)

I also attached the console.log for further investigation

![image](https://cloud.githubusercontent.com/assets/2979072/16779336/fbd2da6c-489b-11e6-99bb-37ddd13aa1e0.png)

**Comment by gihrig** [comment]
The steps (I think) you outlined work for me on Mac OS 10.11.5, Chrome 51.0.2704. I am able to access both Home and Features pages with network disabled. I can also access GitHub repos when the server is down, but network must be available (of course).

With the server down and network enabled, I do get a console error

![image](https://cloud.githubusercontent.com/assets/1481063/16781839/ea3067ee-4831-11e6-8d17-382676e7f597.png)

But everything still works as expected

Sorry if I misunderstood, but were you able to access the example app in production mode before disabling network access?

If so, what is your OS and version?

**Comment by chaintan17** [comment]
@gihrig Yes, i can access the example app in production mode.
I use MacOSX Yosemite and Chrome latest version.

I have another clue...
with wifi turn off, it's working, i can access the website offline.
But with internet throttling, i cannot made it.

So is it working with internet throttling in chrome debugger tool, or it's just my device?

**Comment by gihrig** [comment]
It works for me with internet throttling set to "Offline ..."

What happens if you leave internet access on (No throttling), but stop the react-boilerplate server? Does that work?

If that works but you still have problem with Throttling set to Offline, you could try 
- Open "Resources" tab in Chrome Dev Tools with localhost:3000 page open 
- Delete all entries
- Load Example app in production mode
- Disable network (Throttling =  Offline)

Beyond that, maybe try another browser? Offline mode works for me in Firefox and Safari, latest.

**Comment by chaintan17** [comment]
No luck, all browser produce the same error after stop the server.

But after stop the server, i saw this error in chrome console
![image](https://cloud.githubusercontent.com/assets/2979072/16789961/0c490b4c-48dc-11e6-82ba-234a6d50d45f.png)

btw, may i need your help?
I'm wondering if this offline-loader is the same thing to progressive web app (PWA) ?
Because i thought Safari didn't support it for PWA.

**Comment by chaintan17** [comment]
Strange, now I tried with chrome incognito and it's working.

May be it's because i tried to add offline plugin in `webpack.dev.babel.js` first.
And it got wrong cache when load production, i guess.

**Comment by gihrig** [comment]
Glad to know it's working!

**Comment by chaintan17** [comment]
Thanks a lot for your help! 
I will close the issue.

**Comment by jimmyheaddon** [comment]
Just some feedback... I've updated ALL npm dependencies (including dev) to the latest, except for offline-plugin, react-router and react-router-scroll.

This allows me to run without issue, but updating offline-plugin to anything about v4.6.2 gives me the error mentioned above on dev and production builds.

external "reactBoilerplateDeps":1 Uncaught ReferenceError: reactBoilerplateDeps is not defined
    at Object.dll-reference reactBoilerplateDeps (external "reactBoilerplateDeps":1)
    at __webpack_require__ (bootstrap f393147…:698)
    at fn (bootstrap f393147…:111)
    at Object../node_modules/eventsource-polyfill/dist/browserify-eventsource.js (browserify-eventsource.js from dll-reference reactBoilerplateDeps:1)
    at __webpack_require__ (bootstrap f393147…:698)
    at fn (bootstrap f393147…:111)
    at Object.0 (main.js:6234)
    at __webpack_require__ (bootstrap f393147…:698)
    at ./app/app.js.Object.defineProperty.value (bootstrap f393147…:796)
    at bootstrap f393147…:796
