### ISSUE TITLE
Evaluate using sw-toolbox

### ISSUE THREAD

**Issue by tomascharad** [mxstbr/react-boilerplate#708]
Hi guys,

Have you evaluated using https://github.com/GoogleChrome/sw-toolbox?

**Comment by mxstbr** [comment]
I think it's not worth introducing an abstraction for Service Workers by default in this boilerplate.

We provide a minimum valuable configuration with the `offline-plugin` that just works™, and if people want custom behaviour they can introduce `sw-toolbox` or whatever they want to build their own!
