### ISSUE TITLE
Zombie App

### ISSUE THREAD

**Issue by aleemb** [mxstbr/react-boilerplate#71]
I tested this boilerplate out and subsequently moved on to test out other boilerplates (which also run on localhost:3000). The other apps are not able to be served on `localhost:3000` and instead this same app is constantly being served. I could try deleting my browser cache I suppose but have yet to try that. The `chrome://appcache-internals` doesn't list this app.

Just as surprising is that `http://localhost:3000/d37380ea6ac9abdb6c8fd3c00fbaf410.png` is still being served (which loads the `mxstbr` image). This could be a Chrome issue (47.0.2526.106 (64-bit)), I am not sure, I haven't used AppCache before. In Incognito mode, things work as expected -- the image fails to load and if I server something else on `3000` that loads as expected.

**Comment by aleemb** [comment]
The JS console is constantly looping over the following errors,

```
GET http://localhost:3000/sockjs-node/info?t=1451979320567 net::ERR_CONNECTION_REFUSED
The FetchEvent for "http://localhost:3000/sockjs-node/info?t=1451979320567" resulted in a network error response: the promise was rejected.
(program):1 Uncaught (in promise) TypeError: Failed to fetch(…)
bundle.js:4130 GET http://localhost:3000/sockjs-node/info?t=1451979320567 net::ERR_FAILEDAbstractXHRObject._start @ bundle.js:4130(anonymous function) @ bundle.js:4023
bundle.js:626 [WDS] Disconnected!sock.onclose @ bundle.js:626EventTarget.dispatchEvent @ bundle.js:3565(anonymous function) @ bundle.js:6715
:3000/sockjs-node/info?t=1451979322586:1 GET http://localhost:3000/sockjs-node/info?t=1451979322586 net::ERR_CONNECTION_REFUSED
The FetchEvent for "http://localhost:3000/sockjs-node/info?t=1451979322586" resulted in a network error response: the promise was rejected.
(program):1 Uncaught (in promise) TypeError: Failed to fetch(…)
bundle.js:4130 GET http://localhost:3000/sockjs-node/info?t=1451979322586 net::ERR_FAILEDAbstractXHRObject._start @ bundle.js:4130(anonymous function) @ bundle.js:4023
bundle.js:626 [WDS] Disconnected!
```

**Comment by mxstbr** [comment]
See this comment: https://github.com/mxstbr/react-boilerplate/issues/70#issuecomment-168791025

I'll be removing AppCache from the dev environment as soon as I figure out how to add the manifest attribute to the HTML tag in the index.html file with [HTMLWebpackPlugin](https://github.com/ampedandwired/html-webpack-plugin).

If you have any ideas, feel free to comment this issue or join the [Gitter channel](https://gitter.im/mxstbr/react-boilerplate).

Thanks for reporting this!
