### ISSUE TITLE
How to deploy app on IIS Server?

### ISSUE THREAD

**Issue by mihir-harbinger** [mxstbr/react-boilerplate#711]
I have back-end API written in ASP.NET Web API 2.0. I'm trying get this boilerplate work with it. What is the best way to deploy this app to IIS express or IIS Server? After building the react app I get a dump inside build directory. Do I directly serve that directory on IIS Server?

**Comment by mxstbr** [comment]
I've never used IIS, so I can't really help you here I'm afraid!

*I'll leave this open for a while, maybe somebody can chime in, but generally I recommend to ask questions in the Gitter channel since you'll get your answere much faster: https://gitter.im/mxstbr/react-boilerplate*

**Comment by tobyl** [comment]
I have limited experience with IIS, however since the build folder simple contains html and js files you should have no problem with any server capable of serving HTML and JS.

One minor issue I ran into when setting up is that the .htaccess file included in the build folder is needed for routing to work fully - in my case I could view the home page and navigate via links, but if I tried to type the URL to a specific page I would see an error. To solve this I enabled mod_rewrite - a Google search should reveal plenty of information about how to set this up on IIS.

Hope this helps.

**Comment by mihir-harbinger** [comment]
@mxstbr alright, I'lldo that. Thanks @tobyl. I'll try to serve build directory on IIS express first thing tomorrow.

Please keep this issue open for now. Thanks again for the help!

**Comment by tobyl** [comment]
no problem - let us know if it works.  :)

**Comment by mihir-harbinger** [comment]
It worked! As correctly mentioned by @tobyl I had to override default URL settings. I couldn't figure out how to do it using IIS URL rewriting module. Instead I wrote the rules in web.config of ASP.NET project. 

Another way is to create an empty MVC application and configure default routing in routeConfig.cs. You can find snippets on StackOverflow for the same. 

Hence closing the issue.

**Comment by aogut** [comment]
do you mind sharing the web.config or put up an empty boilerplate app on github?  thanks

**Comment by siddhanttambe** [comment]
+1 to @aogut 's comment.. Your boilerplate would really help.

**Comment by KarandikarMihir** [comment]
@aogut @siddhanttambe Here's the part of `web.config`-

```xml
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
```
