### ISSUE TITLE
Not being able to use the rewire library

### ISSUE THREAD

**Issue by aspglak** [mxstbr/react-boilerplate#712]
Hi,

Even if the documentation state that we can use the rewire library https://github.com/mxstbr/react-boilerplate/blob/master/docs/testing/unit-testing.md#rewire

I haven't seen it listed in the packages.json file or any configuration about it.

I tried to install it by adding  [babel-plugin-rewire](https://github.com/speedskater/babel-plugin-rewire) but unfortunately, I haven't been able to make it work.

Does somebody succeed ? If yes how did you configured it in the boilerplate ?

Thanks

**Comment by mxstbr** [comment]
Yes, this documentation page needs to be updated, you're right!

**Comment by oliverturner** [comment]
PR for fix & updated docs incoming

**Comment by mxstbr** [comment]
_ping_ any news here?

**Comment by oliverturner** [comment]
Buona sera! Been away for the last couple of weeks (business then holiday)... will get on this as soon as possible :)

**Comment by KarandikarMihir** [comment]
I had opened a similar issue #937 You might find these [remarks](https://github.com/mxstbr/react-boilerplate/issues/937#issuecomment-243678123) helpful. It describes how `rewire` doesn't play well with babel. It was overwhelming for me at that time, so I never took a dig at it.

**Comment by samit4me** [comment]
Yes, there are outstanding issues with both [rewire](https://github.com/speedskater/babel-plugin-rewire/issues/148) and [istanbul](https://github.com/istanbuljs/babel-plugin-istanbul/issues/22) and basically, there has been no progress even tho `rewire` closed the issue.

Just recently in the `dev` branch, [Jest](https://facebook.github.io/jest/) has been added (see #980), which has the ability to mock built into the testing framework itself, therefore removing the need for `rewire`.

Moving forward I would say that the testing documentation will need updating, but I am unsure when Jest will be merged into master, maybe @mxstbr can help answer this? Should we close this issue and open a new one to update testing documentation?

**Comment by mxstbr** [comment]
>  Should we close this issue and open a new one to update testing documentation?

Yes please!

**Comment by samit4me** [comment]
Okay great, closing this issue in favor of #1206.
