### ISSUE TITLE
Multi Tenant (theming)

### ISSUE THREAD

**Issue by tobyl** [mxstbr/react-boilerplate#717]
Hello all

I'm really enjoying working with the boilerplate so far, it's a great blend of simplicity and capability.

The question I'm wondering about is, what would be the simplest path towards using this for a multi tenant environment?

Here's my basic requirements:

* To have a default app with pages, components and containers
* To be able to additionally include CSS and custom components for another domain, but within the same codebase
* To be able to work in any tenant in dev, and then use `npm run build <tenant_name>`

I'm already using [this thread](https://github.com/mxstbr/react-boilerplate/issues/583#issuecomment-228056556) to implement variables for use in JS and CSS, so I'm wondering if the simplest path is individual webpack config files for each tenant. I'm not sure if I'd need to then go on to use separate entry point files for each tenant.

Another thought I had was to possibly use node environment variables, although I'm not sure if this would scale well.

Any thoughts or suggestions greatly appreciated!

**Comment by mxstbr** [comment]
I think you'd want to go with a separate entry point for each tenant, otherwise you'll end up copy-and-pasting the webpack config _a lot_.

I'll close this issue for now – hope you can figure it out!
