### ISSUE TITLE
Add NamedModulesPlugin

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#719]
Ref https://github.com/ericclemmons/webpack-hot-server-example/pull/7

```
[HMR] Updated modules:
[HMR]  - ./src/middleware/api.js
[HMR]  - ./src/app.js
[HMR] Update applied.
```

instead of

```
[HMR] Updated modules:
[HMR]  - 5
[HMR]  - 1
[HMR] Update applied.
```

**Comment by avdeev** [comment]
dont work for me

![image](https://cloud.githubusercontent.com/assets/1241671/19639086/860e4358-99df-11e6-8fa3-76d439e1d8a7.png)

**Comment by mxstbr** [comment]
Done in #1118! 

@avdeev are you on the `dev` version?
