### ISSUE TITLE
Should documentation include a step to checkout the latest version?

### ISSUE THREAD

**Issue by esseb** [mxstbr/react-boilerplate#72]
Following the documentation at https://github.com/mxstbr/react-boilerplate#getting-started you end up starting a project using the current master branch.

Shouldn't the documentation include a second step to checkout the 2.5.0 tag, or is master always kept in a "good to use" state?

**Comment by mxstbr** [comment]
Master is protected, i.e. it can only be accessed via PRs and only if the Travis check passes.

Will add some documentation for that, thanks for noticing!
