### ISSUE TITLE
Dev dependencies?

### ISSUE THREAD

**Issue by tomascharad** [mxstbr/react-boilerplate#720]
Hi,

Not sure, but maybe these dependencies should go on dev-dependencies:

react-redux, react-router, react-router-redux, react-router-scroll?

Or are they supposed to provide universal (isomorphic) features?

**Comment by gihrig** [comment]
Nope, those are the core of the boilerplate and any app created with it.

Suggest you look up those modules on npmjs.com to learn more about what they do.

Thanks for contributing!

**Comment by tomascharad** [comment]
Thanks @gihrig,

I know what they do, but at a first glance, your server doesn't depend upon those libraries.
Your clientSide app does, but after you have bundled these deps, they are no longer needed, or am I wrong?
In this case you only need these libraries for development only.

**Comment by gihrig** [comment]
I guess that depends on how you write your app. The whole point of react-boilerplate is integrating those libraries. If you app does not use them, feel free to make changes in your copy.

Remember, react-boilerplate is a starting point. Where you take your app from there is up to you.
