### ISSUE TITLE
WebStorm debugging tool didn't work out-of-the-box

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#721]
WebStorm is a great IDE
and i feel like many people also use this tool for debugging, if not Chrome Debugger Tool.

Basically, you can install JetBrain in Chrome Extension and then you can use this IDE for debugging.

However, with WebPack, we need source map file for debugging real file.
And with source map, look like JetBrain currently only work for this parameter in webpack config

`devtoo: 'source-map'`

I mean this line should change to the above config
https://github.com/mxstbr/react-boilerplate/blob/56eb5a0ec4aa691169ef427f3a0122fde5a5aa24/internals/webpack/webpack.dev.babel.js#L65

So it could make it work with JetBrain out-of-the-box

But i'm not sure what is the consequences, what do you think?

**Comment by gihrig** [comment]
The choice of source-map settings was made for performance reasons see #541 and #411.

Having said that, WebStorm is a popular IDE, if you would like to submit a PR to add the necessary configuration to get WebStorm's debugger working with react-boilerplate, that would be a helpful addition.

**Comment by mxstbr** [comment]
I don't think we should enable that source map by default to be honest, since not everybody will use WebStorm, but this should definitely be added to the FAQ! :+1: Good catch @chaintan17!

**Comment by gihrig** [comment]
> if you would like to submit a PR to add the necessary configuration to get WebStorm's debugger working

@mxstbr @chaintan17 Oops, I meant to say "... add the necessary configuration _to the docs_ to get...

My bad for not proofing 😦

**Comment by chaintan17** [comment]
i create pull request here https://github.com/mxstbr/react-boilerplate/pull/723

**Comment by mxstbr** [comment]
Done by the amazing @chaintan17 in #723!
