### ISSUE TITLE
Do we need more than one SPA in large site?

### ISSUE THREAD

**Issue by Lucas-Qi** [mxstbr/react-boilerplate#726]
So far, we have seen many Reactjs SPA(Singe Page App) demos like this one. This one is of course very good.

However, if we were to build a large website, I would think that maybe we need more than one SPA within that site.

For every part of the large site, we can have one SPA, that means, we would have one "bundle.js" for one part of the website.

Does this mean I need to have multiple WebPack instances runing to produce multiple "bundle.js"? Or is this boilerplate sufficient for a large site?

I know we can use Dynamic Router to split the SPA. But today the larges sites, like github, youtube, facebook, they are not a single SPA. 

What do you think is the best practice?

**Comment by rpoitras** [comment]
Hi Lucas,

We are being a new project and this starter is one of two that I am really interested in. I have the same question as you. I need to dig deeper into the authors documentation and see if there is guidance on the subject that I have missed. But seeing you've raised the topic, I thought I would weigh in. 😄 

I would prefer to work with one SPA for as long as possible. Regardless of that managing many routes is in my mind the major concern. How do we keep these organized and manageable in a large application? The `routes.js` file needs a plan to mitigate size. How do we structure the route hierarchy across `components` and `containers` with the content on one level getting to big? Having worked on many very large projects I painfully understand the perils of avoiding questions of scale early in a project.

I lean toward a structure that can grow and perhaps reflect the UI view hierarchy. Here are a couple links on the topic:
- [Fractal Project Structure with React and Redux - pros/cons](http://stackoverflow.com/questions/38130434/fractal-project-structure-with-react-and-redux-pros-cons)
- [A Better File Structure for React/Redux Applications](http://marmelab.com/blog/2015/12/17/react-directory-structure.html)
  - [Comments on above - reddit](https://www.reddit.com/r/reactjs/comments/47mwdd/a_better_file_structure_for_reactredux/)
- [Rules for Structuring Redux Applications](http://jaysoo.ca/2016/02/28/organizing-redux-application/)

**Comment by cristyansv** [comment]
I think this might help.
http://blog.mxstbr.com/2016/01/react-apps-with-pages/

**Comment by mxstbr** [comment]
There's two ways to go about this: a) use a new setup (i.e. boilerplate) for each SPA or b) tweak the webpack configuration to have multiple entry points.

Schematically, for b), in the webpack config, add `entry: [ 'app/app.js', 'secondapp/app.js' ]`. There might be a few kinks here and there but it should work.

We automatically code-split along the routes if you generate them, so those are separate bundles and only share the common code in a common bundle. I'd suggest using the Ryan Florence folder structure that @rpoitras posted, and having separate sub"apps" in each route that are completely code split and have their own components and containers. (that's what I generally do)

*(the article that @cristyansv posted is sadly far out of date, I need to update it with our new way of code splitting, though the result is the same)*

**Comment by Lucas-Qi** [comment]
Thanks a lot! @rpoitras @cristyansv @mxstbr 
It is really an art to structure the apps! 
: D
