### ISSUE TITLE
Redux-Form integration

### ISSUE THREAD

**Issue by akashshinde** [mxstbr/react-boilerplate#727]
I am using this boilerplate with `redux-form`, I have configured `redux-form`.It would be great to see `redux-form` with `react-boileplate`

**Comment by gihrig** [comment]
@akashshinde Do you mean to say you have redux form working with react-boilerplate?
If it's possible, any example code you could provide, perhaps as a GitHub gist, would be awesome!

It has been determined that redux-form is probably out of scope for this boilerplate project.
However, there are several issues on the subject #383, #453, #567.

I am attempting to put together a reference implementation with redux-form 6-rc3 that could be added to the docs as an example/recipe.

**Comment by tobyl** [comment]
I'd find this very useful too, and agree that it should be a recipe/example, not part of the base boilerplate.

**Comment by akashshinde** [comment]
@gihrig @tobyl 

> `redux-form` got support for immutable.js from V6.0 


Take a look at [link](http://redux-form.com/6.0.0-alpha.14/examples/immutable/) 


Tips to use `redux-form` with `react-boilerplate`

1. Use `Field` component provided by `redux-form` 
2. Add `form reducer` as shown in [docs](http://redux-form.com/6.0.0-alpha.14/docs/api/Reducer.md/)
3. Connect `dummy component` using `reduxForm()`

Import must be

`import { Field , reduxForm } from 'redux-form/immutable'`
 
Let me know if you want example, I will create gist for it

**Comment by tobyl** [comment]
Hi @akashshinde - this is useful, many thanks - I had 5.3.x installed, was not aware of v6.

Any gists you could provide would be greatly appreciated too though!

**Comment by mxstbr** [comment]
I'll close this since the question seems answered, feel free to continue discussing though!

**Comment by gargantuan** [comment]
I'd love to see a gist for this

**Comment by kopax** [comment]
@akashshinde would love aswell for the gist.

**Comment by carlos-peru** [comment]
I made a tiny example https://github.com/carlos-peru/react-boilerplate-redux-form.

**Comment by anhldbk** [comment]
For newer versions of `redux-form`, you should have a look at: http://redux-form.com/6.2.0/examples/immutable/

**Comment by lsanders** [comment]
For anyone else stumbling on this - it works perfectly, but you need to add the `form reducer` to the `app/reducers.js` and not any other containers (without tweaks)
