### ISSUE TITLE
Karma DEPRECATED warning

### ISSUE THREAD

**Issue by Rampage89** [mxstbr/react-boilerplate#728]
Dear All,

I installed latest clean version of the boilerplate. When i run the test, i encounter warning message from karma (please see the last line in code below). Would you please guide me what is causing the DEPRECATED message in karma?

Thanks and regards.

```
express@micro-ubuntu:~/web-ci$ npm run test
> react-boilerplate@3.0.0 pretest /home/express/web-ci
> npm run test:clean && npm run lint
> react-boilerplate@3.0.0 test:clean /home/express/web-ci
> rimraf ./coverage
> react-boilerplate@3.0.0 lint /home/express/web-ci
> npm run lint:js && npm run lint:css
> react-boilerplate@3.0.0 lint:js /home/express/web-ci
> npm run lint:eslint -- . 
> react-boilerplate@3.0.0 lint:eslint /home/express/web-ci
> eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."
> react-boilerplate@3.0.0 lint:css /home/express/web-ci
> stylelint ./app/**/*.css
> react-boilerplate@3.0.0 test /home/express/web-ci
> cross-env NODE_ENV=test karma start internals/testing/karma.conf.js --single-run
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
START:
```

**Comment by gihrig** [comment]
It's just Karma announcing that as of 2.0, Karma will no longer export lodash '_'. It's just a warning, not a problem, until Karma 2.0 is released.

[Karma source](https://github.com/karma-runner/karma/blob/5c6b151d4a1f553b81e2b07202dbec09de95d680/lib/helper.js#L172)
