### ISSUE TITLE
Revisiting ducks

### ISSUE THREAD

**Issue by wmertens** [mxstbr/react-boilerplate#729]
The way I understand it, the main reason that you don't like ducks is because of the somewhat weird exports structure. On the other hand, using them would provide the following benefits:
* Less clutter: only 1 file vs 3/4/5 (if you count sagas and selectors)
* Less boilerplate: no need to import constants
* All the code regarding certain state is colocated, making it easy to understand how each part integrates with other parts
  * For example, actions can see what the reducer expects, selectors can see how the reducer keeps state

So if the main argument is the export structure, how about making the exports explicit? Each duck should export at least the named exports `reducer` and `actions`. `reducer` is obvious, and `actions` is an object with all the actions the duck has.

This has the added advantage of being able to pass the actions object to react-redux's `connect` call without having to name them individually (so they don't exist outside the props scope) and without binding functions that are not actions.

Constants that need sharing (for example, a LOGOUT action type) could be optionally exported under `constants`.

Sagas and/or selectors could be put in there as well, under `sagas` and `selectors`, or at least exported from it.

The file could be called `ducks.js`, or maybe `redux.js` because it isn't quite the same.

**Comment by mxstbr** [comment]
(Ducks also make it seem like actions:reducers are a many:1 relationship, where in reality it's a many:many relationship and should be treated as such.)

I do agree that it's a useful pattern if the entire team knows what's up, so I won't keep anybody from doing it that way.

Imo this boilerplate has enough complexity as is, so I don't think including it by default is the way to go here. It'll just serve to confuse people, and it's another concept to explain.

**Comment by tomascharad** [comment]
Interesting the many:1 relationship POV.
