### ISSUE TITLE
move server folder into internals folder 

### ISSUE THREAD

**Issue by BraunreutherA** [mxstbr/react-boilerplate#738]
Hi, shouldn't the `server` folder get moved into the `internals` folder as it belongs to the build tool?
I personally thought in the first moment it would be one of these fullstack boilerplate projects which simply stick their server code int the client or the other way round which I really don't appreciate much.

**Comment by gihrig** [comment]
My feeling is that _server_ should remain where it is so developers understand its presence. It's intended to be replaced with a _real_ back-end server if that's what your project requires. #664 discusses that issue.

**Comment by mxstbr** [comment]
As @gihrig correctly mentions, the `server` is exactly where it should be! It isn't an internal feature, many people will want to add an API, a database, etc.

See the discussion in #211:

> I get the argument for keeping the root clean, but I'd balance it with the aim of making how the project works as self-evident as possible. More than that, if using the bundled server in production, I feel as though it has stopped being an internal feature and become a first-class element of the application.

– @oliverturner
