### ISSUE TITLE
Look into producthunt/chai-enzyme

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#74]
[Link](https://github.com/producthunt/chai-enzyme)

**Comment by vesln** [comment]
let me know if you need any assistance

**Comment by mxstbr** [comment]
@vesln thanks, will def do if something comes up!

**Comment by philihp** [comment]
I like it! I'll try to take a stab at it on v3.0.0 sometime this week.

**Comment by mxstbr** [comment]
:+1: nice @philihp!

**Comment by mxstbr** [comment]
Closed as of #104!
