### ISSUE TITLE
How to add react-bootstrap via npm?

### ISSUE THREAD

**Issue by bobkocisko** [mxstbr/react-boilerplate#741]
So I'm trying to add the react-bootstrap library and I'm unhappy with the solutions I've seen so far. I've read https://github.com/mxstbr/react-boilerplate/issues/238 but I would really prefer to use npm to install bootstrap-css-only rather than downloading bootstrap.min.css manually into a styles folder.  Also I'm looking for some guidance for how to best use the (global) react-bootstrap CSS with CSS Modules and PostCSS and Webpack.  I see that there is a bootstrap-css project but I'd rather use the original global CSS.  I've seen many different articles addressing these things separately but nothing within the context of react-boilerplate.  It would be super helpful for me to see a clear walkthrough on that. 

I tried to add bootstrap-css-only and react-bootstrap as a dependencies but I got this error when running npm install:
```
                      Asset     Size  Chunks             Chunk Names
reactBoilerplateDeps.dll.js  2.86 MB       0  [emitted]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 2.53 MB [rendered]
  [887] dll reactBoilerplateDeps 12 bytes {0} [built] [1 error]
     + 887 hidden modules

ERROR in ./~/bootstrap-css-only/css/bootstrap.min.css
Module parse failed: /home/.../node_modules/bootstrap-css-only/css/bootstrap.min.css Unexpected token (5:83)
You may need an appropriate loader to handle this file type.
```

**Comment by gihrig** [comment]
Did you see #595. I believe it addresses a similar problem.

**Comment by bobkocisko** [comment]
Thanks gihrig, that was close to what I'm looking for.  Here is how I ended up solving the error.

**package.json**
```
  "dllPlugin": {
    ...
    "exclude": [
      "bootstrap-css-only",
      ...
    ],
    ...
  },
  "dependencies": {
    ...
    "bootstrap-css-only": "3.3.6",
    ...
  },
```

**internals/config.js**
```js
const ReactBoilerplate = {
  /* ... */
  dllPlugin: {
    defaults: {
      /* ... */
      exclude: [
        'bootstrap-css-only',
        /* ... */
      ],

      /* ... */
};
```

As far as integration between the global css of bootstrap and the css-modules / PostCSS local css, there appears to be two options.  Either you can use `:global` in the css module to affect/override global styles, or you can create local styles to override the global ones and use [classnames](https://github.com/JedWatson/classnames) to combine both into one element, like so:

```jsx
import styles from './styles.css';
import classNames from 'classnames';
<div className={ classnames('container-fluid', styles.localContainer) }></div>
```

**Comment by gihrig** [comment]
Seems like an entry to docs/css explaining the use of global css libraries in general would be a welcome addition.

A PR would be awesome!

@mxstbr Agree?

**Comment by mxstbr** [comment]
Agree!

**Comment by gihrig** [comment]
@bobkocisko Would you consider writing this up as a docs/css/recipe and opening a PR?

It would be nice if it could be general in nature for adding any similar global library. It would be fine to use react-bootstrap as the example.

**Comment by bobkocisko** [comment]
Ok I'll try to get to it this weekend.

**Comment by bobkocisko** [comment]
https://github.com/mxstbr/react-boilerplate/pull/777

**Comment by bobkocisko** [comment]
Pull request, take 2: https://github.com/mxstbr/react-boilerplate/pull/802
