### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by rog** [mxstbr/react-boilerplate#746]
There is a way to make the greenkeeper updates once every week or something like that?
I think they are kind of spamy and most of them are minor updates.

Maybe one update every weekend in one PR with all the updates.

![screen shot 2016-07-18 at 16 43 26](https://cloud.githubusercontent.com/assets/1069532/16931571/3b369a8a-4d07-11e6-8633-0978e0445a6f.png)
![screen shot 2016-07-18 at 16 43 40](https://cloud.githubusercontent.com/assets/1069532/16931572/3c95d904-4d07-11e6-9099-0415c5145882.png)

**Comment by gihrig** [comment]
Funny, you should ask 😆 

I'm arriving at the same conclusion. There appears to be no way for GK to open a weekly update PR.  ref GK [#247](https://github.com/greenkeeperio/greenkeeper/issues/247)

I'm working on an update deps roll-up as we speak.

**Comment by gihrig** [comment]
@mxstbr I understand you are traveling? But, is it possible for you to disable Green Keeper?

It's actually less work, less spam and less confusion to manually do weekly roll-up updates, which I'm willing to continue doing.

**Comment by mxstbr** [comment]
Done, it's disabled! 

> It's actually less work, less spam and less confusion to manually do weekly roll-up updates, which I'm willing to continue doing.

Thanks for all the work you've been doing in keeping this repo sane, you rock! :tada:

**Comment by gihrig** [comment]
@mxstbr And You and this repo likewise rock - _that's_ why I'm here 💯
