### ISSUE TITLE
Getting issue on npm install

### ISSUE THREAD

**Issue by Bijayini** [mxstbr/react-boilerplate#752]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'npmcheckversion' ]
2 info using npm@2.14.12
3 info using node@v4.3.2
4 verbose run-script [ 'prenpmcheckversion',
4 verbose run-script   'npmcheckversion',
4 verbose run-script   'postnpmcheckversion' ]
5 info prenpmcheckversion react-boilerplate@3.0.0
6 info npmcheckversion react-boilerplate@3.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-boilerplate@3.0.0 Failed to exec npmcheckversion script
9 verbose stack Error: react-boilerplate@3.0.0 npmcheckversion: `node ./internals/scripts/npmcheckversion.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-boilerplate@3.0.0
11 verbose cwd /Users/bijayinp/react-boilerplate
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "npmcheckversion"
14 error node v4.3.2
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error react-boilerplate@3.0.0 npmcheckversion: `node ./internals/scripts/npmcheckversion.js`
17 error Exit status 1
18 error Failed at the react-boilerplate@3.0.0 npmcheckversion script 'node ./internals/scripts/npmcheckversion.js'.
18 error This is most likely a problem with the react-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./internals/scripts/npmcheckversion.js
18 error You can get their info via:
18 error     npm owner ls react-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by rog** [comment]
the problem is that you need `npm >= 3`, but i'm curious about the error. Can yo share more info about your system? SO, or the full `npm-debug.log` ?

**Comment by Bijayini** [comment]
<img width="1439" alt="screen shot 1938-04-28 at 9 14 42 pm" src="https://cloud.githubusercontent.com/assets/15208077/16956382/e6222196-4df5-11e6-90b3-05d1fe5c59e6.png">

**Comment by rog** [comment]
the issue you have is that you are using `npm 2.14` try updating to `npm 3` delete the `node_modules` folder and try `npm install` again.

**Comment by Bijayini** [comment]
Hey,

I tried npm install after deleting node_modules. It's giving the below error.
<img width="1439" alt="screen shot 1938-04-29 at 10 27 33 am" src="https://cloud.githubusercontent.com/assets/15208077/16975517/ed2537ac-4e64-11e6-82e9-02a40d014692.png">

**Comment by rog** [comment]
You still have `npm 2.14`, to update npm you need to execute: `npm install -g npm`, then again delete the `node_modules` folder and try `npm install` again.

**Comment by Bijayini** [comment]
Thank You.. It's working fine now.
