### ISSUE TITLE
Remove dollar sign ($) in front of terminal commands in docs

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#757]
When writing the docs I prefixed all terminal commands with `$` like so:

```
$ npm run something
```

Due to a recent discussion on twitter I've come to realize that this is confusing to some people, so we should remove all of the `$`. The above example would thus be:

```Sh
npm run something
```

----

*If you're keen to submit a Pull Request for this, please comment underneath stating that you're looking into it so we don't duplicate work! All of our documentation is either in `README.md` or the `docs/` folder in the root.*

**Comment by dmnkgrc** [comment]
I think I could do that :)

**Comment by mxstbr** [comment]
Awesome!!

If you're having troubles with git, Github or Pull Requests, please refer to Kent's excellent http://makeapullrequest.com for more information on how to properly fix this bug and submit a PR (Pull Request)!

**Comment by dmnkgrc** [comment]
Thanks!

**Comment by cesaredamico** [comment]
Well, historically the $ sign has a meaning which is still in use (terminal run by a user, not a super user, which would have the # sign), so perhaps for terminal-related docs that could be explained instead of removed?

**Comment by mxstbr** [comment]
It seems like beginners are confused about it, there was a whole discussion about it on Twitter, so I opted to remove it instead!
