### ISSUE TITLE
Automated browser testing

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#76]
I might look into adding automated browser testing to this boilerplate. Does anybody have experience with that? What's your preferred solution?

**Comment by zavelevsky** [comment]
I'm making a living out of automated visual testing, working at Applitools.
Would be thrilled to help out. I'm currently not near my laptop but we can
add basic e2e tests alongside the project. React also facilitates testing
isolated components visually by rendering only them. I'll be adding more
details soon.

**Comment by mxstbr** [comment]
@zavelevsky would love to hear more! I'm not sure automated browser testing is worth the time/effort, but I'll gladly let myself be convinced otherwise.

**Comment by zavelevsky** [comment]
Sure. What was your original intention then?

**Comment by mxstbr** [comment]
Learn more about it and see if it's viable and useful to include it by default. If not we can always add it to the advanced patterns documentation!

**Comment by zavelevsky** [comment]
You want it. Nothing beats automated e2e tests when it comes to user
interface. We can add a few simple tests based on selenium, with a few page
objects to match the boilerplate's examples.
I'll explain in more details once I'm united with my laptop :)

**Comment by mxstbr** [comment]
Sounds great, looking forward!

**Comment by mxstbr** [comment]
@zavelevsky any update on this? :eyes:

**Comment by giuseppeg** [comment]
If I may suggest a thing is to avoid 3rd parties services (e.g. Applitools).
The audience of this boilerplate is very broad and forcing people to use X-maybe-paid-if-not-OSS service is not optimal. However if you have to pick up a service I highly recommend SauceLabs (it is totally [free](https://saucelabs.com/opensauce/) for OSS). Selenium would be great, another interesting option would be [Integrator](https://github.com/phuu/integrator) although it is still at an early stage.
Either ways you may want to look into [zuul](https://github.com/defunctzombie/zuul) and please run tests in REAL browsers (not phantomjs) – for that you can take a look at [Xvfb](http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/) which is also [supported](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI) by Travis CI.
If you want to test CSS you can look into [tape-css](https://www.npmjs.com/package/tape-css), read the [related blog post](http://tomek.wiszniewski.cc/how-css-unit-tests-helped-us-move-fast/) and take a look at an [example](https://github.com/giuseppeg/suitcss-components-dropdown/pull/1) I wrote.

**Comment by eddiewang** [comment]
http://nightwatchjs.org/ i've been looking at this for browser testing at work... might be relevant. any thoughts @giuseppeg @zavelevsky @mxstbr

**Comment by mxstbr** [comment]
Due to little interest in this, I'll close this for now. Thanks for chiming in everybody!
