### ISSUE TITLE
Bug - generate route registers non-existent saga

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#761]
ref [#744 (comment)](https://github.com/mxstbr/react-boilerplate/pull/744#issuecomment-233851411)

Generating a route to a container with a reducer, but without a saga registers a saga in the route. This results in a broken route/container that is not trivial to fix.

Repro steps:
- Create a new container `npm run generate container` Accept defaults _except_ saga.
![image](https://cloud.githubusercontent.com/assets/1481063/16993282/86806a7e-4e57-11e6-8674-203350b8e52e.png)

- Create a route `npm run generate route`
![image](https://cloud.githubusercontent.com/assets/1481063/16993407/28c3b034-4e58-11e6-8f58-1771c2f5920c.png)

- Start server `npm start`
![image](https://cloud.githubusercontent.com/assets/1481063/16993535/af18930c-4e58-11e6-8468-91ec72727106.png)

- Edit ./app/routes.js to remove reference to saga
![image](https://cloud.githubusercontent.com/assets/1481063/16993748/764089a8-4e59-11e6-9d10-92c2b4d006c2.png)
![image](https://cloud.githubusercontent.com/assets/1481063/16993780/a50ee61c-4e59-11e6-9e93-d3a6d949430e.png)

- Restart server (no error), open `http://localhost:3000/test` Get blank screen and console error
![image](https://cloud.githubusercontent.com/assets/1481063/16993903/23a75824-4e5a-11e6-8d54-71654a3096da.png)

**Comment by mxstbr** [comment]
Fixed by the amazing @kraffslol in #762! :tada:

**Comment by gihrig** [comment]
Resolved by #762 PR
