### ISSUE TITLE
Bug(code style): new route: missing 'name' + unexpected line

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#765]
When a route is generated:
- There is no `name` property created for the new route block.
- An unexpected blank line is inserted into the wildcard block at the end of the routes.

Repro steps:
- Clone and `setup` a new copy of react-boilerplate

./app/routes snippet:
![image](https://cloud.githubusercontent.com/assets/1481063/17034204/7ab00e0e-4f36-11e6-9bbd-1b1d23cfeaa2.png)

- Add a new route /test -> features
![image](https://cloud.githubusercontent.com/assets/1481063/17034841/424e7d18-4f39-11e6-9ab8-7d806b0050db.png)
./app/routes snippet:
![image](https://cloud.githubusercontent.com/assets/1481063/17034327/1030dfd0-4f37-11e6-8192-24188f7cbb3e.png)

Mac OS 10.11.5
npm 3.8.2
node 5.8.0

Note: recent PR #762 may be _only partially_ implicated in this bug.
- The name: issue _was not_ observed in an earlier version of react-boilerplate
- The added line issue _was_ observed in an earlier version of react-boilerplate

**Comment by mxstbr** [comment]
Yeah, the added line issue drove me crazy, I couldn't figure out the right combination between the regex and the template to fix. The name bug is definitely new, PR anybody?

**Comment by kraffslol** [comment]
The no name issue is easily fixed by adding `name: '{{ camelCase component }}',` to route.hbs. The blank line is a mystery however.. It definitively looks like the culprit is the regex pattern.

**Comment by mxstbr** [comment]
PR maybe? :grin: @kraffslol

**Comment by gihrig** [comment]
Confirmed fixed 💯
