### ISSUE TITLE
Docs(code style) enhance contributing.md 

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#766]
The project seems to be gravitating towards a concise commit message style found in various places around the node/react community:

> `<type>(<scope>): <subject>`

That being the case, how about making it _official_ by including a _Commit Message Format_ section in `.github/CONTRIBUTING.md`?

An example that clearly delineates the above format can be found [here](https://github.com/erikras/react-redux-universal-hot-example/blob/master/CONTRIBUTING.md#commit-message-format).

I'm not particularly suggesting there's anything wrong with  @tbaggary's "A Note About Git Commit Messages", (currently referenced) but it seems to me more of a detailed discussion than a usable reference spec. 

I think the reference to @tbaggary's "A Note About Git Commit Messages" is useful and should remain as a reference, while a _Commit Message Format_ section is added to `.github/CONTRIBUTING.md`

Thoughts?

**Comment by mxstbr** [comment]
Fully agreed. Let's do it!

**Comment by justingreenberg** [comment]
I actually added that to RRSK 😜

**Comment by chaintan17** [comment]
How about this tool, will it produce higher effort?
https://www.npmjs.com/package/commitizen

**Comment by mxstbr** [comment]
Yes! We should add commitizen @chaintan17!

**Comment by gihrig** [comment]
Commitizen tooks "mega-cool" 😃 

I'll mention it in the reworked setup UX #760

OT: After a few "scuffles" with git cli, I use [GitUp](https://github.com/git-up/GitUp) for every-day git work (Highly recommended - especially for branching and merging).  Commitizen just might draw me back to the cli 😉

**Comment by mxstbr** [comment]
Closing since this is tracked in #760!
