### ISSUE TITLE
reactBoilerplateDeps: Module not found errors on Windows 7

### ISSUE THREAD

**Issue by edoloughlin** [mxstbr/react-boilerplate#769]
## Description

Webback can't resolve modules when building reactBoilerplateDeps

## Steps to reproduce

running `npm run setup` goes ok until it tries to run internals/dependencies.js:

```
> node ./internals/scripts/dependencies.js

Building the Webpack DLL...
Hash: c2d0bb44497ebed0b2ce
Version: webpack 1.12.14
Time: 82ms
                      Asset     Size  Chunks             Chunk Names
reactBoilerplateDeps.dll.js  1.65 kB       0  [emitted]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 12 bytes [rendered]
    [0] dll reactBoilerplateDeps 12 bytes {0} [built] [19 errors]

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'babel-polyfill' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'fontfaceobserver' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react-router-scroll' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'redux' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'redux-immutable' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'redux-saga' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'reselect' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'whatwg-fetch' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'core-js' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'lodash' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'eventsource-polyfill' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'history' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'immutable' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react-dom' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react-helmet' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react-redux' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react-router' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps

ERROR in dll reactBoilerplateDeps
Module not found: Error: Cannot resolve module 'react-router-redux' in C:\Users\a\git\react-boilerplate-test2
 @ dll reactBoilerplateDeps
npm info lifecycle react-boilerplate@3.0.0~postbuild:dll: react-boilerplate@3.0.0
npm info ok
npm info ok

```

# Versions

- Node: 6.3.1
- NPM: 3.10.5
- OS: Windows 7
- Browser: N/A

**Comment by gihrig** [comment]
Try `npm cache clean` then start over with a new clone of react-boilerplate.

**Comment by edoloughlin** [comment]
I get the same error.

**Comment by edoloughlin** [comment]
Got it working. I had to 
    npm cache clean
    npm install
    npm install eslint -g
    npm run setup

The 'Installing dependencies...' part of the setup seems to do nothing on Windows. The node_modules directory is empty after this completes.

**Comment by gihrig** [comment]
I'm curious to see what happens if you:
- Clone a new copy of react boilerplate
- Edit package.json to remove scripts `preinstall` and `postinstall`
- run `npm install` You should end up with something like 1154 items in `node_modules`

If you do not get the expected node_modules, please post your `npm-debug.log`

If you do get the expected node modules, run 
`npm run build:dll`

Then
`npm start`

Let us know what happens.

**Comment by cenmeejs** [comment]
ERROR in ./test.gif
    Module build failed: Error: ϵͳ�Ҳ���ָ����·����

        at notFoundError (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\cross-spawn\lib\enoent.js:11:11)
        at verifyENOENT (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\cross-spawn\lib\enoent.js:46:16)
        at ChildProcess.cp.emit (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\cross-spawn\lib\enoent.js:33:19)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
     @ ./app.js 1:0-21

    ERROR in ./test.png
    Module build failed: Error: ϵͳ�Ҳ���ָ����·����

        at notFoundError (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\image-webpack-loader\node_modules\imagemin-optipng\node_modules\exec-buffer\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:8:11)
        at verifyENOENT (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\image-webpack-loader\node_modules\imagemin-optipng\node_modules\exec-buffer\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:43:16)
        at ChildProcess.cp.emit (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\image-webpack-loader\node_modules\imagemin-optipng\node_modules\exec-buffer\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:30:19)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
     @ ./app.js 3:0-21

    ERROR in ./test.jpg
    Module build failed: Error: ϵͳ�Ҳ���ָ����·����

        at notFoundError (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\image-webpack-loader\node_modules\imagemin-jpegtran\node_modules\exec-buffer\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:8:11)
        at verifyENOENT (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\image-webpack-loader\node_modules\imagemin-jpegtran\node_modules\exec-buffer\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:43:16)
        at ChildProcess.cp.emit (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\image-webpack-loader\node_modules\imagemin-jpegtran\node_modules\exec-buffer\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:30:19)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
     @ ./app.js 2:0-21

**Comment by cenmeejs** [comment]
I get the same error,too

**Comment by cenmeejs** [comment]
when I use **gulp** minify images. get this error,too(I use Window 7)
```
λ gulp
[10:16:17] Using gulpfile D:\mjx_project\proj_mjx_web_v1.0\B2CUI\gulpfile.js
[10:16:17] Starting 'default'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
 Error: ϵͳ�Ҳ���ָ����·����

    at notFoundError (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (D:\mjx_project\proj_mjx_web_v1.0\B2CUI\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by gihrig** [comment]
Are by any chance using [cnpm](https://cnpmjs.org/)? Try main npm see [#467 (comment)](https://github.com/mxstbr/react-boilerplate/issues/467#issuecomment-234755898).

**Comment by cenmeejs** [comment]
Thank a lot .My problem has been resolved.I remove all node_modules that install from **cnpm** .then use **npm** install again ,then the errors disappear

**Comment by edoloughlin** [comment]
@gihrig install and build:dll complete without errors. When I run npm start and then try to access localhost:3000 I get (in the console): 

```
git/react-boilerplate-tester ‹master› » npm start
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
npm info ok
npm info it worked if it ends with ok
npm info using npm@3.10.5
npm info using node@v6.3.1
npm info lifecycle react-boilerplate@3.0.0~prestart: react-boilerplate@3.0.0
npm info lifecycle react-boilerplate@3.0.0~start: react-boilerplate@3.0.0

> react-boilerplate@3.0.0 start C:\users\a583741\git\react-boilerplate-tester
> cross-env NODE_ENV=development node server

Server started ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://10.132.136.151:3000
-----------------------------------
Press CTRL-C to stop

webpack built 05cff1c4a2e85635aa72 in 18582ms

ERROR in ./app/containers/App/banner-metal.jpg
Module build failed: Error: The system cannot find the path specified.

    at notFoundError (C:\Users\a\git\react-boilerplate-tester\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\a\git\react-boilerplate-tester\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\a\git\react-boilerplate-tester\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 @ ./app/containers/App/index.js 17:0-40
Child html-webpack-plugin for "index.html":
```

**Comment by gihrig** [comment]
The warnings are generally not significant. 
As for Windows 10, it has recently been confirmed to [build correctly](https://github.com/mxstbr/react-boilerplate/issues/739#issuecomment-233728900).

`./app/containers/App/index.js` line 17 is attempting to import `banner-metal.jpg` from the same folder, does that file exist?

I'm just guessing here, but if the file exists try [these steps](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/remove.md#removing-image-optimization) and see what happens.

**Comment by edoloughlin** [comment]
The file exists. Your suggestion for removing image-webpack worked. Looks like there's a regression in npm 3 on windows: https://github.com/tcoopman/image-webpack-loader/issues/16

**Comment by gihrig** [comment]
That was a tough one, well done on finding it!

npm 3.10.6 might have a relevant [fix](https://github.com/npm/npm/blob/master/CHANGELOG.md#better-path-lifecycle-behavior).

Note that react-boilerplate has a requirement for npm 3+

**Comment by sourcesoft** [comment]
> I'm just guessing here, but if the file exists try these steps and see what happens

Mine worked after removing image optimization.

**Comment by ubergarm** [comment]
I just had the same problem with the `ERROR in ./app/containers/App/banner-metal.jpg` business in Linux under Docker. 

You can quickly repeat and fix this error using the following steps.

Freshly clone the repo and get inside a Docker container:
```bash
git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
cd react-boilerplate
docker run -v `pwd`:/app -p 3000:3000 --rm -it --entrypoint=/bin/sh mhart/alpine-node
```

Inside the Docker container:
```bash
node --version #v6.4.0
npm --version #3.10.6
cd /app
npm run setup
npm start
```

The fix for me was the same as what @sourcesoft and @gihrig recommended: removing optimizations then running `npm start` again.

Edit `react-boilerplate/internals/webpack/webpack.base.babel.js` and remove one line:

Original:
```bash
    test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}',
      ],
```

Fixed:
```bash
    test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
      ],
```
