### ISSUE TITLE
Do not delete existed .git folder

### ISSUE THREAD

**Issue by istinspring** [mxstbr/react-boilerplate#770]
I have existed project with django app (API, backend) and decided to use react-boilerplate since i found codebase and style really close to what i'm usually doing (actually what i usually want to do), was able to manually change paths in package.json and some files to make npm commands (at least setup and start) run with frontend/....

Wow, that's great i though... and tried to commit the changes, but something went wrong => checked my .git folder => WTF???! => setup.js

```
/**
 * Deletes the .git folder in dir
 */
function cleanRepo(dir, callback) {
  exec('rm -Rf .git/', addCheckMark.bind(null, callback));
}
```

Guys this really fucked, do not do it, let user decide what to delete, especially such sensitive thing. Or check at least if it's same .git folder as in react-boilerplate repository

**Comment by gihrig** [comment]
Wow! so sorry to hear that 😢 

See #760
