### ISSUE TITLE
Production environment multistage child routes by repeated load file

### ISSUE THREAD

**Issue by fuxianwei** [mxstbr/react-boilerplate#778]
I configured with a in the routing configuration items childRoutes by, the development environment running on demand load is normal, when I am in a production environment neutron routing problems on demand loading, primary routing without problems, more than secondary child Routes by the repeated loading.Such as:I under the admin routing configuration by a usermanage childRoutes, run (NPM run start: production) start production environment server, direct access to the http://localhost:3000/admin/usermanage appear file to load
![image](https://cloud.githubusercontent.com/assets/1736689/17089523/2c57ed18-525a-11e6-820d-8dfedde998bc.png)

How do I configure child Routes by, thank you！

The routing configuration
`import { getAsyncInjectors } from 'utils/asyncInjectors';

const errorLoading = (err) => {
  console.error('Dynamic page loading failed', err); // eslint-disable-line no-console
};

const loadModule = (cb) => (componentModule) => {
  cb(null, componentModule.default);
};

export default function createRoutes(store) {
  // Create reusable async injectors using getAsyncInjectors factory
  const { injectReducer, injectSagas } = getAsyncInjectors(store);

  return [
    {
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/HomePage/reducer'),
          System.import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, component]) => {
          injectReducer('home', reducer.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }, {
      path: '/admin',
      name: 'admin',
      indexRoute: {onEnter: (nextState, replace) => replace('/admin/usermanage')},
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/AdminPage/reducer'),
          System.import('containers/AdminPage/sagas'),
          System.import('containers/AdminPage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('admin', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
      childRoutes: [
        {
          path: '/admin/usermanage',
          name: 'usermanage',
          getComponent(nextState, cb) {
            System.import('containers/admin/UserManagePage')
              .then(loadModule(cb))
              .catch(errorLoading);
          },
        }
      ],
    }, {
      path: '*',
      name: 'notfound',
      getComponent(nextState, cb) {
        System.import('containers/NotFoundPage')
          .then(loadModule(cb))
          .catch(errorLoading);
      },
    },
  ];
}`

**Comment by freemanon** [comment]
I'm facing the same issue here. I have a page with different tabs, where the tabs are defined in `childRoutes`.

```javascript
{
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/Competitions/reducer'),
          System.import('containers/Competitions/sagas'),
          System.import('containers/Competitions/Competition')
        ])

        const renderRoute = loadModule(cb)

        ...
      },
      childRoutes: [
        {
          path: '/competition/:competitionId',
          name: 'competition',
          getComponent(nextState, cb) {
            const importModules = Promise.all([
              System.import('containers/Competitions/Competition/Tabs/Summary')
            ])
          ...
        },
        {
          path: '/competition/:competitionId/teams',
          name: 'competition-teams',
          getComponent(nextState, cb) {
            const importModules = Promise.all([
              System.import('containers/Competitions/Competition/Tabs/Teams')
            ])
          ...
        }
```

But the parent route's saga gets cancelled you navigate to another tab, because we're listening to *any* `LOCATION_CHANGE`.

Should each child route import all the sagas it needs? But then it seems inefficient to cancel and re-inject the same sagas again and again.

**Comment by mxstbr** [comment]
> But the parent route's saga gets cancelled you navigate to another tab, because we're listening to any LOCATION_CHANGE.

This is exactly the reason we don't cancel them on route change automatically – **you can adjust this behaviour in your saga!**

**Comment by freemanon** [comment]
> you can adjust this behaviour in your saga!

I was thinking of that, checking `LOCATION_CHANGE`'s payload, but I couldn't find anything in `react-router-redux` to match the parent's (dynamic) path. There used to be `isActive` in `react-router` but it's not exposed by `react-router-redux`. Could you show me a quick example please? :)

**Comment by fuxianwei** [comment]
Behind me disabled appchache, modify webpack. Prod. Babel. Js file, the
`AppCache: {/ / Starting from offline - plugin: v3, AppCache by default caches only/ / ` main ` section. This lets it use ` additional ` section tooCaches: [' main ', 'additional'].},`
Modified into
`AppCache: false`
You try again,So that we can solve this problem, but I don't know exactly what causes the problem.

**Comment by freemanon** [comment]
Actually I think we might have different problems here.. Misunderstood your first post

**Comment by freemanon** [comment]
Hi @mxstbr, could you please give me a hint on how to cancel sagas conditionally? I'd really appreciate it :)

**Comment by mxstbr** [comment]
Something like this? 

```
const watcher = yield fork(someSaga);

yield take(SOME_ACTION);
yield cancel(watcher);
```
