### ISSUE TITLE
AppCache didn't cache other pages beside homepage (/)

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#779]
We do cache all the webpack file using AppCache
However, look like it currently only cache for `/` page but not the other.
I'm guessing it may be because of the maifest file is only set for `/` page
(http://www.html5rocks.com/en/tutorials/appcache/beginner/#toc-manifest-file-creating)

I still not sure how to fix it...

**Step to reproduce**
1. Checkout the project 
2. `npm run setup`
2. `npm run start:production`
3. open `http://localhost:3000`
4. click feature page
5. set throttling to offline
6. refresh the page
7. Chrome browser cannot reach the /feature page

(EDIT 1 :Update reproduce steps)

**Comment by mxstbr** [comment]
I think this might be due to your webserver configuration, but I can't say for sure. @NekR is there anything the offline-plugin can do to fix this?

**Comment by gihrig** [comment]
> Step to reproduce
> 1. Checkout the project 
> 2. npm run start:prod
> 3. click feature page
> 4. set throttling to offline
> 5. refresh the page
> 6. Chrome browser cannot reach the /feature page

Hmm... Some steps missing (perhaps you just forgot to list?)
1.5 npm run setup
2. should be `npm run start:production` (`start:prod` needs a previous build, it only starts the server).

I have found that off-line mode only works when the page is called through the router, not the address line.

Do the same as ss you did before, except:

At step 5, open localhost:3000
At step 6, click `Features` button at bottom of home page.

I'm not saying this is correct behavior, but that seems to be the way it works.

**Comment by NekR** [comment]
@mxstbr were you able to reproduce the bug? Is all routing (e.g. `/feature`) generated by webpack as its output (e.g. by `HtmlWebpackPlugin`)?

`offline-plugin` doesn't add manifest to your `index.html` or any other page, instead it load specially generated iframe which initializes AppCache. All pages which should be cached are explicitly defined in AppCache Manifest. `offline-plugin` takes the information about which files to cache from webpack's `compilation.assets`,  basically it's a list of your webpack build output files. 

So if `/feature` isn't loading, then it's simply not listed in AppCache Manifest (and I'm sure it won't work for SW too then).

Can anyone provide output of `appcache/appcache.manifest` content and `sw.js` JSON header part here?

**Comment by chaintan17** [comment]
Hi @NekR , thanks for your help.

Below is the content of `manifest.appcache`

```
CACHE MANIFEST
 #ver:7/25/2016, 5:06:41 PM

 CACHE:
 /f32ac9f0ee23aea6ac9fb2f499e1db0d.png
 /manifest.json
 /dc2d76295bb6814ab407d9a82a4b54dd.svg
 /7a357f044443d31dfcd85ca557b96b4e.jpg
 /df074277130ff41c7f81d95681b70813.gif
 /main.455f95f2833dc946550d.js
 /vendor.a365efae2e02ae200374.js
 /main.ecf86f8aa47d50463dc170fcb5b2f678.css
 /
 /1.d1129d400e98e514797b.chunk.js
 /2.2de7d9e0c13a51543be9.chunk.js
 /3.34bbfdc2f3b322dd4928.chunk.js
 /4.da846f630ff49c3b96a1.chunk.js
 /5.70552ab8bc3a978a5e94.chunk.js
 /6.ee2fec1b340faaabb779.chunk.js
 /7.39cdf168a63055d5c3a6.chunk.js
 /8.f81502f7d57792e32fd1.chunk.js
 /9.98dcb7fdc2b937abc049.chunk.js
 /10.814be16c34fcc144589d.chunk.js
 /11.45466fdb76cf19390826.chunk.js
 /12.ebc86b7ae82076b0212c.chunk.js
 /13.2face4ddcdc91244319c.chunk.js
 /14.9113a3b113d4ea8da580.chunk.js
 /15.5851594e0c826fb4ffc9.chunk.js
 /16.d9a44483f985a7faa6c3.chunk.js
 /17.1deeffbdc79befa45272.chunk.js

 NETWORK:
 *
```

and `sw.js` (not sure what you mean by JSON header?)
```
 var __wpo = {"assets":{"main":["/f32ac9f0ee23aea6ac9fb2f499e1db0d.png","/manifest.json","/                  dc2d76295bb6814ab407d9a82a4b54dd.svg","/7a357f044443d31dfcd85ca557b96b4e.jpg","/                            df074277130ff41c7f81d95681b70813.gif","/main.455f95f2833dc946550d.js","/vendor.a365efae2e02ae200374.js","/  main.ecf86f8aa47d50463dc170fcb5b2f678.css","/"],"additional":["/1.d1129d400e98e514797b.chunk.js","/2.       2de7d9e0c13a51543be9.chunk.js","/3.34bbfdc2f3b322dd4928.chunk.js","/4.da846f630ff49c3b96a1.chunk.js","/5.   70552ab8bc3a978a5e94.chunk.js","/6.ee2fec1b340faaabb779.chunk.js","/7.39cdf168a63055d5c3a6.chunk.js","/8.   f81502f7d57792e32fd1.chunk.js","/9.98dcb7fdc2b937abc049.chunk.js","/10.814be16c34fcc144589d.chunk.js","/11. 45466fdb76cf19390826.chunk.js","/12.ebc86b7ae82076b0212c.chunk.js","/13.2face4ddcdc91244319c.chunk.js","/   14.9113a3b113d4ea8da580.chunk.js","/15.5851594e0c826fb4ffc9.chunk.js","/16.d9a44483f985a7faa6c3.chunk.js",  "/17.1deeffbdc79befa45272.chunk.js"],"optional":[]},"hashesMap":{"f32ac9f0ee23aea6ac9fb2f499e1db0d":"/      f32ac9f0ee23aea6ac9fb2f499e1db0d.png","3b84809ee9f3b83cab63901f7c241096":"/manifest.json",                  "dc2d76295bb6814ab407d9a82a4b54dd":"/dc2d76295bb6814ab407d9a82a4b54dd.svg",                                 "7a357f044443d31dfcd85ca557b96b4e":"/7a357f044443d31dfcd85ca557b96b4e.jpg",                                 "df074277130ff41c7f81d95681b70813":"/df074277130ff41c7f81d95681b70813.gif",                                 "455f95f2833dc946550dd8db15d8fd8e":"/main.455f95f2833dc946550d.js","d1129d400e98e514797b23401dbbf159":"/1.  d1129d400e98e514797b.chunk.js","2de7d9e0c13a51543be910e767c668f1":"/2.2de7d9e0c13a51543be9.chunk.js",       "34bbfdc2f3b322dd492814a4eb71a5ba":"/3.34bbfdc2f3b322dd4928.chunk.js","da846f630ff49c3b96a114d36b54840e":"/ 4.da846f630ff49c3b96a1.chunk.js","70552ab8bc3a978a5e94d81774c900c9":"/5.70552ab8bc3a978a5e94.chunk.js",     "ee2fec1b340faaabb779f4ca02d1ebd0":"/6.ee2fec1b340faaabb779.chunk.js","39cdf168a63055d5c3a63a320dc8597a":"/ 7.39cdf168a63055d5c3a6.chunk.js","f81502f7d57792e32fd17faaa4fa96ce":"/8.f81502f7d57792e32fd1.chunk.js",     "98dcb7fdc2b937abc049447a46350182":"/9.98dcb7fdc2b937abc049.chunk.js","814be16c34fcc144589d46d8ab888ac0":"/ 10.814be16c34fcc144589d.chunk.js","45466fdb76cf193908260b1ea38558e1":"/11.45466fdb76cf19390826.chunk.js",   "ebc86b7ae82076b0212c1663c8319970":"/12.ebc86b7ae82076b0212c.chunk.js","2face4ddcdc91244319c629e0de307f9":  "/13.2face4ddcdc91244319c.chunk.js","9113a3b113d4ea8da5809e66ce9a59f7":"/14.9113a3b113d4ea8da580.chunk.js", "5851594e0c826fb4ffc95e4a6b926651":"/15.5851594e0c826fb4ffc9.chunk.js","d9a44483f985a7faa6c382ddd70bb113":  "/16.d9a44483f985a7faa6c3.chunk.js","1deeffbdc79befa45272c55b6bdf29df":"/17.1deeffbdc79befa45272.chunk.js", "a365efae2e02ae200374141be7df1f63":"/vendor.a365efae2e02ae200374.js","ecf86f8aa47d50463dc170fcb5b2f678":"/  main.ecf86f8aa47d50463dc170fcb5b2f678.css","1905fdcaee622a2a50b4324407dd592c":"/"},"strategy":"all",        "version":"7/25/2016, 5:06:41 PM","name":"webpack-offline","relativePaths":false};
```

response header
```
Accept-Ranges:bytes
Cache-Control:public, max-age=0
Content-Encoding:gzip
Content-Type:application/javascript
Date:Mon, 25 Jul 2016 10:10:21 GMT
ETag:W/"3897-15621855368"
Last-Modified:Mon, 25 Jul 2016 10:06:41 GMT
Vary:Accept-Encoding
X-Powered-By:Express
```

**Comment by NekR** [comment]
> not sure what you mean by JSON header?

Yes, I meant `__wpo` variable. It contains settings for SW.

Okay, so as you see, manifest caches only only routing navigation page, it's `/`. @mxstbr I don't know  the `react-boilerplate` structure, what else pages should be cached? I'll add everything, just need to know what to add.

@chaintan17 btw, do you really have duplicated `CACHE MANIFEST` section?

**Comment by mxstbr** [comment]
```
../1.8ffb56943b71177183c3.chunk.js
../2.e52977f3e473d29fc257.chunk.js
../3.84d6eec430f7d079d5b6.chunk.js
../4.d2968c6386f2231a4c07.chunk.js
../5.b88f6611edefc4bd4be0.chunk.js
```

actually are the pages, so this doesn't look like a problem with the `offline-plugin`, it looks like the problem is that the `index.html` file at the root of the page isn't returned, which makes sense now that I think about it like that.

Basically, we use client-side routing for our pages and redirect all request to any page to `/index.html`, which loads the main bundle and takes care of routing the user to the correct page on the client. AppCache when offline doesn't do that redirection, which is why nothing is loading. I'm actually not sure if there's much we can do here…

**Comment by chaintan17** [comment]
No, duplicated CACHE MANIFEST is my fault. Please ignore it. Comment updated.

**Comment by NekR** [comment]
@mxstbr In such situations when I need support of the AppCache, I do the routing with hash `#` .

One possible solution could be to use `FALLBACK` section of the AppCache. It may look like this:

```js
new OfflinePlugin({
  relativePaths: false,
  publicPath: '/',

  // No need to cache .htaccess. See http://mxs.is/googmp,
  // this is applied before any match in `caches` section
  excludes: ['.htaccess'],

  caches: {
    main: [':rest:'],

    // All chunks marked as `additional`, loaded after main section
    // and do not prevent SW to install. Change to `optional` if
    // do not want them to be preloaded at all (cached only when first loaded)
    additional: ['*.chunk.js'],
  },

  // Removes warning for about `additional` section usage
  safeToUseOptionalCaches: true,

  AppCache: {
    // Starting from offline-plugin:v3, AppCache by default caches only
    // `main` section. This lets it use `additional` section too
    caches: ['main', 'additional'],
    FALLBACK: {
      '/': '/'
    }
  },

  ServiceWorker: {
    navigateFallbackURL: '/'
  }
})
```

For SW, it's better to have/specify routing map to be precise about what it going on. Unfortunately `offline-plugin` doesn't yet support runtime routing maps, so we can use `navigateFallbackURL` which behaves almost the same as AppCache's `FALLBACK` section here.

If it's fine and solves the problem, I'll do the PR.

**Comment by chaintan17** [comment]
@NekR yes it's work! that's fantastic! 👍

**Comment by NekR** [comment]
@chaintan17 great!
@mxstbr What do you think, should I add it?

**Comment by chaintan17** [comment]
![image](https://cloud.githubusercontent.com/assets/2979072/17104095/9748c826-52ab-11e6-9f3c-3977b69e8ef6.png)

In boilerplate, it's okay
but not in my real project. do you have any idea about this Failed to parse manifest error?

below is manifest.appcache content.
```
CACHE MANIFEST
#ver:7/22/2016, 3:24:25 PM

CACHE:
/da12c8821843ee50775c875c1789e3cf.png
/manifest.json
/dc2d76295bb6814ab407d9a82a4b54dd.svg
/7a357f044443d31dfcd85ca557b96b4e.jpg
/df074277130ff41c7f81d95681b70813.gif
/main.ef9951ac120f16f5b4c3.js
/vendor.a365efae2e02ae200374.js
/main.f610cdfdf2ef7c2685e758453e00b1e2.css
/
/1.e551649a28c42c88b89f.chunk.js
/2.75f89aaa24fefe4b00d3.chunk.js
/3.61ca1831042183df3055.chunk.js
/4.699c2881450aa894daae.chunk.js
/5.df9802d36c6018ccac35.chunk.js
/6.e965354ebc6a90db1b23.chunk.js
/7.a6838d89957b065f18e8.chunk.js
/8.7dbbab7e37013071380e.chunk.js
/9.fa3f3fe1dc88360e0576.chunk.js
/10.974fa5ccb6560b84710f.chunk.js
/11.e127c0b6e423326eefd0.chunk.js
/12.ebc86b7ae82076b0212c.chunk.js
/13.2face4ddcdc91244319c.chunk.js
/14.9113a3b113d4ea8da580.chunk.js
/15.5851594e0c826fb4ffc9.chunk.js
/16.d9a44483f985a7faa6c3.chunk.js
/17.1deeffbdc79befa45272.chunk.js

NETWORK:
*
```

**Comment by NekR** [comment]
@chaintan17 hmm.. code of a manifest looks normal to me, expect that it doesn't have `FALLBACK` section.

This is how it should look with `FALLBACK` section:

```
CACHE MANIFEST
#ver:v2016-07-19 12:52:27

CACHE:


NETWORK:
*

FALLBACK:
/ /
```

Can you try again / rebuild your project?

**Comment by NekR** [comment]
I just google parse problem and here is what I found:

AppCache validator: http://manifest-validator.com/
Similar problem on SO: http://stackoverflow.com/questions/28759759/appcache-manifest-error-4

**Comment by chaintan17** [comment]
thanks @NekR 
You're right, it should have FALLBACK show in manifest.
Somehow, i deploy to heroku-like and my build is failed without and error.
After new deploy, it work 👍 🎉

**Comment by mxstbr** [comment]
We no longer recommend using AppCache as per the discussion in #450 thanks to @sethmcleod and #791 – is there something actionable for us to implement here?

**Comment by NekR** [comment]
Yeah, I 100% agree AppCache shouldn't be used where possible. This is how I use AppCache in `offline-plugin` (just to show custom "offline" page):

```
AppCache: {
  caches: [],
  FALLBACK: {
    '/': '/offline/offline.html',
    '/assets/': '/offline/offline-asset',
    '/icons/': '/offline/offline-asset',
  }
}
```

Disabling it completely is also completely fine. I guess this one should be closed then.
