### ISSUE TITLE
Add resolve.root to webpack config

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#78]
https://webpack.github.io/docs/configuration.html#resolve-root

Also don't forget to document it somewhere highly visible, otherwise beginners might be confused by the magic.

**Comment by mxstbr** [comment]
Closed in 17afa69

**Comment by sedubois** [comment]
This is actually an issue for IDEs such as my IntelliJ IDEA (uses same engine as WebStorm), it cannot resolve these "absolute" paths. Is there any way to fix? I created a JetBrains issue: https://youtrack.jetbrains.com/issue/WEB-23822

**Comment by sedubois** [comment]
Was marked as duplicate of https://youtrack.jetbrains.com/issue/WEB-17254, still open. But there's the workaround mentioned of marking manually `app` as resources root (right-click > Mark Directory As > Resources Root) 😊
