### ISSUE TITLE
Add react frontend obfuscation demo

### ISSUE THREAD

**Issue by mauvew** [mxstbr/react-boilerplate#780]
## Description
Is it possible to add a demonstration to show that how to obfuscate the frontend code? When saying obfuscation, I mean the kind of way to uglify the react code to make it difficult to read or copy for other people. Otherwise, it can be very easy to copy some code using tools like chrome developer tool or firebug 

This can be very useful for production :smile:

**Comment by gihrig** [comment]
Minified code not obscure enough?

e.g.
`!function(t){function e(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}};return t[n].call(o.exports,o,o.exports,e),o.l=!0,o.exports}var n=window.webpackJsonp;window.webpackJsonp=function(e,r,i){for(var a,u,s=0,c=[];s<e.length;s++)u=e[s],o[u]&&c.push(o[u][0]),o[u]=0;for(a in r)if(Object.prototype.hasOwnProperty.call(r,a)){var l=r[a];switch(typeof l){case"object":t[a]=function(e){var n=e.slice(1),r=e[0];return function(e,o,i){t[r].apply(this,[e,o,i].concat(n))}}(l);break;case"function":t[a]=l;break;default:t[a]=t[l]}}for(n&&n(e,r,i);c.length;)c.shift()()};var r={},o={0:0,6:0};return e.e=function(t){function n(){i.onerror=i.onload=null,clearTimeout(a);var e=o[t];0!==e&&(e&&e[1](new Error("Loading chunk "+t+" failed.")),o[t]=void 0)}if(0===o[t])return Promise.resolve();if(o[t])return o[t][2];var r=document.getElementsByTagName("head")[0],i=document.createElement("script");i.type="text/javascript",i.charset="utf-8",i.async=!0,i.timeout=12e4,i.src=e.p+""+({}[t]||t)...` 

etc.

There is [webpack-obfucator](https://www.npmjs.com/package/webpack-obfuscator) but I have no experience with this.

**Comment by mxstbr** [comment]
> As for a demo, that's not the spirit of open source, so I doubt it would be added to this project

:+1:

Not only open source, but entire web has thrived exactly because of the possibility of `view-source:`. Making it unnecessarily hard for people to read your code goes against that mentality and is definitely not something I plan to stand for anytime soon.
