### ISSUE TITLE
Incompatable with web workers (e.g. react-map-gl)?

### ISSUE THREAD

**Issue by kachkaev** [mxstbr/react-boilerplate#784]
I've been trying to use [`react-map-gl`](https://github.com/uber/react-map-gl) inside a boilerplate but with no luck. The errors that I see in the console hint that the issue may be boilerplate-related. 

MWE is here: https://github.com/kachkaev/react-boilerplate-react-map-gl-mwe
The version of the boilerplate is fresh (just initialised a new project an hour ago).

The errors that I see in dev mode are the following:
![](https://github.com/kachkaev/react-boilerplate-react-map-gl-mwe/raw/master/i/mwe-dev-errors.PNG)
They only show up when I add `<MapGl>` tag and disappear if I comment it out.

A few peculiarities in `react-map-gl` require modification of webpack config, which you can see in my repo here: https://github.com/kachkaev/react-boilerplate-react-map-gl-mwe/commit/c4375f2d63c94a8008f55277122cdc82648c699e

Those extra dependencies and loaders are justified here: 
https://github.com/mapbox/mapbox-gl-js/blob/master/webpack.config.example.js  
https://github.com/uber/react-map-gl/issues/21#issuecomment-224191900  

I know this may be an edge-case, but still find it worth bringing here. My guess is that the problem takes place because of the advanced features in the boilerplate.

**Comment by kachkaev** [comment]
I was able to correlate this with a few extra threads appearing in sources. The code in these threads does not have access to `window.reactBoilerplateDeps`:

[image being added]

The same threads exist in the built version, but everything is working fine.

I even tried to fool the code by hardcoding `reactBoilerplateDeps` this way, but vainly: 
```html
<!doctype html>
<html lang="en">
<head>
  <script>
  reactBoilerplateDeps = function(){};
  </script>
```

Any hints on what's happening in the boilerplate internally guys? :–)

**Comment by kachkaev** [comment]
This is where the error is coming from:

![error source](https://cloud.githubusercontent.com/assets/608862/17144500/df827e86-534e-11e6-910f-f6aa099800d5.PNG)

**Comment by kachkaev** [comment]
@mxstbr?

**Comment by mxstbr** [comment]
I honestly have no idea what's going on here. 😢 I wish I could help you, but I have absolutely no clue…

**Comment by kachkaev** [comment]
The problem seems to be in line 24 on the previous screen shot (`module.exports = reactBoilerplateDeps`), which is not supposed to be in the code of the web workers (these are build using [webworkify-webpack](https://github.com/borisirota/webworkify-webpack). I'm trying to figure out how to get rid of just this line, but still unable to do this.

**Comment by kachkaev** [comment]
@mxstbr you probably know how it lands to that dev-mode code. Could you please give a hint on how to at least replace it with this?
```bash
try {
module.exports = reactBoilerplateDeps;
} catch (e) {}
```

Can't do this even in the most dirty way possible :–)

**Comment by kachkaev** [comment]
It turns out that the error is not just mapbox-gl specific, it will apply to any app that uses web workers.

**Comment by kachkaev** [comment]
One more thing to have in mind when using web workers with this boilerplate _devtool: eval needs to be replaced with something else in  internals/webpack/*_
https://github.com/mapbox/mapbox-gl-js/pull/2887

**Comment by kachkaev** [comment]
Bingo! I've got a workaround! The solution is in removing this block from `package.json`:
```
  "dllPlugin": {
    "path": "node_modules/react-boilerplate-dlls",
    "exclude": [
      "chalk",
      "compression",
      "cross-env",
      "express",
      "ip",
      "minimist",
      "sanitize.css"
    ],
    "include": [
      "core-js",
      "lodash",
      "eventsource-polyfill"
    ]
  },
```

One can also just change `"dllPlugin":` to `"dllPlugin (disabled)":` - it will do the job. The app falls back to CommonsChunkPlugin in dev mode (according to `webpack.dev.babel.json`) and the web workers are no longer polluted with that `module.exports = reactBoilerplateDeps;`!

There are likely to be side-effects - I will let know about them if I discover any.

**Comment by kachkaev** [comment]
If you are using Mapbox GL or anything else with WebWorkers, you might want to consider removing DedupePlugin from webpack's prod configuration. Some thoughts are here: https://github.com/mxstbr/react-boilerplate/pull/802#issuecomment-238077919.

**Comment by gazpachu** [comment]
After fixing a few things in webpack, I arrived to a place where I'm stuck with this error:

`index.js:102 Uncaught Error: webworkify-webpack: Could not locate module containing worker function! Make sure you aren't using eval sourcemaps and that you pass named functions to webworkify-webpack!`

Any idea of what could be wrong? Thanks

**Comment by gazpachu** [comment]
Fixed it! This issue is with webworkify-webpack@1.1.4 and up. 1.1.3 seems to work well.

**Comment by mxstbr** [comment]
Closing since it seems solved, but this is a great reference issue – thanks so much for digging in!

**Comment by martinop** [comment]
I'm using a native web worker and it's works in DEV but when I do the production build then the web worker doesnt work.
