### ISSUE TITLE
(react-intl) FormattedNumber did not working properly in sample project (Safari only)

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#792]
In Safari browser,
when there is component using `<FormattedNumber />`
It will not get formatted and have some error in console.log

Step to reproduce
1. Checkout the project
2. Add `<FormattedNumber value="1000" />` in any page
3. run & open website in browser using safari
4. open console you will find error stating below

```
[Error] [React Intl] Error formatting number.
ReferenceError: No locale data has been provided for this object yet.
	formatNumber
	formatNumber ([native code], line 0)
	render
```

**Comment by chaintan17** [comment]
It seem that we need to add some logic in webpack
https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack

**Comment by mxstbr** [comment]
Are you looking into that @chaintan17?

**Comment by chaintan17** [comment]
@mxstbr Yes and fixed with this pull request, please review :)

**Comment by kachkaev** [comment]
How about closing this since PR is merged?

**Comment by chaintan17** [comment]
yes, thank you.
closed.
