### ISSUE TITLE
Feature to remove Devtools from Production

### ISSUE THREAD

**Issue by ansumanshah** [mxstbr/react-boilerplate#794]
We should strip the redux-devtools extension code in the production.

**Comment by mxstbr** [comment]
Sounds like a good idea, do you want to submit a PR for that? :+1:

**Comment by ansumanshah** [comment]
@mxstbr Sure, will submit a PR shortly

**Comment by kachkaev** [comment]
Should this be done in all cases or be optional (i.e. backwards-compatible)?

**Comment by mxstbr** [comment]
> i.e. backwards-compatible

There's no real "backwards-compatible" for a boilerplate since updating isn't really a thing. I do think this should be done by default!

**Comment by maticrivo** [comment]
@ansumanshah any progress on this? I'm interested in having this feature too

**Comment by ansumanshah** [comment]
Submitted a PR with the quick fix that i did for my project.

P.S. First PR so please help if something is abruptly wrong or if have to add something else too :)

**Comment by zalmoxisus** [comment]
Just to notice that allowing Redux DevTools Extension in production isn't wrong and [rather helpful](https://github.com/zalmoxisus/redux-devtools-extension/issues/185), though agree that better to allow it explecitely.

**Comment by mxstbr** [comment]
Yes, very true @zalmoxisus, it's just that by default it seems better to not have it! Closing since the PR was merged, this is released in v3.3! 🎉
