### ISSUE TITLE
How to disable babel compilation of ES6?

### ISSUE THREAD

**Issue by davidjirovec** [mxstbr/react-boilerplate#797]
Even with devtool set to source-map, debugging ES6 compiled by babel is a pain.

I've found http://stackoverflow.com/questions/33139295/debugging-with-chrome-with-es6

where is mentioned, that enabling ES6 native support and disabling ES6 compilation in babel might help. How can I do this in react-boilerplate?

Thanks.

**Comment by mxstbr** [comment]
You'll have to remove that plugin from the `babelConfig` in `package.json`!
