### ISSUE TITLE
Lint compatible code formatter for WebStorm / Idea

### ISSUE THREAD

**Issue by davidjirovec** [mxstbr/react-boilerplate#799]
Is it possible to somehow set WebStorm code formatter to adhere to Lint requirements? Fixing reported code format problems manually is tedious and time consuming.

**Comment by mxstbr** [comment]
We've got you covered, take a look at the FAQ:

https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md#using-this-boilerplate-with-webstorm

**Comment by davidjirovec** [comment]
To me it seems this only shows errors, but cannot automatically fix formatting errors. Is it true?

**Comment by mxstbr** [comment]
No idea, I don't use WebStorm, you tell me!

**Comment by davidjirovec** [comment]
Well, it seems so :-)

**Comment by mxstbr** [comment]
> Well, it seems so :-)

Any ideas how to fix it?

**Comment by davidjirovec** [comment]
Ideally set up .editorconfig to use same formatting as expected by eslint. If not possible at least set WebStorm formatter to use same formatting as expected by eslint.

At least I've found eslint --fix parameter, which fixes these formatting issues.

**Comment by mxstbr** [comment]
> Ideally set up .editorconfig to use same formatting as expected by eslint.

Oh no, I thought we had that! Is our editorconfig out of sync with the eslint config?

**Comment by gihrig** [comment]
As @mxstbr [tweeted](https://twitter.com/mxstbr/status/760091979292221440) there's [eslint-to-editorconfig](https://www.npmjs.com/package/eslint-to-editorconfig). Might be just the ticket.
