### ISSUE TITLE
PostCSS Plugins for v3.0.0

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#80]
Seeing as we're using CSS Modules in v3.0.0 of this boilerplate, our current PostCSS plugin stack doesn't make sense anymore. (i.e. no need for `postcss-import` and `postcss-simple-vars` anymore)

This issue is to discuss which plugins we should include for v3.0.0, please chime in!

----

Definitely including these plugins:

**`autoprefixer`**

A must-have in every project, no discussion needed. (I hope)

**`cssnano`**

Doesn't hurt to have this in production, minifies your CSS very nicely.

**`postcss-focus`**

Adds a `:focus` selector to every `:hover` selector. Nice to have so you cannot forget, doesn't hurt if you include them anyway.

----

Want to include these plugins:

**`css-mqpacker`**

Pack same CSS media query rules into one media query rule.

Has a few gotchas we need to document, but is overall a nice addition and it makes sense to include it.

**`cssnext`**

This allows us to use CSS4 syntax in our CSS.

I'm not personally using this in any project yet, so I'm not sure about the pros/cons. Can somebody chime in, why would I want to use CSS4 stuff? /cc @MoOx

----

Use this myself, but don't want to include them by default:

**`postcss-autoreset`**

This plugin adds `all: initial;` to all blocks and elements in BEM notation. It's a component-specific reset that completely prohibits inheritance.

Highly opinionated and will need visible documentation otherwise everybody will be confused. On top of that, browser support isn't nearly there yet and we'll need to use `cssnext` to transpile it to CSS3. Transpiling `all: initial;` to CSS3 results in 107 lines of code – added to every single block and element.

Suggestions, feedback, comments? Which plugins do you recommend to be included by default, and why?

**Comment by MoOx** [comment]
cssnext includes autoprefixer ;)
css-mqpacker is not safe imo. Too many side effect.

**Comment by mxstbr** [comment]
@MoOx cssnano does too, right? Worth its own documentation though, no matter which plugin it's included with.

True, it has quite a few side effects...

**Comment by MoOx** [comment]
cssnano is not. It's an opininated tool for optimisation (it was available in cssnext, but this package has been deprecated in favor of postcss-cssnext, see http://cssnext.io/postss).
autoprefixer is the first feature listed on homepage and on features page that's not enough? http://cssnext.io/ + http://cssnext.io/features/

**Comment by MoOx** [comment]
cssnext best feature imo: custom media queries, media queries ranges, nested media queries, color() function

**Comment by mxstbr** [comment]
I know, what I meant is cssnano also includes autoprefixer, see [here](http://cssnano.co/optimisations/)!

I think documenting autoprefixer seperately is worth it, because many people might not be aware that it's included in `cssnext`.

Thanks, will look into those!

**Comment by MoOx** [comment]
Good point.
