### ISSUE TITLE
Development server startup logging

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#81]
This is a starter issue for newcomers to Open Source, feel free to claim it!

----

Jekyll has some very nice logging when starting the development server:

```
Configuration file: /YourUsername/YourSite/_config.yml
            Source: /YourUsername/YourSite
       Destination: /YourUsername/YourSite/_site
      Generating...
                    done.
 Auto-regeneration: enabled for '/YourUsername/YourSite'
Configuration file: /YourUsername/YourSite/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

We should add more logging, both when starting the development server and when starting the production server.

It would be nice if our servers logged `Press CTRL-C to stop` after they finished starting, and if the development server also logged `Hot reloading: enabled` shortly before the server has started.

**Tip:** [`webpack/server.prod.js`](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/webpack/server.prod.js) is the production server, and [`webpack/server.dev.js`](https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/webpack/server.dev.js) the development server.

----

Steps to do this:

- [x] Claim this issue by commenting below (@7rulnik)
- [x] Setup a local copy of react-boilerplate
    - [x] Clone the repo with `git clone git@github.com:mxstbr/react-boilerplate`
    - [x] Enter the newly created folder with `cd react-boilerplate`
    - [x] **Go to the `v3.0.0` branch of this repo with `git checkout v3.0.0`**
    - [x] Install the dependencies with `npm install`
- [x] Add the feature mentioned above
- [x] Start a pull request
- [x] Review
- [x] Merge

**Feel free to ping me on [twitter](https://twitter.com/mxstbr) if you need any help/tips/pointers/are stuck!**

> Note: This feature is scheduled for v3 of this boilerplate, please don't forget to make your changes on the `v3.0.0` branch of this repo.

**Comment by 7rulnik** [comment]
I can do it tonight

**Comment by mxstbr** [comment]
All yours @7rulnik!

**Comment by mxstbr** [comment]
Oops, closed it on accident.

**Comment by 7rulnik** [comment]
@mxstbr
Should I add logs about directories?
If yes, what is the best option for log source dir?
Something like that? Or more smart method?
```
console.log(path.join(__dirname, '..', 'app'));

```

**Comment by mxstbr** [comment]
That would be really nice, and `path.join` is perfect!

**Comment by mxstbr** [comment]
Done thanks to @7rulnik! Looks amazing: 

![dev-server-logging](https://cloud.githubusercontent.com/assets/7525670/12402928/3ad9808e-be28-11e5-977e-f7e303d0c38e.jpg)
