### ISSUE TITLE
App does not work after clean (React.children - related)

### ISSUE THREAD

**Issue by kachkaev** [mxstbr/react-boilerplate#817]
Just started a new project and saw this after `npm run clean`:

![screenshot from 2016-08-02 12-28-59](https://cloud.githubusercontent.com/assets/608862/17326975/d7a2701e-58ac-11e6-81df-5408c3a66405.png)

The cause is three occurrences of `React.children` instead of `React.Children` introduced here:
https://github.com/mxstbr/react-boilerplate/commit/ac1f6346535534e7061a8ba9b15a0f246a020a77

Replacing these strings manually brings the app back to work.

**Comment by mxstbr** [comment]
Oh no, would you mind submitting a PR fixing this?

**Comment by kachkaev** [comment]
Not earlier that tonight :–( This might be worth doing by someone else since it's rather urgent.

**Comment by mxstbr** [comment]
Thanks, I went ahead and did it in #818. Thanks a lot for the notification!

**Comment by kachkaev** [comment]
Great! Thanks a lot for doing this so quickly!
