### ISSUE TITLE
Hot reload issue

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#821]
I understand the issue that is causing the "problem" or to put it better: the hmr modules issues, but as mentioned in this comment [there's work being done](https://github.com/mxstbr/react-boilerplate/issues/590#issuecomment-227997902) to solve the issue.

Hope you don't mind me asking how high is this on the priority list? ;)

Also, I'm new to the react world so I apologize in advance: I've done a todo app using a simple boilerplate which does not have this problem. This is the working example.
https://github.com/mnemanja/React2Do

How complex / trivial is the fix? And are we effectively waiting for the React hot loader 3 to be done?

**Comment by mxstbr** [comment]
> Hope you don't mind me asking how high is this on the priority list? ;)

This isn't up to us at all! Dan Abramov needs to find the time to finish and release `react-hot-loader` v3, which isn't related to this boilerplate.

**Comment by mnemanja** [comment]
Thanks @mxstbr.
