### ISSUE TITLE
How would custom api implementation look?

### ISSUE THREAD

**Issue by IljaDaderko** [mxstbr/react-boilerplate#822]
I understand that custom api implementation should happen in server/index.js under

```
// If you need a backend, e.g. an API, add your custom backend-specific middleware here
// app.use('/api', myApi);
```

but could we get an expanded example of what `myApi` should be?

**Comment by mxstbr** [comment]
`myApi` here would be a standard express.js middleware, i.e. would have this signature:

```JS
function myApi(req, res, next) {/* … */}
```

See here for more information on what this could look like: http://expressjs.com/de/guide/using-middleware.html

**Comment by chaintng** [comment]
And should the source code that being used in backend alone will be kept in `/app` directory the same as frontend source code? or should we kept in `/server` ? can you give me some idea please ?

**Comment by mxstbr** [comment]
Definitely `/server`! I don't think our test setup is good for backend testing, but you can add a new task to the `package.json`, something like this: `"test:backend": "mocha --compilers js:babel-core/register server/**/test/*.test.js"` maybe?

**Comment by sedubois** [comment]
@chaintng also see https://github.com/mxstbr/react-boilerplate/pull/1037

And I currently experiment with adding GraphQL as a backend, see https://github.com/mxstbr/react-boilerplate/issues/1041,

**Comment by chaintng** [comment]
I love GraphQL 👍

**Comment by juanda99** [comment]
My API is being developed in another project.
Could I integrate it with my react app inside this boilerplate?
I mean... I've done kind of, but, what happens with node libraries, dependencies and dev-dependencies?
Does webpack include them in the client app? Do I need some extra conf?
Currently for developing I needed to exclude them inside package.json (dllPlugin key)
But what happens with npm run build?

**Comment by asdf123101** [comment]
@juanda99 You could create a package.json in the `/server` and conveniently copy the server side code over (possibly together with the .git folder and make the `/server` a sub repository of the main project repository). This is a typical pattern when doing server and client side development together.

**Comment by juanda99** [comment]
@asdf123101 Thanks! It's been a while. More or less this is the way I decided to go.
