### ISSUE TITLE
Feature : snapshot testing for components using react-test-renderer

### ISSUE THREAD

**Issue by bsr203** [mxstbr/react-boilerplate#825]
Hi,

Looks like core members in react community are recommending snapshot testing for components. see the discussion.

https://twitter.com/dan_abramov/status/757315414284201985

jest supports it.

http://facebook.github.io/jest/blog/2016/07/27/jest-14.html

not sure how long it takes to get a package which make it possible to use https://www.npmjs.com/package/react-test-renderer with mocha and to provide incremental snapshots like jest does.

I think it would be great to use jest for snapshot test alone, or convert everything over to jest (as they already recommend auto mocking off and seems making serious investment on it).

see https://github.com/facebookincubator/create-react-app/pull/250#issuecomment-237098619

**Comment by mxstbr** [comment]
I'd love for that to happen, I'll close this for now since we have to wait since this exists but it looks like awesome technology!

**Comment by cpojer** [comment]
Someone is working on it and there is a long discussion here: https://github.com/facebook/jest/issues/1341

We actually spent three months building the right infra and UX for this feature and I'm quite convinced it will take a long time for anything to come even close. I recommend just giving Jest a try and see how you like it :) And then help us make snapshotting even better.

**Comment by mxstbr** [comment]
> I recommend just giving Jest a try and see how you like it

I really like Jest, but we now have a solid setup that just works™ with exactly our webpack config – I'm not sure it's worth the effort switching over.

That being said, **I'd appreciate a PR moving our test setup to Jest**. I might be biased towards already done work (what's that fallacy called again?) and if there is a significant drop in complexity it might be worth it!
