### ISSUE TITLE
Switch pages making sagas repeat inject

### ISSUE THREAD

**Issue by rangerch** [mxstbr/react-boilerplate#826]
importModules.then(([reducer, sagas, component]) => {
                        injectReducer('demoPage', reducer.default);
                        injectSagas(sagas.default);
                        initedStatus.demoPage = true;
                        renderRoute(component);
                });

this code will repeat processing when switch page.

**Comment by mxstbr** [comment]
Yes sir, this is intentional. Sagas should be using the watcher pattern as detailled in the example app to make sure they start and stop based on the route they're on!

@justingreenberg we should add a note of this to the docs, this question comes up really frequently.

**Comment by skosno** [comment]
@mxstbr Is there any reason not to wrap sagas in "injectSagas" with this logic by default? Do you expect that some exported sagas should not cancel on location change?

**Comment by mxstbr** [comment]
> Do you expect that some exported sagas should not cancel on location change?

Yes. This way, you can opt-into it, whereas the other way you're forced to have sagas only run when the route is open.

**Comment by skosno** [comment]
Do you expect that there will be sagas that are injected asynchronously with routing but won't be suspended when routing changes (I was just trying to get real world scenarios)?

**Comment by justingreenberg** [comment]
@skosno app-wise services, ie notifications/toast system, global fetch utilities, websocket manager, network connection status, etc

**Comment by skosno** [comment]
@justingreenberg wouldn't we load such sagas directly upon application boostrap instead of injecting them as async sagas? If I understand the logic here, we want to load sagas connected to particular route asynchronously and stop their execution when route changes. What I am unsure is if there would be sagas that are not loaded on application bootstrap but rather upon reaching particular route and are not suspended when that route changes.

**Comment by justingreenberg** [comment]
a few (convoluted) examples: 
- tracking background service (ie. data importer) while letting the user continue using app
- maintaining socket subscriptions created using route params that updates some aggregates

i totally hear what you are saying re: mounting watchers during bootstrap (this is what i do for notification system), the question is how many open saga processing do you want running in the background at **all** times? also, nothing in the current setup prevents you from doing that anyway

**Comment by skosno** [comment]
I definitely agree you do not want too many sagas open in the background, thanks for all the feedback.

**Comment by chaintng** [comment]
Cancel saga after `LOCATION_CHANGE` doesn't work in the case i route to the same PATH but with appending query string.... Sagas then stop working, they won't cancel the previous sagas, but both (old & new injection).

```
export function* githubData() {
  // Fork watcher so we can continue execution
  const watcher = yield fork(getReposWatcher);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}
```
