### ISSUE TITLE
Deploying -- where to?

### ISSUE THREAD

**Issue by Jan-Jan** [mxstbr/react-boilerplate#832]
Where is everyone deploying to?

At the moment I am trying to get gcloud working, it is a mission. (I will share any results if I am successful.) I gave up on heroku.

This is a wonderful piece of boilerplate (thank you very much to all the contributors), but if we cannot deploy it, it looses most of its value :'(

**Comment by mxstbr** [comment]
I just FTP it up to a DigitalOcean droplet running Apache 😁

**Comment by kachkaev** [comment]
I'm building the app using `npm run build` and then simply bake a Docker image by adding those generated files into [the nginx based image](https://hub.docker.com/_/nginx/). The container ends up being really small.

You don't have to deploy the whole boilerplate and this is something I really like. I used to use Meteor before and the deployment process of even a simple single-page app felt as heavy as if I were launching a SuperAI!

**Comment by chaintan17** [comment]
My company use `deis`, it's like self-hosted heroku. And it works pretty well.

**Comment by oyeanuj** [comment]
@kachkaev Would love to see what you have in your nginx based image if possible, as I am planning to have a similar setup!

**Comment by mxstbr** [comment]
Since this has been pretty thoroughly answered I'll close it for now, feel free to continue the discussion though!

**Comment by kachkaev** [comment]
@oyeanuj nothing special really. The Dockerfile can be simple as this:

```
FROM nginx:1.11.1-alpine
COPY build /usr/share/nginx/html
```

I've got a [dynamic nginx-proxy](https://github.com/jwilder/nginx-proxy) with [letsencrypt companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) installed on the production server too, which means that I can run multiple docker containers with one built boilerplate app in each, and all will be served via https on whatever domains I want! Those guys listen to all new containers that I start and if I launch a new one with some special environment variables, they re-configure themselves immediately. The is quite cool!

What I can't do though is to run a boilerplate app inside docker while it is in development. This would allow any of my colleagues to start working on the project without making sure that they have the right versions of node etc. after they clone the repo - all these dependencies would be "prescribed" in some another Dockerfile that is different from the production one. Some discussion of this approach [is another issue](https://github.com/mxstbr/react-boilerplate/issues/751), but there is no good solution so far of which I know.

**Comment by Jan-Jan** [comment]
For a GCloud App Engine deploy I ended up creating a app.yaml file
```
runtime: custom
vm: true
service: default
threadsafe: true

automatic_scaling:
  min_num_instances: 1

# force all connections to be SSL
handlers:
- url: /.*
  script: IGNORED
  secure: always
```
with a custom Dockerfile
```
FROM node:6

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

ENV NODE_ENV production
ENV PORT 8080
ENV RESET_PASSWORD_URL https://www.lifekee.us/reset-password-confirm

# Bundle app source
COPY . /usr/src/app

EXPOSE 8080
RUN npm run build:clean && ./node_modules/.bin/webpack --config internals/webpack/webpack.prod.babel.js --color -p
CMD [ "npm", "start" ]
```
which I deployed with `gcloud app deploy`.

Alternatively, for a docker-engine deploy to GCloud, (assuming your project is called wopee-213489), with the above Dockerfile I ran
```
docker-machine create --driver google --google-project wopee-213489  web-fe
eval $(docker-machine env web-fe)
docker build -t myname .
docker run -p 8080:8080 -d myname
```

@mxstbr I don't know if you would like to include the above in the deployment part of the documentation? (Maybe, it can save someone else some time)

**Comment by Madsn** [comment]
I was hoping to use react-boilerplate or possibly one of the other popular boilerplates, but the full-featured ones are also full-stack as far as I can tell, i.e. the expected setup is using Node on the backend.

Would it be possible (with minor modifications) to host a RBP app with Apache - without running a node.js server? The idea is I would use something other than Node for an API server.

**Comment by mxstbr** [comment]
> Would it be possible (with minor modifications) to host a RBP app with Apache - without running a node.js server?

That's exactly what I do. I just run `npm run build` (which outputs static files) and upload the `build/` folder to a server running Apache – no node needed!

**Comment by akashshinde** [comment]
I am getting `404 Not Found` after deploying build/ to nginx docker image.
