### ISSUE TITLE
Router JSX [question]

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#833]
Is it an option for the router to be done in the JSX syntax?
What are the benefits in having it as pure objects? For me the JSX sintax looks cleaner.

**Comment by jptissot** [comment]
I changed mine to using the JSX synatx. It allowed me to use the <Redirect /> and other components not available when using pure js objects. (i know I could have manually used onEnter).

**Comment by mxstbr** [comment]
> What are the benefits in having it as pure objects?

The generators work :wink: other than that it's mostly personal preference, it's easier to split them up into multiple/nested files that way imo. 

_There might have been a better reason with an earlier react-router version but I can't think of one_

**Comment by loicginoux** [comment]
@jptissot I thought about changing the routes by the jsx syntax. It's seems more clear in my opinion and easier to follow at a glance.
would you mind sharing the changes you made to have the routes in jsx syntax ? 
Thank you.

**Comment by mnemanja** [comment]
@jptissot I would appreciate the example on how you made your changes as well. Thanks.

**Comment by raulgrecio** [comment]
@mxstbr I would also greatly appreciate a comparative example of routes in jsx syntax. It is the only brake I have with this boilerplate. thanks.
