### ISSUE TITLE
Updating store before react router is triggered

### ISSUE THREAD

**Issue by IljaDaderko** [mxstbr/react-boilerplate#834]
I need to be able and somehow update stores value of `isUserAuthenticated` to `true` (it is initially false) before react router kicks in, this will be used to protect routes. In order to check if user is authenticated I need to access an httpOnly cookie within server, check if it exists or not and update this store.

I was looking through examples and docs, but so far didn't find anything on this and wanted to see if boilerplate accounts for such scenarios or will I have to find my own workaround.

**Comment by mxstbr** [comment]
Why can't you use the `onEnter` hook of the routes themselves?

**Comment by IljaDaderko** [comment]
@mxstbr figured it out in the end, just not used to object rout syntax :)
