### ISSUE TITLE
Line numbers mismatch

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#836]
I'm using Webstorm on Win10. What happens is that the line that gets logged in the chrome dev toolbar shows one number, but when you compare it to the source in the IDE or in the dev toolbar the line does not match to the source of the log.

I've tried it on the clean install. Basically add a console log somewhere in the code and check it in the dev toolbar.

**Comment by chaintan17** [comment]
are you talking about dev build or production build?
if dev build, please try check `devtool` config, and make sure that it's using sourcemap

**Comment by mnemanja** [comment]
I'm running a dev build. 
It started working after changing the `devtool` from `cheap-module-eval-source-map` to `eval-source-map` .

@chaintan17 Thanks for the assistance.

**Comment by kachkaev** [comment]
BTW can anyone suggest any other quick and accurate `devtool` mode that does not involve `eval`? That one does not seem to work with Web Workers unfortunately.

**Comment by mxstbr** [comment]
Here's a list of the possible options, I'm sure you'll find something: https://webpack.github.io/docs/configuration.html#devtool
