### ISSUE TITLE
Cannot enable CORS or 

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#837]
I tried to implement this plugin https://github.com/expressjs/cors
To `Access-Control-Allow-Origin`
However, it's not working.

I set it under `addProdMiddlewares` like following
```
const addProdMiddlewares = (app, options) => {
  const publicPath = options.publicPath || '/';
  const outputPath = options.outputPath || path.resolve(process.cwd(), 'build');
  app.use(publicPath, express.static(outputPath));

  app.get('*', cors(), (req, res) => {
    filesystem.readFile(path.resolve(outputPath, 'index.html'), (err, file) => {
      const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
      if (err) {
        res.sendStatus(404);
      } else {
        const compileStr = Mustache.render(file.toString(), { userIpAddress: ip, NODE_ENV: process.env.NODE_ENV });
        res.send(compileStr);
      }
    });
  });
};
```

I wonder does it need any special config to enable this option?

Please advise.

**Comment by chaintan17** [comment]
turns out those static files should be set in 
` app.use(publicPath, express.static(outputPath));`

closed.

**Comment by kylesavant** [comment]
@chaintng what do you mean the static file should be set in `app.use(publicPath, express.static(outputPath));

`? I'm still not able to get this to work...
