### ISSUE TITLE
IE 10 support

### ISSUE THREAD

**Issue by 7rulnik** [mxstbr/react-boilerplate#84]
Since Microsoft stop support IE 10 can we remove it from PostCSS config?

**Comment by mxstbr** [comment]
Seeing as IE8 + 9 + 10 have a combined global browser share of ~3% ([src](http://caniuse.com/usage-table)), which will decline even further from today onwards, I think that's a reasonable thing to do.

Do you want to take a look at that and submit a PR while you're in the codebase?

**Comment by 7rulnik** [comment]
Sure!

**Comment by 7rulnik** [comment]
It's already written as it should
```
  cssnext({
      browsers: ['last 2 versions', 'IE > 10']
    }),
```
