### ISSUE TITLE
Eslint failed after fresh clone

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#842]
![image](https://cloud.githubusercontent.com/assets/2979072/17468922/83c608c6-5d56-11e6-9a91-20f8af1c5158.png)

I guess it's because of AirBNB EsLint v10

**Comment by mxstbr** [comment]
I think we need to fix the `eslint-import-plugin` with our `resolve` settings of webpack. Would you mind looking into that?

**Comment by chaintan17** [comment]
@mxstbr i really would love too. But i'm not sure if i understand correctly.
So,  i guess i need to config `eslint-import-plugin`. But there is no any of `eslint config file` at all.
Shall i create a new one?

**Comment by justingreenberg** [comment]
https://github.com/mxstbr/react-boilerplate/pull/829/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R100 this line can just be switched to `0`

**Comment by chaintan17** [comment]
Thanks @justingreenberg,
but i still feel it's not right to disable this lint rule... 😕 
However, after disable the rule, there is another error in below screenshot
![image](https://cloud.githubusercontent.com/assets/2979072/17524641/a7faa9f2-5e89-11e6-9c6c-45dcdbc9dfca.png)

**Comment by justingreenberg** [comment]
@chaintan17 of course, i agree! it would just be temporary until ecosystem stabilizes from regression.. 

> But there is no any of eslint config file at all.

our config is in package.json under eslint key

for reference, here are the rules we are extending from airbnb:
https://github.com/airbnb/javascript/blob/9d598c3563819a42f23f2ad19dd23a2f6e515a05/packages/eslint-config-airbnb-base/rules/imports.js

**Comment by gihrig** [comment]
I just cloned, setup and `npm run lint`. No problem, am I missing something?

![image](https://cloud.githubusercontent.com/assets/1481063/17531474/d481aa7e-5e30-11e6-9714-a4227848f733.png)

@chaintan17 Have you recently tried a new clone or the project?

**Comment by rizedr** [comment]
@chaintan17 what OS are you running?

**Comment by chaintan17** [comment]
ah... It's now working after run `npm install` again.
I will close this ticket.
