### ISSUE TITLE
Set initial state on the server before routes

### ISSUE THREAD

**Issue by IljaDaderko** [mxstbr/react-boilerplate#844]
I have posted similar issue before, regarding authentication, suggestion there was to use a `onEnter` hook to check if user is logged in, so something like this in routes. js:

Function to redirect user to a login page if he/she is not logged in
```
  const redirectToLogin = (nextState, replace, callback) => {
    if (/* !isAuthenticated() */) {
      replace({
        pathname: '/login',
        state: { nextPathname: nextState.location.pathname }
      })
    }
    callback()
  }
```

And all protected routes would have an onEnter added i.e.

```
   {
      path: '/',
      name: 'login',
      onEnter: redirectToLogin,
      getComponent (nextState, cb) { /* ... */}
    }
```

however my issue lies within following use case scenario. I store user tokens in an httpOnly cookie in order to prevent XSS attacks, hence can only access them via server. I have a seprate endpoint set up to check if token cookie exists `/api/token` that returns success or error status if token is set or not, hence I need to figure out a way to implement that commented out `isAuthenticated` function that will call this endpoint, wait for response and update react router routes. At the moment all protected routes are redirecting to `/login` even if user is logged in, as I believe onEnter simply fails all the time as it doesn't wait for async response.

**Comment by mxstbr** [comment]
Does this help maybe? https://github.com/reactjs/react-router/issues/1439

**Comment by IljaDaderko** [comment]
@mxstbr I found a work around through cookie, but will look into your link. Thank you.
