### ISSUE TITLE
Linting watcher

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#846]
Would it be possible to add a linting watcher? 
Currently lint has to be run manually or with tests. If tests are used in watch mode only they get watched, but not the linter.

**Comment by mxstbr** [comment]
I have the linter setup in my IDE so I see errors and warnings inline. Any reason you cannot do that?

**Comment by mnemanja** [comment]
@mxstbr the linter works for me, but I'm missing (or the boilerplate is missing) the **watch** option for the linter. Do you use it in the watch mode or do you run it manually?

**Comment by gihrig** [comment]
@mnemanja If eslint has a plugin for your editor/ide lint runs automatically and you see errors in real-time as you type.

For example, I'm running Atom with `linter`, `linter-eslint` and `linter-stylelint` packages. I get lint errors reported as I type or paste code in js and css files.

**Comment by mnemanja** [comment]
@gihrig Okay, thanks.
