### ISSUE TITLE
npm run generator not functioning as intended

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#847]
First of all I apologize if I've missed an already existing issue regarding this.

When running `npm run generate` in **Win10 command prompt** and **Webstorm terminal** I get the same behavior which is a list with option to choose from, but navigation through them does not work. So basically I can initially choose _components_ or _containers_ by specifying it in the initial command, but I can't choose between stateless function or es6 class (it's always stateless func).

Running the generate command in Git Bash throws an error:
```
$ npm run generate

> react-boilerplate@3.0.0 generate C:\www\allstr
> plop --plopfile internals/generators/index.js

? [PLOP] Please choose a generator. (Use arrow keys)
> component - Add an unconnected component
  container - Add a container component
  route - Add a route
  language - Add a langauge

C:\www\allstr\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} qu                                                                     antifier.
    at new RegExp (native)
    at breakLines (C:\www\allstr\node_modules\plop\node_modules\inquirer\lib\uti                                                                     ls\screen-manager.js:108:15)
    at ScreenManager.render (C:\www\allstr\node_modules\plop\node_modules\inquir                                                                     er\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\www\allstr\node_modules\plop\node_modules\inquirer\lib\                                                                     prompts\list.js:103:15)
    at Prompt._run (C:\www\allstr\node_modules\plop\node_modules\inquirer\lib\pr                                                                     ompts\list.js:74:8)
    at Prompt.run (C:\www\allstr\node_modules\plop\node_modules\inquirer\lib\pro                                                                     mpts\base.js:57:8)
    at Object.<anonymous> (C:\www\allstr\node_modules\plop\node_modules\inquirer                                                                     \lib\ui\prompt.js:84:12)
    at module.exports (C:\www\allstr\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\www\allstr\node_modules\plop\node_mod                                                                     ules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\www\allstr\node_modules\rx-lite\rx.lit                                                                     e.js:63:31)

```

**Comment by Dattaya** [comment]
I'm also on Windows 10 (anniversary update) but don't experience this bug:
![ezgif-3455290629](https://cloud.githubusercontent.com/assets/387256/17518579/2c03346e-5e51-11e6-9491-21107c184217.gif)

Maybe it's because of your node version? This is what I use:

```bash
>node -v
v4.4.6
```

**Comment by Dattaya** [comment]
Also 'legacy console' is unchecked in settings:
![settings](https://cloud.githubusercontent.com/assets/387256/17518947/99c842c2-5e52-11e6-8578-d5c497ca7159.png)

**Comment by mxstbr** [comment]
This seems to be a problem with your environment, nothing specific to the boilerplate @mnemanja. Hope you figure it out soon!

**Comment by Dattaya** [comment]
I've noticed that @mnemanja uses 3.0 version and I use master branch so maybe there is an error after all.

**Comment by mxstbr** [comment]
`master` is always the newest version, so if this bug is fixed in the newest version there's nothing really for us to do here 😊

**Comment by mnemanja** [comment]
I've switched to the master now. This is the pre-anniversary version and the legacy mode was not on.
I wrote to the `plop` package because this is is the part that is not working for me https://github.com/amwmedia/plop/issues/35

Thanks guys for the quick response :+1:

**Comment by Dattaya** [comment]
@mnemanja, did you see any errors while running `npm i`? What is your node.js' version?
Another suggestion is to put your project on a disk D with empty `node_modules` and run `npm i` there in case it's some sort of file permission issue.

**Comment by mnemanja** [comment]
@Dattaya 
Basically went fine except these few `warn` and `pre-commit` lines.
**npm is 3.6.0**

Unfortunately i only have one disk here :)
```
npm WARN deprecated isparta-loader@2.0.0: This package is deprecated in favor of                                                                                                                                                                                                istanbuljs/babel-plugin-istanbul
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN prefer global colorguard@1.2.0 should be installed with -g

> pre-commit@1.1.3 install C:\www\test\react-boilerplate\node_modules\pre-commit
> node install.js

pre-commit:
pre-commit: Failed to symlink the hook file in your .git/hooks folder because:
pre-commit: EPERM: operation not permitted, symlink '..\..\node_modules\pre-commit\hook' -> 'C:\www\test\react-boilerplate\.git\hooks\pre-commit'
pre-commit: The hook was not installed.
pre-commit:

...

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.

```

**Comment by Dattaya** [comment]
npm 3.6.0 could mean that you have node 6.x installed. I switched to it, installed dependencies again (got exact same errors as yours; 'Failed to symlink' error could be prevented when the console is in administrator mode but it's unrelated to the current issue). 
It seems like I'm out of ideas, you can update your old npm to npm `3.10.3` with `npm i -g npm` but the chances of solving this problem with it are close to zero. I don't think it's related to the anniversary update being installed either but during the weekend I'll try to install `react-boilerplate` on my laptop that hasn't been updated and will see what the result is.

**Comment by mnemanja** [comment]
My Node is 5.7.0. 
I've fixed the problem by changing the node version to 6.2.
https://github.com/amwmedia/plop/issues/35

**Comment by danielo515** [comment]
I am just posting this here because maybe someone could face the same problem again. I 'm using windows 10 home edition and node 6.9.1. I don't know why, but generator command does not work on github bash shell, but it does on default windows cmd shell. Weird, I don't know why, but at least it works.

Regards

**Comment by jimmyheaddon** [comment]
@danielo515 - that worked a treat for me, running from Windows CLI instead of Git Bash.  On Windows 7, with Node v7.2.0 and npm v3.10.9 I had the same regex error as you from Git Bash.
