### ISSUE TITLE
New Issue implementing react-calendar-timeline

### ISSUE THREAD

**Issue by eamonpenland** [mxstbr/react-boilerplate#848]
Hi all!
Trying to implement react-calendar-timeline and I'm having an issue that just appeared. Not sure what happened.
There are two errors in my browser.

-Dynamic page loading failed Error: Cannot find module "./Timeline.scss"
-Uncaught (in promise) Error: Cannot find module "./Timeline.scss"

am i doing something dumb?

  "name": "react-boilerplate",
  "version": "3.0.0",

**Comment by mxstbr** [comment]
We don't support Sass, see the docs right here: https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/sass.md
