### ISSUE TITLE
pre-commit should be installed at setup time

### ISSUE THREAD

**Issue by alikhani** [mxstbr/react-boilerplate#851]
Started a new project and after setup and clean the pre-commit isn't firing.

I saw that this has been fixed and reverted in: 80da0c517e94b9c78614773b94be10427f4083fc and 36893a8c30acd52304f7e9feca4e0342fcdee317

**Comment by mxstbr** [comment]
See #433 for the discussion about this. We definitely need to document somewhere that you need to install `pre-commit` though!

**Comment by amilajack** [comment]
Should this be closed?

**Comment by gihrig** [comment]
Yes, I think so. As part of the weekly dependency update I do a `git commit` a new clone after `clean`.

I see precommit hook run eslint and style lint.

Works as expected AFAICT.

**Comment by mxstbr** [comment]
Same, I can confirm this is definitely fixed. Thanks @amilajack @gihrig!
