### ISSUE TITLE
Add redux-devtools and redux-simple-router ?

### ISSUE THREAD

**Issue by chungchiehlun** [mxstbr/react-boilerplate#86]
We use redux in this repository. How about adding [redux-devtools](https://github.com/gaearon/redux-devtools) in developer mode and using [redux-simple-router](https://github.com/rackt/redux-simple-router) to combine state of route(url) with state of applications further?

**Comment by mxstbr** [comment]
Will definitely look into redux-devtools, we initially [decided against simple-router](https://github.com/mxstbr/react-boilerplate/issues/6) because we thought it wasn't compatible with Immutable JS. That has since proven wrong, so I'll revisit both of them! Thanks for pointing that out!

**Comment by mxstbr** [comment]
redux-devtools looks great, if you want to I'd love if you could submit a second PR with redux-devtools!

**Comment by mxstbr** [comment]
Closing this for now as I consider redux-devtools non-essential for version three, if you'd still like to submit a PR implementing it I'd definitely be interested! Thanks so much again for your work with redux-simple-router!

**Comment by chungchiehlun** [comment]
Thanks for your contribution to the react-redux ecosystem. The awesome repo provided substantial architecture for react and redux. Thank you! I’ll be following up on other issue and send a new PR to better the repo !

**Comment by mxstbr** [comment]
Thank you @chungchiehlun!
