### ISSUE TITLE
ESLint  missing rules. "no-unsafe-negation", "no-global-assign"

### ISSUE THREAD

**Issue by blntylmn** [mxstbr/react-boilerplate#864]
Build and test failed because of missing rules. "no-unsafe-negation", "no-global-assign" rules are missing.

**Comment by gihrig** [comment]
This is corrected by #862 

Thanks for reporting!

**Comment by gihrig** [comment]
Reopening for visibility util issue with #862 is resolved.

**Comment by mxstbr** [comment]
Fixed, sorry for the delay!
