### ISSUE TITLE
Github NPM Linked Module crashing Webpack b/c it cannot resolve...

### ISSUE THREAD

**Issue by eddiewang** [mxstbr/react-boilerplate#866]
Forked a module to change some code from github. Usually I just run npm install myrepo/dependency --save and it will install in npm and update in package.json, but in this scenario, Webpack isn't able to import / resolve the module.

Any ideas how to fix this?

**Comment by gihrig** [comment]
Can you provide steps to reproduce and the error you're getting, please.

**Comment by eddiewang** [comment]
Fixed, error on my part. Thanks to Max for helping me debug.
