### ISSUE TITLE
Split webpack config into base, development and production

### ISSUE THREAD

**Issue by yjcxy12** [mxstbr/react-boilerplate#87]
I found that it's very hard to read and change webpack config with this boilerplate. 

It's clear that there are many differences between development and production environment config. And I found [redux](https://github.com/rackt/redux) approach is pretty good. It has three webpack config files: base, development and production. and uses different files accordingly.

**Comment by mxstbr** [comment]
I'll look into that, sounds like an acceptable and clear solution, thanks for showing me that!

**Comment by mxstbr** [comment]
So I looked at the Redux repo, and that looks really clean. Would love a PR against the `v3.0.0` branch!

**Comment by mxstbr** [comment]
Done with d614130, thanks for the suggestion @yjcxy12!
