### ISSUE TITLE
Linting problems after upgrading node to 6.2

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#870]
After upgrading to Node 6.2 the Eslint throws the following error for all files in the project.
```
7:1  error  Definition for rule 'no-global-assign' was not found    no-global-assign
7:1  error  Definition for rule 'no-unsafe-negation' was not found  no-unsafe-negation
```

Basically that is a first `import` line.
For example:
`import 'babel-polyfill';` or 
`import React, { Component } from 'react';` etc.

I've tried unsuccessfully to find a solution to this. The reason for the upgrade was the issue here https://github.com/mxstbr/react-boilerplate/issues/847

**Comment by immutablelist** [comment]
I have the same problem  too. It was working two days ago. I am using Node 6.3

**Comment by juandambra** [comment]
I have the same problem

**Comment by pavel06081991** [comment]
I have the same issue, so npm run clean throws these issues.

**Comment by gihrig** [comment]
This is a known issue, not related to versions of node or npm, please #864

**Comment by mxstbr** [comment]
Fixed, sorry for the delay!
