### ISSUE TITLE
history is listed as a dependency but doesn’t seem to be used

### ISSUE THREAD

**Issue by brandondurham** [mxstbr/react-boilerplate#878]
`history` is currently listed as a dependency in `package.json` but I don’t see it explicitly imported anywhere. Am I missing something? If not, I’m happy to make a PR…

**Comment by mxstbr** [comment]
I remember we used it back when `react-router` was a bit more in flux, but I'm not sure if we need it anymore.

Would you mind removing it and pushing up a PR? You'll get a deployed preview of the example app, where we can see if something is afoul without it!

**Comment by brandondurham** [comment]
Will do!

**Comment by samit4me** [comment]
Looks like it was remove in [this commit](https://github.com/mxstbr/react-boilerplate/pull/892/commits/47c7e13eb14b3b32a65caa223c9ee483a54bd97e)

**Comment by dawsonbotsford** [comment]
This should be closed. See @samit4me's comment above
