### ISSUE TITLE
Failed to parse SourceMap: http://localhost:3000/index.js.map

### ISSUE THREAD

**Issue by mydearxym** [mxstbr/react-boilerplate#881]
amazing work!

``` console
Failed to parse SourceMap: http://localhost:3000/index.js.map
```

the default project can't generate the index.js.map for debug , i have tried options in this [issue](https://github.com/webpack/webpack/issues/2145), but none of them work .  am i missing sth?

env:
   mac OS 10.11
   node 5.12
   chrome  52.0.2743.116 (64-bit)

**Comment by Dattaya** [comment]
I was able to debug in Chrome after I had set `devtool` to `inline-source-map`, in `webpack.dev.babel.js`.

**Comment by mydearxym** [comment]
@Dattaya   i have tried this , but no luck for me ..

**Comment by Dattaya** [comment]
@mydearxym, here's a checklist for you:

- [ ] Master branch of `react-boilerplate` is used
- [ ] Chrome version is 52.x
- [ ] Application cache is clear (dev tools -> application -> clear site data) and page was refreshed with F5
- [ ] You have a breakpoint on the line that will be active during execution of that page

Is everything checked?

**Comment by mydearxym** [comment]
@Dattaya thanks, i check all those:

[✓] Master branch of react-boilerplate is used
[✓]  Chrome version is 52.x
[✓]  Application cache is clear (dev tools -> application -> clear site data) and page was refreshed with F5
[✓]  You have a breakpoint on the line that will be active during execution of that page

**Comment by Dattaya** [comment]
Something isn't right but I don't know what's causing this mistake. First of all, this repo does not generate index.js, so there shouldn't be index.js.map created, second, `inline-...` means that the sourcemap will be added as a comment directly to the source like this `//# sourceMappingURL=data:application/json;charset=utf-8;base64,` and that in turn means `*.map` files won't be generated. At first glance this mistake doesn't make much sense.
Maybe try to bump your webpack version to the latest beta or use another browser temporarily until it is resolved somewhere?

**Comment by mydearxym** [comment]
@Dattaya  Thanks for your patience.

Actually the way this react project display our code-error is very friendly,  it can easily locate the error with or without sourceMap file , souceMap is a plus though 。

PS:  the webpack version is the latest。

**Comment by mxstbr** [comment]
Did we ever find the root cause of this issue?

**Comment by Dattaya** [comment]
> Did we ever find the root cause of this issue?

I blame `webpack` unless @mydearxym has a better explanation. It's a beta software, what worked in a previous version might not work in the current. I tried to debug `dev` branch with `inline-source-map` devtools option set and it worked. I'll reopen this issue if more developers experience this problem.
