### ISSUE TITLE
SVG loading issue

### ISSUE THREAD

**Issue by debslab** [mxstbr/react-boilerplate#884]
When I build boilerplate in dev mode, then I don't see any issue regarding svg files. But when I build in production mode, following error is coming. in webpack config, I see that file-loader is used for SVG files. 
ERROR in ./app/components/Header/product.svg
Module parse failed: D:\webui\react-boilerplate\app\components\Header\product
.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" encoding="UTF-8" standalone="no"?>
| <svg width="72px" height="72px" viewBox="0 0 72 72" version="1.1" xmlns="http:
//www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
|     <title>product</title>
 @ ./app/components/Header/index.js 14:52-79

Please let me know how I can fix this

**Comment by uzarubin** [comment]
@debslab how is the SVG file being imported?

**Comment by debslab** [comment]
@uzarubin Yes, I am doing like this. For me, it's working in dev build. If I run in prod mode, webpack complains about loader. After seeing your comment, I thought I will try with fresh boilerplate setup and guess what, it started working. Probably I messed up some settings. I will close the bug. Regret the inconvenience.
