### ISSUE TITLE
How to update my react.js app with the future version of this boilerplate?

### ISSUE THREAD

**Issue by rcholic** [mxstbr/react-boilerplate#889]
I am about to finish a react app based off of this boilerplate, and as you can imagine, I have replaced the remote origin with my own personal git repo. I was wondering how to update my boilerplate with the future release of this boilerplate without interrupting my components/containers. Any idea is appreciated

**Comment by juangl** [comment]
Maybe if You add this repo as remote and then, fetch, make a rebase between your branch and react-boilerplate, resolve conficts, and commit.

**Comment by gihrig** [comment]
I have tried a couple of techniques to do this. It's a lot of work with mixed results.

1. Maintain two separate repos, react-biolerplate (RBP) and my-project (MP). Use a compare utility (I use [Beyond Compare](http://www.scootersoftware.com/)) to manually compare and copy changes from RBP to MP.
2. In a fork of RBP, create MP in a dedicated branch and use git compare and merge changes. I use a [visual git UI](http://gitup.co/). I'm still working through this, not certain it's any better method.

Having said that, the official word is that it was [never meant to be](https://github.com/mxstbr/react-boilerplate/issues/600#issuecomment-228722547).

**Comment by mxstbr** [comment]
> I would love love love to provide an upgrade path for existing projects but the thing is that it's quite simply not possible. If you have any idea how to make that happen I would very very happily add it.
> This is a boilerplate, a starting point, not a library. Updating isn't a thing that should happen, because the idea of a boilerplate is that the user changes it. A library isn't meant to be changed by the user, which is why it can be updated with a simple npm install.

(src: #600)

**Comment by rcholic** [comment]
Not sure if everyone knows `mirroing repo` could help with future update with this boilerplate, but from my reading of this [post here](https://help.github.com/articles/duplicating-a-repository/), I think it might answer the question I asked in the original post.

**Comment by gihrig** [comment]
@rcholic Looks promising. Please keep us updated on your experience with this.

I may give it try in the next week or so, I'll post back with my findings as well.

**Comment by barbalex** [comment]
[Mirroring](https://help.github.com/articles/duplicating-a-repository/) the boilerplate repo as proposed by @rcholic was the only way I could set this up. Will need to see if this works long term.

**Comment by gihrig** [comment]
I still haven't tried out mirroring, but this is the setup that more-less works for me:

YMMV!:

1. Fork `react-boilerplatee`
2. Clone fork into new local react-boilerplate
3. Create new`main` branch for your project, leaving `master` and `dev` for the boilerplate
4. `git remote add upstream... ` {react-boilerplate url.git}
5. `git remote remove origin` then`git remote add origin... ` {fork url.git}
6. Copy your project components/containers, etc., into  new project just created.
7. Keep `master` and `dev` updated with fetch and pull from `upstream`
8. Merge `dev` into your `main`, `development`, `whatever` branches  as needed.

You will likely have merge conflicts to resolve and as your project diverges from upstream this may not be maintainable.

**Comment by loicginoux** [comment]
In my case, my own project has diverged too much from the boilerplate, I keep the boilerplate as a remote repository and cherry-pick the commits I need on my project.
