### ISSUE TITLE
Use Rollup for smaller JS bundles

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#89]
See https://github.com/interactivethings/catalog/pull/83#issuecomment-171572649

> Note: If you submit a PR, do it against the `v3.0.0` branch please!

**Comment by herrstucki** [comment]
Just a quick note (I saw that you referenced my Catalog PR): It's probably not possible to use rollup for apps if you want to use webpack loaders (e.g. to import CSS) or code splitting (by using webpack's `require.ensure()` or webpack 2's `System.import()`).

**Comment by mxstbr** [comment]
Ah that's a shame, thanks for jumping in and saving me lots of research time! Much appreciated.
