### ISSUE TITLE
[suggestion] Remove pagespeed

### ISSUE THREAD

**Issue by fisch0920** [mxstbr/react-boilerplate#893]
Using `slow-deps`, it appears that `psi` is the largest and most time-consuming npm dependency by far.  Given that I'm guessing most people don't even really use `npm run pagespeed`, I'd like to start a discussion here regarding removing this feature from `react-boilerplate`.

**Comment by mxstbr** [comment]
I did not know that, and that sounds reasonable!

**Comment by fisch0920** [comment]
I'd suggest running `slow-deps` yourself, but for my project which builds on react-boilerplage, here are the most pertinent results:

```
-------------------------------------------------------------------------------
| Dependency                                     | Time     | Size   | # Deps |
-------------------------------------------------------------------------------
| psi                                            | 2m 44.2s | 18 MB  | 323    |
| webpack                                        | 1m 42.6s | 14 MB  | 192    |
| node-sass                                      | 1m 35.6s | 13 MB  | 180    |
| stylelint                                      | 1m 27.6s | 16 MB  | 164    |
| karma                                          | 1m 11.6s | 16 MB  | 153    |
| css-loader                                     | 58.9s    | 11 MB  | 115    |
| isparta                                        | 54.2s    | 12 MB  | 102    |
| enzyme                                         | 53.7s    | 9.6 MB | 121    |
| ngrok                                          | 53.7s    | 19 MB  | 98     |
| karma-coverage                                 | 50s      | 7.2 MB | 98     |
| isparta-loader                                 | 42.8s    | 12 MB  | 103    |
| babel-preset-es2015                            | 37.3s    | 6.6 MB | 93     |
| postcss-cssnext                                | 36.8s    | 9.7 MB | 78     |
| babel-preset-stage-0                           | 34.5s    | 4.4 MB | 56     |
| html-webpack-plugin                            | 34s      | 6.0 MB | 76     |
| babelify                                       | 32.3s    | 5.9 MB | 55     |
| babel-core                                     | 23.9s    | 5.9 MB | 53     |
| html-loader                                    | 23.5s    | 4.6 MB | 66     |
| express                                        | 22.8s    | 1.0 MB | 42     |
| request                                        | 22.7s    | 3.2 MB | 66     |
```

Note that some of these may differ from what's in react-boilerplate now, but it'll at least give this discussion some context.

**Comment by mxstbr** [comment]
Let's get rid of pagespeed which should make everything a huge deal faster as a first step.

`stylelint` (cc @jeddy3) and `webpack` (cc @TheLarkinn) should look into shedding some weight! I'm not sure why they need 14 and 16 MB (16777216 characters!) of data respectively on `npm`, there must be huge room for optimization there!

`enzyme` (and `karma`, `mocha` and `expect`) might be removed when Jest snapshot testing is more stable, as that essentially solves all the component testing issues. (not 100% sure about this yet though) cc @cpojer for the timeline on this.

*`isparta` will be removed with #795, but I'm not really sure how much of a difference the switch to `istanbul` will make.*

**Comment by fisch0920** [comment]
Awesome! Props to `slow-deps` @nolanlawson 👍

**Comment by jeddy3** [comment]
Great initiative!

I've created a [PR in stylelint](https://github.com/stylelint/stylelint/issues/1825) to discuss removing our untranspiled source files from the npm package, as this will save a meg or so.

However, I've poked around stylelint's dependencies and I'm not sure there's much we can do about the bulk it. You see, the majority of the weight is the [caniuse](https://github.com/Fyrd/caniuse) data. Autoprefixer uses it, which we use in turn to make rules like [`property-no-vendor-prefix`](http://stylelint.io/user-guide/rules/property-no-vendor-prefix/) smarter. Another rule that use the data is [`no-unsupported-browser-features`](https://github.com/stylelint/stylelint/tree/master/src/rules/no-unsupported-browser-features), as it wraps the [doiuse](https://github.com/anandthakker/doiuse) tool.

If anyone has any ideas how to shrink things though, then please open an issue in [stylelint issue tracker](https://github.com/stylelint/stylelint).

**Comment by TheLarkInn** [comment]
We'll probably need an issue tracker for this, to see if we can cut any 'baby-fat' off the deps.

**Comment by cpojer** [comment]
@mxstbr we are planning on a big Jest release this week. You can also use enzyme with Jest just fine :)

**Comment by gihrig** [comment]
Handled by #1352 

@fisch0920 Thanks for raising the issue! 🎉
