### ISSUE TITLE
3.1.0 Installation Failure (cross-spawn)

### ISSUE THREAD

**Issue by azampagl** [mxstbr/react-boilerplate#897]
## Issue Type

- [X] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

npm run setup fails on fresh pull.

## Steps to reproduce

Clone fresh copy of repo on brand new CentOS 7 OS, Node 6.4 virtual machine. npm run setup fails due to "SyntaxError: Unexpected token ILLEGAL" on cross-spawn?

# Versions
Vagrant: 1.8.5
Virtualbox: 5.1.4
OS: CentOS 7
Node: v6.4.0
NPM: 3.10.3

# Error Message
[vagrant@localhost react-boilerplate]$ npm run setup

> react-boilerplate@3.1.0 presetup /srv/react-boilerplate
> npm i chalk shelljs

react-boilerplate@3.1.0 /srv/react-boilerplate
├─┬ chalk@1.1.3 
│ ├── ansi-styles@2.2.1 
│ ├── escape-string-regexp@1.0.5 
│ ├─┬ has-ansi@2.0.0 
│ │ └── ansi-regex@2.0.0 
│ ├── strip-ansi@3.0.1 
│ └── supports-color@2.0.0 
└─┬ shelljs@0.7.3 
  ├─┬ glob@7.0.5 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.5 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.1 
  │ ├─┬ minimatch@3.0.3 
  │ │ └─┬ brace-expansion@1.1.6 
  │ │   ├── balanced-match@0.4.2 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.3.3 
  │ └── path-is-absolute@1.0.0 
  ├── interpret@1.0.1 
  └─┬ rechoir@0.6.2 
    └── resolve@1.1.7 

> react-boilerplate@3.1.0 setup /srv/react-boilerplate
> node ./internals/scripts/setup.js

Cleaning old repository ✓
Installing dependencies ✓. (This might take a while)Installing dependencies
Initialising new repository ✓
Done![..................] \ : sill lifecycle react-boilerplate@3.1.0~setup: Args
> react-boilerplate@3.1.0 postsetup /srv/react-boilerplate
> npm run build:dll

> react-boilerplate@3.1.0 build:dll /srv/react-boilerplate
> node ./internals/scripts/dependencies.js

Building the Webpack DLL...
/srv/react-boilerplate/node_modules/cross-spawn/lib/parse.js:97
        sheb
            
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/react-boilerplate/node_modules/cross-spawn/index.js:4:13)
    at Module._compile (module.js:556:32)

**Comment by amilajack** [comment]
Are you still getting this error?

**Comment by azampagl** [comment]
Unfortunately, I haven't tried to get it up and running since then. I'm thinking it might have been an issue with Vagrant/Virtualbox?

**Comment by amilajack** [comment]
Maybe a cross platform linux error?
