### ISSUE TITLE
Component className={props.className} css not working

### ISSUE THREAD

**Issue by billyshena** [mxstbr/react-boilerplate#898]
Hello guys ! I'm currently facing a strange issue about why the css is not applied to my component, here is my code sample:

```
// InputComponent.js
function Input(props) {
  return (
    <div className={styles.input}>
      <input className={props.className} type={props.type} required={props.required} placeholder={props.placeholder} />
    </div>
  );
}


// InputComponent.css
.input-lg { height:50px; } // Not working
:global(.input-lg) { height: 50px; } // Working

```

```
// FormComponent.js
<Input className="input-lg" type="email" required placeholder="Adresse e-mail"/>
```

Any ideas why I have to use ':global(.my_class_name)' to make the css applied to my component?
Is it the fact that I generate the className using 'props' ?

Best,

**Comment by mxstbr** [comment]
Please see the documentation about css modules, it will answer your question perfectly!

**Comment by nickbarry** [comment]
Sweet! I had this question too.
