### ISSUE TITLE
Webpack DLL config does not extend base config

### ISSUE THREAD

**Issue by Augustin82** [mxstbr/react-boilerplate#902]
After `npm install`-ing, the Webpack DLL build was failing for me, claiming that it did not know how to parse json files. This was making me crazy, as the json loader was correctly configured in my `webpack.base.babel.json`.

After investigating, I noticed that `webpack.base.babel.json` is NOT used by `webpack.dll.babel.json`. It's probably on purpose (;)) but it may be quite confusing for people like me who just discovered the feature and were hoping it'd "just work".

Maybe there could be a way of letting users know that base loaders don't apply for the dll phase?

**Comment by chaintan17** [comment]
Yes, it confused me also.

**Comment by mxstbr** [comment]
Ah yeah, that's definitely a bug, it `dll` should extend from `base`. Would you mind submitting a PR fixing this?

**Comment by mxstbr** [comment]
Done by the amazing @chaintan17 in #930
