### ISSUE TITLE
Question: How to debug tests ? 

### ISSUE THREAD

**Issue by jptissot** [mxstbr/react-boilerplate#903]
#  Question
How to debug tests with this boilerplate ?

## Steps Taken
Added this line in the package.json scripts : 
`  "test:debug": "cross-env NODE_ENV=test karma start internals/testing/karma.conf.js --single-run=false --debug"` to run the tests in debug mode.

I also modified karma.conf.js to only include the coverage reporter if the debug arg is not set
``` 
const webpackConfig = require('../webpack/webpack.test.babel');
const argv = require('minimist')(process.argv.slice(2));
const path = require('path');

module.exports = (config) => {
  config.set({
    frameworks: ['mocha'],
    reporters: ['mocha'],
    browsers: process.env.TRAVIS // eslint-disable-line no-nested-ternary
      ? ['ChromeTravis']
      : process.env.APPVEYOR
        ? ['IE'] : ['Chrome'],

    autoWatch: false,
    singleRun: true,

    client: {
      mocha: {
        grep: argv.grep,
      },
    },

    files: [
      {
        pattern: './test-bundler.js',
        watched: false,
        served: true,
        included: true,
      },
    ],

    preprocessors: {
      ['./test-bundler.js']: ['webpack', 'sourcemap'], // eslint-disable-line no-useless-computed-key
    },

    webpack: webpackConfig,

    // make Webpack bundle generation quiet
    webpackMiddleware: {
      noInfo: true,
      stats: 'errors-only',
    },

    customLaunchers: {
      ChromeTravis: {
        base: 'Chrome',
        flags: ['--no-sandbox'],
      },
    },
  });
  // Only include coverage if we are not in debug mode
  if (!argv.debug) {
    config.set({
      reporters: ['coverage', 'mocha'],
      coverageReporter: {
        dir: path.join(process.cwd(), 'coverage'),
        reporters: [
          { type: 'lcov', subdir: 'lcov' },
          { type: 'html', subdir: 'html' },
          { type: 'text-summary' },
        ],
      },
    });
  }
};
```

When I open the Karma debug window, Even when I try to navigate to the source maps, I get garbled code. 
![image](https://cloud.githubusercontent.com/assets/4681586/17861440/1b4cc8b6-685f-11e6-8086-8ea55bb4ddce.png)

Has anyone been able to debug the components / unit tests ? 

Thank you.

## Boilerplate version : 3.0

**Comment by charch** [comment]
I found that the issue lies in the internals/webpack/webpack.test.babel.js which utilizes 'isparta' is a code coverage tool for karma. I created a webpack.testdebug.babel.js that just doesn't include the isparta settings, and debugging karma tests in the browser should work.

**Comment by mxstbr** [comment]
We've switched away from `isparta` to `istanbul` — would you mind trying out the `dev` branch?

**Comment by jptissot** [comment]
Yes, `istanbul` works much better. Thanks.
