### ISSUE TITLE
Hot reloading after bug is fixed?

### ISSUE THREAD

**Issue by tzusman** [mxstbr/react-boilerplate#905]
`index.js?0963:199 Uncaught TypeError: _get__(...).unmountComponentAtNode is not a function`

If I have a container that uses an undefined component, I'm shown a red background with `ReferenceError: MenuItem is not defined`.  I then fix the issue by importing the component. Upon save, webpack rebuilds, leading to an `unmountComponentAtNode is not a function` error.  Not sure if there is an elegant way to reload under this circumstance, but maybe an automatic full-page reload would work?

**Comment by gihrig** [comment]
@tzusman Does a manual page reload (Ctrl/Cmd-R) get things working again?

**Comment by tzusman** [comment]
Yep, works perfectly after the reload

**Comment by mxstbr** [comment]
Hmm, that'd definitely be preferable, but I really have no idea how one would go about fixing that!

**Comment by mxstbr** [comment]
I'm pretty sure this will only be fixed when react hot loader v3 is stable. See #1068 for more information!
