### ISSUE TITLE
Large image in README

### ISSUE THREAD

**Issue by jt3k** [mxstbr/react-boilerplate#907]
github web-interface is supported only 888 for width

 image in header have filesize 1.2mb and measures 2326 x 676px

I prepare two images:
1. original size 2326x676px but  filesize is 274KB ![banner-metal](https://cloud.githubusercontent.com/assets/1261240/17897541/371e9084-695d-11e6-98f1-b7925bf89e28.jpg)
2. down-scaled size 888x258 53KB ![banner-metal_](https://cloud.githubusercontent.com/assets/1261240/17897533/338c0406-695d-11e6-9476-cde12fa84987.jpg)

let's choose the size and replace the image in the header!

**Comment by SimonSelg** [comment]
Good point. 

> github web-interface is supported only 888 for width

While that's true there are devices with a HighDPI screen (such as the Macbook from which I'm writing this) - from these devices the high res version makes sense.

See this screenshot (you might need to zoom in to see the difference if you're not on a highdpi device):
![image](https://cloud.githubusercontent.com/assets/9430680/18123498/6f3c9d78-6f6e-11e6-9688-38176b7425a8.png)

But compressing the image while keeping the resolution is a good idea 👍

**Comment by lucidlemon** [comment]
![banner-metal](https://cloud.githubusercontent.com/assets/2458762/18167631/f7eb5fc2-7051-11e6-830f-4b0e7b4b601e.jpg)

I'd have a version at exactly @2x for retina screens prepared and optimized right here :) 206kb in size.

**Comment by mxstbr** [comment]
Awesome! Feel free to submit a PR to change this to a smaller image!

**Comment by KarandikarMihir** [comment]
We are getting the brand image from [another](https://github.com/mxstbr/react-boilerplate-brand) repository. If we are to change the image, how would you want to go about this? @mxstbr 

**README.md**
`<img src="https://raw.githubusercontent.com/mxstbr/react-boilerplate-brand/master/assets/banner-metal.jpg" alt="react boilerplate banner" align="center" />`

**Comment by justingreenberg** [comment]
maybe take a look at https://github.com/FormidableLabs/react-progressive-image...

```js
import mainImage from 'main-image.jpg'
import compressedImage from 'compressed-image.jpg'

<ProgressiveImage src={mainImage} placeholder={compressedImage}>
  {(src) => <img src={src} alt="react boilerplate banner" />}
</ProgressiveImage>
```

_side note: the `alt` tag string should be internationalized :)_

@KarandikarMihir please make a companion pull request with assets to the other repository :)

**Comment by KarandikarMihir** [comment]
@justingreenberg :sweat_smile: If I'm not mistaken, we only need to update `README.md`, right? That's what the issue title says, anyway- `Large image in README #907`. 

Are you confusing it with brand image from the home page of example app?

**Comment by justingreenberg** [comment]
@KarandikarMihir haha yes. it's very late over here in nyc 😜  still i've been looking for an excuse to use `react-progessive-image` tho, so i stand by it recommendation for homepage!!

**Comment by KarandikarMihir** [comment]
@justingreenberg Looks like you need to get some sleep! :grin: Good hunt though, I'll try to implement medium.com style lazy image loading using `react-progressive-image` in my project.

Any suggestions on how to change image in `README.md`? You can see that the current image comes from a different repo. Can we add the optimized/new image in the boilerplate root and do something like this- 
`![Alt text](http://full/path/to/img.jpg "Title")` ?

**Comment by mxstbr** [comment]
Please submit a Pull Request against https://github.com/mxstbr/react-boilerplate-brand and add an optimised version of the banner to the folder, and then submit a Pull Request against this repo to swap the link in the README to the one pointing to the optimised version!

**Comment by mxstbr** [comment]
Fixed by the amazing @KarandikarMihir! 👏

**Comment by KarandikarMihir** [comment]
(Thank you)[https://i.imgur.com/ea1LOX7.png] @mxstbr 
Happy to be of help!
