### ISSUE TITLE
replace sanitize.css to normalize.css 

### ISSUE THREAD

**Issue by pavel06081991** [mxstbr/react-boilerplate#908]
I wanted to replace sanitize.css to normalize.css so I added normalize.css to package.json and removed sanitize.css from this file. But then I saw that sanitize.css is also there is in 
```
 "dllPlugin": {
    "path": "node_modules/react-boilerplate-dlls",
    "exclude": [
      "chalk",
      "compression",
      "cross-env",
      "express",
      "ip",
      "minimist",
      "sanitize.css"
],
```
in package.json
Should I replace normalize.css to sanitize.css in this place too? And maybe there are any other steps I need to do to use normalize.css instead of sanitize.css?

**Comment by alexwizp** [comment]
I faced with the same problem =(
Could you please help us?

**Comment by gihrig** [comment]
Normalize and Sanitize are very similar, could be a drop-in replacement.

A project-wide search for `sanitize.css` shows several locations where sanitize is used.

What happens if you replace all sanitize with nornalize?

If you don't want to risk your dev project, clone a new copy and play there. e.g.

git clone `https://github.com/mxstbr/react-boilerplate.git react-bp`

**Comment by Augustin82** [comment]
> If you don't want to risk your dev project, clone a new copy and play there. e.g.

Just for informtation: you could (should?) simply create a new branch, e.g., `git checkout -b sanitizeToNormalize`, which you can then switch out of if things don't work out. Please note that you will need to use NPM commands (`install`, `update`, `prune` and so on) to make sure that the dependencies you're not using in each branch are not kept.

**Comment by pavel06081991** [comment]
@gihrig, maybe it looks similar, but it is not the same. I'll explain why I want to replace it to normalize.css. If you look at sanitize.css code you will see such rules:

```
html {
	box-sizing: border-box;
}
```

and:
```

*,
::before,
::after {
	box-sizing: inherit;
}
```

Why it is bad? Because it is not the default browser behaviour and if I add any components library it expects that DOM elements have "box-sizing: content-box" because it is W3C standard, and components of this library will be broken because of sanitize.css. I have no idea why you choosed sanitize.css

**Comment by gihrig** [comment]
@pavel06081991 Thank for the explanation.

Did you try a simple search and replace? How did that work?
