### ISSUE TITLE
Test warnings

### ISSUE THREAD

**Issue by samit4me** [mxstbr/react-boilerplate#909]
When running the tests `npm test` the following warnings are mixed in with the test output:

```
ERROR: 'Warning: Failed prop type: Required prop `href` was not specified in `A`.
ERROR: 'Warning: Failed prop type: Required prop `children` was not specified in `A`.
ERROR: 'Warning: Failed prop type: Required prop `children` was not specified in `Button`.
ERROR: 'Warning: Failed prop type: Invalid prop `src` of type `object` supplied to `Img`, expected `string`.
ERROR: 'Warning: ReactComponentTreeDevtool: Missing React element for debugID 17 when building stack'
```

It does not cause any issues and does not fail the tests, it simply clutters the test output.

After some investigation, I've managed to resolve the warnings, but I'm new to open source and wasn't sure if I should submit a PR or create an Issue first?

**Comment by gihrig** [comment]
@samit4me Yes, please open a PR. 👍 

See [CONTRIBUTING.md](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md) for details.
