### ISSUE TITLE
Feedbacks after deploying to Heroku

### ISSUE THREAD

**Issue by loicginoux** [mxstbr/react-boilerplate#914]
Not sure if it can help but here is few points about deploying the app to heroku:
- because I am using Material-UI, and there is an error which looks like this

```
ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: MY_APP_PATH/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
```

I needed to `{ test: /\.json$/, loader: 'json-loader' },` to the `module.loaders` of the file `webpack.dll.babel.js

 
- There is a confusion between the documentation which says to add `postinstall": "npm run build:clean` but the package.json contains already `"postinstall": "npm run build:dll",`. I think the correct one is build:dll...

- Nowhere in the deployement process described in your documentation, we call `npm run build` to actually build the ./build directory. Not sure if it's me or the doc which has a problem...
To have a better look here are the lines that can help:
My Procfile  `web: npm run start:prod`
In my package.json:

```
"prebuild": "npm run build:clean && npm run test",
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p",
    "build:clean": "npm run test:clean && rimraf ./build",
    "build:dll": "node ./internals/scripts/dependencies.js",
    "start": "cross-env NODE_ENV=development node server",
    "start:tunnel": "cross-env NODE_ENV=development ENABLE_TUNNEL=true node server",
    "start:production": "npm run build && npm run start:prod",
    "start:prod": "cross-env NODE_ENV=production node server",
```

So we this, deploying to heroku works but the /build directory is not found.

- Then I tried to add to my Procfile  `web: npm run start:production`
But then Heroku couldn't start within 60 sec with a memory quota limit error:

```
2016-08-24T15:18:23.896122+00:00 app[web.1]: > cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p
2016-08-24T15:18:23.896123+00:00 app[web.1]:
2016-08-24T15:19:14.086729+00:00 heroku[web.1]: Process running mem=531M(103.8%)
2016-08-24T15:19:14.086915+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-08-24T15:19:20.117496+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-08-24T15:19:20.117650+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-08-24T15:19:20.321860+00:00 heroku[web.1]: Process exited with status 137
2016-08-24T15:19:20.338089+00:00 heroku[web.1]: State changed from starting to crashed
```

The only way to make my deploy work on heroku was to build locally, commit ./build to git and have only in my  Procfile  `web: npm run start:prod` to serve /build directory.

I am not really happy with having to commit my build directory to git but didn't find another way to make it work.

Let me know if someone managed to solve this in a better way. I guess that will help few others that have had difficulties deploying to heroku.

**Comment by KSMorozov** [comment]
> The only way to make my deploy work on heroku was to build locally, commit ./build to git and have only in my Procfile web: npm run start:prod to serve /build directory.
Confirm that's the only way, and yeah def not the best thing in the world.

**Comment by xcarpentier** [comment]
Hello,
Cleaning build on heroku : no sense. Otherwise, you can't executing your tests on heroku too. And there is inheritance between prebuild, build and postbuilt...

So, I found a 'simple' solution (WIP), but just modify the 'postinstall' npm task calling a new heroku npm task :

- "postinstall": "npm run heroku",

- "heroku": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p"

I hope thats help.

**Comment by jimbofreedman** [comment]
I've found even that causes Heroku to time-out.

**Comment by andykenward** [comment]
Make sure you set `NPM_CONFIG_PRODUCTION=false` on heroku. Without this `devDependencies` won't be installed. Which are needed for this boilerplate to build.

If you have heroku cli installed you can
`heroku config:set NPM_CONFIG_PRODUCTION=false --app your-app-name`

else go to the settings tab on your app and add in Config Variables

**Comment by mxstbr** [comment]
Is there something to be PR'd here to the documentation? Would appreciate an update with the recommended approach!

**Comment by hew** [comment]
I can confirm @loicginoux OP that building locally and pushing the build folder to Heroku is the way to go. 

I can push some changes to the documentation when I have some time (least I could do for this awesome boilerplate) but in the meantime: 

**(in Procfile)**
```
web: npm run start:prod
```

**Steps to deploy**

``heroku git:remote -a your-app-name``
``NPM_CONFIG_PRODUCTION=true`` 
``npm run build``
``git checkout -b heroku-deployment && git add -f build/*``
``git commit -m "This is an example of a heroku deployment.``
``git push heroku master``

**Comment by loicginoux** [comment]
Ok thanks, well if anyone has a better way of doing it, let us now later. For now I close this issue.
Thank you.

**Comment by nappels** [comment]
@mxstbr @loicginoux Heroku has a script hook you can use for this, so you don't have to track the generated build folder in git. 

#### add to package.js scripts object

`"heroku-postbuild": "npm run build"`

This will run the build task after installing all dependencies when deploying the app.

I'd be happy to submit a PR to the Heroku deploy docs.

**Comment by nappels** [comment]
@mxstbr @loicginoux Opened up PR #1111 with the added step in the deploy docs.

**Comment by mxstbr** [comment]
Thanks @nappels, that looks great!
