### ISSUE TITLE
Question: How can i shrink the main.js build file?

### ISSUE THREAD

**Issue by chaintan17** [mxstbr/react-boilerplate#918]
Hi, currently, production build has `main.js` file size around 200+ kb.
And it took 2-3 seconds before the first paint (something show on the page)
I wonder is there anyway to identify which dependencies should be remove in order to lower this size?
Or, is there any way to show something during waiting this `main.js` to be loaded successfully ?

Thank you so much.

**Comment by gihrig** [comment]
Where does Chrome Developer show tools Network tab show the time is being spent?

**Comment by mxstbr** [comment]
> Or, is there any way to show something during waiting this main.js to be loaded successfully ?

Yes, you could put HTML within the `div#app` in the `index.html`:

```HTML
<div id="app">
  <div class="loading-spinner" />
</div>
```

This would then be shown until the javascript has loaded and react mounts on that node, which clears all the contents and thus hides the loading indicator!

**Comment by chaintan17** [comment]
@mxstbr i run
`npm run analyze`
on master branch but it only show

```
{
  "errors": [],
  "warnings": []
}
```

in `stats.json` file 😕

**Comment by chaintan17** [comment]
![image](https://cloud.githubusercontent.com/assets/2979072/18155530/96d5015c-7038-11e6-9ea8-74077d80c338.png)

@gihrig Here is what it show in network tab.
It tooks almost 1.5seconds for the first paint.
I try to find the way to lower download time in main.js (orange box)

Anyway, font-awesome already using CDN, but still took a while for TTFB.

And the bluebox, i have no idea why it's idle.

If you have any advise,

**Comment by gihrig** [comment]
@chaintan17 A couple of thoughts:
1. You have `Disable cache` checked, so this graph is for first-load only. How is it with cache enabled?
2. That CDN performance is _terrible_. You could improve first-load performance by hosting `font-awesome.min.css` on your server.
3. `main.a212...` seems to be the real problem (as you pointed out), why is it blocking other downloads initiated by 1860?
4. Why are so few downloads occurring in parallel? Compare a github repo page.

I know, more questions, no real answers...

I'm guessing, a lot of the problem is due to server configuration. Where is this app hosted? If you control the server and first-load performance is important, you might consider a caching reverse proxy, like [varnish](https://varnish-cache.org/intro/index.html#intro)

**Comment by chaintan17** [comment]
@gihrig I check boilerplate project, `main.js` also block others chunk js. See below picture.
![image](https://cloud.githubusercontent.com/assets/2979072/18158408/5233c258-704d-11e6-816a-30b738990ccd.png)

**Comment by gihrig** [comment]
> And yes, witch cache enable, it's fast.

So is slower first-load performance really a problem? I'm not saying it isn't, that's something you must decide based on the app's audience.

Regardless, I am curious to see how a plain react-boilerplate demo app performs on the host your app is running on (assuming the first graph is not from 'localhost`).

**Comment by gihrig** [comment]
> I wonder is there anyway to identify which dependencies should be remove in order to lower this size?

Thinking about your original question and combining @mxstbr' idea for a loading 'spinner', could you replace `loading-spinner` with a page containing the static content that would be replaced once the JS was fully operational? Sort of a 'poor man's' server-side-render.

**Comment by chaintan17** [comment]
@gihrig i c your point. Yes, my site usually serve non repetitive audience. So, i have mainly concern on first load.

I have one more input, my project is using `react-widgets` and look like webpack did pack the whole lib `*.js` file which i actually need only `dropdownlist`. Please see below picture, it's analyze from `build:dll`

![image](https://cloud.githubusercontent.com/assets/2979072/18191740/debd1102-70f7-11e6-99a5-308b05cf247e.png)

When i do import, i already did 
`import DropdownList from 'react-widgets/lib/DropdownList';
 
I have no idea to let webpack know that i only need dropdownlist :confused:

And also, is `lodash` that really big size?

**Comment by gihrig** [comment]
Nice diagram 😉 

There is something about import, I'm not too sure about this, but I believe that:

The way lodash (and just about everything else) is imported, the entire library is imported:

[`import { conformsTo, isEmpty, isFunction, isObject, isString } from 'lodash';`](
https://github.com/mxstbr/react-boilerplate/blob/master/app/utils/asyncInjectors.js#L1)

But
`import conformsTo from 'lodash/conformsTo';`
`import isEmpty from 'lodash/isEmpty';`
`import isFunction from 'lodash/isFunction';`

Would just import those functions. 

Give it a try and see what happens to your graph.

see this [Stackoverflow](http://stackoverflow.com/questions/35250500/correct-way-to-import-lodash)

See Mozilla [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) but this does not directly address this issue.

**Comment by mxstbr** [comment]
There's also a [`webpack-lodash-plugin`](https://www.npmjs.com/package/lodash-webpack-plugin) that takes care of doing that automatically

**Comment by mydearxym** [comment]
@mxstbr webpack-lodash-plugin uses [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) which has some [Limitations](https://www.npmjs.com/package/babel-plugin-lodash#limitations), one of them is : 

>Babel < 6 & Node.js < 0.12 aren’t supported

and this repo seems only [support node 5.0](https://github.com/mxstbr/react-boilerplate/blob/master/.travis.yml#L5) .

it's this possible to upgrade the  node version to 6.x ?

**Comment by mxstbr** [comment]
Just because we don't run node 6 on Travis doesn't mean anything, I use v6 and is working perfectly fine!

**Comment by mydearxym** [comment]
you're right node v6 works great, and webpack-lodash-plugin works great too!

**Comment by gihrig** [comment]
So, if webpack-lodash-plugin results in a smaller build, is there any reason not to use it in the boilerplate?

**Comment by mxstbr** [comment]
No, I just haven't really dug into the downsides of the magic it does. If there are none, I'd be happy to add it!

**Comment by Geeman201** [comment]
Hey,

First of all great project @mxstbr (and co) I've been using react-boilerplate for a while now and really enjoying the developer experience/performance it gives out the box, so thanks! 

I was wondering what the outcome of this was? Analysing my bundle I see the whole of lodash included when the only import comes from the following in asyncInjectors.js:

```javascript 
import { conformsTo, isEmpty, isFunction, isObject, isString } from 'lodash';
```

as suggested above if you change that import to the following the bundle size decreases (quite substantially in my case)...

```javascript 
import conformsTo from 'lodash/conformsTo';
import isEmpty from 'lodash/isEmpty';
import isFunction from 'lodash/isFunction';
import isObject from 'lodash/isObject';
import isString from 'lodash/isString';
```

Happy to look at changing this but: 
a. What is the reasoning for using lodash anyway? As far as I can see it's only used for validation
b. Should asyncInjectors.js be changed to the 'longer handed', but more 'performant' method shown above?

**Comment by zamrq** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20111802/20934281/30733a20-bc0d-11e6-853b-2f54295d623d.png)

Nothing happen with lodash-webpack-plugin, still big main.js files

**Comment by gihrig** [comment]
What happens if you modify `asyncInjectors.js` as shown in @Geeman201 's comment above?

**Comment by zamrq** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20111802/20937110/0c2a5d46-bc18-11e6-8a90-cf0437aab76b.png)
nothing

**Comment by zamrq** [comment]
```javascript
// import { conformsTo, isEmpty, isFunction, isObject, isString } from 'lodash';
import conformsTo from 'lodash/conformsTo';
import isEmpty from 'lodash/isEmpty';
import isFunction from 'lodash/isFunction';
import isObject from 'lodash/isObject';
import isString from 'lodash/isString';
```

**Comment by zamrq** [comment]
```javascript
// Important modules this config uses
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const OfflinePlugin = require('offline-plugin');
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

module.exports = require('./webpack.base.babel')({
  // In production, we skip all hot-reloading stuff
  entry: [
    path.join(process.cwd(), 'app/app.js'),
  ],

  // Utilize long-term caching by adding content hashes (not compilation hashes) to compiled assets
  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: '[name].[chunkhash].chunk.js',
  },
  babelQuery: {
    plugins: ['lodash'],
    presets: ['es2015', 'react'],
  },
  plugins: [
    new LodashModuleReplacementPlugin({
      collections: true,
      paths: true,
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      children: true,
      minChunks: 2,
      async: true,
    }),

    // Merge all duplicate modules
    // new webpack.optimize.DedupePlugin(),

    // Minify and optimize the index.html
    new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
    }),

    // Put it in the end to capture all the HtmlWebpackPlugin's
    // assets manipulations and do leak its manipulations to HtmlWebpackPlugin
    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',

      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],

      caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },

      // Removes warning for about `additional` section usage
      safeToUseOptionalCaches: true,

      AppCache: false,
    }),
  ],
});

```

**Comment by Geeman201** [comment]
Hey @zamrq 

First up.. 
Any performance analysis should be approached scientifically! [Some colleagues of mine preached this at Devoxx recently!](https://youtu.be/SgM-ZRs-CyY)

1. Figure out the baseline
2. Hypothesis that change x will have effect y
3. Make a single change
4. Rerun the test with only a single change
5. Compare baseline with the results for change x's effect
6. Throw out, build on, or confirm the hypothesis
7. Repeat

Now you say nothing happened when you made the suggested changes, but a lot of things appear to have happened. 

1. 5 png's appear to have been added
2. Your favicon disappeared
3. Your main.js file jumped from 776Kb to 985Kb 
4. A lot of other things changed. 

What I'm trying to get at is it looks as if rather than just the single lodash change (As suggested) many others have been made which kind of makes it hard for the community to give you help

What would help us help you (And you to help many others potentially) is if you can give us the following..

1. Build your app without lodash-webpack-plugin
2. Run `npm run analyze`
3. Upload the generated stats.json file to [this great webpack bundle visualiser](https://chrisbateman.github.io/webpack-visualizer/)
4. Find lodash in the chart, hover over it and screenshot it 
5. Change your app to use lodash-webpack-plugin
6. Repeats steps 2, 3, 4 and show us if it made a difference or not

If theres no difference between the size of lodash perhaps rather than changing lodash-webpack-plugin try the suggested change above where we import the specific lodash functions and repeat the experiment. 

Another question from me is do you have any of the following in your code base: 
```javascript
import { **ANY_LODASH_METHOD** } from 'lodash' 
```

Hopefully we can get to the bottom of this for you.

**Comment by zamrq** [comment]
sorry I had made a mistake when making screenshots about the build stats. wrong / different folders. I do not intend evil and makes you confused

I will try what you suggested, and immediately returned to the experimental results.
thanks for your help @Geeman201

**Comment by Geeman201** [comment]
No worries! Have you had any luck fixing your issue @zamrq?

Did you see the updates in #1309
