### ISSUE TITLE
npm run setup never ends up

### ISSUE THREAD

**Issue by pavel06081991** [mxstbr/react-boilerplate#919]
I cloned the repository and then ran "npm run setup" and it never ends up. About a week ago it worked normally but now it never ends up. What I see is "Installing dependencies... <This might take a while>".

**Comment by pavel06081991** [comment]
When I finished writing this issue it finally ended up! It took so much time, but if ended up!

**Comment by gihrig** [comment]
After `setup` completes, does `npm start` work?

Network problems?

If you do another clone and setup does it take a long time, or complete normally?

**Comment by pavel06081991** [comment]
I did another clone and did "npm run setup". It ended up only after 8 minutes! No network problems. During this time I see only "Installing dependencies... <This migth take a while>" in console. After this npm run start works normally.

**Comment by mxstbr** [comment]
This isn't really a bug with this boilerplate, that's just your network/`npm` being slow!
