### ISSUE TITLE
Remove isparta

### ISSUE THREAD

**Issue by samit4me** [mxstbr/react-boilerplate#924]
It looks like #795 swapped out `isparta` for `istanbul`, but I noticed that `isparta` has been left behind in [webpack.test.babel.js](https://github.com/mxstbr/react-boilerplate/blob/dev/internals/webpack/webpack.test.babel.js#L13-L17) and [package.json](https://github.com/mxstbr/react-boilerplate/blob/dev/package.json#L252-L253). Should this be removed? Would you like a PR?

**Comment by gihrig** [comment]
While I can't speak for @mxstbr, I would say PR? yes please!

Isparta is also mentioned in a code comment in [test-bundler](https://github.com/mxstbr/react-boilerplate/blob/dev/internals/testing/test-bundler.js#L11).

**Comment by samit4me** [comment]
Thank you and good find on test-bundler, I will submit PR tonight.
