### ISSUE TITLE
CDN assets (please help)

### ISSUE THREAD

**Issue by DJTouchette** [mxstbr/react-boilerplate#925]
Hey guys, 

I'm looking to make a CDN with the assets generated by webpack in the build folder. The problem i'm having is more web pack specific, when I link the two entry files (main.x.js, vendor.x.js) in the HTML file that are hosted on the CDN it in turn looks at the root for the files, how can i pass a argument to webpack on build to make the path relative to the files are hosted.

Any help would be greatly appricated

**Comment by gihrig** [comment]
Duplicate post
