### ISSUE TITLE
CDN assets (question)

### ISSUE THREAD

**Issue by DJTouchette** [mxstbr/react-boilerplate#926]
Hey guys, 

I'm looking to make a CDN with the assets generated by webpack in the build folder. The problem i'm having is more web pack specific, when I link the two entry files (main.x.js, vendor.x.js) in the HTML file that are hosted on the CDN it in turn looks at the root for the files, how can i pass a argument to webpack on build to make the path relative to the files are hosted.

Any help would be greatly appricated

**Comment by chaintan17** [comment]
I think this line is what you are looking for
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L22

add `    publicPath: '//cdn-path/',`
in this object.
