### ISSUE TITLE
sass support error 

### ISSUE THREAD

**Issue by mydearxym** [mxstbr/react-boilerplate#927]
thanks for the work!

follow the [sass guide doc](https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/sass.md), the build process is terminated by `npm run test` error

it seems [webpack.test.babel.js](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.test.babel.js#L34) do not have a sass loader, so i add it : 

```js
loaders: [
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.css$/, loader: 'null-loader' },
      { test: /\.scss$/, loader: ['style-loader', 'css-loader', 'sass-loader'] },     
     ...
```
and everything works fine,  is this a bug?

**Comment by gihrig** [comment]
No, not a bug. Did you see [/docs/css/sass.md](https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/sass.md) ?
