### ISSUE TITLE
[Enhancement] Routing transitions using react-router-transition

### ISSUE THREAD

**Issue by KarandikarMihir** [mxstbr/react-boilerplate#933]
First of all, thank you for creating this state-of-the-art boilerplate! We're using this boilerplate in our project. 

One thing that I observed is that route transitions are not smooth (because of chunking) and cause a terrible user experience especially for the ones having slow internet. So we decided to use [react-router-transition](https://github.com/maisano/react-router-transition). 

Since, most of the users of this boilerplate will face this issue at some point of time, can we include react-router-transition in the boilerplate itself?

**Comment by mxstbr** [comment]
`react-router-transition` is a bit too flashy imo, but I'd love to add a loading indicator while a new component is loaded. (something like the github top-loading-bar thingy) If you have any idea how to do that I'd love a PR!

**Comment by KarandikarMihir** [comment]
Alright, I'll give it a try, once I'm on my time.

**Comment by KarandikarMihir** [comment]
@mxstbr Just drawing your attention at [this MVP](https://github.com/KarandikarMihir/react-boilerplate/tree/feature-page-progress-bar). Could you take a look at it? Is that how we want to do it? It's very crude. I'd love to know what you think.

**Comment by mxstbr** [comment]
Generally a fan, but I'm wondering if there's a way to integrate with `react-router` to get the current loading percentage instead of faking it…

**Comment by KarandikarMihir** [comment]
@mxstbr Great. That gives a direction to me. I'll try to whip up something.

**Comment by KarandikarMihir** [comment]
@mxstbr From what I have read, there's no way to calculate progress. Since `System.import` is built on top of `Promise`, there's no way to get real loading percentage. Simply because `Promise` does not know how much time it's going to take to `resolve`. That being said, I found [progress-promise](https://github.com/numtel/progress-promise). But `progress-promise` also fakes the progress.

 That leaves us with `react-router` hooks. Your thoughts?

**Comment by mxstbr** [comment]
Thanks for digging in, that sounds way too hacky – let's just go with your solution in the example app, that's good enough! Could you submit a PR, and we'll iterate from there? Thanks so much!
