### ISSUE TITLE
Unable to remove reselect

### ISSUE THREAD

**Issue by IljaDaderko** [mxstbr/react-boilerplate#934]
I was trying to remove reselect from the boilerplate as advised in the following doc: https://github.com/mxstbr/react-boilerplate/blob/master/docs/js/remove.md
however changing history constant in app/app.js to whats shown in the doc makes page Load endlessly, I also believe that it is stuck in some sort of infinite loop as page gets frozen.

I believe doc's are a bit outdated, as even after `npm run clean` there are plenty of spaces where reselect needs to be removed.

**Comment by mxstbr** [comment]
Ah yes, that doc needs to be updated – would appreciate a PR fixing this!

**Comment by KarandikarMihir** [comment]
@mxstbr Can I take this one?

**Comment by KarandikarMihir** [comment]
## Removing `redux-saga`

**We don't recommend removing `redux-saga`**, as we strongly feel that it's the
way to go for most redux based applications.

If you really want to get rid of it, you will have to delete its traces from several places.

**app/store.js**
1. Remove statement `import createSagaMiddleware from 'redux-saga'`.
2. Remove statement `const sagaMiddleware = createSagaMiddleware()`.
3. Remove `sagaMiddleware` from `middlewares` array.
4. Remove statement `store.runSaga = sagaMiddleware.run`

**app/utils/asyncInjectors.js**
1. Remove `runSaga: isFunction` from `shape`.
2. Remove function `injectAsyncSagas`.
3. Do not export `injectSagas: injectAsyncSagas(store, true)`.

**app/routes.js**
1. Do not pull out `injectSagas` from `getAsyncInjectors()`.
2. Remove `sagas` from `importModules.then()`.
3. Remove `injectSagas(sagas.default)` from every route that uses Saga.

**Finally, remove it from the `package.json`. Then you should be good to go with whatever
side-effect management library you want to use!**

## Removing `reselect`

To remove `reselect`, remove it from your dependencies in `package.json` and then write
your `mapStateToProps` functions like you normally would!

You'll also need to hook up the history directly to the store. Make changes to `app/app.js`.

1. Remove statement `import { selectLocationState } from 'containers/App/selectors'`
2. Make necessary changes to `history` as follows:

```js

const selectLocationState = () => {
  let prevRoutingState;
  let prevRoutingStateJS;

  return (state) => {
    const routingState = state.get('route'); // or state.route

    if (!routingState.equals(prevRoutingState)) {
      prevRoutingState = routingState;
      prevRoutingStateJS = routingState.toJS();
    }

    return prevRoutingStateJS;
  };
};

const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: selectLocationState(),
});
```


How does this look?

**Comment by mxstbr** [comment]
Awesome @KarandikarMihir, absolutely perfect! Would you mind submitting a PR adding this to the docs? Then we can get this shipped to everybody asap!

**Comment by KarandikarMihir** [comment]
@mxstbr Thank you :smile: Does it have to be against `dev`?

**Comment by sedubois** [comment]
> Does it have to be against dev?

@KarandikarMihir yes

**Comment by KarandikarMihir** [comment]
@sedubois Great. Incoming PR.

**Comment by mxstbr** [comment]
Merged into `dev`, thanks so much @KarandikarMihir!

**Comment by KarandikarMihir** [comment]
@mxstbr You're welcome!!

**Comment by joaqtor** [comment]
I think this has become outdated. I'm not being able to remove `reselect` with this method.
