### ISSUE TITLE
HOC and routing

### ISSUE THREAD

**Issue by Stalso** [mxstbr/react-boilerplate#935]
Hello. Your async routing is really cool. But I do not understand, how can I use [Higher Order Components](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.f0ochc7hb). For example, I want to use  [this](https://github.com/mjrussell/redux-auth-wrapper) package. How can I write something like this, withour dynamic routes :

    // Redirects to /login by default
    const UserIsAuthenticated = UserAuthWrapper({
    authSelector: state => state.user, // how to get the user state
    redirectAction: routerActions.replace, // the redux action to dispatch for redirect
    wrapperDisplayName: 'UserIsAuthenticated' // a nice name for this auth check
    })

    ReactDOM.render(
    <Provider store={store}>
        <Router history={history}>
        <Route path="/" component={App}>
            <Route path="login" component={Login}/>
            <Route path="foo" component={UserIsAuthenticated(Foo)}/>
            <Route path="bar" component={Bar}/>
        </Route>
        </Router>
    </Provider>,
    document.getElementById('mount')
    )

Where in this code for boilerplate routing should I place `UserAuthWrapper` HOC  :

    {
        path: '/features',
        name: 'features',
        getComponent(nextState, cb) {
            System.import('containers/FeaturePage')
            .then(loadModule(cb))
            .catch(errorLoading);
        },
        },

**Comment by developer-rakeshpaul** [comment]
@Stalso please refer the solution provided in mjrussell/redux-auth-wrapper#40. I am also in the process of integrating the redux-auth-wrapper to my application. it is still work in progress.  Please find below the code i am using right now

My authwrapper util file
```
import { routerActions } from 'react-router-redux';
import { UserAuthWrapper } from 'redux-auth-wrapper';
import { selectCurrentUser } from '../containers/App/selectors';
import { fromJS } from 'immutable';

// Take the regular authentication & redirect to login from before
export const UserIsAuthenticated = UserAuthWrapper({
  authSelector: selectCurrentUser(),
  predicate: user => user !== fromJS({}),
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated',
});
```

My dashboard view which requires authentication
```
import { UserIsAuthenticated } from '../../utils/authWrappers';

@UserIsAuthenticated
export default class Dashboard extends React.Component { 
...
}
```

And in my login sagas module check for any redirect params specified in the request
like login?**redirect=%2Fdashboard** using the below code

selector code

```
const selectRoute = () => (state) => state.get('route');

/**
 * Other specific selectors
 */
const selectNextPathname = () => createSelector(
  selectRoute(),
  routingState => routingState.getIn(['locationBeforeTransitions', 'query', 'redirect'])
);

```
```
    // redirect to nextPathName or to the dashboard page
    const nextPathName = yield select(selectNextPathname());
    if (nextPathName) {
      yield put(push(nextPathName));
    } else {
      yield put(push('/'));
    }
```

hope this helps..

**Comment by Stalso** [comment]
Thank you,  I have another solution,  but yours is more elegant

**Comment by developer-rakeshpaul** [comment]
thanks @Stalso
