### ISSUE TITLE
Constantly reloading on Oneplus One, Chrome

### ISSUE THREAD

**Issue by dehrax** [mxstbr/react-boilerplate#938]
## Issue Type

- [X] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Site never loads properly on Oneplus One. Loading bar "reloads" indefenitely. It works on iPad Mini and ZTE Blade though.

This can be found in the Chrome DevTools on desktop:

```
offline-plugin: runtime.install() was executed without OfflinePlugin being added to webpack.config.js. The installation of offline-plugin has not been performed. You can ignore this message if you are skipping the OfflinePlugin during development. Otherwise, you may have a configuration issue.
```
## Steps to reproduce

Clone repo according to tutorial.

`npm run setup`

`npm start`

Try to access site from Oneplus One 

# Versions

- Node/NPM: 4.4.3/3.8.1
- Browser: Google Chrome 52.0.2743.98
- OS: Android 4.4.4: A0001 Build/KTU84Q

**Comment by gihrig** [comment]
The message you quoted

> offline-plugin: runtime.install()...

Is correct when in development mode, which is the case for `npm start`. It's merely informational.

> Site never loads properly on Oneplus One. Loading bar "reloads" indefenitely. It works on iPad Mini and ZTE Blade though.
> 
> This can be found in the Chrome DevTools on desktop:
> 

So the real problem is that the site never fully loads when using Oneplus One?

1. What makes you think the informational message is causing the problem?
2. I'm not familiar with Oneplus One, please provide a link.
3. Try in production mode `npm run start:production`

**Comment by mxstbr** [comment]
I have a OnePlus One, Two and Three and the react boilerplate site loads perfectly fine on all of the devices. Which browser/OS are you using?

**Comment by dehrax** [comment]
Cyanogen 11.0
Google Chrome 52.0.2743.98

The inability to properly load the site is only for the example app. After cleaning I am able to run my own app without any problem.

This is not a critical issue, I just wanted to give a heads up.

I solved the issue by cloning once again and setting up. I am unable to reproduce the issue.
