### ISSUE TITLE
Setting global variables in nextcss

### ISSUE THREAD

**Issue by IljaDaderko** [mxstbr/react-boilerplate#940]
I am trying to set some global variables in `App/styles.css` in a following way:

```
:root {
   --color-green: green;
}
```

with an initiative to re use it inside another components styles.css file i.e. using something like this in `H1/styles.css`

```
.h1 {
  color: var(--color-green);
}
```

this throws following warrning:

> variable '--color-green' is undefined and used without a fallback [postcss-custom-properties]

telling me I am not doing it right, maybe I need to take a different approach?

**Comment by edmelly** [comment]
@IljaDaderko from within `H1/styles.css`, are you importing your variable(s)? Something like:

    @import '../App/styles.css';

**Comment by IljaDaderko** [comment]
@edmelly ah, I assumed :root will make postcss parse it. So would you suggest creating separate variable file for these purposes and importing it where needed?

**Comment by edmelly** [comment]
@IljaDaderko Yup, exactly that: I have separate variable files for colours, spacing etc. and just import those into the individual component's `styles.css` file when they're required.

**Comment by sedubois** [comment]
I'm not familiar with PostCSS, CSS modules, etc, especially in conjunction with Webpack. Could you explain how to configure them in RBP to get variables such as `--color-green` to work? 😊 

They are found correctly in development but I get errors with `npm run build` (I added `@import` as suggested). 

```
⚠  variable '--color1' is undefined and used without a fallback [postcss-custom-properties]
```

/cc @edmelly

**Comment by gihrig** [comment]
Have you seen this  [#282 Comment](https://github.com/mxstbr/react-boilerplate/issues/282#issuecomment-234207231) ?

**Comment by sedubois** [comment]
Thanks! I was missing the bit about downgrading `postcss-import`.

I created https://github.com/mxstbr/react-boilerplate/pull/1080.
