### ISSUE TITLE
adding a directory with static files that get copied after building

### ISSUE THREAD

**Issue by lucidlemon** [mxstbr/react-boilerplate#941]
It would be nice if we had the possibility to have a folder (call it `static` or whatever) where we could place files that we need copied after building the project. Examples for these files include

* favicons
* robots.txt
* humans.txt
* google webpage tools html
* php files

In my current example I would love to use this boilerplate as a "child" of my Laravel PHP backend, so I would like to move everything from the build into the /public/ folder of laravel. However I can't use that if the rimraf removes every trace. And I don't want to use a subfolder for better URLs.

So the way react-redux-starter-kit approaches this is by a [static folder](https://github.com/davezuko/react-redux-starter-kit/tree/master/src/static). The contents of it simply get copied to the build directory after finishing the deploy process. Plain and simple.

I guess this is just a small matter of [webpack configuration](https://github.com/davezuko/react-redux-starter-kit/blob/0bde219574933922169e0290a6e5d2fdc6b47d1e/bin/compile.js#L19), but to be honest I always feel a bit lost in webpack configs.

I would love that functionality in this boilerplate, as it seems to be way more friendly for usage in general.

**Comment by mxstbr** [comment]
Thanks for submitting this issue!

In my opinion, the current way of doing it is fine. I appreciate you taking the time to submit the issue and the PR (!), I'm sure people that'll want to implement this behaviour have a great example implementation to go by. Thanks!

**Comment by paulintrognon** [comment]
And what is the "current way of doing it"? I looked at the docs (and the FAQ) and could not find how.

**Comment by lucidlemon** [comment]
place them straight into /app/ ? at least that's where max put his favicon.
