### ISSUE TITLE
Scrolls to top when liveloading CSS in Firefox

### ISSUE THREAD

**Issue by RuudBurger** [mxstbr/react-boilerplate#944]
Unconfirmed bug I found was #275 and that code suppose to fix it, but it didn't. I have a way to replicate it though.

- I only have this on Firefox (Chrome works fine)
- Only happens on the root component or the ones on the first level

I see a quick flicker when changing CSS, which I assume it because a whole component gets remounted. This doesn't happen in Chrome, which I think is faster in doing this, maintaining scroll position. So the in Firefox a pages goes from body height of 2000px -> 0px -> 2000px. And the scroll position gets reset when the height is 0px.

When changing individual smaller components, this doesn't happen because they don't influence the scroll height that much.

**Comment by gihrig** [comment]
@RuudBurger This has been discussed see #275 also [source](https://github.com/mxstbr/react-boilerplate/blob/master/app/app.js#L86)

I'm not sure if the fix from #275 creates a problem in production build, if you could check into that it would be helpful.

**Comment by RuudBurger** [comment]
Like i said. The fix mentioned doesnt work. I removed all the usescroll code, still have the same issue

**Comment by gihrig** [comment]
You're right, sorry 😦

**Comment by mxstbr** [comment]
This highly likely isn't something on our end if usescroll isn't the issue. I'm going to assume `react-hot-loader` v3 will fix this, if not, there isn't much we can do to fix it! Sorry!

**Comment by RuudBurger** [comment]
I figured it was on the HMR side, no worries. Will wait for an update and will develop in Chrome when working on the root components ;)
