### ISSUE TITLE
Incorrect debug line in stacktrace when running tests

### ISSUE THREAD

**Issue by jwyuen** [mxstbr/react-boilerplate#945]
## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I set up a really simple component with a test to demonstrate this issue.  I've also seen this issue when running tests on other components and the common theme is that it always seems to look at line 9:

http://imgur.com/a/PCpZq

I've done some googling and thought the issue might be related to using istanbul code coverage with karma but turning off code coverage doesn't seem to affect this at all.

https://github.com/karma-runner/karma/issues/1141

## Steps to reproduce

1) `git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git`
2) `npm run setup`
3) `npm run clean`
4) Create new component via `npm run generate` (code below)
5) removed linting step in pretest in package.json for convenience
6) run test via `npm run test:watch -- --grep "TestComponent"`

TestComponent:
```
/**
*
* TestComponent
*
*/

import React from 'react';


function TestComponent() {
  garbageToTriggerAnError

  return (

    <h1>hi</h1>
  );
}

export default TestComponent;
```

TestComponent test:
```
import TestComponent from '../index';

import expect from 'expect';
import { shallow } from 'enzyme';
import React from 'react';

describe('<TestComponent />', () => {
  it('renders a <TestComponent>', () => {

    console.log('here');


    const renderedComponent = shallow(
      <TestComponent />
    );
  });
});
```

# Versions

- Node/NPM: 6.5 / 3.10.3
- Browser: Chrome 51.0.2704 Kubuntu 16.04

**Comment by mxstbr** [comment]
We switched to a new code coverage method in the `dev` branch, please try doing it there, see if the issue still exists and comment again here. Thanks!

**Comment by jwyuen** [comment]
Yep this appears to be fixed on the latest dev branch (e83b1b29a39f5746a038bd6f8cd47f795cab8420)!  Many thanks for the quick reply and for making a great boilerplate!

**Comment by jwyuen** [comment]
On a slightly unrelated note, if the build is passing for the dev branch, can we reasonably assume it's stable enough for use?

**Comment by gihrig** [comment]
@jwyuen That is my assumption. But then I'm prepared to do a lot of testing and deal with issues by rolling back commits, etc. So far, I haven't encountered too many issues. There have been some, unfortunately I have not had the time to distill them down an issue I felt good about posting.

So sure, use the dev branch, but understand that, if you do, you are one of the beta testers :wink:
