### ISSUE TITLE
Webpack configuration for PostCSS

### ISSUE THREAD

**Issue by jskorepa** [mxstbr/react-boilerplate#947]
## Issue Type

- [ ] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

in internals/webpack/ there is webpack.dev.babel.js and webpack.prod.babel.js and both contain same postcssPlugins definition. Since they are the same shouldn't it be moved to webpack.base.babel.js?

I can submit PR for it.

**Comment by hew** [comment]
You may want different plugins for dev/prod.

**Comment by mxstbr** [comment]
I'm pretty sure we don't use `cssnano` (or at least not with the same config) in development. If we do, that's an error and should be fixed!

**Comment by jskorepa** [comment]
You don't use `cssnano` in development nor in production as far as I can see

[webpack.prod.babel.js](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L32-L41)
````
// In production, we minify our CSS with cssnano
  postcssPlugins: [
    postcssFocus(),
    cssnext({
      browsers: ['last 2 versions', 'IE > 10'],
    }),
    postcssReporter({
      clearMessages: true,
    }),
  ],
````

[webpack.dev.babel.js](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.dev.babel.js#L48-L57)
````
  // Process the CSS with PostCSS
  postcssPlugins: [
    postcssFocus(), // Add a :focus to every :hover
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true,
    }),
  ],
````

**Comment by mxstbr** [comment]
Huh, I swear we used to do that! Can you check history when and why that was removed?

**Comment by jskorepa** [comment]
Did not look through history but found [issue #126](https://github.com/mxstbr/react-boilerplate/issues/126)

**Comment by mxstbr** [comment]
Ah nice one, alright, would appreciate a PR merging that config! 🔥 very good catch!

**Comment by mxstbr** [comment]
Done by the amazing @jskorepa in #972!
