### ISSUE TITLE
Reducers execution accumulation problem!

### ISSUE THREAD

**Issue by mnemanja** [mxstbr/react-boilerplate#949]
Reducers get accumulated when using them.

I'm experiencing this in my project, but also tested it on the clean master branch.
Log the action and then switch pages between the Features and Home. You should be seeing the accumulation of the execution. 

For example the `action.type`'s that will be logged is `@@INIT` each time once but the `@@router/LOCATION_CHANGE` every time more and more.

Node v6.2.0
npm v3.10.6
Windows 10 - anniversary update

**Comment by goldo** [comment]
I think i'm having the same issue, I though it was coming from my route declarations, but I didn't take the time to try the master branch

**Comment by mxstbr** [comment]
That's definitely a bug – cc @justingreenberg who should know what's up here!

**Comment by justingreenberg** [comment]
i can confirm this is a bug... very bizarre. i will investigate

**Comment by mnemanja** [comment]
@justingreenberg any luck with this?

**Comment by Dattaya** [comment]
Does this have anything to do with `react-router-redux`? Because i see multiple `LOCATION_CHANGE` action, but only one `CHANGE_USERNAME` when I try to change a name.
![image](https://cloud.githubusercontent.com/assets/387256/18351422/ceed60f2-75e2-11e6-994b-e5cc80c64058.png)

**Comment by justingreenberg** [comment]
i'm sorry for the delay in getting around to this, i'm swamped this week. i believe reducer stacking can be simply fixed by checking if the key exists before assignment... ie

```js
// asyncInjectors.js ~ line 36...
if (!Object.hasOwnProperty(store.asyncReducers, name)) {
  store.asyncReducers[name] = asyncReducer
  store.replaceReducer(createReducer(store.asyncReducers))
}
```

i think there is a better solution tho, so i would like more time to research. i will put aside a few hours over the weekend to open a PR to address this either way

as an aside: while this definitely needs to be fixed, reducers are pure functions, so duplicate actions *shouldn't* affect state. in this case, impure console.log exposed the stacking issue

**Comment by goldo** [comment]
I can confirm it doesn't. I've been working on my project for 1 week without noticing that bug :)
Thanks for your help/time

—
Franck Achkouyan

**Comment by mnemanja** [comment]
@justingreenberg Thanks, I appreciate it.

**Comment by mnemanja** [comment]
Good job @justingreenberg

**Comment by maslianok** [comment]
@mxstbr @justingreenberg @mnemanja @goldo OMG, it's the weirdest bug that I've ever seen. It cost me two days to debug but I finally found the answer.

`store.replaceReducer` obviously replaces all reducers and triggers the @@INIT action.
But who repeats all previous actions? `replaceReducer` method doesn't have any logic for this!

And the answer is ......... Redux extension for Chrome 🎉 🎉 🎉  Unexpected, right? 😄 
Yes, try to switch it off and you will see that problem disappears.

So yes, seems that this extension listens for the @@INIT action and repeat all previous actions to make time machine work properly.

**Comment by phuochau** [comment]
Hi all,

I have the same problem. When I switch to another page, the reducer of new page will receive and process all previous actions.

![6b7b026f64a1a05e662c6d7e330b7ab4](https://cloud.githubusercontent.com/assets/1784243/20521831/ca083ffc-b0df-11e6-8c4f-3b976a14d740.png)

Anyone know how to fix it? Thanks
