### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined in prod

### ISSUE THREAD

**Issue by sourcesoft** [mxstbr/react-boilerplate#958]
I ran into a problem today I wanted to share.
My app was working for a week in dev mode with no errors but when I built it with no problems and tried to run it on local, it gives me:
````
Uncaught TypeError: Super expression must either be null or a function, not undefined:
````
I looked again over all my code for typos in class extends but the fact that it was happening only after build means that there's something wrong with packaging.

I changed dev-tools to inline in webpack config to inspect the error stack and it seems that redux-form was the source. I already patched and updated the exact issue https://github.com/mxstbr/react-boilerplate/issues/868 but it seems like to get fixed only in dev. after swapping
````
      'main',
      'jsnext:main',
````
lines it gets fixed in prod too, so the problem is still around. I think this might be relative to https://github.com/mxstbr/react-boilerplate/issues/950 fix but I haven't checked yet.

**Comment by samit4me** [comment]
Ran into the same issue. #952 also seems to resolve the issue.

Adding the line below to `app/reducers.js` causes the issue:
```Javascript
import { reducer as formReducer } from 'redux-form/immutable';`
```
Interestingly the line below does not cause this issue, _but then you have to write your own reducer to convert JS object to immutable_:
```Javascript
import { reducer as formReducer } from 'redux-form';`
```

**Comment by meilers** [comment]
@samit4me Thanks, same issue here. Can you show me an example of how to write my own reducer to convert the JS object (for redux-form)?

**Comment by samit4me** [comment]
@meilers That was almost 2 months ago now, so I'm struggling to remember, but I think `redux-form` fixed this in later versions. The reducer to convert the JS Object was something like the following:
```
import { fromJS } from 'immutable';
import { reducer as formReducer } from 'redux-form';

const immutableize = (reducer) => (state = {}, action) => fromJS(reducer(state.toJS(), action));
const immutableFormReducer = immutableize(formReducer);

...
```
[see this comment for further details](https://github.com/erikras/redux-form/issues/110#issuecomment-144839263)

**Comment by nndung179** [comment]
@sourcesoft solution worked great

**Comment by sourcesoft** [comment]
This seems to be happening again back to this issue https://github.com/erikras/redux-form/issues/1637

**Comment by danielo515** [comment]
On erikras/redux-form#1637 they are suggesting to change the order of preference of jsnex vs main at internals/webpack/webpack.base.babel.js. So they suggest going from 

```
mainFields: [
  'browser',
  'jsnext:main',
  'main',
]
```
to:

```
mainFields: [
  'browser',
  'main',
  'jsnext:main',
]
```

What is the impact of such change? I don't have much experience on that area but I'm afraid that it is not a good thing. Someone (@jacobk )mentioned lack of tree shaking.

A bit off-topic but, could someone point me to an example about how to manage the form submission using redux-form + react-boilerplate?
