### ISSUE TITLE
Where babel plugins should be set？

### ISSUE THREAD

**Issue by Losering** [mxstbr/react-boilerplate#959]
I'm setting it up now.
 ```
 "babel": {
    "presets": [
      [
        "es2015",
        {
          "modules": false
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-inline-elements",
          ["antd",
              [
                {
                  "libraryName": "antd",
                  "libraryDirectory": "lib",
                  "style": true
                },
                {
                  "libraryName": "antd-mobile",
                  "libraryDirectory": "component"
                }
              ]
          ]
        ]
      }
    }
  },

```
**But Error
 Module not found: Error: Can't resolve 'antd-mobile' in '/Users/liuyi/Work/nevermore/app/containers/Editor'**

**Comment by gihrig** [comment]
Sorry I don't have an answer, but here's some ideas:

1. antd was discussed in #755. I'm not sure there's an answer is there but [one user](https://github.com/mxstbr/react-boilerplate/issues/755#issuecomment-242629549) said he had it working.
2. Check out this [Gitter chat](https://gitter.im/mxstbr/react-boilerplate?at=57bf25edf066bd731b4a52e9) and ask there if you don't find an answer.
