### ISSUE TITLE
Hot-Reload not working on v3.0.0

### ISSUE THREAD

**Issue by amorino** [mxstbr/react-boilerplate#96]
I installed both versions (master and v3.0.0). Hot-reload works perfect on master version but didn't work on v3.0.0 using MacOS. I tested on 2 computers with 2 different node versions: v4.1.2 and v5.4.1. The results went equal on both computers.

I deleted node_modules folder between installations and used a clean setup. 

The only output I get on v3.0.0 is: 
>[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
>[HMR]  - 306

Module 306 is HomePage.react.js component, which should be reloadable.

Thanks!

**Comment by mxstbr** [comment]
Very interesting, I'll have a look later, thank you very much for the detailed bug report!

**Comment by amorino** [comment]
I haven't found the solution but `babel-preset-react-hmre` don't match between versions. It is not present in v3.0.0. That may be the answer?

Cheers

**Comment by amorino** [comment]
So, I found the solution: the `babelQuery` in webpack.base.babel.js if not bringing the `babelQuery` from dev because of a typo (it brings `query` instead of `babelQuery`). I will make a PR for that, what I found weird is that you had hot-reload with that config.

**Comment by mxstbr** [comment]
Closed by #99, thanks so much @amorino!

**Comment by figitaki** [comment]
I'm still able to replicate this issue on the latest master branch. Nothing is hot reloading properly, reducers, routes or components.
