### ISSUE TITLE
Can't find variable: IntlPolyfill

### ISSUE THREAD

**Issue by billyshena** [mxstbr/react-boilerplate#960]
Hi everyone !
I'm currently testing the boileplate on Safari and sometimes when I refresh the page, I get this error: "ReferenceError: Can't find variable IntlPolyfill" (only when using /build folder).
I guess the problem is in which order the scripts are loaded after webpack compiles the production build folder.
Any thoughts?

Update: Adding the Intl polyfill `<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-US,Intl.~locale.fr-FR"></script>` in my index.html solves the issue, but don't know why I even need to do that.

Best,

**Comment by kachkaev** [comment]
Did you start your project after https://github.com/mxstbr/react-boilerplate/pull/805 and https://github.com/mxstbr/react-boilerplate/pull/906 were merged? Those PRs seem to address the error you're experiencing.

**Comment by billyshena** [comment]
#805 fixed the issue, thanks @kachkaev !
