### ISSUE TITLE
Integrate react-virtualized - babelHelpers is not defined

### ISSUE THREAD

**Issue by khoaisohd** [mxstbr/react-boilerplate#962]
Hi, I want to use `react-virtualized`: 
```
npm install react-virtualized --save
```

Then include this library
```
import { VirtualScroll } from 'react-virtualized';
```

I had an error:
```
ArrowKeyStepper.js Uncaught ReferenceError: babelHelpers is not defined
```

Do you guys have any idea about that?

**Comment by timgaines** [comment]
@khoaisohd 

I ran into this as well. The fix seems to be:

In `internals/webpack/webpack.base.babel.js`

Make sure the mainFields are in the order below:

```js
mainFields: [
  'main',
  'jsnext:main',
],
```

**Comment by khoaisohd** [comment]
Thanks man

**Comment by mxstbr** [comment]
This is an issue with what `react-virtualized` specifies in its `jsnext:main` field in the `package.json`. cc @bvaughn

The above is a temporary fix that'll make it work, but it'll lose you tree shaking support for ES6 modules.

**Comment by bvaughn** [comment]
Thanks for the tag, @mxstbr!

> They have some non-standard code in their source version that we don't have the correct babel plugins for, I think.

The `jsnext:main` target currently depends on the following `babelHelpers` methods:
* classCallCheck
* createClass
* extends
* inherits
* objectWithoutProperties
* possibleConstructorReturn

The babel settings for that target look fairly similar to this boilerplate's settings:
```js
"es": {
  "presets": [
    "es2015-rollup",
    "react",
    "stage-0" // Recently changed to stage-1
  ]
},
```

I'm not a Babel configuration expert so I'm not sure if that's non-standard or what the best solution is. I'm in China for the next week and so I'm stuck behind a slow VPN. I'll try to give the boilerplate + react-virtualized combo a spin and see what I can find.

**Comment by bvaughn** [comment]
Thanks to @raizyr, `react-virtualized` version 7.24.3 should now play nicely with `react-boilerplate`!
