### ISSUE TITLE
npm run analyze currently not working because webpack config extend from base

### ISSUE THREAD

**Issue by chaintng** [mxstbr/react-boilerplate#964]
I try to analyze the build file by running

`npm run analyze`

However, it's currently not working.
it only show

```
{
  "errors": [],
  "warnings": []
}
```

in `stats.json` file

I found that after remove extend from `webpack.base.babel` in this line
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L13

In that show the expected result.

**Comment by mxstbr** [comment]
Hmm, interesting. Would you mind digging in which part of the `webpack.base.babel.js` breaks this and submitting a PR fixing this? Thank you!

**Comment by amilajack** [comment]
@chaintan17 did you fix this? If you did, please close this.

**Comment by chaintan17** [comment]
no, it doesn't get fix yet.

**Comment by chaintan17** [comment]
@mxstbr can i disable this parameter ?
https://github.com/mxstbr/react-boilerplate/pull/1026

I can't find it in webpack document, not sure what does it do.

**Comment by mxstbr** [comment]
Fixed in #1032 by the amazing @chaintng
