### ISSUE TITLE
Question: How to show confirmation message when user clicks browser back button

### ISSUE THREAD

**Issue by andylhansen** [mxstbr/react-boilerplate#965]
How would I go about showing a confirmation message to the user when they click their browser's back button? I have a form that the user edits and can save or cancel. If the user clicks the back button, I want to warn the user that their changes will be lost and give them a chance to stay on the page instead of actually going back.
A plain javascript example of what I want to do is here: http://jsfiddle.net/andylhansen/0rdm3m98/

**Comment by justingreenberg** [comment]
when using jsx routes you can register an `onLeave` hook directly on the `Route` component, but since we are using plain route objects you'll want to use `withRouter` utility to inject the router instance and route object and set hook at runtime (return false to cancel the navigation) ie...

```js
import { Link, withRouter } from 'react-router'

function Demo({ router, route }) {
  router.setRouteLeaveHook(route, () => window.confirm('you sure?'))
  return <Link to='/elsewhere'>i am outta here</Link>
}
```

**Comment by andylhansen** [comment]
Thanks for the quick reply. So to clarify, "Clingy" is a react component? So I just have to include it somewhere inside my container.
`<MyPage>
    <Clingy />
</MyPage>`

**Comment by justingreenberg** [comment]
@andykenward no problem! you need access to the router and route instances... in the case above it would be whatever component(s) that are returned by `getComponent` so probably container

withRouter is just a utility around context, so vanilla approach works anywhere that has access...

```js
import { routerShape } from 'react-router'
// route injected by parent Route component
// router instance is accessed via context
const Clingy = ({route}, {router}) => {
  router.setRouteLeaveHook(route, () => window.confirm('you sure?'))
  return <span>{"don't leave me"}</span>
}
Clingy.contextTypes = { router: routerShape }
```

here's a fiddle implementing both approaches... http://jsbin.com/gogadabato/1/edit?js,output

**Comment by andylhansen** [comment]
I am still having one problem with this. It successfully prevents the page from going back, but the url in the browser still changes. Is there a way to prevent the browser url from changing to show the previous page?
