### ISSUE TITLE
Local webfonts and development tunneling 

### ISSUE THREAD

**Issue by andylhansen** [mxstbr/react-boilerplate#969]
This issue here describes how to use local web fonts while running the development server: https://github.com/mxstbr/react-boilerplate/issues/443

The solution given, which is to set an absolute publicPath, is not compatible with tunneling, such as ngrok. Has anyone found another solution that doesn't involve using an absolute url?

**Comment by Kielan** [comment]
@andylhansen can you give a more detailed description of your output, what you are getting as an error in the console and what effects you are having I think I might be in the same position using local webfonts, was not a problem until I decided to update things and now I have this same issue locally.

P.S. personally I think this is more than a question maybe a real issue to adress about webpack and local webfonts in development.
