### ISSUE TITLE
RFC: Update tests to use Jest/Enzyme

### ISSUE THREAD

**Issue by justingreenberg** [mxstbr/react-boilerplate#970]
Awesome testing and full coverage are core to the mission of **react-boilerplate**, always on the mind of contributors. [Jest](https://facebook.github.io/jest/) v15 ([release blog post](https://facebook.github.io/jest/blog/2016/09/01/jest-15.html)) is changing the game. With snapshot testing, built in coverage reporting, and huge performance gains (a [concurrent reporter is on the way](https://github.com/facebook/jest/pull/1480))—the react community seems to be coming home to Jest. From what I can tell, it integrates nicely with [webpack v2](https://github.com/facebook/jest/blob/master/docs/TutorialWebpack.md#webpack-2) and enzyme for mounted components. as @sotojuan [recommended, it really seems to be the right fit](https://github.com/mxstbr/react-boilerplate/issues/192#issuecomment-245941215) for this project. Please provide thoughts/feedback!

**Comment by gihrig** [comment]
A truly "usable" test feature would be very welcome! When working in TDD mode (watching test results as I build mod components) the current system is just too slow. Worse than it being slow, is that **_I_** have time check email, twitter, Gitter, issues, etc., and often don't get back "for some time" ;-)

Even though react-boilerplate is a front-end project, I don't see the need to run Karma in watch mode. It would be nice to have as a separate test, but in my (limited) experience, Karma is more overhead than it's worth.

I would really love to see a PR or fork that replaces the current set up with something orders of magnitude faster.

**Comment by mxstbr** [comment]
I 100% agree, let's switch to Jest! Would massively appreciate a PR for this!

*Not even convinced we need Enzyme, but will include it if a good use case can be found.*

(notifying @cpojer, might be interesting for him)

**Comment by cpojer** [comment]
@dmitriiabramov actually did this in a branch: https://github.com/dmitriiabramov/react-boilerplate/commits/jest did he never send the PR for it? :D

**Comment by gihrig** [comment]
No PR or commit for Jest...

**Comment by cpojer** [comment]
We were talking about this right before Jest 15 but then probably put our heads down on the release and forgot.

**Comment by mxstbr** [comment]
Woah, no way! That could save us so much time! @dimitriiabramov would you mind updating your branch and submitting a PR against `dev`?

**Comment by dmitriiabramov** [comment]
hey @mxstbr 
absolutely! i can work on that
i remember i had a few things that blocked me from submitting a PR.
let me open the PR and we can start the discussion there :)

**Comment by dmitriiabramov** [comment]
https://github.com/mxstbr/react-boilerplate/pull/980

**Comment by mxstbr** [comment]
Done in #980 by the amazing @dmitriiabramov!
