### ISSUE TITLE
Template for connect() missing null for mapStateToProps

### ISSUE THREAD

**Issue by tobyl** [mxstbr/react-boilerplate#971]
I *believe* this is a bug, apologies if not.

With the latest repo, I run `npm run generate` and specify no actions/reducers and no sagas.

The resulting line at the bottom of the template is:

`export default connect(mapDispatchToProps)(ConfirmPasswordResetPage);`

I *believe* it should be:

`export default connect(null, mapDispatchToProps)(ConfirmPasswordResetPage);`

Again, apologies if this is submitted in error.

**Comment by gihrig** [comment]
@tobyl It would appear that you are correct. React-redux connect() [docs](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) list the the first parameter, mapStateToProps as optional, but don't specify how to handle the first param if it's not used.

There's an open PR #891 on this issue, would you be able to test it out and let us know how it works for you?

Thanks for reporting!

**Comment by gihrig** [comment]
Fixed by #973
