### ISSUE TITLE
Howto serve static content

### ISSUE THREAD

**Issue by janroesner** [mxstbr/react-boilerplate#984]
I have a use case where in production I'd like to not only serve the application bundle, but also a dynamically growing collection of .json and .png files. The app reads the .json files and uses references to the .png files to update some `img` tag's `src` attribute.

Rendering images properly only works for me when I either reference an externally served image, or `require` an image in my component and apply this [change](https://github.com/mxstbr/react-boilerplate/issues/370).

So my question is, is there a way to have contents of a `static` folder to be served via the webpack dev server w/o going through the packaging process, so that an image at `/static/foobar.png` can actually be referenced as `<img src="/static/foobar.png">` or later on `<img src="{this.props.image}">`?

**Comment by nickwhite917** [comment]
@janroesner I have been researching this issue, and have found the following resources (I'm looking into how to apply them here): 
[Stackoverflow question that helped me](http://stackoverflow.com/questions/27639005/how-to-copy-static-files-to-build-directory-with-webpack)
[Source github/webpack/file-loader](https://github.com/webpack/file-loader)
[Source github/docs/using-loaders](http://webpack.github.io/docs/using-loaders.html)
Please let me know what your thoughts are, as I am trying to resolve this in the best way possible! :)

**Comment by andykenward** [comment]
@janroesner you can simply copy a folder of `/static` into the `/build` folder. It will get served by the node express server

In production mode it gets served by this
https://github.com/mxstbr/react-boilerplate/blob/2852c09b4d0851ce46eea3dc55517f67fd1ab80d/server/middlewares/frontendMiddleware.js#L54

Just remember that there isnt a handler for 404 returns from the node express server. So if you load a image that doesnt exist you wont actually get an error but the `index.html` returned.

**Comment by janroesner** [comment]
@andykenward: Thanks for your suggestion. Putting a folder into `build` is not an option, since I do that in production anyway and put an Nginx in front to deliver the application bundle, as well as my additional static files. I'd need something, that mimics that behavior in dev mode already.

@nickwhite917: I guess it is definitely more of a webpack task, yes. I'll look into the plugins you suggested, and try to come up with a working config for it. Thanks for bringing this up.

**Comment by janroesner** [comment]
@nickwhite917: I doubt, this is the "best way possible", but after having a look at [your so link](http://stackoverflow.com/questions/27639005/how-to-copy-static-files-to-build-directory-with-webpack) it was just obvious to me, that using `copy-webpack-plugin` is the way to go for me. After installing the plugin I just created a `static` in the boilerplate's root dir and added the plugin config to `webpack.dev.babel.js`:

```Javascript
const CopyWebpackPlugin = require('copy-webpack-plugin');
...
const plugins = [
  new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
  new webpack.NoErrorsPlugin(),
  new HtmlWebpackPlugin({
    inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    templateContent: templateContent(), // eslint-disable-line no-use-before-define
  }),
  [++]new CopyWebpackPlugin([{ from: 'static' }]),
];
```

**Comment by kopax** [comment]
@mxstbr I am new tester for this project.
After watching your video, I really thought you got the good way to do and wanted a try your framework, thanks for sharing all that and hope it will goes fine.
Deeper explanation on how works the core boilerplate would have been appreciated. 

@janroesner I needed to add some static components for my design, how did you manage to serve your static content?

I have tried to install over the latest pull of react-boilerplate the CopyWebpackPlugin but this doesn't work for me 
    $ npm install --save-dev copy-webpack-plugin cheerio

    ├── UNMET PEER DEPENDENCY cheerio@0.22.0
    └── copy-webpack-plugin@3.0.1 

Is there a new official way to do so?

**Comment by Altiano** [comment]
@janroesner Do I need to make the change in `webpack.prod.babel.js` too?

**Comment by kopax** [comment]
@Altiano looking at my edit on last comment, this isn't very clear to me either.

**Comment by Altiano** [comment]
@kopax yes, you need to make the change in `webpack.prod.babel.js` too. I just tested it

**Comment by kopax** [comment]
@Altiano Does this also means the static folder has to be included in the distribution bundle with the build folder ?

**Comment by mxstbr** [comment]
Closing this for now, since this issue is quite old. Feel free to discuss on!

**Comment by Altiano** [comment]
@kopax Yes, I think so

**Comment by Altiano** [comment]
@janroesner How do you solve `background-image: url(/image.jpg)` relative path issue ?

**Comment by eric-burel** [comment]
Hi,
From my point of view, the proposed solution is not quite clear. Could this be documented ? Serving static files is a basic feature (almost the first thing I needed when starting to use react-boilerplate), eventhough it's more a backend task than a React task.

Maybe the express server could be configured to handle a "public" or "static" folder by default ?

**Comment by nenti** [comment]
I tried to implement the soludtion in dev.babel.js. And on build it acturally copies the files. But they can't be reached from the browser. Can someone please post an example setup of his project here.

**Comment by nhanco** [comment]
If we use nodejs server to serve static file that will be slowly compare with nginx way. But i dont know how to try with nginx. This is my config but all request was send to nodejs then i still cant serve static file :(.
`#user nobody;
worker_processes 1;

#pid logs/nginx.pid;


events {
worker_connections 1024;
}


http {
include mime.types;
default_type application/octet-stream;
sendfile on;
keepalive_timeout 65;
gzip on;
gzip_comp_level 6;
gzip_vary on;
gzip_min_length 1000;
gzip_proxied any;
client_max_body_size 20M;
server {
listen 80;
server_name test.dev;
server_tokens off;
location /assets/* {
alias C:\Nhan\node\react\static;
}
location / {
try_files $uri @nodejs;
}


location /sw.js {
add_header Cache-Control "no-cache";
proxy_cache_bypass $http_pragma;
proxy_cache_revalidate on;
expires off;
access_log off;
}

location @nodejs {
proxy_pass http://localhost:3000;
proxy_http_version 1.1;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;

}


}

}

`

**Comment by chrismv48** [comment]
Not sure if this is still relevant, but I was able to solve this by adding:
`app.use(express.static('public'))` (where public is your static assets directory)
to express (`server/index.js`)

Now I can reference images like so: `<img src="/uploads/character/display_image/1/people.jpeg" height="200">`

**Comment by m-brantheim** [comment]
@chrismv48 Where do you put the public directory? I read in the Express guide that it was relative to where the node server is launched from... So I put it in the server directory but I can't get it to work for some reason.

**Comment by m-brantheim** [comment]
Never mind, found by trial and error that it works in the root of the project.

**Comment by daaain** [comment]
I had to add `app.use('/public', express.static('public'));` to make it work, ie specify the path where the static files are served at.

**Comment by mikehedman** [comment]
An important note here - you have to place your line with `express.static` **ABOVE** the lines in server/index.js where the react-boilerplate supplied middleware is invoked.  So, you should have:
`
app.use(express.static(path.resolve(process.cwd(), 'static')));
setup(app, {
  outputPath: resolve(process.cwd(), 'build'),
  publicPath: '/',
});
`
instead of 
`
setup(app, {
  outputPath: resolve(process.cwd(), 'build'),
  publicPath: '/',
});
app.use(express.static(path.resolve(process.cwd(), 'static')));
`
If you do it the second way, the request will have been handled before it gets passed to the static handler.
