### ISSUE TITLE
Setup failed on windows 10  x64 with nodejs 6.5.0

### ISSUE THREAD

**Issue by vanloswang** [mxstbr/react-boilerplate#987]
The error info is as following:
```bash
PS E:\vanlos\DevWS\react-boilerplate-3.1.0> npm run setup

> react-boilerplate@3.1.0 presetup E:\vanlos\DevWS\react-boilerplate-3.1.0
> npm i chalk shelljs

react-boilerplate@3.1.0 E:\vanlos\DevWS\react-boilerplate-3.1.0
+-- chalk@1.1.3
+-- UNMET PEER DEPENDENCY eslint-plugin-import@1.12.0
+-- shelljs@0.7.3
`-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.15

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@10.0.1 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint@^3.3.1 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN react-addons-test-utils@15.3.1 requires a peer of react@^15.3.1 but none was installed.
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.

> react-boilerplate@3.1.0 setup E:\vanlos\DevWS\react-boilerplate-3.1.0
> node ./internals/scripts/setup.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'E:\vanlos\DevWS\react-boilerplate-3.1.0\internals\scripts\setup.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.1.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.1.0 setup script 'node ./internals/scripts/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vanlos\DevWS\react-boilerplate-3.1.0\npm-debug.log
```

**Comment by gihrig** [comment]
> Error: Cannot find module 'E:\vanlos\DevWS\react-boilerplate-3.1.0\internals\scripts\setup.js'

Seems you have run `setup` on this clone before? It's self-deleting, so you can only run it once. That's done to avoid destroying an existing project.

What happens if you just run `npm install`?

**Comment by vanloswang** [comment]
@gihrig 
PS E:\vanlos\DevWS\react-boilerplate-3.1.0> npm install

> react-boilerplate@3.1.0 preinstall E:\vanlos\DevWS\react-boilerplate-3.1.0
> npm run npmcheckversion


> react-boilerplate@3.1.0 npmcheckversion E:\vanlos\DevWS\react-boilerplate-3.1.0
> node ./internals/scripts/npmcheckversion.js


> react-boilerplate@3.1.0 postinstall E:\vanlos\DevWS\react-boilerplate-3.1.0
> npm run build:dll


> react-boilerplate@3.1.0 build:dll E:\vanlos\DevWS\react-boilerplate-3.1.0
> node ./internals/scripts/dependencies.js

Building the Webpack DLL...
Hash: 98d9576b4031608da393
Version: webpack 2.1.0-beta.15
Time: 5050ms
                      Asset     Size  Chunks             Chunk Names
reactBoilerplateDeps.dll.js  2.61 MB       0  [emitted]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 2.34 MB [rendered]
  [658] dll reactBoilerplateDeps 12 bytes {0} [built]
     + 662 hidden modules
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@10.0.1 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint@^3.3.1 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN react-addons-test-utils@15.3.1 requires a peer of react@^15.3.1 but none was installed.
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.

**Comment by gihrig** [comment]
OK, no ERRORs only WARNings. Those are normal. Does the project build with `npm start` and load the example app in the browser?

**Comment by vanloswang** [comment]
@gihrig Yes, I can visit the example app now. But howto visit structor ui?

**Comment by vanloswang** [comment]
Already access structor now, close this issue.
