### ISSUE TITLE
test the generated output in an automated way

### ISSUE THREAD

**Issue by peter-mouland** [mxstbr/react-boilerplate#988]
## Issue Type

- [ ] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

new es-lint rules have been added which cause some generated files to fail testing.

The generators, and the files they create, should be included in the test suite in order to ensure they are kept up to date with future changes.  i.e. it would be good to automatically generate a set of files and test them (for linting at a minimum).

## Steps to reproduce

1. `npm run generate`
2. generate a new container
3. `npm run lint`

**Comment by gihrig** [comment]
@peter-mouland So, are you working on this? Do you need help with anything?

**Comment by peter-mouland** [comment]
I'm happy to give it a go, but I wouldn't let this block v3.2.

If you do feel it's a blocker, then probably best someone else take over as i'm not sure when i'll get to finish it.

**Comment by gihrig** [comment]
That's cool. I'm thinking it's likely a pretty simple task. 

As a starter, if you generate a container and locate an error, then do a whole directory search in the ~/internals/generators/container directory for the problem snippet you should be able spot the location responsible for the errant code.

The files of interest are the *.js.hbs files. These templates are in [Handlebars](http://handlebarsjs.com/) format which is pretty simple.

I think if you create containers and components answering 'Yes' for all available options you stand a pretty good chance of hitting all the problem areas.

I'm in Los Angeles (GMT  -8) so I'm about done for the day (midnight here) and tomorrow I'll be out in the morning, but I'll check in as often as I can, so feel free to ask any questions that come up.

As for blocking 3.2, it would be nice to have, but the error as it is now is easy to fix in the generated code. I'll let @mxstbr decide to release or wait.

**Comment by peter-mouland** [comment]
ok, well thats a good guide, i'll take the approach of 'yes' to all things rather than coming up with generated content for every set of options.
