### ISSUE TITLE
Generated styles in Component stylelint-disabled?

### ISSUE THREAD

**Issue by creat-or** [mxstbr/react-boilerplate#989]
When I generate a Component/Container the .css rule always has a `/* stylelint-disable */` rule attached. Is this only to pass tests in the template-file or is this on purpose?

https://github.com/mxstbr/react-boilerplate/blob/ae2a53188c164c05d546f78d3d19774ea1f9304b/internals/generators/container/styles.css.hbs

**Comment by gihrig** [comment]
>  Is this only to pass tests in the template-file or is this on purpose?

That's just to avoid lint errors on newly generated components. Remove it when you begin adding styles.
