### ISSUE TITLE
Nesting containers

### ISSUE THREAD

**Issue by noquepoaqui** [mxstbr/react-boilerplate#990]
I would love to nest a container into another so that i don't end up with loads of code handled by a main page of the application. I feel all this logic should be distributed into lower level containers, but i can't find the best approach to do this. The idea is to have a main container using several containers, each of them with its own logic, reducers, actions, etc, so that the main container doesn't get too hard to manage.

My best approach at this point would be to: 
- create a **specific selector** linking both the mainContainer and the nestedContainer, 
- making the mainContainer reducer **include the nested containers reducers** into the state and 
- **redux.connecting the nested containers** inside the componentWillMount function of the mainContainer. 

I feel the process is overcomplicated. Am I missing something? Is there a better way to do this?

**Comment by jwyuen** [comment]
I've used the solution presented [here](https://github.com/mxstbr/react-boilerplate/issues/547) but I would also like to know if there's a better practice for this scenario....

**Comment by jwyuen** [comment]
Actually I should say it was more wired up like this (thanks to @wullaski on gitter):

```
{
path: '/search',
name: 'taskSearchPage',
getComponent(nextState, cb) {
const importModules = Promise.all([
System.import('containers/TaskSearchPage/reducer'),
System.import('containers/TaskSearchPage/sagas'),
System.import('containers/TaskSearchPage'),
System.import('containers/ClientSelect/reducer'),
System.import('containers/ClientSelect/sagas'),
]);
    const renderRoute = loadModule(cb);

    importModules.then(([
      reducer, 
      sagas, 
      component, 
      clientSelectReducer, 
      clientSelectSagas,
    ]) => {
      injectReducer('taskSearchPage', reducer.default);
      injectReducer('clientSelect', clientSelectReducer.default);
      injectSagas(sagas.default);
      injectSagas(clientSelectSagas.default);
      renderRoute(component);
    });

    importModules.catch(errorLoading);
  },
},
```

**Comment by noquepoaqui** [comment]
Looks good! I'm going to try this solution. I was using another solution but it was a bit muddy.

**Comment by TCatshoek** [comment]
This is exactly what I was looking for except for one thing. It doesn't seem to support rendering multiple components at the same time. Any idea what the best way to do that is? Multiple calls to renderRoute don't work for me.

**Comment by noquepoaqui** [comment]
I would prepare a container containing those components...

**Comment by TCatshoek** [comment]
Sorry, I meant containers where I said components. I have a route which I'd like to render two containers from. This is what I have now: 
```javascript
  getComponent(nextState, cb) {
            const importModules = Promise.all([
              System.import('containers/ProjectBarContainer/reducer'),
              System.import('containers/ProjectBarContainer/sagas'),
              System.import('containers/ProjectBarContainer'),
              System.import('containers/UploadManager/reducer'),
              System.import('containers/UploadManager/sagas'),
              System.import('containers/UploadManager'),
            ]);

            const renderRoute = loadModule(cb);

            importModules.then(([projectBarReducer, projectBarSagas, projectBarComponent,
                                 uploadReducer, uploadSagas, uploadComponent]) => {
              injectReducer('uploadManager', uploadReducer.default);
              injectSagas(uploadSagas.default);
              injectReducer('projectBarContainer', projectBarReducer.default);
              injectSagas(projectBarSagas.default);
              renderRoute(projectBarComponent);
              //renderRoute(uploadComponent); // This is what I'd like to be able to do
            });
          },
```

Instead of rendering the uploadComponent (which is actually a container) from there, I put it in the render method of the projectBarComponent (which is a container too). It works, but I feel it's not the neatest way to do it. 

Of course you could just make a single container and do everything from there, but I'd like to be able to separate the logic of the two. I'm still kinda new to this boilerplate and react in general, so forgive me if there is something obvious I'm missing.

**Comment by jwyuen** [comment]
It sounds like your question is more about structuring your page?  I'm not sure what exactly project bar is supposed to do, but it almost seems like you should have another container that's the glue of the two.... but I might be not understanding your question completely (I'm also relatively new to react ecosystem).

**Comment by TCatshoek** [comment]
I think I found a solution! Check out the `getComponents` function described here: https://github.com/ReactTraining/react-router/blob/master/docs/API.md

It allows you to specify multiple components/containers which are then available as props to their parent route, so you were right about needing another 'glue' container. Thanks!

**Comment by lsanders** [comment]
Sounds like there's still some discussion left on the best approach here, but it would be great if the [FAQ](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md#non-route-containers) got updated because people seem to stubble here a lot.

And to be honest, I don't quite understand how the approach recommended by the FAQ (having the route reducer delegate to the nested container's reducer) helps code-splitting; doesn't this just couple the route container to the nested containers action types, requiring them to be added to both reducers?

**Comment by Marinolinderhof** [comment]
Same issue? #547 cause i do have the same problem.

**Comment by tblazina** [comment]
@TCatshoek could you elaborate on how you've used getComponents? I'm quite a newbie and I'm unable to follow from the API documentation.

**Comment by mxstbr** [comment]
I'll be building a new example soon-ish that'll showcase this, until then I think the comments here have added enough information to fix your app specific issues! Cheers!
